/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/sim1/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const SIM1_SEGMENTS = [] as const;
export const SIM1_RUBRICS = {} as const;
export const SIM1_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
