import type { HorizonteCopy } from '../boardTypes';

export const SIM1_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  less: { role: 'action', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  noRun: { role: 'data', 'en-US': 'None yet', 'es-MX': 'Ninguno aún', 'pt-BR': 'Nenhum ainda' },
  yes: { role: 'data', 'en-US': 'Yes', 'es-MX': 'Sí', 'pt-BR': 'Sim' },
  no: { role: 'data', 'en-US': 'No', 'es-MX': 'No', 'pt-BR': 'Não' },
  total: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  colMeasure: { role: 'data', 'en-US': 'Measure', 'es-MX': 'Medida', 'pt-BR': 'Medida' },
  colValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  chanceOf: { role: 'data', 'en-US': '{a} in {b} ({p})', 'es-MX': '{a} de cada {b} ({p})', 'pt-BR': '{a} em cada {b} ({p})' },

  runCoin: { role: 'body', 'en-US': 'Number of flips', 'es-MX': 'Número de lanzamientos', 'pt-BR': 'Número de lançamentos' },
  runDie: { role: 'body', 'en-US': 'Number of rolls', 'es-MX': 'Número de tiradas', 'pt-BR': 'Número de jogadas' },
  runSpinner: { role: 'body', 'en-US': 'Number of spins', 'es-MX': 'Número de giros', 'pt-BR': 'Número de giros' },
  runBall: { role: 'body', 'en-US': 'Number of balls', 'es-MX': 'Número de bolas', 'pt-BR': 'Número de bolas' },
  runWalk: { role: 'body', 'en-US': 'Number of walks', 'es-MX': 'Número de caminatas', 'pt-BR': 'Número de caminhadas' },
  runResample: { role: 'body', 'en-US': 'Number of resamples', 'es-MX': 'Número de remuestreos', 'pt-BR': 'Número de reamostragens' },
  levelSlider: { role: 'body', 'en-US': 'Confidence level', 'es-MX': 'Nivel de confianza', 'pt-BR': 'Nível de confiança' },
  sizeSlider: { role: 'body', 'en-US': 'Sample size', 'es-MX': 'Tamaño de muestra', 'pt-BR': 'Tamanho da amostra' },

  faceHeads: { role: 'data', 'en-US': 'Heads', 'es-MX': 'Cara', 'pt-BR': 'Cara' },
  faceTails: { role: 'data', 'en-US': 'Tails', 'es-MX': 'Cruz', 'pt-BR': 'Coroa' },
  shareName: { role: 'data', 'en-US': 'Share of trials in the event', 'es-MX': 'Proporción de ensayos en el evento', 'pt-BR': 'Proporção de tentativas no evento' },
  tallyName: { role: 'data', 'en-US': 'Tally of each outcome', 'es-MX': 'Cuenta de cada resultado', 'pt-BR': 'Contagem de cada resultado' },
  chanceStatus: { role: 'data', 'en-US': 'Trials: {n}. In the event: {h}. Share: {s}. Chance: {c}', 'es-MX': 'Ensayos: {n}. En el evento: {h}. Proporción: {s}. Probabilidad: {c}', 'pt-BR': 'Tentativas: {n}. No evento: {h}. Proporção: {s}. Chance: {c}' },
  chanceNone: { role: 'data', 'en-US': 'No trials yet. Chance: {c}', 'es-MX': 'Aún no hay ensayos. Probabilidad: {c}', 'pt-BR': 'Ainda não há tentativas. Chance: {c}' },
  chanceGoal: { role: 'data', 'en-US': 'Goal: at least {n} trials, within {t} points of the chance', 'es-MX': 'Meta: al menos {n} ensayos, a {t} puntos o menos de la probabilidad', 'pt-BR': 'Meta: pelo menos {n} tentativas, a até {t} pontos da chance' },
  tableCaptionTally: { role: 'heading', 'en-US': 'Tally of each outcome', 'es-MX': 'Cuenta de cada resultado', 'pt-BR': 'Contagem de cada resultado' },
  tableCaptionStops: { role: 'heading', 'en-US': 'Share at each stop', 'es-MX': 'Proporción en cada parada', 'pt-BR': 'Proporção em cada parada' },
  colOutcome: { role: 'data', 'en-US': 'Outcome', 'es-MX': 'Resultado', 'pt-BR': 'Resultado' },
  colTimes: { role: 'data', 'en-US': 'Times', 'es-MX': 'Veces', 'pt-BR': 'Vezes' },
  colInEvent: { role: 'data', 'en-US': 'In the event', 'es-MX': 'En el evento', 'pt-BR': 'No evento' },
  colShare: { role: 'data', 'en-US': 'Share', 'es-MX': 'Proporción', 'pt-BR': 'Proporção' },
  colTrials: { role: 'data', 'en-US': 'Trials', 'es-MX': 'Ensayos', 'pt-BR': 'Tentativas' },
  metRun: { role: 'body', 'en-US': 'Your run settled close to the chance.', 'es-MX': 'Tu serie se asentó cerca de la probabilidad.', 'pt-BR': 'Sua série se estabilizou perto da chance.' },
  hintRun: { role: 'body', 'en-US': 'Not yet. More trials make the share steadier.', 'es-MX': 'Aún no. Con más ensayos la proporción se estabiliza.', 'pt-BR': 'Ainda não. Com mais tentativas a proporção se estabiliza.' },

  pegsName: { role: 'data', 'en-US': 'Pegs and the last ball', 'es-MX': 'Clavijas y la última bola', 'pt-BR': 'Pinos e a última bola' },
  pathName: { role: 'data', 'en-US': 'Path of the last walk', 'es-MX': 'Camino de la última caminata', 'pt-BR': 'Caminho da última caminhada' },
  binsName: { role: 'data', 'en-US': 'Balls in each bin', 'es-MX': 'Bolas en cada casillero', 'pt-BR': 'Bolas em cada caixa' },
  placesName: { role: 'data', 'en-US': 'Walks ending at each place', 'es-MX': 'Caminatas que terminan en cada lugar', 'pt-BR': 'Caminhadas que terminam em cada lugar' },
  ballShareName: { role: 'data', 'en-US': 'Share of balls in the target bin', 'es-MX': 'Proporción de bolas en el casillero meta', 'pt-BR': 'Proporção de bolas na caixa alvo' },
  walkShareName: { role: 'data', 'en-US': 'Share of walks at the target place', 'es-MX': 'Proporción de caminatas en el lugar meta', 'pt-BR': 'Proporção de caminhadas no lugar alvo' },
  ballStatus: { role: 'data', 'en-US': 'Balls: {n}. In bin {b}: {h}. Share: {s}. Chance: {c}', 'es-MX': 'Bolas: {n}. En el casillero {b}: {h}. Proporción: {s}. Probabilidad: {c}', 'pt-BR': 'Bolas: {n}. Na caixa {b}: {h}. Proporção: {s}. Chance: {c}' },
  walkStatus: { role: 'data', 'en-US': 'Walks: {n}. Ending {b} steps right: {h}. Share: {s}. Chance: {c}', 'es-MX': 'Caminatas: {n}. Terminan con {b} pasos a la derecha: {h}. Proporción: {s}. Probabilidad: {c}', 'pt-BR': 'Caminhadas: {n}. Terminam com {b} passos para a direita: {h}. Proporção: {s}. Chance: {c}' },
  ballNone: { role: 'data', 'en-US': 'No balls yet. Chance of bin {b}: {c}', 'es-MX': 'Aún no hay bolas. Probabilidad del casillero {b}: {c}', 'pt-BR': 'Ainda não há bolas. Chance da caixa {b}: {c}' },
  walkNone: { role: 'data', 'en-US': 'No walks yet. Chance of {b} steps right: {c}', 'es-MX': 'Aún no hay caminatas. Probabilidad de {b} pasos a la derecha: {c}', 'pt-BR': 'Ainda não há caminhadas. Chance de {b} passos para a direita: {c}' },
  ballGoal: { role: 'data', 'en-US': 'Goal: at least {n} balls, within {t} points of the chance', 'es-MX': 'Meta: al menos {n} bolas, a {t} puntos o menos de la probabilidad', 'pt-BR': 'Meta: pelo menos {n} bolas, a até {t} pontos da chance' },
  walkGoal: { role: 'data', 'en-US': 'Goal: at least {n} walks, within {t} points of the chance', 'es-MX': 'Meta: al menos {n} caminatas, a {t} puntos o menos de la probabilidad', 'pt-BR': 'Meta: pelo menos {n} caminhadas, a até {t} pontos da chance' },
  tableCaptionBins: { role: 'heading', 'en-US': 'Balls in each bin', 'es-MX': 'Bolas en cada casillero', 'pt-BR': 'Bolas em cada caixa' },
  tableCaptionPlaces: { role: 'heading', 'en-US': 'Walks at each place', 'es-MX': 'Caminatas en cada lugar', 'pt-BR': 'Caminhadas em cada lugar' },
  colBin: { role: 'data', 'en-US': 'Bin', 'es-MX': 'Casillero', 'pt-BR': 'Caixa' },
  colStepsRight: { role: 'data', 'en-US': 'Steps right', 'es-MX': 'Pasos a la derecha', 'pt-BR': 'Passos para a direita' },
  colBalls: { role: 'data', 'en-US': 'Balls', 'es-MX': 'Bolas', 'pt-BR': 'Bolas' },
  colWalks: { role: 'data', 'en-US': 'Walks', 'es-MX': 'Caminatas', 'pt-BR': 'Caminhadas' },
  colTarget: { role: 'data', 'en-US': 'Target', 'es-MX': 'Meta', 'pt-BR': 'Alvo' },

  intervalsName: { role: 'data', 'en-US': '100 intervals and the true share', 'es-MX': '100 intervalos y la proporción real', 'pt-BR': '100 intervalos e a proporção real' },
  truthMark: { role: 'data', 'en-US': 'True share', 'es-MX': 'Proporción real', 'pt-BR': 'Proporção real' },
  legendCovers: { role: 'data', 'en-US': 'Covers the truth', 'es-MX': 'Cubre la verdad', 'pt-BR': 'Cobre a verdade' },
  legendMisses: { role: 'data', 'en-US': 'Misses the truth', 'es-MX': 'No cubre la verdad', 'pt-BR': 'Não cobre a verdade' },
  measureLevel: { role: 'data', 'en-US': 'Level', 'es-MX': 'Nivel', 'pt-BR': 'Nível' },
  measureSize: { role: 'data', 'en-US': 'Sample size', 'es-MX': 'Tamaño de muestra', 'pt-BR': 'Tamanho da amostra' },
  measureTruth: { role: 'data', 'en-US': 'True share', 'es-MX': 'Proporción real', 'pt-BR': 'Proporção real' },
  measureCovering: { role: 'data', 'en-US': 'Intervals that cover', 'es-MX': 'Intervalos que cubren', 'pt-BR': 'Intervalos que cobrem' },
  measureMissing: { role: 'data', 'en-US': 'Intervals that miss', 'es-MX': 'Intervalos que no cubren', 'pt-BR': 'Intervalos que não cobrem' },
  measureGoal: { role: 'data', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  coverageStatus: { role: 'data', 'en-US': 'Level: {l}%. Sample size: {n}. Intervals that cover: {c} of 100. Goal: {g}', 'es-MX': 'Nivel: {l}%. Tamaño de muestra: {n}. Intervalos que cubren: {c} de 100. Meta: {g}', 'pt-BR': 'Nível: {l}%. Tamanho da amostra: {n}. Intervalos que cobrem: {c} de 100. Meta: {g}' },
  tableCaptionCoverage: { role: 'heading', 'en-US': 'Level, size and covers', 'es-MX': 'Nivel, tamaño y cobertura', 'pt-BR': 'Nível, tamanho e cobertura' },
  tableCaptionSamples: { role: 'heading', 'en-US': 'Each sample and its interval', 'es-MX': 'Cada muestra y su intervalo', 'pt-BR': 'Cada amostra e seu intervalo' },
  colSample: { role: 'data', 'en-US': 'Sample', 'es-MX': 'Muestra', 'pt-BR': 'Amostra' },
  colLow: { role: 'data', 'en-US': 'Low end', 'es-MX': 'Extremo inferior', 'pt-BR': 'Extremo inferior' },
  colHigh: { role: 'data', 'en-US': 'High end', 'es-MX': 'Extremo superior', 'pt-BR': 'Extremo superior' },
  metCoverage: { role: 'body', 'en-US': 'At least the goal number of intervals cover the truth.', 'es-MX': 'Al menos la meta de intervalos cubre la verdad.', 'pt-BR': 'Pelo menos a meta de intervalos cobre a verdade.' },
  hintCoverage: { role: 'body', 'en-US': 'Not yet. A higher level or a bigger sample helps.', 'es-MX': 'Aún no. Un nivel más alto o una muestra mayor ayuda.', 'pt-BR': 'Ainda não. Um nível mais alto ou uma amostra maior ajuda.' },

  dataName: { role: 'data', 'en-US': 'Your sample', 'es-MX': 'Tu muestra', 'pt-BR': 'Sua amostra' },
  sumsName: { role: 'data', 'en-US': 'Totals of the resamples', 'es-MX': 'Totales de los remuestreos', 'pt-BR': 'Totais das reamostragens' },
  bootData: { role: 'data', 'en-US': 'Sample: {v}', 'es-MX': 'Muestra: {v}', 'pt-BR': 'Amostra: {v}' },
  bootStatus: { role: 'data', 'en-US': 'Resamples: {n}. Middle {l}% of the totals: {a} to {b}', 'es-MX': 'Remuestreos: {n}. {l}% central de los totales: de {a} a {b}', 'pt-BR': 'Reamostragens: {n}. {l}% centrais dos totais: de {a} a {b}' },
  bootNone: { role: 'data', 'en-US': 'No resamples yet. Middle {l}% of the totals', 'es-MX': 'Aún no hay remuestreos. {l}% central de los totales', 'pt-BR': 'Ainda não há reamostragens. {l}% centrais dos totais' },
  bootPrev: { role: 'data', 'en-US': 'At the previous stop: {a} to {b}', 'es-MX': 'En la parada anterior: de {a} a {b}', 'pt-BR': 'Na parada anterior: de {a} a {b}' },
  bootGoal: { role: 'data', 'en-US': 'Goal: at least {n} resamples and steady edges', 'es-MX': 'Meta: al menos {n} remuestreos y bordes estables', 'pt-BR': 'Meta: pelo menos {n} reamostragens e bordas estáveis' },
  tableCaptionEdges: { role: 'heading', 'en-US': 'Edges of the middle totals', 'es-MX': 'Bordes de los totales centrales', 'pt-BR': 'Bordas dos totais centrais' },
  tableCaptionSums: { role: 'heading', 'en-US': 'Resamples at each total', 'es-MX': 'Remuestreos en cada total', 'pt-BR': 'Reamostragens em cada total' },
  measureResamples: { role: 'data', 'en-US': 'Resamples', 'es-MX': 'Remuestreos', 'pt-BR': 'Reamostragens' },
  measureLowEdge: { role: 'data', 'en-US': 'Lower edge', 'es-MX': 'Borde inferior', 'pt-BR': 'Borda inferior' },
  measureHighEdge: { role: 'data', 'en-US': 'Upper edge', 'es-MX': 'Borde superior', 'pt-BR': 'Borda superior' },
  measurePrevLow: { role: 'data', 'en-US': 'Lower edge at the previous stop', 'es-MX': 'Borde inferior en la parada anterior', 'pt-BR': 'Borda inferior na parada anterior' },
  measurePrevHigh: { role: 'data', 'en-US': 'Upper edge at the previous stop', 'es-MX': 'Borde superior en la parada anterior', 'pt-BR': 'Borda superior na parada anterior' },
  colTotal: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  colResamples: { role: 'data', 'en-US': 'Resamples', 'es-MX': 'Remuestreos', 'pt-BR': 'Reamostragens' },
  rangeOf: { role: 'data', 'en-US': '{a} to {b}', 'es-MX': '{a} a {b}', 'pt-BR': '{a} a {b}' },
  metBootstrap: { role: 'body', 'en-US': 'Both edges have settled.', 'es-MX': 'Los dos bordes ya se asentaron.', 'pt-BR': 'As duas bordas já se estabilizaram.' },
  hintBootstrap: { role: 'body', 'en-US': 'Not yet. Run more resamples until the edges stop moving.', 'es-MX': 'Aún no. Haz más remuestreos hasta que los bordes dejen de moverse.', 'pt-BR': 'Ainda não. Faça mais reamostragens até as bordas pararem de se mexer.' },
} as const satisfies HorizonteCopy;
