/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/space2/contract.ts. Do not edit: change the source and regenerate. */
import { z } from 'zod';
import { hzBase, hzServer, hzUngraded, hzVisual } from '../shared.generated';
import type { HorizonteAgeScope } from '../types.generated';
import { AR_OBJECT_IDS, readArPayload } from './ar.generated';
import { GLOBE_ASKS, GLOBE_LIMITS, PLACE_IDS, ROUTE_IDS, globeProblem, readGlobePayload } from './globe.generated';
import { SURFACE_LIMITS, SURFACE_OPTION_IDS, readSurfacePayload, surfaceProblem } from './surface.generated';

const whole = (minimum: number, maximum: number) => z.number().int().min(minimum).max(maximum);
const ascending = (count: { min: number; max: number }, low: number, high: number) => z.array(whole(low, high)).min(count.min).max(count.max)
  .refine((list) => list.every((entry, index) => index === 0 || entry > list[index - 1]!), 'Values must rise');

const compoundSurface = z.object({
  kind: z.literal('compound'),
  principalCents: whole(SURFACE_LIMITS.principalCents.min, SURFACE_LIMITS.principalCents.max),
  ratesBps: ascending(SURFACE_LIMITS.xCount, 0, SURFACE_LIMITS.rateBps),
  terms: ascending(SURFACE_LIMITS.yCount, 0, SURFACE_LIMITS.termYears),
}).strict();

const profitSurface = z.object({
  kind: z.literal('profit'),
  unitCostCents: whole(1, SURFACE_LIMITS.unitCostCents),
  fixedCents: whole(0, SURFACE_LIMITS.fixedCents),
  prices: ascending(SURFACE_LIMITS.xCount, 1, SURFACE_LIMITS.priceCents),
  units: ascending(SURFACE_LIMITS.yCount, 0, SURFACE_LIMITS.units),
}).strict();

const surfaceAsk = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('highest') }).strict(),
  z.object({ kind: z.literal('lowest') }).strict(),
  z.object({ kind: z.literal('reach'), targetCents: whole(-SURFACE_LIMITS.targetCents, SURFACE_LIMITS.targetCents) }).strict(),
]);

/** F4.7: a surface of two inputs and one output (compound interest or profit); the learner reads it and picks the option the question asks for. */
export const surfacePayload = z.object({
  surface: z.discriminatedUnion('kind', [compoundSurface, profitSurface]),
  ask: surfaceAsk,
  options: z.array(z.object({ id: z.enum(SURFACE_OPTION_IDS), x: whole(0, SURFACE_LIMITS.xCount.max - 1), y: whole(0, SURFACE_LIMITS.yCount.max - 1) }).strict())
    .min(SURFACE_LIMITS.options.min).max(SURFACE_LIMITS.options.max),
}).strict();

const placeId = z.enum(PLACE_IDS as [string, ...string[]]);

/** F4.8: routes between named places on a globe, each with a fee; the learner picks the shortest, the longest or the cheapest. */
export const globePayload = z.object({
  routes: z.array(z.object({
    id: z.enum(ROUTE_IDS), from: placeId, to: placeId, feeBps: whole(0, GLOBE_LIMITS.feeBps), flatCents: whole(0, GLOBE_LIMITS.flatCents),
  }).strict()).min(GLOBE_LIMITS.routes.min).max(GLOBE_LIMITS.routes.max),
  ask: z.enum(GLOBE_ASKS),
  sendCents: whole(GLOBE_LIMITS.sendCents.min, GLOBE_LIMITS.sendCents.max),
}).strict();

/** F4.9: one real object shown at its true size; there is no question and no answer. */
export const arPayload = z.object({ object: z.enum(AR_OBJECT_IDS as [string, ...string[]]) }).strict();

const complain = (ctx: z.RefinementCtx, message: string) => ctx.addIssue({ code: 'custom', path: ['payload'], message });

export const SPACE2_SEGMENTS = [
  z.object({
    ...hzBase, type: z.literal('math.surface.v2'), grading: hzServer, visual: hzVisual('surface'), payload: surfacePayload,
  }).strict().superRefine((value, ctx) => {
    const payload = readSurfacePayload(value.payload);
    const problem = payload ? surfaceProblem(payload) : 'The surface payload is malformed';
    if (problem) complain(ctx, problem);
  }),
  z.object({
    ...hzBase, type: z.literal('geography.globe-route.v2'), grading: hzServer, visual: hzVisual('globe-route'), payload: globePayload,
  }).strict().superRefine((value, ctx) => {
    const payload = readGlobePayload(value.payload);
    const problem = payload ? globeProblem(payload) : 'The globe payload is malformed';
    if (problem) complain(ctx, problem);
  }),
  z.object({
    ...hzBase, type: z.literal('space.ar-table.v2'), grading: hzUngraded, visual: hzVisual('ar-table'), payload: arPayload,
  }).strict().superRefine((value, ctx) => {
    if (!readArPayload(value.payload)) complain(ctx, 'The AR payload is malformed');
  }),
] as const;

/** Only the two graded kinds carry a rubric; the AR step is not scored and has no key. */
export const SPACE2_RUBRICS = {
  'math.surface.v2': z.object({ choice: z.enum(SURFACE_OPTION_IDS) }).strict(),
  'geography.globe-route.v2': z.object({ choice: z.enum(ROUTE_IDS) }).strict(),
} as const;

export const SPACE2_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {
  'math.surface.v2': { ages: [15, 17], adult: true },
  'geography.globe-route.v2': { ages: [12, 17], adult: true },
  'space.ar-table.v2': { ages: [13, 17], adult: true },
};
