import type { HorizonteCopy } from '../boardTypes';

/*
 * Every string of the space2 boards (surfaces, globe, AR table), in three native versions, each tagged with the Copy Budget role
 * its element carries. Slots such as {x} are filled by `fill`; place names and object names are `data`, which has no limit.
 */
const B = '13-17' as const;

export const SPACE2_COPY = {
  showTable: { role: 'action', band: B, 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', band: B, 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  less: { role: 'action', band: B, 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', band: B, 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  turnLeft: { role: 'action', band: B, 'en-US': 'Turn left', 'es-MX': 'Girar a la izquierda', 'pt-BR': 'Girar à esquerda' },
  turnRight: { role: 'action', band: B, 'en-US': 'Turn right', 'es-MX': 'Girar a la derecha', 'pt-BR': 'Girar à direita' },
  viewHigher: { role: 'action', band: B, 'en-US': 'Look higher', 'es-MX': 'Vista más alta', 'pt-BR': 'Vista mais alta' },
  viewLower: { role: 'action', band: B, 'en-US': 'Look lower', 'es-MX': 'Vista más baja', 'pt-BR': 'Vista mais baixa' },
  viewTurn: { role: 'data', band: B, 'en-US': 'Turn {n} of 4', 'es-MX': 'Giro {n} de 4', 'pt-BR': 'Giro {n} de 4' },
  viewLevel: { role: 'data', band: B, 'en-US': 'Level view', 'es-MX': 'Vista a nivel', 'pt-BR': 'Vista no nível' },
  viewCorner: { role: 'data', band: B, 'en-US': 'Corner view', 'es-MX': 'Vista de esquina', 'pt-BR': 'Vista de canto' },
  viewTop: { role: 'data', band: B, 'en-US': 'Top view', 'es-MX': 'Vista desde arriba', 'pt-BR': 'Vista de cima' },
  yearOne: { role: 'data', band: B, 'en-US': '{n} year', 'es-MX': '{n} año', 'pt-BR': '{n} ano' },
  yearMany: { role: 'data', band: B, 'en-US': '{n} years', 'es-MX': '{n} años', 'pt-BR': '{n} anos' },
  unitOne: { role: 'data', band: B, 'en-US': '{n} unit', 'es-MX': '{n} unidad', 'pt-BR': '{n} unidade' },
  unitMany: { role: 'data', band: B, 'en-US': '{n} units', 'es-MX': '{n} unidades', 'pt-BR': '{n} unidades' },

  surfaceName: { role: 'data', band: B, 'en-US': 'Surface of values', 'es-MX': 'Superficie de valores', 'pt-BR': 'Superfície de valores' },
  surfaceKeys: {
    role: 'body', band: B,
    'en-US': 'Arrow keys turn the surface. Up and down tilt it.',
    'es-MX': 'Las flechas giran la superficie. Arriba y abajo la inclinan.',
    'pt-BR': 'As setas giram a superfície. Cima e baixo a inclinam.',
  },
  surfaceControls: { role: 'heading', band: B, 'en-US': 'Change the view', 'es-MX': 'Cambia la vista', 'pt-BR': 'Mude a vista' },
  sliceHeading: { role: 'heading', band: B, 'en-US': 'Slice the surface', 'es-MX': 'Corta la superficie', 'pt-BR': 'Corte a superfície' },
  holdHeading: { role: 'heading', band: B, 'en-US': 'Hold one value still', 'es-MX': 'Deja un valor quieto', 'pt-BR': 'Deixe um valor parado' },
  holdRate: { role: 'option', band: B, 'en-US': 'Hold the rate', 'es-MX': 'Fijar la tasa', 'pt-BR': 'Fixar a taxa' },
  holdTerm: { role: 'option', band: B, 'en-US': 'Hold the term', 'es-MX': 'Fijar el plazo', 'pt-BR': 'Fixar o prazo' },
  holdPrice: { role: 'option', band: B, 'en-US': 'Hold the price', 'es-MX': 'Fijar el precio', 'pt-BR': 'Fixar o preço' },
  holdUnits: { role: 'option', band: B, 'en-US': 'Hold the units', 'es-MX': 'Fijar las unidades', 'pt-BR': 'Fixar as unidades' },
  axisRate: { role: 'data', band: B, 'en-US': 'Rate', 'es-MX': 'Tasa', 'pt-BR': 'Taxa' },
  axisTerm: { role: 'data', band: B, 'en-US': 'Term', 'es-MX': 'Plazo', 'pt-BR': 'Prazo' },
  axisPrice: { role: 'data', band: B, 'en-US': 'Price', 'es-MX': 'Precio', 'pt-BR': 'Preço' },
  axisUnits: { role: 'data', band: B, 'en-US': 'Units', 'es-MX': 'Unidades', 'pt-BR': 'Unidades' },
  outAmount: { role: 'data', band: B, 'en-US': 'Amount', 'es-MX': 'Monto', 'pt-BR': 'Montante' },
  outProfit: { role: 'data', band: B, 'en-US': 'Profit', 'es-MX': 'Ganancia', 'pt-BR': 'Lucro' },
  sliceName: { role: 'data', band: B, 'en-US': 'Slice of the surface', 'es-MX': 'Corte de la superficie', 'pt-BR': 'Corte da superfície' },
  sliceNote: { role: 'data', band: B, 'en-US': '{held}. {out} from {low} to {high}.', 'es-MX': '{held}. {out}: de {low} a {high}.', 'pt-BR': '{held}. {out}: de {low} a {high}.' },
  optionsHeading: { role: 'heading', band: B, 'en-US': 'Pick one choice', 'es-MX': 'Elige una opción', 'pt-BR': 'Escolha uma opção' },
  optionLine: { role: 'data', band: B, 'en-US': '{id}: {x}, {y}', 'es-MX': '{id}: {x}, {y}', 'pt-BR': '{id}: {x}, {y}' },
  chosenNone: { role: 'data', band: B, 'en-US': 'Chosen: none', 'es-MX': 'Elegida: ninguna', 'pt-BR': 'Escolhida: nenhuma' },
  chosen: { role: 'data', band: B, 'en-US': 'Chosen: {option}', 'es-MX': 'Elegida: {option}', 'pt-BR': 'Escolhida: {option}' },
  tableAmount: { role: 'heading', band: B, 'en-US': 'Amount at every rate and term', 'es-MX': 'Monto con cada tasa y plazo', 'pt-BR': 'Montante em cada taxa e prazo' },
  tableProfit: { role: 'heading', band: B, 'en-US': 'Profit at every price and quantity', 'es-MX': 'Ganancia con cada precio y cantidad', 'pt-BR': 'Lucro em cada preço e quantidade' },
  tableCorner: { role: 'data', band: B, 'en-US': '{y} / {x}', 'es-MX': '{y} / {x}', 'pt-BR': '{y} / {x}' },
  metSurface: { role: 'body', band: B, 'en-US': 'You read the surface and found it.', 'es-MX': 'Leíste la superficie y la encontraste.', 'pt-BR': 'Você leu a superfície e a encontrou.' },
  hintSurface: { role: 'body', band: B, 'en-US': 'Not yet. Slice the surface and compare.', 'es-MX': 'Aún no. Corta la superficie y compara.', 'pt-BR': 'Ainda não. Corte a superfície e compare.' },

  globeName: { role: 'data', band: B, 'en-US': 'Globe with routes', 'es-MX': 'Globo con rutas', 'pt-BR': 'Globo com rotas' },
  globeKeys: {
    role: 'body', band: B,
    'en-US': 'Arrow keys turn the globe. Up and down tilt it.',
    'es-MX': 'Las flechas giran el globo. Arriba y abajo lo inclinan.',
    'pt-BR': 'As setas giram o globo. Cima e baixo o inclinam.',
  },
  globeControls: { role: 'heading', band: B, 'en-US': 'Turn the globe', 'es-MX': 'Gira el globo', 'pt-BR': 'Gire o globo' },
  turnWest: { role: 'action', band: B, 'en-US': 'Turn west', 'es-MX': 'Girar al oeste', 'pt-BR': 'Girar para oeste' },
  turnEast: { role: 'action', band: B, 'en-US': 'Turn east', 'es-MX': 'Girar al este', 'pt-BR': 'Girar para leste' },
  tiltNorth: { role: 'action', band: B, 'en-US': 'Tilt north', 'es-MX': 'Inclinar al norte', 'pt-BR': 'Inclinar para norte' },
  tiltSouth: { role: 'action', band: B, 'en-US': 'Tilt south', 'es-MX': 'Inclinar al sur', 'pt-BR': 'Inclinar para sul' },
  facing: { role: 'data', band: B, 'en-US': 'Facing {lat}, {lon}', 'es-MX': 'Mirando a {lat}, {lon}', 'pt-BR': 'Voltado para {lat}, {lon}' },
  dirNorth: { role: 'data', band: B, 'en-US': 'N', 'es-MX': 'N', 'pt-BR': 'N' },
  dirSouth: { role: 'data', band: B, 'en-US': 'S', 'es-MX': 'S', 'pt-BR': 'S' },
  dirEast: { role: 'data', band: B, 'en-US': 'E', 'es-MX': 'E', 'pt-BR': 'L' },
  dirWest: { role: 'data', band: B, 'en-US': 'W', 'es-MX': 'O', 'pt-BR': 'O' },
  routesHeading: { role: 'heading', band: B, 'en-US': 'Pick a route', 'es-MX': 'Elige una ruta', 'pt-BR': 'Escolha uma rota' },
  routeLine: { role: 'data', band: B, 'en-US': '{id}: {from} to {to}', 'es-MX': '{id}: {from} a {to}', 'pt-BR': '{id}: {from} para {to}' },
  feeTerms: { role: 'data', band: B, 'en-US': 'fee {rate} + {flat}', 'es-MX': 'comisión {rate} + {flat}', 'pt-BR': 'taxa {rate} + {flat}' },
  sendLine: { role: 'data', band: B, 'en-US': 'Amount to send: {amount}', 'es-MX': 'Monto a enviar: {amount}', 'pt-BR': 'Valor a enviar: {amount}' },
  tableRoutes: { role: 'heading', band: B, 'en-US': 'Routes in numbers', 'es-MX': 'Rutas en números', 'pt-BR': 'Rotas em números' },
  colRoute: { role: 'data', band: B, 'en-US': 'Route', 'es-MX': 'Ruta', 'pt-BR': 'Rota' },
  colFrom: { role: 'data', band: B, 'en-US': 'From', 'es-MX': 'Desde', 'pt-BR': 'De' },
  colTo: { role: 'data', band: B, 'en-US': 'To', 'es-MX': 'Hasta', 'pt-BR': 'Para' },
  colDistance: { role: 'data', band: B, 'en-US': 'Distance', 'es-MX': 'Distancia', 'pt-BR': 'Distância' },
  colFee: { role: 'data', band: B, 'en-US': 'Fee', 'es-MX': 'Comisión', 'pt-BR': 'Taxa' },
  distanceKm: { role: 'data', band: B, 'en-US': '{n} km', 'es-MX': '{n} km', 'pt-BR': '{n} km' },
  metGlobe: { role: 'body', band: B, 'en-US': 'You compared the routes and found it.', 'es-MX': 'Comparaste las rutas y la encontraste.', 'pt-BR': 'Você comparou as rotas e a encontrou.' },
  hintGlobe: { role: 'body', band: B, 'en-US': 'Not yet. Turn the globe and compare.', 'es-MX': 'Aún no. Gira el globo y compara.', 'pt-BR': 'Ainda não. Gire o globo e compare.' },

  placeMexicoCity: { role: 'data', band: B, 'en-US': 'Mexico City', 'es-MX': 'Ciudad de México', 'pt-BR': 'Cidade do México' },
  placeLosAngeles: { role: 'data', band: B, 'en-US': 'Los Angeles', 'es-MX': 'Los Ángeles', 'pt-BR': 'Los Angeles' },
  placeHouston: { role: 'data', band: B, 'en-US': 'Houston', 'es-MX': 'Houston', 'pt-BR': 'Houston' },
  placeNewYork: { role: 'data', band: B, 'en-US': 'New York', 'es-MX': 'Nueva York', 'pt-BR': 'Nova York' },
  placeBogota: { role: 'data', band: B, 'en-US': 'Bogota', 'es-MX': 'Bogotá', 'pt-BR': 'Bogotá' },
  placeSaoPaulo: { role: 'data', band: B, 'en-US': 'Sao Paulo', 'es-MX': 'São Paulo', 'pt-BR': 'São Paulo' },
  placeLisbon: { role: 'data', band: B, 'en-US': 'Lisbon', 'es-MX': 'Lisboa', 'pt-BR': 'Lisboa' },
  placeMadrid: { role: 'data', band: B, 'en-US': 'Madrid', 'es-MX': 'Madrid', 'pt-BR': 'Madri' },
  placeLagos: { role: 'data', band: B, 'en-US': 'Lagos', 'es-MX': 'Lagos', 'pt-BR': 'Lagos' },
  placeNairobi: { role: 'data', band: B, 'en-US': 'Nairobi', 'es-MX': 'Nairobi', 'pt-BR': 'Nairóbi' },
  placeJohannesburg: { role: 'data', band: B, 'en-US': 'Johannesburg', 'es-MX': 'Johannesburgo', 'pt-BR': 'Joanesburgo' },
  placeDubai: { role: 'data', band: B, 'en-US': 'Dubai', 'es-MX': 'Dubái', 'pt-BR': 'Dubai' },
  placeMumbai: { role: 'data', band: B, 'en-US': 'Mumbai', 'es-MX': 'Bombay', 'pt-BR': 'Bombaim' },
  placeManila: { role: 'data', band: B, 'en-US': 'Manila', 'es-MX': 'Manila', 'pt-BR': 'Manila' },
  placeTokyo: { role: 'data', band: B, 'en-US': 'Tokyo', 'es-MX': 'Tokio', 'pt-BR': 'Tóquio' },
  placeSydney: { role: 'data', band: B, 'en-US': 'Sydney', 'es-MX': 'Sídney', 'pt-BR': 'Sydney' },

  arName: { role: 'heading', band: B, 'en-US': 'Object at true size', 'es-MX': 'Objeto a tamaño real', 'pt-BR': 'Objeto em tamanho real' },
  arTag: { role: 'data', band: B, 'en-US': 'Ungraded', 'es-MX': 'Sin calificación', 'pt-BR': 'Sem nota' },
  arKeys: {
    role: 'body', band: B,
    'en-US': 'Arrow keys turn the object. Up and down tilt it.',
    'es-MX': 'Las flechas giran el objeto. Arriba y abajo lo inclinan.',
    'pt-BR': 'As setas giram o objeto. Cima e baixo o inclinam.',
  },
  arControls: { role: 'heading', band: B, 'en-US': 'Turn the object', 'es-MX': 'Gira el objeto', 'pt-BR': 'Gire o objeto' },
  arConsentHeading: { role: 'heading', band: B, 'en-US': 'Use your camera?', 'es-MX': '¿Usar tu cámara?', 'pt-BR': 'Usar a sua câmera?' },
  arConsentBody: {
    role: 'body', band: B,
    'en-US': 'The camera only shows your table. Nothing is saved or sent.',
    'es-MX': 'La cámara solo muestra tu mesa. No se guarda ni se envía nada.',
    'pt-BR': 'A câmera só mostra a sua mesa. Nada é salvo nem enviado.',
  },
  arAllow: { role: 'action', band: B, 'en-US': 'Allow camera', 'es-MX': 'Permitir cámara', 'pt-BR': 'Permitir câmera' },
  arDecline: { role: 'action', band: B, 'en-US': 'Not now', 'es-MX': 'Ahora no', 'pt-BR': 'Agora não' },
  arStart: { role: 'action', band: B, 'en-US': 'See on table', 'es-MX': 'Ver en la mesa', 'pt-BR': 'Ver na mesa' },
  arStarting: { role: 'data', band: B, 'en-US': 'Starting AR', 'es-MX': 'Iniciando RA', 'pt-BR': 'Iniciando RA' },
  arRunning: { role: 'body', band: B, 'en-US': 'AR is on. Leave it from your browser.', 'es-MX': 'La RA está activa. Sal desde tu navegador.', 'pt-BR': 'A RA está ativa. Saia pelo navegador.' },
  arEnded: { role: 'body', band: B, 'en-US': 'AR has ended. Turn the object instead.', 'es-MX': 'La RA terminó. Gira el objeto.', 'pt-BR': 'A RA terminou. Gire o objeto.' },
  arFailed: { role: 'body', band: B, 'en-US': 'AR could not start. Turn the object instead.', 'es-MX': 'No se pudo iniciar la RA. Gira el objeto.', 'pt-BR': 'Não foi possível iniciar a RA. Gire o objeto.' },
  arUnsupported: { role: 'body', band: B, 'en-US': 'AR is not available here. Turn the object instead.', 'es-MX': 'La RA no está disponible aquí. Gira el objeto.', 'pt-BR': 'A RA não está disponível aqui. Gire o objeto.' },
  arDeclined: { role: 'body', band: B, 'en-US': 'No camera. Turn the object instead.', 'es-MX': 'Sin cámara. Gira el objeto.', 'pt-BR': 'Sem câmera. Gire o objeto.' },
  tableSize: { role: 'heading', band: B, 'en-US': 'Size of the object', 'es-MX': 'Tamaño del objeto', 'pt-BR': 'Tamanho do objeto' },
  colMeasure: { role: 'data', band: B, 'en-US': 'Measure', 'es-MX': 'Medida', 'pt-BR': 'Medida' },
  colValue: { role: 'data', band: B, 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  rowWidth: { role: 'data', band: B, 'en-US': 'Width', 'es-MX': 'Ancho', 'pt-BR': 'Largura' },
  rowHeight: { role: 'data', band: B, 'en-US': 'Height', 'es-MX': 'Alto', 'pt-BR': 'Altura' },
  rowDepth: { role: 'data', band: B, 'en-US': 'Depth', 'es-MX': 'Fondo', 'pt-BR': 'Profundidade' },
  rowVolume: { role: 'data', band: B, 'en-US': 'Volume', 'es-MX': 'Volumen', 'pt-BR': 'Volume' },
  unitCm: { role: 'data', band: B, 'en-US': '{n} cm', 'es-MX': '{n} cm', 'pt-BR': '{n} cm' },
  unitMl: { role: 'data', band: B, 'en-US': '{n} mL', 'es-MX': '{n} mL', 'pt-BR': '{n} mL' },
  objectLitreBox: { role: 'data', band: B, 'en-US': 'One litre box', 'es-MX': 'Caja de un litro', 'pt-BR': 'Caixa de um litro' },
  objectCerealBox: { role: 'data', band: B, 'en-US': 'Cereal box', 'es-MX': 'Caja de cereal', 'pt-BR': 'Caixa de cereal' },
  objectSoupCan: { role: 'data', band: B, 'en-US': 'Soup can', 'es-MX': 'Lata de sopa', 'pt-BR': 'Lata de sopa' },
  objectShoebox: { role: 'data', band: B, 'en-US': 'Shoebox', 'es-MX': 'Caja de zapatos', 'pt-BR': 'Caixa de sapatos' },
} as const satisfies HorizonteCopy;
