/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/space2/scorer.ts. Do not edit: change the source and regenerate. */
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import { answerCount, formulaKey, parseFormula, partialsAt, ratEquals, ratText, readFormulaPayload, readNumber, throughCount, type FormulaPayload, type Rat } from './field.generated';
import { globeKey, readGlobePayload } from './globe.generated';
import { readSurfacePayload, surfaceKey } from './surface.generated';

type Segment = { payload: unknown };

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };
const review = (diagnostic: 'partial' | 'miss' | 'value' | 'false_alarm' | 'structure'): V2Grade => ({ verdict: 'review', diagnostic });

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const hasKeys = (value: Record<string, unknown>, keys: readonly string[]): boolean => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));

/**
 * The surface and the globe kinds answer one choice from a short list, so they share one ladder. invalid: malformed, a choice the question
 * does not list, or a rubric that is not the one clear answer. valid: nothing chosen yet, and every well-formed response
 * when there is no rubric. met: the key. review: any other listed choice (the value was read wrongly).
 */
function choiceGrade(ids: readonly string[], key: string | null, response: unknown, rubric: unknown): V2Grade {
  if (!isRecord(response) || !hasKeys(response, ['choice'])) return INVALID;
  const { choice } = response;
  if (typeof choice !== 'string' || (choice !== '' && !ids.includes(choice))) return INVALID;
  if (rubric === undefined) return VALID;
  if (key === null || !isRecord(rubric) || !hasKeys(rubric, ['choice']) || rubric.choice !== key) return INVALID;
  if (choice === '') return VALID;
  return choice === key ? MET : review('value');
}

function surfaceGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readSurfacePayload(segment?.payload);
  if (!payload) return INVALID;
  return choiceGrade(payload.options.map((option) => option.id), surfaceKey(payload), response, rubric);
}

function globeGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readGlobePayload(segment?.payload);
  if (!payload) return INVALID;
  return choiceGrade(payload.routes.map((route) => route.id), globeKey(payload), response, rubric);
}

/** The typed answers, one text per box; null when one is not a number (or, for a build, not a formula that reads). A blank box is allowed and stays blank. */
function readAnswers(payload: FormulaPayload, response: unknown): { texts: string[]; blank: boolean } | null {
  if (!isRecord(response) || !hasKeys(response, ['answer'])) return null;
  const { answer } = response;
  if (!Array.isArray(answer) || answer.length !== answerCount(payload.task)) return null;
  const build = payload.task.kind === 'build';
  const texts: string[] = [];
  for (const entry of answer) {
    if (typeof entry !== 'string') return null;
    const text = entry.trim();
    if (text !== '' && (build ? !parseFormula(text).ok : readNumber(text) === null)) return null;
    texts.push(text);
  }
  return { texts, blank: texts.some((text) => text === '') };
}

const sameNumber = (text: string, expected: Rat): boolean => {
  const value = readNumber(text);
  return value !== null && ratEquals(value, expected);
};

/**
 * One ladder for the four formula tasks. invalid: malformed, a box that is not a number (a formula that does not read, for a build),
 * or a rubric that is not the one exact answer of this payload. valid: a box still blank, and every well-formed response when there is
 * no rubric. met: the exact answer (a slope or a gradient equal as numbers, a walk of the right length, a formula through every
 * point). review: partial (one of two gradient parts, or a formula through some points), structure (the other axis, or the two
 * gradient parts swapped), miss (a formula through none) or value.
 */
function formulaGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readFormulaPayload(segment?.payload);
  if (!payload) return INVALID;
  const answers = readAnswers(payload, response);
  if (!answers) return INVALID;
  const { task } = payload;
  if (task.kind === 'build') {
    if (rubric === undefined) return VALID;
    if (!isRecord(rubric) || !hasKeys(rubric, ['reference']) || throughCount(rubric.reference, task.through) !== task.through.length) return INVALID;
    if (answers.blank) return VALID;
    const hit = throughCount(answers.texts[0], task.through) ?? 0;
    return hit === task.through.length ? MET : review(hit > 0 ? 'partial' : 'miss');
  }
  const key = formulaKey(payload);
  if (rubric === undefined) return VALID;
  if (!key || !isRecord(rubric) || !hasKeys(rubric, ['key']) || !Array.isArray(rubric.key)
    || rubric.key.length !== key.length || rubric.key.some((text, index) => text !== ratText(key[index]!))) return INVALID;
  if (answers.blank) return VALID;
  const right = key.map((value, index) => sameNumber(answers.texts[index]!, value));
  if (right.every(Boolean)) return MET;
  if (task.kind === 'gradient') {
    if (right.some(Boolean)) return review('partial');
    return key.length === 2 && sameNumber(answers.texts[0]!, key[1]!) && sameNumber(answers.texts[1]!, key[0]!) ? review('structure') : review('value');
  }
  if (task.kind === 'slope') {
    const both = partialsAt(payload);
    const other = both ? (task.axis === 'x' ? both.dy : both.dx) : null;
    return other && sameNumber(answers.texts[0]!, other) ? review('structure') : review('value');
  }
  return review('value');
}

const BLANK = (() => ({ choice: '' })) as HorizonteScorer['sample'];
const BLANK_ANSWERS = ((segment: Segment) => {
  const payload = readFormulaPayload(segment?.payload);
  return { answer: Array.from({ length: payload ? answerCount(payload.task) : 1 }, () => '') };
}) as unknown as HorizonteScorer['sample'];

/** The AR step is not scored, so it has no scorer here: Core keys and grades only `grading: server` segments. */
export const SPACE2_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'math.surface.v2': { grade: surfaceGrade as HorizonteScorer['grade'], sample: BLANK },
  'geography.globe-route.v2': { grade: globeGrade as HorizonteScorer['grade'], sample: BLANK },
  'math.surface-formula.v2': { grade: formulaGrade as HorizonteScorer['grade'], sample: BLANK_ANSWERS },
};
