/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/types.ts. Do not edit: change the source and regenerate. */
import type { z } from 'zod';
import type { V2Grade } from '../v2VisualScorer.generated';
import type { HorizonteAttempt } from './seed/protocol.generated';

export type HorizonteAgeScope = { ages: readonly [number, number]; adult: boolean };

/**
 * `rubric` is undefined in the browser, which never holds one: the scorer then reports only invalid or valid.
 * `attempt` is the seed Core derived from the verified attempt token; a seeded scorer replays its simulation under it and
 * treats a rubric without an attempt as invalid. Every other scorer ignores it.
 */
export type HorizonteScorer<Segment = never, Rubric = never> = {
  grade: (segment: Segment, response: unknown, rubric: Rubric | undefined, attempt?: HorizonteAttempt) => V2Grade;
  /** A well-formed response that proves the key is scorable, never that it is met. */
  sample: (segment: Segment, rubric: Rubric) => unknown;
};

/** One Horizonte pack as Core and the browser consume it: pure data, no React. */
export interface HorizontePack {
  id: string;
  segments: readonly z.ZodType[];
  capabilities: Readonly<Record<string, readonly string[]>>;
  rubrics: Readonly<Record<string, z.ZodType>>;
  ageScope: Readonly<Record<string, HorizonteAgeScope>>;
  scorers: Readonly<Record<string, HorizonteScorer>>;
}

export type HorizonteLocale = 'en-US' | 'es-MX' | 'pt-BR';
export type HorizonteAgeBand = '6-9' | '10-12' | '13-17' | 'adult';

/** One authored sample of a piece: drives preview, audit and the contract harnesses. Pure data, no React. */
export interface HorizonteFixture {
  id: string;
  title: Readonly<Record<HorizonteLocale, string>>;
  ageBand: HorizonteAgeBand;
  eligibility: { minimum_age: number; maximum_age: number };
  segment: (locale: HorizonteLocale) => Record<string, unknown>;
  rubric: Record<string, unknown>;
  /** A seeded piece: the attempt seed its ladder responses were simulated under (64 lowercase hex characters). */
  seed?: string;
  /** One response per rung of the ladder; `valid` is the untouched state, `met` the answer. */
  ladder: { invalid: unknown; valid: unknown; met: unknown };
}
