/*
 * GENERATED by agent/tools/check-mentor-canary-parity.mjs --write from
 * docs/rebuild/mentor/governance/registry.json (tier2Parameters) and canaries.json. Do not edit by hand: `npm run canary:check` fails on any drift.
 */

export interface Tier2ParameterBounds {
  min: number;
  max: number;
  integer: boolean;
}

export interface MentorCanaryEntry {
  experimentId: string;
  proposalId: string;
  share: number;
  overrides: Readonly<Record<string, number>>;
}

/** C.22 Tier 2 parameters: the only values a Stage 5 canary may override, and their approved bounds. */
export const TIER2_PARAMETERS: Readonly<Record<string, Tier2ParameterBounds>> = {
  'telemetry.latencyZ': { min: 1, max: 2.5, integer: false },
  'telemetry.minChannels': { min: 2, max: 3, integer: true },
  'telemetry.maxCheckIns': { min: 1, max: 3, integer: true },
  'alliance.renegotiateAfterDeclines': { min: 2, max: 4, integer: true },
  'alliance.maxRenegotiations': { min: 1, max: 3, integer: true },
  'selfExplanation.maxPerSession': { min: 1, max: 6, integer: true },
  'selfExplanation.minSpacingTurns': { min: 2, max: 6, integer: true },
};

export const MENTOR_CANARY_TARGET = 'mentor.canary';
export const MENTOR_CANARY_MAX_SHARE = 0.1;

/** The RUNNING canaries (Appendix F Stage 5); empty while no Tier 2 change is in canary. A concluded one is never delivered. */
export const MENTOR_CANARIES: readonly MentorCanaryEntry[] = [];
