import type { HorizonteCopy } from '../boardTypes';

export const SIM2_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  less: { role: 'action', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  yes: { role: 'data', 'en-US': 'Yes', 'es-MX': 'Sí', 'pt-BR': 'Sim' },
  no: { role: 'data', 'en-US': 'No', 'es-MX': 'No', 'pt-BR': 'Não' },

  sliderPortfolio: { role: 'body', 'en-US': 'Share in stocks', 'es-MX': 'Proporción en acciones', 'pt-BR': 'Fatia em ações' },
  sliderRetirement: { role: 'body', 'en-US': 'Spending each chapter', 'es-MX': 'Gasto en cada capítulo', 'pt-BR': 'Gasto em cada capítulo' },
  sliderInsurance: { role: 'body', 'en-US': 'Share covered', 'es-MX': 'Proporción cubierta', 'pt-BR': 'Fatia coberta' },
  sliderLife: { role: 'body', 'en-US': 'Pay sent to debt', 'es-MX': 'Pago que va a la deuda', 'pt-BR': 'Pagamento que vai para a dívida' },
  valuePortfolio: { role: 'data', 'en-US': '{v}% in stocks', 'es-MX': '{v}% en acciones', 'pt-BR': '{v}% em ações' },
  valueRetirement: { role: 'data', 'en-US': '{v} each chapter', 'es-MX': '{v} por capítulo', 'pt-BR': '{v} por capítulo' },
  valueInsurance: { role: 'data', 'en-US': '{v}% covered', 'es-MX': '{v}% cubierto', 'pt-BR': '{v}% coberto' },
  valueLife: { role: 'data', 'en-US': '{v}% of pay to debt', 'es-MX': '{v}% del pago a la deuda', 'pt-BR': '{v}% do pagamento para a dívida' },

  chartMoney: { role: 'data', 'en-US': 'Your money in 100 futures. Target {finish}, floor {floor}.', 'es-MX': 'Tu dinero en 100 futuros. Meta {finish}, mínimo {floor}.', 'pt-BR': 'Seu dinheiro em 100 futuros. Meta {finish}, mínimo {floor}.' },
  chartMoneyFloor: { role: 'data', 'en-US': 'Your money in 100 futures. Floor {floor}.', 'es-MX': 'Tu dinero en 100 futuros. Mínimo {floor}.', 'pt-BR': 'Seu dinheiro em 100 futuros. Mínimo {floor}.' },
  chartNet: { role: 'data', 'en-US': 'Your money minus debt in 100 futures. Target {finish}.', 'es-MX': 'Tu dinero menos la deuda en 100 futuros. Meta {finish}.', 'pt-BR': 'Seu dinheiro menos a dívida em 100 futuros. Meta {finish}.' },
  chartCash: { role: 'data', 'en-US': 'Your cash in 100 futures. Floor {floor}.', 'es-MX': 'Tu efectivo en 100 futuros. Mínimo {floor}.', 'pt-BR': 'Seu dinheiro em caixa em 100 futuros. Mínimo {floor}.' },
  axisYears: { role: 'data', 'en-US': 'Years', 'es-MX': 'Años', 'pt-BR': 'Anos' },
  legendYes: { role: 'data', 'en-US': 'Future succeeds', 'es-MX': 'El futuro lo logra', 'pt-BR': 'O futuro consegue' },
  legendNo: { role: 'data', 'en-US': 'Future fails', 'es-MX': 'El futuro falla', 'pt-BR': 'O futuro falha' },
  legendFinish: { role: 'data', 'en-US': 'Target', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  legendFloor: { role: 'data', 'en-US': 'Floor', 'es-MX': 'Mínimo', 'pt-BR': 'Mínimo' },
  status: { role: 'data', 'en-US': '{c}. {n} of 100 futures succeed. Needed: {g} of 100.', 'es-MX': '{c}. {n} de 100 futuros lo logran. Se necesitan {g} de 100.', 'pt-BR': '{c}. {n} de 100 futuros conseguem. Necessários: {g} de 100.' },

  tableChoice: { role: 'heading', 'en-US': 'Your choice', 'es-MX': 'Tu elección', 'pt-BR': 'Sua escolha' },
  tableOutcomes: { role: 'heading', 'en-US': 'What one chapter can bring', 'es-MX': 'Lo que puede traer un capítulo', 'pt-BR': 'O que um capítulo pode trazer' },
  tableFutures: { role: 'heading', 'en-US': 'All 100 futures', 'es-MX': 'Los 100 futuros', 'pt-BR': 'Os 100 futuros' },
  outcomesNote: { role: 'body', 'en-US': 'All eight are equally likely each chapter.', 'es-MX': 'Los ocho son igual de probables en cada capítulo.', 'pt-BR': 'Os oito são igualmente prováveis em cada capítulo.' },
  colMeasure: { role: 'data', 'en-US': 'Measure', 'es-MX': 'Medida', 'pt-BR': 'Medida' },
  colValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  measureChoice: { role: 'data', 'en-US': 'Choice', 'es-MX': 'Elección', 'pt-BR': 'Escolha' },
  measureTime: { role: 'data', 'en-US': 'Time', 'es-MX': 'Tiempo', 'pt-BR': 'Tempo' },
  timeValue: { role: 'data', 'en-US': '{n} chapters, {y} years', 'es-MX': '{n} capítulos, {y} años', 'pt-BR': '{n} capítulos, {y} anos' },
  measureStart: { role: 'data', 'en-US': 'Starting cash', 'es-MX': 'Efectivo inicial', 'pt-BR': 'Dinheiro inicial' },
  measureDebt: { role: 'data', 'en-US': 'Starting debt', 'es-MX': 'Deuda inicial', 'pt-BR': 'Dívida inicial' },
  measureFlow: { role: 'data', 'en-US': 'Added each chapter', 'es-MX': 'Se suma en cada capítulo', 'pt-BR': 'Entra em cada capítulo' },
  measureFinish: { role: 'data', 'en-US': 'Target', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  measureFloor: { role: 'data', 'en-US': 'Floor', 'es-MX': 'Mínimo', 'pt-BR': 'Mínimo' },
  measureWins: { role: 'data', 'en-US': 'Futures that succeed', 'es-MX': 'Futuros que lo logran', 'pt-BR': 'Futuros que conseguem' },
  measureNeeded: { role: 'data', 'en-US': 'Futures needed', 'es-MX': 'Futuros necesarios', 'pt-BR': 'Futuros necessários' },
  colOutcome: { role: 'data', 'en-US': 'Outcome', 'es-MX': 'Resultado', 'pt-BR': 'Resultado' },
  colReturn: { role: 'data', 'en-US': 'Return', 'es-MX': 'Rendimiento', 'pt-BR': 'Retorno' },
  colCost: { role: 'data', 'en-US': 'Cost', 'es-MX': 'Costo', 'pt-BR': 'Custo' },
  colCostCover: { role: 'data', 'en-US': 'Cost before cover', 'es-MX': 'Costo antes de la cobertura', 'pt-BR': 'Custo antes da cobertura' },
  colFuture: { role: 'data', 'en-US': 'Future', 'es-MX': 'Futuro', 'pt-BR': 'Futuro' },
  colFinal: { role: 'data', 'en-US': 'Final worth', 'es-MX': 'Valor final', 'pt-BR': 'Valor final' },
  colLowest: { role: 'data', 'en-US': 'Lowest balance', 'es-MX': 'Saldo más bajo', 'pt-BR': 'Menor saldo' },
  colSucceeds: { role: 'data', 'en-US': 'Succeeds', 'es-MX': 'Lo logra', 'pt-BR': 'Consegue' },

  metLife: { role: 'body', 'en-US': 'Your choice holds up in enough futures.', 'es-MX': 'Tu elección aguanta en suficientes futuros.', 'pt-BR': 'Sua escolha se sustenta em futuros suficientes.' },
  hintLife: { role: 'body', 'en-US': 'Not yet. Try another choice and watch the futures.', 'es-MX': 'Aún no. Prueba otra elección y mira los futuros.', 'pt-BR': 'Ainda não. Teste outra escolha e veja os futuros.' },
} as const satisfies HorizonteCopy;
