// `money` family — one demo segment per type for /dev/lesson-lab (es-MX content).
// Fixtures are dev data, not UI strings; lesson documents are single-locale (§3).
// MXN denominations: coins ≤ $10, bills ≥ $20.

import type { SegmentBase } from '../../core/types'

export const moneyFixtures: SegmentBase[] = [
  {
    id: 'fx-coin-count',
    type: 'coin_count',
    prompt_md: 'Dina quiere comprar un cuaderno. Paga la cantidad **exacta** tocando monedas y billetes.',
    difficulty: 1,
    xp: 10,
    hints: ['Empieza con el billete más grande que no se pase.'],
    explanation_md: 'Hay varias combinaciones que suman **$37**: por ejemplo $20 + $10 + $5 + $2.',
    narrator: { character: 'dina', emotion: 'happy' },
    payload: {
      currency: 'MXN',
      denominations: [1, 2, 5, 10, 20, 50],
      target: 37,
    },
    answer: {},
  },
  {
    id: 'fx-make-change',
    type: 'make_change',
    prompt_md: 'Liruf pagó su torta con un billete. Dale su **cambio** exacto de la caja.',
    difficulty: 2,
    xp: 15,
    hints: ['El cambio es lo que pagó **menos** el precio.'],
    explanation_md: '$100 − $68 = **$32** de cambio: por ejemplo $20 + $10 + $2.',
    narrator: { character: 'liruf', emotion: 'thinking' },
    payload: {
      currency: 'MXN',
      denominations: [1, 2, 5, 10, 20, 50],
      price: 68,
      paid_with: 100,
    },
    answer: {},
  },
  {
    id: 'fx-piggy-split',
    type: 'piggy_split',
    prompt_md: 'Ganaste **$100** vendiendo limonada. Reparte todo tu dinero entre los frascos.',
    difficulty: 2,
    xp: 15,
    hints: ['Guarda una buena parte para tu meta, pero no olvides compartir.'],
    explanation_md: 'No hay una única respuesta perfecta: lo importante es **ahorrar bastante** sin dejar de disfrutar y compartir.',
    narrator: { character: 'rho', emotion: 'encouraging' },
    payload: {
      income: 100,
      unit: 'MXN',
      jars: [
        { id: 'save', label: 'Ahorrar', icon: 'savings', hint_md: 'Para tu meta grande' },
        { id: 'spend', label: 'Gastar', icon: 'shopping_cart', hint_md: 'Para disfrutar hoy' },
        { id: 'share', label: 'Compartir', icon: 'redeem', hint_md: 'Para ayudar a otros' },
      ],
      step: 10,
    },
    answer: {
      targets: {
        save: { min: 30, max: 60 },
        spend: { min: 20, max: 50 },
        share: { min: 10, max: 30 },
      },
      rationale_md: 'Una buena regla: **ahorra 3 o más de cada 10 pesos**, gasta con plan y comparte un poco.',
    },
  },
  {
    id: 'fx-needs-wants',
    type: 'needs_wants',
    prompt_md: 'Zara está armando su lista. Marca cada cosa: ¿es **necesidad** o **gusto**?',
    difficulty: 1,
    xp: 10,
    explanation_md: 'Las **necesidades** son para vivir bien: agua, útiles, zapatos. Los **gustos** se disfrutan… con plan.',
    narrator: { character: 'zara', emotion: 'thinking' },
    payload: {
      items: [
        { id: 'water', text_md: 'Agua para beber', icon: 'water_drop' },
        { id: 'game', text_md: 'Videojuego nuevo', icon: 'sports_esports' },
        { id: 'shoes', text_md: 'Zapatos para la escuela', icon: 'checkroom' },
        { id: 'candy', text_md: 'Bolsa gigante de dulces', icon: 'icecream' },
        { id: 'books', text_md: 'Útiles escolares', icon: 'school' },
        { id: 'toy', text_md: 'Peluche de dinosaurio', icon: 'toys' },
      ],
    },
    answer: { needs_ids: ['water', 'shoes', 'books'] },
  },
  {
    id: 'fx-price-compare',
    type: 'price_compare',
    prompt_md: 'Tres puestos venden el mismo jugo. ¿Cuál oferta es **la mejor** de verdad?',
    difficulty: 3,
    xp: 20,
    hints: ['Divide el precio entre la cantidad para saber cuánto cuesta **cada uno**.'],
    explanation_md: 'El precio del paquete engaña: compara el precio **por unidad** antes de decidir.',
    narrator: { character: 'zara', emotion: 'happy' },
    payload: {
      offers: [
        { id: 'small', label: 'Paquete chico', qty: 3, unit: 'jugos', price: 30 },
        { id: 'big', label: 'Paquete grande', qty: 6, unit: 'jugos', price: 51 },
        { id: 'duo', label: 'Paquete dúo', qty: 2, unit: 'jugos', price: 22 },
      ],
      currency: 'MXN',
    },
    answer: { best_offer_id: 'big' },
  },
  {
    id: 'fx-budget-fit',
    type: 'budget_fit',
    prompt_md: 'Tienes **$100** para la semana. Llena tu carrito sin pasarte… ¡y sin olvidar lo importante!',
    difficulty: 3,
    xp: 20,
    hints: ['Primero mete las **necesidades**, luego ve si alcanza para un gusto.'],
    explanation_md: 'Primero lo necesario, después los gustos que **sí caben** en el presupuesto.',
    narrator: { character: 'rho', emotion: 'thinking' },
    payload: {
      budget: 100,
      currency: 'MXN',
      items: [
        { id: 'lunch', label: 'Lonche de la semana', icon: 'lunch_dining', price: 30, need: true },
        { id: 'pencils', label: 'Lápices para la escuela', icon: 'school', price: 25, need: true },
        { id: 'game', label: 'Juego nuevo', icon: 'sports_esports', price: 40 },
        { id: 'stickers', label: 'Stickers brillantes', icon: 'sell', price: 15 },
        { id: 'ice', label: 'Helado doble', icon: 'icecream', price: 50 },
        { id: 'toy', label: 'Carrito de colección', icon: 'toys', price: 35 },
      ],
      must_buy_needs: true,
    },
    answer: {},
  },
  {
    id: 'fx-savings-goal',
    type: 'savings_goal',
    prompt_md: 'Quieres una patineta de **$120**. ¿Cuántas semanas tardas con cada plan de ahorro?',
    difficulty: 3,
    xp: 20,
    hints: ['Divide la meta entre lo que ahorras por semana y **redondea hacia arriba**.'],
    explanation_md: 'Ahorrar más por semana llega **más rápido** a la meta: $120 ÷ $40 = 3 semanas.',
    narrator: { character: 'dina', emotion: 'encouraging' },
    payload: {
      goal: 120,
      currency: 'MXN',
      weekly_options: [10, 20, 40],
    },
    answer: { correct: { '10': 12, '20': 6, '40': 3 } },
  },
  {
    id: 'fx-fair-trade',
    type: 'fair_trade',
    prompt_md: 'Liruf ofrece sus stickers por las canicas de Zara. Con la tabla de cambio, ¿el trato es **justo**?',
    difficulty: 4,
    xp: 20,
    hints: ['Convierte los stickers a canicas con la tasa y compara.'],
    explanation_md: '5 stickers × 2 = **10 canicas**. Zara ofrece 10 canicas: el trato es **justo**.',
    narrator: { character: 'liruf', emotion: 'excited' },
    payload: {
      offer_a: { label: 'Stickers de Liruf', icon: 'sell', qty: 5 },
      offer_b: { label: 'Canicas de Zara', icon: 'toys', qty: 10 },
      rate_md: 'Tasa del patio: **1 sticker vale 2 canicas**.',
    },
    answer: { verdict: 'fair' },
  },
  {
    id: 'fx-interest-peek',
    type: 'interest_peek',
    prompt_md: 'Guardas **$100** y cada año crece **10%**. ¿Cuánto habrá al final de 5 años? ¡Predícelo!',
    difficulty: 4,
    xp: 25,
    hints: ['Cada año el interés se calcula sobre el total **nuevo**, no solo sobre los $100.'],
    explanation_md: 'Eso es el **interés compuesto**: el interés también gana interés. $100 → $161.05 en 5 años.',
    narrator: { character: 'rho', emotion: 'excited' },
    payload: {
      principal: 100,
      rate_pct: 10,
      periods: 5,
      currency: 'MXN',
      prediction: { kind: 'slider', min: 100, max: 220 },
    },
    answer: { value: 161.05, tolerance: 10 },
  },
]
