/** Authored coverage inventory, not playable content or an approved lesson graph. */
export const openingBridge = {
  lesson_id: 'fe-production-usable-money-00',
  domain: 'usable-money',
  objective: 'Identify how a completed payment changes the money held by the named person.',
};

export const objectives = {
  'usable-money': [
    'Distinguish money already received from money someone has promised.',
    'Update available cash after one receipt and one payment using a visible count.',
    'Identify which money is already committed to a stated upcoming obligation.',
    'Choose whether a purchase fits after protecting a stated commitment.',
    'Put a receipt and a payment on a timeline to detect a shortage before payday.',
    'Keep borrowed money separate from earnings when explaining what must be repaid.',
    'Avoid counting a transfer between your own containers as new income.',
    'Revise today’s purchase decision after a promised payment is delayed.',
  ],
  'financial-math': [
    'Read a monetary amount with whole units and fractional units in the local notation.',
    'Calculate change by subtracting a price from the amount tendered.',
    'Add several receipts without counting the same receipt twice.',
    'Calculate the shortfall when stated obligations exceed available money.',
    'Calculate the cost of several identical items by multiplication.',
    'Divide a stated shared cost into equal contributions.',
    'Convert a fraction of a whole into an equivalent percentage with a visual grid.',
    'Calculate a percentage of a stated amount.',
    'Recover the whole amount from a given percentage and its monetary value.',
    'Distinguish a percentage-point difference from a relative percentage change.',
    'Compare amounts expressed for different time periods on a common time basis.',
    'Round a monetary calculation at the specified step and explain the remaining difference.',
    'Check whether a financial result is plausible using an approximate calculation.',
  ],
  'goals-tradeoffs': [
    'Translate a broad wish into a goal with an amount, purpose and date.',
    'Separate a stated essential consequence from a preference in a spending decision.',
    'Identify the next-best feasible use forgone when choosing between two purchases.',
    'Rank competing goals using the learner’s stated deadlines and consequences.',
    'Break a goal’s remaining amount into feasible contributions over the time available.',
    'Recognize when changing a goal or its deadline is necessary because no contribution fits.',
    'Choose a small next action that can be checked without requiring spare income.',
    'Revise a goal when its original cost or purpose changes.',
  ],
  'income-work': [
    'Separate recurring, irregular and one-time receipts when estimating future income.',
    'Distinguish gross pay from money received using explicitly explained deductions.',
    'Calculate earnings from a stated hourly rate and paid hours.',
    'Estimate usable income after stated work-related costs.',
    'Identify which payment date, amount or condition is still unknown in a work offer.',
    'Build a conservative income estimate from an irregular payment history.',
    'Separate a household owner’s withdrawal from the receipts and costs of a small activity.',
    'Identify a missing payment using agreed work terms and a payment record.',
    'Compare two work arrangements using stated net income, time and necessary costs.',
    'Find the authoritative source needed to check a claimed benefit or employment entitlement.',
  ],
  'spending-patterns': [
    'Record an expense with enough detail to identify its amount, date and purpose.',
    'Separate a regular commitment from a variable expense without assuming either is optional.',
    'Find an omitted cash expense when reconciling a spending diary with money remaining.',
    'Convert a recurring small purchase into its total cost over a stated period.',
    'Distinguish a predictable irregular expense from an unforeseen event.',
    'Identify an unused recurring charge from a fictional account history.',
    'Choose an expense adjustment that respects explicitly stated household constraints.',
    'Identify a purchase trigger and choose a pause that allows checking the cost.',
    'Compare planned and actual spending without treating every deviation as a personal failure.',
    'Explain why low income can leave a deficit even after discretionary purchases are removed.',
  ],
  'cashflow-budget': [
    'Build a budget using money expected for the same period as its expenses.',
    'Separate a budget category from the account or envelope holding its money.',
    'Reserve money for unavoidable obligations before allocating the remainder.',
    'Calculate a period’s surplus or deficit from a complete set of stated entries.',
    'Build a payment calendar that reveals an otherwise hidden within-month shortfall.',
    'Distinguish a timing problem from a persistent gap between income and expenses.',
    'Allocate an irregular receipt across obligations due before the next reliable receipt.',
    'Spread a known annual bill across the months remaining until it is due.',
    'Rebalance a plan after an expense increases while keeping its totals consistent.',
    'Explain why a sample percentage budget must be adapted when essential costs exceed its allowance.',
    'Choose a feasible response to a deficit without inventing income or assuming borrowing is affordable.',
    'Separate planned saving from money that is accidentally left over.',
    'Close a budget period by comparing the plan with actual receipts and payments.',
    'Carry an unresolved obligation into the next plan without counting it twice.',
  ],
  'accounts-records': [
    'Match a basic transaction, saving or payment need to the relevant account features.',
    'Distinguish a displayed account balance from funds available to withdraw in a stated scenario.',
    'Calculate a fictional account’s total fees from its stated usage and fee schedule.',
    'Read a statement entry’s date, description and amount before classifying it.',
    'Reconcile a statement with a receipt log and identify the unmatched transaction.',
    'Recognize how a pending charge can affect spending decisions before it settles.',
    'Identify the evidence to preserve when reporting an unfamiliar transaction.',
    'Compare account access conditions with a person’s stated device, location and documentation constraints.',
    'Identify which provider and account protection claims require local official verification.',
    'Choose a secure way to retain financial records without exposing access credentials.',
  ],
  'payments-digital': [
    'Distinguish payment from your own balance from a payment that creates a debt.',
    'Check recipient, amount and reference before confirming a transfer.',
    'Separate a payment request or screenshot from confirmed receipt of funds.',
    'Compare payment methods using stated fees, timing and reversibility.',
    'Identify the information that must never be shared to authorize a payment securely.',
    'Recognize a false urgency or impersonation cue in a payment message.',
    'Reach a provider through an independently verified channel after a suspicious message.',
    'Choose the immediate protective response after a device or payment credential is compromised.',
    'Check recurring-payment terms and retain evidence of a cancellation request.',
    'Distinguish a mistaken transfer from an unauthorized payment when preparing a report.',
  ],
  'purchase-decisions': [
    'Compare unit prices after converting quantities to the same unit.',
    'Calculate a final price that includes all explicitly stated mandatory charges.',
    'Calculate the price after one percentage discount.',
    'Calculate successive discounts without adding their percentages.',
    'Check whether a promotion’s minimum spend makes the planned purchase more expensive.',
    'Compare total ownership costs over the same stated period.',
    'Distinguish a warranty, a return policy and a separately purchased protection plan.',
    'Identify a contract’s renewal, cancellation and exit-cost terms before agreeing.',
    'Compare cash and instalment prices using their complete payment schedules.',
    'Recognize a misleading comparison that uses different quantities or periods.',
    'Choose what missing information must be obtained before a defensible purchase comparison.',
    'Decide whether to repair, replace or postpone using stated costs and functional needs.',
  ],
  'saving-resilience': [
    'Separate money for a predictable bill from money for an unforeseen disruption.',
    'Estimate essential expenses during a stated income interruption.',
    'Set an initial emergency reserve target using the scenario’s actual risks and feasible contributions.',
    'Choose where to keep a near-term reserve using stated access, safety and fee conditions.',
    'Calculate the time needed to reach a goal with a fixed feasible contribution and no assumed return.',
    'Adjust a contribution plan after a missed contribution without concealing the gap.',
    'Choose when an automatic transfer would create a payment shortfall.',
    'Allocate a windfall among stated urgent obligations and goals without assuming one universal rule.',
    'Decide whether a stated expense fits the purpose of an emergency reserve.',
    'Build a replenishment plan after using part of a reserve.',
  ],
  'time-inflation': [
    'Calculate simple interest using an explicitly stated principal, rate and period.',
    'Distinguish earned interest from a contribution to an account.',
    'Calculate a second period’s compound growth after adding the first period’s interest.',
    'Compare simple and compound growth under the same stated assumptions.',
    'Separate the effect of contributions from the effect of modeled returns.',
    'Calculate the nominal price change for a fixed basket of goods.',
    'Determine whether a stated nominal income change keeps up with a stated basket’s price change.',
    'Distinguish an economy-wide inflation measure from one household’s changing expenses.',
    'Compare nominal growth with purchasing-power growth under explicit assumptions.',
    'Identify why a constant-return projection is a model rather than a guaranteed outcome.',
  ],
  'credit-mechanics': [
    'Identify principal, interest and fees in a fictional loan agreement.',
    'Calculate the total amount repaid from a complete payment schedule.',
    'Calculate a period’s interest on the explicitly stated outstanding balance.',
    'Separate a payment’s interest component from its principal reduction.',
    'Update the outstanding principal after a payment.',
    'Compare loans with different payment sizes using total cost and duration.',
    'Check whether a proposed payment fits the borrower’s existing cash-flow plan.',
    'Explain the consequence of a missed payment using the agreement’s stated terms.',
    'Distinguish collateral at risk from the amount originally borrowed.',
    'Identify how a variable-rate clause could change future payments.',
    'Compare periodic rates only after aligning periods and compounding assumptions.',
    'Identify which disclosed annual cost measure and included charges need local interpretation.',
  ],
  'credit-products': [
    'Read a fictional card statement’s balance, minimum payment and due date.',
    'Distinguish the statement closing date from the payment due date.',
    'Determine whether a fictional card’s stated grace-period conditions have been met.',
    'Trace how minimum-only payments affect a balance under a supplied schedule.',
    'Identify the separate costs of a cash advance in a fictional card agreement.',
    'Place multiple buy-now-pay-later instalments on one payment calendar.',
    'Distinguish an overdraft facility from money owned in an account.',
    'Compare a secured loan and an unsecured loan using their stated costs and consequences.',
    'Identify a guarantor’s obligation from a plainly stated guarantee agreement.',
    'Recognize a high-cost short-term loan whose renewal adds cost without reducing principal.',
  ],
  'debt-recovery': [
    'Build a debt inventory containing balances, costs, deadlines and stated consequences.',
    'Prioritize immediate consequences before applying a simple balance or rate ordering.',
    'Compare highest-rate-first and smallest-balance-first repayment using the same feasible surplus.',
    'Identify information to gather before asking a creditor about an unaffordable payment.',
    'Compare a proposed restructuring using total cost, term and payment feasibility.',
    'Check whether consolidation reduces total cost or only lowers the monthly payment.',
    'Detect an upfront-fee debt-relief claim that lacks verifiable terms or authority.',
    'Find qualified local support when no feasible repayment plan covers essential needs.',
  ],
  'credit-records': [
    'Distinguish a credit report’s recorded information from a score derived from it.',
    'Match a fictional credit-report entry to the corresponding account record.',
    'Identify a factual error and assemble supporting evidence for a dispute.',
    'Separate a verified local credit-report process from a promise to erase accurate history.',
    'Explain why an advertised score threshold cannot guarantee a lending decision.',
    'Choose protective steps after discovering an account the person did not open.',
  ],
  'insurance-risk': [
    'Distinguish a frequent manageable loss from a less frequent financially severe loss.',
    'Match a stated risk to prevention, a reserve or risk transfer without treating one as sufficient for all risks.',
    'Identify the policyholder, insured event and beneficiary in a fictional policy.',
    'Separate a premium from a deductible or excess.',
    'Calculate a claim’s out-of-pocket cost under a stated deductible and coverage limit.',
    'Identify an exclusion that prevents coverage in a given scenario.',
    'Compare policies only after aligning coverage, limits and deductibles.',
    'Check whether a waiting period leaves a stated near-term event uncovered.',
    'Identify documents and deadlines to preserve for a fictional claim.',
    'Detect overlapping coverage without assuming all overlap is useless.',
    'Reassess a protection need after a dependent or financial obligation changes.',
    'Distinguish an insurance protection feature from an investment projection in a combined offer.',
  ],
  'investing-foundations': [
    'Separate investing from keeping money needed for a near-term obligation accessible.',
    'Match a goal’s time horizon with the consequence of a temporary investment loss.',
    'Distinguish willingness to accept loss from financial capacity to absorb it.',
    'Separate an investment’s income payments from changes in its sale value.',
    'Distinguish owning a share from lending through a bond.',
    'Explain a bond’s credit risk using a borrower unable to make a promised payment.',
    'Explain why a fixed-rate bond’s resale price can change before maturity.',
    'Identify concentration risk when several holdings depend on the same source of income.',
    'Compare diversified and concentrated fictional portfolios under a common shock.',
    'Distinguish a pooled fund from the assets it holds.',
    'Identify liquidity restrictions that conflict with a stated withdrawal need.',
    'Separate a regulated custody arrangement from a promise of guaranteed market returns.',
    'Identify leverage that can magnify a loss beyond an unleveraged price change.',
    'Recognize speculation in a volatile asset without treating past gains as evidence of safety.',
  ],
  'investment-comparison': [
    'Calculate an investment’s stated return after explicit transaction and ongoing fees.',
    'Compare reported performance over the same period and with consistent treatment of distributions.',
    'Identify missing risk information in an offer that displays only its best historical return.',
    'Compare a fund’s stated objective and holdings with the exposure a learner intended to obtain.',
    'Distinguish an index-tracking strategy from a promise to beat the market.',
    'Explain currency exposure when the spending goal and investment use different currencies.',
    'Identify a conflict of interest in how an investment seller is compensated.',
    'Check whether a proposed portfolio adjustment restores a stated allocation or follows recent hype.',
    'Identify which tax, fee or withdrawal assumptions prevent a fair net-return comparison.',
    'Reject an unverifiable guaranteed-high-return claim using independent verification steps.',
  ],
  'tax-public-systems': [
    'Distinguish a tax, a fee and a social contribution in explicitly labeled examples.',
    'Separate tax withheld during the year from a final tax calculation.',
    'Calculate tax in a fictional progressive bracket system without applying the top rate to all income.',
    'Distinguish a deduction from a credit using a fictional simplified calculation.',
    'Identify records needed to substantiate a fictional income or expense declaration.',
    'Find the official local source for a deadline or filing obligation instead of importing another country’s rule.',
    'Recognize that a benefit’s eligibility and withdrawal conditions must be checked before budgeting it.',
    'Separate legitimate tax planning from hiding or falsifying facts in a financial record.',
  ],
  'retirement-future': [
    'Separate an intended retirement spending need from a projected account balance.',
    'Identify the different roles of public benefits, employer arrangements and personal savings.',
    'Read contribution and ownership conditions in a fictional employer retirement arrangement.',
    'Compare starting contributions earlier or later under the same explicit projection assumptions.',
    'Identify how fees affect a long-term projection without treating the projection as guaranteed.',
    'Recognize inflation and longevity as separate risks to a retirement spending plan.',
    'Check access restrictions before treating retirement assets as an emergency reserve.',
    'Identify how early poor returns can affect withdrawals from a fictional retirement portfolio.',
    'Reassess contributions when income changes while preserving near-term essential obligations.',
    'Identify which beneficiary and account records need review after a major life change.',
  ],
  'housing-transport': [
    'Calculate move-in costs separately from recurring housing costs.',
    'Compare housing options using transport, utilities and other stated necessary costs.',
    'Read a fictional rental agreement’s deposit, notice and repair responsibilities.',
    'Separate a home purchase price from financing, transaction and ongoing ownership costs.',
    'Explain how a down payment changes borrowing needs without making ownership automatically affordable.',
    'Stress-test a housing payment under a stated income drop or variable-rate increase.',
    'Compare renting and buying over a stated horizon without assuming property prices always rise.',
    'Calculate a vehicle’s total ownership cost including maintenance, insurance and depreciation assumptions.',
    'Compare vehicle finance offers including deposits, instalments and final balloon payments.',
    'Compare a lease with a purchase using mileage, return conditions and total stated costs.',
    'Identify repair or maintenance costs that a purchase price does not cover.',
    'Choose a feasible housing or transport adjustment using the household’s stated accessibility and time constraints.',
  ],
  'shared-finances': [
    'Compare equal and income-proportional shared contributions under explicitly agreed rules.',
    'Separate account access from legal ownership or debt liability that requires local verification.',
    'Create a shared-payment agreement that identifies amount, responsibility and review date.',
    'Recognize financial coercion and identify a safe support option without requiring confrontation.',
    'Revise a plan for a stated caregiving period with reduced paid work.',
    'Distinguish an affordable gift from a family loan requiring clear repayment expectations.',
    'Identify account, contract and access records needed when a household separates.',
    'Identify estate and decision-authority questions that require qualified local advice after a death or incapacity.',
  ],
  'financial-landscape': [
    'Verify a financial provider’s identity and permitted activity using the relevant official register.',
    'Distinguish provider regulation from protection against every possible loss.',
    'Check the scope and eligibility conditions of a local deposit-protection claim.',
    'Prepare a complaint with a clear requested remedy and supporting transaction evidence.',
    'Identify the official escalation route after a provider’s complaint response is unresolved.',
    'Calculate how much a recipient receives after a remittance fee and a stated exchange rate.',
    'Compare remittance offers using recipient amount, timing and collection conditions.',
    'Identify a currency-conversion markup when the reference comparison rate is supplied.',
    'Distinguish a specific verifiable sustainability claim from an unsupported financial-product label.',
    'Check who receives financial data and how consent can be withdrawn before enabling a sharing service.',
  ],
  'integrated-decisions': [
    'Revise a household’s next-month plan after an income interruption and an unavoidable bill.',
    'Compare a reserve withdrawal with a proposed loan using near-term access needs and complete loan costs.',
    'Resolve a budget shortfall without silently dropping a dependent’s essential expense.',
    'Evaluate a job move using net pay, relocation costs, timing and lost benefits.',
    'Choose which facts must be verified before financing an urgent replacement purchase.',
    'Reconcile multiple accounts and pending transactions before committing money to a goal.',
    'Compare a debt repayment and a long-term investment contribution under stated risks and constraints.',
    'Revise protection and cash-flow plans when a household takes on a new dependent.',
    'Respond to a suspected scam while preserving essential payments and evidence.',
    'Revise a retirement projection after a change in costs without promising an exact future outcome.',
    'Compare two cross-border payment plans while accounting for uncertainty in the receipt date.',
    'Build an evidence-backed action plan that separates decisions possible now from questions needing qualified help.',
  ],
};
