#!/usr/bin/env bash
# export-course-fixture.sh <course-slug> [output-file] — LOCAL DEV ONLY.
#
# Snapshots one Forge-generated course's full row set (courses -> adventures
# -> sagas -> topics -> lessons -> lesson_documents, in FK dependency order,
# with original ids preserved) into a single portable, idempotent .sql file.
# Meant to be git-committed so ANY developer can `import-course-fixture.sh`
# it into their own local Vault and get a playable course in seconds — no
# DeepSeek/Qwen/Gemini spend, no waiting on the generation pipeline.
#
# KNOWN LIMITATION: lesson_documents.document/audio may reference image and
# audio URLs pointing at whoever's local filebase generated them
# (http://localhost:4006/files/...) — those links will 404 for anyone else,
# since only the manifests (small JSON) are exported, not the underlying
# binary files. Icons remain the fallback for missing images (DESIGN.md /
# LESSON_ENGINE.md), so the lesson still renders and grades correctly either
# way; only the illustration/audio playback itself is unavailable until that
# developer regenerates it locally (cheap — a few cents, see audiogen/README).
#
# Usage: bash scripts/export-course-fixture.sh first-lemonade-stand \
#          seeds/qa-course-fixture.sql

set -euo pipefail

DB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SLUG="${1:-}"
OUT="${2:-$DB_DIR/seeds/${SLUG}-fixture.sql}"

if [[ -z "$SLUG" ]]; then
  echo "Usage: $0 <course-slug> [output-file]" >&2
  exit 1
fi

{
  echo "-- Generated by database/scripts/export-course-fixture.sh — course '$SLUG'."
  echo "-- Idempotent: safe to re-run against any Vault instance with migrations applied."
  echo "-- DO NOT hand-edit — regenerate with the export script instead."
  echo "BEGIN;"
} > "$OUT"

bash "$DB_DIR/scripts/local-stack.sh" psql -t -A -q -v slug="'$SLUG'" >> "$OUT" <<'SQL'
WITH c AS (
  SELECT * FROM courses WHERE slug = :slug
), a AS (
  SELECT * FROM adventures WHERE course_id IN (SELECT id FROM c)
), s AS (
  SELECT * FROM sagas WHERE adventure_id IN (SELECT id FROM a)
), t AS (
  SELECT * FROM topics WHERE saga_id IN (SELECT id FROM s)
), l AS (
  SELECT * FROM lessons WHERE topic_id IN (SELECT id FROM t)
), ld AS (
  SELECT * FROM lesson_documents WHERE lesson_id IN (SELECT id FROM l)
)
SELECT format(
  'INSERT INTO courses (id, slug, title, status, subject, description, position, requires) VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
  id, slug, title, status, subject, description, position, requires
) FROM c
UNION ALL
SELECT format(
  'INSERT INTO adventures (id, course_id, position, slug, title, description, narrative_arc, theme, age_tier, status) VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
  id, course_id, position, slug, title, description, narrative_arc, theme, age_tier, status
) FROM a
UNION ALL
SELECT format(
  'INSERT INTO sagas (id, adventure_id, position, slug, title, description, icon, status) VALUES (%L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
  id, adventure_id, position, slug, title, description, icon, status
) FROM s
UNION ALL
SELECT format(
  'INSERT INTO topics (id, saga_id, position, slug, title, concept_md, learning_objective, key_vocabulary, prior_knowledge, status) VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
  id, saga_id, position, slug, title, concept_md, learning_objective, key_vocabulary, prior_knowledge, status
) FROM t
UNION ALL
SELECT format(
  'INSERT INTO lessons (id, topic_id, position, slug, title, difficulty, xp_total, estimated_minutes, "cast", status) VALUES (%L, %L, %L, %L, %L, %L, %L, %L, %L, %L) ON CONFLICT (id) DO NOTHING;',
  id, topic_id, position, slug, title, difficulty, xp_total, estimated_minutes, "cast", status
) FROM l
UNION ALL
SELECT format(
  'INSERT INTO lesson_documents (lesson_id, locale, schema_version, document, answer_keys, audio) VALUES (%L, %L, %L, %L, %L, %L) ON CONFLICT (lesson_id, locale) DO NOTHING;',
  lesson_id, locale, schema_version, document, answer_keys, audio
) FROM ld;
SQL

echo "COMMIT;" >> "$OUT"

ROWS=$(grep -c '^INSERT INTO' "$OUT" || true)
echo "OK: exported $ROWS row(s) for '$SLUG' -> $OUT"
