import { spendingFrequency } from './spending-frequency.mjs';
import { spendingChoices } from './spending-choices.mjs';
import { spendingTriggers } from './spending-triggers.mjs';
import { spendingGaps } from './spending-gaps.mjs';
import { spendingReviews } from './spending-reviews.mjs';
import { budgetPeriods } from './budget-periods.mjs';
import { budgetReserves } from './budget-reserves.mjs';
import { budgetCalendar } from './budget-calendar.mjs';
import { budgetIrregular } from './budget-irregular.mjs';
import { budgetRebalance } from './budget-rebalance.mjs';
import { budgetResponses } from './budget-responses.mjs';
import { budgetClose } from './budget-close.mjs';
import { budgetReviews } from './budget-reviews.mjs';
import { accountsPurpose } from './accounts-purpose.mjs';
import { accountsFees } from './accounts-fees.mjs';
import { accountsStatements } from './accounts-statements.mjs';
import { accountsReconcile } from './accounts-reconcile.mjs';
import { accountsEvidence } from './accounts-evidence.mjs';
import { accountsProtection } from './accounts-protection.mjs';
import { accountsStorage } from './accounts-storage.mjs';
import { accountsReviews } from './accounts-reviews.mjs';
import { paymentsFunding } from './payments-funding.mjs';
import { paymentsConfirm } from './payments-confirm.mjs';
import { paymentsMethods } from './payments-methods.mjs';
import { spendingRecords } from './spending-records.mjs';
import { basic } from './math-basic.mjs';
import { groups } from './math-groups.mjs';
import { percentages } from './math-percent.mjs';
import { checks } from './math-checks.mjs';
import { mathReviews } from './math-reviews.mjs';
import { goalsStart } from './goals-start.mjs';
import { goalsPlan } from './goals-plan.mjs';
import { goalsAction } from './goals-action.mjs';
import { goalsReviews } from './goals-reviews.mjs';
import { incomeBasics } from './income-basics.mjs';
import { incomeTerms } from './income-terms.mjs';
import { incomeVariability } from './income-variability.mjs';
import { incomeChecks } from './income-checks.mjs';
import { incomeReviews } from './income-reviews.mjs';
import { sequence, skillFor, write } from './factory.mjs';
import { localizedObjective } from './skill-localization.mjs';
import { paymentsSecrets } from './payments-secrets.mjs';
import { paymentsPressure } from './payments-pressure.mjs';
import { paymentsChannel } from './payments-channel.mjs';
import { paymentsContain } from './payments-contain.mjs';
import { paymentsRecurring } from './payments-recurring.mjs';
import { paymentsReport } from './payments-report.mjs';
import { paymentsReviews } from './payments-reviews.mjs';
export const plans=[...basic,...groups,...percentages,...checks,...mathReviews,...goalsStart,...goalsPlan,...goalsAction,...goalsReviews,...incomeBasics,...incomeTerms,...incomeVariability,...incomeChecks,...incomeReviews,...spendingRecords,...spendingFrequency,...spendingChoices,...spendingTriggers,...spendingGaps,...spendingReviews,...budgetPeriods,...budgetReserves,...budgetCalendar,...budgetIrregular,...budgetRebalance,...budgetResponses,...budgetClose,...budgetReviews,...accountsPurpose,...accountsFees,...accountsStatements,...accountsReconcile,...accountsEvidence,...accountsProtection,...accountsStorage,...accountsReviews,...paymentsFunding,...paymentsConfirm,...paymentsMethods,...paymentsSecrets,...paymentsPressure,...paymentsChannel,...paymentsContain,...paymentsRecurring,...paymentsReport,...paymentsReviews];
export const metadata=plans.map(p=>({lesson_id:p.lesson_id,kc_suffix:p.instruction.objective.skill_id,title:p.title,objective:localizedObjective(p),prerequisite_lesson_ids:sequence.lessons.find(x=>x.lesson_id===p.lesson_id).prerequisites}));
export function buildPlans(resolveKc) {
 if(!resolveKc)return structuredClone(plans);
 const replacements=new Map(sequence.lessons.filter(x=>x.kind==='teach').map(x=>[skillFor(x.lesson_id),resolveKc(x.lesson_id)?.replace(/^finance\./,'')??skillFor(x.lesson_id)]));
 const replace=value=>typeof value==='string'?(replacements.get(value)??(value.startsWith('finance.')&&replacements.has(value.slice(8))?`finance.${replacements.get(value.slice(8))}`:value)):Array.isArray(value)?value.map(replace):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,replace(v)])):value;
 return plans.map(replace);
}
if(process.argv[1]?.replaceAll('\\','/').endsWith('/foundations/index.mjs'))write(plans);
