import { lesson, E, Q, I, op } from './factory.mjs';
const sub=(a,b)=>op('subtract',I(a),I(b)), add=(a,b)=>op('add',I(a),I(b));
export const basic=[
lesson('financial-math',1,'Units and cents|Unidades y centavos|Unidades e centavos','Read a price before comparing it with your money.|Lee un precio antes de compararlo con tu dinero.|Leia um preço antes de compará-lo com seu dinheiro.','Treat the decimal separator as decoration or read cents as whole units.',[
 E('example-01','Read both parts|Lee ambas partes|Leia as duas partes','12.50 means twelve dollars and fifty cents; the digits after the point count hundredths.|12.50 significa doce pesos y cincuenta centavos; los dígitos después del punto cuentan centésimos.|12,50 significa doze reais e cinquenta centavos; os dígitos após a vírgula contam centésimos.'),
 Q('guided-01','guided','The price is 8.25. Read units before the point, cents after it.|El precio es 8.25. Lee unidades antes del punto y centavos después.|O preço é 8,25. Leia unidades antes da vírgula e centavos depois.','What does it mean?|¿Qué significa?|O que significa?',['Eight dollars, twenty-five cents|Ocho pesos, veinticinco centavos|Oito reais, vinte e cinco centavos','Eight hundred dollars|Ochocientos pesos|Oitocentos reais','Twenty-five dollars|Veinticinco pesos|Vinte e cinco reais'],'Both parts contribute to the price.|Ambas partes forman el precio.|As duas partes formam o preço.','Separate whole units from hundredths.|Separa unidades enteras de centésimos.|Separe unidades inteiras de centésimos.'),
 Q('guided-02','guided','A label says 3.05. Two digits after the point show cents.|Una etiqueta dice 3.05. Dos dígitos después del punto indican centavos.|Uma etiqueta diz 3,05. Dois dígitos após a vírgula indicam centavos.','Which reading matches?|¿Qué lectura coincide?|Qual leitura corresponde?',['Three dollars, five cents|Tres pesos, cinco centavos|Três reais, cinco centavos','Three dollars, fifty cents|Tres pesos, cincuenta centavos|Três reais, cinquenta centavos','Thirty-five dollars|Treinta y cinco pesos|Trinta e cinco reais'],'The zero keeps five in the hundredths position.|El cero coloca el cinco en los centésimos.|O zero mantém o cinco na posição dos centésimos.','Five cents and fifty cents differ.|Cinco y cincuenta centavos son distintos.|Cinco e cinquenta centavos são diferentes.'),
 Q('practice-01','practice','A fare costs 6.80.|Un pasaje cuesta 6.80.|Uma passagem custa 6,80.','What is its fractional part?|¿Cuál es su parte fraccionaria?|Qual é sua parte fracionária?',['Eighty cents|Ochenta centavos|Oitenta centavos','Eight cents|Ocho centavos|Oito centavos','Six cents|Seis centavos|Seis centavos'],'The two decimal digits name eighty hundredths.|Los dos decimales indican ochenta centésimos.|Os dois decimais indicam oitenta centésimos.','Read both decimal digits together.|Lee juntos ambos dígitos decimales.|Leia os dois dígitos decimais juntos.'),
 Q('practice-02','practice','A refund is 0.75.|Una devolución es de 0.75.|Um reembolso é de 0,75.','What arrived?|¿Qué llegó?|O que chegou?',['Seventy-five cents|Setenta y cinco centavos|Setenta e cinco centavos','Seventy-five dollars|Setenta y cinco pesos|Setenta e cinco reais','Seven dollars|Siete pesos|Sete reais'],'Zero whole units can still include cents.|Cero unidades enteras puede incluir centavos.|Zero unidades inteiras ainda pode incluir centavos.','The whole-unit part is zero.|La parte entera es cero.|A parte inteira é zero.'),
 Q('practice-03','practice','One tag reads 4.50; another reads 4.05.|Una etiqueta dice 4.50; otra dice 4.05.|Uma etiqueta diz 4,50; outra diz 4,05.','Which costs less?|¿Cuál cuesta menos?|Qual custa menos?',['The five-cent tag|La etiqueta de cinco centavos|A etiqueta de cinco centavos','The fifty-cent tag|La etiqueta de cincuenta centavos|A etiqueta de cinquenta centavos','They are equal|Cuestan lo mismo|Custam o mesmo'],'With equal whole units, five cents is less than fifty.|Con unidades iguales, cinco centavos es menos que cincuenta.|Com unidades iguais, cinco centavos é menos que cinquenta.','Compare the fractional parts.|Compara las partes fraccionarias.|Compare as partes fracionárias.'),
 Q('transfer-01','transfer','A statement shows a fee of 10.02.|Un estado de cuenta muestra un cargo de 10.02.|Um extrato mostra uma tarifa de 10,02.','How should you read it?|¿Cómo debes leerlo?|Como deve ler?',['Ten dollars and two cents|Diez pesos y dos centavos|Dez reais e dois centavos','Ten dollars and twenty cents|Diez pesos y veinte centavos|Dez reais e vinte centavos','One hundred two dollars|Ciento dos pesos|Cento e dois reais'],'Two hundredths means two cents, not twenty.|Dos centésimos son dos centavos, no veinte.|Dois centésimos são dois centavos, não vinte.','Keep the zero in its position.|Conserva el cero en su posición.|Mantenha o zero na posição.')]),
lesson('financial-math',2,'Check your change|Revisa tu cambio|Confira seu troco','Check what must return after paying cash.|Revisa cuánto debe volver al pagar en efectivo.|Confira quanto deve voltar ao pagar em dinheiro.','Subtract the tendered amount from the price or accept any returned amount.',[
 E('example-01','Subtract the price|Resta el precio|Subtraia o preço','Hand over 20 for a price of 14: 20 − 14 = 6 change. Price plus change restores the amount handed over.|Entregas 20 por un precio de 14: 20 − 14 = 6 de cambio. Precio más cambio recupera lo entregado.|Entrega 20 por um preço de 14: 20 − 14 = 6 de troco. Preço mais troco recupera o entregue.'),
 Q('guided-01','guided','Hand over 30; the price is 18. Subtract the price.|Entregas 30; el precio es 18. Resta el precio.|Entrega 30; o preço é 18. Subtraia o preço.','Change due?|¿Cambio debido?|Troco devido?',['12|12|12','48|48|48','18|18|18'],'The unused part must return.|La parte no utilizada debe volver.|A parte não utilizada deve voltar.','Start with the amount handed over.|Empieza con lo entregado.|Comece pelo valor entregue.',[[30,18],sub(0,1)]),
 Q('guided-02','guided','The price is 7; you hand over 10 and receive 3.|El precio es 7; entregas 10 y recibes 3.|O preço é 7; entrega 10 e recebe 3.','How can you check?|¿Cómo puedes comprobarlo?|Como conferir?',['Add price and change|Suma precio y cambio|Some preço e troco','Add price twice|Suma el precio dos veces|Some o preço duas vezes','Ignore the price|Ignora el precio|Ignore o preço'],'Price and change together equal the money handed over.|Precio y cambio juntos igualan lo entregado.|Preço e troco juntos igualam o entregue.','Reconstruct the original payment.|Reconstruye el pago original.|Reconstrua o pagamento original.'),
 Q('practice-01','practice','A ticket costs 26. You hand over 50.|Un boleto cuesta 26. Entregas 50.|Um ingresso custa 26. Entrega 50.','What change is due?|¿Qué cambio corresponde?|Qual troco é devido?',['24|24|24','76|76|76','26|26|26'],'Subtract the ticket cost from the tendered amount.|Resta el boleto del monto entregado.|Subtraia o ingresso do valor entregue.','Change is the unused part.|El cambio es la parte no usada.|Troco é a parte não usada.',[[26,50],sub(1,0)]),
 Q('practice-02','practice','You hand over 40 for groceries costing 32; the cashier returns 5.|Entregas 40 por compras de 32; te devuelven 5.|Entrega 40 por compras de 32; recebe 5.','What should you check?|¿Qué debes revisar?|O que deve conferir?',['Three more are due|Faltan tres de cambio|Faltam três de troco','The change is exact|El cambio es exacto|O troco está exato','Five must be returned|Debes devolver cinco|Deve devolver cinco'],'The full change is eight; only five arrived.|El cambio completo es ocho; solo llegaron cinco.|O troco completo é oito; só chegaram cinco.','Compare expected change with received change.|Compara cambio esperado y recibido.|Compare troco esperado e recebido.'),
 Q('practice-03','practice','A repair costs 35; you hand over exactly 35.|Una reparación cuesta 35; entregas exactamente 35.|Um conserto custa 35; entrega exatamente 35.','Change due?|¿Cambio debido?|Troco devido?',['0|0|0','35|35|35','70|70|70'],'An exact payment leaves no change.|Un pago exacto no deja cambio.|Um pagamento exato não deixa troco.','Both amounts are equal.|Ambos montos son iguales.|Os dois valores são iguais.',[[35,35],sub(1,0)]),
 Q('transfer-01','transfer','You hand over 100. A market stall charges 64 including the bag.|Entregas 100. El puesto cobra 64 incluyendo la bolsa.|Entrega 100. A banca cobra 64 incluindo a sacola.','What must return?|¿Cuánto debe volver?|Quanto deve voltar?',['36|36|36','64|64|64','164|164|164'],'Use the complete charge, including the bag.|Usa el cargo completo, incluida la bolsa.|Use a cobrança completa, incluindo a sacola.','Subtract the complete price once.|Resta el precio completo una vez.|Subtraia o preço completo uma vez.',[[100,64],sub(0,1)])]),
lesson('financial-math',3,'Count each receipt once|Cuenta cada entrada una vez|Conte cada entrada uma vez','Records help total receipts without duplicating money.|Los registros permiten sumar entradas sin duplicar dinero.|Registros permitem somar entradas sem duplicar dinheiro.','Count the same receipt again because it appears in two records.',[
 E('example-01','Match the event|Identifica el evento|Identifique o evento','One payment of 30 appears in two records. Count it once; another payment of 20 makes 50.|Una entrada de 30 aparece en diario y estado de cuenta. Es una entrada; suma otra de 20 para obtener 50.|Uma entrada de 30 aparece no diário e extrato. É uma entrada; some outra de 20 para obter 50.'),
 Q('guided-01','guided','Two separate receipts are 12 and 18. Add each once.|Dos entradas distintas son 12 y 18. Suma cada una una vez.|Duas entradas distintas são 12 e 18. Some cada uma uma vez.','Total received?|¿Total recibido?|Total recebido?',['30|30|30','18|18|18','60|60|60'],'Separate completed receipts both belong in the total.|Ambas entradas realizadas pertenecen al total.|As duas entradas concluídas pertencem ao total.','Add the distinct events.|Suma los eventos distintos.|Some os eventos distintos.',[[12,18],add(0,1)]),
 Q('guided-02','guided','A bank alert and statement show the same refund.|Una alerta y el estado de cuenta muestran la misma devolución.|Um alerta e o extrato mostram o mesmo reembolso.','How often do you count it?|¿Cuántas veces lo cuentas?|Quantas vezes contar?',['Once|Una vez|Uma vez','Twice|Dos veces|Duas vezes','Never|Nunca|Nunca'],'Two records can describe one movement.|Dos registros pueden describir un movimiento.|Dois registros podem descrever um movimento.','Match the event, not the number of records.|Identifica el evento, no la cantidad de registros.|Identifique o evento, não a quantidade de registros.'),
 Q('practice-01','practice','Separate cash receipts are 10, 15 and 25.|Entradas distintas en efectivo: 10, 15 y 25.|Entradas distintas em dinheiro: 10, 15 e 25.','Total received?|¿Total recibido?|Total recebido?',['50|50|50','40|40|40','25|25|25'],'Every distinct receipt contributes once.|Cada entrada distinta contribuye una vez.|Cada entrada distinta contribui uma vez.','Include all three events.|Incluye los tres eventos.|Inclua os três eventos.',[[10,15,25],op('add',add(0,1),I(2))]),
 Q('practice-02','practice','You transfer money from your own account to your own wallet.|Transfieres dinero de tu cuenta a tu propia cartera.|Transfere dinheiro da sua conta para sua própria carteira.','Does total owned money grow?|¿Crece tu dinero total?|Seu dinheiro total aumenta?',['No, its location changes|No, cambia de lugar|Não, muda de lugar','Yes, it is new income|Sí, es ingreso nuevo|Sim, é renda nova','Yes, if recorded twice|Sí, si se registra dos veces|Sim, se registrar duas vezes'],'Moving your money does not create another receipt of income.|Mover tu dinero no crea otro ingreso.|Mover seu dinheiro não cria outra renda.','Follow both sides of the transfer.|Sigue ambos lados de la transferencia.|Acompanhe os dois lados da transferência.'),
 Q('practice-03','practice','Two customers each paid 20; they have different payment references.|Dos clientes pagaron 20 cada uno; tienen referencias distintas.|Dois clientes pagaram 20 cada; têm referências diferentes.','Which record is appropriate?|¿Qué registro corresponde?|Qual registro corresponde?',['Keep both receipts|Conserva ambas entradas|Mantenha as duas entradas','Delete one equal amount|Borra uno por ser igual|Apague um por ser igual','Record neither|No registres ninguno|Não registre nenhum'],'Equal amounts can still be separate payments.|Montos iguales pueden ser pagos distintos.|Valores iguais podem ser pagamentos distintos.','Check identity before removing a duplicate.|Verifica identidad antes de eliminar un duplicado.|Verifique identidade antes de remover duplicata.'),
 Q('transfer-01','transfer','A fundraiser log lists gift A twice and gift B once. A is one confirmed payment.|Una colecta registra donativo A dos veces y B una. A es un único pago confirmado.|Uma coleta registra doação A duas vezes e B uma. A é um único pagamento confirmado.','Total these receipts?|¿Cómo sumas las entradas?|Como somar entradas?',['Count A and B once each|Cuenta A y B una vez|Conte A e B uma vez','Count every line|Cuenta cada renglón|Conte cada linha','Discard both gifts|Descarta ambos donativos|Descarte as duas doações'],'Unique payment identities prevent duplicate totals.|Identificar pagos únicos evita totales duplicados.|Identificar pagamentos únicos evita totais duplicados.','One duplicated record is not another gift.|Un registro duplicado no es otro donativo.|Um registro duplicado não é outra doação.')]),
lesson('financial-math',4,'Find the shortfall|Encuentra lo que falta|Encontre o que falta','Knowing the gap lets you respond before a payment fails.|Conocer la diferencia permite actuar antes de incumplir un pago.|Conhecer a diferença permite agir antes de faltar um pagamento.','Treat a shortfall as the whole bill or invent money to erase it.',[
 E('example-01','Need minus available|Necesario menos disponible|Necessário menos disponível','A bill needs 90; you have 65. Subtract what you have: 90 − 65 = 25 still needed.|Una cuenta requiere 90; tienes 65. Resta lo que tienes: 90 − 65 = 25 faltantes.|Uma conta exige 90; você tem 65. Subtraia o que tem: 90 − 65 = 25 faltantes.'),
 Q('guided-01','guided','Need 70; available 50. Subtract available money from the need.|Necesitas 70; disponibles 50. Resta lo disponible de lo necesario.|Precisa de 70; disponíveis 50. Subtraia o disponível do necessário.','How much is missing?|¿Cuánto falta?|Quanto falta?',['20|20|20','70|70|70','120|120|120'],'Only the uncovered part is missing.|Solo falta la parte no cubierta.|Só falta a parte não coberta.','Start with the obligation.|Empieza con la obligación.|Comece pela obrigação.',[[70,50],sub(0,1)]),
 Q('guided-02','guided','Two bills need 30 and 20; you have 40.|Dos cuentas requieren 30 y 20; tienes 40.|Duas contas exigem 30 e 20; você tem 40.','What must you do first?|¿Qué debes hacer primero?|O que fazer primeiro?',['Add both bills|Suma ambas cuentas|Some as duas contas','Ignore the smaller bill|Ignora la cuenta menor|Ignore a conta menor','Count available money twice|Cuenta tu dinero dos veces|Conte seu dinheiro duas vezes'],'The gap must cover all stated obligations.|La diferencia debe cubrir todas las obligaciones indicadas.|A diferença deve cobrir todas as obrigações informadas.','Find the complete need before subtracting.|Encuentra la necesidad completa antes de restar.|Encontre a necessidade completa antes de subtrair.'),
 Q('practice-01','practice','Medicine costs 85; available money is 60.|Las medicinas cuestan 85; tienes disponibles 60.|Os remédios custam 85; há 60 disponíveis.','How much is missing?|¿Cuánto falta?|Quanto falta?',['25|25|25','145|145|145','60|60|60'],'The shortfall is the cost above available money.|El faltante es el costo que supera lo disponible.|A falta é o custo acima do disponível.','Compare need with available money.|Compara necesidad y dinero disponible.|Compare necessidade e dinheiro disponível.',[[85,60],sub(0,1)]),
 Q('practice-02','practice','Bills need 45 and 35; you have 55.|Cuentas pendientes: 45 y 35; tienes 55.|Contas pendentes: 45 e 35; você tem 55.','Combined shortfall?|¿Faltante conjunto?|Falta total?',['25|25|25','10|10|10','80|80|80'],'Total obligations exceed available money by twenty-five.|Las obligaciones superan lo disponible por veinticinco.|As obrigações superam o disponível em vinte e cinco.','Add both needs, then subtract available money.|Suma ambas necesidades y resta lo disponible.|Some as necessidades e subtraia o disponível.',[[45,35,55],op('subtract',add(0,1),I(2))]),
 Q('practice-03','practice','You have enough for a bill, with money left afterward.|Te alcanza para una cuenta y sobra dinero después.|Você tem o suficiente para a conta e sobra dinheiro.','Is there a shortfall for it?|¿Hay un faltante para esa cuenta?|Falta dinheiro para essa conta?',['No|No|Não','Yes, the bill amount|Sí, el monto de la cuenta|Sim, o valor da conta','Yes, the remaining money|Sí, lo que sobra|Sim, o que sobra'],'A covered bill has no shortfall.|Una cuenta cubierta no tiene faltante.|Uma conta coberta não tem falta.','A shortfall means need exceeds available money.|Un faltante implica necesidad mayor que lo disponible.|Falta significa necessidade maior que o disponível.'),
 Q('transfer-01','transfer','A deposit requires 120 today. You hold 80; tomorrow’s 50 has not arrived.|Un depósito requiere 120 hoy. Tienes 80; los 50 de mañana no llegan aún.|Um depósito exige 120 hoje. Você tem 80; os 50 de amanhã não chegaram.','Today’s shortfall?|¿Faltante de hoy?|Falta de hoje?',['40|40|40','0|0|0','70|70|70'],'A future receipt cannot cover today’s payment yet.|Una entrada futura aún no cubre el pago de hoy.|Uma entrada futura ainda não cobre o pagamento de hoje.','Use money available by the due date.|Usa dinero disponible antes del vencimiento.|Use dinheiro disponível até o vencimento.',[[120,80,50],sub(0,1)])]),
];
