import { lesson, E, Q, grid, I, op, C } from './factory.mjs';
const mul=(a,b)=>op('multiply',I(a),I(b)), div=(a,b)=>op('divide',I(a),I(b));
export const groups=[
lesson('financial-math',5,'Equal groups|Grupos iguales|Grupos iguais','Find a total when the same price repeats.|Encuentra un total cuando se repite el mismo precio.|Encontre o total quando o mesmo preço se repete.','Add the unit price to the quantity instead of multiplying.',[
 E('example-01','Count repeated prices|Cuenta precios repetidos|Conte preços repetidos','Three tickets at 8 each cost 8 + 8 + 8 = 24. Multiplication writes the same repeated addition as 3 × 8.|Tres boletos de 8 cuestan 8 + 8 + 8 = 24. Multiplicar expresa esa suma repetida como 3 × 8.|Três ingressos de 8 custam 8 + 8 + 8 = 24. Multiplicar expressa essa soma repetida como 3 × 8.'),
 Q('guided-01','guided','Buy 4 identical items at 6 each. Multiply quantity by unit price.|Compra 4 artículos iguales de 6 cada uno. Multiplica cantidad por precio unitario.|Compre 4 itens iguais de 6 cada. Multiplique quantidade pelo preço unitário.','Total cost?|¿Costo total?|Custo total?',['24|24|24','10|10|10','6|6|6'],'Each item contributes the same price.|Cada artículo aporta el mismo precio.|Cada item contribui com o mesmo preço.','Repeat the price for every item.|Repite el precio por cada artículo.|Repita o preço para cada item.',[[4,6],mul(0,1)]),
 Q('guided-02','guided','Two fares cost 9 each.|Dos pasajes cuestan 9 cada uno.|Duas passagens custam 9 cada.','Which calculation fits?|¿Qué cálculo corresponde?|Qual cálculo corresponde?',['Add nine twice|Suma nueve dos veces|Some nove duas vezes','Add two to nine|Suma dos a nueve|Some dois a nove','Divide nine by two|Divide nueve entre dos|Divida nove por dois'],'Two groups require two copies of the price.|Dos grupos requieren dos copias del precio.|Dois grupos exigem duas cópias do preço.','Quantity tells you how often the price repeats.|La cantidad indica cuántas veces se repite el precio.|A quantidade indica quantas vezes o preço se repete.'),
 Q('practice-01','practice','A refill costs 7; you buy 5.|Una recarga cuesta 7; compras 5.|Uma recarga custa 7; compra 5.','Total cost?|¿Costo total?|Custo total?',['35|35|35','12|12|12','7|7|7'],'Five equal prices form the total.|Cinco precios iguales forman el total.|Cinco preços iguais formam o total.','Multiply price by quantity.|Multiplica precio por cantidad.|Multiplique preço por quantidade.',[[7,5],mul(0,1)]),
 Q('practice-02','practice','A box contains 6 items. Its stated price is 30 per box.|Una caja contiene 6 artículos. Su precio es 30 por caja.|Uma caixa contém 6 itens. Seu preço é 30 por caixa.','What does one box cost?|¿Cuánto cuesta una caja?|Quanto custa uma caixa?',['30|30|30','180|180|180','36|36|36'],'The quoted price already covers the whole box.|El precio indicado ya cubre la caja completa.|O preço informado já cobre a caixa inteira.','Check what unit the price describes.|Revisa qué unidad describe el precio.|Confira qual unidade o preço descreve.',[[6,30],I(1)]),
 Q('practice-03','practice','One item costs 5; another different item costs 8.|Un artículo cuesta 5; otro diferente cuesta 8.|Um item custa 5; outro diferente custa 8.','Which method fits?|¿Qué método corresponde?|Qual método corresponde?',['Add the different prices|Suma los precios distintos|Some os preços diferentes','Multiply five by eight|Multiplica cinco por ocho|Multiplique cinco por oito','Use either price twice|Repite cualquier precio dos veces|Repita qualquer preço duas vezes'],'Different prices must be added individually.|Los precios distintos se suman individualmente.|Os preços diferentes são somados individualmente.','Equal-price multiplication needs equal prices.|Multiplicar precios iguales exige precios iguales.|Multiplicar preços iguais exige preços iguais.'),
 Q('transfer-01','transfer','A shared event needs 8 chairs rented at 12 each. Delivery is free.|Un evento necesita 8 sillas rentadas a 12 cada una. La entrega es gratis.|Um evento precisa de 8 cadeiras alugadas a 12 cada. A entrega é grátis.','Rental total?|¿Total de renta?|Total do aluguel?',['96|96|96','20|20|20','12|12|12'],'Only the repeated chair price contributes here.|Aquí solo contribuye el precio repetido de las sillas.|Aqui só contribui o preço repetido das cadeiras.','Count every chair at the stated price.|Cuenta cada silla al precio indicado.|Conte cada cadeira pelo preço informado.',[[8,12],mul(0,1)])]),
lesson('financial-math',6,'Equal contributions|Aportaciones iguales|Contribuições iguais','Split a stated shared cost without charging anyone twice.|Divide un costo compartido sin cobrar dos veces a nadie.|Divida um custo compartilhado sem cobrar alguém duas vezes.','Confuse total cost with the contribution required from each person.',[
 E('example-01','Share the whole|Reparte el total|Divida o total','A cost of 60 shared equally by 3 people means 60 ÷ 3 = 20 each. Three contributions restore the total.|Un costo de 60 entre 3 personas por igual significa 60 ÷ 3 = 20 cada una. Tres aportaciones recuperan el total.|Um custo de 60 entre 3 pessoas igualmente significa 60 ÷ 3 = 20 cada. Três contribuições recuperam o total.'),
 Q('guided-01','guided','Share 80 equally among 4 people. Divide total by people.|Reparte 80 entre 4 personas por igual. Divide total entre personas.|Divida 80 entre 4 pessoas igualmente. Divida total por pessoas.','Each contribution?|¿Aportación individual?|Contribuição individual?',['20|20|20','84|84|84','320|320|320'],'Equal contributions together cover the stated total.|Las aportaciones iguales cubren juntas el total indicado.|As contribuições iguais cobrem juntas o total informado.','Divide rather than multiply the total.|Divide el total en lugar de multiplicarlo.|Divida o total em vez de multiplicá-lo.',[[80,4],div(0,1)]),
 Q('guided-02','guided','Each of 5 people contributes 12 toward a cost of 60.|Cada una de 5 personas aporta 12 para un costo de 60.|Cada uma de 5 pessoas contribui com 12 para um custo de 60.','How do you check the split?|¿Cómo revisas el reparto?|Como conferir a divisão?',['Multiply contribution by people|Multiplica aportación por personas|Multiplique contribuição por pessoas','Add people to contribution|Suma personas y aportación|Some pessoas e contribuição','Divide contribution again|Divide otra vez la aportación|Divida novamente a contribuição'],'Recombining equal shares should restore the total.|Reunir partes iguales debe recuperar el total.|Reunir partes iguais deve recuperar o total.','Reverse the division with multiplication.|Invierte la división con multiplicación.|Inverta a divisão com multiplicação.'),
 Q('practice-01','practice','A shared ride costs 72 for 6 equal contributors.|Un viaje compartido cuesta 72 para 6 aportantes iguales.|Uma viagem compartilhada custa 72 para 6 contribuintes iguais.','Each contribution?|¿Aportación individual?|Contribuição individual?',['12|12|12','66|66|66','432|432|432'],'Six equal contributions of twelve cover the ride.|Seis aportaciones iguales de doce cubren el viaje.|Seis contribuições iguais de doze cobrem a viagem.','Split the complete cost across all contributors.|Reparte el costo completo entre todos los aportantes.|Divida o custo completo entre todos os contribuintes.',[[72,6],div(0,1)]),
 Q('practice-02','practice','A group agrees equal shares, but one person already paid their share.|Un grupo acuerda partes iguales, pero alguien ya pagó su parte.|Um grupo combina partes iguais, mas alguém já pagou sua parte.','What should records show?|¿Qué debe mostrar el registro?|O que o registro deve mostrar?',['Their share is already paid|Su parte ya está pagada|Sua parte já está paga','They owe the same share again|Debe pagar su parte otra vez|Deve pagar sua parte novamente','Nobody else owes money|Nadie más debe dinero|Ninguém mais deve dinheiro'],'A completed contribution must not be collected twice.|Una aportación realizada no debe cobrarse dos veces.|Uma contribuição concluída não deve ser cobrada duas vezes.','Separate the agreed share from its payment status.|Separa la parte acordada de su estado de pago.|Separe a parte combinada de seu estado de pagamento.'),
 Q('practice-03','practice','Two people agree to share only a 40 delivery fee equally; items stay separate.|Dos personas comparten solo una entrega de 40 por igual; artículos aparte.|Duas pessoas dividem só uma entrega de 40 igualmente; itens separados.','Each delivery share?|¿Parte de entrega individual?|Parte individual da entrega?',['20|20|20','40|40|40','80|80|80'],'Divide only the cost covered by the agreement.|Divide solo el costo incluido en el acuerdo.|Divida só o custo incluído no acordo.','Do not add unrelated purchases.|No sumes compras ajenas al reparto.|Não some compras fora da divisão.',[[40],op('divide',I(0),op('add',C(1),C(1)))]),
 Q('transfer-01','transfer','Equipment rental is 150. A sponsor covers 30; 4 participants split the rest equally.|Rentar equipo cuesta 150. Un patrocinador cubre 30; 4 participantes reparten el resto por igual.|Alugar equipamento custa 150. Um patrocinador cobre 30; 4 participantes dividem o resto igualmente.','Each participant pays?|¿Cuánto paga cada participante?|Quanto paga cada participante?',['30|30|30','45|45|45','120|120|120'],'Remove the covered portion before dividing the remainder.|Retira la parte cubierta antes de dividir el resto.|Retire a parte coberta antes de dividir o resto.','Only the uncovered cost remains to share.|Solo queda por repartir el costo no cubierto.|Só resta dividir o custo não coberto.',[[150,30,4],op('divide',op('subtract',I(0),I(1)),I(2))])]),
lesson('financial-math',7,'Parts of a hundred|Partes de cien|Partes de cem','Compare shares of dollars even when totals differ.|Compara partes de pesos aunque cambien los totales.|Compare partes de reais mesmo quando os totais mudam.','Treat a fraction as a fixed money amount rather than a share of a whole.',[
 E('example-01','One whole grid|Una cuadrícula completa|Uma grade inteira','Percent means out of a hundred. Half a whole is fifty hundredths; a quarter is twenty-five hundredths.|Porcentaje significa de cada cien. La mitad son cincuenta centésimos; un cuarto son veinticinco centésimos.|Porcentagem significa de cada cem. Metade são cinquenta centésimos; um quarto são vinte e cinco centésimos.'),
 grid('guided-01','guided',50,'Show half the grid: fifty of one hundred equal parts.|Muestra la mitad: cincuenta de cien partes iguales.|Mostre metade: cinquenta de cem partes iguais.'),
 grid('guided-02','guided',25,'Show one quarter: divide the whole into four equal shares.|Muestra un cuarto: divide el total en cuatro partes iguales.|Mostre um quarto: divida o total em quatro partes iguais.'),
 grid('practice-01','practice',75,'Select three quarters of the whole grid.|Selecciona tres cuartos de la cuadrícula completa.|Selecione três quartos da grade inteira.'),
 grid('practice-02','practice',20,'Select one fifth of the whole grid.|Selecciona un quinto de la cuadrícula completa.|Selecione um quinto da grade inteira.'),
 Q('practice-03','practice','Half of a small total and half of a large total are compared.|Se compara la mitad de un total pequeño con la de uno grande.|Comparam-se a metade de um total pequeno e a de um grande.','What is equal?|¿Qué es igual?|O que é igual?',['The percentage share|La proporción porcentual|A proporção percentual','The money amount always|Siempre el monto de dinero|Sempre o valor em dinheiro','Both whole totals|Ambos totales completos|Os dois totais completos'],'The share can match while the amounts differ.|La proporción puede coincidir aunque cambien los montos.|A proporção pode coincidir mesmo com valores diferentes.','Percentage describes a relation to the whole.|El porcentaje describe una relación con el total.|Porcentagem descreve uma relação com o total.'),
 grid('transfer-01','transfer',40,'A community fund uses two fifths of its money. Show that share.|Un fondo comunitario usa dos quintos de su dinero. Representa esa parte.|Um fundo comunitário usa dois quintos do dinheiro. Represente essa parte.')]),
];
