import { review,Q,grid,I,op,C } from './factory.mjs';
const m=n=>`fe-production-financial-math-${String(n).padStart(2,'0')}`, balance='fe-production-usable-money-02';
export const mathReviews=[review('financial-math',1,'Prepare the shared trip|Prepara el viaje compartido|Prepare a viagem compartilhada','Check a trip’s records, shared costs and available money.|Revisa registros, costos compartidos y dinero disponible para un viaje.|Confira registros, custos compartilhados e dinheiro disponível para uma viagem.',[
 Q('practice-01','practice','A baggage fee reads 2.09 dollars.|Un cargo por equipaje dice 2.09 pesos.|Uma tarifa de bagagem diz 2,09 reais.','Read the fee.|Lee el cargo.|Leia a tarifa.',['Two units, nine cents|Dos unidades, nueve centavos|Duas unidades, nove centavos','Two units, ninety cents|Dos unidades, noventa centavos|Duas unidades, noventa centavos','Twenty-nine units|Veintinueve unidades|Vinte e nove unidades'],'The zero fixes nine in the cents position.|El cero coloca el nueve en los centavos.|O zero coloca o nove nos centavos.','Read the whole and fractional parts separately.|Lee por separado partes entera y fraccionaria.|Leia separadamente partes inteira e fracionária.'),
 Q('practice-02','practice','Pay 50 for a fare of 37.|Pagas con 50 un pasaje de 37.|Paga com 50 uma passagem de 37.','Change due?|¿Cambio debido?|Troco devido?',['13|13|13','87|87|87','37|37|37'],'Only the unused payment returns.|Solo vuelve la parte del pago no usada.|Só retorna a parte do pagamento não usada.','Subtract the fare from the payment.|Resta el pasaje del pago.|Subtraia a passagem do pagamento.',[[50,37],op('subtract',I(0),I(1))]),
 Q('practice-03','practice','A trip refund appears in both your email and bank record with the same reference.|Una devolución del viaje aparece en correo y banco con la misma referencia.|Um reembolso da viagem aparece no e-mail e banco com a mesma referência.','How many receipts occurred?|¿Cuántas entradas ocurrieron?|Quantas entradas ocorreram?',['One receipt|Una entrada|Uma entrada','Two receipts|Dos entradas|Duas entradas','No receipt|Ninguna entrada|Nenhuma entrada'],'Matching references identify the same payment event.|Las referencias iguales identifican el mismo pago.|Referências iguais identificam o mesmo pagamento.','Count events, not copies of evidence.|Cuenta eventos, no copias de comprobantes.|Conte eventos, não cópias de comprovantes.'),
 Q('practice-04','practice','A required trip payment is 95; only 68 is available.|Un pago necesario del viaje es 95; solo hay 68 disponibles.|Um pagamento necessário da viagem é 95; só há 68 disponíveis.','Shortfall?|¿Faltante?|Falta?',['27|27|27','163|163|163','68|68|68'],'The uncovered portion is the shortfall.|La parte no cubierta es el faltante.|A parte não coberta é a falta.','Subtract available money from the obligation.|Resta lo disponible de la obligación.|Subtraia o disponível da obrigação.',[[95,68],op('subtract',I(0),I(1))]),
 Q('practice-05','practice','A group buys 7 identical tickets at 11 each.|Un grupo compra 7 boletos iguales de 11 cada uno.|Um grupo compra 7 ingressos iguais de 11 cada.','Ticket total?|¿Total de boletos?|Total dos ingressos?',['77|77|77','18|18|18','11|11|11'],'Every ticket contributes the same unit price.|Cada boleto aporta el mismo precio unitario.|Cada ingresso contribui com o mesmo preço unitário.','Multiply the repeated price by quantity.|Multiplica el precio repetido por la cantidad.|Multiplique o preço repetido pela quantidade.',[[7,11],op('multiply',I(0),I(1))]),
 Q('practice-06','practice','A shared booking costs 96 for 4 equal contributors.|Una reserva compartida cuesta 96 para 4 aportantes iguales.|Uma reserva compartilhada custa 96 para 4 contribuintes iguais.','Each contribution?|¿Aportación individual?|Contribuição individual?',['24|24|24','100|100|100','92|92|92'],'Equal shares must recombine to the booking total.|Las partes iguales deben reunir el total de la reserva.|As partes iguais devem reunir o total da reserva.','Divide the total across all contributors.|Divide el total entre todos los aportantes.|Divida o total entre todos os contribuintes.',[[96,4],op('divide',I(0),I(1))]),
 grid('practice-07','practice',60,'The trip fund uses three fifths of its money. Show that share.|El fondo del viaje usa tres quintos de su dinero. Representa esa parte.|O fundo da viagem usa três quintos do dinheiro. Represente essa parte.'),
 Q('practice-08','practice','Travel cash starts at 80; a completed fare payment is 17.|El efectivo del viaje inicia en 80; un pago de pasaje realizado es 17.|O dinheiro da viagem começa em 80; um pagamento de passagem concluído é 17.','Cash remaining?|¿Efectivo restante?|Dinheiro restante?',['63|63|63','97|97|97','17|17|17'],'A completed payment reduces the starting cash.|Un pago realizado reduce el efectivo inicial.|Um pagamento concluído reduz o dinheiro inicial.','Subtract the completed outgoing payment.|Resta el pago de salida realizado.|Subtraia o pagamento de saída concluído.',[[80,17],op('subtract',I(0),I(1))]),
 Q('transfer-01','transfer','The trip wallet starts at 70, receives 25, then pays 40.|La cartera del viaje inicia con 70, recibe 25 y paga 40.|A carteira da viagem começa com 70, recebe 25 e paga 40.','Final balance?|¿Saldo final?|Saldo final?',['55|55|55','95|95|95','135|135|135'],'Include the receipt and completed payment once each.|Incluye la entrada y el pago realizado una vez cada uno.|Inclua a entrada e o pagamento concluído uma vez cada.','Add incoming money and subtract outgoing money.|Suma lo que entra y resta lo que sale.|Some o que entra e subtraia o que sai.',[[70,25,40],op('subtract',op('add',I(0),I(1)),I(2))]),
],[1,2,3,4,5,6,7].map(m).concat(balance,balance)),
review('financial-math',2,'Check a project estimate|Revisa un presupuesto de proyecto|Confira uma estimativa de projeto','Combine shares, time periods and arithmetic checks in a new project.|Combina proporciones, periodos y comprobaciones en un proyecto nuevo.|Combine proporções, períodos e conferências num projeto novo.',[
 Q('practice-01','practice','A project reserves 15% of its 200 budget for delivery.|Un proyecto reserva 15% de su presupuesto de 200 para entrega.|Um projeto reserva 15% do orçamento de 200 para entrega.','Delivery reserve?|¿Reserva de entrega?|Reserva da entrega?',['30|30|30','15|15|15','185|185|185'],'The reserved amount is a share of the whole budget.|La reserva es una parte del presupuesto completo.|A reserva é uma parte do orçamento inteiro.','Use the stated budget as the base.|Usa el presupuesto indicado como base.|Use o orçamento informado como base.',[[15,200],op('divide',op('multiply',I(0),I(1)),C(100))]),
 Q('practice-02','practice','A deposit of 24 covers 40% of a rental.|Un depósito de 24 cubre 40% de una renta.|Um sinal de 24 cobre 40% de um aluguel.','Full rental price?|¿Precio completo de renta?|Preço completo do aluguel?',['60|60|60','64|64|64','9.6|9.6|9,6'],'Recover the whole from the deposit’s stated share.|Recupera el total a partir de la parte del depósito.|Recupere o total a partir da parte do sinal.','The deposit is not the whole rental cost.|El depósito no es el costo completo de renta.|O sinal não é o custo inteiro do aluguel.',[[24,40],op('divide',op('multiply',I(0),C(100)),I(1))]),
 Q('practice-03','practice','A project’s delivery share rises from 10% to 12%.|La proporción de entrega de un proyecto sube de 10% a 12%.|A proporção de entrega de um projeto sobe de 10% para 12%.','Direct difference in percentage points?|¿Diferencia directa en puntos porcentuales?|Diferença direta em pontos percentuais?',['2|2|2','20|20|20','12|12|12'],'Subtracting rates gives a percentage-point difference.|Restar tasas da una diferencia en puntos porcentuales.|Subtrair taxas dá uma diferença em pontos percentuais.','Use the requested comparison unit.|Usa la unidad de comparación pedida.|Use a unidade de comparação pedida.',[[10,12],op('subtract',I(1),I(0))]),
 Q('practice-04','practice','Storage costs 18 monthly; the project lasts 5 months.|Almacenar cuesta 18 mensuales; el proyecto dura 5 meses.|Armazenar custa 18 mensais; o projeto dura 5 meses.','Storage total?|¿Total de almacenamiento?|Total de armazenamento?',['90|90|90','23|23|23','18|18|18'],'Every covered month contributes one monthly charge.|Cada mes cubierto aporta un cargo mensual.|Cada mês coberto contribui com uma cobrança mensal.','Match the cost to the full project period.|Iguala el costo al periodo completo del proyecto.|Iguale o custo ao período inteiro do projeto.',[[18,5],op('multiply',I(0),I(1))]),
 Q('practice-05','practice','A project splits 20 equally three ways. Each rounded share is 6.67.|Un proyecto reparte 20 entre tres por igual. Cada parte redondeada es 6.67.|Um projeto divide 20 entre três igualmente. Cada parte arredondada é 6,67.','What must be resolved?|¿Qué debes resolver?|O que precisa resolver?',['The extra collected cent|El centavo cobrado de más|O centavo cobrado a mais','A missing whole payment|Un pago completo faltante|Um pagamento inteiro faltante','Nothing, rounding is exact|Nada, el redondeo es exacto|Nada, arredondar é exato'],'The rounded shares sum to one cent above the total.|Las partes redondeadas suman un centavo sobre el total.|As partes arredondadas somam um centavo acima do total.','Recombine rounded shares and compare with the bill.|Reúne partes redondeadas y compara con la cuenta.|Reúna partes arredondadas e compare com a conta.'),
 Q('practice-06','practice','Five supplies cost just over 20 each. A calculator gives 1,020.|Cinco insumos cuestan poco más de 20 cada uno. Una calculadora da 1,020.|Cinco materiais custam pouco mais de 20 cada. Uma calculadora dá 1.020.','Best next step?|¿Mejor paso siguiente?|Melhor próximo passo?',['Check input against a rough hundred|Revisa datos contra una estimación de cien|Confira dados com uma estimativa de cem','Trust the displayed total|Confía en el total mostrado|Confie no total mostrado','Assume all prices multiplied by ten|Supón que todos los precios subieron diez veces|Suponha que os preços aumentaram dez vezes'],'The displayed result has the wrong approximate scale.|El resultado mostrado tiene una magnitud aproximada incorrecta.|O resultado mostrado tem uma ordem aproximada incorreta.','Estimate from the item count and approximate unit price.|Estima con cantidad y precio unitario aproximado.|Estime com quantidade e preço unitário aproximado.'),
 Q('practice-07','practice','A project has 55 and receives a completed contribution of 35.|Un proyecto tiene 55 y recibe una aportación realizada de 35.|Um projeto tem 55 e recebe uma contribuição concluída de 35.','Updated balance?|¿Saldo actualizado?|Saldo atualizado?',['90|90|90','20|20|20','55|55|55'],'The completed receipt increases the balance.|La entrada realizada aumenta el saldo.|A entrada concluída aumenta o saldo.','Add the received contribution once.|Suma la aportación recibida una vez.|Some a contribuição recebida uma vez.',[[55,35],op('add',I(0),I(1))]),
 Q('transfer-01','transfer','The project holds 110, receives a 30 refund, and pays a 45 fee.|El proyecto tiene 110, recibe una devolución de 30 y paga un cargo de 45.|O projeto tem 110, recebe um reembolso de 30 e paga uma tarifa de 45.','Final balance?|¿Saldo final?|Saldo final?',['95|95|95','185|185|185','65|65|65'],'A refund enters; the fee leaves the project’s money.|La devolución entra; el cargo sale del dinero del proyecto.|O reembolso entra; a tarifa sai do dinheiro do projeto.','Track the direction of each completed movement.|Sigue la dirección de cada movimiento realizado.|Acompanhe a direção de cada movimento concluído.',[[110,30,45],op('subtract',op('add',I(0),I(1)),I(2))]),
],[8,9,10,11,12,13].map(m).concat(balance,balance))];
