import { lesson, E, Q, I, op, C } from './factory.mjs';
const pct=(a,b)=>op('divide',op('multiply',I(a),I(b)),C(100));
export const percentages=[
lesson('financial-math',8,'A share of an amount|Una parte de un monto|Uma parte de um valor','Use the stated base to find a percentage amount.|Usa la base indicada para encontrar un monto porcentual.|Use a base informada para encontrar um valor percentual.','Apply the percentage to the wrong base or confuse the rate with the amount.',[
 E('example-01','Find one percent first|Primero encuentra uno por ciento|Primeiro encontre um por cento','For 20% of 80, divide 80 by 100, then multiply by 20. The share is 16, not 20 money units.|Para 20% de 80, divide 80 entre 100 y multiplica por 20. La parte es 16, no 20 unidades monetarias.|Para 20% de 80, divida 80 por 100 e multiplique por 20. A parte é 16, não 20 unidades monetárias.'),
 Q('guided-01','guided','Find 10% of 60. Divide the whole into ten equal shares.|Encuentra 10% de 60. Divide el total en diez partes iguales.|Encontre 10% de 60. Divida o total em dez partes iguais.','Share amount?|¿Monto de la parte?|Valor da parte?',['6|6|6','10|10|10','50|50|50'],'The percentage applies to the stated whole.|El porcentaje se aplica al total indicado.|A porcentagem se aplica ao total informado.','The rate is not itself the money amount.|La tasa no es por sí misma el monto.|A taxa não é por si o valor.',[[10,60],pct(0,1)]),
 Q('guided-02','guided','A 25% share is taken from 40, not from a separate balance.|Se toma 25% de 40, no de otro saldo.|Retiram-se 25% de 40, não de outro saldo.','Which is the base?|¿Cuál es la base?|Qual é a base?',['The forty-unit whole|El total de cuarenta|O total de quarenta','The percentage number|El número porcentual|O número percentual','Any available balance|Cualquier saldo disponible|Qualquer saldo disponível'],'The base is the whole named in the calculation.|La base es el total nombrado en el cálculo.|A base é o total indicado no cálculo.','Ask: a percentage of what?|Pregunta: ¿porcentaje de qué?|Pergunte: porcentagem de quê?'),
 Q('practice-01','practice','A fee is 5% of a payment of 200.|Un cargo es 5% de un pago de 200.|Uma tarifa é 5% de um pagamento de 200.','Fee amount?|¿Monto del cargo?|Valor da tarifa?',['10|10|10','5|5|5','195|195|195'],'The fee is the stated fraction of the payment.|El cargo es la fracción indicada del pago.|A tarifa é a fração informada do pagamento.','Multiply the base by the rate divided by one hundred.|Multiplica la base por la tasa dividida entre cien.|Multiplique a base pela taxa dividida por cem.',[[5,200],pct(0,1)]),
 Q('practice-02','practice','A plan assigns 30% of 90 to one category.|Un plan asigna 30% de 90 a una categoría.|Um plano destina 30% de 90 a uma categoria.','Category amount?|¿Monto de la categoría?|Valor da categoria?',['27|27|27','30|30|30','60|60|60'],'The share changes with its base.|La parte cambia con su base.|A parte muda com sua base.','Use the stated base, not a different total.|Usa la base indicada, no otro total.|Use a base informada, não outro total.',[[30,90],pct(0,1)]),
 Q('practice-03','practice','The same positive percentage is applied to a larger base.|Se aplica el mismo porcentaje positivo a una base mayor.|Aplica-se a mesma porcentagem positiva a uma base maior.','What happens to its amount?|¿Qué pasa con su monto?|O que acontece com o valor?',['It increases|Aumenta|Aumenta','It stays fixed|Permanece fijo|Permanece fixo','It disappears|Desaparece|Desaparece'],'A fixed share of a larger whole is larger.|Una parte fija de un total mayor es mayor.|Uma parte fixa de um total maior é maior.','Separate the rate from the money amount.|Separa la tasa del monto de dinero.|Separe a taxa do valor em dinheiro.'),
 Q('transfer-01','transfer','A reimbursement covers 75% of an eligible cost of 80; other costs are excluded.|Un reembolso cubre 75% de un costo elegible de 80; otros costos quedan fuera.|Um reembolso cobre 75% de um custo elegível de 80; outros custos ficam fora.','Reimbursement amount?|¿Monto del reembolso?|Valor do reembolso?',['60|60|60','75|75|75','20|20|20'],'Only the eligible base enters this calculation.|Solo la base elegible entra en este cálculo.|Só a base elegível entra neste cálculo.','Apply the fraction to the covered cost.|Aplica la fracción al costo cubierto.|Aplique a fração ao custo coberto.',[[75,80],pct(0,1)])]),
lesson('financial-math',9,'Recover the whole|Recupera el total|Recupere o total','Work backward when you know a share and its amount.|Trabaja hacia atrás si conoces una parte y su monto.|Trabalhe de trás para frente quando conhece uma parte e seu valor.','Subtract the rate from the share or mistake the share for the original whole.',[
 E('example-01','Reverse the share|Invierte la proporción|Inverta a proporção','If 25% equals 20, the whole contains four such shares: 20 × 4 = 80. The given amount is only a quarter.|Si 25% equivale a 20, el total contiene cuatro partes así: 20 × 4 = 80. El monto dado es un cuarto.|Se 25% equivale a 20, o total contém quatro partes assim: 20 × 4 = 80. O valor dado é um quarto.'),
 Q('guided-01','guided','50% of a total is 30. Half must be doubled.|El 50% de un total es 30. La mitad debe duplicarse.|50% de um total é 30. A metade deve ser duplicada.','Whole amount?|¿Monto total?|Valor total?',['60|60|60','15|15|15','80|80|80'],'Two equal halves reconstruct the whole.|Dos mitades iguales reconstruyen el total.|Duas metades iguais reconstroem o total.','The given amount is half, not the whole.|El monto dado es la mitad, no el total.|O valor dado é metade, não o total.',[[50,30],op('divide',op('multiply',I(1),C(100)),I(0))]),
 Q('guided-02','guided','10% equals 7.|El 10% equivale a 7.|10% equivale a 7.','Which method finds the whole?|¿Qué método encuentra el total?|Qual método encontra o total?',['Use ten equal shares|Usa diez partes iguales|Use dez partes iguais','Subtract ten from seven|Resta diez a siete|Subtraia dez de sete','Keep only one share|Conserva solo una parte|Mantenha só uma parte'],'Ten tenths make one whole.|Diez décimos forman un total.|Dez décimos formam um inteiro.','Ask how many shares fill the whole.|Pregunta cuántas partes completan el total.|Pergunte quantas partes completam o total.'),
 Q('practice-01','practice','A 20% deposit is 18.|Un depósito de 20% es 18.|Um sinal de 20% é 18.','Full price?|¿Precio completo?|Preço completo?',['90|90|90','38|38|38','3.6|3.6|3,6'],'Five equal deposits would cover the full price.|Cinco depósitos iguales cubrirían el precio completo.|Cinco sinais iguais cobririam o preço completo.','Recover the base from the given share.|Recupera la base a partir de la parte.|Recupere a base a partir da parte.',[[20,18],op('divide',op('multiply',I(1),C(100)),I(0))]),
 Q('practice-02','practice','25% of a shared bill is 15.|El 25% de una cuenta compartida es 15.|25% de uma conta compartilhada é 15.','Whole bill?|¿Cuenta completa?|Conta inteira?',['60|60|60','40|40|40','15|15|15'],'Four quarters make the whole bill.|Cuatro cuartos forman la cuenta completa.|Quatro quartos formam a conta inteira.','The amount is a quarter of the bill.|El monto es un cuarto de la cuenta.|O valor é um quarto da conta.',[[25,15],op('divide',op('multiply',I(1),C(100)),I(0))]),
 Q('practice-03','practice','A positive amount represents less than the whole.|Un monto positivo representa menos del total.|Um valor positivo representa menos do total.','How must the whole compare?|¿Cómo debe ser el total?|Como deve ser o total?',['Larger than that amount|Mayor que ese monto|Maior que esse valor','Smaller than that amount|Menor que ese monto|Menor que esse valor','Always equal to it|Siempre igual a ese monto|Sempre igual a esse valor'],'A proper part is smaller than its whole.|Una parte propia es menor que su total.|Uma parte própria é menor que seu total.','Check whether your result could contain the given part.|Revisa si tu resultado puede contener la parte dada.|Confira se seu resultado pode conter a parte dada.'),
 Q('transfer-01','transfer','A grant of 45 covers 75% of an eligible project cost.|Un apoyo de 45 cubre 75% del costo elegible de un proyecto.|Um auxílio de 45 cobre 75% do custo elegível de um projeto.','Eligible whole cost?|¿Costo elegible completo?|Custo elegível completo?',['60|60|60','120|120|120','33.75|33.75|33,75'],'Divide the known share by its fraction of the whole.|Divide la parte conocida entre su fracción del total.|Divida a parte conhecida pela fração do total.','The grant is only three quarters of the cost.|El apoyo es solo tres cuartos del costo.|O auxílio é só três quartos do custo.',[[45,75],op('divide',op('multiply',I(0),C(100)),I(1))])]),
lesson('financial-math',10,'Two kinds of change|Dos tipos de cambio|Dois tipos de mudança','Read claims about changing percentages without mixing their units.|Lee cambios porcentuales sin mezclar sus unidades.|Leia mudanças percentuais sem misturar suas unidades.','Call a difference in rates a relative percentage change without dividing by the original rate.',[
 E('example-01','Name the comparison|Nombra la comparación|Nomeie a comparação','From 10% to 15% is five percentage points. Relative to the original ten, the increase is one half: fifty percent.|De 10% a 15% son cinco puntos porcentuales. Respecto al diez original, el aumento es la mitad: cincuenta por ciento.|De 10% a 15% são cinco pontos percentuais. Em relação aos dez originais, o aumento é metade: cinquenta por cento.'),
 Q('guided-01','guided','A share rises from 20% to 30%. Subtract the two rates.|Una proporción sube de 20% a 30%. Resta ambas tasas.|Uma proporção sobe de 20% para 30%. Subtraia as duas taxas.','Difference in percentage points?|¿Diferencia en puntos porcentuales?|Diferença em pontos percentuais?',['10|10|10','50|50|50','30|30|30'],'Percentage points measure direct subtraction of rates.|Los puntos porcentuales miden la resta directa de tasas.|Pontos percentuais medem a subtração direta de taxas.','The requested unit is percentage points.|La unidad pedida es puntos porcentuales.|A unidade pedida é pontos percentuais.',[[20,30],op('subtract',I(1),I(0))]),
 Q('guided-02','guided','A rate rises from 4% to 8%. It doubles.|Una tasa sube de 4% a 8%. Se duplica.|Uma taxa sobe de 4% para 8%. Ela dobra.','Relative increase?|¿Aumento relativo?|Aumento relativo?',['One hundred percent|Cien por ciento|Cem por cento','Four percent|Cuatro por ciento|Quatro por cento','Eight percentage points|Ocho puntos porcentuales|Oito pontos percentuais'],'Doubling adds the entire original amount.|Duplicar añade el monto original completo.|Dobrar acrescenta o valor original inteiro.','Compare the increase with the starting rate.|Compara el aumento con la tasa inicial.|Compare o aumento com a taxa inicial.'),
 Q('practice-01','practice','A rate falls from 12% to 9%.|Una tasa baja de 12% a 9%.|Uma taxa cai de 12% para 9%.','Fall in percentage points?|¿Baja en puntos porcentuales?|Queda em pontos percentuais?',['3|3|3','25|25|25','9|9|9'],'Direct subtraction gives the point difference.|La resta directa da la diferencia en puntos.|A subtração direta dá a diferença em pontos.','Keep the requested comparison unit.|Conserva la unidad de comparación pedida.|Mantenha a unidade de comparação pedida.',[[12,9],op('subtract',I(0),I(1))]),
 Q('practice-02','practice','A share goes from 40% to 50%.|Una proporción pasa de 40% a 50%.|Uma proporção passa de 40% para 50%.','Relative increase, as a percent?|¿Aumento relativo, en porcentaje?|Aumento relativo, em porcentagem?',['25|25|25','10|10|10','50|50|50'],'The ten-point increase is one quarter of the starting rate.|El aumento de diez puntos es un cuarto de la tasa inicial.|O aumento de dez pontos é um quarto da taxa inicial.','Divide the increase by the original rate, then multiply by one hundred.|Divide el aumento entre la tasa original y multiplica por cien.|Divida o aumento pela taxa original e multiplique por cem.',[[40,50],op('multiply',op('divide',op('subtract',I(1),I(0)),I(0)),C(100))]),
 Q('practice-03','practice','An advertisement says a rate improved by five, without a unit.|Un anuncio dice que una tasa mejoró cinco, sin unidad.|Um anúncio diz que uma taxa melhorou cinco, sem unidade.','What needs clarification?|¿Qué necesitas aclarar?|O que precisa esclarecer?',['Points or relative percent|Puntos o porcentaje relativo|Pontos ou porcentagem relativa','Only the final rate|Solo la tasa final|Só a taxa final','Nothing, they are identical|Nada, son idénticos|Nada, são idênticos'],'The two units describe different comparisons.|Las dos unidades describen comparaciones distintas.|As duas unidades descrevem comparações diferentes.','Ask for the starting rate and the stated unit.|Pide la tasa inicial y la unidad indicada.|Peça a taxa inicial e a unidade informada.'),
 Q('transfer-01','transfer','Budget share: 30% to 20%. Report: ten percentage points.|Una parte del presupuesto baja de 30% a 20%. Un informe dice diez puntos porcentuales.|Uma parte do orçamento cai de 30% para 20%. Um relatório diz dez pontos percentuais.','Is that unit correct?|¿Es correcta esa unidad?|Essa unidade está correta?',['Yes, it subtracts the rates|Sí, resta las tasas|Sim, subtrai as taxas','No, it means ten percent relative|No, significa diez por ciento relativo|Não, significa dez por cento relativo','No, both shares are equal|No, ambas partes son iguales|Não, as partes são iguais'],'A point difference does not require the original-rate division.|Una diferencia en puntos no requiere dividir entre la tasa original.|Uma diferença em pontos não exige dividir pela taxa original.','Distinguish rate subtraction from proportional change.|Distingue resta de tasas y cambio proporcional.|Distinga subtração de taxas e mudança proporcional.')]),
];
