import {lesson,E,Q,I,op,T} from './factory.mjs';
const feeChart={id:'guided-chart',type:'visual.chart.v2',grading:'server',teaching_role:'guided',item_role:'practice',knowledge_component_id:'pending',visual:{type:'bar'},
 payload:{data:{unit:'local',categories:[{id:'route-a'},{id:'route-b'},{id:'route-c'}],series:[{id:'fee',values:[1,4,2]}]},question:{options:[{id:'route-b'},{id:'route-a'},{id:'route-c'}]}},rubric:{acceptable_choice_ids:['route-a']},
 copy:Object.fromEntries(['en-US','es-MX','pt-BR'].map((locale,i)=>[locale,{prompt:T('Compare fictional transfer fees only.|Compara solo comisiones ficticias de transferencia.|Compare só tarifas fictícias de transferência.')[i],title:T('Transfer fees|Comisiones de transferencia|Tarifas de transferência')[i],
 data:{categories:[{label:'A'},{label:'B'},{label:'C'}],series:[{label:T('Fee|Comisión|Tarifa')[i]}]},question:{prompt:T('Which fee is lower?|¿Qué comisión es menor?|Qual tarifa é menor?')[i],options:[{label:'B'},{label:'A'},{label:'C'}]},
 feedback:{met:T('A has the lower fee; timing still needs checking.|A tiene menor comisión; aún debes revisar fechas.|A tem menor tarifa; ainda precisa conferir datas.')[i],not_yet:T('Compare the fee bars, not the payment amount.|Compara barras de comisión, no monto del pago.|Compare barras de tarifa, não valor do pagamento.')[i]},help:[T('Compare the fee bars, not the payment amount.|Compara barras de comisión, no monto del pago.|Compare barras de tarifa, não valor do pagamento.')[i]]}]))};
export const paymentsMethods=[lesson('payments-digital',4,'Compare the full payment route|Compara la ruta completa del pago|Compare a rota completa do pagamento','Check cost, arrival timing and correction terms for the actual payment need.|Revisa costo, llegada y condiciones de corrección según el pago necesario.|Confira custo, chegada e condições de correção conforme o pagamento necessário.','Choosing a payment route by fee alone or assuming that all completed transfers can be reversed.',[
 E('example-01','More than the fee|Más que la comisión|Mais que a tarifa','A cheaper method may arrive after a deadline. Compare fees, arrival and correction terms before choosing the route.|Un método más barato puede llegar tarde. Compara comisiones, llegada y condiciones de corrección antes de elegir.|Um método mais barato pode chegar tarde. Compare tarifas, chegada e condições de correção antes de escolher.'),
 feeChart,
 Q('guided-01','guided','Fictional route A arrives tomorrow; B arrives today; the verified bill requires arrival today.|La ruta ficticia A llega mañana; B llega hoy; la cuenta exige llegada hoy.|A rota fictícia A chega amanhã; B chega hoje; a conta exige chegada hoje.','Which route meets the stated timing?|¿Qué ruta cumple las fechas indicadas?|Qual rota cumpre as datas informadas?',['B|B|B','A|A|A','Either, because sending is enough|Cualquiera, porque basta enviar|Qualquer uma, porque basta enviar'],'The requirement concerns arrival, not merely sending the instruction.|El requisito es llegar, no solo enviar la instrucción.|O requisito é chegar, não só enviar a instrução.','Compare arrival with the actual due time.|Compara llegada con el vencimiento real.|Compare chegada com o vencimento real.'),
 Q('practice-01','practice','Fictional transfer: recipient must receive 60 dollars; the sender pays a separate fee of 3.|Transferencia ficticia: destinatario recibe 60 pesos; quien envía paga comisión aparte de 3.|Transferência fictícia: destinatário recebe 60 reais; quem envia paga tarifa separada de 3.','Total leaving the sender?|¿Total que sale del remitente?|Total que sai de quem envia?',['63|63|63','60|60|60','57|57|57'],'60 + 3 = 63 leaves the sender under these terms.|60 + 3 = 63 sale del remitente bajo esas condiciones.|60 + 3 = 63 sai de quem envia nessas condições.','The stated fee is additional, not deducted from the recipient amount.|La comisión indicada es aparte, no descuento al destinatario.|A tarifa informada é separada, não desconto do destinatário.',[[60,3],op('add',I(0),I(1))]),
 Q('practice-02','practice','This fictional method normally cannot cancel completed transfers.|Un método ficticio avisa que transferencias realizadas no pueden cancelarse por su proceso normal.|Um método fictício avisa que transferências concluídas não podem ser canceladas pelo processo normal.','What matters before confirming?|¿Qué importa antes de confirmar?|O que importa antes de confirmar?',['Verify the destination and amount carefully|Verificar cuidadosamente destino y monto|Conferir destino e valor com cuidado','Assume cancellation is always available|Suponer disponible toda cancelación|Supor disponível todo cancelamento','Send a guessed amount and fix it later|Enviar monto supuesto y corregir después|Enviar valor suposto e corrigir depois'],'The stated correction limit makes the initial check especially relevant.|El límite de corrección vuelve especialmente importante la revisión inicial.|O limite de correção torna especialmente importante a conferência inicial.','Use the actual method’s terms, not a universal reversal assumption.|Usa condiciones reales, no supongas reversión universal.|Use condições reais, não suponha reversão universal.'),
 Q('practice-03','practice','Both methods arrive on time; one fee is unknown.|Dos métodos cumplen el plazo; una comisión se indica y la otra se desconoce.|Dois métodos cumprem o prazo; uma tarifa é informada e a outra é desconhecida.','Can the cheaper route be established yet?|¿Ya sabes cuál ruta cuesta menos?|Já sabe qual rota custa menos?',['No, verify the missing fee|No, verifica la comisión faltante|Não, confira a tarifa ausente','Yes, undisclosed always means zero|Sí, no indicado siempre significa cero|Sim, não informado sempre significa zero','Yes, faster always means cheaper|Sí, más rápido siempre es más barato|Sim, mais rápido sempre é mais barato'],'An undisclosed fee is missing information, not a zero charge.|Una comisión no indicada es dato faltante, no cobro cero.|Uma tarifa não informada é dado ausente, não cobrança zero.','Compare complete terms before deciding on cost.|Compara condiciones completas antes de decidir por costo.|Compare condições completas antes de decidir pelo custo.'),
 Q('transfer-01','transfer','A supplier needs full payment today; this route deducts fees.|Un proveedor necesita el monto completo a tiempo; una ruta descuenta comisión de lo entregado.|Um fornecedor precisa do valor completo no prazo; uma rota desconta tarifa do que entrega.','What determines suitability?|¿Qué datos determinan si sirve?|Quais dados mostram adequação?',['Net receipt and arrival time|Recepción neta y hora de llegada|Recebimento líquido e hora de chegada','Only the amount typed by the sender|Solo el monto escrito al enviar|Só o valor digitado por quem envia','Only app availability|Solo si la ruta tiene aplicación|Só se a rota tem aplicativo'],'The recipient must get the required net amount by the deadline.|El destinatario debe recibir el neto necesario dentro del plazo.|O destinatário deve receber o líquido necessário dentro do prazo.','Check what arrives and when, not just what is sent.|Revisa qué llega y cuándo, no solo qué se envía.|Confira o que chega e quando, não só o que é enviado.')])];
