import type { PlacementItem } from '../types';

// ─── Adventure 2 (ages 8–9) ──────────────────────────────────────────────────

const A2_ITEMS: PlacementItem[] = [
  {
    id: 'P-A2-NUM-001',
    adventure: 2, saga: 1, dimension: 'numeracy', difficulty: 2,
    type: 'multiple_choice',
    question_es: 'Si tienes $20 y te dan $15 más, ¿cuánto dinero tienes en total?',
    question_en: 'If you have $20 and someone gives you $15 more, how much money do you have?',
    options_es: ['$25', '$35', '$40', '$30'],
    options_en: ['$25', '$35', '$40', '$30'],
    correct_index: 1,
    expected_time_sec: 10,
    tags: ['addition', 'money_basics'],
  },
  {
    id: 'P-A2-NUM-002',
    adventure: 2, saga: 1, dimension: 'numeracy', difficulty: 3,
    type: 'multiple_choice',
    question_es: 'Tienes $50 y gastas $23 en un juguete. ¿Cuánto dinero te queda?',
    question_en: 'You have $50 and spend $23 on a toy. How much money do you have left?',
    options_es: ['$33', '$23', '$27', '$37'],
    options_en: ['$33', '$23', '$27', '$37'],
    correct_index: 2,
    expected_time_sec: 12,
    tags: ['subtraction', 'money_basics'],
  },
  {
    id: 'P-A2-SAV-001',
    adventure: 2, saga: 1, dimension: 'saving', difficulty: 2,
    type: 'multiple_choice',
    question_es: 'Quieres comprar algo que cuesta $60 pero solo tienes $20. ¿Qué es lo mejor que puedes hacer?',
    question_en: 'You want to buy something that costs $60 but only have $20. What is the best thing to do?',
    options_es: ['Pedirlo prestado y ya', 'Guardar poco a poco hasta tenerlos', 'Olvidarte de comprarlo', 'Pedir dinero a muchos amigos'],
    options_en: ['Borrow and forget about it', 'Save little by little until you have enough', 'Forget about buying it', 'Ask many friends for money'],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['saving', 'goals'],
  },
  {
    id: 'P-A2-SAV-002',
    adventure: 2, saga: 2, dimension: 'saving', difficulty: 3,
    type: 'multiple_choice',
    question_es: 'Si guardas $10 cada semana durante 4 semanas, ¿cuánto habrás ahorrado?',
    question_en: 'If you save $10 every week for 4 weeks, how much will you have saved?',
    options_es: ['$30', '$14', '$40', '$44'],
    options_en: ['$30', '$14', '$40', '$44'],
    correct_index: 2,
    expected_time_sec: 10,
    tags: ['saving', 'multiplication'],
  },
  {
    id: 'P-A2-SEC-001',
    adventure: 2, saga: 1, dimension: 'security', difficulty: 2,
    type: 'true_false',
    question_es: '¿Es seguro compartir tu contraseña con tu mejor amigo?',
    question_en: 'Is it safe to share your password with your best friend?',
    correct_bool: false,
    expected_time_sec: 8,
    tags: ['password', 'digital_safety'],
  },
  {
    id: 'P-A2-SEC-002',
    adventure: 2, saga: 2, dimension: 'security', difficulty: 3,
    type: 'multiple_choice',
    question_es: 'Un desconocido en internet te escribe: "¿Quieres ganar dinero fácil?" ¿Qué haces?',
    question_en: 'A stranger online writes to you: "Want to make easy money?" What do you do?',
    options_es: ['Responder y preguntar cómo', 'Ignorarlo sin responder', 'Darle tu número de teléfono', 'Contarles a tus amigos'],
    options_en: ['Reply and ask how', 'Ignore it without responding', 'Give them your phone number', 'Tell your friends about it'],
    correct_index: 1,
    expected_time_sec: 12,
    tags: ['online_safety', 'strangers'],
  },
];

// ─── Adventure 3 (ages 10–12) ────────────────────────────────────────────────

const A3_ITEMS: PlacementItem[] = [
  {
    id: 'P-A3-NUM-001',
    adventure: 3, saga: 1, dimension: 'numeracy', difficulty: 3,
    type: 'multiple_choice',
    question_es: 'Una chamarra cuesta $80 y tiene un descuento del 25%. ¿Cuánto pagas?',
    question_en: 'A jacket costs $80 and has a 25% discount. How much do you pay?',
    options_es: ['$55', '$60', '$65', '$75'],
    options_en: ['$55', '$60', '$65', '$75'],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['percentages', 'discounts'],
  },
  {
    id: 'P-A3-NUM-002',
    adventure: 3, saga: 2, dimension: 'numeracy', difficulty: 4,
    type: 'multiple_choice',
    question_es: 'Si ahorras $25 al mes, ¿cuánto tendrás al final de 1 año?',
    question_en: 'If you save $25 per month, how much will you have at the end of 1 year?',
    options_es: ['$250', '$300', '$275', '$325'],
    options_en: ['$250', '$300', '$275', '$325'],
    correct_index: 1,
    expected_time_sec: 12,
    tags: ['multiplication', 'annual_savings'],
  },
  {
    id: 'P-A3-SAV-001',
    adventure: 3, saga: 1, dimension: 'saving', difficulty: 3,
    type: 'multiple_choice',
    question_es: '¿Qué es un presupuesto?',
    question_en: 'What is a budget?',
    options_es: [
      'Un tipo de banco digital',
      'Un plan que muestra cuánto dinero entra y cuánto sale',
      'Una forma de invertir en acciones',
      'Un descuento especial en tiendas',
    ],
    options_en: [
      'A type of digital bank',
      'A plan showing how much money comes in and goes out',
      'A way to invest in stocks',
      'A special discount at stores',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['budget', 'financial_concepts'],
  },
  {
    id: 'P-A3-SAV-002',
    adventure: 3, saga: 3, dimension: 'saving', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Para qué sirve un fondo de emergencia?',
    question_en: 'What is an emergency fund for?',
    options_es: [
      'Para gastar en lujos cuando quieras',
      'Para tener dinero disponible cuando algo inesperado ocurre',
      'Para invertir en acciones',
      'Para pagar la renta cada mes',
    ],
    options_en: [
      'To spend on luxuries whenever you want',
      'To have money available when something unexpected happens',
      'To invest in stocks',
      'To pay rent each month',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['emergency_fund', 'financial_planning'],
  },
  {
    id: 'P-A3-INV-001',
    adventure: 3, saga: 2, dimension: 'investing', difficulty: 3,
    type: 'multiple_choice',
    question_es: '¿Cuál de estas opciones puede hacerte ganar dinero con el tiempo?',
    question_en: 'Which of these options can make you money over time?',
    options_es: [
      'Guardar billetes debajo del colchón',
      'Invertir en una empresa que crece',
      'Gastar todo en cosas nuevas',
      'Prestarle a amigos sin cobrar interés',
    ],
    options_en: [
      'Keep bills under the mattress',
      'Invest in a growing company',
      'Spend it all on new things',
      'Lend to friends without interest',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['investing_basics', 'growth'],
  },
  {
    id: 'P-A3-SEC-001',
    adventure: 3, saga: 2, dimension: 'security', difficulty: 3,
    type: 'multiple_choice',
    question_es: '¿Qué es el "phishing"?',
    question_en: 'What is "phishing"?',
    options_es: [
      'Un tipo de pesca deportiva',
      'Un engaño para robarte información haciéndose pasar por alguien de confianza',
      'Una contraseña muy segura',
      'Un juego en línea',
    ],
    options_en: [
      'A type of sport fishing',
      'A scam to steal your info by pretending to be someone trustworthy',
      'A very secure password',
      'An online game',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['phishing', 'cybersecurity'],
  },
];

// ─── Adventure 4 (ages 13–14) ────────────────────────────────────────────────

const A4_ITEMS: PlacementItem[] = [
  {
    id: 'P-A4-NUM-001',
    adventure: 4, saga: 1, dimension: 'numeracy', difficulty: 3,
    type: 'multiple_choice',
    question_es: 'Inviertes $1,000 con un interés anual del 10%. ¿Cuánto tendrás al final de 1 año?',
    question_en: 'You invest $1,000 at 10% annual interest. How much will you have after 1 year?',
    options_es: ['$1,010', '$1,100', '$1,200', '$1,050'],
    options_en: ['$1,010', '$1,100', '$1,200', '$1,050'],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['interest', 'investing'],
  },
  {
    id: 'P-A4-NUM-002',
    adventure: 4, saga: 2, dimension: 'numeracy', difficulty: 4,
    type: 'multiple_choice',
    question_es: 'Una acción vale $50 y sube un 20%. ¿Cuánto vale ahora?',
    question_en: 'A stock is worth $50 and rises 20%. How much is it worth now?',
    options_es: ['$55', '$60', '$70', '$65'],
    options_en: ['$55', '$60', '$70', '$65'],
    correct_index: 1,
    expected_time_sec: 12,
    tags: ['percentages', 'stocks'],
  },
  {
    id: 'P-A4-SAV-001',
    adventure: 4, saga: 1, dimension: 'saving', difficulty: 3,
    type: 'multiple_choice',
    question_es: '¿Cuál es la diferencia entre una necesidad y un deseo?',
    question_en: 'What is the difference between a need and a want?',
    options_es: [
      'No hay diferencia',
      'Las necesidades son esenciales para vivir; los deseos son extras que queremos pero no necesitamos',
      'Los deseos son más importantes que las necesidades',
      'Las necesidades siempre cuestan más dinero',
    ],
    options_en: [
      'There is no difference',
      'Needs are essential for living; wants are extras we desire but don\'t need',
      'Wants are more important than needs',
      'Needs always cost more money',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['needs_vs_wants', 'budgeting'],
  },
  {
    id: 'P-A4-INV-001',
    adventure: 4, saga: 2, dimension: 'investing', difficulty: 3,
    type: 'multiple_choice',
    question_es: '¿Qué significa "diversificar" una inversión?',
    question_en: 'What does it mean to "diversify" an investment?',
    options_es: [
      'Invertir todo en una sola empresa ganadora',
      'Repartir el dinero en diferentes tipos de inversiones para reducir el riesgo',
      'Invertir solo en criptomonedas',
      'Guardar dinero en diferentes bancos',
    ],
    options_en: [
      'Invest everything in a single winning company',
      'Spread money across different investment types to reduce risk',
      'Invest only in cryptocurrencies',
      'Keep money in different banks',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['diversification', 'risk'],
  },
  {
    id: 'P-A4-INV-002',
    adventure: 4, saga: 3, dimension: 'investing', difficulty: 4,
    type: 'true_false',
    question_es: 'Una inversión con mayor riesgo siempre garantiza mayores ganancias.',
    question_en: 'A higher-risk investment always guarantees higher returns.',
    correct_bool: false,
    expected_time_sec: 10,
    tags: ['risk_return', 'investing'],
  },
  {
    id: 'P-A4-SEC-001',
    adventure: 4, saga: 2, dimension: 'security', difficulty: 4,
    type: 'multiple_choice',
    question_es: 'Recibes un correo de tu "banco" pidiendo que confirmes tu contraseña. ¿Qué haces?',
    question_en: 'You receive an email from your "bank" asking you to confirm your password. What do you do?',
    options_es: [
      'Ingreso mi contraseña inmediatamente',
      'Ignoro el correo y llamo directamente al banco para verificar',
      'Respondo con mis datos personales',
      'Lo reenvío a mis amigos para que me ayuden',
    ],
    options_en: [
      'Enter my password immediately',
      'Ignore the email and call the bank directly to verify',
      'Reply with my personal information',
      'Forward it to friends to get help',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['phishing', 'banking_security'],
  },
  {
    id: 'P-A4-SEC-002',
    adventure: 4, saga: 3, dimension: 'security', difficulty: 3,
    type: 'true_false',
    question_es: 'La autenticación de dos factores (2FA) hace que tu cuenta sea más segura.',
    question_en: 'Two-factor authentication (2FA) makes your account more secure.',
    correct_bool: true,
    expected_time_sec: 8,
    tags: ['2fa', 'account_security'],
  },
];

// ─── Adventure 5 (ages 15–17) ────────────────────────────────────────────────

const A5_ITEMS: PlacementItem[] = [
  {
    id: 'P-A5-NUM-001',
    adventure: 5, saga: 1, dimension: 'numeracy', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Qué es la inflación?',
    question_en: 'What is inflation?',
    options_es: [
      'El aumento general de precios con el tiempo que reduce el poder adquisitivo del dinero',
      'El interés que ganas en una cuenta bancaria',
      'El costo de solicitar un préstamo',
      'El precio de comprar acciones en bolsa',
    ],
    options_en: [
      'The general rise in prices over time that reduces the purchasing power of money',
      'The interest you earn in a bank account',
      'The cost of taking out a loan',
      'The price of buying stocks on the exchange',
    ],
    correct_index: 0,
    expected_time_sec: 15,
    tags: ['inflation', 'macroeconomics'],
  },
  {
    id: 'P-A5-SAV-001',
    adventure: 5, saga: 1, dimension: 'saving', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Cuántos meses de gastos se recomienda tener en un fondo de emergencia?',
    question_en: 'How many months of expenses is it recommended to have in an emergency fund?',
    options_es: ['1 mes', '2 meses', 'Entre 3 y 6 meses', '12 meses o más'],
    options_en: ['1 month', '2 months', 'Between 3 and 6 months', '12 months or more'],
    correct_index: 2,
    expected_time_sec: 12,
    tags: ['emergency_fund', 'financial_planning'],
  },
  {
    id: 'P-A5-INV-001',
    adventure: 5, saga: 2, dimension: 'investing', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Qué es el S&P 500?',
    question_en: 'What is the S&P 500?',
    options_es: [
      'Un tipo especial de cuenta bancaria',
      'Un índice que sigue el desempeño de las 500 empresas más grandes de EE.UU.',
      'Una criptomoneda popular',
      'Un fondo de pensiones del gobierno',
    ],
    options_en: [
      'A special type of bank account',
      'An index tracking the performance of the 500 largest US companies',
      'A popular cryptocurrency',
      'A government pension fund',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['index_funds', 'stock_market'],
  },
  {
    id: 'P-A5-INV-002',
    adventure: 5, saga: 3, dimension: 'investing', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Cuál es la diferencia principal entre una acción y un bono?',
    question_en: 'What is the main difference between a stock and a bond?',
    options_es: [
      'No hay diferencia práctica',
      'Una acción es parte de propiedad en una empresa; un bono es un préstamo a una empresa o gobierno',
      'Los bonos siempre son más rentables que las acciones',
      'Las acciones son emitidas por el gobierno',
    ],
    options_en: [
      'There is no practical difference',
      'A stock is ownership in a company; a bond is a loan to a company or government',
      'Bonds are always more profitable than stocks',
      'Stocks are issued by the government',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['stocks', 'bonds', 'investing'],
  },
  {
    id: 'P-A5-SEC-001',
    adventure: 5, saga: 2, dimension: 'security', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Cuál es la mejor forma de protegerte del robo de identidad en línea?',
    question_en: 'What is the best way to protect yourself from online identity theft?',
    options_es: [
      'Usar la misma contraseña en todos los sitios para recordarla fácil',
      'Usar contraseñas únicas y fuertes con un gestor de contraseñas y activar el 2FA',
      'Compartir tus datos solo con amigos de confianza',
      'Evitar usar internet tanto como sea posible',
    ],
    options_en: [
      'Use the same password everywhere to remember it easily',
      'Use unique strong passwords with a password manager and enable 2FA',
      'Only share your data with trusted friends',
      'Avoid using the internet as much as possible',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['identity_theft', 'password_manager', '2fa'],
  },
  {
    id: 'P-A5-NUM-002',
    adventure: 5, saga: 2, dimension: 'numeracy', difficulty: 4,
    type: 'multiple_choice',
    question_es: 'Si inviertes $1,000 hoy al 7% de interés compuesto anual, ¿cuánto tendrás aproximadamente en 10 años?',
    question_en: 'If you invest $1,000 today at 7% compound annual interest, approximately how much will you have in 10 years?',
    options_es: ['$1,700', '$1,967', '$2,500', '$3,000'],
    options_en: ['$1,700', '$1,967', '$2,500', '$3,000'],
    correct_index: 1,
    expected_time_sec: 20,
    tags: ['compound_interest', 'long_term_investing'],
  },
];

// ─── Adventure 6 (ages 18+) ──────────────────────────────────────────────────

const A6_ITEMS: PlacementItem[] = [
  {
    id: 'P-A6-SAV-001',
    adventure: 6, saga: 1, dimension: 'saving', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Qué describe la regla del 50/30/20 en finanzas personales?',
    question_en: 'What does the 50/30/20 rule in personal finance describe?',
    options_es: [
      'Invertir el 50% en acciones, 30% en bonos y 20% en efectivo',
      'Gastar el 50% en necesidades, 30% en deseos y ahorrar/invertir el 20%',
      'Ahorrar el 50% del sueldo siempre',
      'Pagar el 50% de deudas antes de ahorrar',
    ],
    options_en: [
      'Invest 50% in stocks, 30% in bonds and 20% in cash',
      'Spend 50% on needs, 30% on wants, and save/invest 20%',
      'Always save 50% of your salary',
      'Pay off 50% of debt before saving',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['budgeting', '50_30_20'],
  },
  {
    id: 'P-A6-NUM-001',
    adventure: 6, saga: 1, dimension: 'numeracy', difficulty: 4,
    type: 'multiple_choice',
    question_es: 'Tienes una tarjeta con $10,000 de saldo y tasa del 24% anual. Si no pagas nada, ¿cuánto interés acumulas en 1 año?',
    question_en: 'You have a card with $10,000 balance at 24% annual rate. If you pay nothing, how much interest do you accumulate in 1 year?',
    options_es: ['$1,200', '$2,400', '$4,800', '$240'],
    options_en: ['$1,200', '$2,400', '$4,800', '$240'],
    correct_index: 1,
    expected_time_sec: 18,
    tags: ['credit_card', 'interest_calculation'],
  },
  {
    id: 'P-A6-INV-001',
    adventure: 6, saga: 2, dimension: 'investing', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Por qué es importante empezar a invertir lo antes posible?',
    question_en: 'Why is it important to start investing as early as possible?',
    options_es: [
      'Porque las inversiones nunca bajan de valor',
      'Por el interés compuesto: el dinero genera intereses sobre intereses con el tiempo',
      'Porque el gobierno te da beneficios fiscales automáticos',
      'Porque las acciones siempre suben en los primeros años',
    ],
    options_en: [
      'Because investments never decrease in value',
      'Because of compound interest: money generates interest on interest over time',
      'Because the government gives you automatic tax benefits',
      'Because stocks always rise in the early years',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['compound_interest', 'early_investing'],
  },
  {
    id: 'P-A6-INV-002',
    adventure: 6, saga: 3, dimension: 'investing', difficulty: 5,
    type: 'multiple_choice',
    question_es: '¿Cuál es la diferencia principal entre un fondo mutuo y un ETF?',
    question_en: 'What is the main difference between a mutual fund and an ETF?',
    options_es: [
      'Los ETFs solo invierten en oro',
      'Los ETFs se negocian en bolsa como acciones durante el día; los fondos mutuos se compran/venden al precio de cierre del día',
      'Los fondos mutuos siempre son más rentables',
      'No hay diferencia práctica entre ambos',
    ],
    options_en: [
      'ETFs only invest in gold',
      'ETFs trade on exchanges like stocks during the day; mutual funds buy/sell at end-of-day price',
      'Mutual funds are always more profitable',
      'There is no practical difference between the two',
    ],
    correct_index: 1,
    expected_time_sec: 18,
    tags: ['etf', 'mutual_fund', 'investing_vehicles'],
  },
  {
    id: 'P-A6-SEC-001',
    adventure: 6, saga: 2, dimension: 'security', difficulty: 4,
    type: 'multiple_choice',
    question_es: '¿Qué es el robo de identidad financiera?',
    question_en: 'What is financial identity theft?',
    options_es: [
      'Alguien te roba la cartera física',
      'Alguien usa tu información personal para obtener créditos o cuentas bancarias a tu nombre sin permiso',
      'Tu banco pierde tu dinero por error',
      'Alguien adivina tu contraseña por suerte',
    ],
    options_en: [
      'Someone steals your physical wallet',
      'Someone uses your personal info to get credit or accounts in your name without permission',
      'Your bank loses your money by mistake',
      'Someone guesses your password by luck',
    ],
    correct_index: 1,
    expected_time_sec: 15,
    tags: ['identity_theft', 'financial_fraud'],
  },
  {
    id: 'P-A6-NUM-002',
    adventure: 6, saga: 2, dimension: 'numeracy', difficulty: 5,
    type: 'true_false',
    question_es: 'Si la inflación es del 5% anual, el dinero que tienes hoy comprará menos cosas el año siguiente.',
    question_en: 'If inflation is 5% per year, the money you have today will buy fewer things next year.',
    correct_bool: true,
    expected_time_sec: 10,
    tags: ['inflation', 'purchasing_power'],
  },
];

// ─── Master bank ─────────────────────────────────────────────────────────────

export const ALL_ITEMS: PlacementItem[] = [
  ...A2_ITEMS,
  ...A3_ITEMS,
  ...A4_ITEMS,
  ...A5_ITEMS,
  ...A6_ITEMS,
];
