/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/com/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const COM_SEGMENTS = [] as const;
export const COM_RUBRICS = {} as const;
export const COM_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
