import type { HorizonteCopy } from '../boardTypes';

/*
 * Every authored string of F2.16 to F2.18, in three native versions. Spoken math is copy too: a screen reader says
 * "f of x equals" in the learner's language, so each locale writes how its own classroom reads a formula aloud.
 */
export const COM_COPY = {
  /* ── shared by every board ── */
  tray: { role: 'heading', band: '13-17', 'en-US': 'Pieces', 'es-MX': 'Piezas', 'pt-BR': 'Peças' },
  trayEmpty: { role: 'body', band: '13-17', 'en-US': 'Every piece is placed.', 'es-MX': 'Todas las piezas están colocadas.', 'pt-BR': 'Todas as peças estão no lugar.' },
  backToTray: { role: 'option', band: '13-17', 'en-US': 'Back to the pieces', 'es-MX': 'Volver a las piezas', 'pt-BR': 'Voltar às peças' },
  showTable: { role: 'action', band: '13-17', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', band: '13-17', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  none: { role: 'data', band: '13-17', 'en-US': 'nothing yet', 'es-MX': 'nada todavía', 'pt-BR': 'nada ainda' },
  yes: { role: 'data', band: '13-17', 'en-US': 'Yes', 'es-MX': 'Sí', 'pt-BR': 'Sim' },
  no: { role: 'data', band: '13-17', 'en-US': 'No', 'es-MX': 'No', 'pt-BR': 'Não' },
  unknown: { role: 'data', band: '13-17', 'en-US': 'to find', 'es-MX': 'por hallar', 'pt-BR': 'a descobrir' },

  /* ── F2.16 networks and counting: headings, zones, names ── */
  headingPlaces: { role: 'heading', band: '13-17', 'en-US': 'Land areas', 'es-MX': 'Zonas', 'pt-BR': 'Áreas' },
  headingBridges: { role: 'heading', band: '13-17', 'en-US': 'Bridges', 'es-MX': 'Puentes', 'pt-BR': 'Pontes' },
  headingStops: { role: 'heading', band: '13-17', 'en-US': 'Stops', 'es-MX': 'Paradas', 'pt-BR': 'Paradas' },
  headingOutcomes: { role: 'heading', band: '13-17', 'en-US': 'Outcomes', 'es-MX': 'Resultados', 'pt-BR': 'Resultados' },
  headingTriangle: { role: 'heading', band: '13-17', 'en-US': 'Pascal’s triangle', 'es-MX': 'Triángulo de Pascal', 'pt-BR': 'Triângulo de Pascal' },
  zoneOdd: { role: 'data', band: '13-17', 'en-US': 'Odd areas', 'es-MX': 'Zonas impares', 'pt-BR': 'Áreas ímpares' },
  zoneWalk: { role: 'data', band: '13-17', 'en-US': 'My walk', 'es-MX': 'Mi recorrido', 'pt-BR': 'Meu percurso' },
  zoneRoute: { role: 'data', band: '13-17', 'en-US': 'My route', 'es-MX': 'Mi ruta', 'pt-BR': 'Minha rota' },
  zoneKeep: { role: 'data', band: '13-17', 'en-US': 'Outcomes I keep', 'es-MX': 'Resultados que dejo', 'pt-BR': 'Resultados que mantenho' },
  bridgeN: { role: 'data', band: '13-17', 'en-US': 'Bridge {n}', 'es-MX': 'Puente {n}', 'pt-BR': 'Ponte {n}' },
  roadN: { role: 'data', band: '13-17', 'en-US': 'Road {n}', 'es-MX': 'Camino {n}', 'pt-BR': 'Estrada {n}' },
  between: { role: 'data', band: '13-17', 'en-US': 'between {a} and {b}', 'es-MX': 'entre {a} y {b}', 'pt-BR': 'entre {a} e {b}' },
  stepN: { role: 'data', band: '13-17', 'en-US': 'Step {n}', 'es-MX': 'Paso {n}', 'pt-BR': 'Passo {n}' },
  stopN: { role: 'data', band: '13-17', 'en-US': 'Stop {n}', 'es-MX': 'Parada {n}', 'pt-BR': 'Parada {n}' },
  tagStart: { role: 'data', band: '13-17', 'en-US': 'Start', 'es-MX': 'Salida', 'pt-BR': 'Partida' },
  tagGoal: { role: 'data', band: '13-17', 'en-US': 'End', 'es-MX': 'Llegada', 'pt-BR': 'Chegada' },
  then: { role: 'data', band: '13-17', 'en-US': 'then', 'es-MX': 'luego', 'pt-BR': 'depois' },
  unreached: { role: 'data', band: '13-17', 'en-US': 'not reached', 'es-MX': 'sin alcanzar', 'pt-BR': 'não alcançado' },

  /* ── the cheapest-route helper ── */
  showSteps: { role: 'action', band: '13-17', 'en-US': 'Show the steps', 'es-MX': 'Ver los pasos', 'pt-BR': 'Ver os passos' },
  hideSteps: { role: 'action', band: '13-17', 'en-US': 'Hide the steps', 'es-MX': 'Ocultar los pasos', 'pt-BR': 'Ocultar os passos' },
  stepsHeading: { role: 'heading', band: '13-17', 'en-US': 'Cheapest cost, step by step', 'es-MX': 'El costo menor, paso a paso', 'pt-BR': 'O menor custo, passo a passo' },
  stepLine: { role: 'body', band: '13-17', 'en-US': 'Step {n} of {total}: the cost to {name} is final.', 'es-MX': 'Paso {n} de {total}: el costo hasta {name} ya es el menor.', 'pt-BR': 'Passo {n} de {total}: o custo até {name} já é o menor.' },
  stepPrev: { role: 'action', band: '13-17', 'en-US': 'Previous step', 'es-MX': 'Paso anterior', 'pt-BR': 'Passo anterior' },
  stepNext: { role: 'action', band: '13-17', 'en-US': 'Next step', 'es-MX': 'Paso siguiente', 'pt-BR': 'Próximo passo' },

  /* ── tables ── */
  tableBridges: { role: 'heading', band: '13-17', 'en-US': 'Bridges and where they go', 'es-MX': 'Puentes y a dónde llevan', 'pt-BR': 'Pontes e aonde levam' },
  tableSteps: { role: 'heading', band: '13-17', 'en-US': 'Cheapest cost so far', 'es-MX': 'El costo menor hasta ahora', 'pt-BR': 'O menor custo até agora' },
  tableRoads: { role: 'heading', band: '13-17', 'en-US': 'Roads and their costs', 'es-MX': 'Caminos y sus costos', 'pt-BR': 'Estradas e seus custos' },
  tableOutcomes: { role: 'heading', band: '13-17', 'en-US': 'Outcomes and what you keep', 'es-MX': 'Resultados y lo que dejas', 'pt-BR': 'Resultados e o que você mantém' },
  tableTriangle: { role: 'heading', band: '13-17', 'en-US': 'The triangle, row by row', 'es-MX': 'El triángulo, fila por fila', 'pt-BR': 'O triângulo, linha por linha' },
  tableBits: { role: 'heading', band: '13-17', 'en-US': 'Bits and their values', 'es-MX': 'Bits y sus valores', 'pt-BR': 'Bits e seus valores' },
  tableTruth: { role: 'heading', band: '13-17', 'en-US': 'Truth table', 'es-MX': 'Tabla de verdad', 'pt-BR': 'Tabela-verdade' },
  tableWiring: { role: 'heading', band: '13-17', 'en-US': 'Wiring and gates', 'es-MX': 'Conexiones y compuertas', 'pt-BR': 'Ligações e portas' },
  colBridge: { role: 'data', band: '13-17', 'en-US': 'Bridge', 'es-MX': 'Puente', 'pt-BR': 'Ponte' },
  colFrom: { role: 'data', band: '13-17', 'en-US': 'From', 'es-MX': 'Desde', 'pt-BR': 'De' },
  colTo: { role: 'data', band: '13-17', 'en-US': 'To', 'es-MX': 'Hasta', 'pt-BR': 'Até' },
  colPlace: { role: 'data', band: '13-17', 'en-US': 'Place', 'es-MX': 'Lugar', 'pt-BR': 'Lugar' },
  colCost: { role: 'data', band: '13-17', 'en-US': 'Cost', 'es-MX': 'Costo', 'pt-BR': 'Custo' },
  colThrough: { role: 'data', band: '13-17', 'en-US': 'Came from', 'es-MX': 'Viene de', 'pt-BR': 'Vem de' },
  colRoad: { role: 'data', band: '13-17', 'en-US': 'Road', 'es-MX': 'Camino', 'pt-BR': 'Estrada' },
  colOutcome: { role: 'data', band: '13-17', 'en-US': 'Outcome', 'es-MX': 'Resultado', 'pt-BR': 'Resultado' },
  colKept: { role: 'data', band: '13-17', 'en-US': 'Kept', 'es-MX': 'Se deja', 'pt-BR': 'Mantido' },
  colRow: { role: 'data', band: '13-17', 'en-US': 'Row', 'es-MX': 'Fila', 'pt-BR': 'Linha' },
  colNumbers: { role: 'data', band: '13-17', 'en-US': 'Numbers', 'es-MX': 'Números', 'pt-BR': 'Números' },
  colMarked: { role: 'data', band: '13-17', 'en-US': 'Marked', 'es-MX': 'Marcados', 'pt-BR': 'Marcados' },

  /* ── picture descriptions and statuses: the text equivalent of each board ── */
  chartGraph: { role: 'data', band: '13-17', 'en-US': 'Map of {places} land areas joined by {bridges} bridges', 'es-MX': 'Mapa de {places} zonas unidas por {bridges} puentes', 'pt-BR': 'Mapa de {places} áreas ligadas por {bridges} pontes' },
  chartRoute: { role: 'data', band: '13-17', 'en-US': 'Map of {places} places joined by {roads} roads, each with a cost', 'es-MX': 'Mapa de {places} lugares unidos por {roads} caminos, cada uno con su costo', 'pt-BR': 'Mapa de {places} lugares ligados por {roads} estradas, cada uma com seu custo' },
  chartTree: { role: 'data', band: '13-17', 'en-US': 'Tree of choices with {pick} picks and {total} outcomes', 'es-MX': 'Árbol de decisiones con {pick} elecciones y {total} resultados', 'pt-BR': 'Árvore de escolhas com {pick} escolhas e {total} resultados' },
  chartPascal: { role: 'data', band: '13-17', 'en-US': 'Pascal’s triangle, one button per number', 'es-MX': 'Triángulo de Pascal, un botón por número', 'pt-BR': 'Triângulo de Pascal, um botão por número' },
  chartGates: { role: 'data', band: '13-17', 'en-US': 'Circuit with {inputs} switches and {gates} gates', 'es-MX': 'Circuito con {inputs} interruptores y {gates} compuertas', 'pt-BR': 'Circuito com {inputs} interruptores e {gates} portas' },
  oddStatus: { role: 'data', band: '13-17', 'en-US': 'Marked {count} of {total} areas: {list}.', 'es-MX': '{count} de {total} zonas marcadas: {list}.', 'pt-BR': '{count} de {total} áreas marcadas: {list}.' },
  walkStatus: { role: 'data', band: '13-17', 'en-US': '{count} of {total} bridges crossed: {list}.', 'es-MX': '{count} de {total} puentes cruzados: {list}.', 'pt-BR': '{count} de {total} pontes atravessadas: {list}.' },
  walkLinked: { role: 'body', band: '13-17', 'en-US': 'Each bridge starts where the last one ended.', 'es-MX': 'Cada puente empieza donde terminó el anterior.', 'pt-BR': 'Cada ponte começa onde a anterior terminou.' },
  walkBroken: { role: 'body', band: '13-17', 'en-US': 'These bridges do not join up yet.', 'es-MX': 'Estos puentes aún no se enlazan.', 'pt-BR': 'Essas pontes ainda não se ligam.' },
  routeStatus: { role: 'data', band: '13-17', 'en-US': 'Route: {list}.', 'es-MX': 'Ruta: {list}.', 'pt-BR': 'Rota: {list}.' },
  routeBroken: { role: 'body', band: '13-17', 'en-US': 'Some of these stops have no road between them.', 'es-MX': 'A algunas de estas paradas les falta un camino.', 'pt-BR': 'Algumas dessas paradas não têm estrada entre elas.' },
  routeCost: { role: 'data', band: '13-17', 'en-US': 'Total cost: {total}.', 'es-MX': 'Costo total: {total}.', 'pt-BR': 'Custo total: {total}.' },
  routeFromTo: { role: 'data', band: '13-17', 'en-US': 'from {a} to {b}', 'es-MX': 'de {a} a {b}', 'pt-BR': 'de {a} até {b}' },
  keepStatus: { role: 'data', band: '13-17', 'en-US': 'Keeping {count} of {total} outcomes.', 'es-MX': 'Dejas {count} de {total} resultados.', 'pt-BR': 'Você mantém {count} de {total} resultados.' },
  pascalStatus: { role: 'data', band: '13-17', 'en-US': 'Colored {count} of {total} numbers. Looking for multiples of {multiple}.', 'es-MX': 'Pintados {count} de {total} números. Se buscan los múltiplos de {multiple}.', 'pt-BR': '{count} de {total} números pintados. Procure os múltiplos de {multiple}.' },
  pascalCell: { role: 'data', band: '13-17', 'en-US': 'Row {row}, place {place}: {value}', 'es-MX': 'Fila {row}, lugar {place}: {value}', 'pt-BR': 'Linha {row}, posição {place}: {value}' },
  pascalRow: { role: 'data', band: '13-17', 'en-US': 'Row {row}', 'es-MX': 'Fila {row}', 'pt-BR': 'Linha {row}' },

  /* ── what the foot says when a network step is checked ── */
  metOdd: { role: 'body', band: '13-17', 'en-US': 'Right. Those areas have an odd number of bridges.', 'es-MX': 'Bien. Esas zonas tienen un número impar de puentes.', 'pt-BR': 'Certo. Essas áreas têm um número ímpar de pontes.' },
  hintOdd: { role: 'body', band: '13-17', 'en-US': 'Not yet. Count the bridges at each area again.', 'es-MX': 'Aún no. Cuenta otra vez los puentes de cada zona.', 'pt-BR': 'Ainda não. Conte de novo as pontes de cada área.' },
  metWalk: { role: 'body', band: '13-17', 'en-US': 'Right. You crossed every bridge once.', 'es-MX': 'Bien. Cruzaste cada puente una vez.', 'pt-BR': 'Certo. Você atravessou cada ponte uma vez.' },
  hintWalk: { role: 'body', band: '13-17', 'en-US': 'Not yet. Use each bridge once, joined end to end.', 'es-MX': 'Aún no. Usa cada puente una vez, unidos uno tras otro.', 'pt-BR': 'Ainda não. Use cada ponte uma vez, uma ligada à outra.' },
  metRoute: { role: 'body', band: '13-17', 'en-US': 'Right. No other route costs less.', 'es-MX': 'Bien. Ninguna otra ruta cuesta menos.', 'pt-BR': 'Certo. Nenhuma outra rota custa menos.' },
  hintRoute: { role: 'body', band: '13-17', 'en-US': 'Not yet. Look for a cheaper way to the end.', 'es-MX': 'Aún no. Busca un camino más barato hasta la llegada.', 'pt-BR': 'Ainda não. Procure um caminho mais barato até a chegada.' },
  metTree: { role: 'body', band: '13-17', 'en-US': 'Right. You kept every outcome that counts.', 'es-MX': 'Bien. Dejaste todos los resultados que cuentan.', 'pt-BR': 'Certo. Você manteve todos os resultados que contam.' },
  hintTreeOrder: { role: 'body', band: '13-17', 'en-US': 'Not yet. Keep every order that fits, and no others.', 'es-MX': 'Aún no. Deja todos los órdenes que cumplen, y ninguno más.', 'pt-BR': 'Ainda não. Mantenha todas as ordens que servem, e nenhuma outra.' },
  hintTreeGroup: { role: 'body', band: '13-17', 'en-US': 'Not yet. Keep each different group once, whatever the order.', 'es-MX': 'Aún no. Deja cada grupo distinto una vez, sin importar el orden.', 'pt-BR': 'Ainda não. Mantenha cada grupo diferente uma vez, em qualquer ordem.' },
  metPascal: { role: 'body', band: '13-17', 'en-US': 'Right. Those are all the multiples.', 'es-MX': 'Bien. Esos son todos los múltiplos.', 'pt-BR': 'Certo. Esses são todos os múltiplos.' },
  hintPascal: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check every number once more.', 'es-MX': 'Aún no. Revisa otra vez cada número.', 'pt-BR': 'Ainda não. Confira cada número mais uma vez.' },

  /* ── F2.18 bits and logic gates ── */
  headingBits: { role: 'heading', band: '13-17', 'en-US': 'Bits', 'es-MX': 'Bits', 'pt-BR': 'Bits' },
  headingGates: { role: 'heading', band: '13-17', 'en-US': 'Gates', 'es-MX': 'Compuertas', 'pt-BR': 'Portas' },
  bitsOn: { role: 'data', band: '13-17', 'en-US': 'Switched on', 'es-MX': 'Encendidos', 'pt-BR': 'Ligados' },
  bitsRow: { role: 'data', band: '13-17', 'en-US': 'Bits, biggest first', 'es-MX': 'Bits, del más grande al más chico', 'pt-BR': 'Bits, do maior para o menor' },
  bitName: { role: 'data', band: '13-17', 'en-US': 'Bit worth {weight}', 'es-MX': 'Bit que vale {weight}', 'pt-BR': 'Bit que vale {weight}' },
  bitsStatus: { role: 'data', band: '13-17', 'en-US': 'On: {list}. Total {total} of {target}.', 'es-MX': 'Encendidos: {list}. Suma {total} de {target}.', 'pt-BR': 'Ligados: {list}. Soma {total} de {target}.' },
  bitsTotal: { role: 'data', band: '13-17', 'en-US': '{total} of {target}', 'es-MX': '{total} de {target}', 'pt-BR': '{total} de {target}' },
  colWeight: { role: 'data', band: '13-17', 'en-US': 'Worth', 'es-MX': 'Vale', 'pt-BR': 'Vale' },
  colBit: { role: 'data', band: '13-17', 'en-US': 'Bit', 'es-MX': 'Bit', 'pt-BR': 'Bit' },
  colValue: { role: 'data', band: '13-17', 'en-US': 'Adds', 'es-MX': 'Suma', 'pt-BR': 'Soma' },
  colGoal: { role: 'data', band: '13-17', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  colNow: { role: 'data', band: '13-17', 'en-US': 'Now', 'es-MX': 'Ahora', 'pt-BR': 'Agora' },
  colMatch: { role: 'data', band: '13-17', 'en-US': 'Match', 'es-MX': 'Coincide', 'pt-BR': 'Combina' },
  colPosition: { role: 'data', band: '13-17', 'en-US': 'Position', 'es-MX': 'Posición', 'pt-BR': 'Posição' },
  colReads: { role: 'data', band: '13-17', 'en-US': 'Reads', 'es-MX': 'Lee', 'pt-BR': 'Lê' },
  colGate: { role: 'data', band: '13-17', 'en-US': 'Gate', 'es-MX': 'Compuerta', 'pt-BR': 'Porta' },
  positionN: { role: 'data', band: '13-17', 'en-US': 'Position {n}', 'es-MX': 'Posición {n}', 'pt-BR': 'Posição {n}' },
  readsOne: { role: 'data', band: '13-17', 'en-US': 'Reads {a}.', 'es-MX': 'Lee {a}.', 'pt-BR': 'Lê {a}.' },
  readsTwo: { role: 'data', band: '13-17', 'en-US': 'Reads {a} and {b}.', 'es-MX': 'Lee {a} y {b}.', 'pt-BR': 'Lê {a} e {b}.' },
  outputIs: { role: 'data', band: '13-17', 'en-US': 'Output: {name}.', 'es-MX': 'Salida: {name}.', 'pt-BR': 'Saída: {name}.' },
  gateStatus: { role: 'data', band: '13-17', 'en-US': '{placed} of {slots} gates placed. {right} of {total} rows match.', 'es-MX': '{placed} de {slots} compuertas colocadas. Coinciden {right} de {total} filas.', 'pt-BR': '{placed} de {slots} portas colocadas. {right} de {total} linhas combinam.' },
  'gate:and': { role: 'option', band: '13-17', 'en-US': 'AND', 'es-MX': 'AND', 'pt-BR': 'AND' },
  'gate:or': { role: 'option', band: '13-17', 'en-US': 'OR', 'es-MX': 'OR', 'pt-BR': 'OR' },
  'gate:not': { role: 'option', band: '13-17', 'en-US': 'NOT', 'es-MX': 'NOT', 'pt-BR': 'NOT' },
  'gate:xor': { role: 'option', band: '13-17', 'en-US': 'XOR', 'es-MX': 'XOR', 'pt-BR': 'XOR' },
  'gate:nand': { role: 'option', band: '13-17', 'en-US': 'NAND', 'es-MX': 'NAND', 'pt-BR': 'NAND' },
  'gate:nor': { role: 'option', band: '13-17', 'en-US': 'NOR', 'es-MX': 'NOR', 'pt-BR': 'NOR' },
  'gateNote:and': { role: 'data', band: '13-17', 'en-US': 'on only when every input is on', 'es-MX': 'se enciende solo si todas las entradas están encendidas', 'pt-BR': 'liga só quando todas as entradas estão ligadas' },
  'gateNote:or': { role: 'data', band: '13-17', 'en-US': 'on when any input is on', 'es-MX': 'se enciende si alguna entrada está encendida', 'pt-BR': 'liga quando alguma entrada está ligada' },
  'gateNote:not': { role: 'data', band: '13-17', 'en-US': 'flips its input', 'es-MX': 'invierte su entrada', 'pt-BR': 'inverte a sua entrada' },
  'gateNote:xor': { role: 'data', band: '13-17', 'en-US': 'on when exactly one input is on', 'es-MX': 'se enciende si solo una entrada está encendida', 'pt-BR': 'liga quando só uma entrada está ligada' },
  'gateNote:nand': { role: 'data', band: '13-17', 'en-US': 'off only when every input is on', 'es-MX': 'se apaga solo si todas las entradas están encendidas', 'pt-BR': 'desliga só quando todas as entradas estão ligadas' },
  'gateNote:nor': { role: 'data', band: '13-17', 'en-US': 'on only when no input is on', 'es-MX': 'se enciende solo si ninguna entrada está encendida', 'pt-BR': 'liga só quando nenhuma entrada está ligada' },
  metBits: { role: 'body', band: '13-17', 'en-US': 'Right. Those bits add up to the target.', 'es-MX': 'Bien. Esos bits suman la meta.', 'pt-BR': 'Certo. Esses bits somam o alvo.' },
  hintBits: { role: 'body', band: '13-17', 'en-US': 'Not yet. Add up the values of the bits that are on.', 'es-MX': 'Aún no. Suma los valores de los bits encendidos.', 'pt-BR': 'Ainda não. Some os valores dos bits ligados.' },
  metGates: { role: 'body', band: '13-17', 'en-US': 'Right. The lamp follows the whole table.', 'es-MX': 'Bien. La lámpara sigue toda la tabla.', 'pt-BR': 'Certo. A lâmpada segue a tabela inteira.' },
  hintGates: { role: 'body', band: '13-17', 'en-US': 'Not yet. Compare the lamp with the table, row by row.', 'es-MX': 'Aún no. Compara la lámpara con la tabla, fila por fila.', 'pt-BR': 'Ainda não. Compare a lâmpada com a tabela, linha por linha.' },

  /* ── F2.17 explorers: predict, then find one number ── */
  headingExplore: { role: 'heading', band: '13-17', 'en-US': 'Predict, then explore', 'es-MX': 'Predice y luego explora', 'pt-BR': 'Preveja e depois explore' },
  needPredict: { role: 'body', band: '13-17', 'en-US': 'First, choose your prediction.', 'es-MX': 'Primero, elige tu predicción.', 'pt-BR': 'Primeiro, escolha a sua previsão.' },
  needAngle: { role: 'body', band: '13-17', 'en-US': 'Next, move the point to an angle.', 'es-MX': 'Ahora, mueve el punto a un ángulo.', 'pt-BR': 'Agora, mova o ponto para um ângulo.' },
  needNumber: { role: 'body', band: '13-17', 'en-US': 'Next, type the slope as a whole number.', 'es-MX': 'Ahora, escribe la pendiente como número entero.', 'pt-BR': 'Agora, digite a inclinação como número inteiro.' },
  needMark: { role: 'body', band: '13-17', 'en-US': 'Next, move the mark along x.', 'es-MX': 'Ahora, mueve la marca a lo largo de x.', 'pt-BR': 'Agora, mova a marca ao longo de x.' },
  needN: { role: 'body', band: '13-17', 'en-US': 'Next, change the number of rectangles.', 'es-MX': 'Ahora, cambia el número de rectángulos.', 'pt-BR': 'Agora, mude o número de retângulos.' },
  legendCircle: { role: 'body', band: '13-17', 'en-US': 'Predict: the angle lies in', 'es-MX': 'Predice: el ángulo está en', 'pt-BR': 'Preveja: o ângulo está em' },
  legendWave: { role: 'body', band: '13-17', 'en-US': 'Predict: in one turn the wave hits this height', 'es-MX': 'Predice: en una vuelta la onda llega a esta altura', 'pt-BR': 'Preveja: em uma volta a onda atinge esta altura' },
  legendSecant: { role: 'body', band: '13-17', 'en-US': 'Predict: the slope at this point is', 'es-MX': 'Predice: la pendiente en este punto es', 'pt-BR': 'Preveja: a inclinação neste ponto é' },
  legendLink: { role: 'body', band: '13-17', 'en-US': 'Between its two flat spots, the curve', 'es-MX': 'Entre sus dos puntos planos, la curva', 'pt-BR': 'Entre os dois pontos planos, a curva' },
  legendRiemann: { role: 'body', band: '13-17', 'en-US': 'Predict: the estimate will be', 'es-MX': 'Predice: la estimación será', 'pt-BR': 'Preveja: a estimativa será' },
  legendArea: { role: 'body', band: '13-17', 'en-US': 'Predict: when the area hits the target, it is', 'es-MX': 'Predice: cuando el área llega a la meta, está', 'pt-BR': 'Preveja: quando a área chega ao alvo, ela está' },
  'opt:quadrant-1': { role: 'option', band: '13-17', 'en-US': 'Quadrant 1', 'es-MX': 'Cuadrante 1', 'pt-BR': 'Quadrante 1' },
  'opt:quadrant-2': { role: 'option', band: '13-17', 'en-US': 'Quadrant 2', 'es-MX': 'Cuadrante 2', 'pt-BR': 'Quadrante 2' },
  'opt:quadrant-3': { role: 'option', band: '13-17', 'en-US': 'Quadrant 3', 'es-MX': 'Cuadrante 3', 'pt-BR': 'Quadrante 3' },
  'opt:quadrant-4': { role: 'option', band: '13-17', 'en-US': 'Quadrant 4', 'es-MX': 'Cuadrante 4', 'pt-BR': 'Quadrante 4' },
  'opt:axis': { role: 'option', band: '13-17', 'en-US': 'On an axis', 'es-MX': 'En un eje', 'pt-BR': 'Em um eixo' },
  'opt:times-1': { role: 'option', band: '13-17', 'en-US': 'Once', 'es-MX': 'Una vez', 'pt-BR': 'Uma vez' },
  'opt:times-2': { role: 'option', band: '13-17', 'en-US': 'Twice', 'es-MX': 'Dos veces', 'pt-BR': 'Duas vezes' },
  'opt:positive': { role: 'option', band: '13-17', 'en-US': 'Positive', 'es-MX': 'Positiva', 'pt-BR': 'Positiva' },
  'opt:negative': { role: 'option', band: '13-17', 'en-US': 'Negative', 'es-MX': 'Negativa', 'pt-BR': 'Negativa' },
  'opt:zero': { role: 'option', band: '13-17', 'en-US': 'Zero', 'es-MX': 'Cero', 'pt-BR': 'Zero' },
  'opt:rising': { role: 'option', band: '13-17', 'en-US': 'Rises', 'es-MX': 'Sube', 'pt-BR': 'Sobe' },
  'opt:falling': { role: 'option', band: '13-17', 'en-US': 'Falls', 'es-MX': 'Baja', 'pt-BR': 'Desce' },
  'opt:too-small': { role: 'option', band: '13-17', 'en-US': 'Too small', 'es-MX': 'Se queda corta', 'pt-BR': 'Fica pequena' },
  'opt:too-big': { role: 'option', band: '13-17', 'en-US': 'Too big', 'es-MX': 'Se pasa', 'pt-BR': 'Fica grande' },
  'opt:growing': { role: 'option', band: '13-17', 'en-US': 'Growing', 'es-MX': 'Creciendo', 'pt-BR': 'Crescendo' },
  'opt:shrinking': { role: 'option', band: '13-17', 'en-US': 'Shrinking', 'es-MX': 'Decreciendo', 'pt-BR': 'Diminuindo' },
  'opt:flat': { role: 'option', band: '13-17', 'en-US': 'Flat', 'es-MX': 'Plana', 'pt-BR': 'Parada' },
  findAngle: { role: 'body', band: '13-17', 'en-US': 'Find an angle where', 'es-MX': 'Halla un ángulo donde', 'pt-BR': 'Ache um ângulo em que' },
  'side:upper': { role: 'body', band: '13-17', 'en-US': 'on the upper half', 'es-MX': 'en la mitad de arriba', 'pt-BR': 'na metade de cima' },
  'side:lower': { role: 'body', band: '13-17', 'en-US': 'on the lower half', 'es-MX': 'en la mitad de abajo', 'pt-BR': 'na metade de baixo' },
  'side:right': { role: 'body', band: '13-17', 'en-US': 'on the right half', 'es-MX': 'en la mitad derecha', 'pt-BR': 'na metade direita' },
  'side:left': { role: 'body', band: '13-17', 'en-US': 'on the left half', 'es-MX': 'en la mitad izquierda', 'pt-BR': 'na metade esquerda' },
  'slope:rising': { role: 'body', band: '13-17', 'en-US': 'as the wave rises', 'es-MX': 'mientras la onda sube', 'pt-BR': 'enquanto a onda sobe' },
  'slope:falling': { role: 'body', band: '13-17', 'en-US': 'as the wave falls', 'es-MX': 'mientras la onda baja', 'pt-BR': 'enquanto a onda desce' },
  askSlope: { role: 'body', band: '13-17', 'en-US': 'Find the slope of the curve', 'es-MX': 'Halla la pendiente de la curva', 'pt-BR': 'Ache a inclinação da curva' },
  atX: { role: 'body', band: '13-17', 'en-US': 'at x = {a}', 'es-MX': 'en x = {a}', 'pt-BR': 'em x = {a}' },
  'askLink:max': { role: 'body', band: '13-17', 'en-US': 'Find the x of the peak, given', 'es-MX': 'Halla la x del pico, sabiendo que', 'pt-BR': 'Ache o x do pico, sabendo que' },
  'askLink:min': { role: 'body', band: '13-17', 'en-US': 'Find the x of the trough, given', 'es-MX': 'Halla la x del valle, sabiendo que', 'pt-BR': 'Ache o x do vale, sabendo que' },
  askRiemann: { role: 'body', band: '13-17', 'en-US': 'Raise n until the estimate is within {tol} of', 'es-MX': 'Sube n hasta que la estimación esté a menos de {tol} de', 'pt-BR': 'Aumente n até a estimativa ficar a menos de {tol} de' },
  'method:left': { role: 'body', band: '13-17', 'en-US': 'using left-edge rectangles', 'es-MX': 'con rectángulos del borde izquierdo', 'pt-BR': 'com retângulos da borda esquerda' },
  'method:right': { role: 'body', band: '13-17', 'en-US': 'using right-edge rectangles', 'es-MX': 'con rectángulos del borde derecho', 'pt-BR': 'com retângulos da borda direita' },
  'method:midpoint': { role: 'body', band: '13-17', 'en-US': 'using midpoint rectangles', 'es-MX': 'con rectángulos del punto medio', 'pt-BR': 'com retângulos do ponto médio' },
  'method:trapezoid': { role: 'body', band: '13-17', 'en-US': 'using trapezoids', 'es-MX': 'con trapecios', 'pt-BR': 'com trapézios' },
  askArea: { role: 'body', band: '13-17', 'en-US': 'Find the x where', 'es-MX': 'Halla la x donde', 'pt-BR': 'Ache o x em que' },
  metCircle: { role: 'body', band: '13-17', 'en-US': 'Right. You found the quadrant and the angle.', 'es-MX': 'Bien. Hallaste el cuadrante y el ángulo.', 'pt-BR': 'Certo. Você achou o quadrante e o ângulo.' },
  hintCircle: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check the quadrant, then the angle.', 'es-MX': 'Aún no. Revisa el cuadrante y luego el ángulo.', 'pt-BR': 'Ainda não. Confira o quadrante e depois o ângulo.' },
  metWave: { role: 'body', band: '13-17', 'en-US': 'Right. You counted the hits and found the angle.', 'es-MX': 'Bien. Contaste los cruces y hallaste el ángulo.', 'pt-BR': 'Certo. Você contou os cruzamentos e achou o ângulo.' },
  hintWave: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check the count, then the crossing.', 'es-MX': 'Aún no. Revisa la cuenta y luego el cruce.', 'pt-BR': 'Ainda não. Confira a contagem e depois o cruzamento.' },
  metSecant: { role: 'body', band: '13-17', 'en-US': 'Right. The secant settles on that slope.', 'es-MX': 'Bien. La secante se acerca a esa pendiente.', 'pt-BR': 'Certo. A secante se aproxima dessa inclinação.' },
  hintSecant: { role: 'body', band: '13-17', 'en-US': 'Not yet. Shrink the gap and read the slope again.', 'es-MX': 'Aún no. Reduce la distancia y lee otra vez la pendiente.', 'pt-BR': 'Ainda não. Diminua a distância e leia a inclinação de novo.' },
  metLink: { role: 'body', band: '13-17', 'en-US': 'Right. The slope graph crosses zero there.', 'es-MX': 'Bien. La gráfica de la pendiente cruza el cero ahí.', 'pt-BR': 'Certo. O gráfico da inclinação cruza o zero ali.' },
  hintLink: { role: 'body', band: '13-17', 'en-US': 'Not yet. Look where the slope graph crosses zero.', 'es-MX': 'Aún no. Mira dónde la gráfica de la pendiente cruza el cero.', 'pt-BR': 'Ainda não. Veja onde o gráfico da inclinação cruza o zero.' },
  metRiemann: { role: 'body', band: '13-17', 'en-US': 'Right. That estimate is close enough.', 'es-MX': 'Bien. Esa estimación ya es suficiente.', 'pt-BR': 'Certo. Essa estimativa já é boa o bastante.' },
  hintRiemann: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check the error, then try another n.', 'es-MX': 'Aún no. Revisa el error y prueba otra n.', 'pt-BR': 'Ainda não. Confira o erro e tente outro n.' },
  metArea: { role: 'body', band: '13-17', 'en-US': 'Right. The area so far reaches the target there.', 'es-MX': 'Bien. El área acumulada llega a la meta ahí.', 'pt-BR': 'Certo. A área acumulada chega ao alvo ali.' },
  hintArea: { role: 'body', band: '13-17', 'en-US': 'Not yet. Compare the area so far with the target.', 'es-MX': 'Aún no. Compara el área acumulada con la meta.', 'pt-BR': 'Ainda não. Compare a área acumulada com o alvo.' },

  /* figures, summaries and handles */
  figureCircle: { role: 'heading', band: '13-17', 'en-US': 'The unit circle', 'es-MX': 'El círculo unitario', 'pt-BR': 'O círculo unitário' },
  figureWave: { role: 'heading', band: '13-17', 'en-US': 'The wave it draws', 'es-MX': 'La onda que dibuja', 'pt-BR': 'A onda que ele desenha' },
  figureSecant: { role: 'heading', band: '13-17', 'en-US': 'The curve and its secant', 'es-MX': 'La curva y su secante', 'pt-BR': 'A curva e a sua secante' },
  figureCurve: { role: 'heading', band: '13-17', 'en-US': 'The curve f', 'es-MX': 'La curva f', 'pt-BR': 'A curva f' },
  figureSlope: { role: 'heading', band: '13-17', 'en-US': 'Its slope graph', 'es-MX': 'Su gráfica de pendiente', 'pt-BR': 'O seu gráfico de inclinação' },
  figureRiemann: { role: 'heading', band: '13-17', 'en-US': 'Rectangles under the curve', 'es-MX': 'Rectángulos bajo la curva', 'pt-BR': 'Retângulos sob a curva' },
  figureRate: { role: 'heading', band: '13-17', 'en-US': 'The curve and its area', 'es-MX': 'La curva y su área', 'pt-BR': 'A curva e a sua área' },
  figureTotal: { role: 'heading', band: '13-17', 'en-US': 'The area so far', 'es-MX': 'El área acumulada', 'pt-BR': 'A área acumulada' },
  summaryCircle: { role: 'body', band: '13-17', 'en-US': 'A point rides the circle. Drag it, or use the arrow keys.', 'es-MX': 'Un punto recorre el círculo. Arrástralo o usa las flechas.', 'pt-BR': 'Um ponto percorre o círculo. Arraste-o ou use as setas.' },
  summaryCircleOnly: { role: 'body', band: '13-17', 'en-US': 'The point on the circle marks the same angle as the wave.', 'es-MX': 'El punto del círculo marca el mismo ángulo que la onda.', 'pt-BR': 'O ponto do círculo marca o mesmo ângulo que a onda.' },
  summaryWave: { role: 'body', band: '13-17', 'en-US': 'The wave unrolls the circle. Drag the point along it.', 'es-MX': 'La onda despliega el círculo. Arrastra el punto por ella.', 'pt-BR': 'A onda desenrola o círculo. Arraste o ponto por ela.' },
  summarySecant: { role: 'body', band: '13-17', 'en-US': 'A line through two points. Drag the second one closer.', 'es-MX': 'Una recta por dos puntos. Acerca el segundo punto.', 'pt-BR': 'Uma reta por dois pontos. Aproxime o segundo ponto.' },
  summaryCurve: { role: 'body', band: '13-17', 'en-US': 'The curve f. Drag the mark along x.', 'es-MX': 'La curva f. Arrastra la marca a lo largo de x.', 'pt-BR': 'A curva f. Arraste a marca ao longo de x.' },
  summarySlope: { role: 'body', band: '13-17', 'en-US': 'The slope of f at every x. A dot follows your mark.', 'es-MX': 'La pendiente de f en cada x. Un punto sigue tu marca.', 'pt-BR': 'A inclinação de f em cada x. Um ponto segue a sua marca.' },
  summaryRiemann: { role: 'body', band: '13-17', 'en-US': 'The shaded pieces estimate the area. More pieces fit better.', 'es-MX': 'Las piezas sombreadas estiman el área. Con más piezas, el ajuste mejora.', 'pt-BR': 'As peças sombreadas estimam a área. Com mais peças, o ajuste melhora.' },
  summaryRate: { role: 'body', band: '13-17', 'en-US': 'The curve f, with the area so far shaded.', 'es-MX': 'La curva f, con el área acumulada sombreada.', 'pt-BR': 'A curva f, com a área acumulada sombreada.' },
  summaryTotal: { role: 'body', band: '13-17', 'en-US': 'The area so far, against the target line.', 'es-MX': 'El área acumulada, frente a la línea de la meta.', 'pt-BR': 'A área acumulada, frente à linha do alvo.' },
  handleAngle: { role: 'option', band: '13-17', 'en-US': 'Angle', 'es-MX': 'Ángulo', 'pt-BR': 'Ângulo' },
  handleGap: { role: 'option', band: '13-17', 'en-US': 'Second point', 'es-MX': 'Segundo punto', 'pt-BR': 'Segundo ponto' },
  handleMark: { role: 'option', band: '13-17', 'en-US': 'Mark on x', 'es-MX': 'Marca en x', 'pt-BR': 'Marca em x' },

  /* statuses: the facts of the picture in words, for the text equivalent */
  statusCircle: { role: 'data', band: '13-17', 'en-US': 'Angle {angle}°: cos {cos}, sin {sin}. {where}.', 'es-MX': 'Ángulo {angle}°: cos {cos}, sen {sin}. {where}.', 'pt-BR': 'Ângulo {angle}°: cos {cos}, sen {sin}. {where}.' },
  statusWave: { role: 'data', band: '13-17', 'en-US': 'Angle {angle}°: {fn} is {value}; the wave is {direction}.', 'es-MX': 'Ángulo {angle}°: {fn} vale {value}; la onda {direction}.', 'pt-BR': 'Ângulo {angle}°: {fn} vale {value}; a onda {direction}.' },
  'dir:level': { role: 'data', band: '13-17', 'en-US': 'level', 'es-MX': 'está plana', 'pt-BR': 'está plana' },
  'dir:rising': { role: 'data', band: '13-17', 'en-US': 'rising', 'es-MX': 'sube', 'pt-BR': 'sobe' },
  'dir:falling': { role: 'data', band: '13-17', 'en-US': 'falling', 'es-MX': 'baja', 'pt-BR': 'desce' },
  statusSecant: { role: 'data', band: '13-17', 'en-US': 'On {f}, the secant from x = {a} with gap {gap} has slope {slope}.', 'es-MX': 'En {f}, la secante desde x = {a} con distancia {gap} tiene pendiente {slope}.', 'pt-BR': 'Em {f}, a secante a partir de x = {a} com distância {gap} tem inclinação {slope}.' },
  statusLink: { role: 'data', band: '13-17', 'en-US': '{rule}. At x = {x}: f is {f} and the slope is {slope}.', 'es-MX': '{rule}. En x = {x}: f vale {f} y la pendiente es {slope}.', 'pt-BR': '{rule}. Em x = {x}: f vale {f} e a inclinação é {slope}.' },
  'sign:positive': { role: 'data', band: '13-17', 'en-US': 'positive', 'es-MX': 'positiva', 'pt-BR': 'positiva' },
  'sign:negative': { role: 'data', band: '13-17', 'en-US': 'negative', 'es-MX': 'negativa', 'pt-BR': 'negativa' },
  'sign:zero': { role: 'data', band: '13-17', 'en-US': 'zero', 'es-MX': 'cero', 'pt-BR': 'zero' },
  statusRiemann: { role: 'data', band: '13-17', 'en-US': '{f}. With n = {n}: estimate {estimate}, true area {area}, off by {gap}. {state}', 'es-MX': '{f}. Con n = {n}: estimación {estimate}, área exacta {area}, error de {gap}. {state}', 'pt-BR': '{f}. Com n = {n}: estimativa {estimate}, área exata {area}, erro de {gap}. {state}' },
  within: { role: 'data', band: '13-17', 'en-US': 'Within {tol}.', 'es-MX': 'Dentro de {tol}.', 'pt-BR': 'Dentro de {tol}.' },
  outside: { role: 'data', band: '13-17', 'en-US': 'Not within {tol} yet.', 'es-MX': 'Aún fuera de {tol}.', 'pt-BR': 'Ainda fora de {tol}.' },
  statusArea: { role: 'data', band: '13-17', 'en-US': 'At x = {x}: f is {fx}, so the area is {rate}. Area so far {area} of {target}.', 'es-MX': 'En x = {x}: f vale {fx}, así que el área está {rate}. Área acumulada {area} de {target}.', 'pt-BR': 'Em x = {x}: f vale {fx}, então a área está {rate}. Área acumulada {area} de {target}.' },
  'rate:growing': { role: 'data', band: '13-17', 'en-US': 'growing', 'es-MX': 'creciendo', 'pt-BR': 'crescendo' },
  'rate:shrinking': { role: 'data', band: '13-17', 'en-US': 'shrinking', 'es-MX': 'decreciendo', 'pt-BR': 'diminuindo' },
  'rate:flat': { role: 'data', band: '13-17', 'en-US': 'flat', 'es-MX': 'quieta', 'pt-BR': 'parada' },

  /* tables */
  tableCircle: { role: 'heading', band: '13-17', 'en-US': 'The circle in numbers', 'es-MX': 'El círculo en números', 'pt-BR': 'O círculo em números' },
  tableWave: { role: 'heading', band: '13-17', 'en-US': 'The wave in numbers', 'es-MX': 'La onda en números', 'pt-BR': 'A onda em números' },
  tableSecant: { role: 'heading', band: '13-17', 'en-US': 'Gap and secant slope', 'es-MX': 'Distancia y pendiente de la secante', 'pt-BR': 'Distância e inclinação da secante' },
  tableLink: { role: 'heading', band: '13-17', 'en-US': 'The curve and its slope', 'es-MX': 'La curva y su pendiente', 'pt-BR': 'A curva e a sua inclinação' },
  tableRiemann: { role: 'heading', band: '13-17', 'en-US': 'Estimate and error', 'es-MX': 'Estimación y error', 'pt-BR': 'Estimativa e erro' },
  tableArea: { role: 'heading', band: '13-17', 'en-US': 'The rate and the area', 'es-MX': 'La tasa y el área', 'pt-BR': 'A taxa e a área' },
  colWhat: { role: 'data', band: '13-17', 'en-US': 'Moment', 'es-MX': 'Momento', 'pt-BR': 'Momento' },
  colAngle: { role: 'data', band: '13-17', 'en-US': 'Angle', 'es-MX': 'Ángulo', 'pt-BR': 'Ângulo' },
  colCos: { role: 'data', band: '13-17', 'en-US': 'cos', 'es-MX': 'cos', 'pt-BR': 'cos' },
  colSin: { role: 'data', band: '13-17', 'en-US': 'sin', 'es-MX': 'sen', 'pt-BR': 'sen' },
  colGap: { role: 'data', band: '13-17', 'en-US': 'Gap', 'es-MX': 'Distancia', 'pt-BR': 'Distância' },
  colSlope: { role: 'data', band: '13-17', 'en-US': 'Slope', 'es-MX': 'Pendiente', 'pt-BR': 'Inclinação' },
  colX: { role: 'data', band: '13-17', 'en-US': 'x', 'es-MX': 'x', 'pt-BR': 'x' },
  colF: { role: 'data', band: '13-17', 'en-US': 'f', 'es-MX': 'f', 'pt-BR': 'f' },
  colN: { role: 'data', band: '13-17', 'en-US': 'n', 'es-MX': 'n', 'pt-BR': 'n' },
  colEstimate: { role: 'data', band: '13-17', 'en-US': 'Estimate', 'es-MX': 'Estimación', 'pt-BR': 'Estimativa' },
  colError: { role: 'data', band: '13-17', 'en-US': 'Error', 'es-MX': 'Error', 'pt-BR': 'Erro' },
  colRateF: { role: 'data', band: '13-17', 'en-US': 'f(x)', 'es-MX': 'f(x)', 'pt-BR': 'f(x)' },
  colArea: { role: 'data', band: '13-17', 'en-US': 'Area so far', 'es-MX': 'Área acumulada', 'pt-BR': 'Área acumulada' },
  rowNow: { role: 'data', band: '13-17', 'en-US': 'Now', 'es-MX': 'Ahora', 'pt-BR': 'Agora' },
  rowGoal: { role: 'data', band: '13-17', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  rowExact: { role: 'data', band: '13-17', 'en-US': 'Exact', 'es-MX': 'Exacto', 'pt-BR': 'Exato' },

  /* controls */
  sliderAngle: { role: 'body', band: '13-17', 'en-US': 'Angle', 'es-MX': 'Ángulo', 'pt-BR': 'Ângulo' },
  sliderGap: { role: 'body', band: '13-17', 'en-US': 'Gap between the two points', 'es-MX': 'Distancia entre los dos puntos', 'pt-BR': 'Distância entre os dois pontos' },
  sliderX: { role: 'body', band: '13-17', 'en-US': 'Position on x', 'es-MX': 'Posición en x', 'pt-BR': 'Posição em x' },
  sliderN: { role: 'body', band: '13-17', 'en-US': 'Number of rectangles', 'es-MX': 'Número de rectángulos', 'pt-BR': 'Número de retângulos' },
  labelSlope: { role: 'body', band: '13-17', 'en-US': 'The slope, as a whole number', 'es-MX': 'La pendiente, como número entero', 'pt-BR': 'A inclinação, como número inteiro' },
  less: { role: 'action', band: '13-17', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', band: '13-17', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  smaller: { role: 'action', band: '13-17', 'en-US': 'Smaller', 'es-MX': 'Menor', 'pt-BR': 'Menor' },
  bigger: { role: 'action', band: '13-17', 'en-US': 'Bigger', 'es-MX': 'Mayor', 'pt-BR': 'Maior' },
  left: { role: 'action', band: '13-17', 'en-US': 'Left', 'es-MX': 'Izquierda', 'pt-BR': 'Esquerda' },
  right: { role: 'action', band: '13-17', 'en-US': 'Right', 'es-MX': 'Derecha', 'pt-BR': 'Direita' },

  /* spoken math: what a screen reader says instead of the symbols */
  sayFunction: { role: 'data', band: '13-17', 'en-US': '{name} of x equals', 'es-MX': '{name} de x es igual a', 'pt-BR': '{name} de x é igual a' },
  sayFPrime: { role: 'data', band: '13-17', 'en-US': 'f prime of x equals', 'es-MX': 'f prima de x es igual a', 'pt-BR': 'f linha de x é igual a' },
  sayX: { role: 'data', band: '13-17', 'en-US': 'x', 'es-MX': 'x', 'pt-BR': 'x' },
  sayXSquared: { role: 'data', band: '13-17', 'en-US': 'x squared', 'es-MX': 'x al cuadrado', 'pt-BR': 'x ao quadrado' },
  sayXCubed: { role: 'data', band: '13-17', 'en-US': 'x cubed', 'es-MX': 'x al cubo', 'pt-BR': 'x ao cubo' },
  sayNegative: { role: 'data', band: '13-17', 'en-US': 'negative', 'es-MX': 'menos', 'pt-BR': 'menos' },
  sayMinus: { role: 'data', band: '13-17', 'en-US': 'minus', 'es-MX': 'menos', 'pt-BR': 'menos' },
  sayPlus: { role: 'data', band: '13-17', 'en-US': 'plus', 'es-MX': 'más', 'pt-BR': 'mais' },
  sayTimes: { role: 'data', band: '13-17', 'en-US': 'times', 'es-MX': 'por', 'pt-BR': 'vezes' },
  sayQuantity: { role: 'data', band: '13-17', 'en-US': 'the quantity {value}', 'es-MX': 'la cantidad {value}', 'pt-BR': 'a quantidade {value}' },
  sayTrig: { role: 'data', band: '13-17', 'en-US': '{fn} of theta equals {value}', 'es-MX': '{fn} de theta es igual a {value}', 'pt-BR': '{fn} de teta é igual a {value}' },
  sayCos: { role: 'data', band: '13-17', 'en-US': 'cosine', 'es-MX': 'coseno', 'pt-BR': 'cosseno' },
  saySin: { role: 'data', band: '13-17', 'en-US': 'sine', 'es-MX': 'seno', 'pt-BR': 'seno' },
  'sayLevel:zero': { role: 'data', band: '13-17', 'en-US': 'zero', 'es-MX': 'cero', 'pt-BR': 'zero' },
  'sayLevel:half': { role: 'data', band: '13-17', 'en-US': 'one half', 'es-MX': 'un medio', 'pt-BR': 'um meio' },
  'sayLevel:root2': { role: 'data', band: '13-17', 'en-US': 'root two over two', 'es-MX': 'raíz de dos sobre dos', 'pt-BR': 'raiz de dois sobre dois' },
  'sayLevel:root3': { role: 'data', band: '13-17', 'en-US': 'root three over two', 'es-MX': 'raíz de tres sobre dos', 'pt-BR': 'raiz de três sobre dois' },
  'sayLevel:one': { role: 'data', band: '13-17', 'en-US': 'one', 'es-MX': 'uno', 'pt-BR': 'um' },
  sayAreaSoFar: { role: 'data', band: '13-17', 'en-US': 'the area so far, from {from} up to x, equals {target}', 'es-MX': 'el área acumulada desde {from} hasta x es igual a {target}', 'pt-BR': 'a área acumulada de {from} até x é igual a {target}' },
  sayIntegral: { role: 'data', band: '13-17', 'en-US': 'the integral of f of x, from x equals {from} to x equals {to}', 'es-MX': 'la integral de f de x, desde x igual a {from} hasta x igual a {to}', 'pt-BR': 'a integral de f de x, de x igual a {from} até x igual a {to}' },
} as const satisfies HorizonteCopy;
