import type { HorizonteCopy, HorizonteCopyEntry } from '../boardTypes';
import type { CopyRole } from '../../../design/copyBudget';

/*
 * F1.8 and F1.15 board copy. Every string is written natively per locale (not translated word for word), carries the
 * Copy Budget role of the element that shows it, and is judged at the 10-12 band (13-17 shares its limits). Labels and
 * spoken text for the math live here, keyed by id, because the segment payload is identical in every locale.
 */
const row = (role: CopyRole, en: string, es: string, pt: string): HorizonteCopyEntry => ({ role, band: '10-12', 'en-US': en, 'es-MX': es, 'pt-BR': pt });

export const BALANCE_COPY = {
  /* ---- F1.8 equation balance ---- */
  wordX: row('data', 'x', 'x', 'x'),
  wordPlus: row('data', 'plus', 'más', 'mais'),
  wordEquals: row('data', 'equals', 'es igual a', 'é igual a'),
  opSubX: row('option', 'Take 1 x from both pans', 'Quita 1 x de ambos platos', 'Tire 1 x dos dois pratos'),
  opSubUnit: row('option', 'Take 1 unit from both pans', 'Quita 1 unidad de ambos platos', 'Tire 1 unidade dos dois pratos'),
  opAddUnit: row('option', 'Add 1 unit to both pans', 'Agrega 1 unidad a ambos platos', 'Adicione 1 unidade aos dois pratos'),
  opDiv: row('option', 'Divide both pans by {n}', 'Divide ambos platos entre {n}', 'Divida os dois pratos por {n}'),
  opSlipLeft: row('option', 'Take 1 unit from the left pan only', 'Quita 1 unidad solo del plato izquierdo', 'Tire 1 unidade só do prato esquerdo'),
  opSlipRight: row('option', 'Take 1 unit from the right pan only', 'Quita 1 unidad solo del plato derecho', 'Tire 1 unidade só do prato direito'),
  panLeft: row('data', 'Left pan', 'Plato izquierdo', 'Prato esquerdo'),
  panRight: row('data', 'Right pan', 'Plato derecho', 'Prato direito'),
  scaleLevel: row('data', 'The scale is level.', 'La balanza está nivelada.', 'A balança está nivelada.'),
  scaleRightLow: row('data', 'The right pan is lower.', 'El plato derecho está más abajo.', 'O prato direito está mais baixo.'),
  scaleLeftLow: row('data', 'The left pan is lower.', 'El plato izquierdo está más abajo.', 'O prato esquerdo está mais baixo.'),
  moves: row('data', 'Moves: {n}', 'Movimientos: {n}', 'Movimentos: {n}'),
  movesHeading: row('heading', 'Moves', 'Movimientos', 'Movimentos'),
  greyHint: row('body', 'A greyed move does not fit this scale.', 'Un movimiento gris no cabe en esta balanza.', 'Um movimento cinza não cabe nesta balança.'),
  tipHint: row('body', 'The scale tipped. Undo to level it.', 'La balanza se inclinó. Deshaz para nivelarla.', 'A balança inclinou. Desfaça para nivelá-la.'),
  onScale: row('option', 'On the scale', 'En la balanza', 'Na balança'),
  undo: row('action', 'Undo', 'Deshacer', 'Desfazer'),
  answerLabel: row('body', 'What is x?', '¿Cuánto vale x?', 'Quanto vale x?'),
  typeHint: row('body', 'Type x once it stands alone.', 'Escribe x cuando quede sola.', 'Digite x quando ficar sozinho.'),
  balanceCaption: row('heading', 'What is on each pan', 'Qué hay en cada plato', 'O que há em cada prato'),
  colPan: row('data', 'Pan', 'Plato', 'Prato'),
  colX: row('data', 'x blocks', 'Bloques de x', 'Blocos de x'),
  colUnits: row('data', 'Units', 'Unidades', 'Unidades'),
  metBalance: row('body', 'You kept the scale level and found x.', 'Mantuviste la balanza nivelada y hallaste x.', 'Você manteve a balança nivelada e achou x.'),
  hintBalance: row('body', 'Not yet. Do the same on both pans until x is alone.', 'Aún no. Haz lo mismo en ambos platos hasta dejar la x sola.', 'Ainda não. Faça o mesmo nos dois pratos até deixar o x sozinho.'),

  /* ---- shared by both pieces ---- */
  showTable: row('action', 'Show as table', 'Mostrar como tabla', 'Mostrar como tabela'),
  hideTable: row('action', 'Hide table', 'Ocultar tabla', 'Ocultar tabela'),

  /* ---- F1.15 visual proofs ---- */
  predictHeading: row('heading', 'Predict first', 'Primero predice', 'Primeiro preveja'),
  piecesHeading: row('heading', 'Move the pieces', 'Mueve las piezas', 'Mova as peças'),
  predictHint: row('body', 'Predict first, then move the pieces.', 'Primero predice y luego mueve las piezas.', 'Primeiro preveja e depois mova as peças.'),
  moveHint: row('body', 'Move every piece, then type the answer.', 'Mueve todas las piezas y escribe la respuesta.', 'Mova todas as peças e digite a resposta.'),
  slicesHeading: row('heading', 'How many slices', 'Cuántas rebanadas', 'Quantas fatias'),
  slices: row('option', '{n} slices', '{n} rebanadas', '{n} fatias'),
  groupWedge: row('option', 'Left triangle', 'Triángulo izquierdo', 'Triângulo esquerdo'),
  groupCopy: row('option', 'Copy of the shape', 'Copia de la figura', 'Cópia da figura'),
  groupSlices: row('option', 'All the slices', 'Todas las rebanadas', 'Todas as fatias'),
  groupWheel: row('option', 'The wheel', 'La rueda', 'A roda'),
  groupCorner: row('option', 'Triangle {n}', 'Triángulo {n}', 'Triângulo {n}'),
  groupOdd: row('option', 'Piece of {n}', 'Pieza de {n}', 'Peça de {n}'),
  placedIn: row('option', '{n}: in place', '{n}: en su lugar', '{n}: no lugar'),
  placedAt: row('option', '{n}: at start', '{n}: al inicio', '{n}: no início'),
  moveFit: row('option', 'Where it fits', 'Donde encaja', 'Onde encaixa'),
  moveStart: row('option', 'Back to start', 'De vuelta al inicio', 'De volta ao início'),
  answerArea: row('body', 'Type the area', 'Escribe el área', 'Digite a área'),
  answerAround: row('body', 'Type the distance around', 'Escribe la distancia alrededor', 'Digite a distância ao redor'),
  answerSide: row('body', 'Type the long side', 'Escribe el lado largo', 'Digite o lado maior'),
  answerSum: row('body', 'Type the sum', 'Escribe la suma', 'Digite a soma'),
  figureParallelogram: row('data', 'Parallelogram with a triangle to move', 'Paralelogramo con un triángulo por mover', 'Paralelogramo com um triângulo para mover'),
  figureTriangle: row('data', 'Triangle with a copy to turn', 'Triángulo con una copia por girar', 'Triângulo com uma cópia para girar'),
  figureTrapezoid: row('data', 'Trapezoid with a copy to turn', 'Trapecio con una copia por girar', 'Trapézio com uma cópia para girar'),
  figureCircle: row('data', 'Circle cut into slices', 'Círculo cortado en rebanadas', 'Círculo cortado em fatias'),
  figureCircumference: row('data', 'Wheel on a line', 'Rueda sobre una línea', 'Roda sobre uma linha'),
  figurePythagoras: row('data', 'Square with four triangles', 'Cuadrado con cuatro triángulos', 'Quadrado com quatro triângulos'),
  figureOdd: row('data', 'Square and odd pieces', 'Cuadrado y piezas impares', 'Quadrado e peças ímpares'),
  piecesMoved: row('data', 'Pieces moved: {n}', 'Piezas movidas: {n}', 'Peças movidas: {n}'),
  resultRectangle: row('data', 'Now a rectangle, {a} by {b}.', 'Ahora es un rectángulo de {a} por {b}.', 'Agora é um retângulo de {a} por {b}.'),
  resultTriangle: row('data', 'Two triangles make a parallelogram, base {a}, height {b}.', 'Dos triángulos forman un paralelogramo de base {a} y altura {b}.', 'Dois triângulos formam um paralelogramo de base {a} e altura {b}.'),
  resultTrapezoid: row('data', 'Two trapezoids make a parallelogram, base {a}, height {b}.', 'Dos trapecios forman un paralelogramo de base {a} y altura {b}.', 'Dois trapézios formam um paralelogramo de base {a} e altura {b}.'),
  resultCircle: row('data', 'Almost a rectangle: half the circumference wide, one radius tall.', 'Casi un rectángulo: media circunferencia de ancho y un radio de alto.', 'Quase um retângulo: meia circunferência de largura e um raio de altura.'),
  resultCircumference: row('data', 'One turn lays the circumference on the line: a bit more than 3 diameters.', 'Una vuelta tiende la circunferencia en la línea: poco más de 3 diámetros.', 'Uma volta estende a circunferência na linha: um pouco mais de 3 diâmetros.'),
  resultSquares: row('data', 'Same pieces, now two squares: {a} by {a} and {b} by {b}.', 'Mismas piezas, ahora dos cuadrados: de {a} por {a} y de {b} por {b}.', 'As mesmas peças, agora dois quadrados: de {a} por {a} e de {b} por {b}.'),
  resultSquare: row('data', 'The pieces fill a square, {a} by {a}.', 'Las piezas llenan un cuadrado de {a} por {a}.', 'As peças preenchem um quadrado de {a} por {a}.'),
  proofCaption: row('heading', 'Measures in this figure', 'Medidas de esta figura', 'Medidas desta figura'),
  colMeasure: row('data', 'Measure', 'Medida', 'Medida'),
  colValue: row('data', 'Value', 'Valor', 'Valor'),
  metProof: row('body', 'You predicted right and found the value.', 'Predijiste bien y hallaste el valor.', 'Você previu certo e achou o valor.'),
  hintProof: row('body', 'Not yet. Check your formula and the pieces.', 'Aún no. Revisa tu fórmula y las piezas.', 'Ainda não. Revise sua fórmula e as peças.'),
  'fact:base': row('data', 'Base', 'Base', 'Base'),
  'fact:height': row('data', 'Height', 'Altura', 'Altura'),
  'fact:slant': row('data', 'Shift', 'Desfase', 'Deslocamento'),
  'fact:apex': row('data', 'Top point from left', 'Punta desde la izquierda', 'Ponta a partir da esquerda'),
  'fact:top': row('data', 'Top side', 'Lado de arriba', 'Lado de cima'),
  'fact:bottom': row('data', 'Bottom side', 'Lado de abajo', 'Lado de baixo'),
  'fact:offset': row('data', 'Shift of top side', 'Desfase del lado de arriba', 'Deslocamento do lado de cima'),
  'fact:radius': row('data', 'Radius', 'Radio', 'Raio'),
  'fact:diameter': row('data', 'Diameter', 'Diámetro', 'Diâmetro'),
  'fact:legA': row('data', 'Leg A', 'Cateto A', 'Cateto A'),
  'fact:legB': row('data', 'Leg B', 'Cateto B', 'Cateto B'),
  'fact:slices': row('data', 'Slices', 'Rebanadas', 'Fatias'),
  'fact:odds': row('data', 'Odd numbers added', 'Impares sumados', 'Ímpares somados'),
  'choice:base-height': row('option', 'Base × height', 'Base × altura', 'Base × altura'),
  'choice:half-base-height': row('option', 'Half of base × height', 'La mitad de base × altura', 'Metade de base × altura'),
  'choice:base-plus-height': row('option', 'Base + height', 'Base + altura', 'Base + altura'),
  'choice:half-sum-bases-height': row('option', 'Half the sum of bases × height', 'La mitad de la suma de bases × altura', 'Metade da soma das bases × altura'),
  'choice:sum-bases-height': row('option', 'Sum of bases × height', 'Suma de bases × altura', 'Soma das bases × altura'),
  'choice:pi-r-squared': row('option', 'π × radius × radius', 'π × radio × radio', 'π × raio × raio'),
  'choice:pi-diameter': row('option', 'π × diameter', 'π × diámetro', 'π × diâmetro'),
  'choice:pi-radius': row('option', 'π × radius', 'π × radio', 'π × raio'),
  'choice:radius-squared': row('option', 'Radius × radius', 'Radio × radio', 'Raio × raio'),
  'choice:legs-squares-sum': row('option', 'Leg² + leg² = long side²', 'Cateto² + cateto² = lado largo²', 'Cateto² + cateto² = lado maior²'),
  'choice:legs-sum-squared': row('option', '(Leg + leg)² = long side²', '(Cateto + cateto)² = lado largo²', '(Cateto + cateto)² = lado maior²'),
  'choice:legs-sum': row('option', 'Leg + leg = long side', 'Cateto + cateto = lado largo', 'Cateto + cateto = lado maior'),
  'choice:legs-product': row('option', 'Leg × leg = long side', 'Cateto × cateto = lado largo', 'Cateto × cateto = lado maior'),
  'choice:n-times-n': row('option', 'Count × count', 'Cantidad × cantidad', 'Quantidade × quantidade'),
  'choice:n-plus-n': row('option', 'Count + count', 'Cantidad + cantidad', 'Quantidade + quantidade'),
  'choice:n-times-two': row('option', 'Count × 2', 'Cantidad × 2', 'Quantidade × 2'),
} satisfies HorizonteCopy;
