// Inline game documents for the three mechanics added after the first parity batch
// (launcher, stacker, defender) — the data half of `game-contract.test.ts`.
//
// WHY THEY LIVE HERE AND NOT IN THE TEST FILE. `game-contract.test.ts` already carries
// the sorter and runner documents inline; three more full manifests would bury the
// assertions under a thousand lines of data. Same rule as `learnFixtures.ts`: the
// fixture module holds the values, the test file holds the argument.
//
// WHY THEY ARE TRANSCRIBED AND NOT IMPORTED. `frontend/` is not a dependency of
// `backend/` (CLAUDE.md §1.2: ten independent packages, no workspaces), so importing
// `frontend/src/game-engine/mechanics/*/fixtures.ts` is impossible at build time and
// would misrepresent what Core can actually reach at runtime. The config/content
// VALUES of each mechanic's first published fixture are transcribed instead, and they
// satisfy the PRODUCTION schemas unmodified — §1.14 forbids a relaxed schema for a
// fixture, and `game-contract.test.ts` asserts the parse of each one explicitly.
//
// Curriculum content only: no child, no PII, nothing that identifies anyone (§1.9).

import type { GameDocument } from '../game-contract/core/types.js';

/** Hard tick ceilings, read off each document's own config rather than guessed:
 *  launcher `config.max_ticks`, stacker `config.round.tick_budget`, defender
 *  `config.tick_budget`. `replayGame` refuses any event past them. */
export const LAUNCHER_MAX_TICKS = 1000;
export const STACKER_MAX_TICKS = 1200;
export const DEFENDER_MAX_TICKS = 2200;

export const LAUNCHER_DOCUMENT: GameDocument = {
  schema_version: 1,
  meta: {
    slug: "tiro-al-ahorro",
    title: "Tiro al ahorro",
    locale: "es-MX",
    mechanic: "launcher",
    concept: {
      topic_path: "dinero-basico/ahorro/guardar-para-una-meta",
      recap_md: "Aprendiste que **ahorrar** es guardar una parte de tu dinero para una **meta**, en vez de gastarlo todo el mismo dia. Ahora apunta: manda cada moneda a la alcancia y a tu meta, no al antojo.",
    },
    tier: 1,
    estimated_minutes: 2,
    cast: [
      "dina",
    ],
  },
  skin: {
    palette: "ocean-blue",
    sprites: {},
    sfx: {
      launch: "launch",
      impact: "impact",
      hit: "correct",
      win: "celebration",
    },
  },
  config: {
    world: {
      width: 900,
      height: 540,
      ground_y: 470,
    },
    launcher: {
      x: 60,
      y: 380,
      w: 70,
      h: 70,
      min_angle: 15,
      max_angle: 75,
      angle_step: 5,
      start_angle: 45,
      min_power: 30,
      max_power: 100,
      power_step: 10,
      start_power: 70,
      speed_min: 12,
      speed_max: 30,
      pull_max_units: 220,
      move: {
        axis: "none",
        min: 0,
        max: 0,
        step: 1,
      },
      cooldown_ticks: 8,
    },
    physics: {
      gravity: 1.1,
      wind_x: 0,
      wind_gust: 0,
      wind_period_ticks: 60,
      drag_permille: 0,
      ground_restitution_permille: 0,
      ground_friction_permille: 1000,
      max_flight_ticks: 110,
    },
    projectiles: [
      {
        id: "moneda",
        kind: "standard",
        item_ref: "moneda-10",
        icon: "paid",
        radius: 12,
        gravity_scale_permille: 1000,
        speed_scale_permille: 1000,
        damage: 1,
        bounces: 0,
        restitution_permille: 500,
        friction_permille: 300,
      },
    ],
    aim: {
      trajectory_preview: {
        enabled: true,
        dots: 14,
        tick_step: 3,
      },
    },
    rounds: [
      {
        id: "ronda-alcancia",
        shots: 4,
        max_ticks: 350,
        target_speed_permille: 1000,
        targets: [
          {
            id: "alcancia",
            role: "correct",
            item_ref: "alcancia",
            shape: "box",
            x: 560,
            y: 380,
            w: 90,
            h: 80,
            hp: 1,
            value: 10,
            motion: "static",
            icon: "savings",
          },
          {
            id: "meta",
            role: "correct",
            item_ref: "meta-bici",
            shape: "circle",
            x: 700,
            y: 300,
            w: 80,
            h: 80,
            hp: 1,
            value: 12,
            motion: "static",
            icon: "flag",
          },
          {
            id: "antojo",
            role: "incorrect",
            item_ref: "antojo",
            shape: "box",
            x: 380,
            y: 400,
            w: 70,
            h: 60,
            hp: 1,
            value: 5,
            motion: "static",
            icon: "icecream",
          },
        ],
        obstacles: [],
      },
      {
        id: "ronda-muro",
        shots: 5,
        max_ticks: 400,
        target_speed_permille: 1000,
        targets: [
          {
            id: "alcancia-2",
            role: "correct",
            item_ref: "alcancia",
            shape: "box",
            x: 600,
            y: 390,
            w: 90,
            h: 80,
            hp: 1,
            value: 10,
            motion: "static",
            icon: "savings",
          },
          {
            id: "meta-2",
            role: "correct",
            item_ref: "meta-bici",
            shape: "box",
            x: 740,
            y: 280,
            w: 70,
            h: 70,
            hp: 1,
            value: 12,
            motion: "moving",
            axis: "y",
            amplitude: 40,
            period_ticks: 60,
            icon: "flag",
          },
          {
            id: "antojo-2",
            role: "incorrect",
            item_ref: "antojo",
            shape: "box",
            x: 300,
            y: 400,
            w: 70,
            h: 60,
            hp: 1,
            value: 5,
            motion: "static",
            icon: "icecream",
          },
        ],
        obstacles: [
          {
            id: "muro",
            x: 430,
            y: 300,
            w: 30,
            h: 170,
            material: "deflect",
            restitution_permille: 700,
            friction_permille: 200,
            chain: false,
            icon: "fence",
          },
        ],
      },
    ],
    scoring: {
      accuracy_weight: 1,
      points_weight: 1,
      leftover_weight: 0.6,
      bounce_weight: 0,
      hit_points: 10,
      points_target: 70,
      bounce_target: 3,
      wrong_penalty_pct: 6,
      miss_penalty_pct: 4,
      lives_cost_on_wrong: false,
      combo: {
        step: 2,
        max: 3,
      },
    },
    max_ticks: 1000,
  },
  content: {
    items: [
      {
        id: "moneda-10",
        label_md: "Moneda de 10 pesos",
        icon: "paid",
        value: 10,
        tier: 1,
        category: "ahorro",
      },
      {
        id: "alcancia",
        label_md: "Alcancia",
        icon: "savings",
        value: 0,
        tier: 1,
        category: "ahorro",
      },
      {
        id: "meta-bici",
        label_md: "Meta: la bici",
        icon: "flag",
        value: 900,
        tier: 1,
        category: "ahorro",
      },
      {
        id: "antojo",
        label_md: "Antojo del recreo",
        icon: "icecream",
        value: 15,
        tier: 1,
        category: "gasto",
        misconception_md: "El antojo se acaba en un rato y tu moneda ya no vuelve: si toda la moneda se va ahi, la meta nunca llega.",
      },
    ],
    categories: [
      {
        id: "ahorro",
        label_md: "Ahorro",
        description_md: "Donde tu dinero se queda y crece.",
      },
      {
        id: "gasto",
        label_md: "Gasto rapido",
        description_md: "Lo que se acaba el mismo dia.",
      },
    ],
    feedback: {
      correct_md: [
        "Directo a la alcancia.",
        "Esa moneda ya es tuya.",
        "Tu meta esta mas cerca.",
      ],
      incorrect_md: [
        "Esa moneda se fue en el antojo.",
        "Casi: apunta a tu meta.",
      ],
      results_md: "Cada moneda que apuntaste al ahorro te acerco a tu meta. Asi crece una alcancia.",
    },
    roles: {
      correct: [
        "alcancia",
        "meta-bici",
      ],
      incorrect: [
        "antojo",
      ],
    },
  },
  scoring: {
    mode: "cheer",
    xp_max: 10,
    pass_score: 60,
    lives: null,
    target: 4,
  },
};

export const STACKER_DOCUMENT: GameDocument = {
  schema_version: 1,
  meta: {
    slug: "la-torre-de-mi-ahorro",
    title: "La torre de mi ahorro",
    locale: "es-MX",
    mechanic: "stacker",
    concept: {
      topic_path: "mi-primer-dinero/guardar-con-calma/como-se-arma-un-ahorro",
      recap_md: "Aprendiste que un ahorro se arma por **partes**: primero una meta clara, luego guardar poquito seguido, y anotar lo que gastas para no perderte.",
    },
    tier: 1,
    estimated_minutes: 4,
    cast: [
      "dina",
    ],
  },
  skin: {
    palette: "forest-pear",
    sprites: {},
    sfx: {
      place: "build",
      collapse: "impact",
      hold: "streak",
      win: "celebration",
    },
  },
  config: {
    field: {
      width: 900,
      height: 540,
      ground_y: 440,
      base_x: 450,
      base_width: 320,
      baseline_y: 520,
    },
    gravity: {
      intensity: 1.2,
      direction_degrees: 90,
    },
    catalog: [
      {
        item_id: "meta-clara",
        shape: "box",
        w: 300,
        h: 48,
        mass: 6,
        friction: 0.92,
        restitution: 0.02,
        property: "none",
        property_value: 0,
        cost: 20,
        unlock_after_pieces: 0,
        max_uses: 1,
      },
      {
        item_id: "ahorro-semanal",
        shape: "box",
        w: 240,
        h: 44,
        mass: 4,
        friction: 0.9,
        restitution: 0.02,
        property: "none",
        property_value: 0,
        cost: 16,
        unlock_after_pieces: 0,
        max_uses: 2,
      },
      {
        item_id: "gasto-anotado",
        shape: "box",
        w: 180,
        h: 40,
        mass: 3,
        friction: 0.88,
        restitution: 0.02,
        property: "none",
        property_value: 0,
        cost: 12,
        unlock_after_pieces: 0,
        max_uses: 2,
      },
      {
        item_id: "alcancia",
        shape: "box",
        w: 120,
        h: 38,
        mass: 2,
        friction: 0.86,
        restitution: 0.03,
        property: "none",
        property_value: 0,
        cost: 9,
        unlock_after_pieces: 2,
        max_uses: 2,
      },
      {
        item_id: "compra-impulso",
        shape: "circle",
        w: 80,
        h: 80,
        mass: 1,
        friction: 0.14,
        restitution: 0.5,
        property: "elastic",
        property_value: 0.3,
        cost: 14,
        unlock_after_pieces: 0,
        max_uses: 3,
      },
    ],
    placement: {
      mode: "snap",
      drop_y: 60,
      rotation_steps: 1,
      snap_grid: 30,
      ghost_preview: true,
      max_pieces: 8,
      build_ticks: 240,
    },
    economy: {
      budget: 200,
      use_piece_cost: true,
      cost_per_mass: 0,
      cost_per_area: 0,
      min_cost: 1,
      refund_pct: 60,
      reposition_cost: 0,
      collapse_refund_pct: 60,
    },
    solver: {
      iterations: 12,
      position_correction: 1,
      sleep_speed: 0.4,
      sleep_ticks: 3,
      rest_speed: 2,
      damping: 0.95,
      wind_area_scale: 4000,
      magnet_pull: 0,
    },
    stability: {
      margin_threshold: 2.2,
      margin_cap: 8,
      hold_ticks: 300,
      target_height: 240,
      contact_epsilon: 2,
    },
    collapse: {
      max_tilt_degrees: 22,
      tilt_min_height: 60,
      max_shift: 100,
      brittle_breaks_run: false,
      grace_ticks: 6,
    },
    timeline: {
      announce_ticks: 40,
      gust_variance: 0.15,
      events: [
        {
          id: "viento-suave",
          at_tick: 20,
          kind: "wind",
          magnitude: 0.85,
          duration_ticks: 60,
        },
        {
          id: "lluvia",
          at_tick: 100,
          kind: "rain",
          magnitude: 12,
          duration_ticks: 80,
        },
        {
          id: "viento-fuerte",
          at_tick: 200,
          kind: "wind",
          magnitude: 1.2,
          duration_ticks: 70,
        },
      ],
    },
    assist: {
      enabled: false,
      ease_after_failures: 2,
      ease_factor: 0.8,
      suggest_piece: false,
    },
    style: {
      symmetry_weight: 1,
      cantilever_weight: 0.4,
      cantilever_min_overhang: 30,
      cantilever_target: 2,
      bonus_share: 0.3,
    },
    score_model: "blend",
    score_weights: {
      height: 0.4,
      stability: 0.15,
      hold: 0.15,
      efficiency: 0.15,
      style: 0.15,
    },
    penalty: {
      collapse_pct: 4,
      reposition_pct: 0,
      avoid_piece_pct: 3,
    },
    round: {
      tick_budget: 1200,
    },
  },
  content: {
    categories: [
      {
        id: "plan",
        label_md: "Mi plan",
        description_md: "Piezas que sostienen el ahorro.",
      },
      {
        id: "tentacion",
        label_md: "Tentación",
        description_md: "Piezas que se ven bien y no sostienen.",
      },
    ],
    items: [
      {
        id: "meta-clara",
        label_md: "Meta clara: $20",
        category: "plan",
        value: 20,
        icon: "flag",
        tier: 1,
        image_slot: "piece_1",
        props: {
          ancho: 300,
          peso: 6,
        },
      },
      {
        id: "ahorro-semanal",
        label_md: "Guardar cada semana: $16",
        category: "plan",
        value: 16,
        icon: "savings",
        tier: 1,
        image_slot: "piece_2",
        props: {
          ancho: 240,
          peso: 4,
        },
      },
      {
        id: "gasto-anotado",
        label_md: "Anotar lo que gasto: $12",
        category: "plan",
        value: 12,
        icon: "edit_note",
        tier: 1,
        image_slot: "piece_3",
        props: {
          ancho: 180,
          peso: 3,
        },
      },
      {
        id: "alcancia",
        label_md: "Alcancía cerrada: $9",
        category: "plan",
        value: 9,
        icon: "lock",
        tier: 2,
        image_slot: "piece_4",
        props: {
          ancho: 120,
          peso: 2,
        },
      },
      {
        id: "compra-impulso",
        label_md: "Compra de antojo: $14",
        category: "tentacion",
        value: 14,
        icon: "shopping_bag",
        tier: 2,
        image_slot: "piece_5",
        misconception_md: "Cuesta casi lo mismo que tu meta y no sostiene nada: es redonda, se rueda y tira la torre.",
        props: {
          ancho: 80,
          peso: 1,
        },
      },
    ],
    interludes: [
      {
        id: "pausa-cimiento",
        after_round: 1,
        kind: "pick_one",
        prompt_md: "¿Qué pieza va hasta abajo para que la torre no se caiga?",
        options: [
          {
            id: "a",
            label_md: "La más ancha y pesada",
            correct: true,
            rationale_md: "Una base ancha reparte el peso y aguanta el viento.",
          },
          {
            id: "b",
            label_md: "La más bonita",
            correct: false,
            rationale_md: "Lo bonito no sostiene: lo que sostiene es la base.",
          },
        ],
      },
    ],
    feedback: {
      correct_md: [
        "¡Bien puesta!",
        "Esa pieza sostiene.",
        "¡Tu plan va tomando forma!",
      ],
      incorrect_md: [
        "Casi. Prueba con algo más ancho abajo.",
        "Otra vuelta: ¿esa pieza sostiene o solo se ve bien?",
      ],
      results_md: "Un plan de ahorro se sostiene igual que una torre: base ancha primero, y guardando algo de dinero para lo que no esperabas.",
    },
    roles: {
      foundation: [
        "meta-clara",
        "ahorro-semanal",
      ],
      avoid: [
        "compra-impulso",
      ],
    },
  },
  scoring: {
    mode: "cheer",
    xp_max: 10,
    pass_score: 65,
    lives: null,
    target: 240,
  },
};

export const DEFENDER_DOCUMENT: GameDocument = {
  schema_version: 1,
  meta: {
    slug: "cuida-tu-alcancia",
    title: "Cuida tu alcancía",
    locale: "es-MX",
    mechanic: "defender",
    concept: {
      topic_path: "mi-primer-dinero/cuidar-lo-que-tengo/gastos-hormiga",
      recap_md: "Aprendiste que los **gastos hormiga** son chiquitos pero llegan muchos, y que guardar una parte de tu dinero te deja listo para lo que viene.",
    },
    tier: 1,
    estimated_minutes: 3,
    cast: [
      "dina",
    ],
  },
  skin: {
    palette: "forest-pear",
    sprites: {},
    sfx: {
      build: "drop",
      kill: "match",
      leak: "tryagain",
      wave: "streak",
      win: "celebration",
    },
  },
  config: {
    grid: {
      cell_size: 56,
      map: [
        "#############",
        "#.#.#.#.#.#.#",
        "#.#.#.#.#.#.#",
        "S===========X",
        "#.#.#.#.#.#.#",
        "#.#.#.#.#.#.#",
        "#############",
      ],
    },
    step_costs: {
      open: 3,
      road: 1,
    },
    build: {
      wall_cost: 12,
      wall_hp: 80,
      max_walls: 4,
      sell_refund_pct: 60,
      towers_block_path: false,
    },
    economy: {
      starting_gold: 70,
      wave_clear_bonus: 30,
      interest_pct: 10,
      interest_cap: 40,
      early_call_bonus_gold: 6,
      hp_growth_pct_per_wave: 125,
      gold_growth_pct_per_wave: 110,
    },
    damage_matrix: [
      {
        damage: "impact",
        armor: "light",
        multiplier_pct: 50,
      },
    ],
    default_multiplier_pct: 100,
    slow: {
      diminishing_pct: 50,
      max_slow_pct: 70,
    },
    enemies: [
      {
        id: "gasto-hormiga",
        item_id: "gasto-hormiga",
        hp: 26,
        armor: "unarmored",
        speed_mcells: 90,
        bounty: 7,
        lives_cost: 1,
        sprite_slot: "enemy_1",
      },
      {
        id: "antojo-grande",
        item_id: "antojo-grande",
        hp: 45,
        armor: "light",
        speed_mcells: 65,
        bounty: 12,
        lives_cost: 1,
        sprite_slot: "enemy_2",
      },
    ],
    towers: [
      {
        id: "torre-ahorro",
        item_id: "torre-ahorro",
        archetype: "single",
        cost: 25,
        range_mcells: 1800,
        fire_interval_ticks: 8,
        damage: 12,
        damage_type: "impact",
        targets_air: false,
        targets_ground: true,
        blocks_path: false,
        default_priority: "first",
        sprite_slot: "tower_single",
      },
      {
        id: "alcancia",
        item_id: "alcancia",
        archetype: "economy",
        cost: 30,
        range_mcells: 0,
        fire_interval_ticks: 1,
        damage: 0,
        damage_type: "impact",
        targets_air: false,
        targets_ground: false,
        income_per_wave: 20,
        blocks_path: false,
        default_priority: "first",
        sprite_slot: "tower_economy",
      },
      {
        id: "torre-brillante",
        item_id: "torre-brillante",
        archetype: "single",
        cost: 85,
        range_mcells: 1900,
        fire_interval_ticks: 22,
        damage: 14,
        damage_type: "impact",
        targets_air: false,
        targets_ground: true,
        blocks_path: false,
        default_priority: "first",
        sprite_slot: "tower_single",
      },
    ],
    waves: [
      {
        id: "primera-tanda",
        groups: [
          {
            enemy: "gasto-hormiga",
            count: 6,
            interval_ticks: 26,
            start_tick: 0,
            entry: 0,
          },
        ],
        bonus_gold: 20,
      },
      {
        id: "segunda-tanda",
        groups: [
          {
            enemy: "gasto-hormiga",
            count: 8,
            interval_ticks: 22,
            start_tick: 0,
            entry: 0,
          },
          {
            enemy: "antojo-grande",
            count: 3,
            interval_ticks: 34,
            start_tick: 60,
            entry: 0,
          },
        ],
        bonus_gold: 30,
      },
      {
        id: "tanda-final",
        groups: [
          {
            enemy: "gasto-hormiga",
            count: 10,
            interval_ticks: 18,
            start_tick: 0,
            entry: 0,
          },
          {
            enemy: "antojo-grande",
            count: 5,
            interval_ticks: 26,
            start_tick: 40,
            entry: 0,
          },
        ],
        bonus_gold: 40,
      },
    ],
    prep_ticks: 50,
    efficiency: {
      wall_budget: 4,
      gold_surplus_target: 120,
    },
    score_weights: {
      defense: 0.5,
      leak_free: 0.2,
      economy: 0.2,
      walls: 0.1,
    },
    leak_penalty_pct: 2,
    tick_budget: 2200,
  },
  content: {
    items: [
      {
        id: "gasto-hormiga",
        label_md: "Gasto hormiga",
        icon: "pest_control",
        tier: 1,
        image_slot: "enemy_1",
        props: {
          costo: 7,
        },
      },
      {
        id: "antojo-grande",
        label_md: "Antojo grande",
        icon: "icecream",
        tier: 2,
        image_slot: "enemy_2",
        props: {
          costo: 12,
        },
      },
      {
        id: "torre-ahorro",
        label_md: "Torre Ahorro",
        icon: "savings",
        tier: 1,
        image_slot: "tower_single",
        props: {
          precio: 25,
        },
      },
      {
        id: "alcancia",
        label_md: "Alcancía que rinde",
        icon: "account_balance",
        tier: 2,
        image_slot: "tower_economy",
        props: {
          precio: 30,
        },
      },
      {
        id: "torre-brillante",
        label_md: "Torre Brillante",
        icon: "auto_awesome",
        tier: 3,
        image_slot: "tower_single",
        props: {
          precio: 85,
          trap: 1,
        },
        misconception_md: "Cuesta más del triple y dispara mucho más lento: se ve increíble, pero con ese dinero compras tres Torres Ahorro.",
      },
    ],
    interludes: [
      {
        id: "pausa-ahorro",
        after_round: 1,
        kind: "pick_one",
        prompt_md: "Te quedan monedas después de la primera tanda. ¿Qué te conviene más?",
        options: [
          {
            id: "a",
            label_md: "Gastarlas todas ya mismo",
            correct: false,
            rationale_md: "Si gastas todo, no te queda nada para la tanda que viene, que es más grande.",
          },
          {
            id: "b",
            label_md: "Guardar una parte para la siguiente tanda",
            correct: true,
            rationale_md: "Lo que guardas te da un poquito más al cerrar la tanda: ahorrar rinde.",
          },
        ],
      },
    ],
    feedback: {
      correct_md: [
        "¡Bien colocada!",
        "Ese lugar sí cubre el camino.",
        "¡Tu alcancía está segura!",
      ],
      incorrect_md: [
        "Casi. Prueba una torre más cerca del camino.",
        "Otra vuelta: ¿esa torre alcanza a los gastos?",
      ],
      results_md: "Guardar una parte de tus monedas te dejó más torres al final que gastarlas todas de golpe.",
    },
  },
  scoring: {
    mode: "cheer",
    xp_max: 10,
    pass_score: 60,
    lives: null,
    target: 32,
  },
};
