/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/stats1/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const STATS1_SEGMENTS = [] as const;
export const STATS1_RUBRICS = {} as const;
export const STATS1_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
