import type { HorizonteCopy } from '../boardTypes';

export const STATS1_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  less: { role: 'action', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  colValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  colChance: { role: 'data', 'en-US': 'Chance', 'es-MX': 'Probabilidad', 'pt-BR': 'Chance' },
  mean: { role: 'data', 'en-US': 'Mean', 'es-MX': 'Media', 'pt-BR': 'Média' },

  dotPlotName: { role: 'data', 'en-US': 'Dot plot', 'es-MX': 'Diagrama de puntos', 'pt-BR': 'Gráfico de pontos' },
  takeDot: { role: 'option', 'en-US': 'From {n}', 'es-MX': 'Del {n}', 'pt-BR': 'Do {n}' },
  takeDotName: { role: 'option', 'en-US': 'Take a dot from {n}', 'es-MX': 'Toma un punto del {n}', 'pt-BR': 'Pegue um ponto do {n}' },
  valueAt: { role: 'option', 'en-US': 'Value {n}', 'es-MX': 'Valor {n}', 'pt-BR': 'Valor {n}' },
  moveHeading: { role: 'heading', 'en-US': 'Move the dots', 'es-MX': 'Mueve los puntos', 'pt-BR': 'Mova os pontos' },
  median: { role: 'data', 'en-US': 'Median', 'es-MX': 'Mediana', 'pt-BR': 'Mediana' },
  mode: { role: 'data', 'en-US': 'Mode', 'es-MX': 'Moda', 'pt-BR': 'Moda' },
  none: { role: 'data', 'en-US': 'none', 'es-MX': 'ninguna', 'pt-BR': 'nenhuma' },
  movesUsed: { role: 'data', 'en-US': 'Moves used: {n} of {m}', 'es-MX': 'Movimientos usados: {n} de {m}', 'pt-BR': 'Movimentos usados: {n} de {m}' },
  tableCaptionDots: { role: 'heading', 'en-US': 'Dots at each value', 'es-MX': 'Puntos en cada valor', 'pt-BR': 'Pontos em cada valor' },
  colDots: { role: 'data', 'en-US': 'Dots', 'es-MX': 'Puntos', 'pt-BR': 'Pontos' },
  metDots: { role: 'body', 'en-US': 'You moved the dots and hit the goal.', 'es-MX': 'Moviste los puntos y lograste la meta.', 'pt-BR': 'Você moveu os pontos e atingiu a meta.' },
  hintDots: { role: 'body', 'en-US': 'Not yet. Watch the marker as you move dots.', 'es-MX': 'Aún no. Mira la marca al mover los puntos.', 'pt-BR': 'Ainda não. Observe a marca ao mover os pontos.' },

  pivotLabel: { role: 'body', 'en-US': 'Pivot position', 'es-MX': 'Posición del pivote', 'pt-BR': 'Posição do pivô' },
  balanceName: { role: 'data', 'en-US': 'Beam with dots', 'es-MX': 'Barra con puntos', 'pt-BR': 'Barra com pontos' },
  leftPull: { role: 'data', 'en-US': 'Pull on the left', 'es-MX': 'Peso a la izquierda', 'pt-BR': 'Peso à esquerda' },
  rightPull: { role: 'data', 'en-US': 'Pull on the right', 'es-MX': 'Peso a la derecha', 'pt-BR': 'Peso à direita' },
  tipsLeft: { role: 'data', 'en-US': 'Tips left', 'es-MX': 'Cae a la izquierda', 'pt-BR': 'Cai para a esquerda' },
  tipsRight: { role: 'data', 'en-US': 'Tips right', 'es-MX': 'Cae a la derecha', 'pt-BR': 'Cai para a direita' },
  level: { role: 'data', 'en-US': 'Level', 'es-MX': 'Nivelada', 'pt-BR': 'Nivelada' },
  tableCaptionBalance: { role: 'heading', 'en-US': 'Distance from the pivot', 'es-MX': 'Distancia al pivote', 'pt-BR': 'Distância do pivô' },
  colDotAt: { role: 'data', 'en-US': 'Dot at', 'es-MX': 'Punto en', 'pt-BR': 'Ponto em' },
  colDistance: { role: 'data', 'en-US': 'Distance', 'es-MX': 'Distancia', 'pt-BR': 'Distância' },
  net: { role: 'data', 'en-US': 'Net', 'es-MX': 'Neto', 'pt-BR': 'Líquido' },
  metBalance: { role: 'body', 'en-US': 'You found the balance point.', 'es-MX': 'Encontraste el punto de equilibrio.', 'pt-BR': 'Você achou o ponto de equilíbrio.' },
  hintBalance: { role: 'body', 'en-US': 'Not yet. Make both sides pull the same.', 'es-MX': 'Aún no. Haz que ambos lados pesen igual.', 'pt-BR': 'Ainda não. Faça os dois lados pesarem igual.' },

  sdLabel: { role: 'body', 'en-US': 'Standard deviation', 'es-MX': 'Desviación estándar', 'pt-BR': 'Desvio padrão' },
  curveName: { role: 'data', 'en-US': 'Normal curve', 'es-MX': 'Curva normal', 'pt-BR': 'Curva normal' },
  inside: { role: 'data', 'en-US': 'Inside the band', 'es-MX': 'Dentro de la banda', 'pt-BR': 'Dentro da faixa' },
  lowerEdge: { role: 'data', 'en-US': 'Lower edge', 'es-MX': 'Borde inferior', 'pt-BR': 'Borda inferior' },
  upperEdge: { role: 'data', 'en-US': 'Upper edge', 'es-MX': 'Borde superior', 'pt-BR': 'Borda superior' },
  tableCaptionCurve: { role: 'heading', 'en-US': 'Curve and band', 'es-MX': 'Curva y banda', 'pt-BR': 'Curva e faixa' },
  colMeasure: { role: 'data', 'en-US': 'Measure', 'es-MX': 'Medida', 'pt-BR': 'Medida' },
  metNormal: { role: 'body', 'en-US': 'Both edges now match the band.', 'es-MX': 'Ahora los dos bordes coinciden con la banda.', 'pt-BR': 'Agora as duas bordas combinam com a faixa.' },
  hintNormal: { role: 'body', 'en-US': 'Not yet. Line the edges up with the band.', 'es-MX': 'Aún no. Alinea los bordes con la banda.', 'pt-BR': 'Ainda não. Alinhe as bordas com a faixa.' },

  nLabel: { role: 'body', 'en-US': 'Number of trials', 'es-MX': 'Número de ensayos', 'pt-BR': 'Número de tentativas' },
  pctLabel: { role: 'body', 'en-US': 'Chance of success', 'es-MX': 'Probabilidad de éxito', 'pt-BR': 'Chance de sucesso' },
  barsName: { role: 'data', 'en-US': 'Binomial bars', 'es-MX': 'Barras binomiales', 'pt-BR': 'Barras binomiais' },
  variance: { role: 'data', 'en-US': 'Variance', 'es-MX': 'Varianza', 'pt-BR': 'Variância' },
  tableCaptionBinomial: { role: 'heading', 'en-US': 'Chance of each count', 'es-MX': 'Probabilidad de cada cantidad', 'pt-BR': 'Chance de cada contagem' },
  colSuccesses: { role: 'data', 'en-US': 'Successes', 'es-MX': 'Éxitos', 'pt-BR': 'Sucessos' },
  metBinomial: { role: 'body', 'en-US': 'The mean and variance match the goal.', 'es-MX': 'La media y la varianza coinciden con la meta.', 'pt-BR': 'A média e a variância batem com a meta.' },
  hintBinomial: { role: 'body', 'en-US': 'Not yet. Fix the mean first, then the variance.', 'es-MX': 'Aún no. Ajusta primero la media y luego la varianza.', 'pt-BR': 'Ainda não. Ajuste primeiro a média e depois a variância.' },

  sampleLabel: { role: 'body', 'en-US': 'Sample size', 'es-MX': 'Tamaño de muestra', 'pt-BR': 'Tamanho da amostra' },
  oneDraw: { role: 'data', 'en-US': 'One draw', 'es-MX': 'Una extracción', 'pt-BR': 'Uma extração' },
  meanOfDraws: { role: 'data', 'en-US': 'Mean of the draws', 'es-MX': 'Media de las extracciones', 'pt-BR': 'Média das extrações' },
  spread: { role: 'data', 'en-US': 'Spread', 'es-MX': 'Dispersión', 'pt-BR': 'Dispersão' },
  spreadOne: { role: 'data', 'en-US': 'Spread of one draw', 'es-MX': 'Dispersión de una extracción', 'pt-BR': 'Dispersão de uma extração' },
  spreadMean: { role: 'data', 'en-US': 'Spread of the mean', 'es-MX': 'Dispersión de la media', 'pt-BR': 'Dispersão da média' },
  timesSmaller: { role: 'data', 'en-US': 'Times smaller', 'es-MX': 'Veces menor', 'pt-BR': 'Vezes menor' },
  goalShrink: { role: 'data', 'en-US': 'Goal: {n} times smaller', 'es-MX': 'Meta: {n} veces menor', 'pt-BR': 'Meta: {n} vezes menor' },
  tableCaptionClt: { role: 'heading', 'en-US': 'One draw and the mean', 'es-MX': 'Una extracción y la media', 'pt-BR': 'Uma extração e a média' },
  metClt: { role: 'body', 'en-US': 'The spread of the mean hit the goal.', 'es-MX': 'La dispersión de la media llegó a la meta.', 'pt-BR': 'A dispersão da média chegou à meta.' },
  hintClt: { role: 'body', 'en-US': 'Not yet. Try a different sample size.', 'es-MX': 'Aún no. Prueba otro tamaño de muestra.', 'pt-BR': 'Ainda não. Tente outro tamanho de amostra.' },
} as const satisfies HorizonteCopy;
