/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/stats1/scorer.ts. Do not edit: change the source and regenerate. */
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import {
  isBinomialAnswer, isCltAnswer, isCurveAxis, isNormalAnswer, isWeights, solveBinomial, solveClt, solveNormal,
  type BinomialAnswer, type BinomialGoal, type CltAnswer, type CltGoal, type NormalAnswer, type NormalBand,
} from './distributions.generated';
import {
  DOT_MEASURES, DOT_MOVES_MAX, balancePoint, dotMeasureMet, dotTargetReachable, hasOnly, inRange, isAxis, isDots, respectsDotRule, sameDots, whole,
  type Axis, type DotMeasure,
} from './model.generated';

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };
const REVIEW: V2Grade = { verdict: 'review', diagnostic: 'value' };

/** The ladder every Stats pack scorer shares: untouched is valid, the key is met, anything else well-formed is review. */
const ladder = (touched: boolean, met: boolean): V2Grade => (!touched ? VALID : met ? MET : REVIEW);

const rubricTarget = (rubric: unknown): unknown => (hasOnly(rubric, ['target']) ? rubric.target : undefined);

type DotPlotSegment = { payload: { axis: Axis; dots: number[]; measure: DotMeasure; moves: number } };

/**
 * invalid: malformed, a dot off the axis, a changed number of dots, more dots moved than allowed, or (with a rubric) a key
 * that no allowed move can reach. valid: the plot untouched, and every well-formed response without a rubric. review:
 * moved, but the measure is not on the target. met: the measure is on the target.
 */
function gradeDotPlot(segment: DotPlotSegment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!payload || !isAxis(payload.axis) || !isDots(payload.dots, payload.axis) || !DOT_MEASURES.includes(payload.measure) || !inRange(payload.moves, 1, DOT_MOVES_MAX)) return INVALID;
  if (!hasOnly(response, ['dots']) || !respectsDotRule(payload.dots, response.dots, payload.axis, payload.moves)) return INVALID;
  if (rubric === undefined) return VALID;
  const target = rubricTarget(rubric);
  if (!whole(target) || !dotTargetReachable(payload.dots, payload.axis, payload.measure, payload.moves, target)) return INVALID;
  return ladder(!sameDots(response.dots, payload.dots), dotMeasureMet(payload.measure, response.dots, target));
}

type BalanceSegment = { payload: { axis: Axis; dots: number[]; pivot: number } };

/** invalid: malformed, a pivot off the beam, or a key that is not the mean of the dots. valid: the pivot untouched. met: the pivot at the mean. */
function gradeBalance(segment: BalanceSegment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!payload || !isAxis(payload.axis) || !isDots(payload.dots, payload.axis) || !inRange(payload.pivot, payload.axis.min, payload.axis.max)) return INVALID;
  if (!hasOnly(response, ['pivot']) || !inRange(response.pivot, payload.axis.min, payload.axis.max)) return INVALID;
  if (rubric === undefined) return VALID;
  const target = rubricTarget(rubric);
  const point = balancePoint(payload.dots);
  if (!whole(target) || point === null || target !== point || target === payload.pivot) return INVALID;
  return ladder(response.pivot !== payload.pivot, response.pivot === target);
}

type NormalSegment = { payload: { axis: Axis; start: NormalAnswer; sdMax: number; band: NormalBand } };

/** invalid: malformed, a mean off the axis, a spread out of range, or a key that is not the curve the band asks for. met: that mean and spread. */
function gradeNormal(segment: NormalSegment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!payload || !isCurveAxis(payload.axis) || !inRange(payload.sdMax, 1, 30) || !isNormalAnswer(payload.start, payload.axis, payload.sdMax)) return INVALID;
  if (!isNormalAnswer(response, payload.axis, payload.sdMax)) return INVALID;
  if (rubric === undefined) return VALID;
  const answer = solveNormal(payload.axis, payload.band, payload.sdMax);
  const target = rubricTarget(rubric);
  if (!answer || !isNormalAnswer(target, payload.axis, payload.sdMax) || target.mean !== answer.mean || target.sd !== answer.sd) return INVALID;
  if (answer.mean === payload.start.mean && answer.sd === payload.start.sd) return INVALID;
  return ladder(response.mean !== payload.start.mean || response.sd !== payload.start.sd, response.mean === target.mean && response.sd === target.sd);
}

type BinomialSegment = { payload: { nMax: number; start: BinomialAnswer; goal: BinomialGoal } };

/** invalid: malformed, a count past the maximum, a percent off the 5 step grid, or a key that is not the pair for the mean and variance. */
function gradeBinomial(segment: BinomialSegment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!payload || !inRange(payload.nMax, 1, 40) || !isBinomialAnswer(payload.start, payload.nMax)) return INVALID;
  if (!isBinomialAnswer(response, payload.nMax)) return INVALID;
  if (rubric === undefined) return VALID;
  const answer = solveBinomial(payload.goal, payload.nMax);
  const target = rubricTarget(rubric);
  if (!answer || !isBinomialAnswer(target, payload.nMax) || target.n !== answer.n || target.pct !== answer.pct) return INVALID;
  if (answer.n === payload.start.n && answer.pct === payload.start.pct) return INVALID;
  return ladder(response.n !== payload.start.n || response.pct !== payload.start.pct, response.n === target.n && response.pct === target.pct);
}

type CltSegment = { payload: { weights: number[]; nMax: number; start: CltAnswer; goal: CltGoal } };

/** invalid: malformed, a sample size past the maximum, or a key that is not the shrink factor squared. met: that sample size. */
function gradeClt(segment: CltSegment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!payload || !isWeights(payload.weights) || !inRange(payload.nMax, 1, 25) || !isCltAnswer(payload.start, payload.nMax)) return INVALID;
  if (!isCltAnswer(response, payload.nMax)) return INVALID;
  if (rubric === undefined) return VALID;
  const answer = solveClt(payload.goal, payload.nMax);
  const target = rubricTarget(rubric);
  if (!answer || !isCltAnswer(target, payload.nMax) || target.n !== answer.n || answer.n === payload.start.n) return INVALID;
  return ladder(response.n !== payload.start.n, response.n === target.n);
}

const scorer = <S>(grade: (segment: S, response: unknown, rubric: unknown) => V2Grade, sample: (segment: S) => unknown): HorizonteScorer => ({
  grade: grade as unknown as HorizonteScorer['grade'],
  sample: sample as unknown as HorizonteScorer['sample'],
});

export const STATS1_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'stats.dot-plot.v2': scorer(gradeDotPlot, (segment: DotPlotSegment) => ({ dots: [...segment.payload.dots] })),
  'stats.balance-point.v2': scorer(gradeBalance, (segment: BalanceSegment) => ({ pivot: segment.payload.pivot })),
  'stats.normal.v2': scorer(gradeNormal, (segment: NormalSegment) => ({ mean: segment.payload.start.mean, sd: segment.payload.start.sd })),
  'stats.binomial.v2': scorer(gradeBinomial, (segment: BinomialSegment) => ({ n: segment.payload.start.n, pct: segment.payload.start.pct })),
  'stats.clt.v2': scorer(gradeClt, (segment: CltSegment) => ({ n: segment.payload.start.n })),
};
