/**
 * Shape of one admin-1 region (state, province, department) as generated by
 * scripts/generate-region-maps.mjs. Kept in a hand-written module so the
 * generated per-country files stay pure data.
 */
export interface RegionShape {
  /** ISO 3166-2, e.g. `MX-JAL` — what Plausible's visit:region reports. */
  code: string;
  name: string;
  /** SVG path in the SAME 1000x500 projected space as the world map. */
  d: string;
  centroid: [number, number] | null;
}
