// `autobattler` fixtures — two complete, PLAYABLE es-MX manifests (GAME_ENGINE.md §7).
//
// They are not demo scaffolding. They are the reference answer to "what does a
// well-tuned auto-battler document look like", they are what `/dev/game-lab` loads, and
// `autobattler.test.ts` asserts that the PERFECT bot reaches `pass_score` on each one
// while the RANDOM bot does not — the same §9 winnability gate the Arcade pipeline runs
// before a generated document may be published.
//
// Deliberately different: a tier-2 CHEER manifest (5 rounds, one trait tier, no crits,
// no fail state) and a tier-3 ARCADE manifest (7 rounds, three stars, crits, a stricter
// adjacency rule, three lives).
//
// THE CONCEPT IN BOTH IS THE SHOP ECONOMY: income, saving, interest with a CAP, and the
// decision to spend now or bank for a stronger round later. `score_weights.interest`
// makes that decision worth score, `content.tips.interest_md` makes the rule visible on
// screen, and the perfect bot beats them by banking to the cap and spending the surplus.
//
// Content is curriculum, never a child: no names, no locations, no PII (§1.9).
// `skin.sprites` is empty on purpose — Prism fills it at illustrate time, and both views
// must be fully legible before it does.

import type { GameDocument } from '@/game-engine/core/types'

import type { AutobattlerConfig, AutobattlerContent } from './schema'

// ---- 1. El equipo del ahorro (tier 2, cheer) ---------------------------------------

const savingsConfig: AutobattlerConfig = {
  board: { cols: 3, rows: 2, cell_size: 84, team_size: 4, bench_size: 4 },
  shop: {
    offers: 3,
    refresh_cost: 2,
    rarity_by_level: [
      [80, 20, 0, 0],
      [55, 35, 10, 0],
      [35, 40, 20, 5],
    ],
    level: {
      max: 3,
      xp_cost: 4,
      xp_per_purchase: 4,
      xp_per_buy: 1,
      xp_needed: [4, 6, 99],
      units_by_level: [3, 4, 4],
    },
  },
  merge: { copies_needed: 3, max_star: 2, star_multipliers: [1, 1.8] },
  economy: {
    start_gold: 10,
    base_income: 4,
    income_growth_per_round: 1,
    income_cap: 8,
    // "Cada 5 monedas guardadas pagan 1, hasta 3." Small, legible numbers a 9-year-old
    // can compute in their head — the cap is what makes the decision interesting.
    interest: { gold_per_step: 5, amount_per_step: 1, max_steps: 3 },
    streak: { win_bonus: [1, 2, 3], loss_bonus: [0, 1, 2] },
    sell_refund_pct: 100,
  },
  combat: {
    // 0.5s per combat tick / 50ms per engine tick = exactly 10.
    engine_ticks_per_combat_tick: 10,
    max_combat_ticks: 60,
    timeout_result: 'most_units',
    targeting: 'closest',
    min_damage: 1,
    crit_chance_pct: 0,
    crit_multiplier_pct: 150,
    adjacency: {
      enabled: true,
      per_neighbour_damage_pct: 5,
      per_neighbour_armour: 1,
      same_trait_only: false,
    },
  },
  health: { start: 20, base_damage: 2, per_round: 1, per_survivor: 1 },
  prep: { max_ticks: 240, auto_merge: true },
  units: [
    {
      id: 'ahorrador',
      item_id: 'ahorrador',
      rarity: 1,
      cost: 1,
      traits: ['ahorro'],
      stats: {
        hp: 220,
        damage: 30,
        armour: 5,
        attack_interval: 2,
        range: 1200,
        move_speed: 500,
        mana_max: 40,
        mana_per_attack: 12,
        mana_on_damaged: 4,
      },
      ability: { kind: 'shield', power: 30, radius: 0 },
      sprite_slot: 'unit_1',
    },
    {
      id: 'alcancia',
      item_id: 'alcancia',
      rarity: 1,
      cost: 1,
      traits: ['ahorro', 'escudo'],
      stats: {
        hp: 300,
        damage: 20,
        armour: 10,
        attack_interval: 3,
        range: 1100,
        move_speed: 400,
        mana_max: 50,
        mana_per_attack: 12,
        mana_on_damaged: 6,
      },
      ability: { kind: 'heal', power: 45, radius: 0 },
      sprite_slot: 'unit_2',
    },
    {
      id: 'interes',
      item_id: 'interes',
      rarity: 2,
      cost: 2,
      traits: ['ahorro', 'interes'],
      stats: {
        hp: 190,
        damage: 42,
        armour: 3,
        attack_interval: 2,
        range: 3000,
        move_speed: 450,
        mana_max: 30,
        mana_per_attack: 14,
        mana_on_damaged: 4,
      },
      ability: { kind: 'burst', power: 120, radius: 0 },
      targeting: 'lowest_health',
      sprite_slot: 'unit_3',
    },
    {
      id: 'gasto-hormiga',
      item_id: 'gasto-hormiga',
      rarity: 2,
      cost: 2,
      traits: ['gasto'],
      stats: {
        hp: 200,
        damage: 38,
        armour: 4,
        attack_interval: 2,
        range: 1200,
        move_speed: 550,
        mana_max: 40,
        mana_per_attack: 14,
        mana_on_damaged: 5,
      },
      ability: { kind: 'empower', power: 40, radius: 0 },
      sprite_slot: 'unit_4',
    },
    {
      id: 'presupuesto',
      item_id: 'presupuesto',
      rarity: 3,
      cost: 3,
      traits: ['interes', 'escudo'],
      stats: {
        hp: 280,
        damage: 45,
        armour: 8,
        attack_interval: 2,
        range: 2200,
        move_speed: 500,
        mana_max: 50,
        mana_per_attack: 16,
        mana_on_damaged: 6,
      },
      ability: { kind: 'splash', power: 100, radius: 1600 },
      sprite_slot: 'unit_5',
    },
  ],
  traits: [
    {
      id: 'ahorro',
      item_id: 'trait-ahorro',
      scope: 'team',
      thresholds: [
        { count: 2, damage_pct: 0, hp_pct: 15, armour: 3, attack_speed_pct: 0 },
        { count: 3, damage_pct: 0, hp_pct: 15, armour: 4, attack_speed_pct: 0 },
      ],
    },
    {
      id: 'interes',
      item_id: 'trait-interes',
      scope: 'trait',
      thresholds: [
        { count: 1, damage_pct: 15, hp_pct: 0, armour: 0, attack_speed_pct: 0 },
        { count: 2, damage_pct: 20, hp_pct: 0, armour: 0, attack_speed_pct: 10 },
      ],
    },
    {
      id: 'escudo',
      item_id: 'trait-escudo',
      scope: 'trait',
      thresholds: [{ count: 2, damage_pct: 0, hp_pct: 10, armour: 8, attack_speed_pct: 0 }],
    },
    {
      id: 'gasto',
      item_id: 'trait-gasto',
      scope: 'trait',
      thresholds: [{ count: 1, damage_pct: 25, hp_pct: 0, armour: 0, attack_speed_pct: 0 }],
    },
  ],
  items: [
    {
      id: 'moneda-extra',
      item_id: 'moneda-extra',
      damage: 6,
      hp: 0,
      armour: 0,
      attack_speed_pct: 0,
      combines_with: 'libreta',
      combines_into: 'plan-de-ahorro',
    },
    { id: 'libreta', item_id: 'libreta', damage: 0, hp: 40, armour: 3, attack_speed_pct: 0 },
    {
      id: 'plan-de-ahorro',
      item_id: 'plan-de-ahorro',
      damage: 10,
      hp: 60,
      armour: 4,
      attack_speed_pct: 10,
    },
  ],
  opponents: [
    {
      id: 'rival-ahorrador',
      item_id: 'rival-ahorrador',
      profile: 'saver',
      power_pct: 84,
      error_rate_pct: 8,
      units: [
        { unit_id: 'ahorrador', star: 1, col: 0, row: 0 },
        { unit_id: 'ahorrador', star: 1, col: 2, row: 0 },
        { unit_id: 'alcancia', star: 1, col: 1, row: 1 },
      ],
      sprite_slot: 'opponent_1',
    },
    {
      id: 'rival-gastalon',
      item_id: 'rival-gastalon',
      profile: 'synergy',
      power_pct: 76,
      error_rate_pct: 0,
      units: [
        { unit_id: 'gasto-hormiga', star: 1, col: 0, row: 0 },
        { unit_id: 'gasto-hormiga', star: 1, col: 2, row: 0 },
        { unit_id: 'alcancia', star: 1, col: 1, row: 1 },
        { unit_id: 'interes', star: 1, col: 0, row: 1 },
      ],
      sprite_slot: 'opponent_2',
    },
    {
      id: 'rival-espejo',
      item_id: 'rival-espejo',
      profile: 'mirror',
      power_pct: 72,
      error_rate_pct: 0,
      units: [],
      sprite_slot: 'opponent_3',
    },
  ],
  camps: [
    {
      id: 'camp-monedas',
      item_id: 'camp-monedas',
      power_pct: 58,
      units: [
        { unit_id: 'ahorrador', star: 1, col: 0, row: 0 },
        { unit_id: 'ahorrador', star: 1, col: 2, row: 0 },
        { unit_id: 'alcancia', star: 1, col: 1, row: 1 },
      ],
      drops: ['moneda-extra'],
      sprite_slot: 'opponent_4',
    },
    {
      id: 'camp-gastos',
      item_id: 'camp-gastos',
      power_pct: 68,
      units: [
        { unit_id: 'gasto-hormiga', star: 1, col: 0, row: 0 },
        { unit_id: 'gasto-hormiga', star: 1, col: 2, row: 0 },
        { unit_id: 'alcancia', star: 1, col: 1, row: 1 },
      ],
      drops: ['libreta'],
      sprite_slot: 'opponent_5',
    },
  ],
  opponent_profiles: {
    saver: {
      early_power_pct: 70,
      late_power_pct: 120,
      late_from_round: 4,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 0,
      mirror: false,
    },
    rush: {
      early_power_pct: 120,
      late_power_pct: 80,
      late_from_round: 4,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 0,
      mirror: false,
    },
    synergy: {
      early_power_pct: 90,
      late_power_pct: 100,
      late_from_round: 3,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 15,
      mirror: false,
    },
    mirror: {
      early_power_pct: 100,
      late_power_pct: 100,
      late_from_round: 1,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 0,
      mirror: true,
    },
    adaptive: {
      early_power_pct: 85,
      late_power_pct: 95,
      late_from_round: 3,
      adaptive_per_win_pct: 5,
      team_bonus_pct: 0,
      mirror: false,
    },
  },
  rounds: [
    { kind: 'pve', camp_id: 'camp-monedas' },
    { kind: 'pvp', opponent_id: 'rival-ahorrador' },
    { kind: 'pve', camp_id: 'camp-gastos' },
    { kind: 'pvp', opponent_id: 'rival-gastalon' },
    { kind: 'pvp', opponent_id: 'rival-espejo' },
    // The finale re-meets the saver, whose personality curve has flipped to its LATE
    // power by now: a board that coasted on early wins meets a rival that saved for this.
    { kind: 'pvp', opponent_id: 'rival-ahorrador' },
  ],
  score_weights: { rounds: 0.4, health: 0.2, interest: 0.4 },
  targets: { rounds_won: 5, interest: 14 },
  loss_penalty_pct: 2,
  max_ticks: 5000,
}

const savingsContent: AutobattlerContent = {
  categories: [
    { id: 'equipo', label_md: 'Tu equipo', description_md: 'Los que pelean por tu plan.' },
    { id: 'rivales', label_md: 'Rivales', description_md: 'Quienes retan tu presupuesto.' },
    { id: 'objetos', label_md: 'Objetos', description_md: 'Lo que sueltan los campamentos.' },
  ],
  items: [
    {
      id: 'ahorrador',
      label_md: 'Ahorrador',
      category: 'equipo',
      icon: 'savings',
      value: 1,
      image_slot: 'unit_1',
      props: { costo: 1 },
    },
    {
      id: 'alcancia',
      label_md: 'Alcancía',
      category: 'equipo',
      icon: 'account_balance_wallet',
      value: 1,
      image_slot: 'unit_2',
      props: { costo: 1 },
    },
    {
      id: 'interes',
      label_md: 'Interés',
      category: 'equipo',
      icon: 'trending_up',
      value: 2,
      image_slot: 'unit_3',
      props: { costo: 2 },
    },
    {
      id: 'gasto-hormiga',
      label_md: 'Gasto hormiga',
      category: 'equipo',
      icon: 'local_cafe',
      value: 2,
      image_slot: 'unit_4',
      misconception_md:
        'Pega fuerte al principio, pero cada compra chiquita te deja sin monedas que guardar.',
      props: { costo: 2 },
    },
    {
      id: 'presupuesto',
      label_md: 'Presupuesto',
      category: 'equipo',
      icon: 'receipt_long',
      value: 3,
      image_slot: 'unit_5',
      props: { costo: 3 },
    },
    { id: 'trait-ahorro', label_md: 'Ahorro', icon: 'shield_moon', image_slot: 'trait_1' },
    { id: 'trait-interes', label_md: 'Interés', icon: 'percent', image_slot: 'trait_2' },
    { id: 'trait-escudo', label_md: 'Colchón', icon: 'security', image_slot: 'trait_3' },
    { id: 'trait-gasto', label_md: 'Gasto', icon: 'shopping_bag', image_slot: 'trait_4' },
    {
      id: 'rival-ahorrador',
      label_md: 'La que guarda primero',
      category: 'rivales',
      icon: 'group',
      image_slot: 'opponent_1',
    },
    {
      id: 'rival-gastalon',
      label_md: 'El que gasta todo',
      category: 'rivales',
      icon: 'shopping_cart',
      image_slot: 'opponent_2',
      misconception_md: 'Se ve poderoso, pero gastó todo y no le quedó nada para la ronda siguiente.',
    },
    {
      id: 'rival-espejo',
      label_md: 'Tu propio reflejo',
      category: 'rivales',
      icon: 'flip',
      image_slot: 'opponent_3',
    },
    {
      id: 'camp-monedas',
      label_md: 'Campamento de monedas',
      category: 'rivales',
      icon: 'paid',
      image_slot: 'opponent_4',
    },
    {
      id: 'camp-gastos',
      label_md: 'Campamento de antojos',
      category: 'rivales',
      icon: 'icecream',
      image_slot: 'opponent_5',
    },
    {
      id: 'moneda-extra',
      label_md: 'Moneda extra',
      category: 'objetos',
      icon: 'toll',
      image_slot: 'item_1',
    },
    {
      id: 'libreta',
      label_md: 'Libreta de gastos',
      category: 'objetos',
      icon: 'edit_note',
      image_slot: 'item_2',
    },
    {
      id: 'plan-de-ahorro',
      label_md: 'Plan de ahorro',
      category: 'objetos',
      icon: 'workspace_premium',
      image_slot: 'item_3',
    },
  ],
  interludes: [
    {
      id: 'pausa-interes',
      after_round: 2,
      kind: 'pick_one',
      prompt_md: 'Tienes 12 monedas. ¿Qué te deja mejor para la próxima ronda?',
      options: [
        {
          id: 'a',
          label_md: 'Gastarlas todas hoy',
          correct: false,
          rationale_md: 'Te quedas fuerte una ronda y sin interés para la siguiente.',
        },
        {
          id: 'b',
          label_md: 'Guardar hasta el tope y gastar lo que sobra',
          correct: true,
          rationale_md: 'Así cobras el interés completo y aun así mejoras tu equipo.',
        },
      ],
    },
  ],
  feedback: {
    correct_md: ['¡Tu plan aguantó!', 'Guardaste y ganaste.', 'Ese equipo estaba bien pensado.'],
    incorrect_md: [
      'Casi. Revisa cuántas monedas te quedaron guardadas.',
      'Otra vuelta: ¿te faltó equipo o te faltó ahorro?',
    ],
    results_md:
      'Guardar hasta el tope del interés y gastar solo lo que sobra te deja fuerte hoy y más rico mañana.',
  },
  tips: {
    interest_md: 'Cada 5 monedas guardadas te pagan 1 al final de la ronda, hasta 3 monedas.',
    saving_md: 'Si gastas todo, el interés se va a cero. Guarda hasta el tope y compra con lo demás.',
  },
}

const savingsTeam: GameDocument = {
  schema_version: 1,
  meta: {
    slug: 'el-equipo-del-ahorro',
    title: 'El equipo del ahorro',
    locale: 'es-MX',
    mechanic: 'autobattler',
    concept: {
      topic_path: 'mi-primer-dinero/guardar-con-un-plan/el-interes',
      recap_md:
        'Aprendiste que el **interés** es lo que tu dinero gana por quedarse guardado, y que casi siempre tiene un **tope**: pasado ese punto, guardar de más ya no paga más.',
    },
    tier: 2,
    estimated_minutes: 5,
    cast: ['dina', 'liruf'],
  },
  skin: {
    palette: 'forest-pear',
    sprites: {},
    sfx: { buy: 'drop', merge: 'match', win: 'celebration', lose: 'tryagain', interest: 'streak' },
  },
  config: savingsConfig,
  content: savingsContent,
  scoring: { mode: 'cheer', xp_max: 15, pass_score: 65, lives: null, target: 4 },
}

// ---- 2. Duelo de presupuesto (tier 3, arcade) ----------------------------------------

const budgetConfig: AutobattlerConfig = {
  board: { cols: 4, rows: 2, cell_size: 76, team_size: 6, bench_size: 5 },
  shop: {
    offers: 4,
    refresh_cost: 2,
    rarity_by_level: [
      [75, 25, 0, 0],
      [55, 35, 10, 0],
      [40, 35, 22, 3],
      [30, 33, 27, 10],
    ],
    level: {
      max: 4,
      xp_cost: 4,
      xp_per_purchase: 4,
      xp_per_buy: 1,
      xp_needed: [4, 8, 12, 99],
      units_by_level: [3, 4, 5, 6],
    },
  },
  merge: { copies_needed: 3, max_star: 3, star_multipliers: [1, 1.8, 3.2] },
  economy: {
    start_gold: 14,
    base_income: 5,
    income_growth_per_round: 1,
    income_cap: 10,
    interest: { gold_per_step: 6, amount_per_step: 1, max_steps: 4 },
    streak: { win_bonus: [1, 2, 3], loss_bonus: [0, 1, 2] },
    sell_refund_pct: 80,
  },
  combat: {
    engine_ticks_per_combat_tick: 10,
    max_combat_ticks: 70,
    timeout_result: 'most_units',
    targeting: 'closest',
    min_damage: 2,
    crit_chance_pct: 15,
    crit_multiplier_pct: 180,
    adjacency: {
      enabled: true,
      per_neighbour_damage_pct: 6,
      per_neighbour_armour: 2,
      // Tier 3: neighbours only count when they share a trait, so the board becomes a
      // planning problem instead of a "put them next to each other" reflex.
      same_trait_only: true,
    },
  },
  health: { start: 30, base_damage: 3, per_round: 1, per_survivor: 2 },
  prep: { max_ticks: 300, auto_merge: true },
  units: [
    {
      id: 'ingreso',
      item_id: 'ingreso',
      rarity: 1,
      cost: 1,
      traits: ['entrada'],
      stats: {
        hp: 240,
        damage: 32,
        armour: 6,
        attack_interval: 2,
        range: 1200,
        move_speed: 520,
        mana_max: 30,
        mana_per_attack: 12,
        mana_on_damaged: 4,
      },
      ability: { kind: 'empower', power: 30, radius: 0 },
      sprite_slot: 'unit_1',
    },
    {
      id: 'fondo-emergencia',
      item_id: 'fondo-emergencia',
      rarity: 1,
      cost: 1,
      traits: ['reserva', 'colchon'],
      stats: {
        hp: 340,
        damage: 22,
        armour: 12,
        attack_interval: 3,
        range: 1100,
        move_speed: 420,
        mana_max: 55,
        mana_per_attack: 12,
        mana_on_damaged: 7,
      },
      ability: { kind: 'shield', power: 50, radius: 0 },
      sprite_slot: 'unit_2',
    },
    {
      id: 'interes-compuesto',
      item_id: 'interes-compuesto',
      rarity: 2,
      cost: 2,
      traits: ['reserva', 'interes'],
      stats: {
        hp: 210,
        damage: 46,
        armour: 4,
        attack_interval: 2,
        range: 3200,
        move_speed: 460,
        mana_max: 30,
        mana_per_attack: 15,
        mana_on_damaged: 4,
      },
      ability: { kind: 'burst', power: 140, radius: 0 },
      targeting: 'lowest_health',
      sprite_slot: 'unit_3',
    },
    {
      id: 'meta-de-ahorro',
      item_id: 'meta-de-ahorro',
      rarity: 2,
      cost: 2,
      traits: ['reserva'],
      stats: {
        hp: 280,
        damage: 34,
        armour: 8,
        attack_interval: 2,
        range: 1400,
        move_speed: 500,
        mana_max: 55,
        mana_per_attack: 13,
        mana_on_damaged: 6,
      },
      ability: { kind: 'heal', power: 60, radius: 0 },
      sprite_slot: 'unit_4',
    },
    {
      id: 'compra-impulsiva',
      item_id: 'compra-impulsiva',
      rarity: 2,
      cost: 2,
      traits: ['gasto'],
      stats: {
        hp: 210,
        damage: 44,
        armour: 4,
        attack_interval: 2,
        range: 1200,
        move_speed: 580,
        mana_max: 40,
        mana_per_attack: 15,
        mana_on_damaged: 5,
      },
      ability: { kind: 'empower', power: 45, radius: 0 },
      sprite_slot: 'unit_5',
    },
    {
      id: 'presupuesto-mensual',
      item_id: 'presupuesto-mensual',
      rarity: 3,
      cost: 3,
      traits: ['entrada', 'interes'],
      stats: {
        hp: 300,
        damage: 50,
        armour: 9,
        attack_interval: 2,
        range: 2400,
        move_speed: 500,
        mana_max: 50,
        mana_per_attack: 17,
        mana_on_damaged: 6,
      },
      ability: { kind: 'splash', power: 120, radius: 1700 },
      sprite_slot: 'unit_6',
    },
    {
      id: 'inversion',
      item_id: 'inversion',
      rarity: 4,
      cost: 4,
      traits: ['interes', 'colchon'],
      stats: {
        hp: 340,
        damage: 58,
        armour: 10,
        attack_interval: 2,
        range: 2600,
        move_speed: 480,
        mana_max: 50,
        mana_per_attack: 18,
        mana_on_damaged: 6,
      },
      ability: { kind: 'splash', power: 150, radius: 1900 },
      sprite_slot: 'unit_7',
    },
  ],
  traits: [
    {
      id: 'reserva',
      item_id: 'trait-reserva',
      scope: 'team',
      thresholds: [
        { count: 2, damage_pct: 0, hp_pct: 12, armour: 3, attack_speed_pct: 0 },
        { count: 3, damage_pct: 5, hp_pct: 12, armour: 4, attack_speed_pct: 0 },
        { count: 4, damage_pct: 8, hp_pct: 14, armour: 5, attack_speed_pct: 5 },
      ],
    },
    {
      id: 'interes',
      item_id: 'trait-interes',
      scope: 'trait',
      thresholds: [
        { count: 1, damage_pct: 15, hp_pct: 0, armour: 0, attack_speed_pct: 0 },
        { count: 2, damage_pct: 25, hp_pct: 0, armour: 0, attack_speed_pct: 15 },
      ],
    },
    {
      id: 'colchon',
      item_id: 'trait-colchon',
      scope: 'trait',
      thresholds: [{ count: 2, damage_pct: 0, hp_pct: 15, armour: 10, attack_speed_pct: 0 }],
    },
    {
      id: 'entrada',
      item_id: 'trait-entrada',
      scope: 'trait',
      thresholds: [
        { count: 1, damage_pct: 10, hp_pct: 0, armour: 0, attack_speed_pct: 0 },
        { count: 2, damage_pct: 15, hp_pct: 8, armour: 0, attack_speed_pct: 0 },
      ],
    },
    {
      id: 'gasto',
      item_id: 'trait-gasto',
      scope: 'trait',
      thresholds: [{ count: 1, damage_pct: 30, hp_pct: 0, armour: 0, attack_speed_pct: 0 }],
    },
  ],
  items: [
    {
      id: 'sobre-quincenal',
      item_id: 'sobre-quincenal',
      damage: 8,
      hp: 0,
      armour: 0,
      attack_speed_pct: 0,
      combines_with: 'hoja-de-metas',
      combines_into: 'plan-anual',
    },
    {
      id: 'hoja-de-metas',
      item_id: 'hoja-de-metas',
      damage: 0,
      hp: 60,
      armour: 4,
      attack_speed_pct: 0,
    },
    {
      id: 'plan-anual',
      item_id: 'plan-anual',
      damage: 14,
      hp: 90,
      armour: 6,
      attack_speed_pct: 12,
    },
  ],
  opponents: [
    {
      id: 'rival-prisa',
      item_id: 'rival-prisa',
      profile: 'rush',
      power_pct: 78,
      error_rate_pct: 20,
      units: [
        { unit_id: 'compra-impulsiva', star: 1, col: 1, row: 0 },
        { unit_id: 'compra-impulsiva', star: 1, col: 2, row: 0 },
        { unit_id: 'ingreso', star: 1, col: 1, row: 1 },
        { unit_id: 'ingreso', star: 1, col: 2, row: 1 },
      ],
      sprite_slot: 'opponent_1',
    },
    {
      id: 'rival-paciente',
      item_id: 'rival-paciente',
      profile: 'saver',
      power_pct: 92,
      error_rate_pct: 10,
      units: [
        { unit_id: 'fondo-emergencia', star: 1, col: 1, row: 0 },
        { unit_id: 'meta-de-ahorro', star: 1, col: 2, row: 0 },
        { unit_id: 'interes-compuesto', star: 1, col: 1, row: 1 },
        { unit_id: 'ingreso', star: 1, col: 0, row: 0 },
      ],
      sprite_slot: 'opponent_2',
    },
    {
      id: 'rival-sinergia',
      item_id: 'rival-sinergia',
      profile: 'synergy',
      power_pct: 88,
      error_rate_pct: 5,
      units: [
        { unit_id: 'ingreso', star: 1, col: 0, row: 0 },
        { unit_id: 'meta-de-ahorro', star: 1, col: 2, row: 0 },
        { unit_id: 'fondo-emergencia', star: 1, col: 1, row: 1 },
        { unit_id: 'interes-compuesto', star: 1, col: 2, row: 1 },
        { unit_id: 'presupuesto-mensual', star: 1, col: 1, row: 0 },
      ],
      sprite_slot: 'opponent_3',
    },
    {
      id: 'rival-espejo',
      item_id: 'rival-espejo',
      profile: 'mirror',
      power_pct: 84,
      error_rate_pct: 0,
      units: [],
      sprite_slot: 'opponent_4',
    },
    {
      id: 'rival-que-aprende',
      item_id: 'rival-que-aprende',
      profile: 'adaptive',
      power_pct: 86,
      error_rate_pct: 5,
      units: [
        { unit_id: 'presupuesto-mensual', star: 1, col: 1, row: 0 },
        { unit_id: 'fondo-emergencia', star: 1, col: 2, row: 0 },
        { unit_id: 'interes-compuesto', star: 1, col: 1, row: 1 },
        { unit_id: 'meta-de-ahorro', star: 1, col: 2, row: 1 },
        { unit_id: 'inversion', star: 1, col: 0, row: 0 },
      ],
      sprite_slot: 'opponent_5',
    },
  ],
  camps: [
    {
      id: 'camp-sobres',
      item_id: 'camp-sobres',
      power_pct: 58,
      units: [
        { unit_id: 'ingreso', star: 1, col: 0, row: 0 },
        { unit_id: 'ingreso', star: 1, col: 3, row: 0 },
        { unit_id: 'ingreso', star: 1, col: 2, row: 1 },
      ],
      drops: ['sobre-quincenal'],
      sprite_slot: 'opponent_6',
    },
    {
      id: 'camp-metas',
      item_id: 'camp-metas',
      power_pct: 76,
      units: [
        { unit_id: 'meta-de-ahorro', star: 1, col: 1, row: 0 },
        { unit_id: 'fondo-emergencia', star: 1, col: 2, row: 1 },
        { unit_id: 'ingreso', star: 1, col: 2, row: 0 },
      ],
      drops: ['hoja-de-metas'],
      sprite_slot: 'opponent_6',
    },
  ],
  opponent_profiles: {
    saver: {
      early_power_pct: 65,
      late_power_pct: 115,
      late_from_round: 5,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 0,
      mirror: false,
    },
    rush: {
      early_power_pct: 115,
      late_power_pct: 75,
      late_from_round: 4,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 0,
      mirror: false,
    },
    synergy: {
      early_power_pct: 85,
      late_power_pct: 95,
      late_from_round: 4,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 12,
      mirror: false,
    },
    mirror: {
      early_power_pct: 100,
      late_power_pct: 100,
      late_from_round: 1,
      adaptive_per_win_pct: 0,
      team_bonus_pct: 0,
      mirror: true,
    },
    adaptive: {
      early_power_pct: 80,
      late_power_pct: 90,
      late_from_round: 4,
      adaptive_per_win_pct: 4,
      team_bonus_pct: 0,
      mirror: false,
    },
  },
  rounds: [
    { kind: 'pve', camp_id: 'camp-sobres' },
    { kind: 'pvp', opponent_id: 'rival-prisa' },
    { kind: 'pve', camp_id: 'camp-metas' },
    { kind: 'pvp', opponent_id: 'rival-paciente' },
    { kind: 'pvp', opponent_id: 'rival-sinergia' },
    { kind: 'pvp', opponent_id: 'rival-espejo' },
    { kind: 'pvp', opponent_id: 'rival-que-aprende' },
  ],
  score_weights: { rounds: 0.4, health: 0.2, interest: 0.4 },
  targets: { rounds_won: 5, interest: 20 },
  loss_penalty_pct: 3,
  max_ticks: 6000,
}

const budgetContent: AutobattlerContent = {
  categories: [
    { id: 'equipo', label_md: 'Tu equipo', description_md: 'Las piezas de tu presupuesto.' },
    { id: 'rivales', label_md: 'Rivales', description_md: 'Cada uno decide su dinero distinto.' },
    { id: 'objetos', label_md: 'Objetos', description_md: 'Se combinan para hacer uno mejor.' },
  ],
  items: [
    {
      id: 'ingreso',
      label_md: 'Ingreso',
      category: 'equipo',
      icon: 'payments',
      value: 1,
      image_slot: 'unit_1',
      props: { costo: 1 },
    },
    {
      id: 'fondo-emergencia',
      label_md: 'Fondo de emergencia',
      category: 'equipo',
      icon: 'health_and_safety',
      value: 1,
      image_slot: 'unit_2',
      props: { costo: 1 },
    },
    {
      id: 'interes-compuesto',
      label_md: 'Interés compuesto',
      category: 'equipo',
      icon: 'trending_up',
      value: 2,
      image_slot: 'unit_3',
      props: { costo: 2 },
    },
    {
      id: 'meta-de-ahorro',
      label_md: 'Meta de ahorro',
      category: 'equipo',
      icon: 'flag',
      value: 2,
      image_slot: 'unit_4',
      props: { costo: 2 },
    },
    {
      id: 'compra-impulsiva',
      label_md: 'Compra impulsiva',
      category: 'equipo',
      icon: 'bolt',
      value: 2,
      image_slot: 'unit_5',
      misconception_md:
        'Pega durísimo una ronda y te deja sin monedas guardadas para la siguiente: fuerza prestada, no ganada.',
      props: { costo: 2 },
    },
    {
      id: 'presupuesto-mensual',
      label_md: 'Presupuesto mensual',
      category: 'equipo',
      icon: 'receipt_long',
      value: 3,
      image_slot: 'unit_6',
      props: { costo: 3 },
    },
    {
      id: 'inversion',
      label_md: 'Inversión',
      category: 'equipo',
      icon: 'query_stats',
      value: 4,
      image_slot: 'unit_7',
      props: { costo: 4 },
    },
    { id: 'trait-reserva', label_md: 'Reserva', icon: 'savings', image_slot: 'trait_1' },
    { id: 'trait-interes', label_md: 'Interés', icon: 'percent', image_slot: 'trait_2' },
    { id: 'trait-colchon', label_md: 'Colchón', icon: 'security', image_slot: 'trait_3' },
    { id: 'trait-entrada', label_md: 'Entradas', icon: 'login', image_slot: 'trait_4' },
    { id: 'trait-gasto', label_md: 'Gasto', icon: 'shopping_bag', image_slot: 'trait_5' },
    {
      id: 'rival-prisa',
      label_md: 'El que compra de volada',
      category: 'rivales',
      icon: 'rocket_launch',
      image_slot: 'opponent_1',
      misconception_md: 'Arranca fortísimo y se apaga: gastó todo antes de las rondas difíciles.',
    },
    {
      id: 'rival-paciente',
      label_md: 'La que espera y guarda',
      category: 'rivales',
      icon: 'hourglass_top',
      image_slot: 'opponent_2',
    },
    {
      id: 'rival-sinergia',
      label_md: 'El del equipo parejo',
      category: 'rivales',
      icon: 'diversity_3',
      image_slot: 'opponent_3',
    },
    {
      id: 'rival-espejo',
      label_md: 'Tu propio reflejo',
      category: 'rivales',
      icon: 'flip',
      image_slot: 'opponent_4',
    },
    {
      id: 'rival-que-aprende',
      label_md: 'La que aprende de ti',
      category: 'rivales',
      icon: 'psychology',
      image_slot: 'opponent_5',
    },
    {
      id: 'camp-sobres',
      label_md: 'Campamento de sobres',
      category: 'rivales',
      icon: 'mail',
      image_slot: 'opponent_6',
    },
    {
      id: 'camp-metas',
      label_md: 'Campamento de metas',
      category: 'rivales',
      icon: 'checklist',
      image_slot: 'opponent_6',
    },
    {
      id: 'sobre-quincenal',
      label_md: 'Sobre quincenal',
      category: 'objetos',
      icon: 'mail',
      image_slot: 'item_1',
    },
    {
      id: 'hoja-de-metas',
      label_md: 'Hoja de metas',
      category: 'objetos',
      icon: 'edit_note',
      image_slot: 'item_2',
    },
    {
      id: 'plan-anual',
      label_md: 'Plan anual',
      category: 'objetos',
      icon: 'workspace_premium',
      image_slot: 'item_3',
    },
  ],
  interludes: [
    {
      id: 'pausa-tope',
      after_round: 3,
      kind: 'true_false',
      prompt_md: 'Guardar más allá del tope del interés te paga todavía más.',
      options: [
        {
          id: 'si',
          label_md: 'Cierto',
          correct: false,
          rationale_md: 'Pasado el tope, esas monedas ya no generan nada extra.',
        },
        {
          id: 'no',
          label_md: 'Falso',
          correct: true,
          rationale_md: 'Justo por eso conviene guardar hasta el tope y usar lo demás en tu equipo.',
        },
      ],
    },
  ],
  feedback: {
    correct_md: ['¡Ronda tuya!', 'El plan aguantó.', 'Ahorro y equipo, los dos.'],
    incorrect_md: [
      'Casi. Fíjate si te faltó equipo o te faltó guardar.',
      'Otra vuelta: revisa cuántas monedas dejaste trabajando.',
    ],
    results_md:
      'Ganar rondas y seguir cobrando interés es el mismo plan: guarda hasta el tope, gasta el sobrante y arma tu equipo con calma.',
  },
  tips: {
    interest_md: 'Cada 6 monedas guardadas te pagan 1 al cerrar la ronda, hasta 4 monedas.',
    saving_md:
      'Gastar hasta la última moneda te deja fuerte hoy y pobre mañana. Deja el tope guardado y compra con el resto.',
  },
}

const budgetDuel: GameDocument = {
  schema_version: 1,
  meta: {
    slug: 'duelo-de-presupuesto',
    title: 'Duelo de presupuesto',
    locale: 'es-MX',
    mechanic: 'autobattler',
    concept: {
      topic_path: 'planear-mi-dinero/decidir-con-numeros/gastar-o-guardar',
      recap_md:
        'Aprendiste a comparar **gastar ahora** contra **guardar para después**: el interés paga por esperar, pero sólo hasta su tope, así que la mejor jugada casi siempre es guardar hasta ahí y usar el resto.',
    },
    tier: 3,
    estimated_minutes: 7,
    cast: ['rho', 'zara'],
  },
  skin: {
    palette: 'navy-papaya',
    sprites: {},
    sfx: {
      buy: 'drop',
      merge: 'match',
      win: 'celebration',
      lose: 'tryagain',
      interest: 'streak',
      battle: 'impact',
    },
    bgm: 'arcade-tense',
  },
  config: budgetConfig,
  content: budgetContent,
  scoring: { mode: 'arcade', xp_max: 25, pass_score: 70, lives: 3, target: 5 },
  adaptive: { enabled: true, ease_after_failures: 2, ease_factor: 0.85, assist_toggleable: true },
}

export const autobattlerFixtures: GameDocument[] = [savingsTeam, budgetDuel]
