// Independently declared scope and sequence. Never infer course completeness from existing files.
import { L, sharedKc } from './assemble.mjs';
import { objectives } from './skill-objectives.mjs';
const skills = [
  ['cash.direction', 'cash-flow', []],
  ['cash.received', 'cash-flow', ['cash.direction']],
  ['cash.balance', 'cash-flow', ['cash.direction', 'cash.received']],
  ['cash.reserved', 'cash-flow', ['cash.received', 'cash.balance']],
  ['cash.dates', 'cash-flow', ['cash.received', 'cash.reserved']],
  ['plan.priority', 'planning', ['cash.reserved', 'cash.dates']],
  ['plan.uncertain-income', 'planning', ['cash.received', 'cash.reserved', 'plan.priority']],
  ['plan.periodic', 'planning', ['cash.dates', 'cash.reserved']],
  ['plan.revise', 'planning', ['cash.balance', 'cash.reserved', 'plan.priority', 'plan.uncertain-income', 'plan.periodic']],
  ['price.unit', 'purchasing', ['cash.balance', 'plan.priority']],
  ['price.percent', 'purchasing', ['cash.balance', 'price.unit']],
  ['price.final', 'purchasing', ['price.percent', 'price.unit', 'cash.reserved']],
  ['save.goal', 'saving', ['plan.periodic', 'plan.revise']],
  ['save.emergency', 'saving', ['plan.priority', 'plan.periodic', 'save.goal']],
  ['save.access', 'saving', ['cash.dates', 'save.emergency']],
  ['debt.obligation', 'borrowing', ['cash.balance', 'cash.dates', 'plan.revise']],
  ['debt.total-cost', 'borrowing', ['debt.obligation', 'price.final', 'cash.dates']],
  ['debt.interest', 'borrowing', ['debt.total-cost', 'price.percent', 'cash.balance']],
  ['debt.minimum', 'borrowing', ['debt.interest', 'debt.total-cost', 'plan.revise']],
  ['time.purchasing-power', 'time-and-risk', ['price.percent', 'cash.reserved']],
  ['time.compound', 'time-and-risk', ['price.percent', 'debt.interest', 'time.purchasing-power']],
  ['invest.horizon', 'time-and-risk', ['save.access', 'time.purchasing-power', 'time.compound']],
  ['invest.diversify', 'time-and-risk', ['invest.horizon']],
  ['safety.fraud', 'protection', ['debt.total-cost', 'invest.horizon']],
  ['safety.credentials', 'protection', ['safety.fraud']],
  ['product.conditions', 'protection', ['price.final', 'save.access', 'debt.obligation', 'plan.periodic']],
  ['rights.agreement', 'protection', ['product.conditions', 'debt.total-cost', 'safety.fraud']],
];
const units = [
  ['fe-solid-01-money-today', ['Money available today', 'Dinero disponible hoy', 'Dinheiro disponível hoje'], 'Track received money, balance, reservations and payment dates before planning a purchase.'],
  ['fe-solid-02-a-plan-that-fits', ['A plan that fits', 'Un plan que sí cabe', 'Um plano que cabe'], 'Prioritize by consequences and revise a feasible plan under uncertainty and predictable future costs.'],
  ['fe-solid-03-compare-before-paying', ['Compare before paying', 'Compara antes de pagar', 'Compare antes de pagar'], 'Compare equal units, percentage shares and complete prices rather than advertising headlines.'],
  ['fe-solid-04-save-with-a-purpose', ['Save with a purpose', 'Ahorra con propósito', 'Poupe com um propósito'], 'Prepare goals and unexpected needs while checking real contribution capacity and access conditions.'],
  ['fe-solid-05-understand-borrowing', ['Understand borrowing', 'Comprende los préstamos', 'Entenda os empréstimos'], 'Distinguish income from debt and calculate total obligations, period interest and remaining balances.'],
  ['fe-solid-06-money-over-time', ['Money over time', 'El dinero con el tiempo', 'O dinheiro com o tempo'], 'Distinguish purchasing power and modeled compound growth from nominal amounts and guarantees.'],
  ['fe-solid-07-risk-and-protection', ['Risk and protection', 'Riesgo y protección', 'Risco e proteção'], 'Check time horizons, concentration and claims of safe returns without recommending products.'],
  ['fe-solid-08-decide-with-evidence', ['Decide with evidence', 'Decide con información', 'Decida com informação'], 'Protect credentials, read complete terms and apply prior skills in integrated decisions.'],
];
// [number, slug, unit index, primary skill, teaching/review kind, retrieved skills]
const sequence = [
  [1, 'money-moves', 0, 'cash.direction'],
  [2, 'received-not-promised', 0, 'cash.received'],
  [3, 'update-your-balance', 0, 'cash.balance'],
  [4, 'protect-committed-money', 0, 'cash.reserved'],
  [5, 'money-has-dates', 0, 'cash.dates'],
  [6, 'protect-what-matters', 1, 'plan.priority'],
  [7, 'a-week-of-real-payments', 1, 'cash.received', 'consolidate', ['cash.direction', 'cash.received', 'cash.balance', 'cash.reserved', 'cash.dates']],
  [8, 'income-can-change', 1, 'plan.uncertain-income'],
  [9, 'prepare-for-known-costs', 1, 'plan.periodic'],
  [10, 'revise-a-plan', 1, 'plan.revise'],
  [11, 'choose-a-workable-plan', 1, 'plan.priority', 'consolidate', ['plan.priority', 'plan.uncertain-income', 'plan.periodic']],
  [12, 'compare-equal-units', 2, 'price.unit'],
  [13, 'a-percent-is-a-share', 2, 'price.percent'],
  [14, 'compare-the-final-price', 2, 'price.final'],
  [15, 'make-a-purchase-plan', 2, 'price.unit', 'consolidate', ['plan.revise', 'price.unit', 'price.percent']],
  [16, 'make-a-saving-goal', 3, 'save.goal'],
  [17, 'prepare-for-a-surprise', 3, 'save.emergency'],
  [18, 'can-you-use-it-in-time', 3, 'save.access'],
  [19, 'protect-two-saving-purposes', 3, 'save.goal', 'consolidate', ['price.final', 'save.goal', 'save.emergency']],
  [20, 'borrowing-is-an-obligation', 4, 'debt.obligation'],
  [21, 'count-the-full-repayment', 4, 'debt.total-cost'],
  [22, 'interest-changes-the-debt', 4, 'debt.interest'],
  [23, 'read-the-whole-commitment', 4, 'debt.total-cost', 'consolidate', ['save.access', 'debt.obligation', 'debt.total-cost']],
  [24, 'minimum-is-not-interest-free', 4, 'debt.minimum'],
  [25, 'what-your-money-can-buy', 5, 'time.purchasing-power'],
  [26, 'growth-on-earlier-growth', 5, 'time.compound'],
  [27, 'when-time-changes-the-balance', 5, 'debt.interest', 'consolidate', ['debt.interest', 'debt.minimum', 'time.purchasing-power']],
  [28, 'risk-needs-a-time-horizon', 6, 'invest.horizon'],
  [29, 'spread-the-exposure', 6, 'invest.diversify'],
  [30, 'recognize-a-financial-trap', 6, 'safety.fraud'],
  [31, 'check-the-investment-story', 6, 'invest.horizon', 'consolidate', ['time.compound', 'invest.horizon', 'invest.diversify']],
  [32, 'protect-access-to-your-money', 7, 'safety.credentials'],
  [33, 'compare-account-conditions', 7, 'product.conditions'],
  [34, 'check-an-agreement-before-signing', 7, 'rights.agreement'],
  [35, 'choose-under-pressure', 7, 'safety.fraud', 'capstone', ['safety.fraud', 'safety.credentials', 'product.conditions']],
  [36, 'plan-a-new-month', 7, 'plan.revise', 'capstone', ['rights.agreement', 'save.goal', 'debt.minimum', 'plan.revise', 'cash.reserved']],
];
export const blueprint = {
  publication_intent: 'calibration-only',
  version: 1, course_id: 'financial-education', pathway_id: 'financial-adult', age_band: 'adult',
  metadata: { title: L(['Financial Education','Educación Financiera','Educação Financeira']), description: L(['Build practical foundations for everyday money decisions.','Construye bases prácticas para decidir sobre tu dinero cotidiano.','Construa bases práticas para decidir sobre seu dinheiro cotidiano.']), subject: 'money', position: 1, badge_asset: 'course-badges/financial-education.png', requires: [] },
  scope: 'Adult financial foundations: progress from usable money and feasible plans to saving, borrowing, percentage calculations, purchasing power, modeled growth, basic investment risk and informed consumer decisions. This is a bounded foundation course, not a claim to exhaust financial knowledge or qualify a learner to advise others.',
  excluded_scope: ['Personal financial or investment recommendations', 'Current product offers, forecasts or market returns', 'Jurisdiction-specific tax filing, benefit eligibility and deposit-insurance limits', 'Advanced securities valuation, derivatives and professional financial advice', 'Child and teen pathways; family wallet operations'],
  units: units.map(([id, title, objective]) => ({id, title: L(title), objective})),
  sources: [
    {url:'https://www.consumerfinance.gov/ask-cfpb/what-are-some-classic-warning-signs-of-possible-fraud-and-scams-en-2094/', use:'Independent identity verification and pressured-payment warning signs; no US reporting procedure is presented as universal.'},
    {url:'https://www.consumerfinance.gov/ask-cfpb/i-received-an-email-from-my-bank-or-credit-union-asking-me-to-verify-my-account-information-what-should-i-do-en-999/', use:'Protecting credentials and verifying account messages through a separate official channel.'},
    {url:'https://www.condusef.gob.mx/?idc=2023&idcat=1&p=contenido', use:'Compare actual financial product costs, conditions and service information rather than advertisements alone.'},
    {url:'https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/toolkit/', use:'Coverage of goals, income, bills, cash flow, debt, products and protection; US legal rules are not exported to other markets.'},
    {url:'https://www.fdic.gov/consumer-resource-center/money-smart-adults', use:'Adult financial capability coverage; adapted into prerequisite-led micro-lessons rather than copied module order.'},
    {url:'https://www.oecd.org/en/publications/financial-competence-framework-for-adults-in-the-european-union_510f133c-en.html', use:'Competency coverage reference; bounded course scope does not claim complete professional financial competence.'},
    {url:'https://webappsos.condusef.gob.mx/EducaTuCartera/presupuesto.html', use:'Mexican financial education reference for budgeting and distinguishing actual resources from planned spending.'},
    {url:'https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/', use:'Borrowing vocabulary and the distinction between balances, minimum payments and borrowing charges; contractual examples remain explicitly fictional.'},
    {url:'https://www.investor.gov/introduction-investing', use:'Compound growth and investment risk concepts; examples make no return promises or product recommendations.'},
    {url:'https://www.investor.gov/additional-resources/general-resources/publications-research/info-sheets/beginners-guide-asset', use:'Time horizon and diversification concepts, including the limits of diversification.'},
    {url:'https://ies.ed.gov/ncee/wwc/PracticeGuide/1', use:'Instructional sequence with worked examples, independent practice and later retrieval; no claim of measured learner outcomes.'},
  ],
  skills: skills.map(([id, domain, prerequisites]) => { if (!objectives[id]) throw new Error(`Missing measurable outcome: ${id}`); return { id, knowledge_component_id: sharedKc(id), domain, outcome: objectives[id][0], prerequisites }; }),
  lessons: sequence.map(([number, slug, unit, primary_skill, kind = 'teach', retrieve_skills = []]) => ({ lesson_id: `fe-solid-${String(number).padStart(2,'0')}-${slug}`, unit_id: units[unit][0], primary_skill, kind, retrieve_skills })),
};
