import { makeLesson, examples as E, choice as Q, savings } from './assemble.mjs';
const unit = 'fe-solid-04-save-with-a-purpose';
export const plans = [makeLesson({ number: 16, slug: 'make-a-saving-goal', unit, title: ['Make a saving goal', 'Prepara una meta de ahorro', 'Prepare uma meta de poupança'], skill: 'save.goal', kc: 'money.savings-plan-math', prerequisites: ['plan.periodic', 'plan.revise'],
  outcome: 'Calculate the remaining amount for a goal and check whether repeated contributions fit both the deadline and available resources.',
  misconception: 'Dividing the full target instead of the remaining gap, or treating an unaffordable contribution as a workable plan.', numeracy: 'Subtract current savings from the target, then build the gap using repeated equal contributions.',
  relevance: ['Give saving a purpose, an amount and a date. These examples use dollars; check whether each plan fits.', 'Dale al ahorro un propósito, un monto y una fecha. Explora montos ficticios en pesos y comprueba si el plan cabe.', 'Dê à poupança um propósito, um valor e uma data. Explore valores fictícios em reais e confira se o plano cabe.'],
  segments: [
    E('example-01', ['Find the missing amount', 'Halla lo que falta', 'Ache o que falta'], ['A repair goal is 100 and 20 is already saved. The missing amount is 100 − 20 = 80.', 'La meta para una reparación es 100 y ya hay 20 ahorrados. Faltan 100 − 20 = 80.', 'A meta para um conserto é 100 e já há 20 poupados. Faltam 100 − 20 = 80.']),
    E('example-02', ['Build the gap in parts', 'Reúne el faltante por partes', 'Reúna a falta em partes'], ['Four contributions of 20 make 80. This plan works only if each contribution fits and arrives before the repair deadline.', 'Cuatro aportaciones de 20 reúnen 80. El plan funciona solo si cada aportación cabe y llega antes de la reparación.', 'Quatro contribuições de 20 reúnem 80. O plano funciona só se cada contribuição couber e chegar antes do conserto.']),
    savings('example-03', 4, 0, 30, 10, ['This chart starts from zero for the missing amount only. Try saving 20 weekly for four weeks, then compare 10.', 'Esta gráfica empieza en cero solo para el faltante. Prueba ahorrar 20 semanales durante cuatro semanas y compara con 10.', 'Este gráfico começa em zero só para o valor que falta. Teste poupar 20 por semana durante quatro semanas e compare com 10.']),
    Q('guided-01', 'guided', 'money.savings-plan-math', 0, [
      ['How much is still needed?', 'Your target is 100 and you already have 20 saved for it.', ['80', '100', '120'], 'Existing savings reduce the amount still needed.', 'Subtract what is already saved from the goal.'],
      ['¿Cuánto falta reunir?', 'Tu meta es 100 y ya tienes 20 ahorrados para ella.', ['80', '100', '120'], 'Lo ahorrado reduce el monto que aún falta.', 'Resta a la meta lo que ya tienes ahorrado.'],
      ['Quanto falta reunir?', 'Sua meta é 100 e você já tem 20 poupados para ela.', ['80', '100', '120'], 'O que foi poupado reduz o valor que ainda falta.', 'Subtraia da meta o que já tem poupado.'],
    ]),
    Q('guided-02', 'guided', 'money.savings-plan-math', 2, [
      ['Which plan fills the stated gap?', 'You need 80 across four dates. Each contribution is affordable.', ['10 + 10 + 10 + 10', '15 + 15 + 15 + 15', '20 + 20 + 20 + 20'], 'The contributions cover the missing amount by the stated dates.', 'Add the contributions and compare with the gap.'],
      ['¿Qué plan cubre el faltante indicado?', 'Aún faltan 80 y hay cuatro fechas para aportar. Cada aportación propuesta cabe en el presupuesto.', ['10 + 10 + 10 + 10', '15 + 15 + 15 + 15', '20 + 20 + 20 + 20'], 'Las aportaciones cubren el faltante en las fechas indicadas.', 'Suma las aportaciones y compáralas con el faltante.'],
      ['Qual plano cobre a falta informada?', 'Ainda faltam 80 e há quatro datas para contribuir. Cada contribuição proposta cabe no orçamento.', ['10 + 10 + 10 + 10', '15 + 15 + 15 + 15', '20 + 20 + 20 + 20'], 'As contribuições cobrem a falta nas datas informadas.', 'Some as contribuições e compare com o que falta.'],
    ]),
    Q('practice-01', 'practice', 'money.savings-plan-math', 1, [
      ['What remains to be saved?', 'A goal costs 150; 50 is already reserved for it.', ['150', '100', '200'], 'Fund the remaining gap, not the full target again.', 'Keep the existing reserved amount in the calculation.'],
      ['¿Cuánto falta ahorrar?', 'Una meta cuesta 150; ya hay 50 apartados para ella.', ['150', '100', '200'], 'El plan debe cubrir el faltante, no reunir toda la meta otra vez.', 'Incluye el monto ya apartado en el cálculo.'],
      ['Quanto falta poupar?', 'Uma meta custa 150; já há 50 reservados para ela.', ['150', '100', '200'], 'O plano deve cobrir a falta, não reunir toda a meta novamente.', 'Inclua o valor já reservado no cálculo.'],
    ]),
    Q('practice-02', 'practice', 'money.savings-plan-math', 0, [
      ['What makes this plan unworkable?', 'Weekly goal: save 40. Only 20 remains after essentials.', ['You cannot spare 40', 'The goal is not reached yet', 'Saving must wait until month-end'], 'A correct sum is not enough if its contributions cannot fit.', 'Check resources as well as the arithmetic target.'],
      ['¿Qué hace inviable este plan?', 'El plan exige ahorrar 40 por semana. Solo quedan 20 después de pagos necesarios cada semana.', ['La aportación supera la capacidad indicada', 'La meta aún no se alcanza', 'Ahorrar exige esperar al fin de mes'], 'Una suma correcta no basta si las aportaciones no caben.', 'Comprueba los recursos además del objetivo numérico.'],
      ['O que torna este plano inviável?', 'O plano exige 40 semanais; sobram só 20 após gastos necessários.', ['A contribuição supera a capacidade informada', 'A meta ainda não foi alcançada', 'Poupar exige esperar o fim do mês'], 'Uma soma correta não basta se as contribuições não cabem.', 'Confira os recursos além do objetivo numérico.'],
    ]),
    Q('practice-03', 'practice', 'money.savings-plan-math', 2, [
      ['Which change makes it feasible?', 'Affordable contributions fall short by a flexible deadline.', ['Assume extra money arrives', 'Count the same savings twice', 'Extend the date and recalculate'], 'A flexible deadline can allow more affordable contribution periods.', 'Change a stated flexible constraint instead of inventing resources.'],
      ['¿Qué cambio hace viable el plan?', 'La meta opcional tiene fecha flexible. Las aportaciones posibles no la alcanzan para la fecha inicial.', ['Mantener la fecha y suponer más dinero', 'Contar el mismo ahorro dos veces', 'Ampliar el plazo y recalcular'], 'Un plazo flexible puede permitir más aportaciones posibles.', 'Cambia un límite flexible en vez de inventar recursos.'],
      ['Qual mudança poderia viabilizar o plano?', 'A meta opcional tem data flexível. As contribuições possíveis não bastam até a data inicial.', ['Manter a data e supor mais dinheiro', 'Contar a mesma poupança duas vezes', 'Ampliar o prazo e recalcular'], 'Um prazo flexível pode permitir mais contribuições possíveis.', 'Mude um limite flexível em vez de inventar recursos.'],
    ]),
    Q('transfer-01', 'transfer', 'money.savings-plan-math', 1, [
      ['Which contribution plan reaches the goal?', 'Enrollment costs 120; 40 is saved. Four affordable contributions remain.', ['10 + 10 + 10 + 10', '20 + 20 + 20 + 20', '15 + 15 + 15 + 15'], 'The contributions fill the remaining gap before enrollment.', 'Account for existing savings before splitting what remains.'],
      ['¿Qué plan de aportaciones alcanza la meta?', 'Un curso cuesta 120; hay 40 ahorrados. Quedan cuatro aportaciones posibles antes de inscribirse.', ['10 + 10 + 10 + 10', '20 + 20 + 20 + 20', '15 + 15 + 15 + 15'], 'Las aportaciones cubren el faltante antes de la inscripción.', 'Considera lo ya ahorrado antes de repartir lo que falta.'],
      ['Qual plano de contribuições alcança a meta?', 'Um curso custa 120; há 40 poupados. Restam quatro contribuições possíveis antes da inscrição.', ['10 + 10 + 10 + 10', '20 + 20 + 20 + 20', '15 + 15 + 15 + 15'], 'As contribuições cobrem a falta antes da inscrição.', 'Considere o que já foi poupado antes de dividir o que falta.'],
    ]),
  ] }), makeLesson({ number: 17, slug: 'prepare-for-a-surprise', unit, title: ['Prepare for a surprise', 'Prepárate para imprevistos', 'Prepare-se para imprevistos'], skill: 'save.emergency', kc: 'life.saving-for-later', prerequisites: ['plan.priority', 'plan.periodic', 'save.goal'],
  outcome: 'Distinguish an unexpected necessary expense from a known planned cost or optional purchase, and preserve or rebuild a reserve accordingly.',
  misconception: 'Treating all nonmonthly spending as an emergency or regarding use of an emergency reserve for its purpose as failure.', numeracy: 'This lesson classifies purpose and predictability; it does not prescribe an income percentage or a universal reserve amount.',
  relevance: ['Some necessary expenses arrive unexpectedly. A reserve creates room to respond; its amount depends on your circumstances.', 'Algunos gastos necesarios llegan sin aviso. Una reserva da margen para responder; su monto depende de tus circunstancias.', 'Um gasto urgente pode surgir sem aviso. Guardar dinheiro dá tempo para agir; o valor depende da sua vida.'],
  segments: [
    E('example-01', ['Known or unexpected?', '¿Conocido o inesperado?', 'Conhecido ou inesperado?'], ['A renewal with a known date belongs in a planned-cost fund. An unexpected essential repair has a different purpose.', 'Una renovación con fecha conocida pertenece al ahorro para gastos previstos. Una reparación necesaria inesperada tiene otro propósito.', 'Uma conta com data marcada entra no plano. Um conserto urgente que surge sem aviso pede outra reserva.']),
    E('example-02', ['Use, then rebuild', 'Usa y luego reconstruye', 'Use e depois reconstrua'], ['Using the reserve for a real emergency serves its purpose. Revisit affordable contributions afterward; using it was not failure.', 'Usar la reserva para una emergencia real cumple su propósito. Después revisa aportaciones posibles, en vez de verlo como fracaso.', 'Usar a reserva para uma urgência real é seu papel. Depois, faça um plano para repor o que usou.']),
    Q('guided-01', 'guided', 'life.saving-for-later', 1, [
      ['Which situation matches an emergency reserve?', 'Choose the unexpected necessary expense.', ['A known annual renewal', 'A sudden essential pipe repair', 'A planned decorative upgrade'], 'The repair is both necessary and unexpected in this scenario.', 'Check both necessity and whether it was already predictable.'],
      ['¿Qué situación corresponde a la reserva?', 'Elige el gasto necesario e inesperado.', ['Una renovación anual conocida', 'Una reparación urgente de tubería', 'Una mejora decorativa planeada'], 'La reparación es necesaria e inesperada en esta situación.', 'Comprueba la necesidad y si el gasto ya era previsible.'],
      ['Quando usar essa reserva?', 'Escolha o gasto urgente que surgiu sem aviso.', ['Uma renovação anual conhecida', 'Um conserto súbito de cano essencial', 'Uma melhoria decorativa planejada'], 'O conserto é urgente e surgiu sem aviso.', 'Veja se é urgente e se já estava no plano.'],
    ]),
    Q('guided-02', 'guided', 'life.saving-for-later', 0, [
      ['What does the reserve achieve?', 'An unexpected essential repair was paid from money saved for emergencies.', ['The reserve served its purpose', 'Saving never worked', 'Every future expense is covered'], 'A reserve is meant to help with the event it protects against.', 'Separate appropriate use from the need to rebuild afterward.'],
      ['¿Qué muestra usar la reserva aquí?', 'Una reparación necesaria inesperada se pagó con dinero ahorrado para emergencias.', ['La reserva cumplió su propósito', 'Ahorrar nunca funcionó', 'Todo gasto futuro queda cubierto'], 'Una reserva ayuda ante el evento para el que se preparó.', 'Separa el uso adecuado de la necesidad de reconstruirla después.'],
      ['O que mostra usar a reserva aqui?', 'A reserva pagou um conserto urgente que surgiu sem aviso.', ['A reserva cumpriu seu papel', 'Poupar nunca funcionou', 'Todo gasto futuro está coberto'], 'A reserva ajudou no gasto para o qual foi feita.', 'Usar bem a reserva não impede repor o valor depois.'],
    ]),
    Q('practice-01', 'practice', 'life.saving-for-later', 2, [
      ['Which fund matches this cost?', 'An annual inspection has a known price and date.', ['Only an emergency reserve', 'Optional spending with no plan', 'A planned-cost reserve'], 'Known infrequent costs can be prepared separately from emergencies.', 'Infrequent does not automatically mean unpredictable.'],
      ['¿Qué reserva corresponde a este costo?', 'Una revisión anual tiene monto y fecha conocidos con anticipación.', ['Solo la reserva de emergencia', 'Gasto opcional sin plan', 'Ahorro para gastos previstos'], 'Los costos conocidos poco frecuentes pueden prepararse aparte.', 'Poco frecuente no significa automáticamente imprevisible.'],
      ['Qual reserva corresponde a esse custo?', 'Uma revisão anual tem preço e data já marcados.', ['Só a reserva de emergência', 'Gasto opcional sem plano', 'Reserva de gastos previstos'], 'Dá para planejar um gasto conhecido mesmo sem pagar todo mês.', 'Nem todo gasto fora do mês é uma surpresa.'],
    ]),
    Q('practice-02', 'practice', 'life.saving-for-later', 1, [
      ['What changes after spending the reserve?', 'A sale tempts you without an essential need.', ['The reserve becomes larger', 'Less remains for unexpected needs', 'The sale creates an emergency'], 'An optional purchase uses money reserved for another purpose.', 'A limited offer does not change the purpose of the fund.'],
      ['¿Qué cambia si se usa la reserva aquí?', 'Una oferta opcional resulta atractiva, pero no apareció ningún gasto necesario.', ['La reserva aumenta', 'Queda menos para imprevistos', 'La oferta crea una emergencia'], 'Una compra opcional usa dinero reservado para otro propósito.', 'Una oferta limitada no cambia el propósito del fondo.'],
      ['O que muda se usar a reserva aqui?', 'Uma oferta opcional é atraente, mas não apareceu nenhum gasto necessário.', ['A reserva aumenta', 'Resta menos para imprevistos', 'A oferta cria uma emergência'], 'A compra usa dinheiro que tinha outra função.', 'Uma oferta por pouco tempo não muda o papel da reserva.'],
    ]),
    Q('practice-03', 'practice', 'life.saving-for-later', 0, [
      ['How can you rebuild it?', 'After using the reserve, essentials leave little to rebuild it.', ['Plan an affordable contribution', 'Plan unaffordable savings', 'Pretend the reserve is unchanged'], 'Rebuilding starts from current capacity, not an invented surplus.', 'Use the actual remaining resources and revise as circumstances change.'],
      ['¿Qué paso permite reconstruirla?', 'La reserva se usó correctamente. Los pagos necesarios dejan un monto pequeño disponible ahora.', ['Planear una aportación que sí cabe', 'Fijar un monto que no puede caber', 'Suponer que la reserva no cambió'], 'Reconstruir parte de la capacidad actual, no de un sobrante inventado.', 'Usa los recursos reales y ajusta cuando cambien las circunstancias.'],
      ['Como começar a repor a reserva?', 'A reserva foi bem usada. Depois das contas básicas, sobra pouco agora.', ['Planejar uma contribuição que cabe', 'Fixar um valor que não pode caber', 'Supor que a reserva não mudou'], 'O plano deve usar o que de fato sobra agora.', 'Use o que tem e reveja o plano quando houver mudanças.'],
    ]),
    Q('transfer-01', 'transfer', 'life.saving-for-later', 2, [
      ['Which purpose fits this reserve use?', 'Unexpected damage stops your essential work tool. Work requires a repair.', ['A routine decorative upgrade', 'A known annual subscription', 'An unexpected necessary repair'], 'The reserve addresses an unexpected interruption of an essential activity.', 'Classify the consequence and predictability, not the object alone.'],
      ['¿Qué propósito corresponde a este uso?', 'Un daño inesperado detiene la única herramienta necesaria para trabajar. Hay que repararla para retomar el trabajo.', ['Una mejora decorativa habitual', 'Una suscripción anual conocida', 'Una reparación necesaria inesperada'], 'La reserva atiende una interrupción inesperada de una actividad necesaria.', 'Clasifica la consecuencia y previsibilidad, no solo el objeto.'],
      ['Que uso é esse?', 'Um dano inesperado para a única ferramenta necessária para trabalhar. É preciso consertá-la para retomar o trabalho.', ['Uma melhoria decorativa habitual', 'Uma assinatura anual conhecida', 'Um conserto urgente sem aviso'], 'A reserva ajuda a retomar o trabalho após um dano súbito.', 'Veja o efeito e se era previsto, não só o objeto.'],
    ]),
  ] })];
