import { makeLesson, examples as E, choice as Q } from './assemble.mjs';
const unit = 'fe-solid-05-understand-borrowing';
export const plans = [makeLesson({ number: 20, slug: 'borrowing-is-an-obligation', unit, title: ['Borrowing creates an obligation', 'Pedir prestado crea una obligación', 'Pegar emprestado cria obrigação'], skill: 'debt.obligation', kc: 'life.banks-and-accounts', prerequisites: ['cash.balance', 'cash.dates', 'plan.revise'],
  outcome: 'Distinguish borrowed money from earned income and identify the future repayment obligation created by using credit.',
  misconception: 'Treating an available credit limit or borrowed deposit as extra income with no future claim on resources.', numeracy: 'Use money direction and future payment dates; this lesson introduces the obligation before interest calculations.',
  relevance: ['Borrowing can make money available now, but creates a payment obligation later. Keep both sides in the plan.', 'Pedir prestado puede dar dinero hoy, pero crea un pago futuro. Incluye ambos lados en el plan.', 'Pegar emprestado pode dar dinheiro agora, mas cria um pagamento futuro. Inclua os dois lados no plano.'],
  segments: [
    E('example-01', ['Cash and obligation', 'Dinero y obligación', 'Dinheiro e obrigação'], ['Ana receives a loan of 100. Her usable money rises by 100, but she also owes repayment under the agreement.', 'Ana recibe un préstamo de 100. Su dinero utilizable aumenta 100, pero también debe pagar según el acuerdo.', 'Ana recebe um empréstimo de 100. Seu dinheiro utilizável aumenta 100, mas também deve pagar conforme o acordo.']),
    E('example-02', ['A limit is not income', 'Un límite no es ingreso', 'Um limite não é renda'], ['A credit limit states how much may be borrowed. Using it creates debt; it is not earned income.', 'Un límite de crédito indica cuánto se puede pedir según sus condiciones. Usarlo crea deuda; no es ingreso ganado.', 'Um limite de crédito indica quanto se pode pegar conforme suas condições. Usá-lo cria dívida; não é renda ganha.']),
    Q('guided-01', 'guided', 'life.banks-and-accounts', 1, [
      ['Which record describes the loan?', 'Ana receives 100 that must be repaid under a loan agreement.', ['Income with no repayment', 'Usable cash plus an obligation', 'Only money leaving immediately'], 'The receipt and the repayment obligation exist together.', 'Track both what arrived and what the agreement requires later.'],
      ['¿Qué registro describe el préstamo?', 'Ana recibe 100 que debe devolver según un acuerdo de préstamo.', ['Ingreso sin devolución', 'Dinero utilizable y una obligación', 'Solo dinero que sale de inmediato'], 'La entrada y la obligación de pago existen juntas.', 'Registra lo recibido y lo que el acuerdo exige después.'],
      ['Qual registro descreve o empréstimo?', 'Ana recebe 100 que deve devolver conforme um acordo de empréstimo.', ['Renda sem devolução', 'Dinheiro utilizável e uma obrigação', 'Só dinheiro saindo imediatamente'], 'A entrada e a obrigação de pagamento existem juntas.', 'Registre o recebido e o que o acordo exige depois.'],
    ]),
    Q('guided-02', 'guided', 'life.banks-and-accounts', 0, [
      ['What is an unused credit limit?', 'A card permits borrowing under its stated limit.', ['Permission to borrow, not earnings', 'A payment already received for work', 'Savings already owned without repayment'], 'Credit availability describes borrowing capacity, not income.', 'Check whether using the amount creates a debt.'],
      ['¿Qué representa un límite de crédito sin usar?', 'Una tarjeta permite pedir hasta su límite según sus condiciones.', ['Capacidad de pedir, no dinero ganado', 'Un pago ya recibido por trabajar', 'Ahorro propio sin devolución'], 'El crédito disponible describe capacidad de pedir, no ingreso.', 'Comprueba si usar el monto crea una deuda.'],
      ['O que representa um limite de crédito não usado?', 'Um cartão permite tomar até seu limite conforme suas condições.', ['Capacidade de tomar, não dinheiro ganho', 'Um pagamento já recebido por trabalho', 'Poupança própria sem devolução'], 'O crédito disponível descreve capacidade de tomar, não renda.', 'Confira se usar o valor cria uma dívida.'],
    ]),
    Q('practice-01', 'practice', 'life.banks-and-accounts', 2, [
      ['Which future item belongs in the plan?', 'You buy a necessary tool using a loan.', ['Only the tool value', 'Only the cash received', 'The required repayment dates and amounts'], 'A useful purchase still leaves its financing obligation.', 'The purpose of a purchase does not cancel its repayment terms.'],
      ['¿Qué dato futuro pertenece al plan?', 'Compras una herramienta necesaria mediante un préstamo.', ['Solo el valor de la herramienta', 'Solo el dinero recibido', 'Fechas y montos obligatorios de pago'], 'Una compra útil conserva su obligación de financiamiento.', 'El propósito de la compra no elimina sus condiciones de pago.'],
      ['Qual dado futuro pertence ao plano?', 'Você compra uma ferramenta necessária usando um empréstimo.', ['Só o valor da ferramenta', 'Só o dinheiro recebido', 'Datas e valores obrigatórios de pagamento'], 'Uma compra útil mantém sua obrigação de financiamento.', 'O propósito da compra não elimina suas condições de pagamento.'],
    ]),
    Q('practice-02', 'practice', 'life.banks-and-accounts', 0, [
      ['Which receipt creates no loan debt?', 'Compare earned pay with a loan requiring repayment.', ['The completed payment for work', 'The loan deposit', 'Both are loans because money arrives'], 'Receiving money can mean different things depending on its source and terms.', 'Ask whether this receipt must be repaid under an agreement.'],
      ['¿Qué entrada no crea esa deuda de préstamo?', 'Compara un pago por trabajo realizado con un préstamo que exige devolución.', ['El pago por trabajo realizado', 'El depósito del préstamo', 'Ambos son préstamos porque entra dinero'], 'Recibir dinero tiene distinto significado según su origen y condiciones.', 'Pregunta si esta entrada debe devolverse según un acuerdo.'],
      ['Qual entrada não cria essa dívida de empréstimo?', 'Compare um pagamento por trabalho feito com um empréstimo que exige devolução.', ['O pagamento por trabalho feito', 'O depósito do empréstimo', 'Ambos são empréstimos porque entra dinheiro'], 'Receber dinheiro tem significados diferentes conforme a origem e condições.', 'Pergunte se essa entrada deve ser devolvida conforme um acordo.'],
    ]),
    Q('practice-03', 'practice', 'life.banks-and-accounts', 1, [
      ['What is missing before deciding?', 'An offer omits its repayment schedule.', ['Only the amount received today', 'What must be paid and when', 'Whether the amount appears attractive'], 'The future obligation cannot be planned without its terms.', 'A cash receipt alone does not describe the whole agreement.'],
      ['¿Qué falta antes de decidir?', 'Una oferta anuncia dinero hoy, pero no muestra el calendario de devolución.', ['Solo el monto recibido hoy', 'Qué se debe pagar y cuándo', 'Si el monto parece atractivo'], 'Sin condiciones no se puede planear la obligación futura.', 'Una entrada de dinero no describe todo el acuerdo.'],
      ['O que falta antes de decidir?', 'Uma oferta anuncia dinheiro hoje, mas não mostra o calendário de devolução.', ['Só o valor recebido hoje', 'O que deve ser pago e quando', 'Se o valor parece atraente'], 'Sem condições não se pode planejar a obrigação futura.', 'Uma entrada de dinheiro não descreve todo o acordo.'],
    ]),
    Q('transfer-01', 'transfer', 'life.banks-and-accounts', 2, [
      ['What happens when you accept?', 'Take a device now; pay agreed installments later.', ['The later payments become income', 'No obligation exists until the last date', 'You create future payment commitments'], 'Receiving the item now does not remove the later payment commitments.', 'The borrowing arrangement may appear at a checkout rather than a bank.'],
      ['¿Qué ocurre si aceptas estas cuotas?', 'Un vendedor entrega un aparato hoy y permite pagar cuotas acordadas después.', ['Los pagos futuros se vuelven ingreso', 'No hay obligación hasta la última fecha', 'Creas compromisos futuros de pago'], 'Recibir el aparato hoy no elimina los pagos posteriores.', 'El financiamiento puede aparecer en la caja, no solo en un banco.'],
      ['O que ocorre ao aceitar estas parcelas?', 'Um vendedor entrega um aparelho agora e permite pagar parcelas combinadas depois.', ['Os pagamentos futuros viram renda', 'Não há obrigação até a última data', 'Você cria compromissos futuros de pagamento'], 'Receber o aparelho agora não elimina os pagamentos posteriores.', 'O financiamento pode aparecer no caixa, não só em um banco.'],
    ]),
  ] }), makeLesson({ number: 21, slug: 'count-the-full-repayment', unit, title: ['Count the full repayment', 'Cuenta el pago completo', 'Conte o pagamento completo'], skill: 'debt.total-cost', kc: 'life.banks-and-accounts', prerequisites: ['debt.obligation', 'price.final', 'cash.dates'],
  outcome: 'Add all required installments and fees, distinguish total repayment from borrowing cost, and compare the same received amount and term.',
  misconception: 'Using the smallest installment as proof of the cheapest loan while ignoring the number of payments or mandatory fees.', numeracy: 'Repeated addition computes total installments; subtract received principal to obtain borrowing cost in fully specified examples.',
  relevance: ['A small installment can hide many payments. Count the complete obligation before comparing financing offers.', 'Una cuota pequeña puede esconder muchos pagos. Cuenta la obligación completa antes de comparar ofertas de financiamiento.', 'Uma parcela pequena pode esconder muitos pagamentos. Conte a obrigação completa antes de comparar ofertas de financiamento.'],
  segments: [
    E('example-01', ['Add every required payment', 'Suma cada pago obligatorio', 'Some cada pagamento obrigatório'], ['A fictional loan gives 100 now and requires four payments of 30. Repayment totals 30 + 30 + 30 + 30 = 120.', 'Un préstamo ficticio entrega 100 hoy y exige cuatro pagos de 30. Se devuelve 30 + 30 + 30 + 30 = 120.', 'Um empréstimo fictício entrega 100 agora e exige quatro pagamentos de 30. Devolve-se 30 + 30 + 30 + 30 = 120.']),
    E('example-02', ['Separate repayment and cost', 'Separa devolución y costo', 'Separe devolução e custo'], ['With no fees, repaying 120 after receiving 100 means a cost of 20. Full repayment includes the borrowed amount.', 'Sin otros cargos, devolver 120 tras recibir 100 implica un costo de 20. La devolución completa no es solo el costo.', 'Sem outras cobranças, devolver 120 após receber 100 implica um custo de 20. A devolução completa não é só o custo.']),
    Q('guided-01', 'guided', 'life.banks-and-accounts', 1, [
      ['What is the total repayment?', 'The agreement requires 4 payments of 30 and no other fees.', ['30', '120', '100'], 'The total includes every required installment.', 'Add the whole schedule, not only one installment.'],
      ['¿Cuál es la devolución total?', 'El acuerdo exige 4 pagos de 30 y ningún otro cargo.', ['30', '120', '100'], 'El total incluye cada cuota obligatoria.', 'Suma todo el calendario, no solo una cuota.'],
      ['Qual é a devolução total?', 'O acordo exige 4 pagamentos de 30 e nenhuma outra cobrança.', ['30', '120', '100'], 'O total inclui cada parcela obrigatória.', 'Some todo o calendário, não só uma parcela.'],
    ]),
    Q('guided-02', 'guided', 'life.banks-and-accounts', 0, [
      ['What is the borrowing cost here?', 'You received 100 and must repay 120 in total. There are no other charges.', ['20', '100', '120'], 'Borrowing cost is the extra amount above what was received.', 'Separate returning the received money from paying for its use.'],
      ['¿Cuál es el costo de pedir prestado aquí?', 'Recibiste 100 y debes devolver 120 en total. No hay otros cargos.', ['20', '100', '120'], 'El costo es el monto adicional a lo recibido.', 'Separa devolver lo recibido de pagar por su uso.'],
      ['Qual é o custo de pegar emprestado aqui?', 'Você recebeu 100 e deve devolver 120 no total. Não há outras cobranças.', ['20', '100', '120'], 'O custo é o valor adicional ao que foi recebido.', 'Separe devolver o recebido de pagar pelo seu uso.'],
    ]),
    Q('practice-01', 'practice', 'life.banks-and-accounts', 2, [
      ['Which repayment totals less?', 'Same loan, no fees: A repays 3 × 40; B repays 4 × 35.', ['B has smaller payments', 'Equal totals', 'A totals less'], 'The number of installments changes the total comparison.', 'Compare all payments rather than the smallest individual payment.'],
      ['¿Cuál suma menos por el mismo monto recibido?', 'A exige tres pagos de 40; B exige cuatro pagos de 35. No hay otros cargos.', ['B, porque cada cuota es menor', 'Ambos suman lo mismo', 'A, al contar todos los pagos'], 'El número de cuotas cambia la comparación de totales.', 'Compara todos los pagos, no la cuota individual más pequeña.'],
      ['Qual soma menos pelo mesmo valor recebido?', 'A exige três pagamentos de 40; B exige quatro pagamentos de 35. Não há outras cobranças.', ['B, porque cada parcela é menor', 'Ambos somam o mesmo', 'A, ao contar todos os pagamentos'], 'O número de parcelas muda a comparação dos totais.', 'Compare todos os pagamentos, não a menor parcela individual.'],
    ]),
    Q('practice-02', 'practice', 'life.banks-and-accounts', 0, [
      ['What is the full required total?', 'Installments sum to 120, and a separate mandatory fee of 10 must also be paid.', ['130', '120', '10'], 'A separately required fee is part of the complete payment obligation.', 'Check whether a stated fee is additional or already included.'],
      ['¿Cuál es el total obligatorio completo?', 'Las cuotas suman 120 y además debe pagarse un cargo obligatorio de 10.', ['130', '120', '10'], 'Un cargo obligatorio adicional forma parte del pago completo.', 'Comprueba si el cargo es adicional o ya está incluido.'],
      ['Qual é o total obrigatório completo?', 'As parcelas somam 120 e também deve ser paga uma cobrança obrigatória de 10.', ['130', '120', '10'], 'Uma cobrança obrigatória adicional faz parte do pagamento completo.', 'Confira se a cobrança é adicional ou já está incluída.'],
    ]),
    Q('practice-03', 'practice', 'life.banks-and-accounts', 1, [
      ['Is the cheaper plan affordable?', 'The payment falls due before enough money arrives.', ['Yes, cost alone matters', 'No, check payment timing', 'Yes, later income changes the deadline'], 'Cost and ability to pay on the required dates are different checks.', 'Compare the schedule with money available by each deadline.'],
      ['¿El menor total demuestra que puedes pagarlo?', 'El menor total exige un pago antes de que llegue suficiente dinero utilizable.', ['Sí, el costo es el único límite', 'No, también deben caber las fechas', 'Sí, el ingreso posterior cambia el plazo'], 'El costo y poder pagar en las fechas exigidas son comprobaciones distintas.', 'Compara el calendario con el dinero disponible para cada vencimiento.'],
      ['O menor total prova que pode pagar?', 'O menor total exige um pagamento antes de chegar dinheiro utilizável suficiente.', ['Sim, o custo é o único limite', 'Não, as datas também devem caber', 'Sim, a renda posterior muda o prazo'], 'O custo e poder pagar nas datas exigidas são verificações diferentes.', 'Compare o calendário com o dinheiro disponível em cada vencimento.'],
    ]),
    Q('transfer-01', 'transfer', 'life.banks-and-accounts', 2, [
      ['What is the extra financing cost?', 'An identical item costs 200 paid now. Financing requires 4 payments of 60, with no other fees.', ['60', '240', '40'], 'Extra cost is the financed total minus the cash price.', 'Add every installment, then compare with the stated cash price.'],
      ['¿Cuál es el costo extra del financiamiento?', 'Un artículo idéntico cuesta 200 al contado. Financiarlo exige 4 pagos de 60, sin otros cargos.', ['60', '240', '40'], 'El costo extra es el total financiado menos el precio al contado.', 'Suma cada cuota y compara con el precio al contado indicado.'],
      ['Qual é o custo extra do financiamento?', 'Um item idêntico custa 200 à vista. Financiá-lo exige 4 pagamentos de 60, sem outras cobranças.', ['60', '240', '40'], 'O custo extra é o total financiado menos o preço à vista.', 'Some cada parcela e compare com o preço à vista informado.'],
    ]),
  ] })];
