// Generated by agent/tools/teaching-visual-coverage.mjs (Appendix P Part 8). Do not edit by hand.
export const TEACHING_VISUAL_COVERAGE = {
  "generated_at": "2026-09-28",
  "tap_alternative": {
    "drag_interactions": 2,
    "with_alternative": 2,
    "share": 1,
    "missing": []
  },
  "locale_rendering": {
    "kinds": 48,
    "covered": 48,
    "share": 1,
    "missing": []
  }
} as const;
