import { z } from 'zod';

/*
 * Canonical source of the v2 segment families added by the first-release
 * catalog (GAP-FIX-R1 learning, B.7 / Appendix P Part 8, B.8, B.9, B.11,
 * B.18). Core's contract (v2LessonDocument.ts) composes these schemas; the
 * browser copy (frontend/src/rebuild/learning/v2SegmentFamilies.generated.ts)
 * is generated byte-for-byte by agent/tools/sync-v2-segment-families.mjs and
 * `npm run spec:check` fails on drift, the same posture as the scorer.
 *
 * Every payload here is answerless: which card must be flipped, which region
 * or bin an item belongs to, which message is a scam, the path through a
 * flowchart, the amount to make and the acceptable story choice all live in
 * Core's private rubric (`V2_FAMILY_RUBRICS`), never in the document.
 *
 * This module must stay self-contained (zod only): it is copied verbatim.
 */

export const V2_ID_PATTERN = /^[a-z0-9][a-z0-9._:-]{2,100}$/;
const id = z.string().regex(V2_ID_PATTERN);
const positive = z.number().int().positive().safe();
const label = (max: number) => z.string().trim().min(1).max(max);
const option = z.object({ id, label: label(80) }).strict();

/**
 * Optional fields every v2 segment may carry (all three copies):
 * - `help`: up to two ladder steps shown on request, one speech-plate turn
 *   each (Bible 08 §11, Appendix A Part 2 "help available on request").
 * - `item_role`: practice or transfer (Appendix C 1.1 transfer success).
 * - `knowledge_component_id`: the KC this item evidences; it must be one of
 *   the document's `knowledge_component_ids`.
 */
export const v2SegmentExtras = {
  help: z.array(label(160)).min(1).max(2).optional(),
  item_role: z.enum(['practice', 'transfer']).optional(),
  knowledge_component_id: id.optional(),
};

function uniqueIds(values: ReadonlyArray<{ id: string }>): boolean {
  return new Set(values.map((value) => value.id)).size === values.length;
}

/* ── Logic (Appendix P Part 8: L1, L5, L6, L10, L12) ─────────────────────── */

/** L1: a conditional rule and the cards that could break it; the learner flips the ones that must be checked. */
export const ruleCheckerPayload = z.object({
  rule: label(160),
  cards: z.array(z.object({ id, face: label(24) }).strict()).min(3).max(6),
}).strict().refine((value) => uniqueIds(value.cards), 'Invalid rule cards');

/** L5: two sets drawn as an Euler diagram in a declared relation; items are placed in regions. */
export const EULER_REGIONS = ['first', 'second', 'both', 'neither'] as const;
export const eulerPayload = z.object({
  relation: z.enum(['overlap', 'subset', 'disjoint']),
  sets: z.tuple([option, option]),
  items: z.array(option).min(2).max(6),
}).strict().refine((value) => uniqueIds([...value.sets, ...value.items]), 'Invalid Euler items');

/** L6 / $9: a steppable flowchart or decision tree walked once per scenario. */
const flowNode = z.object({
  id, kind: z.enum(['question', 'outcome']), label: label(80), yes: id.optional(), no: id.optional(),
}).strict();
export const flowchartPayload = z.object({
  start: id,
  nodes: z.array(flowNode).min(3).max(12),
  scenarios: z.array(option).min(1).max(3),
}).strict().refine((value) => validFlowchart(value), 'Invalid flowchart');

export type FlowchartPayload = z.infer<typeof flowchartPayload>;

function validFlowchart(value: { start: string; nodes: Array<{ id: string; kind: string; yes?: string; no?: string }>; scenarios: Array<{ id: string }> }): boolean {
  if (!uniqueIds(value.nodes) || !uniqueIds(value.scenarios)) return false;
  const byId = new Map(value.nodes.map((node) => [node.id, node]));
  const start = byId.get(value.start);
  if (!start || start.kind !== 'question') return false;
  for (const node of value.nodes) {
    if (node.kind === 'question' && (!node.yes || !node.no || !byId.has(node.yes) || !byId.has(node.no) || node.yes === node.no)) return false;
    if (node.kind === 'outcome' && (node.yes !== undefined || node.no !== undefined)) return false;
  }
  // Acyclic and every node reachable from the start: a walk always ends.
  const state = new Map<string, 'open' | 'done'>();
  const visit = (nodeId: string): boolean => {
    const mark = state.get(nodeId);
    if (mark === 'open') return false;
    if (mark === 'done') return true;
    state.set(nodeId, 'open');
    const node = byId.get(nodeId)!;
    const ok = node.kind === 'outcome' || (visit(node.yes!) && visit(node.no!));
    state.set(nodeId, 'done');
    return ok;
  };
  return visit(value.start) && state.size === value.nodes.length;
}

/** L10 / $10: sort items into bins by a rule and say why; one bin is "it depends". */
export const sortBinsPayload = z.object({
  bins: z.array(option).min(2).max(4),
  depends_bin_id: id,
  items: z.array(option).min(2).max(8),
  reasons: z.array(option).min(2).max(5),
}).strict().refine((value) => uniqueIds([...value.bins, ...value.items, ...value.reasons])
  && value.bins.some((bin) => bin.id === value.depends_bin_id), 'Invalid sort bins');

/** L12 / $11: messages to classify; genuine messages are always in the set (enforced by the rubric). */
export const messageListPayload = z.object({
  messages: z.array(z.object({ id, sender: label(40), text: label(200) }).strict()).min(3).max(8),
}).strict().refine((value) => uniqueIds(value.messages), 'Invalid messages');

/* ── Money ($1, $2) ───────────────────────────────────────────────────────── */

const denomination = z.object({ value_minor: positive.max(100_000), kind: z.enum(['coin', 'bill']), available: positive.max(20) }).strict();
const denominations = z.array(denomination).min(2).max(8)
  .refine((values) => values.every((value, index) => index === 0 || value.value_minor < values[index - 1]!.value_minor), 'Denominations must be strictly descending');

/** $1: build an amount from a tray of coins and bills (integer minor units). */
export const coinTrayPayload = z.object({ currency: z.enum(['coins', 'local']), denominations }).strict();

/** $2: make change; price and payment are public, the change owed is private. */
export const makingChangePayload = z.object({
  currency: z.enum(['coins', 'local']), denominations,
  price_minor: positive.max(1_000_000), paid_minor: positive.max(1_000_000),
}).strict().refine((value) => value.paid_minor > value.price_minor, 'Payment must exceed the price');

/* ── Story and Mentor voice (B.8, B.9, B.11, B.18) ────────────────────────── */

export const storyBranchPayload = z.object({ scene: label(300), options: z.array(option).min(2).max(3) }).strict()
  .refine((value) => uniqueIds(value.options), 'Invalid story options');
export const dialogueChoicePayload = z.object({ speaker: label(40), line: label(200), replies: z.array(option).min(2).max(3) }).strict()
  .refine((value) => uniqueIds(value.replies), 'Invalid dialogue replies');
export const wouldYouRatherPayload = z.object({ options: z.tuple([option, option]) }).strict()
  .refine((value) => value.options[0].id !== value.options[1].id, 'Invalid would-you-rather options');

/**
 * B.18: the narration channel. `text_only` voices nothing; `differentiated`
 * carries a script that says more than the on-screen line, so Forge gate 11
 * can prove the plate is a caption and not a transcript.
 */
export const narrationChannel = z.object({
  mode: z.enum(['text_only', 'differentiated']),
  script: label(400).optional(),
  audio_ref: id.optional(),
}).strict().refine((value) => value.mode === 'text_only' ? value.script === undefined && value.audio_ref === undefined : value.script !== undefined,
  'Invalid narration channel');

/** B.8: the learner's Mentor introduces, bridges or wraps a lesson in one speech-plate turn. The character is always the learner's own (OD-19). */
export const mentorTurnPayload = z.object({
  role: z.enum(['intro', 'transition', 'wrap']),
  line: label(160),
  narration: narrationChannel.optional(),
}).strict();

/** B.11: a flawed, human decision voiced by the Mentor, then its recovery. Character-agnostic lines. */
export const mentorEpisodePayload = z.object({
  setup: label(160), misjudgment: label(160), recovery: label(160),
  narration: narrationChannel.optional(),
}).strict();

/* ── Segments ─────────────────────────────────────────────────────────────── */

const base = { id, prompt: z.string().trim().min(1).max(500), ...v2SegmentExtras };
const server = z.literal('server');
const visual = <T extends string>(type: T) => z.object({ type: z.literal(type) }).strict();

export const v2FamilySegments = [
  z.object({ ...base, type: z.literal('logic.rule-checker.v2'), grading: server, visual: visual('rule-cards'), payload: ruleCheckerPayload }).strict(),
  z.object({ ...base, type: z.literal('logic.euler.v2'), grading: server, visual: visual('euler'), payload: eulerPayload }).strict(),
  z.object({ ...base, type: z.literal('logic.flowchart.v2'), grading: server, visual: visual('flowchart'), payload: flowchartPayload }).strict(),
  z.object({ ...base, type: z.literal('money.spend-decision.v2'), grading: server, visual: visual('decision-tree'), payload: flowchartPayload }).strict(),
  z.object({ ...base, type: z.literal('logic.sort-by-rule.v2'), grading: server, visual: visual('sort-bins'), payload: sortBinsPayload }).strict(),
  z.object({ ...base, type: z.literal('money.needs-wants.v2'), grading: server, visual: visual('sort-bins'), payload: sortBinsPayload }).strict(),
  z.object({ ...base, type: z.literal('logic.scam-spotter.v2'), grading: server, visual: visual('message-list'), payload: messageListPayload }).strict(),
  z.object({ ...base, type: z.literal('money.scam-check.v2'), grading: server, visual: visual('message-list'), payload: messageListPayload }).strict(),
  z.object({ ...base, type: z.literal('money.coin-tray.v2'), grading: server, visual: visual('coin-tray'), payload: coinTrayPayload }).strict(),
  z.object({ ...base, type: z.literal('money.making-change.v2'), grading: server, visual: visual('coin-tray'), payload: makingChangePayload }).strict(),
  z.object({ ...base, type: z.literal('story.branch.v2'), grading: server, visual: visual('story-scene'), payload: storyBranchPayload }).strict(),
  z.object({ ...base, type: z.literal('story.dialogue-choice.v2'), grading: server, visual: visual('dialogue'), payload: dialogueChoicePayload }).strict(),
  z.object({ ...base, type: z.literal('story.would-you-rather.v2'), grading: server, visual: visual('would-you-rather'), payload: wouldYouRatherPayload }).strict(),
  z.object({ ...base, type: z.literal('voice.mentor-turn.v2'), grading: z.literal('none'), visual: visual('speech-plate'), payload: mentorTurnPayload }).strict(),
  z.object({ ...base, type: z.literal('voice.mentor-episode.v2'), grading: z.literal('none'), visual: visual('speech-plate'), payload: mentorEpisodePayload }).strict(),
] as const;

export type V2FamilySegment = z.infer<(typeof v2FamilySegments)[number]>;
export type V2FamilyType = V2FamilySegment['type'];

/** The segment kinds whose choice is a story decision for the B.9 journal. */
export const V2_STORY_TYPES = ['story.branch.v2', 'story.dialogue-choice.v2', 'story.would-you-rather.v2'] as const;

/* ── Private rubrics (Core only; the browser never receives them) ─────────── */

const ids = (min: number, max: number) => z.array(id).min(min).max(max);
export const V2_FAMILY_RUBRICS = {
  'logic.rule-checker.v2': z.object({ must_flip_ids: ids(1, 5) }).strict(),
  'logic.euler.v2': z.object({ regions: z.record(id, z.enum(EULER_REGIONS)) }).strict(),
  'logic.flowchart.v2': z.object({ paths: z.record(id, ids(2, 12)) }).strict(),
  'money.spend-decision.v2': z.object({ paths: z.record(id, ids(2, 12)) }).strict(),
  'logic.sort-by-rule.v2': z.object({ accepted: z.record(id, z.array(z.object({ bin: id, reason: id }).strict()).min(1).max(4)) }).strict(),
  'money.needs-wants.v2': z.object({ accepted: z.record(id, z.array(z.object({ bin: id, reason: id }).strict()).min(1).max(4)) }).strict(),
  'logic.scam-spotter.v2': z.object({ scam_ids: ids(1, 7) }).strict(),
  'money.scam-check.v2': z.object({ scam_ids: ids(1, 7) }).strict(),
  'money.coin-tray.v2': z.object({ target_minor: positive.max(1_000_000), fewest: z.boolean() }).strict(),
  'money.making-change.v2': z.object({ change_minor: positive.max(1_000_000) }).strict(),
  'story.branch.v2': z.object({ acceptable_choice_ids: ids(1, 3) }).strict(),
  'story.dialogue-choice.v2': z.object({ acceptable_choice_ids: ids(1, 3) }).strict(),
  'story.would-you-rather.v2': z.object({ acceptable_choice_ids: ids(1, 2) }).strict(),
} as const;


/**
 * The semantic payload the canonical scorer receives for a family segment:
 * structure only, never labels or copy.
 */
export function v2FamilyScorerPayload(segment: V2FamilySegment): Record<string, unknown> {
  switch (segment.type) {
    case 'logic.rule-checker.v2': return { cardIds: segment.payload.cards.map((card) => card.id) };
    case 'logic.euler.v2': return { relation: segment.payload.relation, itemIds: segment.payload.items.map((item) => item.id) };
    case 'logic.flowchart.v2':
    case 'money.spend-decision.v2': return {
      start: segment.payload.start,
      nodes: segment.payload.nodes.map((node) => node.kind === 'question' ? { id: node.id, yes: node.yes, no: node.no } : { id: node.id }),
      scenarioIds: segment.payload.scenarios.map((scenario) => scenario.id),
    };
    case 'logic.sort-by-rule.v2':
    case 'money.needs-wants.v2': return {
      binIds: segment.payload.bins.map((bin) => bin.id), itemIds: segment.payload.items.map((item) => item.id),
      reasonIds: segment.payload.reasons.map((reason) => reason.id),
    };
    case 'logic.scam-spotter.v2':
    case 'money.scam-check.v2': return { messageIds: segment.payload.messages.map((message) => message.id) };
    case 'money.coin-tray.v2': return { denominations: segment.payload.denominations.map((d) => ({ value: d.value_minor, available: d.available })) };
    case 'money.making-change.v2': return {
      denominations: segment.payload.denominations.map((d) => ({ value: d.value_minor, available: d.available })),
      price: segment.payload.price_minor, paid: segment.payload.paid_minor,
    };
    case 'story.branch.v2': return { choiceIds: segment.payload.options.map((item) => item.id) };
    case 'story.dialogue-choice.v2': return { choiceIds: segment.payload.replies.map((item) => item.id) };
    case 'story.would-you-rather.v2': return { choiceIds: segment.payload.options.map((item) => item.id) };
    case 'voice.mentor-turn.v2':
    case 'voice.mentor-episode.v2': return {};
  }
}

/** A well-formed sample response the contract validator scores against each rubric (never 'invalid'). */
export function v2FamilySampleResponse(segment: V2FamilySegment): unknown {
  switch (segment.type) {
    case 'logic.rule-checker.v2': return { flipped: [segment.payload.cards[0]!.id] };
    case 'logic.euler.v2': return { placements: Object.fromEntries(segment.payload.items.map((item) => [item.id, 'neither'])) };
    case 'logic.flowchart.v2':
    case 'money.spend-decision.v2': {
      const byId = new Map(segment.payload.nodes.map((node) => [node.id, node]));
      const path = [segment.payload.start];
      let node = byId.get(segment.payload.start);
      while (node && node.kind === 'question') { node = byId.get(node.yes!); if (node) path.push(node.id); }
      return { paths: Object.fromEntries(segment.payload.scenarios.map((scenario) => [scenario.id, path])) };
    }
    case 'logic.sort-by-rule.v2':
    case 'money.needs-wants.v2': return { placements: Object.fromEntries(segment.payload.items.map((item) => [item.id,
      { bin: segment.payload.bins[0]!.id, reason: segment.payload.reasons[0]!.id }])) };
    case 'logic.scam-spotter.v2':
    case 'money.scam-check.v2': return { flagged: [] };
    case 'money.coin-tray.v2':
    case 'money.making-change.v2': return { counts: Object.fromEntries(segment.payload.denominations.map((d) => [String(d.value_minor), 0])) };
    case 'story.branch.v2': return { choice: segment.payload.options[0]!.id };
    case 'story.dialogue-choice.v2': return { choice: segment.payload.replies[0]!.id };
    case 'story.would-you-rather.v2': return { choice: segment.payload.options[0].id };
    case 'voice.mentor-turn.v2':
    case 'voice.mentor-episode.v2': return null;
  }
}
