/* Canonical pure scorer source. Its browser copy is generated by sync-v2-visual-scorer.mjs. */
export type V2VisualKind = 'money.allocation.v2' | 'math.number-line.whole.v2' | 'math.number-line.fraction.v2' | 'math.fraction-area.v2' | 'math.bar-model.structure.v2' | 'math.bar-model.answer.v2' | 'math.schema-diagram.structure.v2' | 'math.schema-diagram.slots.v2' | 'math.schema-diagram.answer.v2' | 'math.worked-example.v2' | 'math.function-machine.v2' | 'math.cpa-count.v2' | 'reasoning.decide-justify.v2'
  | 'math.place-value.v2' | 'math.ratio-table.v2' | 'visual.percent-grid.v2' | 'visual.growth-comparison.v2' | 'visual.tax-bracket.v2' | 'logic.savings-rule.v2' | 'visual.goal-bullet.v2' | 'money.running-ledger.v2'
  | 'logic.rule-checker.v2' | 'logic.euler.v2' | 'logic.flowchart.v2' | 'money.spend-decision.v2' | 'logic.sort-by-rule.v2' | 'money.needs-wants.v2' | 'logic.scam-spotter.v2' | 'money.scam-check.v2'
  | 'money.coin-tray.v2' | 'money.making-change.v2' | 'story.branch.v2' | 'story.dialogue-choice.v2' | 'story.would-you-rather.v2';
export type V2VisualVerdict = 'invalid' | 'valid' | 'review' | 'met';
/** B.12 (Law 4): the quality of the reason a learner gave, graded apart from the decision. */
export type V2JudgmentQuality = 'sound' | 'partial' | 'unsupported';

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function fields(value: unknown, names: readonly string[]): value is Record<string, unknown> {
  return record(value) && Object.keys(value).length === names.length && names.every((name) => Object.hasOwn(value, name));
}

function whole(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value);
}

/** A missing rubric checks only the semantic response; the browser never receives hidden answers. */
export function scoreV2Visual(kind: V2VisualKind, payload: unknown, response: unknown, rubric?: unknown): V2VisualVerdict {
  switch (kind) {
    case 'money.allocation.v2': {
      if (!fields(payload, ['total', 'step']) || !whole(payload.total) || payload.total <= 0
        || !whole(payload.step) || payload.step <= 0 || payload.total % payload.step !== 0
        || !fields(response, ['save', 'spend', 'share'])) return 'invalid';
      for (const pocket of ['save', 'spend', 'share']) {
        const value = response[pocket];
        if (!whole(value) || value < 0 || value > payload.total || value % payload.step !== 0) return 'invalid';
      }
      if (response.save as number + (response.spend as number) + (response.share as number) !== payload.total) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['minimumSave']) || !whole(rubric.minimumSave)
        || rubric.minimumSave < 0 || rubric.minimumSave > payload.total || rubric.minimumSave % payload.step !== 0) return 'invalid';
      return (response.save as number) >= rubric.minimumSave ? 'met' : 'review';
    }
    case 'math.number-line.whole.v2': {
      if (!fields(payload, ['minimum', 'maximum', 'step']) || !whole(payload.minimum) || payload.minimum < 0
        || !whole(payload.maximum) || payload.maximum <= payload.minimum || !whole(payload.step) || payload.step <= 0
        || (payload.maximum - payload.minimum) % payload.step !== 0 || !fields(response, ['value'])
        || typeof response.value !== 'string' || !/^(0|[1-9]\d*)$/.test(response.value)) return 'invalid';
      const value = Number(response.value);
      if (!whole(value) || value < payload.minimum || value > payload.maximum || (value - payload.minimum) % payload.step !== 0) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['target']) || !whole(rubric.target) || rubric.target < payload.minimum
        || rubric.target > payload.maximum || (rubric.target - payload.minimum) % payload.step !== 0) return 'invalid';
      return value === rubric.target ? 'met' : 'review';
    }
    case 'math.number-line.fraction.v2': {
      if (!fields(payload, ['maximumWhole', 'divisions']) || !whole(payload.maximumWhole) || (payload.maximumWhole !== 1 && payload.maximumWhole !== 2)
        || !whole(payload.divisions) || payload.divisions < 2 || payload.divisions > 12 || !fields(response, ['value'])
        || typeof response.value !== 'string' || !/^(0|[1-9]\d*)\/(0|[1-9]\d*)$/.test(response.value)) return 'invalid';
      const [numerator, denominator] = response.value.split('/').map(Number);
      if (!whole(numerator) || !whole(denominator) || denominator <= 0 || numerator > payload.maximumWhole * denominator
        || numerator * payload.divisions % denominator !== 0) return 'invalid';
      const units = numerator * payload.divisions / denominator;
      if (!whole(units) || units < 0 || units > payload.maximumWhole * payload.divisions) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['targetNumerator', 'targetDenominator', 'toleranceUnits']) || !whole(rubric.targetNumerator)
        || !whole(rubric.targetDenominator) || rubric.targetDenominator <= 0 || !whole(rubric.toleranceUnits) || rubric.toleranceUnits < 0
        || rubric.targetNumerator > payload.maximumWhole * rubric.targetDenominator || rubric.targetNumerator * payload.divisions % rubric.targetDenominator !== 0) return 'invalid';
      const targetUnits = rubric.targetNumerator * payload.divisions / rubric.targetDenominator;
      return Math.abs(units - targetUnits) <= rubric.toleranceUnits ? 'met' : 'review';
    }
    case 'math.fraction-area.v2': {
      if (!fields(payload, ['minimumParts', 'maximumParts']) || !whole(payload.minimumParts) || !whole(payload.maximumParts)
        || payload.minimumParts < 2 || payload.maximumParts > 6 || payload.minimumParts > payload.maximumParts
        || !fields(response, ['n', 'd']) || !whole(response.n) || !whole(response.d) || response.d < payload.minimumParts
        || response.d > payload.maximumParts || response.n < 0 || response.n > response.d) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['targetNumerator', 'targetDenominator']) || !whole(rubric.targetNumerator) || !whole(rubric.targetDenominator)
        || rubric.targetDenominator < payload.minimumParts || rubric.targetDenominator > payload.maximumParts
        || rubric.targetNumerator < 0 || rubric.targetNumerator > rubric.targetDenominator) return 'invalid';
      return response.n * rubric.targetDenominator === rubric.targetNumerator * response.d ? 'met' : 'review';
    }
    case 'math.bar-model.structure.v2': {
      if (!fields(payload, ['whole', 'difference']) || !whole(payload.whole) || !whole(payload.difference) || payload.whole <= payload.difference
        || !fields(response, ['model']) || (response.model !== 'comparison' && response.model !== 'part-whole')) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['model']) || rubric.model !== 'comparison') return 'invalid';
      return response.model === rubric.model ? 'met' : 'review';
    }
    case 'math.bar-model.answer.v2': {
      if (!fields(payload, ['whole', 'difference']) || !whole(payload.whole) || !whole(payload.difference) || payload.whole <= payload.difference
        || !fields(response, ['value']) || typeof response.value !== 'string' || !/^(0|[1-9]\d*)$/.test(response.value)) return 'invalid';
      const value = Number(response.value); if (!whole(value) || value > payload.whole) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['target']) || !whole(rubric.target) || rubric.target < 0 || rubric.target > payload.whole) return 'invalid';
      return value === rubric.target ? 'met' : 'review';
    }
    case 'math.schema-diagram.structure.v2': {
      if (!fields(payload, ['income', 'spending']) || !whole(payload.income) || !whole(payload.spending) || payload.income <= payload.spending
        || !fields(response, ['schema']) || (response.schema !== 'change' && response.schema !== 'compare')) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['schema']) || rubric.schema !== 'change') return 'invalid';
      return response.schema === rubric.schema ? 'met' : 'review';
    }
    case 'math.schema-diagram.slots.v2': {
      if (!fields(payload, ['income', 'spending']) || !whole(payload.income) || !whole(payload.spending) || payload.income <= payload.spending
        || !fields(response, ['income', 'spending']) || typeof response.income !== 'string' || typeof response.spending !== 'string'
        || !/^(0|[1-9]\d*)$/.test(response.income) || !/^(0|[1-9]\d*)$/.test(response.spending)) return 'invalid';
      const income = Number(response.income), spending = Number(response.spending);
      if (!whole(income) || !whole(spending) || income > payload.income || spending > payload.income) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['income', 'spending']) || !whole(rubric.income) || !whole(rubric.spending)) return 'invalid';
      return income === rubric.income && spending === rubric.spending ? 'met' : 'review';
    }
    case 'math.schema-diagram.answer.v2': {
      if (!fields(payload, ['income', 'spending']) || !whole(payload.income) || !whole(payload.spending) || payload.income <= payload.spending
        || !fields(response, ['value']) || typeof response.value !== 'string' || !/^(0|[1-9]\d*)$/.test(response.value)) return 'invalid';
      const value = Number(response.value); if (!whole(value) || value > payload.income) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['target']) || !whole(rubric.target) || rubric.target < 0 || rubric.target > payload.income) return 'invalid';
      return value === rubric.target ? 'met' : 'review';
    }
    case 'math.worked-example.v2': {
      if (!fields(payload, ['response_step_ids']) || !Array.isArray(payload.response_step_ids)
        || payload.response_step_ids.length < 2 || payload.response_step_ids.length > 3
        || payload.response_step_ids.some((id) => typeof id !== 'string' || !/^[a-z0-9][a-z0-9._:-]{2,100}$/.test(id))
        || new Set(payload.response_step_ids).size !== payload.response_step_ids.length
        || !fields(response, ['values']) || !record(response.values)) return 'invalid';
      const ids = payload.response_step_ids as string[];
      const values = response.values;
      if (Object.keys(values).length !== ids.length || ids.some((id) => typeof values[id] !== 'string'
        || (values[id] as string).trim().length === 0 || (values[id] as string).trim().length > 40)) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['expectedValues'])) return 'invalid';
      const expectedValues = rubric.expectedValues;
      if (!record(expectedValues) || Object.keys(expectedValues).length !== ids.length
        || ids.some((id) => typeof expectedValues[id] !== 'string'
          || (expectedValues[id] as string).trim().length === 0
          || (expectedValues[id] as string).trim().length > 40)) return 'invalid';
      return ids.every((id) => sameAnswer(values[id] as string, expectedValues[id] as string)) ? 'met' : 'review';
    }
      case 'math.function-machine.v2': {
        if (!fields(payload, ['multiplierMaximum', 'offsetMaximum', 'exampleInputs']) || !whole(payload.multiplierMaximum)
          || payload.multiplierMaximum < 1 || payload.multiplierMaximum > 12 || !whole(payload.offsetMaximum)
          || payload.offsetMaximum < 0 || payload.offsetMaximum > 100 || !Array.isArray(payload.exampleInputs)
          || payload.exampleInputs.length < 3 || payload.exampleInputs.length > 5
          || payload.exampleInputs.some((input) => !whole(input) || input < 0 || input > 12)
          || new Set(payload.exampleInputs).size !== payload.exampleInputs.length || !fields(response, ['multiplier', 'offset'])
        || typeof response.multiplier !== 'string' || typeof response.offset !== 'string'
        || !/^(0|[1-9]\d*)$/.test(response.multiplier) || !/^(0|[1-9]\d*)$/.test(response.offset)) return 'invalid';
        const exampleInputs = payload.exampleInputs as number[];
        const multiplier = Number(response.multiplier); const offset = Number(response.offset);
      if (!whole(multiplier) || multiplier < 1 || multiplier > payload.multiplierMaximum
        || !whole(offset) || offset < 0 || offset > payload.offsetMaximum) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['multiplier', 'offset', 'heldOutInputs']) || !whole(rubric.multiplier)
        || rubric.multiplier < 1 || rubric.multiplier > payload.multiplierMaximum || !whole(rubric.offset)
        || rubric.offset < 0 || rubric.offset > payload.offsetMaximum || !Array.isArray(rubric.heldOutInputs)
        || rubric.heldOutInputs.length < 2 || rubric.heldOutInputs.length > 4
          || rubric.heldOutInputs.some((input) => !whole(input) || input < 0 || input > 24)
          || new Set(rubric.heldOutInputs).size !== rubric.heldOutInputs.length
          || rubric.heldOutInputs.some((input) => exampleInputs.includes(input))) return 'invalid';
      const expectedMultiplier = rubric.multiplier;
      const expectedOffset = rubric.offset;
      const heldOutInputs = rubric.heldOutInputs;
      return heldOutInputs.every((input) => multiplier * input + offset === expectedMultiplier * input + expectedOffset) ? 'met' : 'review';
    }
    case 'math.cpa-count.v2': {
      if (!fields(payload, ['left', 'right']) || !whole(payload.left) || !whole(payload.right)
        || payload.left < 1 || payload.right < 1 || payload.left > 20 || payload.right > 20
        || !fields(response, ['value']) || typeof response.value !== 'string' || !/^(0|[1-9]\d*)$/.test(response.value)) return 'invalid';
      const value = Number(response.value);
      if (!whole(value) || value < 0 || value > payload.left + payload.right) return 'invalid';
      if (rubric === undefined) return 'valid';
      if (!fields(rubric, ['target']) || !whole(rubric.target) || rubric.target !== payload.left + payload.right) return 'invalid';
      return value === rubric.target ? 'met' : 'review';
    }
    case 'reasoning.decide-justify.v2': {
      const choice = reasoningResponse(payload, response);
      if (!choice) return 'invalid';
      if (rubric === undefined) return 'valid';
      const key = reasoningRubric(payload, rubric);
      if (!key) return 'invalid';
      return key.acceptableChoiceIds.includes(choice.choice) ? 'met' : 'review';
    }
    default: return scoreV2Extended(kind, payload, response, rubric);
  }
}

const REASONING_ID = /^[a-z0-9][a-z0-9._:-]{2,100}$/;
const JUDGMENT_QUALITIES: readonly V2JudgmentQuality[] = ['sound', 'partial', 'unsupported'];

function reasoningIds(value: unknown, minimum: number, maximum: number): value is string[] {
  return Array.isArray(value) && value.length >= minimum && value.length <= maximum
    && value.every((id) => typeof id === 'string' && REASONING_ID.test(id)) && new Set(value).size === value.length;
}

function reasoningResponse(payload: unknown, response: unknown): { choice: string; reason: string } | null {
  if (!fields(payload, ['choiceIds', 'reasonIds']) || !reasoningIds(payload.choiceIds, 2, 4) || !reasoningIds(payload.reasonIds, 3, 5)
    || payload.choiceIds.some((id) => (payload.reasonIds as string[]).includes(id))
    || !fields(response, ['choice', 'reason']) || typeof response.choice !== 'string' || typeof response.reason !== 'string'
    || !payload.choiceIds.includes(response.choice) || !payload.reasonIds.includes(response.reason)) return null;
  return { choice: response.choice, reason: response.reason };
}

/**
 * A reasoning rubric must be able to disagree with correctness, or the
 * judgment is correctness in disguise (Appendix C Stage 3): at least one
 * decision is not acceptable, every offered reason is classified, and the
 * reasons include at least one sound and one unsupported option.
 */
function reasoningRubric(payload: unknown, rubric: unknown): { acceptableChoiceIds: string[]; reasonQuality: Record<string, V2JudgmentQuality> } | null {
  if (!fields(payload, ['choiceIds', 'reasonIds']) || !reasoningIds(payload.choiceIds, 2, 4) || !reasoningIds(payload.reasonIds, 3, 5)
    || !fields(rubric, ['acceptableChoiceIds', 'reasonQuality']) || !reasoningIds(rubric.acceptableChoiceIds, 1, 3)
    || rubric.acceptableChoiceIds.length >= payload.choiceIds.length
    || rubric.acceptableChoiceIds.some((id) => !(payload.choiceIds as string[]).includes(id))
    || !record(rubric.reasonQuality)) return null;
  const quality = rubric.reasonQuality;
  const reasonIds = payload.reasonIds;
  if (Object.keys(quality).length !== reasonIds.length
    || reasonIds.some((id) => typeof quality[id] !== 'string' || !JUDGMENT_QUALITIES.includes(quality[id] as V2JudgmentQuality))) return null;
  const values = reasonIds.map((id) => quality[id]);
  if (!values.includes('sound') || !values.includes('unsupported')) return null;
  return { acceptableChoiceIds: rubric.acceptableChoiceIds, reasonQuality: quality as Record<string, V2JudgmentQuality> };
}

/**
 * The judgment quality of one reasoning response, independent of whether the
 * decision was acceptable. Only the reasoning family has a judgment; every
 * other kind, and any malformed input, is 'invalid'.
 */
export function scoreV2Judgment(kind: V2VisualKind, payload: unknown, response: unknown, rubric: unknown): V2JudgmentQuality | 'invalid' {
  if (kind !== 'reasoning.decide-justify.v2') return 'invalid';
  const answer = reasoningResponse(payload, response);
  const key = reasoningRubric(payload, rubric);
  if (!answer || !key) return 'invalid';
  return key.reasonQuality[answer.reason] ?? 'invalid';
}

/* ── GAP-FIX-R1 learning: locale numbers, extended scorers, diagnostics ──── */

/**
 * Appendix P Part 5 / Bible 05 §5: one pure parser for typed numbers in the
 * three launch locales. en-US and es-MX write 1,234.5; pt-BR writes 1.234,5.
 * A thousands separator must group by three; anything ambiguous is refused
 * (null) rather than guessed. The browser submits the canonical string
 * (`-?digits(.digits)?`) and echoes it before Check; Core compares values,
 * never raw text.
 */
export type V2NumberLocale = 'en-US' | 'es-MX' | 'pt-BR';
export function parseLocaleNumber(text: string, locale: V2NumberLocale): string | null {
  if (typeof text !== 'string') return null;
  const trimmed = text.trim().replace(/ | /g, ' ');
  if (trimmed.length === 0 || trimmed.length > 40) return null;
  const negative = trimmed.startsWith('-') || trimmed.startsWith('−');
  const body = negative ? trimmed.slice(1).trim() : trimmed;
  const pattern = locale === 'pt-BR'
    ? /^(\d{1,3}(?:[. ]\d{3})+|\d+)(?:,(\d+))?$/
    : /^(\d{1,3}(?:[, ]\d{3})+|\d+)(?:\.(\d+))?$/;
  const match = pattern.exec(body);
  if (!match) return null;
  const integer = match[1]!.replace(/[., ]/g, '').replace(/^0+(?=\d)/, '');
  const fraction = (match[2] ?? '').replace(/0+$/, '');
  const canonical = fraction ? `${integer}.${fraction}` : integer;
  return negative && canonical !== '0' ? `-${canonical}` : canonical;
}

/** An exact rational from a canonical decimal (`-?d+(.d+)?`) or a fraction (`-?d+/d+`). */
function rational(text: string): { n: bigint; d: bigint } | null {
  const value = text.trim();
  const fraction = /^(-?)(\d{1,15})\/(\d{1,15})$/.exec(value);
  if (fraction) {
    const d = BigInt(fraction[3]!);
    if (d === 0n) return null;
    return { n: BigInt(fraction[2]!) * (fraction[1] ? -1n : 1n), d };
  }
  const decimal = /^(-?)(\d{1,15})(?:\.(\d{1,12}))?$/.exec(value);
  if (!decimal) return null;
  const places = decimal[3]?.length ?? 0;
  const n = BigInt(`${decimal[2]}${decimal[3] ?? ''}`) * (decimal[1] ? -1n : 1n);
  return { n, d: 10n ** BigInt(places) };
}

/** Part 7.2: a semantic comparison. Numbers compare as exact rationals; anything else as case-folded text. */
export function sameAnswer(given: string, expected: string): boolean {
  const left = rational(given);
  const right = rational(expected);
  if (left && right) return left.n * right.d === right.n * left.d;
  return given.trim().toLocaleLowerCase('en-US') === expected.trim().toLocaleLowerCase('en-US');
}

/**
 * Appendix P Part 4.5: a closed diagnostic vocabulary stored beside each
 * verdict. `structure`, `path` and `bin` are structure errors (the learner
 * built the wrong model); every other non-`none` code is an answer error.
 */
export const V2_DIAGNOSTIC_CODES = ['none', 'structure', 'value', 'partial', 'miss', 'false_alarm', 'path', 'outcome', 'bin', 'reason', 'tolerance'] as const;
export type V2Diagnostic = (typeof V2_DIAGNOSTIC_CODES)[number];
export function v2DiagnosticFamily(code: V2Diagnostic): 'structure' | 'answer' | null {
  return code === 'none' ? null : code === 'structure' || code === 'path' || code === 'bin' ? 'structure' : 'answer';
}

/** Signal-detection counts for the scam families (Part 7: hits, false alarms, d′). */
export interface V2Detection { hits: number; misses: number; false_alarms: number; correct_rejections: number }

/** d′ with the log-linear correction (0.5 added to each cell), so a perfect sort stays finite. */
export function dPrime(value: V2Detection): number {
  const hitRate = (value.hits + 0.5) / (value.hits + value.misses + 1);
  const faRate = (value.false_alarms + 0.5) / (value.false_alarms + value.correct_rejections + 1);
  return Math.round((probit(hitRate) - probit(faRate)) * 1000) / 1000;
}

function probit(p: number): number {
  // Acklam's rational approximation of the inverse normal CDF.
  const a = [-39.69683028665376, 220.9460984245205, -275.9285104469687, 138.357751867269, -30.66479806614716, 2.506628277459239];
  const b = [-54.47609879822406, 161.5858368580409, -155.6989798598866, 66.80131188771972, -13.28068155288572];
  const c = [-0.007784894002430293, -0.3223964580411365, -2.400758277161838, -2.549732539343734, 4.374664141464968, 2.938163982698783];
  const d = [0.007784695709041462, 0.3224671290700398, 2.445134137142996, 3.754408661907416];
  const tail = (q: number) => (((((c[0]! * q + c[1]!) * q + c[2]!) * q + c[3]!) * q + c[4]!) * q + c[5]!) / ((((d[0]! * q + d[1]!) * q + d[2]!) * q + d[3]!) * q + 1);
  if (p < 0.02425) return tail(Math.sqrt(-2 * Math.log(p)));
  if (p > 1 - 0.02425) return -tail(Math.sqrt(-2 * Math.log(1 - p)));
  const q = p - 0.5; const r = q * q;
  return (((((a[0]! * r + a[1]!) * r + a[2]!) * r + a[3]!) * r + a[4]!) * r + a[5]!) * q / (((((b[0]! * r + b[1]!) * r + b[2]!) * r + b[3]!) * r + b[4]!) * r + 1);
}

export interface V2Grade { verdict: V2VisualVerdict; diagnostic: V2Diagnostic; detection?: V2Detection }

const NUMBER_TEXT = /^-?(0|[1-9]\d*)(\.\d+)?$/;
function numberText(value: unknown): value is string { return typeof value === 'string' && value.length <= 40 && NUMBER_TEXT.test(value); }
function strings(value: unknown, min: number, max: number): value is string[] {
  return Array.isArray(value) && value.length >= min && value.length <= max && value.every((item) => typeof item === 'string' && REASONING_ID.test(item))
    && new Set(value).size === value.length;
}
function onGrid(value: unknown, minimum: number, maximum: number, step: number): value is number {
  return whole(value) && whole(minimum) && whole(maximum) && whole(step) && step > 0 && value >= minimum && value <= maximum && (value - minimum) % step === 0;
}
const grade = (verdict: V2VisualVerdict, diagnostic: V2Diagnostic = verdict === 'met' ? 'none' : 'value'): V2Grade => ({ verdict, diagnostic });
const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };

function compoundMinor(principal: number, rateBps: number, years: number): number | null {
  if (!whole(principal) || principal < 100 || principal > 1_000_000 || !whole(rateBps) || rateBps < 100 || rateBps > 1_500 || !whole(years) || years < 1 || years > 30) return null;
  let value = BigInt(principal);
  for (let year = 0; year < years; year += 1) value = (value * BigInt(10_000 + rateBps) + 5_000n) / 10_000n;
  return value > BigInt(Number.MAX_SAFE_INTEGER) ? null : Number(value);
}

function taxOwed(income: number, brackets: unknown): { tax: number; marginal: number } | null {
  if (!Array.isArray(brackets) || brackets.length < 2 || brackets.length > 6) return null;
  let lower = 0; let tax = 0; let marginal = 0;
  for (const [index, bracket] of brackets.entries()) {
    if (!record(bracket) || !whole(bracket.rateBasisPoints) || bracket.rateBasisPoints < 0 || bracket.rateBasisPoints > 10_000) return null;
    const upper = bracket.upToMinor;
    if (upper === null ? index !== brackets.length - 1 : !whole(upper) || upper <= lower) return null;
    const taxable = Math.max(0, Math.min(income, (upper as number | null) ?? income) - lower);
    tax += Math.round(taxable * bracket.rateBasisPoints / 10_000);
    if (taxable > 0) marginal = bracket.rateBasisPoints;
    if (upper === null) break;
    lower = upper as number;
  }
  return { tax, marginal };
}

type RuleLink = 'and' | 'or' | 'none';
type RuleComparator = '>=' | '>' | '<=' | '<';
function ruleOutcome(saved: number, goalDay: boolean, comparator: RuleComparator, threshold: number, link: RuleLink): boolean {
  const amount = comparator === '>=' ? saved >= threshold : comparator === '>' ? saved > threshold : comparator === '<=' ? saved <= threshold : saved < threshold;
  return link === 'and' ? amount && goalDay : link === 'or' ? amount || goalDay : amount;
}
const COMPARATORS: readonly string[] = ['>=', '>', '<=', '<'];
const LINKS: readonly string[] = ['and', 'or', 'none'];

function money(payload: Record<string, unknown>, response: unknown): number | null {
  const denominations = payload.denominations;
  if (!Array.isArray(denominations) || denominations.length < 2 || denominations.length > 8 || !fields(response, ['counts']) || !record(response.counts)) return null;
  const counts = response.counts;
  if (Object.keys(counts).length !== denominations.length) return null;
  let total = 0;
  for (const denomination of denominations) {
    if (!record(denomination) || !whole(denomination.value) || denomination.value <= 0 || !whole(denomination.available)) return null;
    const count = counts[String(denomination.value)];
    // Conservation: a tray never holds more pieces than it has, nor fewer than none.
    if (!whole(count) || count < 0 || count > denomination.available) return null;
    total += count * denomination.value;
  }
  return total;
}

function fewestPieces(target: number, denominations: Array<{ value: number; available: number }>): number | null {
  const best = new Array<number>(target + 1).fill(Infinity);
  best[0] = 0;
  for (const { value, available } of denominations) {
    for (let used = 0; used < available; used += 1) {
      for (let amount = target; amount >= value; amount -= 1) {
        const candidate = best[amount - value]! + 1;
        if (candidate < best[amount]!) best[amount] = candidate;
      }
    }
  }
  return Number.isFinite(best[target]!) ? best[target]! : null;
}

function flowPath(payload: Record<string, unknown>, path: unknown): path is string[] {
  if (!Array.isArray(path) || path.length < 2 || path.length > 12 || typeof payload.start !== 'string' || path[0] !== payload.start || !Array.isArray(payload.nodes)) return false;
  const nodes = new Map<string, Record<string, unknown>>();
  for (const node of payload.nodes) if (record(node) && typeof node.id === 'string') nodes.set(node.id, node);
  for (let index = 0; index < path.length; index += 1) {
    const node = typeof path[index] === 'string' ? nodes.get(path[index] as string) : undefined;
    if (!node) return false;
    const next = path[index + 1];
    if (next === undefined) return node.yes === undefined && node.no === undefined;
    if (next !== node.yes && next !== node.no) return false;
  }
  return false;
}

function choiceGrade(payload: unknown, response: unknown, rubric: unknown, maximum: number): V2Grade {
  if (!fields(payload, ['choiceIds']) || !strings(payload.choiceIds, 2, 3) || !fields(response, ['choice']) || typeof response.choice !== 'string'
    || !payload.choiceIds.includes(response.choice)) return INVALID;
  if (rubric === undefined) return grade('valid');
  if (!fields(rubric, ['acceptable_choice_ids']) || !strings(rubric.acceptable_choice_ids, 1, maximum)
    || rubric.acceptable_choice_ids.some((choice) => !(payload.choiceIds as string[]).includes(choice))) return INVALID;
  return rubric.acceptable_choice_ids.includes(response.choice) ? grade('met') : grade('review', 'outcome');
}

function sortGrade(payload: unknown, response: unknown, rubric: unknown): V2Grade {
  if (!fields(payload, ['binIds', 'itemIds', 'reasonIds']) || !strings(payload.binIds, 2, 4) || !strings(payload.itemIds, 2, 8) || !strings(payload.reasonIds, 2, 5)
    || !fields(response, ['placements']) || !record(response.placements)) return INVALID;
  const { binIds, itemIds, reasonIds } = payload as { binIds: string[]; itemIds: string[]; reasonIds: string[] };
  const placements = response.placements;
  if (Object.keys(placements).length !== itemIds.length) return INVALID;
  for (const item of itemIds) {
    const placed = placements[item];
    if (!fields(placed, ['bin', 'reason']) || typeof placed.bin !== 'string' || typeof placed.reason !== 'string'
      || !binIds.includes(placed.bin) || !reasonIds.includes(placed.reason)) return INVALID;
  }
  if (rubric === undefined) return grade('valid');
  if (!fields(rubric, ['accepted']) || !record(rubric.accepted) || Object.keys(rubric.accepted).length !== itemIds.length) return INVALID;
  const accepted = rubric.accepted;
  let binMiss = false; let reasonMiss = false;
  for (const item of itemIds) {
    const pairs = accepted[item];
    if (!Array.isArray(pairs) || pairs.length < 1 || pairs.length > 4 || pairs.some((pair) => !fields(pair, ['bin', 'reason'])
      || !binIds.includes(pair.bin as string) || !reasonIds.includes(pair.reason as string))) return INVALID;
    const placed = placements[item] as { bin: string; reason: string };
    const sameBin = pairs.filter((pair) => (pair as { bin: string }).bin === placed.bin);
    if (sameBin.length === 0) binMiss = true;
    else if (!sameBin.some((pair) => (pair as { reason: string }).reason === placed.reason)) reasonMiss = true;
  }
  return !binMiss && !reasonMiss ? grade('met') : grade('review', binMiss ? 'bin' : 'reason');
}

function detectionGrade(payload: unknown, response: unknown, rubric: unknown): V2Grade {
  if (!fields(payload, ['messageIds']) || !strings(payload.messageIds, 3, 8) || !fields(response, ['flagged']) || !strings(response.flagged, 0, 8)
    || response.flagged.some((flag) => !(payload.messageIds as string[]).includes(flag))) return INVALID;
  if (rubric === undefined) return grade('valid');
  const messages = payload.messageIds as string[];
  // Genuine messages are always in the set: a key that calls everything a scam cannot measure false alarms.
  if (!fields(rubric, ['scam_ids']) || !strings(rubric.scam_ids, 1, messages.length - 1) || rubric.scam_ids.some((scam) => !messages.includes(scam))) return INVALID;
  const scams = new Set(rubric.scam_ids);
  const flagged = new Set(response.flagged as string[]);
  const detection: V2Detection = {
    hits: [...scams].filter((scam) => flagged.has(scam)).length,
    misses: [...scams].filter((scam) => !flagged.has(scam)).length,
    false_alarms: [...flagged].filter((flag) => !scams.has(flag)).length,
    correct_rejections: messages.filter((message) => !scams.has(message) && !flagged.has(message)).length,
  };
  const met = detection.misses === 0 && detection.false_alarms === 0;
  const diagnostic: V2Diagnostic = met ? 'none' : detection.misses > 0 && detection.false_alarms > 0 ? 'partial' : detection.misses > 0 ? 'miss' : 'false_alarm';
  return { verdict: met ? 'met' : 'review', diagnostic, detection };
}

/**
 * Canonical grade of one response: the verdict, a closed diagnostic code and,
 * for the detection families, the signal-detection counts. `scoreV2Visual`
 * stays the verdict-only entry point every existing caller uses.
 */
export function gradeV2Response(kind: V2VisualKind, payload: unknown, response: unknown, rubric?: unknown): V2Grade {
  const verdict = scoreV2Visual(kind, payload, response, rubric);
  if (verdict === 'invalid' || verdict === 'valid') return { verdict, diagnostic: 'none' };
  switch (kind) {
    case 'money.allocation.v2':
    case 'math.bar-model.answer.v2':
    case 'math.schema-diagram.slots.v2':
    case 'math.schema-diagram.answer.v2':
    case 'math.fraction-area.v2':
    case 'math.function-machine.v2':
    case 'math.cpa-count.v2': return grade(verdict);
    case 'math.bar-model.structure.v2':
    case 'math.schema-diagram.structure.v2': return grade(verdict, verdict === 'met' ? 'none' : 'structure');
    case 'math.number-line.whole.v2':
    case 'math.number-line.fraction.v2': return grade(verdict, verdict === 'met' ? 'none' : 'tolerance');
    case 'reasoning.decide-justify.v2': return grade(verdict, verdict === 'met' ? 'none' : 'outcome');
    case 'math.worked-example.v2': {
      if (verdict === 'met') return grade('met');
      const values = (response as { values: Record<string, string> }).values;
      const expected = (rubric as { expectedValues: Record<string, string> }).expectedValues;
      const right = Object.keys(expected).filter((key) => sameAnswer(values[key]!, expected[key]!)).length;
      return grade('review', right > 0 ? 'partial' : 'value');
    }
    default: return scoreV2ExtendedDetailed(kind, payload, response, rubric);
  }
}

function scoreV2Extended(kind: V2VisualKind, payload: unknown, response: unknown, rubric: unknown): V2VisualVerdict {
  return scoreV2ExtendedDetailed(kind, payload, response, rubric).verdict;
}

function scoreV2ExtendedDetailed(kind: V2VisualKind, payload: unknown, response: unknown, rubric: unknown): V2Grade {
  switch (kind) {
    case 'math.place-value.v2': {
      // M5: the trade sequence and the written digits, one integer state.
      if (!fields(payload, ['total']) || !whole(payload.total) || payload.total < 10 || payload.total > 29
        || !fields(response, ['trades', 'tens', 'ones']) || !whole(response.trades) || response.trades < 0
        || response.trades > Math.floor(payload.total / 10) || !numberText(response.tens) || !numberText(response.ones)) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['trades']) || rubric.trades !== Math.floor(payload.total / 10)) return INVALID;
      if (response.trades !== rubric.trades) return grade('review', 'structure');
      return Number(response.tens) === Math.floor(payload.total / 10) && Number(response.ones) === payload.total % 10 ? grade('met') : grade('review', 'value');
    }
    case 'math.ratio-table.v2': {
      // M14: the chosen pair and the missing value.
      if (!fields(payload, ['itemsPerPack', 'pricePerPack', 'minimumPacks', 'maximumPacks']) || !whole(payload.itemsPerPack) || !whole(payload.pricePerPack)
        || !whole(payload.minimumPacks) || !whole(payload.maximumPacks) || payload.maximumPacks <= payload.minimumPacks
        || !fields(response, ['packs', 'price']) || !onGrid(response.packs, payload.minimumPacks, payload.maximumPacks, 1) || !numberText(response.price)) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['target_packs']) || !onGrid(rubric.target_packs, payload.minimumPacks, payload.maximumPacks, 1)) return INVALID;
      if (response.packs !== rubric.target_packs) return grade('review', 'structure');
      return sameAnswer(response.price, String(rubric.target_packs * payload.pricePerPack)) ? grade('met') : grade('review', 'value');
    }
    case 'visual.percent-grid.v2': {
      // M15: the shaded count (snapped), the marker percent and the amount.
      if (!fields(payload, ['baseUnits', 'step']) || !whole(payload.baseUnits) || payload.baseUnits <= 0 || !whole(payload.step) || payload.step <= 0 || 100 % payload.step !== 0
        || !fields(response, ['percent', 'amount']) || !onGrid(response.percent, 0, 100, payload.step) || !numberText(response.amount)) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['target_percent']) || !onGrid(rubric.target_percent, 0, 100, payload.step)) return INVALID;
      if (response.percent !== rubric.target_percent) return grade('review', 'structure');
      return sameAnswer(response.amount, String(payload.baseUnits * response.percent / 100)) ? grade('met') : grade('review', 'value');
    }
    case 'visual.growth-comparison.v2': {
      // M19: a committed prediction, graded within the private tolerance (Part 4.2).
      if (!fields(payload, ['principalMinor', 'minimumRateBps', 'maximumRateBps', 'rateStepBps', 'minimumYears', 'maximumYears', 'yearStep', 'predictionStepMinor', 'predictionMaximumMinor'])) return INVALID;
      const p = payload as Record<string, number>;
      if (!fields(response, ['rateBps', 'years', 'predictionMinor']) || !onGrid(response.rateBps, p.minimumRateBps!, p.maximumRateBps!, p.rateStepBps!)
        || !onGrid(response.years, p.minimumYears!, p.maximumYears!, p.yearStep!)
        || !onGrid(response.predictionMinor, p.principalMinor!, p.predictionMaximumMinor!, p.predictionStepMinor!)) return INVALID;
      const actual = compoundMinor(p.principalMinor!, response.rateBps, response.years);
      if (actual === null) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['tolerance_minor']) || !whole(rubric.tolerance_minor) || rubric.tolerance_minor < 0 || rubric.tolerance_minor > p.predictionMaximumMinor!) return INVALID;
      return Math.abs(response.predictionMinor - actual) <= rubric.tolerance_minor ? grade('met') : grade('review', 'tolerance');
    }
    case 'visual.tax-bracket.v2': {
      // M20: tax owed and the marginal rate at the asked income.
      if (!fields(payload, ['minimumIncomeMinor', 'maximumIncomeMinor', 'incomeStepMinor', 'brackets']) || !whole(payload.minimumIncomeMinor) || !whole(payload.maximumIncomeMinor)
        || !whole(payload.incomeStepMinor) || payload.incomeStepMinor <= 0
        || !fields(response, ['incomeMinor', 'taxMinor', 'marginalBps']) || !onGrid(response.incomeMinor, payload.minimumIncomeMinor, payload.maximumIncomeMinor, payload.incomeStepMinor)
        || !numberText(response.taxMinor) || !whole(response.marginalBps) || response.marginalBps < 0 || response.marginalBps > 10_000) return INVALID;
      const owed = taxOwed(response.incomeMinor, payload.brackets);
      if (!owed) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['income_minor']) || !onGrid(rubric.income_minor, payload.minimumIncomeMinor, payload.maximumIncomeMinor, payload.incomeStepMinor)) return INVALID;
      if (response.incomeMinor !== rubric.income_minor) return grade('review', 'structure');
      const taxRight = sameAnswer(response.taxMinor, String(owed.tax));
      const rateRight = response.marginalBps === owed.marginal;
      return taxRight && rateRight ? grade('met') : grade('review', taxRight || rateRight ? 'partial' : 'value');
    }
    case 'logic.savings-rule.v2': {
      // L2 (Part 4.6): the learner's rule is compiled and run on held-out cases, never matched as text.
      if (!fields(payload, ['goal']) || !whole(payload.goal) || payload.goal < 2 || payload.goal > 100
        || !fields(response, ['comparator', 'threshold', 'link']) || typeof response.comparator !== 'string' || !COMPARATORS.includes(response.comparator)
        || !onGrid(response.threshold, 0, payload.goal * 2, 1) || typeof response.link !== 'string' || !LINKS.includes(response.link)) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['comparator', 'threshold', 'link', 'held_out']) || typeof rubric.comparator !== 'string' || !COMPARATORS.includes(rubric.comparator)
        || !onGrid(rubric.threshold, 0, payload.goal * 2, 1) || typeof rubric.link !== 'string' || !LINKS.includes(rubric.link)
        || !Array.isArray(rubric.held_out) || rubric.held_out.length < 2 || rubric.held_out.length > 8) return INVALID;
      const goal = payload.goal;
      const cases = rubric.held_out;
      if (cases.some((item) => !fields(item, ['saved', 'goal_day']) || !onGrid(item.saved, 0, goal * 2, 1) || typeof item.goal_day !== 'boolean')) return INVALID;
      const key = cases.map((item) => ruleOutcome(item.saved as number, item.goal_day as boolean, rubric.comparator as RuleComparator, rubric.threshold as number, rubric.link as RuleLink));
      // A held-out set where the key rule is always true or always false proves nothing.
      if (!key.includes(true) || !key.includes(false)) return INVALID;
      const learner = cases.map((item) => ruleOutcome(item.saved as number, item.goal_day as boolean, response.comparator as RuleComparator, response.threshold as number, response.link as RuleLink));
      if (learner.every((value, index) => value === key[index])) return grade('met');
      return grade('review', response.link !== rubric.link ? 'structure' : 'value');
    }
    case 'visual.goal-bullet.v2': {
      if (!fields(payload, ['minimum', 'maximum', 'step']) || !whole(payload.minimum) || !whole(payload.maximum) || !whole(payload.step) || payload.step <= 0
        || !fields(response, ['value']) || !onGrid(response.value, payload.minimum, payload.maximum, payload.step)) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['minimum_value']) || !onGrid(rubric.minimum_value, payload.minimum, payload.maximum, payload.step) || rubric.minimum_value === payload.minimum) return INVALID;
      return response.value >= rubric.minimum_value ? grade('met') : grade('review', 'value');
    }
    case 'money.running-ledger.v2': {
      if (!fields(payload, ['initial', 'sale', 'cost', 'maxEntries']) || !whole(payload.initial) || !whole(payload.sale) || !whole(payload.cost) || !whole(payload.maxEntries)
        || !fields(response, ['entries', 'balance']) || !Array.isArray(response.entries) || response.entries.length > payload.maxEntries
        || response.entries.some((entry) => entry !== 'sale' && entry !== 'cost') || !numberText(response.balance)) return INVALID;
      const sale = payload.sale; const cost = payload.cost;
      // Conservation: the balance is always the opening amount plus every sale minus every cost.
      const computed = (response.entries as string[]).reduce((sum, entry) => sum + (entry === 'sale' ? sale : -cost), payload.initial);
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['target_balance']) || !whole(rubric.target_balance) || rubric.target_balance === payload.initial) return INVALID;
      if (computed !== rubric.target_balance) return grade('review', 'structure');
      return sameAnswer(response.balance, String(computed)) ? grade('met') : grade('review', 'value');
    }
    case 'logic.rule-checker.v2': {
      if (!fields(payload, ['cardIds']) || !strings(payload.cardIds, 3, 6) || !fields(response, ['flipped']) || !strings(response.flipped, 1, 6)
        || response.flipped.some((card) => !(payload.cardIds as string[]).includes(card))) return INVALID;
      if (rubric === undefined) return grade('valid');
      const cards = payload.cardIds as string[];
      if (!fields(rubric, ['must_flip_ids']) || !strings(rubric.must_flip_ids, 1, cards.length - 1) || rubric.must_flip_ids.some((card) => !cards.includes(card))) return INVALID;
      const need = new Set(rubric.must_flip_ids);
      const flipped = new Set(response.flipped as string[]);
      const missing = [...need].some((card) => !flipped.has(card));
      const extra = [...flipped].some((card) => !need.has(card));
      return !missing && !extra ? grade('met') : grade('review', missing && extra ? 'partial' : missing ? 'miss' : 'false_alarm');
    }
    case 'logic.euler.v2': {
      if (!fields(payload, ['relation', 'itemIds']) || !strings(payload.itemIds, 2, 6) || !fields(response, ['placements']) || !record(response.placements)) return INVALID;
      const relation = payload.relation;
      if (relation !== 'overlap' && relation !== 'subset' && relation !== 'disjoint') return INVALID;
      const items = payload.itemIds as string[];
      const placements = response.placements;
      // Impossible states: nothing is only-in-A when A sits inside B; nothing is in both when they never meet.
      const allowed = relation === 'subset' ? ['second', 'both', 'neither'] : relation === 'disjoint' ? ['first', 'second', 'neither'] : ['first', 'second', 'both', 'neither'];
      if (Object.keys(placements).length !== items.length || items.some((item) => typeof placements[item] !== 'string' || !allowed.includes(placements[item] as string))) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['regions']) || !record(rubric.regions) || Object.keys(rubric.regions).length !== items.length) return INVALID;
      const regions = rubric.regions;
      if (items.some((item) => !allowed.includes(regions[item] as string))) return INVALID;
      const wrong = items.filter((item) => placements[item] !== regions[item]).length;
      return wrong === 0 ? grade('met') : grade('review', wrong < items.length ? 'partial' : 'structure');
    }
    case 'logic.flowchart.v2':
    case 'money.spend-decision.v2': {
      if (!fields(payload, ['start', 'nodes', 'scenarioIds']) || !strings(payload.scenarioIds, 1, 3) || !fields(response, ['paths']) || !record(response.paths)) return INVALID;
      const scenarios = payload.scenarioIds as string[];
      const paths = response.paths;
      if (Object.keys(paths).length !== scenarios.length || scenarios.some((scenario) => !flowPath(payload, paths[scenario]))) return INVALID;
      if (rubric === undefined) return grade('valid');
      if (!fields(rubric, ['paths']) || !record(rubric.paths) || Object.keys(rubric.paths).length !== scenarios.length) return INVALID;
      const keys = rubric.paths;
      if (scenarios.some((scenario) => !flowPath(payload, keys[scenario]))) return INVALID;
      let pathWrong = false; let outcomeWrong = false;
      for (const scenario of scenarios) {
        const given = paths[scenario] as string[];
        const key = keys[scenario] as string[];
        if (given.at(-1) !== key.at(-1)) outcomeWrong = true;
        else if (given.join('>') !== key.join('>')) pathWrong = true;
      }
      return !pathWrong && !outcomeWrong ? grade('met') : grade('review', outcomeWrong ? 'outcome' : 'path');
    }
    case 'logic.sort-by-rule.v2':
    case 'money.needs-wants.v2': return sortGrade(payload, response, rubric);
    case 'logic.scam-spotter.v2':
    case 'money.scam-check.v2': return detectionGrade(payload, response, rubric);
    case 'money.coin-tray.v2': {
      if (!record(payload)) return INVALID;
      const total = money(payload, response);
      if (total === null) return INVALID;
      if (rubric === undefined) return grade('valid');
      const denominations = payload.denominations as Array<{ value: number; available: number }>;
      const most = denominations.reduce((sum, item) => sum + item.value * item.available, 0);
      if (!fields(rubric, ['target_minor', 'fewest']) || !whole(rubric.target_minor) || rubric.target_minor <= 0 || rubric.target_minor > most
        || typeof rubric.fewest !== 'boolean' || rubric.target_minor > 100_000) return INVALID;
      const fewest = fewestPieces(rubric.target_minor, denominations);
      if (fewest === null) return INVALID;
      if (total !== rubric.target_minor) return grade('review', 'value');
      const pieces = Object.values((response as { counts: Record<string, number> }).counts).reduce((sum, count) => sum + count, 0);
      return !rubric.fewest || pieces === fewest ? grade('met') : grade('review', 'partial');
    }
    case 'money.making-change.v2': {
      if (!fields(payload, ['denominations', 'price', 'paid']) || !whole(payload.price) || !whole(payload.paid) || payload.paid <= payload.price) return INVALID;
      const total = money(payload, response);
      if (total === null) return INVALID;
      if (rubric === undefined) return grade('valid');
      // Conservation: the change owed is exactly what was paid minus the price.
      if (!fields(rubric, ['change_minor']) || rubric.change_minor !== payload.paid - payload.price) return INVALID;
      return total === rubric.change_minor ? grade('met') : grade('review', 'value');
    }
    case 'story.branch.v2':
    case 'story.dialogue-choice.v2': return choiceGrade(payload, response, rubric, 3);
    case 'story.would-you-rather.v2': return choiceGrade(payload, response, rubric, 2);
    default: return INVALID;
  }
}
