import { t, row as r, item as q } from './helpers.mjs';

export const creditTerms = [
  {
    id: 'fe-production-credit-mechanics-01', title: t('Parts of a loan', 'Partes del préstamo', 'Partes do empréstimo'),
    relevance: t('Identify what you borrowed and what you are charged for borrowing it.', 'Identifica qué pediste prestado y qué te cobran por usarlo.', 'Identifique o que tomou emprestado e o que cobram pelo seu uso.'),
    misconception: 'Principal, interest and administrative fees are all interchangeable names for the borrowed cash.',
    example: t('Borrowed money is principal. Interest charges for using it; a separately listed processing fee is another charge.', 'El dinero prestado es capital. El interés cobra por usarlo; una comisión de trámite separada es otro cargo.', 'O dinheiro emprestado é o principal. Juros cobram pelo seu uso; uma tarifa separada de processamento é outro encargo.'),
    items: [
      q('guided', [r('Identify the principal.', 'Fictional agreement: borrowed cash, interest and a separate setup fee.', ['Borrowed cash', 'Interest', 'Setup fee'], 'Principal is the money borrowed, not the borrowing charges.', 'Separate the original borrowed money from its charges.'), r('Identifica el capital.', 'Contrato ficticio: dinero prestado, interés y comisión de apertura separada.', ['Dinero prestado', 'Interés', 'Comisión de apertura'], 'El capital es el dinero prestado, no los cargos.', 'Distingue el dinero originalmente prestado de sus cargos.'), r('Identifique o principal.', 'Contrato fictício: dinheiro emprestado, juros e tarifa de abertura separada.', ['Dinheiro emprestado', 'Juros', 'Tarifa de abertura'], 'O principal é o dinheiro emprestado, não os encargos.', 'Separe o dinheiro tomado emprestado dos encargos.')]),
      q('guided', [r('Identify the interest.', 'The contract labels a periodic charge for using borrowed money as interest.', ['The periodic borrowing charge', 'The original borrowed money'], 'Interest is charged for using the borrowed money.', 'Follow the contract’s stated purpose for the charge.'), r('Identifica el interés.', 'El contrato llama interés al cargo periódico por usar el dinero prestado.', ['El cargo periódico del préstamo', 'El dinero originalmente prestado'], 'El interés se cobra por usar el dinero prestado.', 'Sigue el propósito del cargo indicado en el contrato.'), r('Identifique os juros.', 'O contrato chama de juros o encargo periódico pelo uso do dinheiro emprestado.', ['O encargo periódico do empréstimo', 'O dinheiro tomado emprestado'], 'Os juros são cobrados pelo uso do dinheiro emprestado.', 'Siga a finalidade do encargo indicada no contrato.')]),
      q('practice', [r('Which is a separate fee?', 'The agreement lists interest and a one-time processing fee as different charges.', ['The processing fee', 'The interest rate'], 'The agreement explicitly separates processing fees from interest.', 'Use the agreement’s labels rather than merging distinct charges.'), r('¿Cuál es una comisión separada?', 'El contrato distingue interés y comisión única de trámite.', ['La comisión de trámite', 'La tasa de interés'], 'El contrato separa expresamente la comisión del interés.', 'Usa las etiquetas del contrato sin mezclar cargos distintos.'), r('Qual é uma tarifa separada?', 'O contrato distingue juros e tarifa única de processamento.', ['A tarifa de processamento', 'A taxa de juros'], 'O contrato separa a tarifa dos juros.', 'Use os nomes do contrato sem misturar encargos distintos.')]),
      q('practice', [r('Does “no interest” mean no charges?', 'The offer waives interest but explicitly lists a processing fee.', ['No, the fee remains', 'Yes, all charges disappear'], 'Waiving interest does not waive the separately stated fee.', 'Check fees separately from interest.'), r('¿Sin interés significa sin cargos?', 'La oferta elimina el interés, pero incluye una comisión de trámite.', ['No, queda la comisión', 'Sí, desaparecen todos los cargos'], 'Eliminar el interés no elimina la comisión indicada aparte.', 'Revisa las comisiones por separado del interés.'), r('Sem juros significa sem encargos?', 'A oferta dispensa juros, mas inclui uma tarifa de processamento.', ['Não, a tarifa continua', 'Sim, todos os encargos somem'], 'Dispensar juros não dispensa a tarifa indicada à parte.', 'Confira as tarifas separadas dos juros.')]),
      q('practice', [r('Which distinction matters?', 'Your payment includes a principal portion and an interest portion.', ['They pay different parts of the agreement', 'Both are entirely new borrowed money'], 'Principal repayment and interest charges serve different purposes.', 'Repaying borrowed money differs from paying its use charge.'), r('¿Qué distinción importa?', 'Tu pago incluye una parte de capital y otra de interés.', ['Cubren partes distintas del contrato', 'Todo es dinero nuevo prestado'], 'Devolver capital y pagar interés tienen funciones diferentes.', 'Devolver dinero difiere de pagar el cargo por usarlo.'), r('Qual distinção importa?', 'Sua parcela inclui uma parte do principal e outra de juros.', ['Cobrem partes distintas do contrato', 'Tudo é dinheiro novo emprestado'], 'Devolver principal e pagar juros têm funções diferentes.', 'Devolver dinheiro difere de pagar pelo seu uso.')]),
      q('transfer', [r('What has been deducted?', 'A loan’s principal stays unchanged, but the lender withholds the stated setup fee from disbursement.', ['A fee, not principal repayment', 'A payment reducing principal'], 'Withholding a fee does not itself repay borrowed principal.', 'Distinguish a fee deducted from cash from principal repaid.'), r('¿Qué se descontó?', 'El capital del préstamo no cambia, pero la entidad retiene la comisión de apertura del desembolso.', ['Una comisión, no abono a capital', 'Un pago que reduce capital'], 'Retener una comisión no devuelve por sí mismo capital prestado.', 'Distingue una comisión retenida de un abono a capital.'), r('O que foi descontado?', 'O principal não muda, mas a entidade retém a tarifa de abertura do dinheiro liberado.', ['Uma tarifa, não abatimento do principal', 'Um pagamento que reduz principal'], 'Reter uma tarifa não devolve por si só o principal.', 'Separe uma tarifa retida de um abatimento do principal.')]),
    ],
  },
  {
    id: 'fe-production-credit-mechanics-08', title: t('Read the missed-payment terms', 'Lee las consecuencias del atraso', 'Leia as regras do atraso'),
    relevance: t('A missed payment has the consequences stated in the applicable agreement and rules.', 'Un atraso tiene las consecuencias del contrato y las reglas aplicables.', 'Um atraso tem as consequências do contrato e das regras aplicáveis.'),
    misconception: 'Every late payment triggers the same fee, grace period or collateral consequence in every agreement.',
    example: t('This fictional agreement charges a late fee after its deadline. Missing that deadline triggers the stated fee, not invented consequences.', 'Este contrato ficticio cobra una comisión tras su fecha límite. El atraso activa ese cargo, no consecuencias inventadas.', 'Este contrato fictício cobra uma tarifa após o prazo. O atraso gera esse encargo, não consequências inventadas.'),
    items: [
      q('guided', [r('What follows from these terms?', 'Fictional agreement: unpaid after Friday triggers a late fee. Payment remains unpaid Saturday.', ['The stated late fee applies', 'Weekends automatically postpone the deadline'], 'The unpaid balance passed the stated fee-triggering deadline.', 'Use the stated trigger and consequence.'), r('¿Qué ocurre según estas condiciones?', 'Contrato ficticio: después del viernes se cobra atraso. El sábado sigue pendiente.', ['Se aplica el cargo indicado', 'El fin de semana aplaza el plazo'], 'El pago pendiente pasó la fecha que activa el cargo.', 'Usa la condición y consecuencia indicadas.'), r('O que ocorre por estas regras?', 'Contrato fictício: após sexta há tarifa de atraso. No sábado o pagamento segue pendente.', ['Aplica-se a tarifa indicada', 'O fim de semana adia o prazo'], 'O pagamento pendente passou do prazo que gera a tarifa.', 'Use a condição e a consequência indicadas.')]),
      q('guided', [r('Is the fee triggered yet?', 'Terms allow payment through Monday without a late fee. Payment arrives Monday.', ['No, it met the stated deadline', 'Yes, any Monday payment is late'], 'The payment arrived within the agreement’s stated window.', 'Apply this agreement’s deadline rather than an assumed one.'), r('¿Ya se activa el cargo?', 'Las condiciones permiten pagar hasta el lunes sin cargo. El pago llega el lunes.', ['No, cumple el plazo indicado', 'Sí, todo pago del lunes se atrasa'], 'El pago llegó dentro del plazo indicado.', 'Usa el plazo de este contrato, no uno supuesto.'), r('A tarifa já se aplica?', 'As regras permitem pagar até segunda sem tarifa. O pagamento chega na segunda.', ['Não, cumpriu o prazo indicado', 'Sim, toda segunda já é atraso'], 'O pagamento chegou dentro do prazo indicado.', 'Use o prazo deste contrato, não um prazo suposto.')]),
      q('practice', [r('Can you infer this consequence?', 'The excerpt states a late fee, without demanding immediate full repayment.', ['No, more terms are needed', 'Yes, every late fee means full repayment'], 'A late-fee clause alone does not establish immediate full repayment.', 'Do not add a consequence absent from the excerpt.'), r('¿Puedes concluir esta consecuencia?', 'El extracto indica cargo por atraso. No menciona exigir todo el saldo de inmediato.', ['No, faltan condiciones', 'Sí, todo cargo exige liquidación'], 'La cláusula de cargo no demuestra una exigencia de liquidación.', 'No añadas una consecuencia ausente del extracto.'), r('Pode concluir esta consequência?', 'O trecho indica tarifa de atraso. Não menciona cobrar todo o saldo de imediato.', ['Não, faltam regras', 'Sim, toda tarifa exige quitação'], 'A cláusula da tarifa não prova exigência de quitação imediata.', 'Não acrescente uma consequência ausente do trecho.')]),
      q('practice', [r('Which terms should you use?', 'Your old loan waived late fees. The new agreement explicitly charges them after its deadline.', ['The new agreement’s applicable terms', 'The old loan’s waiver'], 'The old waiver does not change the new stated terms.', 'Check the agreement governing this payment.'), r('¿Qué condiciones debes usar?', 'Tu préstamo anterior perdonaba cargos. El nuevo contrato los cobra después del plazo.', ['Las condiciones aplicables del nuevo', 'La exención del préstamo anterior'], 'La exención anterior no cambia las condiciones nuevas.', 'Revisa el contrato que rige este pago.'), r('Quais regras deve usar?', 'O empréstimo antigo dispensava tarifas. O novo contrato cobra após o prazo.', ['As regras aplicáveis do novo', 'A dispensa do empréstimo antigo'], 'A dispensa antiga não muda as novas regras.', 'Confira o contrato que rege esta parcela.')]),
      q('practice', [r('Which missing detail matters?', 'A fee applies after the receipt cutoff. You know only the sending time.', ['The receipt time and cutoff', 'Only the day you intended to pay'], 'The stated trigger depends on receipt, not intention.', 'Check the event the agreement uses to determine lateness.'), r('¿Qué dato faltante importa?', 'El cargo depende de la recepción tras el límite. Sabes cuándo enviaste, no cuándo llegó.', ['Hora de recepción y límite', 'Solo cuándo pensabas pagar'], 'La condición depende de la recepción, no de la intención.', 'Revisa qué evento usa el contrato para determinar atraso.'), r('Qual dado ausente importa?', 'A tarifa depende do recebimento após o limite. Você sabe quando enviou, não quando chegou.', ['Hora de recebimento e limite', 'Só quando pretendia pagar'], 'A condição depende do recebimento, não da intenção.', 'Veja qual evento o contrato usa para definir atraso.')]),
      q('transfer', [r('What does the clause establish?', 'A tool loan says missed installments pause future deliveries until payment. This installment was missed.', ['Future deliveries pause under this clause', 'Ownership automatically transfers today'], 'The clause states a delivery pause, not automatic ownership transfer.', 'Identify the precise contractual consequence stated here.'), r('¿Qué establece la cláusula?', 'Un préstamo de herramientas suspende entregas futuras hasta pagar si omites una cuota. La omitiste.', ['Se suspenden las entregas según la cláusula', 'La propiedad cambia automáticamente hoy'], 'La cláusula suspende entregas; no transfiere automáticamente la propiedad.', 'Identifica la consecuencia contractual específica indicada aquí.'), r('O que a cláusula estabelece?', 'Um empréstimo de ferramentas pausa entregas futuras até pagar se faltar uma parcela. Ela não foi paga.', ['As entregas param conforme a cláusula', 'A propriedade muda automaticamente hoje'], 'A cláusula pausa entregas; não transfere a propriedade de imediato.', 'Identifique a consequência exata informada nesta cláusula.')]),
    ],
  },
  {
    id: 'fe-production-credit-mechanics-09', title: t('What is pledged?', '¿Qué queda en garantía?', 'O que fica em garantia?'),
    relevance: t('A pledged asset can be at risk even when its value exceeds the loan.', 'Un bien en garantía puede estar en riesgo aunque valga más que el préstamo.', 'Um bem em garantia pode estar em risco mesmo valendo mais que o empréstimo.'),
    misconception: 'Collateral means the borrowed cash or limits every possible loss to the original loan amount.',
    example: t('A vehicle secures a loan. The borrowed amount is principal; the vehicle is collateral, subject to the agreement’s enforcement terms.', 'Un vehículo garantiza un préstamo. El dinero prestado es capital; el vehículo es garantía, sujeto a las condiciones del contrato.', 'Um veículo garante um empréstimo. O dinheiro emprestado é principal; o veículo é garantia, sujeito às regras do contrato.'),
    items: [
      q('guided', [r('Which is collateral?', 'A fictional agreement pledges a bicycle to secure borrowed cash.', ['The pledged bicycle', 'The cash borrowed'], 'The bicycle is the asset pledged to secure repayment.', 'Separate the pledged asset from the borrowed money.'), r('¿Cuál es la garantía?', 'Un contrato ficticio deja una bicicleta en garantía del dinero prestado.', ['La bicicleta comprometida', 'El dinero prestado'], 'La bicicleta es el bien que garantiza el pago.', 'Distingue el bien comprometido del dinero prestado.'), r('Qual é a garantia?', 'Um contrato fictício dá uma bicicleta em garantia do dinheiro emprestado.', ['A bicicleta dada em garantia', 'O dinheiro emprestado'], 'A bicicleta é o bem que garante o pagamento.', 'Separe o bem dado em garantia do dinheiro emprestado.')]),
      q('guided', [r('What is potentially at risk?', 'The agreement permits claiming the pledged machine after the stated default process.', ['The pledged machine', 'Only the cash originally borrowed'], 'The clause identifies the machine as the asset at risk.', 'Read which asset secures this loan.'), r('¿Qué bien está en riesgo?', 'El contrato permite reclamar la máquina en garantía tras el procedimiento de incumplimiento indicado.', ['La máquina en garantía', 'Solo el dinero originalmente prestado'], 'La cláusula identifica la máquina como el bien en riesgo.', 'Lee qué bien garantiza este préstamo.'), r('Qual bem está em risco?', 'O contrato permite tomar a máquina em garantia após o processo de falta de pagamento indicado.', ['A máquina em garantia', 'Só o dinheiro tomado emprestado'], 'A cláusula aponta a máquina como o bem em risco.', 'Leia qual bem garante este empréstimo.')]),
      q('practice', [r('Are these the same thing?', 'The loan names an outstanding balance and a pledged vehicle separately.', ['No, debt and collateral are distinct', 'Yes, the vehicle is the cash balance'], 'The debt amount and pledged asset are different concepts.', 'One is an amount owed; the other is an asset.'), r('¿Son lo mismo?', 'El préstamo distingue saldo pendiente y vehículo en garantía.', ['No, deuda y garantía son distintas', 'Sí, el vehículo es el saldo'], 'El importe de deuda y el bien comprometido son distintos.', 'Uno es dinero debido; el otro es un bien.'), r('São a mesma coisa?', 'O empréstimo distingue saldo devedor e veículo em garantia.', ['Não, dívida e garantia são distintos', 'Sim, o veículo é o saldo'], 'O valor da dívida e o bem dado em garantia diferem.', 'Um é dinheiro devido; o outro é um bem.')]),
      q('practice', [r('Does higher value remove the risk?', 'The pledged tool exceeds the loan’s value; the contract still names it as collateral.', ['No, it remains pledged', 'Yes, greater value cancels the pledge'], 'Higher value does not itself remove the contractual pledge.', 'Collateral depends on the agreement, not value alone.'), r('¿El mayor valor elimina el riesgo?', 'La herramienta vale más que el préstamo. El contrato la mantiene en garantía.', ['No, sigue comprometida', 'Sí, el valor mayor cancela la garantía'], 'Un valor mayor no elimina por sí mismo la garantía.', 'La garantía depende del contrato, no solo del valor.'), r('O maior valor elimina o risco?', 'A ferramenta vale mais que o empréstimo. O contrato a mantém em garantia.', ['Não, continua em garantia', 'Sim, o maior valor cancela a garantia'], 'Um valor maior não elimina por si só a garantia.', 'A garantia depende do contrato, não só do valor.')]),
      q('practice', [r('Does surrender settle everything?', 'The excerpt allows selling collateral but does not explain any remaining debt after sale.', ['More terms and local rules are needed', 'Surrender always erases every debt'], 'The excerpt does not establish treatment of any remaining debt.', 'Do not assume surrender and full settlement are identical.'), r('¿Entregar el bien liquida todo?', 'El extracto permite vender la garantía, pero no explica la deuda que pudiera quedar.', ['Faltan condiciones y reglas locales', 'Entregar siempre borra toda deuda'], 'El extracto no establece qué pasa con la deuda restante.', 'No supongas que entregar el bien equivale a liquidar todo.'), r('Entregar o bem quita tudo?', 'O trecho permite vender a garantia, mas não explica a dívida que pode restar.', ['Faltam regras do contrato e locais', 'Entregar sempre apaga toda dívida'], 'O trecho não define o que ocorre com a dívida restante.', 'Não suponha que entregar o bem seja quitar tudo.')]),
      q('transfer', [r('Identify the exposure.', 'A repair loan pledges your work equipment, not the item being repaired.', ['The work equipment is pledged', 'Only the repaired item is at risk'], 'The agreement names work equipment as collateral for this loan.', 'The financed purchase and the pledged asset can differ.'), r('Identifica el riesgo.', 'Un préstamo para reparar deja en garantía tu equipo de trabajo, no el artículo reparado.', ['El equipo de trabajo está comprometido', 'Solo está en riesgo el artículo reparado'], 'El contrato nombra el equipo de trabajo como garantía.', 'La compra financiada y el bien en garantía pueden diferir.'), r('Identifique o risco.', 'Um empréstimo para reparo dá seu equipamento de trabalho em garantia, não o item reparado.', ['O equipamento de trabalho está em garantia', 'Só o item reparado está em risco'], 'O contrato dá o equipamento de trabalho como garantia.', 'A compra financiada e o bem em garantia podem diferir.')]),
    ],
  },
  {
    id: 'fe-production-credit-mechanics-10', title: t('When a rate can change', 'Cuando la tasa puede cambiar', 'Quando a taxa pode mudar'),
    relevance: t('A payment affordable today may change if the agreement permits rate resets.', 'Un pago accesible hoy puede cambiar si el contrato permite ajustar la tasa.', 'Uma parcela que cabe hoje pode mudar se o contrato permite ajustar a taxa.'),
    misconception: 'A displayed initial payment is fixed forever even when a variable-rate clause permits recalculation.',
    example: t('This loan resets its rate at review dates. Higher rates can raise interest and payments under its stated formula.', 'Este préstamo ajusta su tasa en fechas de revisión. Una tasa mayor puede subir el interés y el pago previsto.', 'Este empréstimo ajusta a taxa nas datas de revisão. Uma taxa maior pode elevar juros e a parcela prevista.'),
    items: [
      q('guided', [r('Can the initial payment change?', 'The agreement recalculates payments when its variable rate resets.', ['Yes, under the reset terms', 'No, the first quote lasts forever'], 'The agreement explicitly permits recalculation at a rate reset.', 'Check the reset clause, not only the first quote.'), r('¿Puede cambiar el pago inicial?', 'El contrato recalcula pagos cuando se ajusta su tasa variable.', ['Sí, según las condiciones de ajuste', 'No, la primera cotización dura siempre'], 'El contrato permite recalcular cuando se ajusta la tasa.', 'Revisa la cláusula de ajuste, no solo la primera cotización.'), r('A parcela inicial pode mudar?', 'O contrato recalcula parcelas quando sua taxa variável é ajustada.', ['Sim, conforme as regras de ajuste', 'Não, a primeira cotação vale sempre'], 'O contrato permite recalcular quando a taxa muda.', 'Confira a regra de ajuste, não só a primeira cotação.')]),
      q('guided', [r('What needs checking?', 'A variable-rate offer shows the current payment alone.', ['Reset dates and calculation rules', 'Only the previous loan’s rate'], 'Reset terms explain when and how the payment can change.', 'Look for the timing and rule governing future recalculation.'), r('¿Qué debes revisar?', 'Una oferta de tasa variable muestra solo el pago actual.', ['Fechas y reglas de ajuste', 'Solo la tasa del préstamo anterior'], 'Las condiciones explican cuándo y cómo puede cambiar el pago.', 'Busca el momento y la regla de los ajustes futuros.'), r('O que deve conferir?', 'Uma oferta de taxa variável mostra só a parcela atual.', ['Datas e regras de ajuste', 'Só a taxa do empréstimo anterior'], 'As regras explicam quando e como a parcela pode mudar.', 'Busque a data e a regra dos ajustes futuros.')]),
      q('practice', [r('Which assumption is unsafe?', 'Your budget barely covers the initial payment; the contract allows it to rise.', ['Assuming the payment never rises', 'Testing a higher-payment scenario'], 'The no-increase assumption conflicts with the contract’s stated possibility.', 'Check whether the budget can withstand an allowed change.'), r('¿Qué suposición es frágil?', 'Tu presupuesto apenas cubre el pago inicial; el contrato permite aumentarlo.', ['Suponer que nunca subirá', 'Probar un escenario de pago mayor'], 'Suponer que no subirá contradice la posibilidad del contrato.', 'Revisa si el presupuesto soporta un cambio permitido.'), r('Qual suposição é frágil?', 'Seu orçamento mal cobre a parcela inicial; o contrato permite aumentá-la.', ['Supor que nunca vai subir', 'Testar um cenário de parcela maior'], 'Supor que não subirá contraria a possibilidade do contrato.', 'Confira se o orçamento suporta uma mudança permitida.')]),
      q('practice', [r('What does this cap establish?', 'The clause limits each reset’s increase, but permits repeated resets.', ['Each increase is limited', 'All future increases are impossible'], 'A limit per reset does not prohibit later permitted resets.', 'Distinguish a per-reset limit from a lifetime fixed rate.'), r('¿Qué establece este límite?', 'La cláusula limita el aumento de cada ajuste, pero permite ajustes repetidos.', ['Cada aumento tiene un límite', 'Todo aumento futuro es imposible'], 'Un límite por ajuste no prohíbe ajustes posteriores permitidos.', 'Distingue un límite por ajuste de una tasa fija permanente.'), r('O que este limite define?', 'A cláusula limita o aumento de cada ajuste, mas permite ajustes repetidos.', ['Cada aumento tem um limite', 'Todo aumento futuro é impossível'], 'Um limite por ajuste não proíbe ajustes futuros permitidos.', 'Separe o limite por ajuste de uma taxa fixa permanente.')]),
      q('practice', [r('Does this promise fix the rate?', 'An advertisement says “low payment”; the contract states variable pricing.', ['No, the variable clause still matters', 'Yes, “low” means fixed forever'], 'The adjective does not change the contract’s variable-rate clause.', 'Use the contract’s actual rate terms.'), r('¿La promesa fija la tasa?', 'Un anuncio llama bajo al pago inicial; el contrato indica tasa variable.', ['No, importa la cláusula variable', 'Sí, «bajo» significa fijo para siempre'], 'El adjetivo no cambia la cláusula de tasa variable.', 'Usa las condiciones reales de tasa del contrato.'), r('A promessa fixa a taxa?', 'Um anúncio chama a parcela inicial de baixa; o contrato indica taxa variável.', ['Não, importa a cláusula variável', 'Sim, “baixa” significa fixa para sempre'], 'O adjetivo não muda a cláusula de taxa variável.', 'Use as regras reais da taxa no contrato.')]),
      q('transfer', [r('Which budget check is needed?', 'Housing payments are fixed temporarily, then recalculated at the stated date.', ['Test the payment after the reset', 'Use only the temporary fixed payment'], 'The later reset can change the continuing housing commitment.', 'A temporary fixed period does not establish all future payments.'), r('¿Qué revisión del presupuesto falta?', 'Un préstamo de vivienda fija pagos al inicio y los recalcula en la fecha de ajuste.', ['Probar el pago después del ajuste', 'Usar solo el pago fijo temporal'], 'El ajuste posterior puede cambiar el compromiso de vivienda.', 'Un periodo fijo temporal no define todos los pagos futuros.'), r('Qual revisão do orçamento falta?', 'Um empréstimo de moradia fixa parcelas no início e recalcula na data de ajuste.', ['Testar a parcela após o ajuste', 'Usar só a parcela fixa temporária'], 'O ajuste posterior pode mudar o compromisso com a moradia.', 'Um período fixo temporário não define todas as parcelas futuras.')]),
    ],
  },
];
