import { t, row as r, item as q, calculation as c, i, op } from './helpers.mjs';
const retrieve = (id, item) => ({ ...item, retrieve: `fe-production-${id}` });
const sub = (...args) => op('subtract', ...args);
const add = (...args) => op('add', ...args);
const mul = (...args) => op('multiply', ...args);
const div = (...args) => op('divide', ...args);
export const creditReviews = [
  {
    id: 'fe-production-credit-mechanics-review-1', primary: 'fe-production-credit-mechanics-05',
    title: t('Read the whole loan', 'Revisa todo el préstamo', 'Confira todo o empréstimo'),
    outcome: 'Separate borrowed money, charges and principal reduction while comparing complete repayment schedules.',
    relevance: t('Check what each payment changes before deciding a loan is nearly repaid.', 'Revisa qué cambia con cada pago antes de pensar que casi terminaste.', 'Confira o que cada parcela muda antes de pensar que já está quase quitado.'),
    misconception: 'A payment’s size proves the same reduction in principal or the same total cost across loans.',
    items: [
      retrieve('credit-mechanics-01', q('practice', [r('Which entry is principal?', 'The repair contract separately lists the amount lent, a service fee and interest.', ['The amount lent', 'The service fee'], 'The amount lent is principal; the fee is a charge.', 'Separate borrowed money from the costs of borrowing.'), r('¿Qué registro es capital?', 'El contrato de reparación separa importe prestado, comisión de servicio e interés.', ['El importe prestado', 'La comisión de servicio'], 'El importe prestado es capital; la comisión es un cargo.', 'Distingue dinero prestado de los costos del préstamo.'), r('Qual registro é principal?', 'O contrato de reparo separa valor emprestado, tarifa de serviço e juros.', ['O valor emprestado', 'A tarifa de serviço'], 'O valor emprestado é principal; a tarifa é um encargo.', 'Separe dinheiro emprestado dos custos do empréstimo.') ])),
      retrieve('credit-mechanics-02', c('practice', t('Complete repayment total?', '¿Total completo devuelto?', 'Total completo devolvido?'), t('Equipment loan: 4 payments of 18 plus a closing payment of 8. All charges included.', 'Préstamo de equipo: 4 pagos de 18 y un pago final de 8. Cargos incluidos.', 'Empréstimo de equipamento: 4 parcelas de 18 e pagamento final de 8. Encargos incluídos.'), [80,72,26], t('Include every regular payment and the separate closing payment.', 'Incluye cada pago regular y el pago final separado.', 'Inclua cada parcela regular e o pagamento final separado.'), t('The final payment belongs in the complete schedule.', 'El pago final forma parte del calendario completo.', 'O pagamento final faz parte do calendário completo.'), [4,18,8], add(mul(i(0),i(1)),i(2)))),
      retrieve('credit-mechanics-03', c('practice', t('Interest for this period?', '¿Interés de este periodo?', 'Juros deste período?'), t('Current interest base 180; period rate 5%. No other charges.', 'Base actual de interés 180; tasa del periodo 5%. Sin otros cargos.', 'Base atual dos juros 180; taxa do período 5%. Sem outros encargos.'), [9,5,185], t('Apply the period rate to the stated current interest base.', 'Aplica la tasa del periodo a la base actual indicada.', 'Aplique a taxa do período à base atual indicada.'), t('The percentage is not itself the money charge.', 'El porcentaje no es por sí mismo el cargo en dinero.', 'O percentual não é por si só o encargo em dinheiro.'), [180,5], div(mul(i(0),i(1)),{constant:100}))),
      retrieve('credit-mechanics-04', c('practice', t('Principal reduction?', '¿Reducción de capital?', 'Redução do principal?'), t('Payment 36 includes interest 9 and fee 2; the rest reduces principal.', 'Pago 36 incluye interés 9 y comisión 2; el resto reduce capital.', 'Parcela 36 inclui juros 9 e tarifa 2; o resto reduz principal.'), [25,27,36], t('Remove both charges to identify the principal component.', 'Quita ambos cargos para identificar la parte de capital.', 'Retire ambos os encargos para identificar a parte do principal.'), t('A fee and interest do not repay principal in this example.', 'Aquí la comisión y el interés no devuelven capital.', 'Aqui a tarifa e os juros não devolvem principal.'), [36,9,2], sub(sub(i(0),i(1)),i(2)))),
      retrieve('credit-mechanics-05', c('practice', t('Updated principal?', '¿Capital actualizado?', 'Principal atualizado?'), t('Principal 130; payment 35 includes interest 5. No other charges.', 'Capital 130; pago 35 incluye interés 5. Sin otros cargos.', 'Principal 130; parcela 35 inclui juros 5. Sem outros encargos.'), [100,95,105], t('Subtract only the principal portion from the opening principal.', 'Resta solo la parte de capital al capital inicial.', 'Subtraia só a parte do principal do principal inicial.'), t('Separate interest before updating the borrowed amount remaining.', 'Separa el interés antes de actualizar el dinero prestado restante.', 'Separe os juros antes de atualizar o dinheiro emprestado restante.'), [130,35,5], sub(i(0),sub(i(1),i(2))))),
      retrieve('credit-mechanics-06', q('practice', [r('Which loan costs less overall?', 'Same borrowed amount: A total 240 over 6 months; B total 260 over 10. All charges included.', ['A', 'B'], 'The complete total, not the smaller monthly amount, decides cost.', 'Keep duration and total repayment separate.'), r('¿Qué préstamo cuesta menos en total?', 'Mismo préstamo: A suma 240 en 6 meses; B suma 260 en 10. Cargos incluidos.', ['A', 'B'], 'El total completo determina el costo, no la mensualidad menor.', 'Distingue duración y total devuelto.'), r('Qual empréstimo custa menos no total?', 'Mesmo empréstimo: A soma 240 em 6 meses; B soma 260 em 10. Encargos incluídos.', ['A', 'B'], 'O total completo define o custo, não a parcela menor.', 'Separe duração e total devolvido.') ])),
      retrieve('usable-money-06', q('practice', [r('Is this earned income?', 'A relative lends money under an explicit repayment agreement.', ['No, it creates a repayment obligation', 'Yes, because the cash arrived'], 'Received loan money comes with the stated repayment obligation.', 'Cash received and income earned are different here.'), r('¿Es ingreso ganado?', 'Un familiar presta dinero con un acuerdo explícito de devolución.', ['No, crea una obligación de devolver', 'Sí, porque llegó efectivo'], 'El dinero prestado recibido trae la obligación de devolverlo.', 'Recibir efectivo y ganar ingresos son distintos aquí.'), r('É renda ganha?', 'Um familiar empresta dinheiro com acordo explícito de devolução.', ['Não, cria obrigação de devolver', 'Sim, porque o dinheiro chegou'], 'O dinheiro emprestado recebido traz a obrigação de devolução.', 'Receber dinheiro e ganhar renda são coisas distintas aqui.') ])),
      retrieve('credit-mechanics-05', c('transfer', t('Remaining principal after closure payment?', '¿Capital tras el pago de cierre?', 'Principal após o pagamento final?'), t('Remaining principal 42. Closing payment 50 includes interest 8, with no other charges.', 'Capital pendiente 42. Pago de cierre 50 incluye interés 8, sin otros cargos.', 'Principal restante 42. Pagamento final 50 inclui juros 8, sem outros encargos.'), [0,8,42], t('Removing interest leaves exactly enough payment to clear principal.', 'Al quitar el interés, el pago liquida exactamente el capital.', 'Retirando os juros, o pagamento quita exatamente o principal.'), t('Do not treat the interest portion as principal repayment.', 'No trates la parte de interés como devolución de capital.', 'Não trate a parte dos juros como devolução do principal.'), [42,50,8], sub(i(0),sub(i(1),i(2))))),
    ],
  },
  {
    id: 'fe-production-credit-mechanics-review-2', primary: 'fe-production-credit-mechanics-07',
    title: t('Check the borrowing decision', 'Revisa la decisión de crédito', 'Confira a decisão de crédito'),
    outcome: 'Check payment feasibility, contractual risks and comparable cost disclosures before accepting a fictional borrowing offer.',
    relevance: t('Combine the cash calendar with the loan’s actual terms.', 'Combina el calendario de dinero con las condiciones reales del préstamo.', 'Combine o calendário do dinheiro com as regras reais do empréstimo.'),
    misconception: 'A low headline rate proves a loan affordable and harmless regardless of its terms.',
    items: [
      retrieve('credit-mechanics-07', q('practice', [r('Does the new payment fit?', 'Free cash after essentials: 40; existing loan: 25; new loan: 20, both due today.', ['No, their combined amount exceeds the remainder', 'Yes, each loan alone fits'], 'The payments share the same available money and deadline.', 'Count existing debt payments before adding a new one.'), r('¿Cabe el pago nuevo?', 'Libre tras lo esencial: 40; préstamo existente: 25; nuevo: 20, ambos vencen hoy.', ['No, juntos superan el resto', 'Sí, cada préstamo solo cabe'], 'Los pagos usan el mismo dinero y fecha.', 'Cuenta pagos de deuda existentes antes de añadir otro.'), r('A nova parcela cabe?', 'Livre após o essencial: 40; empréstimo existente: 25; novo: 20, ambos vencem hoje.', ['Não, juntos superam a sobra', 'Sim, cada empréstimo sozinho cabe'], 'As parcelas usam o mesmo dinheiro e a mesma data.', 'Conte parcelas existentes antes de acrescentar outra.') ])),
      retrieve('credit-mechanics-08', q('practice', [r('What follows from the clause?', 'A missed Friday payment triggers the stated fee. The money arrives Monday.', ['The stated trigger was met', 'Monday automatically counts as Friday'], 'The payment arrived after this agreement’s stated deadline.', 'Use the agreed receipt deadline, not the eventual arrival.'), r('¿Qué implica la cláusula?', 'Omitir el pago del viernes activa el cargo indicado. El dinero llega el lunes.', ['Se cumplió la condición del cargo', 'El lunes cuenta automáticamente como viernes'], 'El pago llegó después del plazo indicado en este contrato.', 'Usa el plazo de recepción, no la llegada posterior.'), r('O que implica a cláusula?', 'Não pagar sexta gera a tarifa indicada. O dinheiro chega segunda.', ['A condição da tarifa ocorreu', 'Segunda conta automaticamente como sexta'], 'O pagamento chegou após o prazo indicado neste contrato.', 'Use o prazo de recebimento, não a chegada posterior.') ])),
      retrieve('credit-mechanics-09', q('practice', [r('Identify the pledged asset.', 'A training loan uses your vehicle as collateral under the stated agreement.', ['The vehicle', 'The training certificate'], 'The contract names the vehicle, not the purchased training.', 'The funded purpose and pledged asset need not match.'), r('Identifica el bien en garantía.', 'Un préstamo de capacitación usa tu vehículo como garantía según el contrato.', ['El vehículo', 'El certificado de capacitación'], 'El contrato nombra el vehículo, no la capacitación comprada.', 'El propósito financiado y la garantía no tienen que coincidir.'), r('Identifique o bem em garantia.', 'Um empréstimo para curso usa seu veículo como garantia pelo contrato.', ['O veículo', 'O certificado do curso'], 'O contrato indica o veículo, não o curso comprado.', 'A finalidade financiada e a garantia não precisam coincidir.') ])),
      retrieve('credit-mechanics-10', q('practice', [r('Which payment needs testing?', 'An initial fixed period ends before the loan ends; afterward, a variable-rate reset applies.', ['The payment after the reset', 'Only the initial fixed payment'], 'The later rate reset can change the remaining payments.', 'A temporary fixed period does not cover the entire loan.'), r('¿Qué pago debes probar?', 'El periodo fijo inicial termina antes del préstamo; después se ajusta la tasa variable.', ['El pago después del ajuste', 'Solo el pago fijo inicial'], 'El ajuste posterior puede cambiar los pagos restantes.', 'Un periodo fijo temporal no cubre todo el préstamo.'), r('Qual parcela deve testar?', 'O período fixo inicial termina antes do empréstimo; depois há ajuste de taxa variável.', ['A parcela após o ajuste', 'Só a parcela fixa inicial'], 'O ajuste posterior pode mudar as parcelas restantes.', 'Um período fixo temporário não cobre todo o empréstimo.') ])),
      retrieve('credit-mechanics-11', q('practice', [r('Can these figures be compared directly?', 'A daily nominal quote is compared with an annual effective quote.', ['No, align period and compounding', 'Yes, choose the smaller printed number'], 'Different periods and rate definitions need a common basis.', 'Match the period and interest treatment before ranking.'), r('¿Puedes comparar directamente las cifras?', 'Se compara una tasa diaria nominal con una tasa anual efectiva.', ['No, iguala periodo y capitalización', 'Sí, elige la menor cifra impresa'], 'Los periodos y definiciones distintos necesitan una base común.', 'Iguala periodo y tratamiento del interés antes de ordenar.'), r('Pode comparar diretamente os números?', 'Compara-se uma taxa diária nominal com uma taxa anual efetiva.', ['Não, iguale período e capitalização', 'Sim, escolha o menor número impresso'], 'Períodos e definições diferentes precisam de uma base comum.', 'Iguale período e tratamento dos juros antes de ordenar.') ])),
      retrieve('credit-mechanics-12', q('practice', [r('Which missing information matters?', 'The annual disclosure does not say whether the separately listed charge is included.', ['The measure’s included-charge definition', 'Only its percentage size'], 'Scope determines whether adding the charge would double-count it.', 'Clarify inclusion before calculating the complete comparison.'), r('¿Qué información faltante importa?', 'El indicador anual no aclara si incluye el cargo que aparece por separado.', ['La definición de cargos incluidos', 'Solo el tamaño del porcentaje'], 'El alcance determina si añadir el cargo lo contaría doble.', 'Aclara qué incluye antes de calcular la comparación completa.'), r('Qual informação ausente importa?', 'O indicador anual não esclarece se inclui o encargo listado à parte.', ['A definição dos encargos incluídos', 'Só o tamanho do percentual'], 'O alcance define se somar o encargo contaria duas vezes.', 'Esclareça o que está incluído antes de comparar o total.') ])),
      retrieve('usable-money-06', q('practice', [r('Does receiving a loan settle the problem?', 'Emergency cash arrives as a loan with a stated repayment obligation.', ['It adds cash and a future obligation', 'It is income with nothing owed'], 'The loan improves current cash but creates repayment obligations.', 'Keep the receipt and its future obligation visible together.'), r('¿Recibir el préstamo resuelve todo?', 'Llega efectivo de emergencia como préstamo con obligación de devolverlo.', ['Añade efectivo y una obligación futura', 'Es ingreso sin nada pendiente'], 'El préstamo mejora el efectivo actual y crea pagos futuros.', 'Mantén visibles la entrada y su obligación futura.'), r('Receber o empréstimo resolve tudo?', 'Chega dinheiro de emergência como empréstimo com obrigação de devolver.', ['Acrescenta dinheiro e obrigação futura', 'É renda sem nada devido'], 'O empréstimo melhora o dinheiro atual e cria pagamentos futuros.', 'Mantenha visíveis a entrada e sua obrigação futura.') ])),
      retrieve('credit-mechanics-07', q('transfer', [r('Is this feasible on time?', 'A seasonal worker’s money arrives after the proposed installment deadline; no reserve covers the gap.', ['The payment timing is unfunded', 'Seasonal totals are sufficient later'], 'Later income cannot cover this earlier unfunded deadline.', 'Test the due date, not just eventual total earnings.'), r('¿El plan es viable a tiempo?', 'El ingreso temporal llega después del vencimiento propuesto; no hay reserva para cubrir el desfase.', ['No, falta dinero en la fecha', 'Sí, los totales alcanzan después'], 'El ingreso posterior no cubre este vencimiento sin fondos.', 'Prueba la fecha de pago, no solo los ingresos finales.'), r('O plano cabe no prazo?', 'A renda temporária chega depois do vencimento proposto; não há reserva para cobrir o intervalo.', ['Não, falta dinheiro na data', 'Sim, os totais bastam depois'], 'A renda posterior não cobre este vencimento sem fundos.', 'Teste a data de pagamento, não só a renda final.') ])),
    ],
  },
];
