import {t,item,row,calculation as c,i,op,worked} from './helpers.mjs';
const q=(role,...texts)=>item(role,texts.map(x=>row(...x))),pct=(x,y)=>op('divide',op('multiply',x,y),{constant:100});
export const debtOrder=[{
 id:'fe-production-debt-recovery-03',title:t('Compare repayment orders','Compara órdenes de pago','Compare ordens de pagamento'),
 relevance:t('After essentials and required payments, compare what the same feasible extra payment changes.','Tras esenciales y pagos exigidos, compara qué cambia el mismo pago extra viable.','Após essenciais e pagamentos exigidos, compare o que muda o mesmo pagamento extra viável.'),
 misconception:'Confusing highest-rate-first with smallest-balance-first, or comparing them using different available surpluses.',
 example:t('Highest-rate-first targets cost; smallest-balance-first targets an earlier account closure. Compare both using the same feasible extra payment and actual terms.','Mayor tasa primero busca reducir costo; menor saldo primero busca cerrar una cuenta antes. Compara con igual pago extra viable.','Maior taxa primeiro busca reduzir custo; menor saldo primeiro busca fechar uma conta antes. Compare com igual pagamento extra viável.'),
 guidedBoard:worked(t('Repay 100 now; otherwise outstanding one year. Model: fixed yearly simple interest, 20% or 10%; no compounding or fees.','Paga 100 extra hoy; seguirían pendientes un año. Modelo: interés simple anual fijo, 20% o 10%; sin capitalización ni cargos.','Pague 100 extras hoje; ficariam pendentes um ano. Modelo: juros simples anuais fixos, 20% ou 10%; sem capitalização nem tarifas.'),[
 {expression:'100 * 20 / 100',result:20,spoken:t('One-year interest avoided on the higher-rate principal.','Interés anual evitado sobre capital a tasa mayor.','Juros anuais evitados sobre principal à taxa maior.')},
 {expression:'100 * 10 / 100',result:10,spoken:t('One-year interest avoided on the lower-rate principal.','Interés anual evitado sobre capital a tasa menor.','Juros anuais evitados sobre principal à taxa menor.')},
 {expression:'20 - 10',result:10,spoken:t('Difference under equal duration and no extra fees.','Diferencia con igual duración y sin cargos extra.','Diferença com mesmo prazo e sem tarifas extras.')},
 ],t('Same extra principal payment; different modeled interest costs avoided.','Mismo pago extra de capital; distintos costos de interés evitados.','Mesmo pagamento extra de principal; diferentes custos de juros evitados.'),t('Compare the same extra amount and period.','Compara el mismo monto extra y periodo.','Compare o mesmo valor extra e período.')),
 items:[
 q('guided',
 ['Smallest-balance-first targets which debt?','A balance 600; B balance 200; required payments covered.',['B','A','Whichever rate is higher'],'This method orders by remaining balance, not interest rate.','Find the smaller outstanding balance.'],
 ['¿Cuál elige menor saldo primero?','Saldo A 600; saldo B 200; pagos exigidos cubiertos.',['B','A','La tasa que sea mayor'],'Este método ordena por saldo restante, no por tasa.','Busca el saldo pendiente menor.'],
 ['Qual escolhe menor saldo primeiro?','Saldo A 600; saldo B 200; pagamentos exigidos cobertos.',['B','A','A taxa que for maior'],'Esse método ordena pelo saldo restante, não pela taxa.','Ache o menor saldo pendente.']),
 c('practice',t('Interest avoided?','¿Interés evitado?','Juros evitados?'),t('Repay 200 now; otherwise outstanding one year. Model: fixed 15% yearly simple interest, no compounding or fees.','Paga 200 extra hoy; seguirían pendientes un año. Modelo: interés simple anual fijo 15%, sin capitalización ni cargos.','Pague 200 extras hoje; ficariam pendentes um ano. Modelo: juros simples anuais fixos 15%, sem capitalização nem tarifas.'),[30,15,215],t('200 × 15% = 30 under the stated one-year model.','200 × 15% = 30 bajo el modelo anual indicado.','200 × 15% = 30 sob o modelo anual informado.'),t('Apply the rate to the same extra principal reduction.','Aplica tasa a la misma reducción extra de capital.','Aplique taxa à mesma redução extra de principal.'),[200,15],pct(i(0),i(1))),
 c('practice',t('Balance remaining?','¿Saldo restante?','Saldo restante?'),t('Smaller debt after required payment: 250; feasible extra payment: 100; no new charges.','Deuda menor tras pago exigido: 250; pago extra viable: 100; sin cargos nuevos.','Dívida menor após pagamento exigido: 250; pagamento extra viável: 100; sem novas tarifas.'),[150,250,350],t('250 − 100 = 150 remains; this debt is not closed yet.','250 − 100 = 150 queda; la deuda aún no termina.','250 − 100 = 150 resta; a dívida ainda não acaba.'),t('Apply only the extra amount actually available.','Aplica solo monto extra realmente disponible.','Aplique só o valor extra de fato disponível.'),[250,100],op('subtract',i(0),i(1))),
 q('practice',
 ['Fair comparison?','Plan A uses extra 100; B uses unexplained extra 300.',['No, use the same feasible surplus','Yes, larger payment proves better method','Yes, any assumed surplus is available'],'Different funding assumptions do not isolate the effect of repayment order.','Hold available money constant when comparing methods.'],
 ['¿Es comparación justa de métodos?','Un plan usa extra 100; otro extra 300 de fondos no identificados.',['No, usa el mismo excedente viable','Sí, pago mayor prueba mejor método','Sí, cualquier excedente supuesto está disponible'],'Fondos supuestos distintos no aíslan el efecto del orden de pago.','Conserva dinero disponible igual al comparar métodos.'],
 ['É comparação justa de métodos?','Um plano usa extra 100; outro extra 300 sem fonte indicada.',['Não, use a mesma sobra viável','Sim, pagamento maior prova melhor método','Sim, qualquer sobra suposta está disponível'],'Fontes diferentes não isolam o efeito da ordem de pagamento.','Mantenha dinheiro disponível igual ao comparar métodos.']),
 q('transfer',
 ['Highest-rate-first, then smallest-balance-first?','Extra 50 after essentials/minimums. Debts: A 400 at 20% yearly; B 100 at 10% yearly.',['A; B','B; A'],'With the same extra 50, highest-rate-first selects A; smallest-balance-first selects B.','Compare rates for the first method and balances for the second.'],
 ['¿Mayor tasa primero; luego menor saldo?','Sobran 50 tras esenciales y mínimos. Deudas: A 400 al 20% anual; B 100 al 10% anual.',['A; B','B; A'],'Con los mismos 50 extra, mayor tasa elige A; menor saldo elige B.','Compara tasas para el primer método y saldos para el segundo.'],
 ['Maior taxa primeiro; depois menor saldo?','Sobram 50 após essenciais e mínimos. Dívidas: A 400 a 20% anuais; B 100 a 10% anuais.',['A; B','B; A'],'Com os mesmos 50 extras, maior taxa escolhe A; menor saldo escolhe B.','Compare taxas para o primeiro método e saldos para o segundo.']),
 ],
}];
