import {t,item,row,calculation as c,i,op} from './helpers.mjs';
const q=(role,...texts)=>item(role,texts.map(x=>row(...x))),m=(x,y)=>op('multiply',x,y),a=(x,y)=>op('add',x,y),s=(x,y)=>op('subtract',x,y);
const primary='fe-production-credit-products-01',target=n=>`fe-production-debt-recovery-${String(n).padStart(2,'0')}`;
const review=(n,title,relevance,items,targets)=>({id:`fe-production-debt-recovery-review-${n}`,primary:targets.at(-1),title,relevance,outcome:'Apply previously taught debt records, consequences and feasible-payment comparisons in a new household situation.',misconception:'Choose an attractive payment headline without verifying the actual obligation, cost, date and feasibility.',items:items.map((x,i)=>({...x,retrieve:targets[i]}))});
export const debtReviews=[review(1,t('Decide from complete debt records','Decide con registros completos de deuda','Decida com registros completos de dívida'),t('Connect the debt list, consequences, extra-payment choices and current statements.','Relaciona lista de deudas, consecuencias, pagos extra y estados actuales.','Relacione lista de dívidas, efeitos, pagamentos extras e extratos atuais.'),[
 q('practice',
 ['How to record these notices?','Two differently branded notices identify the same original loan.',['Match references before adding another debt','Count both notices as separate borrowing','Ignore whichever notice arrived later'],'An inventory counts obligations, not the number of notices.','Check whether both records refer to the same debt.'],
 ['¿Cómo tratar esto en el inventario?','Dos avisos con marcas distintas identifican el mismo préstamo original.',['Comparar referencias antes de añadir otra deuda','Contar ambos avisos como préstamos separados','Ignorar el aviso que llegó después'],'Un inventario cuenta obligaciones, no cantidad de avisos.','Revisa si ambos registros corresponden a la misma deuda.'],
 ['Como tratar isso na lista?','Dois avisos com marcas diferentes indicam o mesmo empréstimo original.',['Comparar referências antes de somar outra dívida','Contar ambos os avisos como empréstimos separados','Ignorar o aviso que chegou depois'],'Uma lista conta obrigações, não quantidade de avisos.','Confira se ambos os registros se referem à mesma dívida.']),
 q('practice',
 ['Before ranking by rate?','Verified notice: essential service ends tomorrow; another debt’s rate is higher.',['Assess the immediate essential consequence','Always pay the higher rate regardless','Rank by call count'],'The immediate stated consequence matters alongside interest cost.','Check essential needs and deadlines before assigning extra payments.'],
 ['¿Qué antecede a ordenar solo por tasa?','Un aviso verificado amenaza servicio esencial mañana; otra deuda tiene mayor tasa.',['Evaluar la consecuencia esencial inmediata','Siempre pagar mayor tasa sin considerar nada','Ordenar solo por llamadas del acreedor'],'La consecuencia inmediata indicada importa además del costo de interés.','Revisa esenciales y plazos antes de asignar pagos extra.'],
 ['O que conferir antes das taxas?','Um aviso conferido ameaça serviço essencial amanhã; outra dívida tem maior taxa.',['Avaliar o efeito essencial imediato','Sempre pagar maior taxa sem considerar nada','Ordenar só por ligações do credor'],'O efeito imediato informado importa além do custo de juros.','Confira essenciais e prazos antes de destinar pagamentos extras.']),
 q('practice',
 ['Which target follows highest-rate-first?','Minimums covered; same surplus; A balance 100 at 12% annually; B balance 300 at 20% annually.',['B: higher rate','A: smaller balance','Split by call frequency'],'This method selects the higher rate after checking feasibility and consequences.','Compare rates on the same stated period.'],
 ['¿Qué elige mayor tasa primero?','Mínimos cubiertos; igual excedente; A saldo 100 al 12% anual; B saldo 300 al 20% anual.',['B: mayor tasa','A: menor saldo','Dividir según llamadas de acreedores'],'Este método elige mayor tasa tras revisar viabilidad y consecuencias.','Compara tasas del mismo periodo indicado.'],
 ['O que escolhe maior taxa primeiro?','Mínimos cobertos; mesma sobra; A saldo 100 a 12% ao ano; B saldo 300 a 20% ao ano.',['B: maior taxa','A: menor saldo','Dividir conforme ligações dos credores'],'Esse método escolhe maior taxa após conferir viabilidade e efeitos.','Compare taxas do mesmo período informado.']),
 c('practice',t('Capacity before this proposed payment?','¿Capacidad antes de este pago propuesto?','Capacidade antes deste pagamento proposto?'),t('Reliable income 260; essentials 200; other required payments 40; no other resources.','Ingreso fiable 260; esenciales 200; otros pagos exigidos 40; sin otros recursos.','Renda confiável 260; essenciais 200; outros pagamentos exigidos 40; sem outros recursos.'),[20,60,260],t('260 − 200 − 40 = 20 available under these facts.','260 − 200 − 40 = 20 disponible según estos hechos.','260 − 200 − 40 = 20 disponível segundo esses fatos.'),t('Account for existing necessities and commitments.','Considera necesidades y compromisos existentes.','Considere necessidades e compromissos existentes.'),[260,200,40],s(s(i(0),i(1)),i(2))),
 c('practice',t('Stated minimum payment?','¿Pago mínimo indicado?','Pagamento mínimo informado?'),t('Fictional card statement: balance 460; minimum payment 25; due on day 15.','Estado ficticio de tarjeta: saldo 460; pago mínimo 25; vence día 15.','Extrato fictício do cartão: saldo 460; pagamento mínimo 25; vence dia 15.'),[25,460,15],t('The minimum field is 25; it is not the whole balance.','El campo mínimo dice 25; no es todo el saldo.','O campo mínimo diz 25; não é todo o saldo.'),t('Read the field named by the question.','Lee el campo que pide la pregunta.','Leia o campo pedido pela pergunta.'),[460,25,15],i(1)),
 q('transfer',
 ['Next step?','Minimum 35 tomorrow; after essentials, 20 available. Next income arrives next week.',['Request an arrangement before the deadline','Promise 35 tomorrow','Count future income today'],'The required payment exceeds money available before its deadline.','Use available funds and contact the creditor before the deadline.'],
 ['¿Siguiente paso?','Mínimo 35 mañana; tras esenciales, dispones de 20. Próximo ingreso: siguiente semana.',['Pedir un acuerdo antes del vencimiento','Prometer 35 mañana','Contar hoy ingreso futuro'],'El pago exigido supera el dinero disponible antes del vencimiento.','Usa fondos disponibles y contacta al acreedor antes del vencimiento.'],
 ['Próximo passo?','Mínimo 35 amanhã; após essenciais, há 20 disponíveis. Próxima renda: semana que vem.',['Pedir um acordo antes do vencimento','Prometer 35 amanhã','Contar renda futura hoje'],'O pagamento exigido supera o dinheiro disponível antes do vencimento.','Use fundos disponíveis e contate o credor antes do vencimento.']),
],[target(1),target(2),target(3),target(4),primary,target(4)]),
review(2,t('Check the complete recovery proposal','Revisa la propuesta completa de recuperación','Confira a proposta completa de recuperação'),t('Compare full costs and real capacity while checking the people offering help.','Compara costos completos y capacidad real verificando a quienes ofrecen ayuda.','Compare custos completos e capacidade real conferindo quem oferece ajuda.'),[
 c('practice',t('Replacement total from today?','¿Total del reemplazo desde hoy?','Total da troca a partir de hoje?'),t('Fictional revision: 10 payments of 32 plus separate fee 20; no other costs.','Revisión ficticia: 10 pagos de 32 más comisión aparte 20; sin otros costos.','Revisão fictícia: 10 parcelas de 32 mais tarifa separada 20; sem outros custos.'),[340,320,52],t('10 × 32 + 20 = 340.','10 × 32 + 20 = 340.','10 × 32 + 20 = 340.'),t('Include all payments and the separate fee.','Incluye todos los pagos y comisión separada.','Inclua todas as parcelas e tarifa separada.'),[10,32,20],a(m(i(0),i(1)),i(2))),
 c('practice',t('Extra total cost of consolidation?','¿Costo total adicional de consolidar?','Custo total extra de consolidar?'),t('Remaining existing total 600; consolidation total 660; same date and all charges included.','Total pendiente actual 600; total consolidado 660; misma fecha y todos los cargos incluidos.','Total restante atual 600; total consolidado 660; mesma data e todas as tarifas incluídas.'),[60,660,1260],t('660 − 600 = 60 more, despite any smaller installment.','660 − 600 = 60 más, aunque la cuota sea menor.','660 − 600 = 60 a mais, mesmo com parcela menor.'),t('Compare totals from the same decision date.','Compara totales desde la misma fecha de decisión.','Compare totais a partir da mesma data de decisão.'),[600,660],s(i(1),i(0))),
 q('practice',
 ['What must precede payment?','A caller guarantees debt erasure, demanding advance payment without verifiable terms.',['Independent verification and written terms','A test payment trusting the guarantee','Sharing access to speed recovery'],'A promised result does not replace checkable authority and terms.','Do not let pressure substitute for verification.'],
 ['¿Qué debe preceder a cualquier pago?','Alguien garantiza borrar deuda, exige anticipo y rechaza condiciones verificables.',['Verificación independiente y condiciones escritas','Pagar prueba porque la garantía suena cierta','Compartir código para acelerar recuperación'],'Prometer resultado no reemplaza autoridad y condiciones verificables.','No dejes que presión sustituya verificación.'],
 ['O que deve vir antes de qualquer pagamento?','Alguém garante apagar dívida, exige adiantamento e recusa regras que possa conferir.',['Conferência independente e regras por escrito','Pagar teste porque a garantia parece certa','Compartilhar código para acelerar recuperação'],'Prometer resultado não substitui poder e regras que possa conferir.','Não deixe pressão substituir conferência.']),
 q('practice',
 ['Viable next step?','Essentials and required payments exceed income; optional costs are zero.',['Seek qualified help using actual records','Invent spare income to complete the plan','Assume every shortfall is overspending'],'An infeasible plan requires realistic options, not invented capacity.','Bring the debt inventory and essential-cost evidence.'],
 ['¿Cómo sería un siguiente paso viable?','Esenciales y pagos exigidos superan ingreso aun sin ningún gasto opcional.',['Buscar ayuda local calificada con registros reales','Inventar ingreso sobrante para completar plan','Suponer que todo faltante es derroche'],'Un plan inviable exige opciones reales, no capacidad inventada.','Lleva inventario de deuda y evidencia de costos esenciales.'],
 ['Como seria um próximo passo viável?','Essenciais e pagamentos exigidos superam renda mesmo sem gasto opcional algum.',['Buscar ajuda local qualificada com registros reais','Inventar renda sobrando para completar plano','Supor que toda falta é desperdício'],'Um plano inviável exige opções reais, não capacidade inventada.','Leve lista de dívidas e provas dos custos essenciais.']),
 c('practice',t('Full statement balance?','¿Saldo total del estado?','Saldo total do extrato?'),t('Fictional statement: balance 520; minimum 30; deadline day 18.','Estado ficticio: saldo 520; mínimo 30; vence día 18.','Extrato fictício: saldo 520; mínimo 30; vence dia 18.'),[520,30,18],t('The balance field is 520, distinct from minimum and deadline.','El campo saldo es 520, distinto de mínimo y vencimiento.','O campo saldo é 520, diferente de mínimo e vencimento.'),t('Find the total balance field.','Busca el campo saldo total.','Busque o campo saldo total.'),[520,30,18],i(0)),
 c('transfer',t('Feasible plan costs how much more?','¿Cuánto más cuesta el plan viable?','Quanto mais custa o plano viável?'),t('Monthly capacity after essentials: 25. Remaining monthly schedules, fees included: old 5 payments of 30; replacement 8 of 20.','Capacidad mensual tras esenciales: 25. Calendarios mensuales pendientes, cargos incluidos: anterior 5 pagos de 30; reemplazo 8 de 20.','Capacidade mensal após essenciais: 25. Calendários mensais restantes, tarifas incluídas: anterior 5 parcelas de 30; troca 8 de 20.'),[10,5,150],t('The replacement fits monthly capacity but increases total remaining repayment.','El reemplazo cabe mensualmente, pero aumenta el total pendiente de pago.','A troca cabe mensalmente, mas aumenta o total restante a pagar.'),t('Choose the affordable monthly payment, then compare complete totals.','Identifica la mensualidad viable; después compara los totales completos.','Identifique a parcela viável; depois compare os totais completos.'),[25,5,30,8,20],s(m(i(3),i(4)),m(i(1),i(2)))),
],[target(5),target(6),target(7),target(8),primary,target(6)])];
