import {t,calculation as c,item,row,i,op} from './helpers.mjs';
const a=(x,y)=>op('add',x,y),s=(x,y)=>op('subtract',x,y),m=(x,y)=>op('multiply',x,y),d=(x,y)=>op('divide',x,y),h={constant:100};
const q=(role,...texts)=>item(role,texts.map(x=>row(...x)));
const pct=(x,y)=>d(m(x,y),h),grown=(x,y)=>a(x,pct(x,y));
const primary='fe-production-financial-math-08',target=n=>`fe-production-time-inflation-${String(n).padStart(2,'0')}`;
const review=(n,title,relevance,items,targets)=>({id:`fe-production-time-inflation-review-${n}`,primary,title,relevance,outcome:'Apply previously learned growth, price and percentage relationships under a new scenario’s explicit assumptions.',misconception:'Reuse a previous answer without checking the current base, period, contributions or prices.',items:items.map((x,i)=>({...x,retrieve:targets[i]}))});
export const timeReviews=[review(1,t('Follow the source of modeled growth','Sigue el origen del crecimiento modelado','Siga a origem do crescimento modelado'),t('Connect rates, periods, retained gains and added money.','Relaciona tasas, periodos, ganancias conservadas y dinero añadido.','Relacione taxas, períodos, ganhos mantidos e dinheiro somado.'),[
 c('practice',t('Total simple interest?','¿Interés simple total?','Juros simples totais?'),t('Fictional principal 800; annual rate 3%; duration 2 years; simple interest.','Capital ficticio 800; tasa anual 3%; duración 2 años; interés simple.','Principal fictício 800; taxa anual 3%; prazo 2 anos; juros simples.'),[48,24,848],t('800 × 3% × 2 = 48 interest.','800 × 3% × 2 = 48 de interés.','800 × 3% × 2 = 48 de juros.'),t('Keep original principal as the base each year.','Conserva capital original como base cada año.','Mantenha principal original como base todo ano.'),[800,3,2],m(pct(i(0),i(1)),i(2))),
 c('practice',t('Interest credited?','¿Interés abonado?','Juros creditados?'),t('Opening 600; owner deposit 90; closing 714; no other movement.','Inicio 600; depósito propio 90; cierre 714; sin otros movimientos.','Início 600; depósito próprio 90; fechamento 714; sem outros movimentos.'),[24,114,90],t('714 − 600 − 90 = 24 interest.','714 − 600 − 90 = 24 de interés.','714 − 600 − 90 = 24 de juros.'),t('Separate the owner’s deposit from the bank’s interest.','Separa depósito propio del interés bancario.','Separe depósito próprio dos juros bancários.'),[600,90,714],s(s(i(2),i(0)),i(1))),
 c('practice',t('Next-period balance?','¿Saldo del siguiente periodo?','Saldo do próximo período?'),t('Model balance now 330 after retained gains; next rate 10%; no other changes.','Saldo modelado ahora 330 tras ganancias conservadas; siguiente tasa 10%; sin otros cambios.','Saldo modelado agora 330 após ganhos mantidos; próxima taxa 10%; sem outras mudanças.'),[363,360,33],t('330 + (330 × 10%) = 363.','330 + (330 × 10%) = 363.','330 + (330 × 10%) = 363.'),t('Use the full updated balance.','Usa todo el saldo actualizado.','Use todo o saldo atualizado.'),[330,10],grown(i(0),i(1))),
 q('practice',
 ['Fair comparison of compounding?','Two models share a rate but use different starting amounts.',['No, align principal and other assumptions','Yes, equal rates are sufficient','Yes, larger totals prove better compounding'],'The starting amount also affects the final total.','Hold other inputs equal to compare the compounding effect.'],
 ['¿Comparación justa de capitalización?','Dos modelos comparten tasa, pero usan montos iniciales distintos.',['No, iguala capital y otros supuestos','Sí, tasas iguales bastan','Sí, mayor total prueba mejor capitalización'],'El monto inicial también afecta el total final.','Iguala otras entradas al comparar el efecto de capitalizar.'],
 ['Comparação justa da capitalização?','Dois modelos têm mesma taxa, mas valores iniciais diferentes.',['Não, iguale principal e outras hipóteses','Sim, taxas iguais bastam','Sim, maior total prova melhor capitalização'],'O valor inicial também afeta o total final.','Iguale outras entradas ao comparar o efeito de capitalizar.']),
 c('practice',t('Modeled return?','¿Rendimiento modelado?','Retorno modelado?'),t('Forecast: starting 700; added deposits 200; ending 950; no other changes.','Pronóstico: inicio 700; depósitos añadidos 200; final 950; sin otros cambios.','Previsão: início 700; depósitos somados 200; final 950; sem outras mudanças.'),[50,250,200],t('950 − 700 − 200 = 50 modeled return.','950 − 700 − 200 = 50 de rendimiento modelado.','950 − 700 − 200 = 50 de retorno modelado.'),t('Added deposits are not investment returns.','Depósitos añadidos no son rendimientos de inversión.','Depósitos somados não são retornos de investimento.'),[700,200,950],s(s(i(2),i(0)),i(1))),
 c('practice',t('Amount represented by the share?','¿Monto representado por la parte?','Valor representado pela parte?'),t('A model allocates 15% of a stated base of 400.','Un modelo asigna 15% de una base indicada de 400.','Um modelo destina 15% de uma base informada de 400.'),[60,15,415],t('400 × 15% = 60.','400 × 15% = 60.','400 × 15% = 60.'),t('Apply the percentage to its stated base.','Aplica el porcentaje a su base indicada.','Aplique a porcentagem à base informada.'),[15,400],pct(i(1),i(0))),
 c('transfer',t('Reserved share?','¿Parte reservada?','Parte reservada?'),t('A shared plan reserves 8% of an actual contribution of 750.','Un plan compartido reserva 8% de una aportación real de 750.','Um plano compartilhado reserva 8% de um aporte real de 750.'),[60,8,758],t('750 × 8% = 60 reserved.','750 × 8% = 60 reservado.','750 × 8% = 60 reservado.'),t('Use the actual contribution, not a hoped-for balance.','Usa aportación real, no saldo deseado.','Use aporte real, não saldo desejado.'),[8,750],pct(i(1),i(0))),
],[target(1),target(2),target(3),target(4),target(5),primary,primary]),
review(2,t('Compare money with what it buys','Compara dinero con lo que compra','Compare dinheiro com o que compra'),t('Connect fixed baskets, income, price measures and uncertain forecasts.','Relaciona canastas fijas, ingreso, medidas de precios y pronósticos inciertos.','Relacione cestas fixas, renda, medidas de preços e previsões incertas.'),[
 c('practice',t('Increase in the basket’s cost?','¿Aumento del costo de canasta?','Aumento do custo da cesta?'),t('Unchanged basket: previous 450; current 495.','Canasta sin cambios: antes 450; ahora 495.','Cesta sem mudanças: antes 450; agora 495.'),[45,495,945],t('495 − 450 = 45 extra for the same basket.','495 − 450 = 45 más por la misma canasta.','495 − 450 = 45 a mais pela mesma cesta.'),t('Keep the goods and quantities unchanged.','Conserva productos y cantidades sin cambios.','Mantenha produtos e quantidades sem mudanças.'),[450,495],s(i(1),i(0))),
 q('practice',
 ['Does income keep up with this basket?','Same period: income rises 3%; this fixed basket rises 7%.',['No, basket prices rise faster','Yes, any raise preserves purchasing power','Yes, both increased'],'Income grows more slowly than this basket’s cost.','Compare the percentage changes for the same period.'],
 ['¿Ingreso mantiene el paso con esta canasta?','Mismo periodo: ingreso sube 3%; esta canasta fija sube 7%.',['No, precios de canasta suben más','Sí, cualquier aumento conserva poder de compra','Sí, ambos aumentaron'],'Ingreso crece más lento que costo de esta canasta.','Compara cambios porcentuales del mismo periodo.'],
 ['Renda acompanha esta cesta?','Mesmo período: renda sobe 3%; esta cesta fixa sobe 7%.',['Não, preços da cesta sobem mais','Sim, qualquer aumento mantém poder de compra','Sim, ambos aumentaram'],'Renda cresce mais devagar que custo desta cesta.','Compare mudanças percentuais do mesmo período.']),
 q('practice',
 ['What explains a possible difference?','Your household buys a different mix from the national price index.',['Different spending weights','All households must match the index','The index is your personal receipt'],'A broad index does not reproduce every household’s exact basket.','Separate the shared measure from the household’s purchases.'],
 ['¿Qué explica una posible diferencia?','Tu hogar compra una mezcla distinta del índice nacional de precios.',['Pesos de gasto distintos','Todo hogar debe coincidir con el índice','El índice es tu recibo personal'],'Un índice general no reproduce la canasta exacta de cada hogar.','Separa medida general de compras del hogar.'],
 ['O que explica uma possível diferença?','Sua casa compra uma mistura diferente do índice nacional de preços.',['Pesos de gasto diferentes','Toda casa deve coincidir com o índice','O índice é seu recibo pessoal'],'Um índice geral não reproduz a cesta exata de cada casa.','Separe medida geral de compras da casa.']),
 c('practice',t('Change in baskets affordable?','¿Cambio en canastas que puedes comprar?','Mudança nas cestas que pode comprar?'),t('Earlier balance 300, basket 30; later balance 360, same basket 36.','Saldo anterior 300, canasta 30; saldo posterior 360, misma canasta 36.','Saldo anterior 300, cesta 30; saldo posterior 360, mesma cesta 36.'),[0,60,6],t('360 ÷ 36 − 300 ÷ 30 = 0 change.','360 ÷ 36 − 300 ÷ 30 = 0 de cambio.','360 ÷ 36 − 300 ÷ 30 = 0 de mudança.'),t('Compare purchasing capacity, not nominal balances alone.','Compara capacidad de compra, no solo saldos nominales.','Compare capacidade de compra, não só saldos nominais.'),[300,30,360,36],s(d(i(2),i(3)),d(i(0),i(1)))),
 q('practice',
 ['How to assess?','A forecast hides fees and assumes unchanged positive returns forever.',['Check assumptions and test alternatives','Treat its exact number as a promise','Ignore costs because the curve rises'],'A precise forecast still depends on incomplete or uncertain assumptions.','Inspect inputs before relying on the output.'],
 ['¿Qué hacer con su conclusión?','Un pronóstico oculta cargos y supone rendimientos positivos constantes para siempre.',['Revisar supuestos y probar alternativas','Tratar su cifra exacta como promesa','Ignorar costos porque sube la curva'],'Un pronóstico preciso depende de supuestos incompletos o inciertos.','Examina entradas antes de confiar en resultados.'],
 ['O que fazer com sua conclusão?','Uma previsão esconde tarifas e supõe ganhos positivos iguais para sempre.',['Conferir regras e testar alternativas','Tratar seu valor exato como promessa','Ignorar custos porque a curva sobe'],'Uma previsão exata depende de regras incompletas ou incertas.','Veja os dados antes de confiar no valor final.']),
 c('practice',t('Percentage share in money?','¿Parte porcentual en dinero?','Parte percentual em dinheiro?'),t('Reserve 12% of the stated budget base of 500.','Reserva 12% de la base presupuestal indicada de 500.','Reserve 12% da base de orçamento informada de 500.'),[60,12,512],t('500 × 12% = 60.','500 × 12% = 60.','500 × 12% = 60.'),t('Use the base the percentage describes.','Usa la base que describe el porcentaje.','Use a base que a porcentagem descreve.'),[12,500],pct(i(1),i(0))),
 c('transfer',t('Amount assigned under the plan?','¿Monto asignado según el plan?','Valor destinado segundo o plano?'),t('A fictional reserve plan assigns 7% of a received grant of 900.','Un plan ficticio de reserva asigna 7% de una ayuda recibida de 900.','Um plano fictício de reserva destina 7% de uma ajuda recebida de 900.'),[63,7,907],t('900 × 7% = 63.','900 × 7% = 63.','900 × 7% = 63.'),t('Apply the share to the received amount.','Aplica la parte al monto recibido.','Aplique a parte ao valor recebido.'),[7,900],pct(i(1),i(0))),
],[target(6),target(7),target(8),target(9),target(10),primary,primary])];
