import {t,calculation as c,item,row,i,op} from './helpers.mjs';
const sub=(a,b)=>op('subtract',a,b);
export const timeSources=[{
 id:'fe-production-time-inflation-02',title:t('Where did the increase come from?','¿De dónde vino el aumento?','De onde veio o aumento?'),
 relevance:t('A rising account balance can include your own added money.','Un saldo creciente puede incluir dinero que tú añadiste.','Um saldo crescente pode incluir dinheiro que você acrescentou.'),
 misconception:'Treating all account growth as interest, including money contributed by the account holder.',
 example:t('Start with 100, add your own 20 and earn interest 5: balance 125. Only 5 is interest.','Empieza con 100, añade 20 propios y gana interés 5: saldo 125. Solo 5 es interés.','Comece com 100, acrescente 20 seus e ganhe juros 5: saldo 125. Só 5 é juros.'),
 items:[
 c('guided',t('Interest portion?','¿Parte de interés?','Parte de juros?'),t('Opening 200; your contribution 40; closing 250; no other movement.','Inicio 200; aportación tuya 40; cierre 250; sin otros movimientos.','Início 200; aporte seu 40; fechamento 250; sem outros movimentos.'),[10,50,40],t('250 − 200 − 40 = 10 interest.','250 − 200 − 40 = 10 de interés.','250 − 200 − 40 = 10 de juros.'),t('Remove the opening balance and your added money.','Resta el saldo inicial y el dinero que añadiste.','Subtraia o saldo inicial e o dinheiro que acrescentou.'),[200,40,250],sub(sub(i(2),i(0)),i(1))),
 item('guided',[
 row('Which entry is earned interest?','Records list your transfer and a separate bank interest credit.',['The bank interest credit','Your transfer','Both because both increase balance'],'Your transfer moves existing money; the interest credit is different.','Identify the source of each increase.'),
 row('¿Qué entrada es interés ganado?','El registro separa tu transferencia y un abono de interés bancario.',['El abono de interés bancario','Tu transferencia','Ambos porque aumentan el saldo'],'Tu transferencia mueve dinero existente; el abono de interés es distinto.','Identifica el origen de cada aumento.'),
 row('Qual entrada é juros ganhos?','O registro separa sua transferência e um crédito de juros bancários.',['O crédito de juros bancários','Sua transferência','Ambos porque aumentam o saldo'],'Sua transferência move dinheiro existente; o crédito de juros é diferente.','Identifique a origem de cada aumento.'),
 ]),
 c('practice',t('Interest earned?','¿Interés ganado?','Juros ganhos?'),t('Opening 300; contribution 60; closing 372; no other movements.','Inicio 300; aportación 60; cierre 372; sin otros movimientos.','Início 300; aporte 60; fechamento 372; sem outros movimentos.'),[12,72,60],t('372 − 300 − 60 = 12 interest.','372 − 300 − 60 = 12 de interés.','372 − 300 − 60 = 12 de juros.'),t('The contribution is not interest.','La aportación no es interés.','O aporte não é juros.'),[300,60,372],sub(sub(i(2),i(0)),i(1))),
 c('practice',t('Interest earned?','¿Interés ganado?','Juros ganhos?'),t('Opening 80; your addition 20; closing 100; no other changes.','Inicio 80; añades 20; cierre 100; sin otros cambios.','Início 80; acrescenta 20; fechamento 100; sem outras mudanças.'),[0,20,100],t('100 − 80 − 20 = 0; contributions explain the increase.','100 − 80 − 20 = 0; la aportación explica el aumento.','100 − 80 − 20 = 0; o aporte explica o aumento.'),t('An increasing balance does not necessarily mean interest.','Un saldo creciente no implica necesariamente interés.','Um saldo crescente não implica necessariamente juros.'),[80,20,100],sub(sub(i(2),i(0)),i(1))),
 item('practice',[
 row('Can all growth be called interest?','The balance increased, but contribution records are missing.',['No, identify the movements first','Yes, every increase is interest','Yes, missing records mean no contributions'],'The cause of growth cannot be established from totals alone.','Missing contribution data is not proof of zero contributions.'),
 row('¿Todo aumento puede llamarse interés?','El saldo aumentó, pero faltan registros de aportaciones.',['No, identifica primero los movimientos','Sí, todo aumento es interés','Sí, sin registros no hubo aportaciones'],'Los totales solos no permiten establecer la causa del aumento.','Falta de datos no prueba ausencia de aportaciones.'),
 row('Todo aumento pode ser chamado de juros?','O saldo subiu, mas faltam registros de aportes.',['Não, identifique primeiro os movimentos','Sim, todo aumento é juros','Sim, sem registros não houve aportes'],'Os totais sozinhos não mostram a causa do aumento.','Falta de dados não prova ausência de aportes.'),
 ]),
 c('transfer',t('Interest under these facts?','¿Interés según estos datos?','Juros segundo esses dados?'),t('Shared fund: opening 500; member contributions 120; closing 645; no other movement.','Fondo compartido: inicio 500; aportaciones 120; cierre 645; sin otros movimientos.','Fundo compartilhado: início 500; aportes 120; fechamento 645; sem outros movimentos.'),[25,145,120],t('645 − 500 − 120 = 25 interest.','645 − 500 − 120 = 25 de interés.','645 − 500 − 120 = 25 de juros.'),t('Separate members’ added money from earnings.','Separa dinero aportado por miembros de ganancias.','Separe dinheiro dos membros dos ganhos.'),[500,120,645],sub(sub(i(2),i(0)),i(1))),
 ],
}];
