import {t,calculation as c,item,row,i,op,worked} from './helpers.mjs';
const sub=(a,b)=>op('subtract',a,b),mul=(a,b)=>op('multiply',a,b),div=(a,b)=>op('divide',a,b);
export const timeBasket=[{
 id:'fe-production-time-inflation-06',title:t('Price the same basket again','Calcula otra vez la misma canasta','Calcule de novo a mesma cesta'),
 relevance:t('Compare prices without confusing a change in quantities with a price increase.','Compara precios sin confundir cambios de cantidades con aumentos de precio.','Compare preços sem confundir mudança de quantidades com aumento de preço.'),
 misconception:'Calling every increase in a shopping bill inflation despite changes in the goods or quantities purchased.',
 example:t('Keep goods and quantities fixed. If the same basket costs more, compare the new cost with its earlier cost.','Mantén productos y cantidades iguales. Si esa misma canasta cuesta más, compara su costo nuevo con el anterior.','Mantenha produtos e quantidades iguais. Se essa mesma cesta custa mais, compare o custo novo com o anterior.'),
 guidedBoard:worked(t('Same basket: cost rises from 200 to 220.','Misma canasta: costo sube de 200 a 220.','Mesma cesta: custo sobe de 200 para 220.'),[
 {expression:'220 - 200',result:20,spoken:t('Find the extra cost.','Halla el costo adicional.','Ache o custo extra.')},
 {expression:'20 / 200',result:0.1,spoken:t('Compare the increase with the old cost.','Compara el aumento con el costo anterior.','Compare o aumento com o custo anterior.')},
 {expression:'0.1 * 100',result:10,spoken:t('Express the change as a percentage.','Expresa el cambio como porcentaje.','Expresse a mudança como porcentagem.')},
 ],t('The old basket cost is the percentage base.','El costo anterior de la canasta es la base porcentual.','O custo anterior da cesta é a base percentual.'),t('Keep the same goods and quantities for both costs.','Conserva productos y cantidades iguales en ambos costos.','Mantenha produtos e quantidades iguais nos dois custos.')),
 items:[
 c('guided',t('Extra cost?','¿Costo adicional?','Custo extra?'),t('Same basket: old cost 80; new cost 88.','Misma canasta: costo anterior 80; nuevo 88.','Mesma cesta: custo anterior 80; novo 88.'),[8,88,168],t('88 − 80 = 8 additional units.','88 − 80 = 8 unidades adicionales.','88 − 80 = 8 unidades extras.'),t('Subtract the earlier cost.','Resta el costo anterior.','Subtraia o custo anterior.'),[80,88],sub(i(1),i(0))),
 c('practice',t('Price increase percentage?','¿Porcentaje de aumento de precio?','Porcentagem de aumento do preço?'),t('Identical basket: earlier cost 300; current cost 330.','Canasta idéntica: costo anterior 300; actual 330.','Cesta idêntica: custo anterior 300; atual 330.'),[10,30,110],t('Compare the cost difference with the earlier cost, as a percentage.','Compara diferencia de costo con costo anterior, como porcentaje.','Compare diferença de custo com custo anterior, como porcentagem.'),t('Use the earlier price as the base.','Usa el precio anterior como base.','Use o preço anterior como base.'),[300,330],mul(div(sub(i(1),i(0)),i(0)),{constant:100})),
 item('practice',[
 row('Does this alone show price inflation?','You bought twice as much food; the total bill doubled.',['Quantities also changed','Every doubled bill proves inflation','Quantity never affects total cost'],'Different quantities prevent attributing the whole increase to prices.','Hold quantities fixed to compare prices.'),
 row('¿La cuenta sola demuestra inflación de precios?','Compraste el doble de comida; la cuenta total se duplicó.',['No, también cambiaron las cantidades','Sí, duplicar cuenta prueba inflación','Sí, cantidad nunca afecta costo total'],'Cantidades distintas impiden atribuir todo el aumento a precios.','Mantén cantidades iguales para comparar precios.'),
 row('A conta sozinha prova inflação de preços?','Comprou o dobro de comida; a conta total dobrou.',['Não, quantidades também mudaram','Sim, dobrar conta prova inflação','Sim, quantidade nunca afeta custo total'],'Quantidades diferentes impedem atribuir todo aumento a preços.','Mantenha quantidades iguais para comparar preços.'),
 ]),
 c('practice',t('How much cheaper?','¿Cuánto más barata?','Quanto mais barata?'),t('Fixed basket: previous cost 250; current cost 240.','Canasta fija: costo previo 250; actual 240.','Cesta fixa: custo anterior 250; atual 240.'),[10,240,490],t('250 − 240 = 10 less for the same basket.','250 − 240 = 10 menos por la misma canasta.','250 − 240 = 10 a menos pela mesma cesta.'),t('A lower new cost means a decrease here.','Un nuevo costo menor implica disminución aquí.','Um novo custo menor implica redução aqui.'),[250,240],sub(i(0),i(1))),
 c('transfer',t('Percentage cost increase?','¿Porcentaje de aumento del costo?','Porcentagem de aumento do custo?'),t('Unchanged work-supply basket: old cost 400; new cost 460.','Canasta laboral sin cambios: costo anterior 400; nuevo 460.','Cesta de materiais sem mudanças: custo anterior 400; novo 460.'),[15,60,115],t('The increase is measured against the old basket cost.','El aumento se mide contra el costo anterior de la canasta.','O aumento é medido contra o custo anterior da cesta.'),t('Subtract first, then divide by the earlier cost.','Resta primero y divide entre el costo anterior.','Subtraia primeiro e divida pelo custo anterior.'),[400,460],mul(div(sub(i(1),i(0)),i(0)),{constant:100})),
 ],
}];
