import {t,calculation as c,item,row,i,op} from './helpers.mjs';
const add=(a,b)=>op('add',a,b),sub=(a,b)=>op('subtract',a,b),mul=(a,b)=>op('multiply',a,b),div=(a,b)=>op('divide',a,b),hundred={constant:100};
const grown=(base,rate)=>add(base,div(mul(base,rate),hundred));
const growthBoard={id:'example-growth',type:'visual.growth-comparison.v2',grading:'none',teaching_role:'example',visual:{type:'multi-line'},payload:{principalMinor:10000,minimumRateBps:500,maximumRateBps:1000,rateStepBps:500,initialRateBps:1000,minimumYears:1,maximumYears:5,yearStep:1,initialYears:2,predictionStepMinor:100,predictionMaximumMinor:30000},copy:Object.fromEntries(['en-US','es-MX','pt-BR'].map((locale,n)=>[locale,{prompt:t('Toy model: 100 dollars, no fees or deposits. Change time or rate; compare both growth lines.','Modelo ficticio: 100 pesos, sin cargos ni depósitos. Cambia tiempo o tasa; compara ambas líneas de crecimiento.','Modelo fictício: 100 reais, sem tarifas nem depósitos. Mude tempo ou taxa; compare ambas as linhas de crescimento.')[n]}]))};
export const timeCompare=[{
 id:'fe-production-time-inflation-04',title:t('Compare equal growth assumptions','Compara supuestos de crecimiento iguales','Compare hipóteses iguais de crescimento'),
 relevance:t('Simple and compound models differ only meaningfully when their other assumptions match.','Modelos simple y compuesto se comparan cuando coinciden sus otros supuestos.','Modelos simples e composto se comparam quando suas outras hipóteses coincidem.'),
 misconception:'Comparing model labels without aligning principal, rate, duration and treatment of retained gains.',
 example:t('At equal positive rates, retained interest can earn interest in later periods. Simple interest keeps using the original principal.','Con tasas positivas iguales, el interés conservado puede generar interés después. El interés simple sigue usando capital original.','Com taxas positivas iguais, juros mantidos podem render juros depois. Juros simples continuam usando o principal original.'),
 guidedBoard:growthBoard,
 items:[
 item('guided',[
 row('Fair comparison?','Both models start at 100; one runs a year, the other five.',['No, align the duration','Yes, starting amounts match','Yes, all growth models are interchangeable'],'Different durations change the result independently of compounding.','Match time as well as the starting amount.'),
 row('¿Comparación justa?','Ambos modelos inician en 100; uno dura un año y otro cinco.',['No, iguala la duración','Sí, coinciden montos iniciales','Sí, todos los modelos son equivalentes'],'Duraciones distintas cambian el resultado aparte de la capitalización.','Iguala tiempo además del monto inicial.'),
 row('Comparação justa?','Ambos começam com 100; um dura um ano e outro cinco.',['Não, iguale o prazo','Sim, valores iniciais coincidem','Sim, todos os modelos são equivalentes'],'Prazos diferentes mudam o resultado além da capitalização.','Iguale tempo além do valor inicial.'),
 ]),
 c('guided',t('Simple-model ending balance?','¿Saldo final del modelo simple?','Saldo final do modelo simples?'),t('Start 100; yearly rate 10%; duration 2 years; simple interest; no other changes.','Inicio 100; tasa anual 10%; duración 2 años; interés simple; sin otros cambios.','Início 100; taxa anual 10%; prazo 2 anos; juros simples; sem outras mudanças.'),[120,121,110],t('100 + (100 × 10% × 2) = 120.','100 + (100 × 10% × 2) = 120.','100 + (100 × 10% × 2) = 120.'),t('Each year uses the original principal.','Cada año usa el capital original.','Cada ano usa o principal original.'),[100,10,2],add(i(0),mul(div(mul(i(0),i(1)),hundred),i(2)))),
 c('practice',t('Compound-model ending balance?','¿Saldo final del modelo compuesto?','Saldo final do modelo composto?'),t('Start 200; first rate 10%; second rate 10%; compound; no deposits or withdrawals.','Inicio 200; primera tasa 10%; segunda tasa 10%; compuesto; sin depósitos ni retiros.','Início 200; primeira taxa 10%; segunda taxa 10%; composto; sem depósitos nem saques.'),[242,240,220],t('The second period includes growth on the first period’s retained interest.','El segundo periodo crece también sobre el interés previo conservado.','O segundo período cresce também sobre os juros anteriores mantidos.'),t('Use the updated base for the second calculation.','Usa la base actualizada en el segundo cálculo.','Use a base atualizada no segundo cálculo.'),[200,10,10],grown(grown(i(0),i(1)),i(2))),
 c('practice',t('Difference between ending balances?','¿Diferencia entre saldos finales?','Diferença entre saldos finais?'),t('Matched models: compound ending balance 484; simple ending balance 480.','Modelos comparables: saldo final compuesto 484; saldo final simple 480.','Modelos comparáveis: saldo final composto 484; saldo final simples 480.'),[4,484,964],t('484 − 480 = 4 additional modeled units.','484 − 480 = 4 unidades adicionales modeladas.','484 − 480 = 4 unidades adicionais modeladas.'),t('Compare the two completed balances.','Compara los dos saldos finales.','Compare os dois saldos finais.'),[484,480],sub(i(0),i(1))),
 item('practice',[
 row('Why can the lines differ later?','Same principal, positive rate and duration; compound gains remain.',['Earlier gains enter later interest calculations','The compound account receives secret deposits','The original principal disappears'],'Compounding changes the interest base as retained gains accumulate.','Trace the base rather than inventing extra money.'),
 row('¿Por qué pueden diferir las líneas después?','Mismo capital, tasa positiva y duración; ganancias compuestas permanecen.',['Ganancias previas integran el cálculo posterior','La cuenta compuesta recibe depósitos secretos','Desaparece el capital original'],'Capitalizar cambia la base al acumular ganancias conservadas.','Sigue la base sin inventar dinero adicional.'),
 row('Por que as linhas podem diferir depois?','Mesmo principal, taxa positiva e prazo; ganhos compostos ficam.',['Ganhos anteriores entram no cálculo seguinte','A conta composta recebe depósitos secretos','O principal original desaparece'],'Capitalizar muda a base ao acumular ganhos mantidos.','Siga a base sem inventar dinheiro extra.'),
 ]),
 item('transfer',[
 row('Can compounding alone explain the difference?','A comparison changes both the rate and whether interest compounds.',['Isolate the changed assumptions','Ignore the rate difference','The larger balance proves it'],'Changing two assumptions prevents attributing the result to only one.','Keep other assumptions equal when comparing one effect.'),
 row('¿Capitalizar explica por sí solo la diferencia?','Una comparación cambia tasa y forma de capitalizar.',['No, separa los supuestos cambiados','Sí, ignora la diferencia de tasa','Sí, el saldo mayor lo prueba'],'Cambiar dos supuestos impide atribuir el resultado solo a uno.','Iguala otros supuestos al comparar un efecto.'),
 row('Capitalizar explica sozinho a diferença?','Uma comparação muda taxa e forma de capitalizar.',['Não, separe as hipóteses alteradas','Sim, ignore a diferença de taxa','Sim, o saldo maior prova isso'],'Mudar duas hipóteses impede atribuir o resultado só a uma.','Iguale outras hipóteses ao comparar um efeito.'),
 ]),
 ],
}];
