import type { HorizonteCopy } from '../boardTypes';

export const PROB_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  less: { role: 'action', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  person: { role: 'data', 'en-US': 'person', 'es-MX': 'persona', 'pt-BR': 'pessoa' },
  people: { role: 'data', 'en-US': 'people', 'es-MX': 'personas', 'pt-BR': 'pessoas' },
  rateOf: { role: 'data', 'en-US': '{part} in {whole}', 'es-MX': '{part} de {whole}', 'pt-BR': '{part} em {whole}' },
  theRest: { role: 'data', 'en-US': 'the rest', 'es-MX': 'el resto', 'pt-BR': 'o restante' },
  slotHas: { role: 'option', 'en-US': 'Have it', 'es-MX': 'Lo tienen', 'pt-BR': 'Têm' },
  slotLacks: { role: 'option', 'en-US': 'Do not have it', 'es-MX': 'No lo tienen', 'pt-BR': 'Não têm' },
  slotHasPos: { role: 'option', 'en-US': 'Have it, positive', 'es-MX': 'Lo tienen, positivo', 'pt-BR': 'Têm, positivo' },
  slotHasNeg: { role: 'option', 'en-US': 'Have it, negative', 'es-MX': 'Lo tienen, negativo', 'pt-BR': 'Têm, negativo' },
  slotLacksPos: { role: 'option', 'en-US': 'Do not have it, positive', 'es-MX': 'No lo tienen, positivo', 'pt-BR': 'Não têm, positivo' },
  slotLacksNeg: { role: 'option', 'en-US': 'Do not have it, negative', 'es-MX': 'No lo tienen, negativo', 'pt-BR': 'Não têm, negativo' },
  resultPos: { role: 'data', 'en-US': 'Positive', 'es-MX': 'Positivo', 'pt-BR': 'Positivo' },
  resultNeg: { role: 'data', 'en-US': 'Negative', 'es-MX': 'Negativo', 'pt-BR': 'Negativo' },

  treeName: { role: 'data', 'en-US': 'Probability tree', 'es-MX': 'Árbol de probabilidad', 'pt-BR': 'Árvore de probabilidade' },
  factPrior: { role: 'body', 'en-US': '{part} in {whole} have it.', 'es-MX': '{part} de cada {whole} lo tienen.', 'pt-BR': '{part} em cada {whole} têm.' },
  factHit: { role: 'body', 'en-US': 'Of those, {part} in {whole} test positive.', 'es-MX': 'De ellos, {part} de cada {whole} dan positivo.', 'pt-BR': 'Desses, {part} em cada {whole} testam positivo.' },
  factAlarm: { role: 'body', 'en-US': 'Of the rest, {part} in {whole} test positive.', 'es-MX': 'Del resto, {part} de cada {whole} dan positivo.', 'pt-BR': 'Do restante, {part} em cada {whole} testam positivo.' },
  trayHeading: { role: 'heading', 'en-US': 'Counts to place', 'es-MX': 'Cantidades por colocar', 'pt-BR': 'Quantidades para colocar' },
  chipPlaced: { role: 'option', 'en-US': '{n} on {slot}', 'es-MX': '{n} en {slot}', 'pt-BR': '{n} em {slot}' },
  moveBack: { role: 'option', 'en-US': 'Back to the tray', 'es-MX': 'De vuelta a la bandeja', 'pt-BR': 'De volta à bandeja' },
  placedCount: { role: 'data', 'en-US': 'Placed: {n} of 6', 'es-MX': 'Colocadas: {n} de 6', 'pt-BR': 'Colocadas: {n} de 6' },
  tableCaptionTree: { role: 'heading', 'en-US': 'Branches and counts', 'es-MX': 'Ramas y cantidades', 'pt-BR': 'Ramos e quantidades' },
  colBranch: { role: 'data', 'en-US': 'Branch', 'es-MX': 'Rama', 'pt-BR': 'Ramo' },
  colShare: { role: 'data', 'en-US': 'Share', 'es-MX': 'Fracción', 'pt-BR': 'Fração' },
  colCount: { role: 'data', 'en-US': 'Count', 'es-MX': 'Cantidad', 'pt-BR': 'Quantidade' },
  emptyCell: { role: 'data', 'en-US': 'none', 'es-MX': 'ninguna', 'pt-BR': 'nenhuma' },
  metTree: { role: 'body', 'en-US': 'You built the tree. Every count is on its branch.', 'es-MX': 'Armaste el árbol. Cada cantidad está en su rama.', 'pt-BR': 'Você montou a árvore. Cada quantidade está no seu ramo.' },
  hintTree: { role: 'body', 'en-US': 'Not yet. Branches must add up to the one above.', 'es-MX': 'Aún no. Las ramas deben sumar lo que tiene la de arriba.', 'pt-BR': 'Ainda não. Os ramos devem somar o que tem o de cima.' },

  bayesName: { role: 'data', 'en-US': 'Natural frequencies', 'es-MX': 'Frecuencias naturales', 'pt-BR': 'Frequências naturais' },
  inAll: { role: 'data', 'en-US': '{n} in all', 'es-MX': '{n} en total', 'pt-BR': '{n} no total' },
  gridScale: { role: 'data', 'en-US': 'Each square holds {n}', 'es-MX': 'Cada cuadro tiene {n}', 'pt-BR': 'Cada quadrado tem {n}' },
  outlinePos: { role: 'data', 'en-US': 'Outlined: people who test positive', 'es-MX': 'Con borde: personas que dan positivo', 'pt-BR': 'Com borda: pessoas que testam positivo' },
  outlineNeg: { role: 'data', 'en-US': 'Outlined: people who test negative', 'es-MX': 'Con borde: personas que dan negativo', 'pt-BR': 'Com borda: pessoas que testam negativo' },
  chanceLabel: { role: 'body', 'en-US': 'Chance they have it', 'es-MX': 'Probabilidad de que lo tenga', 'pt-BR': 'Chance de ter' },
  chanceHelp: { role: 'body', 'en-US': 'Write a percent, a decimal or a fraction.', 'es-MX': 'Escribe un porcentaje, un decimal o una fracción.', 'pt-BR': 'Escreva uma porcentagem, um decimal ou uma fração.' },
  chanceError: { role: 'body', 'en-US': 'Write a number from 0 to 1, or a percent.', 'es-MX': 'Escribe un número de 0 a 1, o un porcentaje.', 'pt-BR': 'Escreva um número de 0 a 1, ou uma porcentagem.' },
  tableCaptionBayes: { role: 'heading', 'en-US': 'People by result', 'es-MX': 'Personas por resultado', 'pt-BR': 'Pessoas por resultado' },
  colGroup: { role: 'data', 'en-US': 'Group', 'es-MX': 'Grupo', 'pt-BR': 'Grupo' },
  metBayes: { role: 'body', 'en-US': 'That is the chance. You read it from the counts.', 'es-MX': 'Esa es la probabilidad. La leíste de las cantidades.', 'pt-BR': 'Essa é a chance. Você a leu nas quantidades.' },
  hintBayes: { role: 'body', 'en-US': 'Not yet. Out of the outlined people, how many have it?', 'es-MX': 'Aún no. De las personas con borde, ¿cuántas lo tienen?', 'pt-BR': 'Ainda não. Das pessoas com borda, quantas têm?' },

  regressionName: { role: 'data', 'en-US': 'Scatter plot with a line', 'es-MX': 'Gráfica de puntos con una recta', 'pt-BR': 'Gráfico de pontos com uma reta' },
  slopeLabel: { role: 'body', 'en-US': 'Slope', 'es-MX': 'Pendiente', 'pt-BR': 'Inclinação' },
  interceptLabel: { role: 'body', 'en-US': 'Intercept', 'es-MX': 'Ordenada al origen', 'pt-BR': 'Intercepto' },
  squaresTotal: { role: 'data', 'en-US': 'Sum of the squares', 'es-MX': 'Suma de los cuadrados', 'pt-BR': 'Soma dos quadrados' },
  wordEquals: { role: 'data', 'en-US': 'equals', 'es-MX': 'es igual a', 'pt-BR': 'é igual a' },
  wordPlus: { role: 'data', 'en-US': 'plus', 'es-MX': 'más', 'pt-BR': 'mais' },
  wordMinus: { role: 'data', 'en-US': 'minus', 'es-MX': 'menos', 'pt-BR': 'menos' },
  tableCaptionFit: { role: 'heading', 'en-US': 'Points, line and squares', 'es-MX': 'Puntos, recta y cuadrados', 'pt-BR': 'Pontos, reta e quadrados' },
  colOnLine: { role: 'data', 'en-US': 'On the line', 'es-MX': 'En la recta', 'pt-BR': 'Na reta' },
  colResidual: { role: 'data', 'en-US': 'Residual', 'es-MX': 'Residuo', 'pt-BR': 'Resíduo' },
  colSquare: { role: 'data', 'en-US': 'Square', 'es-MX': 'Cuadrado', 'pt-BR': 'Quadrado' },
  total: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  metFit: { role: 'body', 'en-US': 'That is the best line. The squares cannot get smaller.', 'es-MX': 'Esa es la mejor recta. Los cuadrados ya no pueden ser menores.', 'pt-BR': 'Essa é a melhor reta. Os quadrados não podem ficar menores.' },
  hintFit: { role: 'body', 'en-US': 'Not yet. Keep moving until the squares stop shrinking.', 'es-MX': 'Aún no. Sigue moviendo hasta que los cuadrados dejen de encogerse.', 'pt-BR': 'Ainda não. Continue até os quadrados pararem de encolher.' },
} as const satisfies HorizonteCopy;
