/*
 * GENERATED by agent/tools/check-mentor-canary-parity.mjs --write from
 * docs/rebuild/mentor/governance/registry.json (tier2Parameters). Do not edit by hand: `npm run canary:check` fails on any drift.
 */

export interface Tier2ParameterBounds {
  object: 'TELEMETRY_DEFAULTS' | 'ALLIANCE_DEFAULTS' | 'SELF_EXPLANATION_DEFAULTS';
  field: string;
  min: number;
  max: number;
  integer: boolean;
}

/** C.22 Tier 2 parameters: the only values a Stage 5 canary may override, and their approved bounds. */
export const TIER2_PARAMETERS = {
  'telemetry.latencyZ': { object: 'TELEMETRY_DEFAULTS', field: 'latencyZ', min: 1, max: 2.5, integer: false },
  'telemetry.minChannels': { object: 'TELEMETRY_DEFAULTS', field: 'minChannels', min: 2, max: 3, integer: true },
  'telemetry.maxCheckIns': { object: 'TELEMETRY_DEFAULTS', field: 'maxCheckIns', min: 1, max: 3, integer: true },
  'alliance.renegotiateAfterDeclines': { object: 'ALLIANCE_DEFAULTS', field: 'renegotiateAfterDeclines', min: 2, max: 4, integer: true },
  'alliance.maxRenegotiations': { object: 'ALLIANCE_DEFAULTS', field: 'maxRenegotiations', min: 1, max: 3, integer: true },
  'selfExplanation.maxPerSession': { object: 'SELF_EXPLANATION_DEFAULTS', field: 'maxPerSession', min: 1, max: 6, integer: true },
  'selfExplanation.minSpacingTurns': { object: 'SELF_EXPLANATION_DEFAULTS', field: 'minSpacingTurns', min: 2, max: 6, integer: true },
} as const satisfies Record<string, Tier2ParameterBounds>;

export type Tier2ParameterId = keyof typeof TIER2_PARAMETERS;
