/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/golden/contract.ts. Do not edit: change the source and regenerate. */
import { z } from 'zod';
import { hzBase, hzServer, hzVisual } from '../shared.generated';
import type { HorizonteAgeScope } from '../types.generated';
import { TEN_FRAME_CELLS, TEN_FRAME_MAX_FRAMES } from './model.generated';

const count = z.number().int().min(0).max(TEN_FRAME_CELLS);
const counts = z.array(count).min(1).max(TEN_FRAME_MAX_FRAMES);

/** A03/A04: one ten frame (visual `ten-frame`) or two (`double-ten-frame`); the payload carries only the start, never the answer. */
export const tenFramePayload = z.object({ start: counts }).strict();

export const GOLDEN_SEGMENTS = [
  z.object({
    ...hzBase, type: z.literal('math.ten-frame.v2'), grading: hzServer,
    visual: z.union([hzVisual('ten-frame'), hzVisual('double-ten-frame')]), payload: tenFramePayload,
  }).strict().superRefine((value, ctx) => {
    if ((value.visual.type === 'double-ten-frame') !== (value.payload.start.length === 2)) ctx.addIssue({ code: 'custom', path: ['visual'], message: 'The visual matches the number of frames' });
  }),
] as const;

export const GOLDEN_RUBRICS = {
  'math.ten-frame.v2': z.object({ target: counts }).strict(),
} as const;

export const GOLDEN_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {
  'math.ten-frame.v2': { ages: [6, 9], adult: false },
};
