/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/space1/coins.ts. Do not edit: change the source and regenerate. */
export const COIN_PIECES = ['coin', 'bill'] as const;
export type CoinPiece = (typeof COIN_PIECES)[number];
/** The teaching thickness of one piece in tenths of a millimetre: a coin is 2 mm, a bill 0.1 mm. */
export const THICKNESS_TENTHS: Readonly<Record<CoinPiece, number>> = { coin: 20, bill: 1 };
export const COIN_LIMITS = {
  value: { min: 1, max: 100_000 },
  total: { max: 10_000_000_000 },
  mm: { max: 100_000 },
  step: { min: 1, max: 10_000 },
  max: { min: 2, max: 100_000 },
  positions: { max: 40 },
} as const;

/** Things of a known height drawn beside the stack so the learner can read the scale; each locale names them in its own copy. */
export const REFERENCE_MARKS = [
  { id: 'phone', mm: 8 },
  { id: 'book', mm: 30 },
  { id: 'desk', mm: 750 },
  { id: 'door', mm: 2000 },
] as const;
export type ReferenceId = (typeof REFERENCE_MARKS)[number]['id'];

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const exactKeys = (value: Record<string, unknown>, keys: readonly string[]): boolean => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
const whole = (value: unknown, minimum: number, maximum: number): value is number => typeof value === 'number' && Number.isInteger(value) && value >= minimum && value <= maximum;

/** Values are whole cents of a generic currency: no real currency is named. */
export type CoinGoal = { kind: 'amount'; total: number } | { kind: 'height'; mm: number };
export interface CoinPayload { piece: CoinPiece; value: number; goal: CoinGoal; step: number; max: number }

export const isCoinPiece = (value: unknown): value is CoinPiece => typeof value === 'string' && (COIN_PIECES as readonly string[]).includes(value);

function readGoal(value: unknown): CoinGoal | null {
  if (!isRecord(value)) return null;
  if (value.kind === 'amount' && exactKeys(value, ['kind', 'total']) && whole(value.total, 1, COIN_LIMITS.total.max)) return { kind: 'amount', total: value.total };
  if (value.kind === 'height' && exactKeys(value, ['kind', 'mm']) && whole(value.mm, 1, COIN_LIMITS.mm.max)) return { kind: 'height', mm: value.mm };
  return null;
}

export function readCoinPayload(value: unknown): CoinPayload | null {
  if (!isRecord(value) || !exactKeys(value, ['piece', 'value', 'goal', 'step', 'max'])) return null;
  const goal = readGoal(value.goal);
  if (!goal || !isCoinPiece(value.piece)) return null;
  if (!whole(value.value, COIN_LIMITS.value.min, COIN_LIMITS.value.max) || !whole(value.step, COIN_LIMITS.step.min, COIN_LIMITS.step.max) || !whole(value.max, COIN_LIMITS.max.min, COIN_LIMITS.max.max)) return null;
  return { piece: value.piece, value: value.value, goal, step: value.step, max: value.max };
}

/** The height of a stack in tenths of a millimetre, and the money in it in cents. */
export const stackTenths = (piece: CoinPiece, count: number): number => count * THICKNESS_TENTHS[piece];
export const stackCents = (payload: Pick<CoinPayload, 'value'>, count: number): number => count * payload.value;

/** The number of pieces the question asks for, or null when the goal does not fall on a whole number of pieces. */
export function coinAnswer(payload: CoinPayload): number | null {
  const thickness = THICKNESS_TENTHS[payload.piece];
  const count = payload.goal.kind === 'amount'
    ? (payload.goal.total % payload.value === 0 ? payload.goal.total / payload.value : null)
    : ((payload.goal.mm * 10) % thickness === 0 ? (payload.goal.mm * 10) / thickness : null);
  return count !== null && Number.isSafeInteger(count) ? count : null;
}

/** The counts the handle can rest on: 0, then every multiple of the step up to the maximum. */
export const coinPositions = (payload: Pick<CoinPayload, 'step' | 'max'>): number[] => Array.from({ length: Math.floor(payload.max / payload.step) + 1 }, (_, index) => index * payload.step);

export function coinProblem(payload: CoinPayload): string | null {
  if (payload.max % payload.step !== 0) return 'The maximum must be a whole number of steps';
  if (payload.max / payload.step > COIN_LIMITS.positions.max) return `The handle may rest on at most ${COIN_LIMITS.positions.max} counts: raise the step`;
  const answer = coinAnswer(payload);
  if (answer === null) return payload.goal.kind === 'amount' ? 'The total must be a whole number of pieces' : 'The height must be a whole number of pieces';
  if (answer < payload.step || answer > payload.max) return 'The answer must be between one step and the maximum';
  if (answer % payload.step !== 0) return 'The answer must be a multiple of the step, so the handle can rest on it';
  return null;
}
