import type { HorizonteCopy } from '../boardTypes';

export const SPACE1_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },

  rotHeading: { role: 'heading', 'en-US': 'Turn the figure', 'es-MX': 'Gira la figura', 'pt-BR': 'Gire a figura' },
  rotFigureLabel: {
    role: 'data',
    'en-US': 'Your figure, turned {angle} degrees, {n} cubes',
    'es-MX': 'Tu figura, girada {angle} grados, {n} cubos',
    'pt-BR': 'Sua figura, girada {angle} graus, {n} cubos',
  },
  rotAxisUp: {
    role: 'body',
    'en-US': 'Turn around the upright line, seen from above.',
    'es-MX': 'Gira alrededor de la línea vertical, vista desde arriba.',
    'pt-BR': 'Gire em torno da linha vertical, vista de cima.',
  },
  rotAxisSide: {
    role: 'body',
    'en-US': 'Turn around the left-to-right line, seen from the right.',
    'es-MX': 'Gira alrededor de la línea de izquierda a derecha, vista desde la derecha.',
    'pt-BR': 'Gire em torno da linha da esquerda à direita, vista da direita.',
  },
  rotAxisDepth: {
    role: 'body',
    'en-US': 'Turn around the front-to-back line, seen from the front.',
    'es-MX': 'Gira alrededor de la línea de frente a fondo, vista de frente.',
    'pt-BR': 'Gire em torno da linha de frente a fundo, vista de frente.',
  },
  rotDialHeading: { role: 'heading', 'en-US': 'Choose the turn', 'es-MX': 'Elige el giro', 'pt-BR': 'Escolha o giro' },
  rotDialLabel: { role: 'data', 'en-US': 'Clockwise turn', 'es-MX': 'Giro horario', 'pt-BR': 'Giro horário' },
  rotDialValue: { role: 'data', 'en-US': '{n} degrees', 'es-MX': '{n} grados', 'pt-BR': '{n} graus' },
  rotDialKeys: {
    role: 'body',
    'en-US': 'Arrow keys turn the figure by 90 degrees.',
    'es-MX': 'Las flechas giran la figura 90 grados.',
    'pt-BR': 'As setas giram a figura 90 graus.',
  },
  rotTargetsHeading: { role: 'heading', 'en-US': 'Which shape does it become?', 'es-MX': '¿En qué forma se convierte?', 'pt-BR': 'Em que forma ela se torna?' },
  rotShapeName: { role: 'data', 'en-US': 'Shape {id}', 'es-MX': 'Forma {id}', 'pt-BR': 'Forma {id}' },
  rotShapeLabel: { role: 'data', 'en-US': 'Shape {id}, {n} cubes', 'es-MX': 'Forma {id}, {n} cubos', 'pt-BR': 'Forma {id}, {n} cubos' },
  rotPicked: { role: 'data', 'en-US': 'Shape picked: {id}', 'es-MX': 'Forma elegida: {id}', 'pt-BR': 'Forma escolhida: {id}' },
  rotNone: { role: 'data', 'en-US': 'none', 'es-MX': 'ninguna', 'pt-BR': 'nenhuma' },
  rotStatus: { role: 'data', 'en-US': 'Turn: {angle} degrees. {picked}.', 'es-MX': 'Giro: {angle} grados. {picked}.', 'pt-BR': 'Giro: {angle} graus. {picked}.' },
  rotCoords: {
    role: 'body',
    'en-US': 'x runs right, y runs up, z comes toward you.',
    'es-MX': 'x va a la derecha, y hacia arriba, z hacia ti.',
    'pt-BR': 'x vai para a direita, y para cima, z para você.',
  },
  rotTableCaption: { role: 'heading', 'en-US': 'Where the cubes are', 'es-MX': 'Dónde están los cubos', 'pt-BR': 'Onde estão os cubos' },
  rotColShape: { role: 'data', 'en-US': 'Shape', 'es-MX': 'Forma', 'pt-BR': 'Forma' },
  rotColCubes: { role: 'data', 'en-US': 'Cubes', 'es-MX': 'Cubos', 'pt-BR': 'Cubos' },
  rotColPlaces: { role: 'data', 'en-US': 'Places (x, y, z)', 'es-MX': 'Lugares (x, y, z)', 'pt-BR': 'Lugares (x, y, z)' },
  rotFigureRow: { role: 'data', 'en-US': 'Your figure', 'es-MX': 'Tu figura', 'pt-BR': 'Sua figura' },
  rotTurnedRow: { role: 'data', 'en-US': 'Figure after the turn', 'es-MX': 'Figura tras el giro', 'pt-BR': 'Figura após o giro' },
  metRotation: { role: 'body', 'en-US': 'You turned the figure to the matching shape.', 'es-MX': 'Giraste la figura hasta la forma igual.', 'pt-BR': 'Você girou a figura até a forma igual.' },
  hintRotation: { role: 'body', 'en-US': 'Not yet. Turn the figure and compare it again.', 'es-MX': 'Aún no. Gira la figura y compárala otra vez.', 'pt-BR': 'Ainda não. Gire a figura e compare de novo.' },

  solidTetrahedron: { role: 'data', 'en-US': 'Tetrahedron', 'es-MX': 'Tetraedro', 'pt-BR': 'Tetraedro' },
  solidCube: { role: 'data', 'en-US': 'Cube', 'es-MX': 'Cubo', 'pt-BR': 'Cubo' },
  solidOctahedron: { role: 'data', 'en-US': 'Octahedron', 'es-MX': 'Octaedro', 'pt-BR': 'Octaedro' },
  solidDodecahedron: { role: 'data', 'en-US': 'Dodecahedron', 'es-MX': 'Dodecaedro', 'pt-BR': 'Dodecaedro' },
  solidIcosahedron: { role: 'data', 'en-US': 'Icosahedron', 'es-MX': 'Icosaedro', 'pt-BR': 'Icosaedro' },
  solidTruncatedTetrahedron: { role: 'data', 'en-US': 'Truncated tetrahedron', 'es-MX': 'Tetraedro truncado', 'pt-BR': 'Tetraedro truncado' },
  solidCuboctahedron: { role: 'data', 'en-US': 'Cuboctahedron', 'es-MX': 'Cuboctaedro', 'pt-BR': 'Cuboctaedro' },
  solidTruncatedOctahedron: { role: 'data', 'en-US': 'Truncated octahedron', 'es-MX': 'Octaedro truncado', 'pt-BR': 'Octaedro truncado' },
  solidIcosidodecahedron: { role: 'data', 'en-US': 'Icosidodecahedron', 'es-MX': 'Icosidodecaedro', 'pt-BR': 'Icosidodecaedro' },
  solidTruncatedIcosahedron: { role: 'data', 'en-US': 'Truncated icosahedron', 'es-MX': 'Icosaedro truncado', 'pt-BR': 'Icosaedro truncado' },
  solidCylinder: { role: 'data', 'en-US': 'Cylinder', 'es-MX': 'Cilindro', 'pt-BR': 'Cilindro' },
  solidCone: { role: 'data', 'en-US': 'Cone', 'es-MX': 'Cono', 'pt-BR': 'Cone' },
  solidPrism: { role: 'data', 'en-US': 'Square prism', 'es-MX': 'Prisma cuadrado', 'pt-BR': 'Prisma quadrado' },
  solidPyramid: { role: 'data', 'en-US': 'Square pyramid', 'es-MX': 'Pirámide cuadrada', 'pt-BR': 'Pirâmide quadrada' },
  shapeTriangle: { role: 'option', 'en-US': 'Triangle', 'es-MX': 'Triángulo', 'pt-BR': 'Triângulo' },
  shapeSquare: { role: 'option', 'en-US': 'Square', 'es-MX': 'Cuadrado', 'pt-BR': 'Quadrado' },
  shapeRectangle: { role: 'option', 'en-US': 'Rectangle', 'es-MX': 'Rectángulo', 'pt-BR': 'Retângulo' },
  shapeRhombus: { role: 'option', 'en-US': 'Rhombus', 'es-MX': 'Rombo', 'pt-BR': 'Losango' },
  shapeParallelogram: { role: 'option', 'en-US': 'Parallelogram', 'es-MX': 'Paralelogramo', 'pt-BR': 'Paralelogramo' },
  shapeTrapezoid: { role: 'option', 'en-US': 'Trapezoid', 'es-MX': 'Trapecio', 'pt-BR': 'Trapézio' },
  shapeQuadrilateral: { role: 'option', 'en-US': 'Quadrilateral', 'es-MX': 'Cuadrilátero', 'pt-BR': 'Quadrilátero' },
  shapePentagon: { role: 'option', 'en-US': 'Pentagon', 'es-MX': 'Pentágono', 'pt-BR': 'Pentágono' },
  shapeHexagon: { role: 'option', 'en-US': 'Hexagon', 'es-MX': 'Hexágono', 'pt-BR': 'Hexágono' },
  shapePolygon: { role: 'option', 'en-US': 'Polygon', 'es-MX': 'Polígono', 'pt-BR': 'Polígono' },
  shapeCircle: { role: 'option', 'en-US': 'Circle', 'es-MX': 'Círculo', 'pt-BR': 'Círculo' },
  shapeEllipse: { role: 'option', 'en-US': 'Ellipse', 'es-MX': 'Elipse', 'pt-BR': 'Elipse' },

  stageHeading: { role: 'heading', 'en-US': 'Turn the solid to look', 'es-MX': 'Gira el cuerpo para mirar', 'pt-BR': 'Gire o sólido para olhar' },
  turnLeft: { role: 'action', 'en-US': 'Turn left', 'es-MX': 'Girar a la izquierda', 'pt-BR': 'Girar à esquerda' },
  turnRight: { role: 'action', 'en-US': 'Turn right', 'es-MX': 'Girar a la derecha', 'pt-BR': 'Girar à direita' },
  viewHigher: { role: 'action', 'en-US': 'Look higher', 'es-MX': 'Vista más alta', 'pt-BR': 'Vista mais alta' },
  viewLower: { role: 'action', 'en-US': 'Look lower', 'es-MX': 'Vista más baja', 'pt-BR': 'Vista mais baixa' },
  stageKeys: {
    role: 'body',
    'en-US': 'Arrow keys turn the solid. Up and down tilt it.',
    'es-MX': 'Las flechas giran el cuerpo. Arriba y abajo lo inclinan.',
    'pt-BR': 'As setas giram o sólido. Cima e baixo o inclinam.',
  },
  viewLevel: { role: 'data', 'en-US': 'Level view', 'es-MX': 'Vista a nivel', 'pt-BR': 'Vista no nível' },
  viewCorner: { role: 'data', 'en-US': 'Corner view', 'es-MX': 'Vista de esquina', 'pt-BR': 'Vista de canto' },
  viewTop: { role: 'data', 'en-US': 'Top view', 'es-MX': 'Vista desde arriba', 'pt-BR': 'Vista de cima' },
  viewTurn: { role: 'data', 'en-US': 'Turn {n} of 4', 'es-MX': 'Giro {n} de 4', 'pt-BR': 'Giro {n} de 4' },
  solidFacts: {
    role: 'data',
    'en-US': '{faces} faces, {edges} edges, {vertices} vertices',
    'es-MX': '{faces} caras, {edges} aristas, {vertices} vértices',
    'pt-BR': '{faces} faces, {edges} arestas, {vertices} vértices',
  },
  solidFactsCylinder: {
    role: 'data',
    'en-US': '2 flat ends and 1 curved side, standing on the y line',
    'es-MX': '2 bases planas y 1 cara curva, de pie sobre la línea y',
    'pt-BR': '2 bases planas e 1 superfície curva, em pé sobre a linha y',
  },
  cylLevel: {
    role: 'data',
    'en-US': 'The plane lies across the cylinder, level with its flat ends.',
    'es-MX': 'El plano cruza el cilindro, a nivel con sus bases.',
    'pt-BR': 'O plano cruza o cilindro, no nível das bases.',
  },
  cylAlong: {
    role: 'data',
    'en-US': 'The plane runs along the cylinder’s axis.',
    'es-MX': 'El plano va a lo largo del eje del cilindro.',
    'pt-BR': 'O plano segue ao longo do eixo do cilindro.',
  },
  cylSlanted: {
    role: 'data',
    'en-US': 'The plane is slanted across the cylinder.',
    'es-MX': 'El plano cruza el cilindro en diagonal.',
    'pt-BR': 'O plano cruza o cilindro na diagonal.',
  },
  cylFactSize: { role: 'data', 'en-US': 'Radius, height', 'es-MX': 'Radio, altura', 'pt-BR': 'Raio, altura' },
  cylFactNormal: { role: 'data', 'en-US': 'Plane direction (x, y, z)', 'es-MX': 'Dirección del plano (x, y, z)', 'pt-BR': 'Direção do plano (x, y, z)' },
  cylFactPosition: { role: 'data', 'en-US': 'Plane position', 'es-MX': 'Posición del plano', 'pt-BR': 'Posição do plano' },

  secOptionsHeading: { role: 'heading', 'en-US': 'Which shape is the cut?', 'es-MX': '¿Qué forma tiene el corte?', 'pt-BR': 'Qual é a forma do corte?' },
  secCutNote: {
    role: 'body',
    'en-US': 'The thick line is where the plane cuts.',
    'es-MX': 'La línea gruesa es donde corta el plano.',
    'pt-BR': 'A linha grossa é onde o plano corta.',
  },
  secChosen: { role: 'data', 'en-US': 'Chosen: {shape}', 'es-MX': 'Elegida: {shape}', 'pt-BR': 'Escolhida: {shape}' },
  secChosenNone: { role: 'data', 'en-US': 'Chosen: none', 'es-MX': 'Elegida: ninguna', 'pt-BR': 'Escolhida: nenhuma' },
  secCrossing: { role: 'data', 'en-US': 'The plane crosses {n} edges.', 'es-MX': 'El plano cruza {n} aristas.', 'pt-BR': 'O plano cruza {n} arestas.' },
  secTableCaption: { role: 'heading', 'en-US': 'What the plane crosses', 'es-MX': 'Qué cruza el plano', 'pt-BR': 'O que o plano cruza' },
  colFact: { role: 'data', 'en-US': 'Fact', 'es-MX': 'Dato', 'pt-BR': 'Dado' },
  colCount: { role: 'data', 'en-US': 'Count', 'es-MX': 'Cantidad', 'pt-BR': 'Quantidade' },
  secFactEdges: { role: 'data', 'en-US': 'Edges it crosses', 'es-MX': 'Aristas que cruza', 'pt-BR': 'Arestas que cruza' },
  secFactCorners: { role: 'data', 'en-US': 'Corners it touches', 'es-MX': 'Vértices que toca', 'pt-BR': 'Vértices que toca' },
  secFactAbove: { role: 'data', 'en-US': 'Corners on one side', 'es-MX': 'Vértices de un lado', 'pt-BR': 'Vértices de um lado' },
  secFactBelow: { role: 'data', 'en-US': 'Corners on the other side', 'es-MX': 'Vértices del otro lado', 'pt-BR': 'Vértices do outro lado' },
  metSection: { role: 'body', 'en-US': 'You named the shape of the cut.', 'es-MX': 'Nombraste la forma del corte.', 'pt-BR': 'Você nomeou a forma do corte.' },
  hintSection: { role: 'body', 'en-US': 'Not yet. Turn the solid and look again.', 'es-MX': 'Aún no. Gira el cuerpo y mira otra vez.', 'pt-BR': 'Ainda não. Gire o sólido e olhe de novo.' },

  eulHeading: { role: 'heading', 'en-US': 'Count the solid', 'es-MX': 'Cuenta el cuerpo', 'pt-BR': 'Conte o sólido' },
  eulRuleHeading: { role: 'heading', 'en-US': 'The rule', 'es-MX': 'La regla', 'pt-BR': 'A regra' },
  eulRuleNote: {
    role: 'body',
    'en-US': 'Vertices minus edges plus faces always makes 2.',
    'es-MX': 'Vértices menos aristas más caras siempre da 2.',
    'pt-BR': 'Vértices menos arestas mais faces sempre dá 2.',
  },
  eulSpoken: { role: 'data', 'en-US': 'V minus E plus F equals 2', 'es-MX': 'V menos E más F es igual a 2', 'pt-BR': 'V menos E mais F é igual a 2' },
  countVertices: { role: 'data', 'en-US': 'Vertices', 'es-MX': 'Vértices', 'pt-BR': 'Vértices' },
  countEdges: { role: 'data', 'en-US': 'Edges', 'es-MX': 'Aristas', 'pt-BR': 'Arestas' },
  countFaces: { role: 'data', 'en-US': 'Faces', 'es-MX': 'Caras', 'pt-BR': 'Faces' },
  askVertices: { role: 'body', 'en-US': 'Number of vertices', 'es-MX': 'Número de vértices', 'pt-BR': 'Número de vértices' },
  askEdges: { role: 'body', 'en-US': 'Number of edges', 'es-MX': 'Número de aristas', 'pt-BR': 'Número de arestas' },
  askFaces: { role: 'body', 'en-US': 'Number of faces', 'es-MX': 'Número de caras', 'pt-BR': 'Número de faces' },
  eulHidden: { role: 'data', 'en-US': '?', 'es-MX': '?', 'pt-BR': '?' },
  eulStatus: {
    role: 'data',
    'en-US': '{solid}. Vertices: {v}. Edges: {e}. Faces: {f}.',
    'es-MX': '{solid}. Vértices: {v}. Aristas: {e}. Caras: {f}.',
    'pt-BR': '{solid}. Vértices: {v}. Arestas: {e}. Faces: {f}.',
  },
  eulTableCaption: { role: 'heading', 'en-US': 'Counts of the solid', 'es-MX': 'Conteos del cuerpo', 'pt-BR': 'Contagens do sólido' },
  eulSumRow: { role: 'data', 'en-US': 'V - E + F', 'es-MX': 'V - E + F', 'pt-BR': 'V - E + F' },
  metEuler: { role: 'body', 'en-US': 'You found the missing count.', 'es-MX': 'Encontraste el conteo que faltaba.', 'pt-BR': 'Você achou a contagem que faltava.' },
  hintEuler: { role: 'body', 'en-US': 'Not yet. Count again, or use the rule.', 'es-MX': 'Aún no. Cuenta otra vez o usa la regla.', 'pt-BR': 'Ainda não. Conte de novo ou use a regra.' },

  volHeading: { role: 'heading', 'en-US': 'Pyramid inside a prism', 'es-MX': 'Pirámide dentro de un prisma', 'pt-BR': 'Pirâmide dentro de um prisma' },
  volNote: { role: 'body', 'en-US': 'The prism has the same base and height.', 'es-MX': 'El prisma tiene la misma base y altura.', 'pt-BR': 'O prisma tem a mesma base e altura.' },
  volAsk: {
    role: 'body',
    'en-US': 'Volume of the pyramid, in cubic units',
    'es-MX': 'Volumen de la pirámide, en unidades cúbicas',
    'pt-BR': 'Volume da pirâmide, em unidades cúbicas',
  },
  volStatus: {
    role: 'data',
    'en-US': 'Base side {side}, height {height}. Prism: {prism} cubic units.',
    'es-MX': 'Lado de la base {side}, altura {height}. Prisma: {prism} unidades cúbicas.',
    'pt-BR': 'Lado da base {side}, altura {height}. Prisma: {prism} unidades cúbicas.',
  },
  volTableCaption: { role: 'heading', 'en-US': 'The two solids', 'es-MX': 'Los dos cuerpos', 'pt-BR': 'Os dois sólidos' },
  colValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  volSide: { role: 'data', 'en-US': 'Base side', 'es-MX': 'Lado de la base', 'pt-BR': 'Lado da base' },
  volHeight: { role: 'data', 'en-US': 'Height', 'es-MX': 'Altura', 'pt-BR': 'Altura' },
  volPrism: { role: 'data', 'en-US': 'Volume of the prism', 'es-MX': 'Volumen del prisma', 'pt-BR': 'Volume do prisma' },
  metVolume: { role: 'body', 'en-US': 'You found the volume of the pyramid.', 'es-MX': 'Encontraste el volumen de la pirámide.', 'pt-BR': 'Você achou o volume da pirâmide.' },
  hintVolume: { role: 'body', 'en-US': 'Not yet. Compare the pyramid with the prism.', 'es-MX': 'Aún no. Compara la pirámide con el prisma.', 'pt-BR': 'Ainda não. Compare a pirâmide com o prisma.' },

  coneHeading: { role: 'heading', 'en-US': 'Cone inside a cylinder', 'es-MX': 'Cono dentro de un cilindro', 'pt-BR': 'Cone dentro de um cilindro' },
  coneNote: { role: 'body', 'en-US': 'The cylinder has the same base and height.', 'es-MX': 'El cilindro tiene la misma base y altura.', 'pt-BR': 'O cilindro tem a mesma base e altura.' },
  coneAsk: {
    role: 'body',
    'en-US': 'Volume of the cone, as a number of pi cubic units',
    'es-MX': 'Volumen del cono, como número de unidades cúbicas de pi',
    'pt-BR': 'Volume do cone, como número de unidades cúbicas de pi',
  },
  coneStatus: {
    role: 'data',
    'en-US': 'Radius {radius}, height {height}. Cylinder: {cylinder} pi cubic units.',
    'es-MX': 'Radio {radius}, altura {height}. Cilindro: {cylinder} unidades cúbicas de pi.',
    'pt-BR': 'Raio {radius}, altura {height}. Cilindro: {cylinder} unidades cúbicas de pi.',
  },
  coneRadius: { role: 'data', 'en-US': 'Radius', 'es-MX': 'Radio', 'pt-BR': 'Raio' },
  coneCylinder: { role: 'data', 'en-US': 'Volume of the cylinder, in pi', 'es-MX': 'Volumen del cilindro, en pi', 'pt-BR': 'Volume do cilindro, em pi' },
  metCone: { role: 'body', 'en-US': 'You found the volume of the cone.', 'es-MX': 'Encontraste el volumen del cono.', 'pt-BR': 'Você achou o volume do cone.' },
  hintCone: { role: 'body', 'en-US': 'Not yet. Compare the cone with the cylinder.', 'es-MX': 'Aún no. Compara el cono con el cilindro.', 'pt-BR': 'Ainda não. Compare o cone com o cilindro.' },

  slideHeading: { role: 'heading', 'en-US': 'Slide the plane', 'es-MX': 'Desliza el plano', 'pt-BR': 'Deslize o plano' },
  slideGoal: {
    role: 'body',
    'en-US': 'Slide the plane to make this cut: {shape}.',
    'es-MX': 'Desliza el plano para lograr este corte: {shape}.',
    'pt-BR': 'Deslize o plano para obter este corte: {shape}.',
  },
  slideNote: {
    role: 'body',
    'en-US': 'The dashed square is the plane. The thick line is the cut.',
    'es-MX': 'El cuadro punteado es el plano. La línea gruesa es el corte.',
    'pt-BR': 'O quadro pontilhado é o plano. A linha grossa é o corte.',
  },
  slideSliderLabel: { role: 'data', 'en-US': 'Position of the plane', 'es-MX': 'Posición del plano', 'pt-BR': 'Posição do plano' },
  slideValue: { role: 'data', 'en-US': 'Position {n}', 'es-MX': 'Posición {n}', 'pt-BR': 'Posição {n}' },
  slideKeys: {
    role: 'body',
    'en-US': 'Arrow keys move one step. Page keys move four.',
    'es-MX': 'Las flechas mueven un paso. Re Pág y Av Pág mueven cuatro.',
    'pt-BR': 'As setas movem um passo. Page Up e Page Down movem quatro.',
  },
  slideBack: { role: 'action', 'en-US': 'Plane back', 'es-MX': 'Plano atrás', 'pt-BR': 'Plano para trás' },
  slideForward: { role: 'action', 'en-US': 'Plane forward', 'es-MX': 'Plano adelante', 'pt-BR': 'Plano para a frente' },
  slideNone: { role: 'data', 'en-US': 'The plane does not cut through the solid.', 'es-MX': 'El plano no corta el cuerpo.', 'pt-BR': 'O plano não corta o sólido.' },
  slideClipped: { role: 'data', 'en-US': 'The cut runs into a flat end.', 'es-MX': 'El corte llega a una base plana.', 'pt-BR': 'O corte chega a uma base plana.' },
  slideSides: { role: 'data', 'en-US': 'The cut has {n} sides.', 'es-MX': 'El corte tiene {n} lados.', 'pt-BR': 'O corte tem {n} lados.' },
  slideQuad: {
    role: 'data',
    'en-US': 'The cut has 4 sides. Pairs of parallel sides: {pairs}. All sides equal: {equal}. All angles right: {right}.',
    'es-MX': 'El corte tiene 4 lados. Pares de lados paralelos: {pairs}. Todos los lados iguales: {equal}. Todos los ángulos rectos: {right}.',
    'pt-BR': 'O corte tem 4 lados. Pares de lados paralelos: {pairs}. Todos os lados iguais: {equal}. Todos os ângulos retos: {right}.',
  },
  slideYes: { role: 'data', 'en-US': 'yes', 'es-MX': 'sí', 'pt-BR': 'sim' },
  slideNo: { role: 'data', 'en-US': 'no', 'es-MX': 'no', 'pt-BR': 'não' },
  slideStatus: {
    role: 'data',
    'en-US': 'Plane at position {n}. {cut}',
    'es-MX': 'Plano en la posición {n}. {cut}',
    'pt-BR': 'Plano na posição {n}. {cut}',
  },
  slideTableCaption: { role: 'heading', 'en-US': 'Where the plane can sit', 'es-MX': 'Dónde puede estar el plano', 'pt-BR': 'Onde o plano pode ficar' },
  slideColPosition: { role: 'data', 'en-US': 'Position', 'es-MX': 'Posición', 'pt-BR': 'Posição' },
  slideColCut: { role: 'data', 'en-US': 'The cut', 'es-MX': 'El corte', 'pt-BR': 'O corte' },
  metSlide: { role: 'body', 'en-US': 'You slid the plane to the right cut.', 'es-MX': 'Deslizaste el plano al corte correcto.', 'pt-BR': 'Você deslizou o plano até o corte certo.' },
  hintSlide: { role: 'body', 'en-US': 'Not yet. Slide the plane and watch the cut.', 'es-MX': 'Aún no. Desliza el plano y mira el corte.', 'pt-BR': 'Ainda não. Deslize o plano e olhe o corte.' },

  itemApple: { role: 'option', 'en-US': 'Apple', 'es-MX': 'Manzana', 'pt-BR': 'Maçã' },
  itemBread: { role: 'option', 'en-US': 'Bread', 'es-MX': 'Pan', 'pt-BR': 'Pão' },
  itemJuice: { role: 'option', 'en-US': 'Juice', 'es-MX': 'Jugo', 'pt-BR': 'Suco' },
  itemToy: { role: 'option', 'en-US': 'Toy', 'es-MX': 'Juguete', 'pt-BR': 'Brinquedo' },
  itemBook: { role: 'option', 'en-US': 'Book', 'es-MX': 'Libro', 'pt-BR': 'Livro' },
  itemPen: { role: 'option', 'en-US': 'Pen', 'es-MX': 'Pluma', 'pt-BR': 'Caneta' },
  itemCap: { role: 'option', 'en-US': 'Cap', 'es-MX': 'Gorra', 'pt-BR': 'Boné' },
  itemKite: { role: 'option', 'en-US': 'Kite', 'es-MX': 'Papalote', 'pt-BR': 'Pipa' },
  itemShell: { role: 'option', 'en-US': 'Shell', 'es-MX': 'Concha', 'pt-BR': 'Búzio' },
  itemStamp: { role: 'option', 'en-US': 'Stamp', 'es-MX': 'Estampilla', 'pt-BR': 'Selo' },

  stlShelfHeading: { role: 'heading', 'en-US': 'On the stall', 'es-MX': 'En el puesto', 'pt-BR': 'Na barraca' },
  stlBasketHeading: { role: 'heading', 'en-US': 'Your basket', 'es-MX': 'Tu canasta', 'pt-BR': 'Sua cesta' },
  stlHelp: {
    role: 'body',
    'en-US': 'Pick an item, then tap the basket.',
    'es-MX': 'Elige un artículo y toca la canasta.',
    'pt-BR': 'Escolha um item e toque na cesta.',
  },
  stlGoalExact: { role: 'body', 'en-US': 'Spend exactly {amount}.', 'es-MX': 'Gasta exactamente {amount}.', 'pt-BR': 'Gaste exatamente {amount}.' },
  stlGoalMost: {
    role: 'body',
    'en-US': 'You have {amount}. Buy as many items as you can.',
    'es-MX': 'Tienes {amount}. Compra todos los artículos que puedas.',
    'pt-BR': 'Você tem {amount}. Compre o máximo de itens que puder.',
  },
  stlGoalChange: { role: 'body', 'en-US': 'You pay {paid}. You want {change} back.', 'es-MX': 'Pagas {paid}. Quieres {change} de cambio.', 'pt-BR': 'Você paga {paid}. Quer {change} de troco.' },
  stlOnShelf: { role: 'data', 'en-US': '{n} left', 'es-MX': 'quedan {n}', 'pt-BR': 'restam {n}' },
  stlInBasket: { role: 'data', 'en-US': 'x{n}', 'es-MX': 'x{n}', 'pt-BR': 'x{n}' },
  stlRemove: { role: 'action', 'en-US': 'Remove', 'es-MX': 'Quitar', 'pt-BR': 'Remover' },
  stlRemoveLabel: { role: 'data', 'en-US': 'Remove one: {item}', 'es-MX': 'Quitar uno: {item}', 'pt-BR': 'Remover um: {item}' },
  stlEmpty: { role: 'data', 'en-US': 'Nothing in the basket yet.', 'es-MX': 'Aún no hay nada en la canasta.', 'pt-BR': 'Ainda não há nada na cesta.' },
  stlItems: { role: 'data', 'en-US': 'Items: {n}', 'es-MX': 'Artículos: {n}', 'pt-BR': 'Itens: {n}' },
  stlCost: { role: 'data', 'en-US': 'Cost: {amount}', 'es-MX': 'Costo: {amount}', 'pt-BR': 'Custo: {amount}' },
  stlChange: { role: 'data', 'en-US': 'Change: {amount}', 'es-MX': 'Cambio: {amount}', 'pt-BR': 'Troco: {amount}' },
  stlOver: { role: 'data', 'en-US': 'Over by {amount}', 'es-MX': 'Te pasas por {amount}', 'pt-BR': 'Passou {amount}' },
  stlBarLabel: { role: 'data', 'en-US': 'Basket cost bar', 'es-MX': 'Barra del costo de la canasta', 'pt-BR': 'Barra do custo da cesta' },
  stlMarkGoal: { role: 'data', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  stlMarkBudget: { role: 'data', 'en-US': 'Budget', 'es-MX': 'Presupuesto', 'pt-BR': 'Orçamento' },
  stlMarkPaid: { role: 'data', 'en-US': 'You pay', 'es-MX': 'Pagas', 'pt-BR': 'Você paga' },
  stlTableCaption: { role: 'heading', 'en-US': 'Items and prices', 'es-MX': 'Artículos y precios', 'pt-BR': 'Itens e preços' },
  stlColItem: { role: 'data', 'en-US': 'Item', 'es-MX': 'Artículo', 'pt-BR': 'Item' },
  stlColPrice: { role: 'data', 'en-US': 'Price', 'es-MX': 'Precio', 'pt-BR': 'Preço' },
  stlColStock: { role: 'data', 'en-US': 'Stock', 'es-MX': 'Existencias', 'pt-BR': 'Estoque' },
  stlColCount: { role: 'data', 'en-US': 'In basket', 'es-MX': 'En la canasta', 'pt-BR': 'Na cesta' },
  stlColCost: { role: 'data', 'en-US': 'Cost', 'es-MX': 'Costo', 'pt-BR': 'Custo' },
  stlTotal: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  metStall: { role: 'body', 'en-US': 'Your basket meets the goal.', 'es-MX': 'Tu canasta cumple la meta.', 'pt-BR': 'Sua cesta cumpre a meta.' },
  hintStall: { role: 'body', 'en-US': 'Not yet. Change the basket and add up again.', 'es-MX': 'Aún no. Cambia la canasta y suma otra vez.', 'pt-BR': 'Ainda não. Mude a cesta e some de novo.' },
  metStallMost: { role: 'body', 'en-US': 'You bought the most items.', 'es-MX': 'Compraste la mayor cantidad.', 'pt-BR': 'Você comprou o máximo de itens.' },
  hintStallMost: { role: 'body', 'en-US': 'Not yet. Check the budget and the count.', 'es-MX': 'Aún no. Revisa el presupuesto y la cantidad.', 'pt-BR': 'Ainda não. Confira o orçamento e a quantidade.' },

  coinHeading: { role: 'heading', 'en-US': 'Build the stack', 'es-MX': 'Arma la pila', 'pt-BR': 'Monte a pilha' },
  pieceCoin: { role: 'data', 'en-US': 'coin', 'es-MX': 'moneda', 'pt-BR': 'moeda' },
  pieceBill: { role: 'data', 'en-US': 'bill', 'es-MX': 'billete', 'pt-BR': 'nota' },
  piecesCoin: { role: 'data', 'en-US': 'coins', 'es-MX': 'monedas', 'pt-BR': 'moedas' },
  piecesBill: { role: 'data', 'en-US': 'bills', 'es-MX': 'billetes', 'pt-BR': 'notas' },
  coinGoalAmount: { role: 'body', 'en-US': 'Stack {pieces} worth {amount}.', 'es-MX': 'Apila {pieces} que valgan {amount}.', 'pt-BR': 'Empilhe {pieces} que valham {amount}.' },
  coinGoalHeight: { role: 'body', 'en-US': 'Stack {pieces} {height} tall.', 'es-MX': 'Apila {pieces} hasta {height} de alto.', 'pt-BR': 'Empilhe {pieces} até {height} de altura.' },
  coinEach: {
    role: 'data',
    'en-US': 'Each {piece}: worth {amount}, {thick} thick.',
    'es-MX': 'Cada {piece}: vale {amount}, {thick} de grosor.',
    'pt-BR': 'Cada {piece}: vale {amount}, {thick} de espessura.',
  },
  coinSliderLabel: { role: 'data', 'en-US': 'Number of {pieces}', 'es-MX': 'Cantidad de {pieces}', 'pt-BR': 'Quantidade de {pieces}' },
  coinSliderKeys: {
    role: 'body',
    'en-US': 'Arrow keys move the handle one step.',
    'es-MX': 'Las flechas mueven el control un paso.',
    'pt-BR': 'As setas movem o controle um passo.',
  },
  coinStatus: {
    role: 'data',
    'en-US': '{n} {pieces}: worth {amount}, {height} tall.',
    'es-MX': '{n} {pieces}: valen {amount}, {height} de alto.',
    'pt-BR': '{n} {pieces}: valem {amount}, {height} de altura.',
  },
  coinStackLabel: { role: 'data', 'en-US': 'Stack drawn to scale', 'es-MX': 'Pila dibujada a escala', 'pt-BR': 'Pilha desenhada em escala' },
  coinMarkGoal: { role: 'data', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  refPhone: { role: 'data', 'en-US': 'Phone', 'es-MX': 'Celular', 'pt-BR': 'Celular' },
  refBook: { role: 'data', 'en-US': 'Book', 'es-MX': 'Libro', 'pt-BR': 'Livro' },
  refDesk: { role: 'data', 'en-US': 'Desk', 'es-MX': 'Escritorio', 'pt-BR': 'Mesa' },
  refDoor: { role: 'data', 'en-US': 'Door', 'es-MX': 'Puerta', 'pt-BR': 'Porta' },
  coinTableCaption: { role: 'heading', 'en-US': 'Stacks you can build', 'es-MX': 'Pilas que puedes armar', 'pt-BR': 'Pilhas que você pode montar' },
  coinColPieces: { role: 'data', 'en-US': 'Pieces', 'es-MX': 'Piezas', 'pt-BR': 'Peças' },
  coinColWorth: { role: 'data', 'en-US': 'Worth', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  coinColHeight: { role: 'data', 'en-US': 'Height', 'es-MX': 'Altura', 'pt-BR': 'Altura' },
  coinRefCaption: { role: 'heading', 'en-US': 'Heights to compare', 'es-MX': 'Alturas para comparar', 'pt-BR': 'Alturas para comparar' },
  coinColThing: { role: 'data', 'en-US': 'Object', 'es-MX': 'Objeto', 'pt-BR': 'Objeto' },
  metCoin: { role: 'body', 'en-US': 'You built the right stack.', 'es-MX': 'Armaste la pila correcta.', 'pt-BR': 'Você montou a pilha certa.' },
  hintCoin: { role: 'body', 'en-US': 'Not yet. Compare the stack with the goal.', 'es-MX': 'Aún no. Compara la pila con la meta.', 'pt-BR': 'Ainda não. Compare a pilha com a meta.' },
} as const satisfies HorizonteCopy;
