/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/space1/fixtures.ts. Do not edit: change the source and regenerate. */
import type { HorizonteFixture } from '../types.generated';

export const SPACE1_FIXTURES: readonly HorizonteFixture[] = [];
