/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/space1/scorer.ts. Do not edit: change the source and regenerate. */
import { gradeNumberTolerance, sampleArrangement } from '../../v2AnswerShapes.generated';
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import { coinAnswer, coinProblem, readCoinPayload } from './coins.generated';
import { cylinderVolume, prismVolume, slideRange, type SectionShape } from './polyhedra.generated';
import { readRotationPayload, rotationAnswer } from './rotationRules.generated';
import { VOLUME_BOUNDS, eulerBounds, readSolidSectionPayload, slideCut, solidSectionAnswer } from './sectionRules.generated';
import { basketCount, basketMeets, goalTotal, mostItems, basketCost, slotsToBasket, stallContext, readStallPayload } from './stall.generated';
import { TARGET_IDS, isAngle, isTargetId } from './voxels.generated';

type Segment = { payload: unknown };

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };
const review = (diagnostic: 'partial' | 'miss' | 'value' | 'false_alarm' | 'structure'): V2Grade => ({ verdict: 'review', diagnostic });

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const hasKeys = (value: Record<string, unknown>, keys: readonly string[]): boolean => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));

/**
 * invalid: malformed, a target the question does not have, or an angle off the four stops. valid: the figure not turned yet
 * (angle 0) or no target picked. met: the matching target and a turn that carries the figure onto it. review: the right
 * target with the wrong turn (partial when there are several targets), or the wrong target.
 */
function rotationGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readRotationPayload(segment?.payload);
  if (!payload || !isRecord(response) || !hasKeys(response, ['pick', 'angle'])) return INVALID;
  const { pick, angle } = response;
  if (pick !== '' && (!isTargetId(pick) || TARGET_IDS.indexOf(pick) >= payload.targets.length)) return INVALID;
  if (!isAngle(angle)) return INVALID;
  if (rubric === undefined) return VALID;
  const answer = rotationAnswer(payload);
  if (!answer || !isRecord(rubric) || !hasKeys(rubric, ['pick', 'angles']) || rubric.pick !== answer.pick) return INVALID;
  if (JSON.stringify(rubric.angles) !== JSON.stringify(answer.angles)) return INVALID;
  if (pick === '' || angle === 0) return VALID;
  if (pick !== answer.pick) return review('value');
  if (answer.angles.includes(angle)) return MET;
  return review(payload.targets.length > 1 ? 'partial' : 'value');
}

const WHOLE = /^(0|[1-9]\d{0,3})$/;

/**
 * invalid: malformed, a shape the question does not list, a plane off the slider, or a typed number outside the whole numbers it
 * can be. valid: nothing chosen or typed yet, or the plane still where it started. met: the shape the plane cuts (named, or made
 * by sliding the plane), the hidden count, or the volume of the pyramid or the cone in pi. A volume typed as the whole prism or
 * cylinder is review "structure": the one-third was left out. A slide that makes another shape is review "value"; one that
 * makes no clean cut is review "miss".
 */
function sectionGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readSolidSectionPayload(segment?.payload);
  if (!payload || !isRecord(response)) return INVALID;
  if (payload.mode === 'section') {
    if (!hasKeys(response, ['pick']) || typeof response.pick !== 'string') return INVALID;
    const { pick } = response;
    if (pick !== '' && !payload.options.includes(pick as SectionShape)) return INVALID;
    if (rubric === undefined) return VALID;
    const answer = solidSectionAnswer(payload);
    if (!answer || !('pick' in answer) || !isRecord(rubric) || !hasKeys(rubric, ['pick']) || rubric.pick !== answer.pick) return INVALID;
    if (pick === '') return VALID;
    return pick === answer.pick ? MET : review('value');
  }
  if (payload.mode === 'slide') {
    if (!hasKeys(response, ['offset']) || typeof response.offset !== 'number' || !Number.isInteger(response.offset)) return INVALID;
    const { offset } = response;
    const { min, max } = slideRange(payload.solid, payload.normal);
    if (offset < min || offset > max) return INVALID;
    if (rubric === undefined) return VALID;
    if (!isRecord(rubric) || !hasKeys(rubric, ['pick']) || rubric.pick !== payload.target) return INVALID;
    if (offset === payload.start) return VALID;
    const shape = slideCut(payload, offset);
    if (shape === payload.target) return MET;
    return review(shape === null ? 'miss' : 'value');
  }
  if (!hasKeys(response, ['value']) || typeof response.value !== 'string') return INVALID;
  const bounds = payload.mode === 'euler' ? eulerBounds(payload.solid) : VOLUME_BOUNDS;
  const { value } = response;
  if (value !== '' && (!WHOLE.test(value) || gradeNumberTolerance({ value }, undefined, bounds).verdict === 'invalid')) return INVALID;
  if (rubric === undefined) return VALID;
  const answer = solidSectionAnswer(payload);
  if (!answer || !('target' in answer) || !isRecord(rubric) || !hasKeys(rubric, ['target']) || rubric.target !== answer.target) return INVALID;
  if (value === '') return VALID;
  if (gradeNumberTolerance({ value }, { target: answer.target }, bounds).verdict === 'met') return MET;
  const whole = payload.mode === 'volume' ? prismVolume(payload.side, payload.height) : payload.mode === 'cone' ? cylinderVolume(payload.radius, payload.height) : null;
  return review(whole !== null && Number(value) === whole ? 'structure' : 'value');
}

/**
 * invalid: malformed, an item the stall does not sell, a piece that is not an item, or more than the stall holds. valid: an
 * empty or partly filled basket. met: the basket meets the rule (the sum hits the total, or it is the biggest bag the budget
 * buys), whichever items make it. review: under (miss) or over (false_alarm) the total or the budget.
 */
function stallGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readStallPayload(segment?.payload);
  if (!payload || !isRecord(response) || !hasKeys(response, ['slots'])) return INVALID;
  const basket = slotsToBasket(response.slots, payload);
  if (!basket) return INVALID;
  if (rubric === undefined) return VALID;
  if (sampleArrangement(rubric, stallContext(payload)) === null) return INVALID;
  const sound = (rubric as { solutions: unknown[] }).solutions.every((solution) => {
    const held = slotsToBasket(solution, payload);
    return held !== null && basketMeets(payload, held);
  });
  if (!sound) return INVALID;
  if (basketCount(basket) === 0) return VALID;
  if (basketMeets(payload, basket)) return MET;
  const cost = basketCost(payload.items, basket);
  const total = goalTotal(payload.goal);
  if (total !== null) return review(cost < total ? 'miss' : 'false_alarm');
  const { budget } = payload.goal as { kind: 'most'; budget: number };
  return review(cost > budget ? 'false_alarm' : basketCount(basket) < mostItems(payload.items, budget) ? 'miss' : 'value');
}

const COUNT = /^(0|[1-9]\d{0,5})$/;

/**
 * invalid: malformed, a count that is not a whole number on the handle's grid, or above the maximum. valid: nothing set yet
 * (blank or 0). met: the count that makes the amount or the height. review: too few (miss) or too many (false_alarm).
 */
function coinGrade(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = readCoinPayload(segment?.payload);
  if (!payload || !isRecord(response) || !hasKeys(response, ['value']) || typeof response.value !== 'string') return INVALID;
  const { value } = response;
  if (value !== '' && (!COUNT.test(value) || Number(value) > payload.max || Number(value) % payload.step !== 0)) return INVALID;
  if (rubric === undefined) return VALID;
  const answer = coinAnswer(payload);
  if (answer === null || coinProblem(payload) !== null || !isRecord(rubric) || !hasKeys(rubric, ['target']) || rubric.target !== String(answer)) return INVALID;
  if (value === '' || Number(value) === 0) return VALID;
  if (Number(value) === answer) return MET;
  return review(Number(value) < answer ? 'miss' : 'false_alarm');
}

export const SPACE1_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'geometry.mental-rotation.v2': {
    grade: rotationGrade as HorizonteScorer['grade'],
    sample: ((segment: Segment) => {
      const payload = readRotationPayload(segment.payload);
      return { pick: payload && payload.targets.length === 1 ? 'a' : '', angle: 0 };
    }) as HorizonteScorer['sample'],
  },
  'geometry.solid-section.v2': {
    grade: sectionGrade as HorizonteScorer['grade'],
    sample: ((segment: Segment) => {
      const payload = readSolidSectionPayload(segment.payload);
      if (payload?.mode === 'slide') return { offset: payload.start };
      return payload && payload.mode !== 'section' ? { value: '' } : { pick: '' };
    }) as HorizonteScorer['sample'],
  },
  'money.market-stall.v2': {
    grade: stallGrade as HorizonteScorer['grade'],
    sample: (() => ({ slots: {} })) as HorizonteScorer['sample'],
  },
  'money.coin-stack.v2': {
    grade: coinGrade as HorizonteScorer['grade'],
    sample: (() => ({ value: '' })) as HorizonteScorer['sample'],
  },
};
