import type { HorizonteCopy } from '../boardTypes';

/*
 * The words of the eight plane boards (F1.9, F1.11, F1.12), native in en-US, es-MX and pt-BR. Slots like {n} are filled by the
 * board. Every line fits the Copy Budget of its role at the strictest band (06 §3); the words that sit beside a number are
 * data, which the budget leaves free.
 */
export const PLANE1_COPY = {
  less: { role: 'action', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  controlsLabel: { role: 'data', 'en-US': 'Controls', 'es-MX': 'Controles', 'pt-BR': 'Controles' },
  over: { role: 'data', 'en-US': '{n} over {d}', 'es-MX': '{n} sobre {d}', 'pt-BR': '{n} sobre {d}' },
  sayEquals: { role: 'data', 'en-US': 'equals', 'es-MX': 'es igual a', 'pt-BR': 'é igual a' },
  sayPlus: { role: 'data', 'en-US': 'plus', 'es-MX': 'más', 'pt-BR': 'mais' },
  sayMinus: { role: 'data', 'en-US': 'minus', 'es-MX': 'menos', 'pt-BR': 'menos' },
  yourLine: { role: 'data', 'en-US': 'Your line', 'es-MX': 'Tu recta', 'pt-BR': 'Sua reta' },
  price: { role: 'data', 'en-US': 'Price', 'es-MX': 'Precio', 'pt-BR': 'Preço' },
  quantity: { role: 'data', 'en-US': 'Quantity', 'es-MX': 'Cantidad', 'pt-BR': 'Quantidade' },
  goalLine: { role: 'data', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  handlePrice: { role: 'data', 'en-US': 'Price marker', 'es-MX': 'Marcador de precio', 'pt-BR': 'Marcador de preço' },
  sliderPrice: { role: 'body', 'en-US': 'Price', 'es-MX': 'Precio', 'pt-BR': 'Preço' },

  slopeName: { role: 'heading', 'en-US': 'Line with a slope triangle', 'es-MX': 'Recta con triángulo de pendiente', 'pt-BR': 'Reta com triângulo de inclinação' },
  slopeSummary: { role: 'body', 'en-US': 'The line rises. The triangle shows rise over run.', 'es-MX': 'La recta sube. El triángulo muestra la subida sobre el avance.', 'pt-BR': 'A reta sobe. O triângulo mostra a subida sobre o avanço.' },
  lineName: { role: 'data', 'en-US': 'Line', 'es-MX': 'Recta', 'pt-BR': 'Reta' },
  triangleName: { role: 'data', 'en-US': 'Triangle', 'es-MX': 'Triángulo', 'pt-BR': 'Triângulo' },
  edgeName: { role: 'data', 'en-US': 'Slanted side', 'es-MX': 'Lado inclinado', 'pt-BR': 'Lado inclinado' },
  handleTop: { role: 'data', 'en-US': 'Top of the triangle', 'es-MX': 'Punta del triángulo', 'pt-BR': 'Topo do triângulo' },
  sliderRise: { role: 'body', 'en-US': 'Rise', 'es-MX': 'Subida', 'pt-BR': 'Subida' },
  run: { role: 'data', 'en-US': 'Run', 'es-MX': 'Avance', 'pt-BR': 'Avanço' },
  rise: { role: 'data', 'en-US': 'Rise', 'es-MX': 'Subida', 'pt-BR': 'Subida' },
  slope: { role: 'data', 'en-US': 'Slope', 'es-MX': 'Pendiente', 'pt-BR': 'Inclinação' },
  metSlope: { role: 'body', 'en-US': 'You found the rise that stays on the line.', 'es-MX': 'Encontraste la subida que queda sobre la recta.', 'pt-BR': 'Você achou a subida que fica sobre a reta.' },
  hintSlope: { role: 'body', 'en-US': 'Not yet. Make the slanted side follow the line.', 'es-MX': 'Aún no. Haz que el lado inclinado siga la recta.', 'pt-BR': 'Ainda não. Faça o lado inclinado seguir a reta.' },

  rateName: { role: 'heading', 'en-US': 'Value at each step', 'es-MX': 'Valor en cada paso', 'pt-BR': 'Valor em cada passo' },
  rateSummary: { role: 'body', 'en-US': 'The value grows by the same amount each step.', 'es-MX': 'El valor crece lo mismo en cada paso.', 'pt-BR': 'O valor cresce o mesmo em cada passo.' },
  axisStep: { role: 'data', 'en-US': 'Step', 'es-MX': 'Paso', 'pt-BR': 'Passo' },
  axisValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  sliderValueAt: { role: 'body', 'en-US': 'Value at step {n}', 'es-MX': 'Valor en el paso {n}', 'pt-BR': 'Valor no passo {n}' },
  handleGraphAt: { role: 'data', 'en-US': 'Graph point at step {n}', 'es-MX': 'Punto de la gráfica en el paso {n}', 'pt-BR': 'Ponto do gráfico no passo {n}' },
  stepN: { role: 'data', 'en-US': 'Step {n}', 'es-MX': 'Paso {n}', 'pt-BR': 'Passo {n}' },
  tableSteps: { role: 'heading', 'en-US': 'Steps and values', 'es-MX': 'Pasos y valores', 'pt-BR': 'Passos e valores' },
  colStep: { role: 'data', 'en-US': 'Step', 'es-MX': 'Paso', 'pt-BR': 'Passo' },
  colValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  statusRate: {
    role: 'data',
    'en-US': 'Rate: {r} per step. Value at step {n}: {v}. Your change per step: {c}',
    'es-MX': 'Ritmo: {r} por paso. Valor en el paso {n}: {v}. Tu cambio por paso: {c}',
    'pt-BR': 'Taxa: {r} por passo. Valor no passo {n}: {v}. Sua mudança por passo: {c}',
  },
  metRate: { role: 'body', 'en-US': 'You reached the right value at that step.', 'es-MX': 'Llegaste al valor correcto en ese paso.', 'pt-BR': 'Você chegou ao valor certo nesse passo.' },
  hintRate: { role: 'body', 'en-US': 'Not yet. Add the rate once for each step.', 'es-MX': 'Aún no. Suma el ritmo una vez por cada paso.', 'pt-BR': 'Ainda não. Some a taxa uma vez por passo.' },

  linkedName: { role: 'heading', 'en-US': 'Table, graph and equation', 'es-MX': 'Tabla, gráfica y ecuación', 'pt-BR': 'Tabela, gráfico e equação' },
  linkedSummary: { role: 'body', 'en-US': 'The line must pass through the table points.', 'es-MX': 'La recta debe pasar por los puntos de la tabla.', 'pt-BR': 'A reta deve passar pelos pontos da tabela.' },
  sliderSlope: { role: 'body', 'en-US': 'Slope (m)', 'es-MX': 'Pendiente (m)', 'pt-BR': 'Inclinação (m)' },
  sliderIntercept: { role: 'body', 'en-US': 'Intercept (b)', 'es-MX': 'Ordenada al origen (b)', 'pt-BR': 'Intercepto (b)' },
  handleSlope: { role: 'data', 'en-US': 'Slope point', 'es-MX': 'Punto de la pendiente', 'pt-BR': 'Ponto da inclinação' },
  handleIntercept: { role: 'data', 'en-US': 'Intercept point', 'es-MX': 'Punto de la ordenada', 'pt-BR': 'Ponto do intercepto' },
  tablePoint: { role: 'data', 'en-US': 'Table point {n}', 'es-MX': 'Punto de la tabla {n}', 'pt-BR': 'Ponto da tabela {n}' },
  tableLinked: { role: 'heading', 'en-US': 'Points on the line', 'es-MX': 'Puntos sobre la recta', 'pt-BR': 'Pontos sobre a reta' },
  colX: { role: 'data', 'en-US': 'x', 'es-MX': 'x', 'pt-BR': 'x' },
  colGiven: { role: 'data', 'en-US': 'Table y', 'es-MX': 'y de la tabla', 'pt-BR': 'y da tabela' },
  colLine: { role: 'data', 'en-US': 'Line y', 'es-MX': 'y de la recta', 'pt-BR': 'y da reta' },
  equation: { role: 'data', 'en-US': 'Equation', 'es-MX': 'Ecuación', 'pt-BR': 'Equação' },
  intercept: { role: 'data', 'en-US': 'Intercept', 'es-MX': 'Ordenada', 'pt-BR': 'Intercepto' },
  metLinked: { role: 'body', 'en-US': 'Your line passes through both points.', 'es-MX': 'Tu recta pasa por los dos puntos.', 'pt-BR': 'Sua reta passa pelos dois pontos.' },
  hintLinked: { role: 'body', 'en-US': 'Not yet. Check each table row against the line.', 'es-MX': 'Aún no. Compara cada fila de la tabla con la recta.', 'pt-BR': 'Ainda não. Compare cada linha da tabela com a reta.' },

  breakName: { role: 'heading', 'en-US': 'Revenue and cost', 'es-MX': 'Ingresos y costos', 'pt-BR': 'Receita e custos' },
  breakSummary: { role: 'body', 'en-US': 'Break-even is where revenue meets cost.', 'es-MX': 'El punto de equilibrio es donde el ingreso iguala al costo.', 'pt-BR': 'O ponto de equilíbrio é onde a receita iguala o custo.' },
  axisUnitsSold: { role: 'data', 'en-US': 'Units sold', 'es-MX': 'Unidades vendidas', 'pt-BR': 'Unidades vendidas' },
  axisMoney: { role: 'data', 'en-US': 'Money', 'es-MX': 'Dinero', 'pt-BR': 'Dinheiro' },
  revenue: { role: 'data', 'en-US': 'Revenue', 'es-MX': 'Ingreso', 'pt-BR': 'Receita' },
  cost: { role: 'data', 'en-US': 'Cost', 'es-MX': 'Costo', 'pt-BR': 'Custo' },
  costHere: { role: 'data', 'en-US': 'Cost at these units', 'es-MX': 'Costo con estas unidades', 'pt-BR': 'Custo com estas unidades' },
  handleUnitsSold: { role: 'data', 'en-US': 'Units marker', 'es-MX': 'Marcador de unidades', 'pt-BR': 'Marcador de unidades' },
  sliderUnitsSold: { role: 'body', 'en-US': 'Units sold', 'es-MX': 'Unidades vendidas', 'pt-BR': 'Unidades vendidas' },
  factsBreak: {
    role: 'data',
    'en-US': 'Fixed cost: {f}. Price per unit: {p}. Cost per unit: {u}',
    'es-MX': 'Costo fijo: {f}. Precio por unidad: {p}. Costo por unidad: {u}',
    'pt-BR': 'Custo fixo: {f}. Preço por unidade: {p}. Custo por unidade: {u}',
  },
  statusBreak: {
    role: 'data',
    'en-US': 'Units: {n}. Revenue: {r}. Cost: {c}. Profit: {p}',
    'es-MX': 'Unidades: {n}. Ingreso: {r}. Costo: {c}. Ganancia: {p}',
    'pt-BR': 'Unidades: {n}. Receita: {r}. Custo: {c}. Lucro: {p}',
  },
  metBreak: { role: 'body', 'en-US': 'Revenue and cost meet at your units.', 'es-MX': 'El ingreso y el costo se igualan en tus unidades.', 'pt-BR': 'A receita e o custo se igualam nas suas unidades.' },
  hintBreak: { role: 'body', 'en-US': 'Not yet. Find where the two lines cross.', 'es-MX': 'Aún no. Busca dónde se cruzan las dos rectas.', 'pt-BR': 'Ainda não. Procure onde as duas retas se cruzam.' },

  costName: { role: 'heading', 'en-US': 'Cost per unit', 'es-MX': 'Costo por unidad', 'pt-BR': 'Custo por unidade' },
  costSummary: { role: 'body', 'en-US': 'Spreading the fixed cost makes each unit cheaper.', 'es-MX': 'Repartir el costo fijo abarata cada unidad.', 'pt-BR': 'Dividir o custo fixo barateia cada unidade.' },
  axisUnitsMade: { role: 'data', 'en-US': 'Units made', 'es-MX': 'Unidades producidas', 'pt-BR': 'Unidades produzidas' },
  axisCostPer: { role: 'data', 'en-US': 'Cost per unit', 'es-MX': 'Costo por unidad', 'pt-BR': 'Custo por unidade' },
  averageCost: { role: 'data', 'en-US': 'Average cost', 'es-MX': 'Costo promedio', 'pt-BR': 'Custo médio' },
  extraCost: { role: 'data', 'en-US': 'Extra cost per unit', 'es-MX': 'Costo extra por unidad', 'pt-BR': 'Custo extra por unidade' },
  handleUnitsMade: { role: 'data', 'en-US': 'Units marker', 'es-MX': 'Marcador de unidades', 'pt-BR': 'Marcador de unidades' },
  sliderUnitsMade: { role: 'body', 'en-US': 'Units made', 'es-MX': 'Unidades producidas', 'pt-BR': 'Unidades produzidas' },
  factsCost: {
    role: 'data',
    'en-US': 'Fixed cost: {f}. Extra cost per unit: {v}',
    'es-MX': 'Costo fijo: {f}. Costo extra por unidad: {v}',
    'pt-BR': 'Custo fixo: {f}. Custo extra por unidade: {v}',
  },
  statusCost: {
    role: 'data',
    'en-US': 'Units: {n}. Total cost: {t}. Average cost: {a}. Goal: {g}',
    'es-MX': 'Unidades: {n}. Costo total: {t}. Costo promedio: {a}. Meta: {g}',
    'pt-BR': 'Unidades: {n}. Custo total: {t}. Custo médio: {a}. Meta: {g}',
  },
  metCost: { role: 'body', 'en-US': 'The average cost now matches the goal.', 'es-MX': 'El costo promedio ya coincide con la meta.', 'pt-BR': 'O custo médio agora bate com a meta.' },
  hintCost: { role: 'body', 'en-US': 'Not yet. Watch the average cost as units change.', 'es-MX': 'Aún no. Mira el costo promedio al cambiar las unidades.', 'pt-BR': 'Ainda não. Observe o custo médio ao mudar as unidades.' },

  markupName: { role: 'heading', 'en-US': 'Price and profit', 'es-MX': 'Precio y ganancia', 'pt-BR': 'Preço e lucro' },
  markupSummary: { role: 'body', 'en-US': 'Markup is on cost. Margin is on price.', 'es-MX': 'El recargo es sobre el costo. El margen, sobre el precio.', 'pt-BR': 'O acréscimo é sobre o custo. A margem é sobre o preço.' },
  wordMarkup: { role: 'data', 'en-US': 'Markup', 'es-MX': 'Recargo', 'pt-BR': 'Acréscimo' },
  wordMargin: { role: 'data', 'en-US': 'Margin', 'es-MX': 'Margen', 'pt-BR': 'Margem' },
  axisPercent: { role: 'data', 'en-US': 'Percent', 'es-MX': 'Porcentaje', 'pt-BR': 'Porcentagem' },
  factsMarkup: { role: 'data', 'en-US': 'Cost: {c}. Goal: {w} {n}%', 'es-MX': 'Costo: {c}. Meta: {w} {n}%', 'pt-BR': 'Custo: {c}. Meta: {w} {n}%' },
  statusMarkup: {
    role: 'data',
    'en-US': 'Price: {p}. Profit: {f}. Markup: {mk}%. Margin: {mg}%',
    'es-MX': 'Precio: {p}. Ganancia: {f}. Recargo: {mk}%. Margen: {mg}%',
    'pt-BR': 'Preço: {p}. Lucro: {f}. Acréscimo: {mk}%. Margem: {mg}%',
  },
  metMarkup: { role: 'body', 'en-US': 'The price gives the percent you were asked for.', 'es-MX': 'El precio da el porcentaje que te pidieron.', 'pt-BR': 'O preço dá a porcentagem que pediram.' },
  hintMarkup: { role: 'body', 'en-US': 'Not yet. Compare the marker with the goal line.', 'es-MX': 'Aún no. Compara el marcador con la línea de la meta.', 'pt-BR': 'Ainda não. Compare o marcador com a linha da meta.' },

  marketName: { role: 'heading', 'en-US': 'Supply and demand', 'es-MX': 'Oferta y demanda', 'pt-BR': 'Oferta e demanda' },
  marketSummary: { role: 'body', 'en-US': 'A shift moves a whole curve. Find the new price.', 'es-MX': 'Un desplazamiento mueve toda la curva. Halla el precio nuevo.', 'pt-BR': 'Um deslocamento move a curva toda. Ache o novo preço.' },
  demand: { role: 'data', 'en-US': 'Demand', 'es-MX': 'Demanda', 'pt-BR': 'Demanda' },
  supply: { role: 'data', 'en-US': 'Supply', 'es-MX': 'Oferta', 'pt-BR': 'Oferta' },
  demandAfter: { role: 'data', 'en-US': 'Demand after the shift', 'es-MX': 'Demanda tras el desplazamiento', 'pt-BR': 'Demanda após o deslocamento' },
  supplyAfter: { role: 'data', 'en-US': 'Supply after the shift', 'es-MX': 'Oferta tras el desplazamiento', 'pt-BR': 'Oferta após o deslocamento' },
  supplyHere: { role: 'data', 'en-US': 'Supply at this price', 'es-MX': 'Oferta con este precio', 'pt-BR': 'Oferta com este preço' },
  choiceLegend: { role: 'body', 'en-US': 'Which way does the price move?', 'es-MX': '¿Hacia dónde se mueve el precio?', 'pt-BR': 'Para onde o preço se move?' },
  goesUp: { role: 'option', 'en-US': 'Goes up', 'es-MX': 'Sube', 'pt-BR': 'Sobe' },
  goesDown: { role: 'option', 'en-US': 'Goes down', 'es-MX': 'Baja', 'pt-BR': 'Desce' },
  shiftDemandUp: { role: 'data', 'en-US': 'Demand adds {n} units at every price', 'es-MX': 'La demanda suma {n} unidades en cada precio', 'pt-BR': 'A demanda soma {n} unidades em cada preço' },
  shiftDemandDown: { role: 'data', 'en-US': 'Demand loses {n} units at every price', 'es-MX': 'La demanda pierde {n} unidades en cada precio', 'pt-BR': 'A demanda perde {n} unidades em cada preço' },
  shiftSupplyUp: { role: 'data', 'en-US': 'Supply adds {n} units at every price', 'es-MX': 'La oferta suma {n} unidades en cada precio', 'pt-BR': 'A oferta soma {n} unidades em cada preço' },
  shiftSupplyDown: { role: 'data', 'en-US': 'Supply loses {n} units at every price', 'es-MX': 'La oferta pierde {n} unidades en cada precio', 'pt-BR': 'A oferta perde {n} unidades em cada preço' },
  beforeMarket: {
    role: 'data',
    'en-US': 'Before the shift: price {p}, quantity {q}',
    'es-MX': 'Antes del desplazamiento: precio {p}, cantidad {q}',
    'pt-BR': 'Antes do deslocamento: preço {p}, quantidade {q}',
  },
  statusMarket: {
    role: 'data',
    'en-US': 'Price: {p}. Quantity demanded: {d}. Quantity supplied: {s}. {state}',
    'es-MX': 'Precio: {p}. Cantidad demandada: {d}. Cantidad ofrecida: {s}. {state}',
    'pt-BR': 'Preço: {p}. Quantidade demandada: {d}. Quantidade ofertada: {s}. {state}',
  },
  shortage: { role: 'data', 'en-US': 'Shortage of {n}', 'es-MX': 'Escasez de {n}', 'pt-BR': 'Escassez de {n}' },
  surplus: { role: 'data', 'en-US': 'Surplus of {n}', 'es-MX': 'Excedente de {n}', 'pt-BR': 'Excedente de {n}' },
  balanced: { role: 'data', 'en-US': 'Balanced', 'es-MX': 'En equilibrio', 'pt-BR': 'Em equilíbrio' },
  metMarket: { role: 'body', 'en-US': 'You read the shift and found the new price.', 'es-MX': 'Leíste el desplazamiento y hallaste el precio nuevo.', 'pt-BR': 'Você leu o deslocamento e achou o novo preço.' },
  hintMarket: { role: 'body', 'en-US': 'Not yet. Find where the curves meet after the shift.', 'es-MX': 'Aún no. Busca dónde se cruzan las curvas tras el desplazamiento.', 'pt-BR': 'Ainda não. Procure onde as curvas se cruzam após o deslocamento.' },

  elasticName: { role: 'heading', 'en-US': 'Elasticity of demand', 'es-MX': 'Elasticidad de la demanda', 'pt-BR': 'Elasticidade da demanda' },
  elasticSummary: { role: 'body', 'en-US': 'Elasticity shows how much quantity reacts to price.', 'es-MX': 'La elasticidad muestra cuánto reacciona la cantidad al precio.', 'pt-BR': 'A elasticidade mostra quanto a quantidade reage ao preço.' },
  statusElastic: {
    role: 'data',
    'en-US': 'Price: {p}. Quantity: {q}. Elasticity: {e}. {kind}',
    'es-MX': 'Precio: {p}. Cantidad: {q}. Elasticidad: {e}. {kind}',
    'pt-BR': 'Preço: {p}. Quantidade: {q}. Elasticidade: {e}. {kind}',
  },
  goalElastic: { role: 'data', 'en-US': 'Goal elasticity', 'es-MX': 'Elasticidad meta', 'pt-BR': 'Elasticidade meta' },
  kindElastic: { role: 'data', 'en-US': 'Elastic', 'es-MX': 'Elástica', 'pt-BR': 'Elástica' },
  kindUnit: { role: 'data', 'en-US': 'Unit elastic', 'es-MX': 'Elasticidad unitaria', 'pt-BR': 'Elasticidade unitária' },
  kindInelastic: { role: 'data', 'en-US': 'Inelastic', 'es-MX': 'Inelástica', 'pt-BR': 'Inelástica' },
  metElastic: { role: 'body', 'en-US': 'The elasticity now matches the goal.', 'es-MX': 'La elasticidad ya coincide con la meta.', 'pt-BR': 'A elasticidade agora bate com a meta.' },
  hintElastic: { role: 'body', 'en-US': 'Not yet. See how quantity changes as the price moves.', 'es-MX': 'Aún no. Mira cómo cambia la cantidad al mover el precio.', 'pt-BR': 'Ainda não. Veja como a quantidade muda ao mover o preço.' },
} as const satisfies HorizonteCopy;
