/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/plane1/scorer.ts. Do not edit: change the source and regenerate. */
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import { solveBreakEven, solveCostStructure, solveMarginMarkup, type BreakEven, type CostStructure, type MarginMarkup } from './finance.generated';
import { CHOICES, solveElasticity, solveMarketShift, type Choice, type Elasticity, type MarketAnswer, type MarketShift } from './market.generated';
import {
  hasOnly, inRange, isLineFit, solveLinkedViews, solveRateOfChange, solveSlopeTriangle, whole,
  type LineFit, type LinkedViews, type RateOfChange, type SlopeTriangle, type Solved,
} from './model.generated';

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };
const REVIEW: V2Grade = { verdict: 'review', diagnostic: 'value' };

/** The ladder every Plane pack scorer shares: untouched is valid, the key is met, anything else well-formed is review. */
const ladder = (touched: boolean, met: boolean): V2Grade => (!touched ? VALID : met ? MET : REVIEW);

type Spec<Payload, Answer, Response> = {
  solve: (payload: unknown) => Solved<Answer>;
  /** The response when it is well-formed for this payload, otherwise null. */
  read: (payload: Payload, response: unknown) => Response | null;
  /** The response that leaves the board as it starts. */
  untouched: (payload: Payload) => Response;
  /** Whether the rubric's target is the one answer the payload derives. */
  isKey: (target: unknown, answer: Answer) => boolean;
  met: (response: Response, answer: Answer) => boolean;
  same: (a: Response, b: Response) => boolean;
};

/**
 * invalid: a payload with no single whole answer, a malformed response (an extra field, a value off the grid), or (with a rubric)
 * a key that is not the one derived answer. valid: the board untouched, and every well-formed response without a rubric.
 * review: well-formed and changed, but not the answer; diagnostic value. met: the answer.
 */
function scorer<Payload, Answer, Response>(spec: Spec<Payload, Answer, Response>): HorizonteScorer {
  const payloadOf = (segment: unknown): unknown => (segment as { payload?: unknown } | null | undefined)?.payload;
  const grade = (segment: unknown, response: unknown, rubric: unknown): V2Grade => {
    const payload = payloadOf(segment);
    const solution = spec.solve(payload);
    if (!solution.ok) return INVALID;
    const read = spec.read(payload as Payload, response);
    if (read === null) return INVALID;
    if (rubric === undefined) return VALID;
    if (!hasOnly(rubric, ['target']) || !spec.isKey(rubric.target, solution.answer)) return INVALID;
    return ladder(!spec.same(read, spec.untouched(payload as Payload)), spec.met(read, solution.answer));
  };
  const sample = (segment: unknown): unknown => spec.untouched(payloadOf(segment) as Payload);
  return { grade: grade as unknown as HorizonteScorer['grade'], sample: sample as unknown as HorizonteScorer['sample'] };
}

type One<Key extends string> = { [K in Key]: number };

/** A response of one whole number under `key`, from the low to the high bound the payload sets. */
function single<Payload, Key extends string>(
  solve: (payload: unknown) => Solved<number>,
  key: Key,
  bounds: (payload: Payload) => readonly [number, number],
  start: (payload: Payload) => number,
): Spec<Payload, number, One<Key>> {
  const wrap = (value: number): One<Key> => ({ [key]: value }) as One<Key>;
  return {
    solve,
    read: (payload, response) => {
      const [low, high] = bounds(payload);
      return hasOnly(response, [key]) && inRange(response[key], low, high) ? wrap(response[key]) : null;
    },
    untouched: (payload) => wrap(start(payload)),
    isKey: (target, answer) => whole(target) && target === answer,
    met: (response, answer) => response[key] === answer,
    same: (a, b) => a[key] === b[key],
  };
}

const LINKED_VIEWS: Spec<LinkedViews, LineFit, LineFit> = {
  solve: solveLinkedViews,
  read: (payload, response) => (isLineFit(response, payload.grid) ? { m: response.m, b: response.b } : null),
  untouched: (payload) => ({ m: payload.start.m, b: payload.start.b }),
  isKey: (target, answer) => hasOnly(target, ['m', 'b']) && target.m === answer.m && target.b === answer.b,
  met: (response, answer) => response.m === answer.m && response.b === answer.b,
  same: (a, b) => a.m === b.m && a.b === b.b,
};

type MarketResponse = { direction: Choice; price: number };

const MARKET_SHIFT: Spec<MarketShift, MarketAnswer, MarketResponse> = {
  solve: solveMarketShift,
  read: (payload, response) =>
    hasOnly(response, ['direction', 'price']) && typeof response.direction === 'string' && (CHOICES as readonly string[]).includes(response.direction) && inRange(response.price, 0, payload.pMax)
      ? { direction: response.direction as Choice, price: response.price }
      : null,
  untouched: (payload) => ({ direction: 'unset', price: payload.start }),
  isKey: (target, answer) => hasOnly(target, ['direction', 'price']) && target.direction === answer.direction && target.price === answer.price,
  met: (response, answer) => response.direction === answer.direction && response.price === answer.price,
  same: (a, b) => a.direction === b.direction && a.price === b.price,
};

export const PLANE1_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'alg.slope-triangle.v2': scorer(single<SlopeTriangle, 'rise'>(solveSlopeTriangle, 'rise', (payload) => [0, payload.grid.yMax - payload.line.from.y], (payload) => payload.start)),
  'alg.rate-of-change.v2': scorer(single<RateOfChange, 'y'>(solveRateOfChange, 'y', (payload) => [payload.grid.yMin, payload.grid.yMax], (payload) => payload.start)),
  'alg.linked-views.v2': scorer(LINKED_VIEWS),
  'fin.break-even.v2': scorer(single<BreakEven, 'units'>(solveBreakEven, 'units', (payload) => [0, payload.maxUnits], (payload) => payload.start)),
  'fin.cost-structure.v2': scorer(single<CostStructure, 'units'>(solveCostStructure, 'units', (payload) => [1, payload.maxUnits], (payload) => payload.start)),
  'fin.margin-markup.v2': scorer(single<MarginMarkup, 'price'>(solveMarginMarkup, 'price', (payload) => [0, payload.maxPrice], (payload) => payload.start)),
  'econ.market-shift.v2': scorer(MARKET_SHIFT),
  'econ.elasticity.v2': scorer(single<Elasticity, 'price'>(solveElasticity, 'price', (payload) => [1, payload.pMax], (payload) => payload.start)),
};
