"""Generates filebase/src/lib/badgeDesign.generated.ts (OD-20 achievement image).

Depot draws the image with librsvg (sharp), which cannot load a web font and
silently falls back to whatever system face it finds. So the image carries no
<text>: every string is set in the design system's own faces (Frontend Bible
02 D3: Fredoka for display, Nunito for body) as glyph outlines, taken from
the SAME self-hosted woff2 files the rebuilt frontend serves, instanced at the
weight the image uses. The light-mode colour tokens are mirrored from the
generated sheet (frontend/src/rebuild/design/tokens.css) so the renderer can
only name a token colour; a filebase test pins this mirror to the sheet.

Zero spend, deterministic, run by hand after a token or font change:
    python filebase/scripts/build-badge-assets.py
Needs fontTools with brotli (woff2).
"""
import json
import re
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = Path(__file__).resolve().parents[2]
FONTS = REPO / 'frontend/public/fonts'
TOKENS = REPO / 'frontend/src/rebuild/design/tokens.css'
OUT = REPO / 'filebase/src/lib/badgeDesign.generated.ts'

FACES = {
    # 02 D3 display face at the display-* weight (kicker, first name, wordmark).
    'display': ('fredoka-latin-v1.woff2', 700),
    # 02 D3 body face at the question/answer weight (the label).
    'body': ('nunito-latin-v1.woff2', 700),
}


def ntos(value):
    return str(int(round(value)))


def face(file, weight):
    font = TTFont(FONTS / file)
    font = instantiateVariableFont(font, {'wght': weight})
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font['hmtx']
    glyphs = {}
    for code in sorted(cmap):
        char = chr(code)
        if not char.isprintable() and char != ' ':
            continue
        name = cmap[code]
        pen = SVGPathPen(glyph_set, ntos=ntos)
        # Font units are y-up; the SVG is y-down, so the outline is flipped here once.
        glyph_set[name].draw(TransformPen(pen, (1, 0, 0, -1, 0, 0)))
        glyphs[char] = [hmtx[name][0], pen.getCommands()]
    return {
        'unitsPerEm': font['head'].unitsPerEm,
        'ascent': font['hhea'].ascent,
        'descent': font['hhea'].descent,
        'glyphs': glyphs,
    }


def tokens():
    sheet = TOKENS.read_text(encoding='utf8')
    light = sheet.split('}', 1)[0]
    return {name: value.lower() for name, value in re.findall(r'--([\w-]+):\s*(#[0-9a-fA-F]{6})\b', light)}


def main():
    data = {
        'tokens': tokens(),
        'faces': {key: face(file, weight) for key, (file, weight) in FACES.items()},
    }
    body = json.dumps(data, ensure_ascii=False, separators=(',', ':'), sort_keys=True)
    OUT.write_text(
        '/* Generated by filebase/scripts/build-badge-assets.py from frontend/public/fonts and\n'
        ' * frontend/src/rebuild/design/tokens.css. Do not edit by hand; rerun the script. */\n'
        'export interface BadgeFace { unitsPerEm: number; ascent: number; descent: number; glyphs: Record<string, [number, string]> }\n'
        'export interface BadgeDesign { tokens: Record<string, string>; faces: { display: BadgeFace; body: BadgeFace } }\n'
        f'export const BADGE_DESIGN: BadgeDesign = {body};\n',
        encoding='utf8',
        newline='\n',
    )
    print(f'wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
