import type { HorizonteCopy } from '../boardTypes';

export const FIN2_COPY = {
  tray: { role: 'heading', band: '13-17', 'en-US': 'Pieces', 'es-MX': 'Piezas', 'pt-BR': 'Peças' },
  moveHeading: { role: 'heading', band: '13-17', 'en-US': 'Move a piece', 'es-MX': 'Mueve una pieza', 'pt-BR': 'Mova uma peça' },
  trayEmpty: { role: 'body', band: '13-17', 'en-US': 'Every piece is placed.', 'es-MX': 'Todas las piezas están colocadas.', 'pt-BR': 'Todas as peças estão no lugar.' },
  backToTray: { role: 'option', band: '13-17', 'en-US': 'Back to the pieces', 'es-MX': 'Volver a las piezas', 'pt-BR': 'Voltar às peças' },
  showTable: { role: 'action', band: '13-17', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', band: '13-17', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  none: { role: 'data', band: '13-17', 'en-US': 'nothing yet', 'es-MX': 'nada todavía', 'pt-BR': 'nada ainda' },
  placed: { role: 'data', band: '13-17', 'en-US': '{n} of {n} pieces placed', 'es-MX': '{n} de {n} piezas colocadas', 'pt-BR': '{n} de {n} peças no lugar' },
  colPiece: { role: 'data', band: '13-17', 'en-US': 'Piece', 'es-MX': 'Pieza', 'pt-BR': 'Peça' },
  colPlace: { role: 'data', band: '13-17', 'en-US': 'Place', 'es-MX': 'Lugar', 'pt-BR': 'Lugar' },

  perMonth: { role: 'data', band: '13-17', 'en-US': '{n} a month', 'es-MX': '{n} al mes', 'pt-BR': '{n} por mês' },
  'slot:earned': { role: 'data', band: '13-17', 'en-US': 'Earned income', 'es-MX': 'Ingreso por trabajo', 'pt-BR': 'Renda do trabalho' },
  'slot:passive': { role: 'data', band: '13-17', 'en-US': 'Passive income', 'es-MX': 'Ingreso pasivo', 'pt-BR': 'Renda passiva' },
  'slot:expenses': { role: 'data', band: '13-17', 'en-US': 'Expenses', 'es-MX': 'Gastos', 'pt-BR': 'Despesas' },
  'slot:assets': { role: 'data', band: '13-17', 'en-US': 'Assets', 'es-MX': 'Activos', 'pt-BR': 'Ativos' },
  'slot:liabilities': { role: 'data', band: '13-17', 'en-US': 'Liabilities', 'es-MX': 'Pasivos', 'pt-BR': 'Passivos' },
  'slot:goal': { role: 'data', band: '13-17', 'en-US': 'Goal check', 'es-MX': 'Revisión de la meta', 'pt-BR': 'Checagem da meta' },
  'piece:goal-met': { role: 'option', band: '13-17', 'en-US': 'Passive income is above expenses', 'es-MX': 'El ingreso pasivo supera los gastos', 'pt-BR': 'A renda passiva supera as despesas' },
  'piece:goal-short': { role: 'option', band: '13-17', 'en-US': 'Passive income is not above expenses', 'es-MX': 'El ingreso pasivo no supera los gastos', 'pt-BR': 'A renda passiva não supera as despesas' },
  colItem: { role: 'data', band: '13-17', 'en-US': 'Item', 'es-MX': 'Concepto', 'pt-BR': 'Item' },
  colLine: { role: 'data', band: '13-17', 'en-US': 'Line', 'es-MX': 'Línea', 'pt-BR': 'Linha' },
  colAmount: { role: 'data', band: '13-17', 'en-US': 'Amount', 'es-MX': 'Monto', 'pt-BR': 'Valor' },
  chartStatement: { role: 'data', band: '13-17', 'en-US': 'Bars for monthly income and expenses, with a line at the expenses total', 'es-MX': 'Barras de ingresos y gastos del mes, con una línea en el total de gastos', 'pt-BR': 'Barras de renda e despesas do mês, com uma linha no total de despesas' },
  tableStatement: { role: 'heading', band: '13-17', 'en-US': 'Items by line', 'es-MX': 'Conceptos por línea', 'pt-BR': 'Itens por linha' },
  statementMet: { role: 'body', band: '13-17', 'en-US': 'You sorted every line and named the goal.', 'es-MX': 'Ordenaste cada línea y nombraste la meta.', 'pt-BR': 'Você organizou cada linha e nomeou a meta.' },
  statementHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check each line and the goal.', 'es-MX': 'Aún no. Revisa cada línea y la meta.', 'pt-BR': 'Ainda não. Confira cada linha e a meta.' },

  'slot:strengths': { role: 'data', band: '13-17', 'en-US': 'Strengths', 'es-MX': 'Fortalezas', 'pt-BR': 'Forças' },
  'slot:weaknesses': { role: 'data', band: '13-17', 'en-US': 'Weaknesses', 'es-MX': 'Debilidades', 'pt-BR': 'Fraquezas' },
  'slot:opportunities': { role: 'data', band: '13-17', 'en-US': 'Opportunities', 'es-MX': 'Oportunidades', 'pt-BR': 'Oportunidades' },
  'slot:threats': { role: 'data', band: '13-17', 'en-US': 'Threats', 'es-MX': 'Amenazas', 'pt-BR': 'Ameaças' },
  'slot:do-now': { role: 'data', band: '13-17', 'en-US': 'Do now', 'es-MX': 'Hazlo ya', 'pt-BR': 'Faça já' },
  'slot:schedule': { role: 'data', band: '13-17', 'en-US': 'Schedule', 'es-MX': 'Programa', 'pt-BR': 'Agende' },
  'slot:delegate': { role: 'data', band: '13-17', 'en-US': 'Delegate', 'es-MX': 'Delega', 'pt-BR': 'Delegue' },
  'slot:drop': { role: 'data', band: '13-17', 'en-US': 'Drop', 'es-MX': 'Descarta', 'pt-BR': 'Descarte' },
  'slot:partners': { role: 'data', band: '13-17', 'en-US': 'Key partners', 'es-MX': 'Socios clave', 'pt-BR': 'Parceiros-chave' },
  'slot:activities': { role: 'data', band: '13-17', 'en-US': 'Key activities', 'es-MX': 'Actividades clave', 'pt-BR': 'Atividades-chave' },
  'slot:resources': { role: 'data', band: '13-17', 'en-US': 'Key resources', 'es-MX': 'Recursos clave', 'pt-BR': 'Recursos-chave' },
  'slot:value': { role: 'data', band: '13-17', 'en-US': 'Value proposition', 'es-MX': 'Propuesta de valor', 'pt-BR': 'Proposta de valor' },
  'slot:relationships': { role: 'data', band: '13-17', 'en-US': 'Customer relationships', 'es-MX': 'Relación con clientes', 'pt-BR': 'Relacionamento com clientes' },
  'slot:channels': { role: 'data', band: '13-17', 'en-US': 'Channels', 'es-MX': 'Canales', 'pt-BR': 'Canais' },
  'slot:segments': { role: 'data', band: '13-17', 'en-US': 'Customer segments', 'es-MX': 'Segmentos de clientes', 'pt-BR': 'Segmentos de clientes' },
  'slot:costs': { role: 'data', band: '13-17', 'en-US': 'Cost structure', 'es-MX': 'Estructura de costos', 'pt-BR': 'Estrutura de custos' },
  'slot:revenue': { role: 'data', band: '13-17', 'en-US': 'Revenue streams', 'es-MX': 'Fuentes de ingresos', 'pt-BR': 'Fontes de receita' },
  'note:strengths': { role: 'data', band: '13-17', 'en-US': 'Inside, helps', 'es-MX': 'Interno, ayuda', 'pt-BR': 'Interno, ajuda' },
  'note:weaknesses': { role: 'data', band: '13-17', 'en-US': 'Inside, hurts', 'es-MX': 'Interno, perjudica', 'pt-BR': 'Interno, atrapalha' },
  'note:opportunities': { role: 'data', band: '13-17', 'en-US': 'Outside, helps', 'es-MX': 'Externo, ayuda', 'pt-BR': 'Externo, ajuda' },
  'note:threats': { role: 'data', band: '13-17', 'en-US': 'Outside, hurts', 'es-MX': 'Externo, perjudica', 'pt-BR': 'Externo, atrapalha' },
  'note:do-now': { role: 'data', band: '13-17', 'en-US': 'Urgent and important', 'es-MX': 'Urgente e importante', 'pt-BR': 'Urgente e importante' },
  'note:schedule': { role: 'data', band: '13-17', 'en-US': 'Important, not urgent', 'es-MX': 'Importante, no urgente', 'pt-BR': 'Importante, não urgente' },
  'note:delegate': { role: 'data', band: '13-17', 'en-US': 'Urgent, not important', 'es-MX': 'Urgente, no importante', 'pt-BR': 'Urgente, não importante' },
  'note:drop': { role: 'data', band: '13-17', 'en-US': 'Not urgent, not important', 'es-MX': 'Ni urgente ni importante', 'pt-BR': 'Nem urgente nem importante' },
  rank: { role: 'data', band: '13-17', 'en-US': 'Rank {n}', 'es-MX': 'Lugar {n}', 'pt-BR': 'Posição {n}' },
  weight: { role: 'data', band: '13-17', 'en-US': 'weight {n}', 'es-MX': 'peso {n}', 'pt-BR': 'peso {n}' },
  weights: { role: 'data', band: '13-17', 'en-US': 'Weights', 'es-MX': 'Pesos', 'pt-BR': 'Pesos' },
  dot: { role: 'data', band: '13-17', 'en-US': 'Dot {n}', 'es-MX': 'Punto {n}', 'pt-BR': 'Ponto {n}' },
  colRank: { role: 'data', band: '13-17', 'en-US': 'Your rank', 'es-MX': 'Tu lugar', 'pt-BR': 'Sua posição' },
  colOption: { role: 'data', band: '13-17', 'en-US': 'Option', 'es-MX': 'Opción', 'pt-BR': 'Opção' },
  colQuadrant: { role: 'data', band: '13-17', 'en-US': 'Quadrant', 'es-MX': 'Cuadrante', 'pt-BR': 'Quadrante' },
  chartMap: { role: 'data', band: '13-17', 'en-US': 'Boxes with the number of notes placed in each', 'es-MX': 'Cuadros con el número de notas colocadas en cada uno', 'pt-BR': 'Quadros com o número de notas colocadas em cada um' },
  chartPlot: { role: 'data', band: '13-17', 'en-US': 'Plot of the ideas by their two ratings', 'es-MX': 'Gráfica de las ideas por sus dos calificaciones', 'pt-BR': 'Gráfico das ideias por suas duas notas' },
  chartScores: { role: 'data', band: '13-17', 'en-US': 'Bars for each option on each criterion', 'es-MX': 'Barras de cada opción en cada criterio', 'pt-BR': 'Barras de cada opção em cada critério' },
  tableGrid: { role: 'heading', band: '13-17', 'en-US': 'Notes by box', 'es-MX': 'Notas por cuadro', 'pt-BR': 'Notas por quadro' },
  tablePlot: { role: 'heading', band: '13-17', 'en-US': 'Ideas, ratings and quadrant', 'es-MX': 'Ideas, calificaciones y cuadrante', 'pt-BR': 'Ideias, notas e quadrante' },
  tableScores: { role: 'heading', band: '13-17', 'en-US': 'Scores and your order', 'es-MX': 'Puntajes y tu orden', 'pt-BR': 'Pontuações e sua ordem' },
  sortedMet: { role: 'body', band: '13-17', 'en-US': 'Every note sits in the right box.', 'es-MX': 'Cada nota está en el cuadro correcto.', 'pt-BR': 'Cada nota está no quadro certo.' },
  sortedHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check each box again.', 'es-MX': 'Aún no. Revisa cada cuadro otra vez.', 'pt-BR': 'Ainda não. Confira cada quadro de novo.' },
  plottedMet: { role: 'body', band: '13-17', 'en-US': 'Each idea sits where its ratings point.', 'es-MX': 'Cada idea está donde apuntan sus calificaciones.', 'pt-BR': 'Cada ideia está onde as notas apontam.' },
  plottedHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Compare each rating with the middle line.', 'es-MX': 'Aún no. Compara cada calificación con la línea central.', 'pt-BR': 'Ainda não. Compare cada nota com a linha central.' },
  rankedMet: { role: 'body', band: '13-17', 'en-US': 'Your order follows the weighted scores.', 'es-MX': 'Tu orden sigue los puntajes ponderados.', 'pt-BR': 'Sua ordem segue as pontuações ponderadas.' },
  rankedHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Multiply each score by its weight.', 'es-MX': 'Aún no. Multiplica cada puntaje por su peso.', 'pt-BR': 'Ainda não. Multiplique cada pontuação pelo peso.' },

  period: { role: 'data', band: '13-17', 'en-US': 'Period {n}', 'es-MX': 'Periodo {n}', 'pt-BR': 'Período {n}' },
  step: { role: 'data', band: '13-17', 'en-US': 'Step {n}', 'es-MX': 'Paso {n}', 'pt-BR': 'Etapa {n}' },
  'slot:todo': { role: 'data', band: '13-17', 'en-US': 'To do', 'es-MX': 'Por hacer', 'pt-BR': 'A fazer' },
  'slot:doing': { role: 'data', band: '13-17', 'en-US': 'Doing', 'es-MX': 'En curso', 'pt-BR': 'Em andamento' },
  doneColumn: { role: 'data', band: '13-17', 'en-US': 'Done', 'es-MX': 'Hecho', 'pt-BR': 'Feito' },
  limit: { role: 'data', band: '13-17', 'en-US': 'Limit {n}', 'es-MX': 'Límite {n}', 'pt-BR': 'Limite {n}' },
  after: { role: 'data', band: '13-17', 'en-US': 'After: {n}', 'es-MX': 'Después de: {n}', 'pt-BR': 'Depois de: {n}' },
  takes1: { role: 'data', band: '13-17', 'en-US': 'Takes 1 period', 'es-MX': 'Dura 1 periodo', 'pt-BR': 'Leva 1 período' },
  takesN: { role: 'data', band: '13-17', 'en-US': 'Takes {n} periods', 'es-MX': 'Dura {n} periodos', 'pt-BR': 'Leva {n} períodos' },
  dueStep: { role: 'data', band: '13-17', 'en-US': 'Due by step {n}', 'es-MX': 'Para la etapa {n}', 'pt-BR': 'Até a etapa {n}' },
  deadline: { role: 'data', band: '13-17', 'en-US': 'Deadline', 'es-MX': 'Fecha límite', 'pt-BR': 'Prazo' },
  workers: { role: 'data', band: '13-17', 'en-US': 'Workers', 'es-MX': 'Personas', 'pt-BR': 'Pessoas' },
  busy: { role: 'data', band: '13-17', 'en-US': 'Busy', 'es-MX': 'Ocupadas', 'pt-BR': 'Ocupadas' },
  conflicts: { role: 'data', band: '13-17', 'en-US': 'Breaks a rule: {n}', 'es-MX': 'Rompe una regla: {n}', 'pt-BR': 'Quebra uma regra: {n}' },
  noConflicts: { role: 'body', band: '13-17', 'en-US': 'No task breaks a rule.', 'es-MX': 'Ninguna tarea rompe una regla.', 'pt-BR': 'Nenhuma tarefa quebra uma regra.' },
  colTask: { role: 'data', band: '13-17', 'en-US': 'Task', 'es-MX': 'Tarea', 'pt-BR': 'Tarefa' },
  colAfter: { role: 'data', band: '13-17', 'en-US': 'After', 'es-MX': 'Después de', 'pt-BR': 'Depois de' },
  colTakes: { role: 'data', band: '13-17', 'en-US': 'Periods', 'es-MX': 'Periodos', 'pt-BR': 'Períodos' },
  colDue: { role: 'data', band: '13-17', 'en-US': 'Due step', 'es-MX': 'Etapa límite', 'pt-BR': 'Etapa limite' },
  chartGantt: { role: 'data', band: '13-17', 'en-US': 'Bars by period, with arrows from each task to the next', 'es-MX': 'Barras por periodo, con flechas de cada tarea a la siguiente', 'pt-BR': 'Barras por período, com setas de cada tarefa à seguinte' },
  chartTimeline: { role: 'data', band: '13-17', 'en-US': 'Tasks by step, with arrows from what comes first', 'es-MX': 'Tareas por etapa, con flechas desde lo que va primero', 'pt-BR': 'Tarefas por etapa, com setas do que vem primeiro' },
  chartKanban: { role: 'data', band: '13-17', 'en-US': 'Cards in each column, with the Doing limit', 'es-MX': 'Tarjetas en cada columna, con el límite de En curso', 'pt-BR': 'Cartões em cada coluna, com o limite de Em andamento' },
  tableGantt: { role: 'heading', band: '13-17', 'en-US': 'Tasks and start periods', 'es-MX': 'Tareas y periodos de inicio', 'pt-BR': 'Tarefas e períodos de início' },
  tableTimeline: { role: 'heading', band: '13-17', 'en-US': 'Tasks and steps', 'es-MX': 'Tareas y etapas', 'pt-BR': 'Tarefas e etapas' },
  tableKanban: { role: 'heading', band: '13-17', 'en-US': 'Tasks by column', 'es-MX': 'Tareas por columna', 'pt-BR': 'Tarefas por coluna' },
  planMet: { role: 'body', band: '13-17', 'en-US': 'Your plan keeps the order and the deadline.', 'es-MX': 'Tu plan respeta el orden y la fecha límite.', 'pt-BR': 'Seu plano respeita a ordem e o prazo.' },
  planHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check the order, the workers and the deadline.', 'es-MX': 'Aún no. Revisa el orden, las personas y la fecha límite.', 'pt-BR': 'Ainda não. Confira a ordem, as pessoas e o prazo.' },
  orderMet: { role: 'body', band: '13-17', 'en-US': 'Your order meets every deadline.', 'es-MX': 'Tu orden cumple cada fecha límite.', 'pt-BR': 'Sua ordem cumpre cada prazo.' },
  orderHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. A task comes after what it needs.', 'es-MX': 'Aún no. Una tarea va después de lo que necesita.', 'pt-BR': 'Ainda não. Uma tarefa vem depois do que precisa.' },
  kanbanMet: { role: 'body', band: '13-17', 'en-US': 'You moved every ready task into Doing.', 'es-MX': 'Moviste a En curso cada tarea lista.', 'pt-BR': 'Você moveu para Em andamento cada tarefa pronta.' },
  kanbanHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Only ready tasks can start, within the limit.', 'es-MX': 'Aún no. Solo las tareas listas pueden empezar, dentro del límite.', 'pt-BR': 'Ainda não. Só tarefas prontas podem começar, dentro do limite.' },
} as const satisfies HorizonteCopy;
