/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/fin2/fixtures.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeBand, HorizonteFixture, HorizonteLocale } from '../types.generated';
import type { SlotMap } from './slots.generated';

type Words = readonly [en: string, es: string, pt: string];

const LOCALES: readonly HorizonteLocale[] = ['en-US', 'es-MX', 'pt-BR'];
const pick = (words: Words, locale: HorizonteLocale): string => words[LOCALES.indexOf(locale)]!;
const title = (words: Words): Record<HorizonteLocale, string> => ({ 'en-US': words[0], 'es-MX': words[1], 'pt-BR': words[2] });

interface Spec {
  id: string;
  title: Words;
  band: HorizonteAgeBand;
  ages: [number, number];
  type: string;
  visual: string;
  prompt: Words;
  labels: Record<string, Words>;
  payload: Record<string, unknown>;
  solutions: SlotMap[];
  invalid: SlotMap;
}

function fixture(spec: Spec): HorizonteFixture {
  return {
    id: spec.id,
    title: title(spec.title),
    ageBand: spec.band,
    eligibility: { minimum_age: spec.ages[0], maximum_age: spec.ages[1] },
    segment: (locale) => ({
      id: spec.id, type: spec.type, grading: 'server', visual: { type: spec.visual }, prompt: pick(spec.prompt, locale),
      labels: Object.fromEntries(Object.entries(spec.labels).map(([id, words]) => [id, pick(words, locale)])), payload: spec.payload,
    }),
    rubric: { solutions: spec.solutions },
    ladder: { invalid: { slots: spec.invalid }, valid: { slots: {} }, met: { slots: spec.solutions[0]! } },
  };
}

const CASH = 'money.cash-flow.v2';
const GRID = 'reasoning.decision-grid.v2';
const PLAN = 'plan.schedule-board.v2';

export const FIN2_FIXTURES: readonly HorizonteFixture[] = [
  fixture({
    id: 'cash-flow-short', title: ['Sam\'s month', 'El mes de Sam', 'O mês do Sam'], band: '13-17', ages: [13, 17], type: CASH, visual: 'statement-board',
    prompt: ['Sort each item onto its line, then say if passive income beats expenses.', 'Coloca cada concepto en su línea y di si el ingreso pasivo supera los gastos.', 'Coloque cada item na sua linha e diga se a renda passiva supera as despesas.'],
    labels: {
      'weekend-job': ['Weekend job pay', 'Sueldo de fin de semana', 'Salário de fim de semana'],
      tutoring: ['Tutoring fees', 'Pago por tutorías', 'Pagamento por aulas'],
      'savings-interest': ['Savings interest', 'Intereses del ahorro', 'Juros da poupança'],
      'stock-dividend': ['Stock dividends', 'Dividendos de acciones', 'Dividendos de ações'],
      'phone-plan': ['Phone plan', 'Plan de celular', 'Plano de celular'],
      snacks: ['Snacks and outings', 'Antojitos y salidas', 'Lanches e passeios'],
      savings: ['Savings account', 'Cuenta de ahorro', 'Conta poupança'],
      'bike-loan': ['Bike loan balance', 'Saldo del préstamo de la bici', 'Saldo do empréstimo da bike'],
    },
    payload: {
      items: [
        { id: 'weekend-job', amount: 420 }, { id: 'tutoring', amount: 180 }, { id: 'savings-interest', amount: 12 }, { id: 'stock-dividend', amount: 25 },
        { id: 'phone-plan', amount: 35 }, { id: 'snacks', amount: 90 }, { id: 'savings', amount: 650 }, { id: 'bike-loan', amount: 300 },
      ],
    },
    solutions: [{ earned: ['weekend-job', 'tutoring'], passive: ['savings-interest', 'stock-dividend'], expenses: ['phone-plan', 'snacks'], assets: ['savings'], liabilities: ['bike-loan'], goal: ['goal-short'] }],
    invalid: { earned: ['no-such-item'] },
  }),
  fixture({
    id: 'cash-flow-met', title: ['Maya\'s print shop', 'La imprenta de Maya', 'A gráfica da Maya'], band: '13-17', ages: [13, 17], type: CASH, visual: 'statement-board',
    prompt: ['Sort each item onto its line, then say if passive income beats expenses.', 'Coloca cada concepto en su línea y di si el ingreso pasivo supera los gastos.', 'Coloque cada item na sua linha e diga se a renda passiva supera as despesas.'],
    labels: {
      'print-sales': ['Print shop sales', 'Ventas de la imprenta', 'Vendas da gráfica'],
      'design-gigs': ['Logo design gigs', 'Trabajos de diseño de logos', 'Trabalhos de design de logos'],
      'stock-dividend': ['Stock dividends', 'Dividendos de acciones', 'Dividendos de ações'],
      'song-royalty': ['Song royalties', 'Regalías de una canción', 'Royalties de uma música'],
      'garage-rent': ['Garage rent from a neighbor', 'Renta de la cochera a un vecino', 'Aluguel da garagem a um vizinho'],
      'ink-paper': ['Ink and paper', 'Tinta y papel', 'Tinta e papel'],
      'bus-pass': ['Bus pass', 'Pase de autobús', 'Passe de ônibus'],
      printer: ['Printer, fully paid', 'Impresora ya pagada', 'Impressora quitada'],
      'laptop-loan': ['Laptop loan balance', 'Saldo del préstamo de la laptop', 'Saldo do empréstimo do notebook'],
    },
    payload: {
      items: [
        { id: 'print-sales', amount: 380 }, { id: 'design-gigs', amount: 200 }, { id: 'stock-dividend', amount: 110 }, { id: 'song-royalty', amount: 140 },
        { id: 'garage-rent', amount: 90 }, { id: 'ink-paper', amount: 120 }, { id: 'bus-pass', amount: 60 }, { id: 'printer', amount: 900 }, { id: 'laptop-loan', amount: 700 },
      ],
    },
    solutions: [{
      earned: ['print-sales', 'design-gigs'], passive: ['stock-dividend', 'song-royalty', 'garage-rent'], expenses: ['ink-paper', 'bus-pass'],
      assets: ['printer'], liabilities: ['laptop-loan'], goal: ['goal-met'],
    }],
    invalid: { passive: ['no-such-item'] },
  }),
  fixture({
    id: 'grid-swot-stand', title: ['Lemonade stand SWOT', 'FODA del puesto de limonada', 'Análise FOFA da barraca'], band: '13-17', ages: [13, 17], type: GRID, visual: 'swot',
    prompt: ['Place each point in strengths, weaknesses, opportunities or threats.', 'Coloca cada punto en fortalezas, debilidades, oportunidades o amenazas.', 'Coloque cada ponto em forças, fraquezas, oportunidades ou ameaças.'],
    labels: {
      'fresh-recipe': ['Fresh family recipe', 'Receta familiar fresca', 'Receita de família sempre fresca'],
      'loyal-regulars': ['Loyal regular customers', 'Clientes fieles y frecuentes', 'Clientes fiéis e frequentes'],
      'cash-only': ['Cash payments only', 'Solo se paga en efectivo', 'Só aceita dinheiro'],
      'one-seller': ['Only one person selling', 'Solo una persona vende', 'Só uma pessoa vende'],
      'school-fair': ['School fair next month', 'Feria escolar el próximo mes', 'Feira da escola no mês que vem'],
      'new-park': ['New park opens nearby', 'Abren un parque cerca', 'Novo parque abre por perto'],
      'rainy-season': ['Rainy season starts', 'Empieza la temporada de lluvias', 'Começa a época de chuvas'],
      'rival-stand': ['Rival stand across the street', 'Puesto rival al otro lado', 'Barraca rival do outro lado'],
    },
    payload: { pieces: ['fresh-recipe', 'loyal-regulars', 'cash-only', 'one-seller', 'school-fair', 'new-park', 'rainy-season', 'rival-stand'] },
    solutions: [{ strengths: ['fresh-recipe', 'loyal-regulars'], weaknesses: ['cash-only', 'one-seller'], opportunities: ['school-fair', 'new-park'], threats: ['rainy-season', 'rival-stand'] }],
    invalid: { strengths: ['no-such-piece'] },
  }),
  fixture({
    id: 'grid-eisenhower-week', title: ['Sort the week', 'Ordena la semana', 'Organize a semana'], band: '10-12', ages: [12, 12], type: GRID, visual: 'eisenhower',
    prompt: ['Sort each task by how urgent and how important it is.', 'Ordena cada tarea según qué tan urgente e importante es.', 'Organize cada tarefa por urgência e importância.'],
    labels: {
      'study-test': ['Study for tomorrow\'s test', 'Estudiar para el examen de mañana', 'Estudar para a prova de amanhã'],
      'pay-supplier': ['Pay the lemon supplier today', 'Pagar hoy al proveedor de limones', 'Pagar hoje o fornecedor de limões'],
      'plan-menu': ['Plan next season\'s menu', 'Planear el menú de la próxima temporada', 'Planejar o cardápio da próxima temporada'],
      'learn-pricing': ['Learn how to set prices', 'Aprender a fijar precios', 'Aprender a definir preços'],
      'refill-cups': ['Refill cups now, a helper can', 'Rellenar vasos ya, un ayudante puede', 'Repor copos já, um ajudante pode'],
      'hand-flyers': ['Hand out flyers today, anyone can', 'Repartir volantes hoy, cualquiera puede', 'Distribuir panfletos hoje, qualquer um pode'],
      'scroll-videos': ['Scroll random videos', 'Ver videos al azar', 'Rolar vídeos aleatórios'],
      'sort-stickers': ['Re-sort old stickers again', 'Reordenar stickers viejos otra vez', 'Reorganizar adesivos antigos de novo'],
    },
    payload: { pieces: ['study-test', 'pay-supplier', 'plan-menu', 'learn-pricing', 'refill-cups', 'hand-flyers', 'scroll-videos', 'sort-stickers'] },
    solutions: [{ 'do-now': ['study-test', 'pay-supplier'], schedule: ['plan-menu', 'learn-pricing'], delegate: ['refill-cups', 'hand-flyers'], drop: ['scroll-videos', 'sort-stickers'] }],
    invalid: { drop: ['no-such-piece'] },
  }),
  fixture({
    id: 'grid-two-by-two-ideas', title: ['Ideas by effort and impact', 'Ideas por esfuerzo e impacto', 'Ideias por esforço e impacto'], band: '13-17', ages: [13, 17], type: GRID, visual: 'two-by-two',
    prompt: ['Sort each idea into the quadrant its ratings point to.', 'Coloca cada idea en el cuadrante que indican sus calificaciones.', 'Coloque cada ideia no quadrante que as notas indicam.'],
    labels: {
      'x-name': ['Effort', 'Esfuerzo', 'Esforço'], 'y-name': ['Impact', 'Impacto', 'Impacto'],
      'x-low': ['Low effort', 'Poco esfuerzo', 'Pouco esforço'], 'x-high': ['High effort', 'Mucho esfuerzo', 'Muito esforço'],
      'y-low': ['Low impact', 'Poco impacto', 'Pouco impacto'], 'y-high': ['High impact', 'Mucho impacto', 'Muito impacto'],
      'new-sign': ['Paint a new sign', 'Pintar un letrero nuevo', 'Pintar uma placa nova'],
      'order-app': ['Build an ordering app', 'Crear una app de pedidos', 'Criar um app de pedidos'],
      'extra-napkins': ['Add extra napkins', 'Agregar más servilletas', 'Colocar mais guardanapos'],
      'second-cart': ['Buy a second cart', 'Comprar un segundo carrito', 'Comprar um segundo carrinho'],
      'discount-card': ['Print discount cards', 'Imprimir tarjetas de descuento', 'Imprimir cartões de desconto'],
      'rename-stand': ['Rename the stand', 'Cambiar el nombre del puesto', 'Mudar o nome da barraca'],
    },
    payload: {
      pieces: ['new-sign', 'order-app', 'extra-napkins', 'second-cart', 'discount-card', 'rename-stand'],
      points: [[2, 8], [9, 9], [3, 2], [8, 3], [4, 7], [7, 2]],
    },
    solutions: [{ 'top-left': ['new-sign', 'discount-card'], 'top-right': ['order-app'], 'bottom-left': ['extra-napkins'], 'bottom-right': ['second-cart', 'rename-stand'] }],
    invalid: { 'top-left': ['no-such-piece'] },
  }),
  fixture({
    id: 'grid-decision-spot', title: ['Best spot for the stand', 'El mejor lugar para el puesto', 'O melhor ponto para a barraca'], band: '13-17', ages: [13, 17], type: GRID, visual: 'decision-matrix',
    prompt: ['Rank the spots by weighted score, highest first.', 'Ordena los lugares por puntaje ponderado, del más alto al más bajo.', 'Ordene os pontos pela pontuação ponderada, do maior ao menor.'],
    labels: {
      'market-corner': ['Market corner', 'Esquina del mercado', 'Esquina do mercado'],
      'library-steps': ['Library steps', 'Escalinatas de la biblioteca', 'Escadaria da biblioteca'],
      'bus-stop': ['Bus stop', 'Parada de autobús', 'Ponto de ônibus'],
      'foot-traffic': ['Foot traffic', 'Gente que pasa', 'Movimento de pessoas'],
      'low-rent': ['Low rent', 'Renta baja', 'Aluguel baixo'],
      shade: ['Shade', 'Sombra', 'Sombra'],
    },
    payload: {
      pieces: ['market-corner', 'library-steps', 'bus-stop'],
      criteria: [{ id: 'foot-traffic', weight: 5 }, { id: 'low-rent', weight: 3 }, { id: 'shade', weight: 2 }],
      scores: [[5, 3, 1], [2, 4, 5], [4, 2, 4]],
    },
    solutions: [{ 'rank-1': ['market-corner'], 'rank-2': ['bus-stop'], 'rank-3': ['library-steps'] }],
    invalid: { 'rank-1': ['market-corner', 'bus-stop'] },
  }),
  fixture({
    id: 'grid-canvas-lemonade', title: ['Lemonade stand canvas', 'Lienzo del puesto de limonada', 'Canvas da barraca de limonada'], band: '13-17', ages: [13, 17], type: GRID, visual: 'business-canvas',
    prompt: ['Place each note in its block of the business canvas.', 'Coloca cada nota en su bloque del lienzo de negocio.', 'Coloque cada nota no seu bloco do canvas de negócio.'],
    labels: {
      'fruit-farm': ['Local fruit farm', 'Granja de fruta local', 'Fazenda de frutas local'],
      'squeeze-juice': ['Squeeze juice each morning', 'Exprimir jugo cada mañana', 'Espremer suco toda manhã'],
      'cart-cooler': ['Cart and cooler box', 'Carrito y hielera', 'Carrinho e caixa térmica'],
      'fresh-cold': ['Fresh cold juice, fast', 'Jugo fresco y frío, rápido', 'Suco fresco e gelado, rápido'],
      'stamp-card': ['Loyalty stamp card', 'Tarjeta de sellos de lealtad', 'Cartão fidelidade com carimbos'],
      'street-corner': ['Street corner', 'Esquina de la calle', 'Esquina da rua'],
      'fair-table': ['School fair table', 'Mesa en la feria escolar', 'Mesa na feira da escola'],
      'students-parents': ['Students and parents', 'Estudiantes y padres', 'Estudantes e pais'],
      'lemons-sugar': ['Lemons and sugar', 'Limones y azúcar', 'Limões e açúcar'],
      'cup-sales': ['Sales of each cup', 'Venta de cada vaso', 'Venda de cada copo'],
    },
    payload: { pieces: ['fruit-farm', 'squeeze-juice', 'cart-cooler', 'fresh-cold', 'stamp-card', 'street-corner', 'fair-table', 'students-parents', 'lemons-sugar', 'cup-sales'] },
    solutions: [{
      partners: ['fruit-farm'], activities: ['squeeze-juice'], resources: ['cart-cooler'], value: ['fresh-cold'], relationships: ['stamp-card'],
      channels: ['street-corner', 'fair-table'], segments: ['students-parents'], costs: ['lemons-sugar'], revenue: ['cup-sales'],
    }],
    invalid: { value: ['no-such-piece'] },
  }),
  fixture({
    id: 'plan-gantt-opening', title: ['Plan the opening', 'Planea la apertura', 'Planeje a abertura'], band: '13-17', ages: [13, 17], type: PLAN, visual: 'gantt',
    prompt: ['Give every task a start period. Keep the order and the deadline.', 'Dale a cada tarea un periodo de inicio. Respeta el orden y la fecha límite.', 'Dê a cada tarefa um período de início. Respeite a ordem e o prazo.'],
    labels: {
      'design-menu': ['Design the menu', 'Diseñar el menú', 'Desenhar o cardápio'],
      'print-menu': ['Print the menu', 'Imprimir el menú', 'Imprimir o cardápio'],
      'shop-lemons': ['Buy lemons', 'Comprar limones', 'Comprar limões'],
      'squeeze-juice': ['Squeeze the juice', 'Exprimir el jugo', 'Espremer o suco'],
      'open-stand': ['Open the stand', 'Abrir el puesto', 'Abrir a barraca'],
      'make-sign': ['Paint the sign', 'Pintar el letrero', 'Pintar a placa'],
    },
    payload: {
      tasks: [
        { id: 'design-menu', after: [], duration: 2 }, { id: 'print-menu', after: ['design-menu'], duration: 1 }, { id: 'shop-lemons', after: [], duration: 1 },
        { id: 'squeeze-juice', after: ['shop-lemons'], duration: 2 }, { id: 'open-stand', after: ['print-menu', 'squeeze-juice'], duration: 1 }, { id: 'make-sign', after: [], duration: 1 },
      ],
      periods: 5,
      workers: 2,
    },
    solutions: [{ 'period-1': ['design-menu', 'shop-lemons'], 'period-2': ['squeeze-juice'], 'period-3': ['print-menu'], 'period-4': ['open-stand', 'make-sign'] }],
    invalid: { 'period-9': ['design-menu'] },
  }),
  fixture({
    id: 'plan-kanban-opening', title: ['Stand opening board', 'Tablero de apertura del puesto', 'Quadro de abertura da barraca'], band: '13-17', ages: [13, 17], type: PLAN, visual: 'kanban',
    prompt: ['Move every task that can start now into Doing. Mind the limit.', 'Mueve a En curso toda tarea que ya pueda empezar. Respeta el límite.', 'Mova para Em andamento toda tarefa que já pode começar. Respeite o limite.'],
    labels: {
      'design-menu': ['Design the menu', 'Diseñar el menú', 'Desenhar o cardápio'],
      'buy-cups': ['Buy cups', 'Comprar vasos', 'Comprar copos'],
      'print-menu': ['Print the menu', 'Imprimir el menú', 'Imprimir o cardápio'],
      'buy-lemons': ['Buy lemons', 'Comprar limones', 'Comprar limões'],
      'set-tables': ['Set up the tables', 'Montar las mesas', 'Montar as mesas'],
      'open-stand': ['Open the stand', 'Abrir el puesto', 'Abrir a barraca'],
    },
    payload: {
      tasks: [
        { id: 'design-menu', after: [] }, { id: 'buy-cups', after: [] }, { id: 'print-menu', after: ['design-menu'] },
        { id: 'buy-lemons', after: [] }, { id: 'set-tables', after: ['buy-cups', 'print-menu'] }, { id: 'open-stand', after: ['buy-lemons', 'set-tables'] },
      ],
      done: ['design-menu', 'buy-cups'],
      limit: 2,
    },
    solutions: [{ doing: ['print-menu', 'buy-lemons'], todo: ['set-tables', 'open-stand'] }],
    invalid: { doing: ['print-menu', 'buy-lemons', 'set-tables'] },
  }),
  fixture({
    id: 'plan-timeline-opening', title: ['Order the opening', 'Ordena la apertura', 'Ordene a abertura'], band: '10-12', ages: [12, 12], type: PLAN, visual: 'timeline',
    prompt: ['Put the tasks in order. Meet every deadline.', 'Pon las tareas en orden. Cumple cada fecha límite.', 'Coloque as tarefas em ordem. Cumpra cada prazo.'],
    labels: {
      'buy-lemons': ['Buy lemons', 'Comprar limones', 'Comprar limões'],
      'make-juice': ['Make the juice', 'Hacer el jugo', 'Fazer o suco'],
      'set-price': ['Set the price', 'Fijar el precio', 'Definir o preço'],
      'make-sign': ['Paint the sign', 'Pintar el letrero', 'Pintar a placa'],
      'open-stand': ['Open the stand', 'Abrir el puesto', 'Abrir a barraca'],
      'count-cash': ['Count the cash', 'Contar el efectivo', 'Contar o dinheiro'],
    },
    payload: {
      tasks: [
        { id: 'buy-lemons', after: [] }, { id: 'make-juice', after: ['buy-lemons'] }, { id: 'set-price', after: [] },
        { id: 'make-sign', after: ['set-price'], due: 3 }, { id: 'open-stand', after: ['make-juice', 'make-sign'], due: 5 }, { id: 'count-cash', after: ['open-stand'] },
      ],
    },
    solutions: [{ 'step-1': ['buy-lemons'], 'step-2': ['set-price'], 'step-3': ['make-sign'], 'step-4': ['make-juice'], 'step-5': ['open-stand'], 'step-6': ['count-cash'] }],
    invalid: { 'step-9': ['buy-lemons'] },
  }),
];
