/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/fin2/placement.ts. Do not edit: change the source and regenerate. */
import { scheduleFrame } from './schedule.generated';
import type { Frame, SlotMap } from './slots.generated';

export const TRAY = 'tray';

export type Accepts = (piece: string, slot: string) => boolean;

export function locate(slots: SlotMap, piece: string): string | null {
  for (const [slot, pieces] of Object.entries(slots)) if (pieces.includes(piece)) return slot;
  return null;
}

/**
 * The placement after moving `piece` to `target` (a slot, or the tray to take it back). The same `slots` object comes back
 * when the move is not allowed: unknown piece or target, a full slot, or a slot that does not accept the piece.
 * A full one-piece slot swaps with its occupant instead of refusing.
 */
export function placePiece(frame: Frame, slots: SlotMap, piece: string, target: string, accepts: Accepts = () => true): SlotMap {
  const from = locate(slots, piece);
  if (!frame.pieceIds.includes(piece) || (from ?? TRAY) === target) return slots;
  if (target !== TRAY && (!frame.slotIds.includes(target) || !accepts(piece, target))) return slots;
  const next: Record<string, string[]> = Object.fromEntries(Object.entries(slots).map(([slot, pieces]) => [slot, [...pieces]]));
  if (from !== null) next[from] = next[from]!.filter((id) => id !== piece);
  if (target !== TRAY) {
    const there = next[target] ?? [];
    const capacity = frame.capacities[target] ?? 0;
    if (there.length < capacity) next[target] = [...there, piece];
    else if (capacity === 1 && there.length === 1) {
      const other = there[0]!;
      if (from !== null && !accepts(other, from)) return slots;
      next[target] = [piece];
      if (from !== null) next[from] = [...next[from]!, other];
    } else return slots;
  }
  return Object.fromEntries(Object.entries(next).filter(([, pieces]) => pieces.length > 0));
}

export const canPlace = (frame: Frame, slots: SlotMap, piece: string, target: string, accepts?: Accepts): boolean => placePiece(frame, slots, piece, target, accepts) !== slots;

export const unplaced = (frame: Frame, slots: SlotMap): string[] => frame.pieceIds.filter((id) => locate(slots, id) === null);

export const sameSlots = (a: SlotMap, b: SlotMap): boolean => {
  const key = (slots: SlotMap) => JSON.stringify(Object.entries(slots).filter(([, pieces]) => pieces.length > 0).map(([slot, pieces]) => [slot, [...pieces].sort()]).sort());
  return key(a) === key(b);
};

/** The response of a placement: the non-empty slots, as the arrangement shape reads them. */
export const answerOf = (slots: SlotMap): { slots: SlotMap } => ({ slots: Object.fromEntries(Object.entries(slots).filter(([, pieces]) => pieces.length > 0)) });

/** Where a board starts: a kanban begins with every movable task waiting in To do, every other board empty. */
export function startSlots(visual: unknown, payload: unknown): SlotMap {
  const frame = visual === 'kanban' ? scheduleFrame(visual, payload) : null;
  return frame ? { todo: [...frame.pieceIds] } : {};
}
