/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/fin2/scorer.ts. Do not edit: change the source and regenerate. */
import { gradeArrangement, sampleArrangement } from '../../v2AnswerShapes.generated';
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import { gridFrame, gridKeyProblem } from './matrix.generated';
import { scheduleFrame, scheduleKeyProblem, scheduleMet } from './schedule.generated';
import { exactKeys, isUntouched, toContext, type Frame, type SlotMap } from './slots.generated';
import { statementFrame, statementKeyProblem } from './statement.generated';

type Segment = { visual?: { type?: unknown }; payload?: unknown };
type Rubric = { solutions: SlotMap[] };

interface Spec {
  frame: (visual: unknown, payload: unknown) => Frame | null;
  keyProblem: (visual: unknown, payload: unknown, solutions: readonly SlotMap[]) => string | null;
  /** A rule the arrangement can meet in more than one way; absent when the key is the only answer. */
  met?: (visual: unknown, payload: unknown, slots: SlotMap) => boolean;
}

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };

/**
 * invalid: malformed, off the board, over a slot capacity or a malformed key. valid: nothing placed yet, and every
 * well-formed placement when there is no rubric, as in the browser. review: placed, not the key. met: the key, or a rule the board checks.
 */
function gradeWith(spec: Spec) {
  return (segment: Segment, response: unknown, rubric: Rubric | undefined): V2Grade => {
    const visual = segment?.visual?.type;
    const frame = spec.frame(visual, segment?.payload);
    if (!frame) return INVALID;
    const context = toContext(frame);
    if (rubric !== undefined) {
      if (!exactKeys(rubric, ['solutions']) || sampleArrangement(rubric, context) === null) return INVALID;
      if (spec.keyProblem(visual, segment.payload, rubric.solutions) !== null) return INVALID;
    }
    if (isUntouched(response, frame)) return VALID;
    if (gradeArrangement(response, undefined, context).verdict === 'invalid') return INVALID;
    if (rubric === undefined) return VALID;
    if (spec.met?.(visual, segment.payload, (response as { slots: SlotMap }).slots)) return MET;
    const shape = gradeArrangement(response, rubric, context);
    return { verdict: shape.verdict, diagnostic: shape.diagnostic };
  };
}

function sampleWith(spec: Spec) {
  return (segment: Segment, rubric: Rubric): unknown => {
    const frame = spec.frame(segment?.visual?.type, segment?.payload);
    return frame ? sampleArrangement(rubric, toContext(frame)) : null;
  };
}

const STATEMENT: Spec = {
  frame: (visual, payload) => (visual === 'statement-board' ? statementFrame(payload) : null),
  keyProblem: (_visual, payload, solutions) => statementKeyProblem(payload, solutions),
};
const GRID: Spec = { frame: gridFrame, keyProblem: gridKeyProblem };
const SCHEDULE: Spec = { frame: scheduleFrame, keyProblem: scheduleKeyProblem, met: scheduleMet };

const scorer = (spec: Spec): HorizonteScorer => ({ grade: gradeWith(spec) as HorizonteScorer['grade'], sample: sampleWith(spec) as HorizonteScorer['sample'] });

export const FIN2_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'money.cash-flow.v2': scorer(STATEMENT),
  'reasoning.decision-grid.v2': scorer(GRID),
  'plan.schedule-board.v2': scorer(SCHEDULE),
};
