-- 0073_badge_shares.sql — the shareable-achievement-badge viral loop's
-- source of truth: one row per generated badge image / share link.
-- @phase: expand
--
-- WHAT THIS ADDS AND WHY.
--
-- badge_shares   One row per composited badge image (Depot object) and its
--                public share token. Created by Core when a verified
--                guardian requests a share for their kid (backend/AGENTS.md
--                "badge issuance"), after Depot (filebase) has composited
--                and stored the image. The row is what the public landing
--                page (frontend `/badge/:token`, a Vercel function) reads
--                to render the per-share OG title/image.
--
-- PII (/AGENTS.md §1.9): this row is a WORLD-READABLE-ADJACENT surface —
-- its `token` is handed to strangers by design, so it must never carry more
-- than the same "age band + first name" ceiling §1.9 sets for third-party
-- AI context, even though this is first-party storage. No surname, no exact
-- age (age_band only, same closed vocabulary as elsewhere), no school, no
-- real photo — `image_bucket/hash/ext`/`image_url` point at a Depot object
-- composited from a template + first name, never an uploaded photo.
-- `achievement_label` is never free text: it is derived server-side from a
-- course slug or streak count, never accepted from the client as a string.
CREATE TABLE IF NOT EXISTS public.badge_shares (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    -- URL-safe opaque token, generated by Core (crypto random, base64url).
    -- Charset-constrained like every other externally-facing id in this
    -- schema (0023's segment_id precedent) — a length cap alone would still
    -- leave a free-text channel into a row a stranger's request can read.
    token              text NOT NULL UNIQUE CHECK (token ~ '^[A-Za-z0-9_-]{16,64}$'),
    kid_user_id        uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    created_by         uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    achievement_kind   text NOT NULL CHECK (achievement_kind IN ('course_badge', 'streak')),
    -- Server-derived display label (a course title or "7-day streak"), never
    -- client-supplied free text. Bounded regardless, defense in depth.
    achievement_label  text NOT NULL CHECK (char_length(achievement_label) BETWEEN 1 AND 80),
    -- First name only — no surname column exists on this table by design.
    first_name         text NOT NULL CHECK (char_length(first_name) BETWEEN 1 AND 40),
    age_band           text NULL CHECK (age_band IS NULL OR age_band IN ('6-8', '9-11', '12-14')),
    image_bucket       text NOT NULL CHECK (char_length(image_bucket) BETWEEN 1 AND 64),
    image_hash         text NOT NULL CHECK (image_hash ~ '^[a-f0-9]{64}$'),
    image_ext          text NOT NULL CHECK (image_ext IN ('png')),
    -- The exact URL Depot returned at compose time (its own PUBLIC_BASE_URL,
    -- which is NOT the same value as Core's internal FILEBASE_URL used for
    -- service-to-service calls — reconstructing a public URL from bucket/
    -- hash/ext using the wrong base would silently hand a stranger's browser
    -- an unreachable private-networking hostname). bucket/hash/ext above stay
    -- for the same audit/dedup reasons every other Depot reference keeps
    -- them; this column is what the public read route actually serves.
    image_url          text NOT NULL CHECK (char_length(image_url) BETWEEN 1 AND 2048),
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS badge_shares_kid_user_id_idx ON public.badge_shares (kid_user_id);

ALTER TABLE public.badge_shares ENABLE ROW LEVEL SECURITY;

-- The kid (if ever browser-authenticated) or a verified guardian may read
-- their own share history. The public landing page never reads this table
-- directly with the browser's own credentials — it goes through Core's
-- service-role read (§1.5: internal services are service-to-service only;
-- the browser talks only to Core), so no anonymous SELECT policy exists.
DROP POLICY IF EXISTS badge_shares_select_own ON public.badge_shares;
CREATE POLICY badge_shares_select_own ON public.badge_shares
    FOR SELECT USING (
        kid_user_id = auth.uid()
        OR created_by = auth.uid()
        OR public.is_verified_guardian_of(kid_user_id)
    );
-- No INSERT/UPDATE/DELETE policies: only the service role writes, and rows
-- are immutable once created (a re-share issues a new token/row rather than
-- mutating an existing one, so an old shared link's preview never changes
-- out from under whoever already has it open).
