/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/alg2/fixtures.ts. Do not edit: change the source and regenerate. */
import type { HorizonteFixture, HorizonteLocale } from '../types.generated';

const text = (en: string, es: string, pt: string): Record<HorizonteLocale, string> => ({ 'en-US': en, 'es-MX': es, 'pt-BR': pt });

const slider = (min: string, max: string, step: string) => ({ min, max, step });

export const ALG2_FIXTURES: readonly HorizonteFixture[] = [
  {
    id: 'graph-line-two-dots',
    title: text('Fit the line', 'Ajusta la recta', 'Ajuste a reta'),
    ageBand: '10-12',
    eligibility: { minimum_age: 12, maximum_age: 12 },
    segment: (locale) => ({
      id: 'graph-line-two-dots', type: 'math.function-graph.v2', grading: 'server', visual: { type: 'function-graph' },
      prompt: text('Slide m and b until the line goes through both dots.', 'Desliza m y b hasta que la recta pase por ambos puntos.', 'Deslize m e b até que a reta passe pelos dois pontos.')[locale],
      payload: {
        curve: 'line', start: { m: '1', b: '0' }, sliders: { m: slider('-5', '5', '1'), b: slider('-6', '6', '1') },
        window: { xMin: -6, xMax: 6, yMin: -8, yMax: 8 }, marks: [{ x: 0, y: -3 }, { x: 2, y: 1 }],
      },
    }),
    rubric: { family: 'line', target: { m: '2', b: '-3' } },
    ladder: {
      invalid: { family: 'line', params: { m: '2.5', b: '-3' } },
      valid: { family: 'line', params: { m: '1', b: '0' } },
      met: { family: 'line', params: { m: '2', b: '-3' } },
    },
  },
  {
    id: 'graph-parabola-vertex',
    title: text('Shape the parabola', 'Da forma a la parábola', 'Dê forma à parábola'),
    ageBand: '13-17',
    eligibility: { minimum_age: 14, maximum_age: 17 },
    segment: (locale) => ({
      id: 'graph-parabola-vertex', type: 'math.function-graph.v2', grading: 'server', visual: { type: 'function-graph' },
      prompt: text('Set the vertex and the opening so the curve goes through the three dots.', 'Fija el vértice y la apertura para que la curva pase por los tres puntos.', 'Defina o vértice e a abertura para que a curva passe pelos três pontos.')[locale],
      payload: {
        curve: 'quadratic', form: 'vertex', start: { a: '1', h: '0', k: '0' },
        sliders: { a: slider('1', '4', '1'), h: slider('-3', '4', '1'), k: slider('-6', '6', '1') },
        window: { xMin: -4, xMax: 6, yMin: -5, yMax: 10 }, marks: [{ x: 1, y: -3 }, { x: 3, y: 5 }, { x: -1, y: 5 }],
      },
    }),
    rubric: { family: 'quadratic', target: { a: '2', b: '-4', c: '-1' } },
    ladder: {
      invalid: { family: 'quadratic', params: { a: '2', b: '-4', c: '-0.5' } },
      valid: { family: 'quadratic', params: { a: '1', b: '0', c: '0' } },
      met: { family: 'quadratic', params: { a: '2', b: '-4', c: '-1' } },
    },
  },
  {
    id: 'graph-parabola-standard',
    title: text('Match the parabola', 'Iguala la parábola', 'Iguale a parábola'),
    ageBand: '13-17',
    eligibility: { minimum_age: 13, maximum_age: 17 },
    segment: (locale) => ({
      id: 'graph-parabola-standard', type: 'math.function-graph.v2', grading: 'server', visual: { type: 'function-graph' },
      prompt: text('Match the three dots with a, b and c.', 'Ajusta a, b y c a los tres puntos.', 'Ajuste a, b e c aos três pontos.')[locale],
      payload: {
        curve: 'quadratic', start: { a: '2', b: '0', c: '0' },
        sliders: { a: slider('-2', '2', '1'), b: slider('-6', '6', '1'), c: slider('-6', '6', '1') },
        window: { xMin: -4, xMax: 6, yMin: -6, yMax: 6 }, marks: [{ x: -1, y: 0 }, { x: 3, y: 0 }, { x: 0, y: -3 }],
      },
    }),
    rubric: { family: 'quadratic', target: { a: '1', b: '-2', c: '-3' } },
    ladder: {
      invalid: { family: 'quadratic', params: { a: '1', b: '-2.5', c: '-3' } },
      valid: { family: 'quadratic', params: { a: '2', b: '0', c: '0' } },
      met: { family: 'quadratic', params: { a: '1', b: '-2', c: '-3' } },
    },
  },
  {
    id: 'graph-growth-curve',
    title: text('Fit the growth', 'Ajusta el crecimiento', 'Ajuste o crescimento'),
    ageBand: '13-17',
    eligibility: { minimum_age: 14, maximum_age: 17 },
    segment: (locale) => ({
      id: 'graph-growth-curve', type: 'math.function-graph.v2', grading: 'server', visual: { type: 'function-graph' },
      prompt: text('Slide a and the base until the curve goes through both dots.', 'Desliza a y la base hasta que la curva pase por ambos puntos.', 'Deslize a e a base até que a curva passe pelos dois pontos.')[locale],
      payload: {
        curve: 'exponential', start: { a: '2', b: '1.5' }, sliders: { a: slider('1', '4', '1'), b: slider('0.5', '3', '0.5') },
        window: { xMin: -3, xMax: 5, yMin: -2, yMax: 20 }, marks: [{ x: 0, y: 1 }, { x: 3, y: 8 }],
      },
    }),
    rubric: { family: 'exponential', target: { a: '1', b: '2' } },
    ladder: {
      invalid: { family: 'exponential', params: { a: '1', b: '0' } },
      valid: { family: 'exponential', params: { a: '2', b: '1.5' } },
      met: { family: 'exponential', params: { a: '1', b: '2' } },
    },
  },
  {
    id: 'system-cross-two-lines',
    title: text('Find the crossing', 'Encuentra el cruce', 'Encontre o cruzamento'),
    ageBand: '13-17',
    eligibility: { minimum_age: 13, maximum_age: 17 },
    segment: (locale) => ({
      id: 'system-cross-two-lines', type: 'math.line-system.v2', grading: 'server', visual: { type: 'line-system' },
      prompt: text('Move the marker to the point where the two lines cross.', 'Mueve la marca al punto donde se cruzan las dos rectas.', 'Mova a marca até o ponto onde as duas retas se cruzam.')[locale],
      payload: {
        lines: [{ a: 1, b: 1, c: 5 }, { a: 1, b: -1, c: 1 }], window: { xMin: -2, xMax: 8, yMin: -2, yMax: 8 }, grid: 1, start: [{ x: 0, y: 0 }],
      },
    }),
    rubric: { required: [{ x: 3, y: 2 }] },
    ladder: {
      invalid: { points: [{ x: 3.5, y: 2 }] },
      valid: { points: [{ x: 0, y: 0 }] },
      met: { points: [{ x: 3, y: 2 }] },
    },
  },
  {
    id: 'system-half-grid',
    title: text('Cross on a half step', 'Cruce en medio paso', 'Cruzamento em meio passo'),
    ageBand: '13-17',
    eligibility: { minimum_age: 14, maximum_age: 17 },
    segment: (locale) => ({
      id: 'system-half-grid', type: 'math.line-system.v2', grading: 'server', visual: { type: 'line-system' },
      prompt: text('The lines cross between whole numbers. Move the marker onto the crossing.', 'Las rectas se cruzan entre números enteros. Mueve la marca al cruce.', 'As retas se cruzam entre números inteiros. Mova a marca até o cruzamento.')[locale],
      payload: {
        lines: [{ a: 1, b: 1, c: 2 }, { a: 1, b: -1, c: 1 }], window: { xMin: -2, xMax: 5, yMin: -2, yMax: 5 }, grid: 0.5, start: [{ x: 0, y: 0 }],
      },
    }),
    rubric: { required: [{ x: 1.5, y: 0.5 }] },
    ladder: {
      invalid: { points: [{ x: 1.25, y: 0.5 }] },
      valid: { points: [{ x: 0, y: 0 }] },
      met: { points: [{ x: 1.5, y: 0.5 }] },
    },
  },
  {
    id: 'system-triangle',
    title: text('Mark the corners', 'Marca las esquinas', 'Marque os cantos'),
    ageBand: '13-17',
    eligibility: { minimum_age: 14, maximum_age: 17 },
    segment: (locale) => ({
      id: 'system-triangle', type: 'math.line-system.v2', grading: 'server', visual: { type: 'line-system' },
      prompt: text('Three lines make a triangle. Move a marker onto each corner.', 'Tres rectas forman un triángulo. Mueve una marca a cada esquina.', 'Três retas formam um triângulo. Mova uma marca até cada canto.')[locale],
      payload: {
        lines: [{ a: 1, b: 1, c: 6 }, { a: 1, b: -1, c: 0 }, { a: 0, b: 1, c: 1 }], window: { xMin: -1, xMax: 7, yMin: -1, yMax: 7 }, grid: 1,
        start: [{ x: 1, y: 0 }, { x: 0, y: 0 }, { x: 2, y: 0 }],
      },
    }),
    rubric: { required: [{ x: 3, y: 3 }, { x: 5, y: 1 }, { x: 1, y: 1 }] },
    ladder: {
      invalid: { points: [{ x: 1, y: 1 }, { x: 3, y: 3 }] },
      valid: { points: [{ x: 1, y: 0 }, { x: 0, y: 0 }, { x: 2, y: 0 }] },
      met: { points: [{ x: 3, y: 3 }, { x: 5, y: 1 }, { x: 1, y: 1 }] },
    },
  },
  {
    id: 'expression-expand-product',
    title: text('Expand a product', 'Expande un producto', 'Expanda um produto'),
    ageBand: '13-17',
    eligibility: { minimum_age: 13, maximum_age: 17 },
    segment: (locale) => ({
      id: 'expression-expand-product', type: 'math.expression-editor.v2', grading: 'server', visual: { type: 'expression-editor' },
      prompt: text('Expand the product. Write each step on its own line.', 'Expande el producto. Escribe cada paso en su propia línea.', 'Expanda o produto. Escreva cada passo em sua própria linha.')[locale],
      payload: { task: 'rewrite', given: '(x+2)(x+3)', form: 'expanded', variable: 'x' },
    }),
    rubric: { reference: 'x^2+5x+6' },
    ladder: {
      invalid: { steps: ['(x+2)(x+3'] },
      valid: { steps: ['(x+2)(x+3)'] },
      met: { steps: ['(x+2)(x+3)', 'x(x+3)+2(x+3)', 'x^2+5x+6'] },
    },
  },
  {
    id: 'expression-factor-trinomial',
    title: text('Factor a trinomial', 'Factoriza un trinomio', 'Fatore um trinômio'),
    ageBand: '13-17',
    eligibility: { minimum_age: 14, maximum_age: 17 },
    segment: (locale) => ({
      id: 'expression-factor-trinomial', type: 'math.expression-editor.v2', grading: 'server', visual: { type: 'expression-editor' },
      prompt: text('Factor the expression. Write each step on its own line.', 'Factoriza la expresión. Escribe cada paso en su propia línea.', 'Fatore a expressão. Escreva cada passo em sua própria linha.')[locale],
      payload: { task: 'rewrite', given: 'x^2+7x+12', form: 'factored', variable: 'x' },
    }),
    rubric: { reference: '(x+3)(x+4)' },
    ladder: {
      invalid: { steps: ['x^2+7x+12', '(x+3)(x+4'] },
      valid: { steps: ['x^2+7x+12'] },
      met: { steps: ['x^2+7x+12', '(x+3)(x+4)'] },
    },
  },
  {
    id: 'expression-solve-isolate',
    title: text('Solve for x', 'Despeja x', 'Isole x'),
    ageBand: '13-17',
    eligibility: { minimum_age: 13, maximum_age: 17 },
    segment: (locale) => ({
      id: 'expression-solve-isolate', type: 'math.expression-editor.v2', grading: 'server', visual: { type: 'expression-editor' },
      prompt: text('Solve for x. Write each step on its own line.', 'Despeja x. Escribe cada paso en su propia línea.', 'Isole x. Escreva cada passo em sua própria linha.')[locale],
      payload: { task: 'solve', given: '3x+5=20', form: 'isolated', variable: 'x' },
    }),
    rubric: { reference: 'x=5' },
    ladder: {
      invalid: { steps: ['3x+5=20', '3x=15='] },
      valid: { steps: ['3x+5=20'] },
      met: { steps: ['3x+5=20', '3x=15', 'x=5'] },
    },
  },
  {
    id: 'expression-solve-separate',
    title: text('Gather the x terms', 'Junta los términos con x', 'Reúna os termos com x'),
    ageBand: '13-17',
    eligibility: { minimum_age: 14, maximum_age: 17 },
    segment: (locale) => ({
      id: 'expression-solve-separate', type: 'math.expression-editor.v2', grading: 'server', visual: { type: 'expression-editor' },
      prompt: text('Gather the x terms on one side. Write each step on its own line.', 'Junta los términos con x en un lado. Escribe cada paso en su propia línea.', 'Reúna os termos com x de um lado. Escreva cada passo em sua própria linha.')[locale],
      payload: { task: 'solve', given: '5x-4=2x+8', form: 'separated', variable: 'x' },
    }),
    rubric: { reference: '3x=12' },
    ladder: {
      invalid: { steps: ['5x-4=2x+8', '3x=12='] },
      valid: { steps: ['5x-4=2x+8'] },
      met: { steps: ['5x-4=2x+8', '5x=2x+12', '3x=12'] },
    },
  },
];
