/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/alg2/scorer.ts. Do not edit: change the source and regenerate. */
import { gradeCurveParameters, gradePointSet } from '../../v2AnswerShapes.generated';
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import { analyseLines, expressionReferenceProblem, expressionTaskProblem, isExpressionTask, parseExpression, sameParsed, satisfiesForm, type ExpressionTask } from './expression.generated';
import {
  graphContext, isCrossing, onSliders, passesThrough, readGraphPayload, readStandard, readSystemPayload, sameSpots, sameStandard, startResponse, toStandard,
  type PlanePoint, type ReadSystem,
} from './model.generated';

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
/** Exactly these keys, as own properties: nothing missing, nothing extra. */
const hasOnly = (value: unknown, keys: readonly string[]): value is Record<string, unknown> =>
  isRecord(value) && Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));

type Segment = { payload?: unknown };

/** What the answer shape reports for a touched response: met, or review with its closed diagnostic. */
const fromShape = (grade: { verdict: string; diagnostic: V2Grade['diagnostic'] }): V2Grade =>
  grade.verdict === 'met' ? MET : grade.verdict === 'review' ? { verdict: 'review', diagnostic: grade.diagnostic } : INVALID;

/**
 * F2.4. invalid: malformed, a family other than the payload's, parameters off the sliders, or (with a rubric) a key that
 * is malformed, off the sliders, off the marks or already met by the start. valid: the sliders untouched, and every
 * well-formed response without a rubric. review: moved, but not on the key, with the diagnostic of `curve.parameters`.
 * met: the key, within its tolerance.
 */
function gradeFunctionGraph(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const graph = readGraphPayload(segment?.payload);
  if (typeof graph === 'string') return INVALID;
  if (!hasOnly(response, ['family', 'params']) || response.family !== graph.curve) return INVALID;
  const standard = readStandard(graph.curve, response.params);
  if (!standard || !onSliders(graph, standard)) return INVALID;
  if (rubric === undefined) return VALID;
  const start = startResponse(graph);
  const startStandard = toStandard(graph, graph.start);
  if (!start || !startStandard) return INVALID;
  const context = graphContext(graph);
  const opening = gradeCurveParameters(start, rubric, context);
  if (opening.verdict === 'invalid' || opening.verdict === 'met') return INVALID;
  const key = rubric as { family?: unknown; target?: unknown };
  const target = key.family === graph.curve ? readStandard(graph.curve, key.target) : null;
  if (!target || !onSliders(graph, target) || !passesThrough(graph.curve, target, graph.marks)) return INVALID;
  if (sameStandard(standard, startStandard)) return VALID;
  return fromShape(gradeCurveParameters(response, rubric, context));
}

const sampleFunctionGraph = (segment: Segment): unknown => {
  const graph = readGraphPayload(segment?.payload);
  return typeof graph === 'string' ? null : startResponse(graph);
};

function systemContext(system: ReadSystem) {
  const { xMin, xMax, yMin, yMax } = system.window;
  return { minimumX: xMin, maximumX: xMax, minimumY: yMin, maximumY: yMax, step: system.grid, maxPoints: system.start.length };
}

/**
 * F2.5. invalid: malformed, a different number of markers than the payload starts with, a marker off the window or the
 * grid, two markers on one spot, or (with a rubric) a key that is not exactly one crossing per marker or is already met
 * by the start. valid: the markers untouched. review: moved, but not on the key, with the diagnostic of `points.set`.
 * met: every marker on a required crossing.
 */
function gradeLineSystem(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const system = readSystemPayload(segment?.payload);
  if (typeof system === 'string') return INVALID;
  const context = systemContext(system);
  if (!hasOnly(response, ['points']) || gradePointSet(response, undefined, context).verdict === 'invalid') return INVALID;
  const points = response.points as PlanePoint[];
  if (points.length !== system.start.length) return INVALID;
  if (rubric === undefined) return VALID;
  if (!hasOnly(rubric, ['required'])) return INVALID;
  const opening = gradePointSet({ points: system.start }, rubric, context);
  if (opening.verdict === 'invalid' || opening.verdict === 'met') return INVALID;
  const required = rubric.required as PlanePoint[];
  if (required.length !== system.start.length || !required.every((point) => isCrossing(system.lines, point))) return INVALID;
  if (sameSpots(points, system.start)) return VALID;
  return fromShape(gradePointSet(response, rubric, context));
}

const sampleLineSystem = (segment: Segment): unknown => {
  const system = readSystemPayload(segment?.payload);
  return typeof system === 'string' ? null : { points: system.start.map((point) => ({ x: point.x, y: point.y })) };
};

/**
 * F2.6. invalid: malformed, a line that does not read (or reads as the wrong kind), or (with a rubric) a reference that
 * is not the finished form of the given. valid: the given, untouched, and every readable response without a rubric.
 * review: value when a line does not equal the one above it (or structure when the last line is right all the same),
 * partial when every line follows but the last is not the finished form. met: every line follows and the last line is
 * the reference in the finished form.
 */
function gradeExpressionEditor(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!hasOnly(payload, ['task', 'given', 'form', 'variable']) || !isExpressionTask(payload) || expressionTaskProblem(payload)) return INVALID;
  const task: ExpressionTask = payload;
  if (!hasOnly(response, ['steps']) || !Array.isArray(response.steps) || !response.steps.every((step) => typeof step === 'string')) return INVALID;
  const steps: string[] = response.steps;
  const analysis = analyseLines(task, steps);
  if (!analysis || !analysis.wellFormed) return INVALID;
  if (rubric === undefined) return VALID;
  if (!hasOnly(rubric, ['reference']) || expressionReferenceProblem(task, rubric.reference)) return INVALID;
  if (steps.length === 1 && steps[0] === task.given) return VALID;
  const last = analysis.parsed[analysis.parsed.length - 1]!;
  const finished = satisfiesForm(last, task.form) && sameParsed(parseExpression(rubric.reference, task.variable), last) === true;
  if (analysis.chainSound) return finished ? MET : { verdict: 'review', diagnostic: 'partial' };
  return { verdict: 'review', diagnostic: finished ? 'structure' : 'value' };
}

const sampleExpressionEditor = (segment: Segment): unknown => {
  const given = (segment?.payload as { given?: unknown } | undefined)?.given;
  return { steps: [typeof given === 'string' ? given : ''] };
};

const scorer = <S>(grade: (segment: S, response: unknown, rubric: unknown) => V2Grade, sample: (segment: S) => unknown): HorizonteScorer => ({
  grade: grade as unknown as HorizonteScorer['grade'],
  sample: sample as unknown as HorizonteScorer['sample'],
});

export const ALG2_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'math.function-graph.v2': scorer(gradeFunctionGraph, sampleFunctionGraph),
  'math.line-system.v2': scorer(gradeLineSystem, sampleLineSystem),
  'math.expression-editor.v2': scorer(gradeExpressionEditor, sampleExpressionEditor),
};
