// Usage ledger — one JSONL line per provider call, appended to
// runs/<run-id>/ledger.jsonl, plus an in-memory running total the kill
// switches (FORGE_MAX_TOKENS_PER_RUN / FORGE_MAX_USD_PER_RUN) check before
// every call (COURSE_ENGINE.md §4 "Budget").

import { appendFile, mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { getConfig } from '../env.js';

export type UsageProvider = 'deepseek' | 'qwen' | 'picturegen';

export interface UsageRecord {
  provider: UsageProvider;
  model: string;
  operation: string;
  promptTokens: number;
  completionTokens: number;
  /**
   * The SUBSET of promptTokens served by the provider's automatic context
   * cache (billed ~10-20x cheaper). NEVER add this to a token total —
   * it is contained within promptTokens; it only changes the PRICE.
   */
  cachedPromptTokens?: number;
  /**
   * Images ACTUALLY generated by this call (Prism cache hits are free and must be
   * reported as 0). Priced separately from tokens because image providers bill per
   * image, and because image spend was previously invisible to every budget guard.
   */
  images?: number;
}

/** Small cost table, USD, env-overridable (env.ts COST_* vars, defaults verified against official price pages 2026-07-25). */
export function estimateCostUsd(
  record: Pick<UsageRecord, 'provider' | 'promptTokens' | 'completionTokens' | 'cachedPromptTokens' | 'images'>,
): number {
  const c = getConfig();
  const imageCost = (record.images ?? 0) * c.COST_QWEN_IMAGE_PER_IMAGE;
  // Cached tokens are a subset of promptTokens: subtract before applying the
  // full input rate (pricing prompt*INPUT + cached*CACHED would double-charge).
  const cached = Math.min(record.cachedPromptTokens ?? 0, record.promptTokens);
  const freshPrompt = record.promptTokens - cached;
  switch (record.provider) {
    case 'deepseek':
      return (freshPrompt / 1000) * c.COST_DEEPSEEK_INPUT_PER_1K +
        (cached / 1000) * c.COST_DEEPSEEK_INPUT_CACHED_PER_1K +
        (record.completionTokens / 1000) * c.COST_DEEPSEEK_OUTPUT_PER_1K;
    case 'qwen':
      return (freshPrompt / 1000) * c.COST_QWEN_INPUT_PER_1K +
        (cached / 1000) * c.COST_QWEN_INPUT_CACHED_PER_1K +
        (record.completionTokens / 1000) * c.COST_QWEN_OUTPUT_PER_1K;
    case 'picturegen':
      // Prism bills per generated image; its judge/verifier tokens are accounted
      // inside Prism itself, so only the image count is priced here.
      return imageCost;
  }
}

export class BudgetExceededError extends Error {
  constructor(kind: 'tokens' | 'usd', used: number, limit: number) {
    super(`Forge run budget exceeded (${kind}): used ${used}, limit ${limit}`);
    this.name = 'BudgetExceededError';
  }
}

export class UsageLedger {
  private totalTokens = 0;
  private totalUsd = 0;
  private totalImages = 0;
  /** Reporting-only counter (subset of totalTokens) — NEVER feeds checkBudget. */
  private totalCachedTokens = 0;
  private readonly filePath: string;
  /**
   * Effective per-RUN caps. Defaults come from config, but `hydrate()` accepts
   * work-scaled limits from run.ts so a 1000-slot course is not held to the same
   * absolute ceiling as a 3-slot smoke test (see run.ts#effectiveBudget).
   */
  private maxTokens: number | null = null;
  private maxUsd: number | null = null;

  constructor(runDir: string) {
    this.filePath = path.join(runDir, 'ledger.jsonl');
  }

  /**
   * Restores the running totals from `ledger.jsonl` and installs the run's caps.
   *
   * WHY: the totals used to start at ZERO in every process, so the "per-run"
   * kill switches were really per-INVOCATION. A 1000-lesson course cannot be
   * generated in one process (the token cap alone forces a dozen-plus resumes),
   * which meant the $/token ceilings bounded nothing at all across the run that
   * actually mattered — a mass-generation audit found this reported from seven
   * different angles. The append-only ledger file was already the durable record;
   * it simply was never read back. Replaying it makes the cap mean what it says.
   *
   * Tolerant by design: a truncated final line (killed mid-append) is skipped
   * rather than fatal — losing one record's accounting is far better than
   * refusing to resume a multi-day run.
   */
  async hydrate(limits?: { maxTokens?: number; maxUsd?: number }): Promise<void> {
    this.maxTokens = limits?.maxTokens ?? null;
    this.maxUsd = limits?.maxUsd ?? null;
    let raw: string;
    try {
      raw = await readFile(this.filePath, 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return;
      throw err;
    }
    let tokens = 0;
    let usd = 0;
    let images = 0;
    let cachedTokens = 0;
    let skipped = 0;
    for (const line of raw.split('\n')) {
      if (line.trim().length === 0) continue;
      try {
        const rec = JSON.parse(line) as {
          prompt_tokens?: number;
          completion_tokens?: number;
          cached_prompt_tokens?: number;
          est_usd?: number;
          images?: number;
        };
        // cached_prompt_tokens is a SUBSET of prompt_tokens — replayed into its
        // own reporting counter, never into the token total (it would inflate
        // the kill switch). USD replays the PERSISTED est_usd verbatim, so
        // mixed-rate ledgers (lines written before/after a price change)
        // hydrate correctly.
        tokens += (rec.prompt_tokens ?? 0) + (rec.completion_tokens ?? 0);
        usd += rec.est_usd ?? 0;
        images += rec.images ?? 0;
        cachedTokens += rec.cached_prompt_tokens ?? 0;
      } catch {
        skipped += 1;
      }
    }
    this.totalTokens = tokens;
    this.totalUsd = usd;
    this.totalImages = images;
    this.totalCachedTokens = cachedTokens;
    if (tokens > 0) {
      console.log(
        `[forge] ledger resumed: ${tokens.toLocaleString()} tokens, $${usd.toFixed(4)} already spent on this run` +
          (skipped > 0 ? ` (${skipped} unparseable line(s) skipped)` : ''),
      );
    }
  }

  get tokens(): number {
    return this.totalTokens;
  }

  get usd(): number {
    return this.totalUsd;
  }

  /** Images actually generated (cache hits excluded) — reported in the run summary. */
  get images(): number {
    return this.totalImages;
  }

  /** Prompt tokens served by provider context caches (subset of `tokens`) — reporting only. */
  get cachedTokens(): number {
    return this.totalCachedTokens;
  }

  /** Throws BudgetExceededError if the run is already over budget — call BEFORE every provider call. */
  checkBudget(): void {
    const c = getConfig();
    const maxTokens = this.maxTokens ?? c.FORGE_MAX_TOKENS_PER_RUN;
    const maxUsd = this.maxUsd ?? c.FORGE_MAX_USD_PER_RUN;
    if (this.totalTokens >= maxTokens) {
      throw new BudgetExceededError('tokens', this.totalTokens, maxTokens);
    }
    if (this.totalUsd >= maxUsd) {
      throw new BudgetExceededError('usd', this.totalUsd, maxUsd);
    }
  }

  async record(record: UsageRecord): Promise<void> {
    const estUsd = estimateCostUsd(record);
    this.totalTokens += record.promptTokens + record.completionTokens;
    this.totalUsd += estUsd;
    this.totalImages += record.images ?? 0;
    this.totalCachedTokens += Math.min(record.cachedPromptTokens ?? 0, record.promptTokens);

    await mkdir(path.dirname(this.filePath), { recursive: true });
    const line =
      JSON.stringify({
        ts: new Date().toISOString(),
        provider: record.provider,
        model: record.model,
        operation: record.operation,
        prompt_tokens: record.promptTokens,
        completion_tokens: record.completionTokens,
        cached_prompt_tokens: Math.min(record.cachedPromptTokens ?? 0, record.promptTokens),
        images: record.images ?? 0,
        est_usd: Number(estUsd.toFixed(6)),
      }) + '\n';
    await appendFile(this.filePath, line, 'utf8');
  }
}
