import type { HorizonteCopy } from '../boardTypes';

export const ALG1_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  undo: { role: 'action', 'en-US': 'Undo', 'es-MX': 'Deshacer', 'pt-BR': 'Desfazer' },
  empty: { role: 'data', 'en-US': 'empty', 'es-MX': 'vacío', 'pt-BR': 'vazio' },

  sqPos: { role: 'option', band: '10-12', 'en-US': 'Positive x squared tile', 'es-MX': 'Ficha x cuadrada positiva', 'pt-BR': 'Peça x ao quadrado positiva' },
  sqNeg: { role: 'option', band: '10-12', 'en-US': 'Negative x squared tile', 'es-MX': 'Ficha x cuadrada negativa', 'pt-BR': 'Peça x ao quadrado negativa' },
  barPos: { role: 'option', band: '10-12', 'en-US': 'Positive x tile', 'es-MX': 'Ficha x positiva', 'pt-BR': 'Peça x positiva' },
  barNeg: { role: 'option', band: '10-12', 'en-US': 'Negative x tile', 'es-MX': 'Ficha x negativa', 'pt-BR': 'Peça x negativa' },
  unitPos: { role: 'option', band: '10-12', 'en-US': 'Positive 1 tile', 'es-MX': 'Ficha 1 positiva', 'pt-BR': 'Peça 1 positiva' },
  unitNeg: { role: 'option', band: '10-12', 'en-US': 'Negative 1 tile', 'es-MX': 'Ficha 1 negativa', 'pt-BR': 'Peça 1 negativa' },
  pairSq: { role: 'option', band: '10-12', 'en-US': 'Pairs of x squared', 'es-MX': 'Pares de x cuadrada', 'pt-BR': 'Pares de x ao quadrado' },
  pairBar: { role: 'option', band: '10-12', 'en-US': 'Pairs of x', 'es-MX': 'Pares de x', 'pt-BR': 'Pares de x' },
  pairUnit: { role: 'option', band: '10-12', 'en-US': 'Pairs of 1', 'es-MX': 'Pares de 1', 'pt-BR': 'Pares de 1' },
  zoneMat: { role: 'heading', band: '10-12', 'en-US': 'The mat', 'es-MX': 'El tablero', 'pt-BR': 'O tabuleiro' },
  zoneZero: { role: 'heading', band: '10-12', 'en-US': 'Zero pairs', 'es-MX': 'Pares cero', 'pt-BR': 'Pares zero' },
  tilesTray: { role: 'heading', band: '10-12', 'en-US': 'Tiles', 'es-MX': 'Fichas', 'pt-BR': 'Peças' },
  onMat: { role: 'data', 'en-US': 'On the mat', 'es-MX': 'En el tablero', 'pt-BR': 'No tabuleiro' },
  zeroSet: { role: 'data', 'en-US': 'Zero pairs', 'es-MX': 'Pares cero', 'pt-BR': 'Pares zero' },
  noPair: { role: 'body', band: '10-12', 'en-US': 'That tile has no opposite here.', 'es-MX': 'Esa ficha no tiene opuesta aquí.', 'pt-BR': 'Essa peça não tem oposta aqui.' },
  tilesCaption: { role: 'heading', band: '10-12', 'en-US': 'Tiles by kind', 'es-MX': 'Fichas por tipo', 'pt-BR': 'Peças por tipo' },
  colTile: { role: 'data', 'en-US': 'Tile', 'es-MX': 'Ficha', 'pt-BR': 'Peça' },
  colMat: { role: 'data', 'en-US': 'On the mat', 'es-MX': 'En el tablero', 'pt-BR': 'No tabuleiro' },
  colZero: { role: 'data', 'en-US': 'In zero pairs', 'es-MX': 'En pares cero', 'pt-BR': 'Em pares zero' },
  metTiles: { role: 'body', band: '10-12', 'en-US': 'You set every zero pair aside.', 'es-MX': 'Apartaste todos los pares cero.', 'pt-BR': 'Você separou todos os pares zero.' },
  hintTiles: { role: 'body', band: '10-12', 'en-US': 'Not yet. Match each tile with its opposite.', 'es-MX': 'Aún no. Junta cada ficha con su opuesta.', 'pt-BR': 'Ainda não. Junte cada peça com a oposta.' },

  boxName: { role: 'option', band: '10-12', 'en-US': 'Unknown box', 'es-MX': 'Caja desconocida', 'pt-BR': 'Caixa desconhecida' },
  boxDebt: { role: 'option', band: '10-12', 'en-US': 'Box debt', 'es-MX': 'Deuda de caja', 'pt-BR': 'Dívida de caixa' },
  coins: { role: 'option', band: '10-12', 'en-US': 'Coins: {n}', 'es-MX': 'Monedas: {n}', 'pt-BR': 'Moedas: {n}' },
  debt: { role: 'option', band: '10-12', 'en-US': 'Debt: {n}', 'es-MX': 'Deuda: {n}', 'pt-BR': 'Dívida: {n}' },
  leftSide: { role: 'heading', band: '10-12', 'en-US': 'Left side', 'es-MX': 'Lado izquierdo', 'pt-BR': 'Lado esquerdo' },
  rightSide: { role: 'heading', band: '10-12', 'en-US': 'Right side', 'es-MX': 'Lado derecho', 'pt-BR': 'Lado direito' },
  binName: { role: 'heading', band: '10-12', 'en-US': 'Cancelled', 'es-MX': 'Anuladas', 'pt-BR': 'Anuladas' },
  supplyName: { role: 'heading', band: '10-12', 'en-US': 'Add to both sides', 'es-MX': 'Suma a los dos lados', 'pt-BR': 'Some nos dois lados' },
  addBoth: { role: 'option', band: '10-12', 'en-US': 'Both sides', 'es-MX': 'Los dos lados', 'pt-BR': 'Os dois lados' },
  cancelWith: { role: 'option', band: '10-12', 'en-US': 'Cancel with {n}', 'es-MX': 'Anula con {n}', 'pt-BR': 'Anule com {n}' },
  cardsCaption: { role: 'heading', band: '10-12', 'en-US': 'Cards on each side', 'es-MX': 'Cartas en cada lado', 'pt-BR': 'Cartas em cada lado' },
  colSide: { role: 'data', 'en-US': 'Side', 'es-MX': 'Lado', 'pt-BR': 'Lado' },
  colCards: { role: 'data', 'en-US': 'Cards', 'es-MX': 'Cartas', 'pt-BR': 'Cartas' },
  metCards: { role: 'body', band: '10-12', 'en-US': 'You isolated the unknown.', 'es-MX': 'Aislaste la incógnita.', 'pt-BR': 'Você isolou a incógnita.' },
  hintCards: { role: 'body', band: '10-12', 'en-US': 'Not yet. Get the unknown alone on one side.', 'es-MX': 'Aún no. Deja la incógnita sola en un lado.', 'pt-BR': 'Ainda não. Deixe a incógnita sozinha em um lado.' },

  piecesTray: { role: 'heading', band: '10-12', 'en-US': 'Pieces', 'es-MX': 'Piezas', 'pt-BR': 'Peças' },
  row: { role: 'option', band: '10-12', 'en-US': 'Row {n}', 'es-MX': 'Fila {n}', 'pt-BR': 'Linha {n}' },
  column: { role: 'option', band: '10-12', 'en-US': 'Column {n}', 'es-MX': 'Columna {n}', 'pt-BR': 'Coluna {n}' },
  corner: { role: 'option', band: '10-12', 'en-US': 'Corner', 'es-MX': 'Esquina', 'pt-BR': 'Canto' },
  constant: { role: 'option', band: '10-12', 'en-US': 'Constant', 'es-MX': 'Constante', 'pt-BR': 'Constante' },
  backToPieces: { role: 'option', band: '10-12', 'en-US': 'Back to the pieces', 'es-MX': 'De vuelta a las piezas', 'pt-BR': 'De volta às peças' },
  areaPlaced: { role: 'data', 'en-US': 'Placed', 'es-MX': 'Colocadas', 'pt-BR': 'Colocadas' },
  areaOf: { role: 'data', 'en-US': 'of', 'es-MX': 'de', 'pt-BR': 'de' },
  areaCaption: { role: 'heading', band: '10-12', 'en-US': 'Piece in each place', 'es-MX': 'Pieza en cada lugar', 'pt-BR': 'Peça em cada lugar' },
  colPlace: { role: 'data', 'en-US': 'Place', 'es-MX': 'Lugar', 'pt-BR': 'Lugar' },
  colPiece: { role: 'data', 'en-US': 'Piece', 'es-MX': 'Pieza', 'pt-BR': 'Peça' },
  metCells: { role: 'body', band: '10-12', 'en-US': 'Every product is in its cell.', 'es-MX': 'Cada producto está en su celda.', 'pt-BR': 'Cada produto está na sua célula.' },
  hintCells: { role: 'body', band: '10-12', 'en-US': 'Not yet. Multiply each row by each column.', 'es-MX': 'Aún no. Multiplica cada fila por cada columna.', 'pt-BR': 'Ainda não. Multiplique cada linha por cada coluna.' },
  metEdges: { role: 'body', band: '10-12', 'en-US': 'The factors fit the products.', 'es-MX': 'Los factores dan los productos.', 'pt-BR': 'Os fatores dão os produtos.' },
  hintEdges: { role: 'body', band: '10-12', 'en-US': 'Not yet. Each cell is a row times a column.', 'es-MX': 'Aún no. Cada celda es una fila por una columna.', 'pt-BR': 'Ainda não. Cada célula é uma linha vezes uma coluna.' },
  metSquare: { role: 'body', band: '10-12', 'en-US': 'The square is complete.', 'es-MX': 'El cuadrado está completo.', 'pt-BR': 'O quadrado está completo.' },
  hintSquare: { role: 'body', band: '10-12', 'en-US': 'Not yet. Half of b, squared, fills the corner.', 'es-MX': 'Aún no. La mitad de b, al cuadrado, llena la esquina.', 'pt-BR': 'Ainda não. A metade de b, ao quadrado, preenche o canto.' },
} as const satisfies HorizonteCopy;
