/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/alg1/scorer.ts. Do not edit: change the source and regenerate. */
import type { HorizonteScorer } from '../types.generated';

export const ALG1_SCORERS: Readonly<Record<string, HorizonteScorer>> = {};
