import { useId, useState } from 'react';
import type { Locale } from '../design/copyBudget';
import { Button, SegmentedControl, TextField } from '../design/controls';
import { LessonFeedback } from './LessonFeedback';
import { type LessonClientDocument, type LessonClientSegment } from './lessonDocument';
import { type LessonSequenceControl } from './lessonSequence';
import { useSingleActiveGrade } from './useSingleActiveGrade';
import './learning.css';
import { LessonStageSlot } from './lessonStage';

type Segment = Extract<LessonClientSegment, { type: 'math.bar-model.structure.v2' | 'math.bar-model.answer.v2' }>;
type Verdict = 'invalid' | 'met' | 'review';
type Copy = { reset: string; back: string; model: string; answer: string; comparison: string; partWhole: string; check: string; continue: string; correct: string; retry: string; unavailable: string; input: string; and: string; whole: string; difference: string; measure: string; value: string; smaller: string; unknown: string; showTable: string; showVisual: string };
const copy: Record<Locale, Copy> = {
  'en-US': { reset: 'Reset', back: 'Back', model: 'Build the model', answer: 'Solve the model', comparison: 'Comparison', partWhole: 'Part and whole', check: 'Check', continue: 'Continue', correct: 'Correct', retry: 'Try a different model.', unavailable: 'We could not check that. Try again.', input: 'How many coins does the smaller bar show?', and: 'and', whole: 'whole', difference: 'difference', measure: 'Measure', value: 'Value', smaller: 'Smaller bar', unknown: 'Unknown', showTable: 'Show as table', showVisual: 'Show model' },
  'es-MX': { reset: 'Restablecer', back: 'Volver', model: 'Construye el modelo', answer: 'Resuelve el modelo', comparison: 'Comparación', partWhole: 'Parte y total', check: 'Comprobar', continue: 'Continuar', correct: 'Correcto', retry: 'Prueba otro modelo.', unavailable: 'No pudimos comprobarlo. Intenta otra vez.', input: '¿Cuántas monedas muestra la barra más pequeña?', and: 'y', whole: 'total', difference: 'diferencia', measure: 'Medida', value: 'Valor', smaller: 'Barra pequeña', unknown: 'Incógnita', showTable: 'Ver tabla', showVisual: 'Ver modelo' },
  'pt-BR': { reset: 'Recomeçar', back: 'Voltar', model: 'Monte o modelo', answer: 'Resolva o modelo', comparison: 'Comparação', partWhole: 'Parte e todo', check: 'Conferir', continue: 'Continue', correct: 'Correto', retry: 'Tente outro modelo.', unavailable: 'Não foi possível conferir. Tente de novo.', input: 'Quantas moedas a barra menor mostra?', and: 'e', whole: 'total', difference: 'diferença', measure: 'Medida', value: 'Valor', smaller: 'Barra menor', unknown: 'Incógnita', showTable: 'Ver tabela', showVisual: 'Ver modelo' },
};

export function barModelPilotDocument(locale: Locale): unknown {
  const title = { 'en-US': 'Compare two savings', 'es-MX': 'Compara dos ahorros', 'pt-BR': 'Compare duas economias' }[locale];
  const structurePrompt = { 'en-US': 'Ana has 12 more coins than Leo, and together they have 50. Choose the model.', 'es-MX': 'Ana tiene 12 monedas más que Leo y juntos tienen 50. Elige el modelo.', 'pt-BR': 'Ana tem 12 moedas a mais que Leo e, juntos, têm 50. Escolha o modelo.' }[locale];
  const answerPrompt = { 'en-US': 'Use the comparison model. How many coins does Leo have?', 'es-MX': 'Usa el modelo de comparación. ¿Cuántas monedas tiene Leo?', 'pt-BR': 'Use o modelo de comparação. Quantas moedas Leo tem?' }[locale];
  const p = { whole: 50, difference: 12, knownLabel: 'Ana', unknownLabel: 'Leo', spokenText: 'fifty minus twelve' };
  return { schema_version: 2, course_id: 'financial-education', pathway_id: 'financial-10-12', chapter_id: 'compare-savings', lesson_id: 'pilot-bar-model', version_id: 'rev-1', locale, age_band: '10-12', eligibility: { minimum_age: 10, maximum_age: 12 }, knowledge_component_ids: ['kc-compare-quantities'], adventure_scene_id: 'diorama-a', title, required_capabilities: ['visual.bar-model.v1', 'operation.build-slots.v1', 'operation.structure-check.v1', 'operation.number-input.v1'], segments: [{ id: 'bar-structure-01', type: 'math.bar-model.structure.v2', grading: 'server', prompt: structurePrompt, visual: { type: 'bar-model' }, payload: p }, { id: 'bar-answer-01', type: 'math.bar-model.answer.v2', grading: 'server', prompt: answerPrompt, visual: { type: 'bar-model' }, payload: p }] };
}

export function BarModelBoard({ document, segment, onBack, onGrade, sequence }: { document: LessonClientDocument; segment: Segment; onBack: () => void; onGrade: (answer: Record<string, unknown>, segmentId: string) => Verdict | Promise<Verdict>; sequence?: LessonSequenceControl }) {
  const t = copy[document.locale]; const p = segment.payload; const structure = segment.type === 'math.bar-model.structure.v2'; const modelName = useId();
  const [model, setModel] = useState<'comparison' | 'part-whole'>('comparison'); const [value, setValue] = useState(''); const [showTable, setShowTable] = useState(false); const [verdict, setVerdict] = useState<'met' | 'review' | 'unavailable' | null>(null);
  const { pending, grade } = useSingleActiveGrade();
  // Bible 05 §3: Reset restores the authored start (the comparison model, an empty answer) and clears the verdict.
  const pristine = model === 'comparison' && value === '' && verdict === null;
  const reset = () => { setModel('comparison'); setValue(''); setVerdict(null); };
  const submit = () => { if (verdict === 'met') { sequence?.onAdvance(); return; } const answer = structure ? { model } : { value }; grade(() => onGrade(answer, segment.id), (result) => setVerdict(result === 'met' ? 'met' : 'review'), () => setVerdict('unavailable')); };
  const table = <table className="lf-learning-table" aria-label={structure ? t.model : t.answer}><thead><tr><th scope="col" data-copy-role="data">{t.measure}</th><th scope="col" data-copy-role="data">{t.value}</th></tr></thead><tbody><tr><th scope="row" data-label={t.measure} data-copy-role="data">{t.whole}</th><td data-label={t.value} data-copy-role="data">{p.whole}</td></tr><tr><th scope="row" data-label={t.measure} data-copy-role="data">{t.difference}</th><td data-label={t.value} data-copy-role="data">{p.difference}</td></tr><tr><th scope="row" data-label={t.measure} data-copy-role="data">{t.smaller}</th><td data-label={t.value} data-copy-role="data">{t.unknown}</td></tr></tbody></table>;
  const visual = <div className="lf-bar-model" role="img" aria-label={`${p.knownLabel} ${t.and} ${p.unknownLabel}; ${t.whole} ${p.whole}, ${t.difference} ${p.difference}`}><div className="lf-bar-model-row"><span data-copy-role="label">{p.unknownLabel}</span><div className="lf-bar-model-track"><i style={{ inlineSize: `${(p.whole - p.difference) / p.whole * 100}%` }} /></div></div><div className="lf-bar-model-row"><span data-copy-role="label">{p.knownLabel}</span><div className="lf-bar-model-track"><i style={{ inlineSize: '100%' }} /><b data-copy-role="data">+{p.difference}</b></div></div></div>;
  return <main className="lf-learning" data-surface="app" data-screen="bar-model"><div className="lf-learning-inner"><header className="lf-learning-top"><Button onClick={onBack}>{t.back}</Button><span data-copy-role="data">{sequence ? `${sequence.index + 1}/${sequence.total}` : ''}</span></header><LessonStageSlot verdict={verdict} /><div className="lf-learning-content"><div className="lf-learning-intro"><h1 data-copy-role="heading">{document.title}</h1><p data-copy-role="prompt">{segment.prompt}</p></div><section className="lf-learning-board"><h2 data-copy-role="heading">{structure ? t.model : t.answer}</h2>{showTable ? table : visual}</section><div className="lf-learning-control-strip"><div className="lf-learning-control-bar"><Button size="sm" onClick={reset} disabled={pending || pristine}>{t.reset}</Button><Button variant="sky" size="sm" className="lf-learning-view-toggle" onClick={() => setShowTable((current) => !current)}>{showTable ? t.showVisual : t.showTable}</Button></div>{structure ? <SegmentedControl legend={t.model} legendHidden name={`${modelName}-model`} disabled={pending} value={model}
    onValueChange={(next) => { setModel(next); setVerdict(null); }} options={[{ value: 'comparison', label: t.comparison }, { value: 'part-whole', label: t.partWhole }]} /> : <TextField label={t.input} inputMode="numeric" pattern="[0-9]*" autoComplete="off" disabled={pending} value={value} onChange={(event) => { setValue(event.target.value); setVerdict(null); }} />}</div><footer className="lf-learning-foot"><LessonFeedback verdict={verdict}>{verdict === 'met' ? t.correct : verdict === 'review' ? t.retry : verdict === 'unavailable' ? t.unavailable : null}</LessonFeedback><div className="lf-learning-actions"><Button variant="accent" onClick={submit} disabled={pending || !structure && !/^(0|[1-9]\d*)$/.test(value)}>{verdict === 'met' ? t.continue : t.check}</Button></div></footer></div></div></main>;
}
