import { useState } from 'react';
import type { Locale } from '../design/copyBudget';
import { Button } from '../design/controls';
import { type LessonClientDocument, type LessonClientSegment } from './lessonDocument';
import { type LessonSequenceControl } from './lessonSequence';
import { useSingleActiveGrade } from './useSingleActiveGrade';
import './learning.css';
import './numberLine.css';

type Segment = Extract<LessonClientSegment, { type: 'math.fraction-area.v2' }>;
type Verdict = 'met' | 'review' | 'invalid';
type Copy = { back: string; explore: string; board: string; parts: string; shaded: string; of: string; less: string; more: string; measure: string; value: string; showTable: string; showVisual: string; check: string; continue: string; correct: string; retry: string; unavailable: string };
const copy: Record<Locale, Copy> = {
  'en-US': { back: 'Back', explore: 'Explore', board: 'Equal parts', parts: 'Equal parts', shaded: 'Shaded parts', of: 'of', less: 'Less', more: 'More', measure: 'Measure', value: 'Value', showTable: 'Show as table', showVisual: 'Show board', check: 'Check', continue: 'Continue', correct: 'Correct', retry: 'Try a different split.', unavailable: 'We could not check that. Try again.' },
  'es-MX': { back: 'Volver', explore: 'Explorar', board: 'Partes iguales', parts: 'Partes iguales', shaded: 'Partes coloreadas', of: 'de', less: 'Menos', more: 'Más', measure: 'Medida', value: 'Valor', showTable: 'Ver tabla', showVisual: 'Ver pizarrón', check: 'Comprobar', continue: 'Continuar', correct: 'Correcto', retry: 'Prueba otra división.', unavailable: 'No pudimos comprobarlo. Intenta otra vez.' },
  'pt-BR': { back: 'Voltar', explore: 'Explorar', board: 'Partes iguais', parts: 'Partes iguais', shaded: 'Partes coloridas', of: 'de', less: 'Menos', more: 'Mais', measure: 'Medida', value: 'Valor', showTable: 'Ver tabela', showVisual: 'Ver quadro', check: 'Conferir', continue: 'Continuar', correct: 'Correto', retry: 'Tente outra divisão.', unavailable: 'Não foi possível conferir. Tente de novo.' },
};

export function fractionAreaPilotDocument(locale: Locale): unknown {
  const title = { 'en-US': 'Make equal shares', 'es-MX': 'Haz partes iguales', 'pt-BR': 'Faça partes iguais' }[locale];
  const prompt = { 'en-US': 'Split the shape into equal parts. Shade one half.', 'es-MX': 'Divide la figura en partes iguales. Colorea una mitad.', 'pt-BR': 'Divida a figura em partes iguais. Pinte uma metade.' }[locale];
  const spokenText = { 'en-US': 'one half', 'es-MX': 'una mitad', 'pt-BR': 'uma metade' }[locale];
  return { schema_version: 2, course_id: 'financial-education', pathway_id: 'financial-young', chapter_id: 'equal-shares', lesson_id: 'pilot-fraction-area', version_id: 'rev-1', locale, age_band: '6-9', eligibility: { minimum_age: 7, maximum_age: 9 }, knowledge_component_ids: ['kc-equal-shares'], adventure_scene_id: 'diorama-a', title, required_capabilities: ['visual.fraction-area.v1', 'operation.partition-equal.v1', 'operation.shade-parts.v1', 'operation.split-equivalent.v1'], segments: [{ id: 'fraction-area-01', type: 'math.fraction-area.v2', grading: 'server', prompt, visual: { type: 'fraction-area' }, payload: { minimumParts: 2, maximumParts: 6, initialParts: 2, initialShaded: 0, spokenText } }] };
}

export function FractionAreaBoard({ document, segment, onBack, onGrade, sequence }: { document: LessonClientDocument; segment: Segment; onBack: () => void; onGrade: (answer: { n: number; d: number }, segmentId: string) => Verdict | Promise<Verdict>; sequence?: LessonSequenceControl }) {
  const t = copy[document.locale]; const p = segment.payload;
  const [parts, setParts] = useState(p.initialParts); const [shaded, setShaded] = useState(p.initialShaded); const [showTable, setShowTable] = useState(false); const [verdict, setVerdict] = useState<'met' | 'review' | 'unavailable' | null>(null);
  const { pending, grade } = useSingleActiveGrade();
  const changeParts = (next: number) => { setVerdict(null); setParts(next); setShaded((current) => Math.min(current, next)); };
  const changeShaded = (next: number) => { setVerdict(null); setShaded(next); };
  const submit = () => { if (verdict === 'met') { sequence?.onAdvance(); return; } grade(() => onGrade({ n: shaded, d: parts }, segment.id), (result) => setVerdict(result === 'met' ? 'met' : 'review'), () => setVerdict('unavailable')); };
  const fraction = `${shaded}/${parts}`;
  const table = <table className="lf-learning-table" aria-label={t.board}><thead><tr><th scope="col" data-copy-role="data">{t.measure}</th><th scope="col" data-copy-role="data">{t.value}</th></tr></thead><tbody><tr><th scope="row" data-label={t.measure} data-copy-role="data">{t.parts}</th><td data-label={t.value} data-copy-role="data">{parts}</td></tr><tr><th scope="row" data-label={t.measure} data-copy-role="data">{t.shaded}</th><td data-label={t.value} data-copy-role="data">{fraction}</td></tr></tbody></table>;
  const visual = <div className="lf-fraction-area" role="img" aria-label={`${t.board}: ${shaded} ${t.of} ${parts}. ${p.spokenText}`}><div className="lf-fraction-cells" style={{ gridTemplateColumns: `repeat(${parts}, minmax(0, 1fr))` }}>{Array.from({ length: parts }, (_, index) => <span key={index} className={index < shaded ? 'lf-fraction-cell lf-fraction-cell--filled' : 'lf-fraction-cell'} />)}</div></div>;
  return <main className="lf-learning" data-surface="app" data-screen="fraction-area"><div className="lf-learning-inner"><header className="lf-learning-top"><Button onClick={onBack}>{t.back}</Button><span data-copy-role="body">{t.explore}</span></header><div className="lf-learning-content"><div className="lf-learning-intro"><h1 data-copy-role="heading">{document.title}</h1><p data-copy-role="prompt">{segment.prompt}</p></div><div className="lf-learning-workspace"><section className="lf-learning-board" aria-labelledby="fraction-area-title"><h2 id="fraction-area-title" data-copy-role="heading">{t.board}</h2>{showTable ? table : visual}</section><div className="lf-learning-control-strip lf-fraction-area-controls"><div className="lf-learning-control-bar"><button className="lf-learning-view-toggle" type="button" aria-pressed={showTable} onClick={() => setShowTable((current) => !current)} data-copy-role="action">{showTable ? t.showVisual : t.showTable}</button></div><div className="lf-learning-control"><div className="lf-learning-control-label"><span data-copy-role="label">{t.parts}</span><strong data-copy-role="data">{parts}</strong></div><div className="lf-learning-stepper"><button type="button" aria-label={`${t.parts}: ${t.less}`} disabled={pending || parts === p.minimumParts} onClick={() => changeParts(parts - 1)}>−</button><button type="button" aria-label={`${t.parts}: ${t.more}`} disabled={pending || parts === p.maximumParts} onClick={() => changeParts(parts + 1)}>+</button></div></div><div className="lf-learning-control"><div className="lf-learning-control-label"><span data-copy-role="label">{t.shaded}</span><strong data-copy-role="data">{fraction}</strong></div><div className="lf-learning-stepper"><button type="button" aria-label={`${t.shaded}: ${t.less}`} disabled={pending || !shaded} onClick={() => changeShaded(shaded - 1)}>−</button><button type="button" aria-label={`${t.shaded}: ${t.more}`} disabled={pending || shaded === parts} onClick={() => changeShaded(shaded + 1)}>+</button></div></div></div></div><footer className="lf-learning-foot"><div role="status" className={verdict ? `lf-learning-feedback lf-learning-feedback--${verdict}` : 'lf-learning-feedback'} data-copy-role="feedback">{verdict === 'met' ? t.correct : verdict === 'review' ? t.retry : verdict === 'unavailable' ? t.unavailable : null}</div><div className="lf-learning-actions"><Button variant="accent" disabled={pending} onClick={submit}>{verdict === 'met' && sequence ? t.continue : t.check}</Button></div></footer></div></div></main>;
}
