import { useId, useState } from 'react';
import type { Locale } from '../design/copyBudget';
import { Button } from '../design/controls';
import { ageEligibilityForBand, type LessonClientDocument, type LessonClientSegment } from './lessonDocument';
import { type LessonSequenceControl } from './lessonSequence';
import { useSingleActiveGrade } from './useSingleActiveGrade';
import './learning.css';
import './numberLine.css';

type Segment = Extract<LessonClientSegment, { type: 'math.number-line.fraction.v2' }>;
type Copy = { back: string; explore: string; board: string; line: string; area: string; place: string; reset: string; left: string; right: string; estimate: string; representation: string; value: string; showTable: string; showVisual: string; check: string; continue: string; correct: string; retry: string; unavailable: string };
const copy: Record<Locale, Copy> = {
  'en-US': { back: 'Back', explore: 'Explore', board: 'Fraction board', line: 'Number line', area: 'Equal parts', place: 'Place the fraction', reset: 'Reset', left: 'Move left', right: 'Move right', estimate: 'Choose a place', representation: 'Representation', value: 'Value', showTable: 'Show as table', showVisual: 'Show board', check: 'Check', continue: 'Continue', correct: 'Correct', retry: 'Try a different place.', unavailable: 'We could not check that. Try again.' },
  'es-MX': { back: 'Volver', explore: 'Explorar', board: 'Pizarrón de fracciones', line: 'Recta numérica', area: 'Partes iguales', place: 'Coloca la fracción', reset: 'Restablecer', left: 'Mover a la izquierda', right: 'Mover a la derecha', estimate: 'Elige un lugar', representation: 'Representación', value: 'Valor', showTable: 'Ver tabla', showVisual: 'Ver pizarrón', check: 'Comprobar', continue: 'Continuar', correct: 'Correcto', retry: 'Prueba otro lugar.', unavailable: 'No pudimos comprobarlo. Intenta otra vez.' },
  'pt-BR': { back: 'Voltar', explore: 'Explorar', board: 'Quadro de frações', line: 'Reta numérica', area: 'Partes iguais', place: 'Coloque a fração', reset: 'Recomeçar', left: 'Mover à esquerda', right: 'Mover à direita', estimate: 'Escolha um lugar', representation: 'Representação', value: 'Valor', showTable: 'Ver tabela', showVisual: 'Ver quadro', check: 'Conferir', continue: 'Continuar', correct: 'Correto', retry: 'Tente outro lugar.', unavailable: 'Não foi possível conferir. Tente de novo.' },
};

export function fractionNumberLinePilotDocument(locale: Locale): unknown {
  const title = { 'en-US': 'Fractions have a place', 'es-MX': 'Las fracciones tienen lugar', 'pt-BR': 'Frações têm lugar' }[locale];
  const prompt = { 'en-US': 'Move the point. Three quarters and 0.75 name the same size.', 'es-MX': 'Mueve el punto. Tres cuartos y 0.75 nombran el mismo tamaño.', 'pt-BR': 'Mova o ponto. Três quartos e 0,75 dão nome ao mesmo tamanho.' }[locale];
  const spokenText = { 'en-US': 'three quarters, zero point seven five', 'es-MX': 'tres cuartos, cero punto setenta y cinco', 'pt-BR': 'três quartos, zero vírgula setenta e cinco' }[locale];
  return { schema_version: 2, course_id: 'financial-education', pathway_id: 'financial-10-12', chapter_id: 'fraction-magnitude', lesson_id: 'pilot-fraction-number-line', version_id: 'rev-1', locale, age_band: '10-12', eligibility: ageEligibilityForBand('10-12'), knowledge_component_ids: ['kc-fraction-magnitude'], adventure_scene_id: 'diorama-a', title, required_capabilities: ['visual.number-line.v1', 'visual.fraction-area.v1', 'operation.place-point.v1', 'operation.linked-representations.v1'], segments: [{ id: 'fraction-01', type: 'math.number-line.fraction.v2', grading: 'server', prompt, visual: { type: 'number-line' }, payload: { maximumWhole: 1, divisions: 4, initialUnits: 0, spokenText } }] };
}

export function FractionNumberLineBoard({ document, segment, onBack, onGrade, sequence }: { document: LessonClientDocument; segment: Segment; onBack: () => void; onGrade: (answer: { value: string }, segmentId: string) => 'met' | 'review' | 'invalid' | Promise<'met' | 'review' | 'invalid'>; sequence?: LessonSequenceControl }) {
  const t = copy[document.locale]; const p = segment.payload;
  const [units, setUnits] = useState(p.initialUnits); const [showTable, setShowTable] = useState(false); const [verdict, setVerdict] = useState<'met' | 'review' | 'unavailable' | null>(null); const id = useId(); const total = p.maximumWhole * p.divisions;
  const { pending, grade } = useSingleActiveGrade(); const fraction = `${units}/${p.divisions}`; const decimal = new Intl.NumberFormat(document.locale, { maximumFractionDigits: 2 }).format(units / p.divisions); const percent = units / total; const benchmarks = p.maximumWhole === 1 ? [0, .5, 1] : [0, .5, 1, 1.5, 2];
  const change = (next: number) => { setVerdict(null); setUnits(next); };
  const submit = () => { if (verdict === 'met') { sequence?.onAdvance(); return; } grade(() => onGrade({ value: fraction }, segment.id), (result) => setVerdict(result === 'met' ? 'met' : 'review'), () => setVerdict('unavailable')); };
  const table = <table className="lf-learning-table" aria-label={t.board}><thead><tr><th scope="col" data-copy-role="data">{t.representation}</th><th scope="col" data-copy-role="data">{t.value}</th></tr></thead><tbody><tr><th scope="row" data-label={t.representation} data-copy-role="data">{t.area}</th><td data-label={t.value} data-copy-role="data">{fraction}</td></tr><tr><th scope="row" data-label={t.representation} data-copy-role="data">{t.line}</th><td data-label={t.value} data-copy-role="data">{fraction} = {decimal}</td></tr></tbody></table>;
  const visual = <><div className="lf-fraction-area" role="img" aria-label={`${t.area}: ${fraction}, ${decimal}. ${p.spokenText}`}><div className="lf-fraction-cells" style={{ gridTemplateColumns: `repeat(${total}, minmax(0, 1fr))` }}>{Array.from({ length: total }, (_, index) => <span key={index} className={index < units ? 'lf-fraction-cell lf-fraction-cell--filled' : 'lf-fraction-cell'} />)}</div></div><div className="lf-number-line-drawing"><div role="img" aria-label={`${t.line}: 0–${p.maximumWhole}; ${fraction}, ${decimal}`}><svg viewBox="0 0 300 96" preserveAspectRatio="none"><line x1="24" y1="52" x2="276" y2="52" className="lf-number-line-track" />{benchmarks.map((value) => { const x = 24 + 252 * value / p.maximumWhole; return <line key={value} x1={x} x2={x} y1="38" y2="66" className="lf-number-line-tick" />; })}</svg></div><input className="lf-number-line-slider" type="range" min="0" max={total} step="1" value={units} disabled={pending} aria-label={t.place} aria-valuetext={`${fraction}, ${decimal}`} onChange={(event) => change(Number(event.target.value))} /><span className="lf-number-line-marker" style={{ left: `${8 + percent * 84}%` }} aria-hidden="true" /><div className="lf-number-line-labels" aria-hidden="true">{benchmarks.map((value) => <span key={value} data-copy-role="data">{value}</span>)}</div></div></>;
  return <main className="lf-learning" data-surface="app" data-screen="fraction-numberline"><div className="lf-learning-inner"><header className="lf-learning-top"><Button onClick={onBack}>{t.back}</Button><span data-copy-role="body">{t.explore}</span></header><div className="lf-learning-content"><div className="lf-learning-intro"><h1 data-copy-role="heading">{document.title}</h1><p data-copy-role="prompt">{segment.prompt}</p></div><div className="lf-learning-workspace"><section className="lf-learning-board" aria-labelledby={`${id}-title`}><h2 id={`${id}-title`} data-copy-role="heading">{t.board}</h2>{showTable ? table : visual}</section><div className="lf-learning-control-strip"><div className="lf-learning-control-bar"><Button onClick={() => change(p.initialUnits)} disabled={pending || units === p.initialUnits}>{t.reset}</Button><strong data-copy-role="data">{verdict ? `${fraction} = ${decimal}` : t.estimate}</strong><button className="lf-learning-view-toggle" type="button" aria-pressed={showTable} onClick={() => setShowTable((current) => !current)} data-copy-role="action">{showTable ? t.showVisual : t.showTable}</button></div><div className="lf-number-line-stepper"><button type="button" aria-label={t.left} disabled={pending || !units} onClick={() => change(units - 1)}>−</button><button type="button" aria-label={t.right} disabled={pending || units === total} onClick={() => change(units + 1)}>+</button></div></div></div><footer className="lf-learning-foot"><div role="status" className={verdict ? `lf-learning-feedback lf-learning-feedback--${verdict}` : 'lf-learning-feedback'} data-copy-role="feedback">{verdict === 'met' ? t.correct : verdict === 'review' ? t.retry : verdict === 'unavailable' ? t.unavailable : null}</div><div className="lf-learning-actions"><Button variant="accent" disabled={pending} onClick={submit}>{verdict === 'met' && sequence ? t.continue : t.check}</Button></div></footer></div></div></main>;
}
