/* Canonical pure visual model. Its browser copy is generated by sync-v2-growth-comparison.mjs. */
export interface GrowthComparisonInput {
  principalMinor: number;
  rateBasisPoints: number;
  years: number;
}

export interface GrowthComparisonPoint {
  year: number;
  simpleMinor: number;
  compoundMinor: number;
}

const BPS = 10_000n;

function roundMinor(numerator: bigint): bigint {
  return (numerator + BPS / 2n) / BPS;
}

/** Annual interest on one principal, rounded to the nearest minor unit at each annual posting. */
export function growthComparison(input: GrowthComparisonInput): GrowthComparisonPoint[] | null {
  const { principalMinor, rateBasisPoints, years } = input;
  if (!Number.isSafeInteger(principalMinor) || principalMinor < 100 || principalMinor > 1_000_000
    || !Number.isSafeInteger(rateBasisPoints) || rateBasisPoints < 100 || rateBasisPoints > 1_500
    || !Number.isSafeInteger(years) || years < 1 || years > 30) return null;
  const principal = BigInt(principalMinor);
  const rate = BigInt(rateBasisPoints);
  let compound = principal;
  const points: GrowthComparisonPoint[] = [{ year: 0, simpleMinor: principalMinor, compoundMinor: principalMinor }];
  for (let year = 1; year <= years; year += 1) {
    const simple = principal + roundMinor(principal * rate * BigInt(year));
    compound = roundMinor(compound * (BPS + rate));
    if (simple > BigInt(Number.MAX_SAFE_INTEGER) || compound > BigInt(Number.MAX_SAFE_INTEGER)) return null;
    points.push({ year, simpleMinor: Number(simple), compoundMinor: Number(compound) });
  }
  return points;
}
