import { useMemo, useState } from 'react';
import type { Locale } from '../design/copyBudget';
import { Button, Slider } from '../design/controls';
import { taxBracketModel } from './taxBracketModel.generated';
import { TeachingChartBoard } from './TeachingChartBoard';
import type { LessonClientDocument, LessonClientSegment } from './lessonDocument';
import './learning.css';
import './taxBracket.css';
import { LessonStageSlot } from './lessonStage';

type TaxSegment = Extract<LessonClientSegment, { type: 'visual.tax-bracket.v2' }>;
const copy: Record<Locale, { back: string; explore: string; board: string; chart: string; showTable: string; showChart: string; income: string; tax: string; takeHome: string; marginal: string; average: string; bracket: string; taxable: string; reset: string; title: string; prompt: string }> = {
  'en-US': { back: 'Back', explore: 'Explore', board: 'Tax board', chart: 'Tax bracket stacked bar', showTable: 'Show as table', showChart: 'Show chart', income: 'Income', tax: 'Tax', takeHome: 'Take home', marginal: 'Marginal rate', average: 'Average rate', bracket: 'Bracket', taxable: 'Taxed here', reset: 'Reset', title: 'How brackets fill', prompt: 'Move income. A higher bracket changes only the part that reaches it.' },
  'es-MX': { back: 'Volver', explore: 'Explorar', board: 'Pizarrón fiscal', chart: 'Barra apilada de tramos fiscales', showTable: 'Ver tabla', showChart: 'Ver gráfico', income: 'Ingreso', tax: 'Impuesto', takeHome: 'Te queda', marginal: 'Tasa marginal', average: 'Tasa promedio', bracket: 'Tramo', taxable: 'Gravado aquí', reset: 'Restablecer', title: 'Cómo se llenan los tramos', prompt: 'Cambia el ingreso. Una tasa mayor afecta solo la parte que llega a ese tramo.' },
  'pt-BR': { back: 'Voltar', explore: 'Explorar', board: 'Quadro fiscal', chart: 'Barra empilhada de faixas fiscais', showTable: 'Ver tabela', showChart: 'Ver gráfico', income: 'Renda', tax: 'Imposto', takeHome: 'Você recebe', marginal: 'Alíquota marginal', average: 'Alíquota média', bracket: 'Faixa', taxable: 'Tributado aqui', reset: 'Recomeçar', title: 'Como as faixas se preenchem', prompt: 'Mude a renda. Uma alíquota maior afeta só a parte que chega àquela faixa.' },
};
const currencies: Record<Locale, string> = { 'en-US': 'USD', 'es-MX': 'MXN', 'pt-BR': 'BRL' };

export function taxBracketPilotDocument(locale: Locale): unknown {
  const t = copy[locale];
  return { schema_version: 2, course_id: 'financial-education', pathway_id: 'financial-13-17', chapter_id: 'tax-basics', lesson_id: 'pilot-tax-brackets', version_id: 'rev-1', locale, age_band: '13-17', eligibility: { minimum_age: 14, maximum_age: 17 }, knowledge_component_ids: ['kc-marginal-tax'], adventure_scene_id: 'diorama-a', title: t.title,
    required_capabilities: ['visual.stacked-bar.v1', 'operation.parameter-slider.v1', 'operation.linked-representations.v1'], segments: [{ id: 'tax-01', type: 'visual.tax-bracket.v2', grading: 'none', prompt: t.prompt, visual: { type: 'stacked-bar' }, payload: { minimumIncomeMinor: 0, maximumIncomeMinor: 60_000, incomeStepMinor: 5_000, initialIncomeMinor: 30_000, brackets: [{ upToMinor: 10_000, rateBasisPoints: 1_000 }, { upToMinor: 30_000, rateBasisPoints: 2_000 }, { upToMinor: null, rateBasisPoints: 3_000 }] } }] };
}

export function TaxBracketBoard({ document, segment, onBack }: { document: LessonClientDocument; segment: TaxSegment; onBack: () => void }) {
  const t = copy[document.locale]; const p = segment.payload; const [income, setIncome] = useState(p.initialIncomeMinor);
  const model = taxBracketModel(income, p.brackets); if (!model) return null;
  const money = useMemo(() => new Intl.NumberFormat(document.locale, { style: 'currency', currency: currencies[document.locale], currencyDisplay: 'code' }), [document.locale]);
  const percent = useMemo(() => new Intl.NumberFormat(document.locale, { style: 'percent', maximumFractionDigits: 0 }), [document.locale]);
  const amount = (value: number) => money.format(value / 100); const rate = (value: number) => percent.format(value / 10_000);
  const table = <table className="lf-learning-table" aria-label={t.board}><thead><tr><th scope="col" data-copy-role="data">{t.bracket}</th><th scope="col" data-copy-role="data">{t.taxable}</th><th scope="col" data-copy-role="data">{t.tax}</th></tr></thead><tbody>{model.slices.map((slice, index) => <tr key={index}><th scope="row" data-label={t.bracket} data-copy-role="data">{rate(slice.rateBasisPoints)}</th><td data-label={t.taxable} data-copy-role="data">{amount(slice.taxableMinor)}</td><td data-label={t.tax} data-copy-role="data">{amount(slice.taxMinor)}</td></tr>)}</tbody></table>;
  return <main className="lf-learning" data-surface="app" data-screen="tax-bracket"><div className="lf-learning-inner"><header className="lf-learning-top"><Button onClick={onBack}>{t.back}</Button><span data-copy-role="body">{t.explore}</span></header><LessonStageSlot /><div className="lf-learning-content"><div className="lf-learning-intro"><h1 data-copy-role="heading">{document.title}</h1><p data-copy-role="prompt">{segment.prompt}</p></div><TeachingChartBoard title={t.board} showTableLabel={t.showTable} showChartLabel={t.showChart} table={table} controlLeading={<Button onClick={() => setIncome(p.initialIncomeMinor)} disabled={income === p.initialIncomeMinor}>{t.reset}</Button>} chart={<><div className="lf-tax-chart" role="img" aria-label={`${t.chart}. ${t.income}: ${amount(income)}. ${t.tax}: ${amount(model.totalTaxMinor)}. ${t.takeHome}: ${amount(model.takeHomeMinor)}. ${t.marginal}: ${rate(model.marginalRateBasisPoints)}. ${t.average}: ${rate(model.averageRateBasisPoints)}.`}><svg className="lf-tax-stack" viewBox="0 0 300 72" preserveAspectRatio="none" aria-hidden="true">{model.slices.map((slice, index) => { const width = income === 0 ? 0 : slice.taxableMinor / income * 300; const x = income === 0 ? 0 : model.slices.slice(0, index).reduce((total, previous) => total + previous.taxableMinor, 0) / income * 300; return <rect key={index} className={`lf-tax-slice lf-tax-slice--${index}`} x={x} y="0" width={width} height="72" />; })}</svg><div className="lf-tax-legend">{model.slices.map((slice, index) => <span key={index} data-copy-role="data"><i className={`lf-tax-swatch lf-tax-swatch--${index}`} aria-hidden="true" />{rate(slice.rateBasisPoints)}</span>)}</div></div><div className="lf-tax-summary" role="status" aria-live="polite"><span data-copy-role="data">{t.tax}: {amount(model.totalTaxMinor)}</span><span data-copy-role="data">{t.takeHome}: {amount(model.takeHomeMinor)}</span><span data-copy-role="data">{t.marginal}: {rate(model.marginalRateBasisPoints)}</span><span data-copy-role="data">{t.average}: {rate(model.averageRateBasisPoints)}</span></div></>}>{() => <Slider label={t.income} valueText={amount(income)} min={p.minimumIncomeMinor} max={p.maximumIncomeMinor} step={p.incomeStepMinor} value={income} onValueChange={setIncome} />}</TeachingChartBoard></div></div></main>;
}
