/*
 * Canonical semantic payload for the v2 scorer (GAP-FIX-R2 learning,
 * Appendix P Part 8 "scorer parity"). Core grades with it; the browser copy
 * (frontend/src/rebuild/learning/v2ScorerPayload.generated.ts) is generated by
 * agent/tools/sync-v2-scorer-payload.mjs and `npm run spec:check` fails on
 * drift. The browser runs the same pure scorer on the same semantic payload
 * without a rubric, so its advisory verdict (valid or invalid) can be compared
 * with Core's for every graded submission. Only structure reaches the scorer:
 * never labels, copy or answers.
 *
 * Self-contained except for the synced segment families module.
 */
import { barModelScorerPayload, placeValueScorerPayload, schemaDiagramScorerPayload, v2FamilyScorerPayload, type BarModelPayload, type PlaceValuePayload, type SchemaDiagramPayload, type V2FamilySegment } from './v2SegmentFamilies.generated';

type Loose = { type: string; payload: Record<string, any> }; // eslint-disable-line @typescript-eslint/no-explicit-any

const FAMILY_KINDS = new Set(['logic.rule-checker.v2', 'logic.euler.v2', 'logic.flowchart.v2', 'money.spend-decision.v2', 'logic.sort-by-rule.v2',
  'money.needs-wants.v2', 'logic.scam-spotter.v2', 'money.scam-check.v2', 'money.coin-tray.v2', 'money.making-change.v2', 'story.branch.v2',
  'story.dialogue-choice.v2', 'story.would-you-rather.v2', 'money.unit-price.v2', 'logic.rule-builder.v2']);

/** The scorer payload of a validated segment, or null for a kind the visual scorer does not grade (concept boards, voice). */
export function v2ScorerPayload(segment: Loose): Record<string, unknown> | null {
  const p = segment.payload;
  if (FAMILY_KINDS.has(segment.type)) return v2FamilyScorerPayload(segment as unknown as V2FamilySegment);
  switch (segment.type) {
    case 'money.allocation.v2': return { total: p.total, step: p.step };
    case 'math.number-line.whole.v2': return { minimum: p.minimum, maximum: p.maximum, step: p.step, ...(p.hops ? { initial: p.initial, hops: p.hops } : {}),
      ...(p.items ? { itemIds: (p.items as Array<{ id: string }>).map((item) => item.id) } : {}) };
    case 'math.number-line.fraction.v2': return { maximumWhole: p.maximumWhole, divisions: p.divisions,
      ...(p.compare_values ? { compare_values: p.compare_values } : {}), ...(p.equivalent_values ? { equivalent_values: p.equivalent_values } : {}) };
    case 'math.fraction-area.v2': return { minimumParts: p.minimumParts, maximumParts: p.maximumParts };
    case 'math.bar-model.structure.v2':
    case 'math.bar-model.answer.v2': return barModelScorerPayload(p as BarModelPayload);
    case 'math.schema-diagram.structure.v2':
    case 'math.schema-diagram.slots.v2':
    case 'math.schema-diagram.answer.v2': return schemaDiagramScorerPayload(p as SchemaDiagramPayload);
    case 'math.worked-example.v2': return { response_step_ids: p.response_step_ids };
    case 'math.function-machine.v2': return { multiplierMaximum: p.multiplierMaximum, offsetMaximum: p.offsetMaximum,
      exampleInputs: (p.examples as Array<{ input: number }>).map((example) => example.input) };
    case 'math.cpa-count.v2': return { left: p.left, right: p.right };
    case 'reasoning.decide-justify.v2': return { choiceIds: (p.choices as Array<{ id: string }>).map((option) => option.id),
      reasonIds: (p.reasons as Array<{ id: string }>).map((option) => option.id) };
    case 'math.place-value.v2': return placeValueScorerPayload(p as PlaceValuePayload);
    case 'math.ratio-table.v2': return { itemsPerPack: p.itemsPerPack, pricePerPack: p.pricePerPack, minimumPacks: p.minimumPacks, maximumPacks: p.maximumPacks };
    case 'visual.percent-grid.v2': return { baseUnits: p.baseUnits, step: p.step };
    case 'visual.growth-comparison.v2': return { principalMinor: p.principalMinor, minimumRateBps: p.minimumRateBps, maximumRateBps: p.maximumRateBps,
      rateStepBps: p.rateStepBps, minimumYears: p.minimumYears, maximumYears: p.maximumYears, yearStep: p.yearStep,
      predictionStepMinor: p.predictionStepMinor, predictionMaximumMinor: p.predictionMaximumMinor };
    case 'visual.tax-bracket.v2': return { minimumIncomeMinor: p.minimumIncomeMinor, maximumIncomeMinor: p.maximumIncomeMinor,
      incomeStepMinor: p.incomeStepMinor, brackets: p.brackets };
    case 'logic.savings-rule.v2': return { goal: p.goal };
    case 'visual.goal-bullet.v2': return { minimum: p.minimum, maximum: p.maximum, step: p.step };
    case 'money.running-ledger.v2': return { initial: p.initial, sale: p.sale, cost: p.cost, maxEntries: p.maxEntries };
    case 'visual.chart.v2': return { choiceIds: ((p.question?.options ?? []) as Array<{ id: string }>).map((option) => option.id) };
    default: return null;
  }
}
