/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/geom2/areaModel.ts. Do not edit: change the source and regenerate. */
import { cellsInside, cornersOf, isLatticeList, isOrthogonal, isSimplePolygon, sameSet, type Lattice } from './geometry.generated';

export const AREA_MIN_SIDE = 2;
export const AREA_MAX_SIDE = 8;
/** The most squares a figure may cover; the point-set answer shape holds at most this many required points. */
export const AREA_MAX_CELLS = 32;

/** A grid of `columns` by `rows` squares and the outline drawn on it: corners of a closed band whose edges follow the grid lines. */
export interface AreaSquaresPayload { columns: number; rows: number; outline: Lattice[] }
/** The private key: every square inside the outline, each named by its lower-left corner. */
export interface AreaSquaresRubric { required: Lattice[] }

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const hasKeys = (value: Record<string, unknown>, required: readonly string[]): boolean => {
  const keys = Object.keys(value);
  return keys.length === required.length && required.every((key) => keys.includes(key));
};
const isSide = (value: unknown): value is number => Number.isInteger(value) && (value as number) >= AREA_MIN_SIDE && (value as number) <= AREA_MAX_SIDE;

export function isAreaSquaresPayload(value: unknown): value is AreaSquaresPayload {
  if (!isRecord(value) || !hasKeys(value, ['columns', 'rows', 'outline']) || !isSide(value.columns) || !isSide(value.rows)) return false;
  const { columns, rows, outline } = value as { columns: number; rows: number; outline: unknown };
  if (!isLatticeList(outline, 4, 16) || !outline.every((point) => point.x >= 0 && point.x <= columns && point.y >= 0 && point.y <= rows)) return false;
  if (!isSimplePolygon(outline) || !isOrthogonal(outline) || cornersOf(outline).length !== outline.length) return false;
  const count = cellsInside(outline, columns, rows).length;
  return count >= 1 && count <= AREA_MAX_CELLS;
}

/** The squares the outline covers: the one correct shading. */
export const areaCells = (payload: AreaSquaresPayload): Lattice[] => cellsInside(payload.outline, payload.columns, payload.rows);

/** The frame the point-set grader reads a shading in: whole squares on the grid, at most all of them. */
export const areaPointContext = (payload: AreaSquaresPayload) => ({
  minimumX: 0, maximumX: payload.columns - 1, minimumY: 0, maximumY: payload.rows - 1, step: 1, maxPoints: Math.min(64, payload.columns * payload.rows),
});

export function isAreaSquaresRubric(value: unknown, payload: AreaSquaresPayload): value is AreaSquaresRubric {
  if (!isRecord(value) || !hasKeys(value, ['required']) || !isLatticeList(value.required, 1, AREA_MAX_CELLS)) return false;
  return sameSet(value.required, areaCells(payload));
}
