/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/geom2/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const GEOM2_SEGMENTS = [] as const;
export const GEOM2_RUBRICS = {} as const;
export const GEOM2_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
