import type { HorizonteCopy } from '../boardTypes';

/* Written to the strictest budget (ages 6-9) so one entry serves every band; {name} marks a slot. Words beside a figure are `data`. */
export const GEOM2_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  undo: { role: 'action', 'en-US': 'Undo', 'es-MX': 'Deshacer', 'pt-BR': 'Desfazer' },
  total: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  colX: { role: 'data', 'en-US': 'x', 'es-MX': 'x', 'pt-BR': 'x' },
  colY: { role: 'data', 'en-US': 'y', 'es-MX': 'y', 'pt-BR': 'y' },

  geoLabel: { role: 'data', 'en-US': 'Geoboard', 'es-MX': 'Geoplano', 'pt-BR': 'Geoplano' },
  geoCursor: { role: 'data', 'en-US': 'Peg cursor', 'es-MX': 'Cursor de clavija', 'pt-BR': 'Cursor do pino' },
  placePeg: { role: 'action', 'en-US': 'Place peg', 'es-MX': 'Poner clavija', 'pt-BR': 'Colocar pino' },
  geoHint: { role: 'body', 'en-US': 'Arrow keys move the cursor. Enter places a peg.', 'es-MX': 'Las flechas mueven el cursor. Enter pone una clavija.', 'pt-BR': 'As setas movem o cursor. Enter coloca um pino.' },
  geoFacts: {
    role: 'data', 'en-US': 'Geoboard {size} by {size}. Band: {count} pegs. Cursor: {x}, {y}.',
    'es-MX': 'Geoplano de {size} por {size}. Liga: {count} clavijas. Cursor: {x}, {y}.',
    'pt-BR': 'Geoplano de {size} por {size}. Elástico: {count} pinos. Cursor: {x}, {y}.',
  },
  geoNeed: { role: 'data', 'en-US': 'The band needs 3 pegs.', 'es-MX': 'La liga necesita 3 clavijas.', 'pt-BR': 'O elástico precisa de 3 pinos.' },
  geoCross: { role: 'data', 'en-US': 'The band crosses itself.', 'es-MX': 'La liga se cruza.', 'pt-BR': 'O elástico se cruza.' },
  geoCaption: { role: 'heading', 'en-US': 'Pegs in the band', 'es-MX': 'Clavijas en la liga', 'pt-BR': 'Pinos no elástico' },
  colPeg: { role: 'data', 'en-US': 'Peg', 'es-MX': 'Clavija', 'pt-BR': 'Pino' },
  pegName: { role: 'data', 'en-US': 'Peg {n}', 'es-MX': 'Clavija {n}', 'pt-BR': 'Pino {n}' },
  metGeo: { role: 'body', 'en-US': 'The band covers the right area.', 'es-MX': 'La liga cubre el área correcta.', 'pt-BR': 'O elástico cobre a área certa.' },
  hintGeo: { role: 'body', 'en-US': 'Not yet. Check the area and the shape.', 'es-MX': 'Aún no. Revisa el área y la figura.', 'pt-BR': 'Ainda não. Confira a área e a figura.' },

  areaLabel: { role: 'data', 'en-US': 'Grid of squares', 'es-MX': 'Cuadrícula de cuadritos', 'pt-BR': 'Grade de quadradinhos' },
  areaCursor: { role: 'data', 'en-US': 'Square cursor', 'es-MX': 'Cursor de cuadrito', 'pt-BR': 'Cursor de quadradinho' },
  shadeSquare: { role: 'action', 'en-US': 'Shade square', 'es-MX': 'Sombrear cuadrito', 'pt-BR': 'Pintar quadradinho' },
  areaHint: { role: 'body', 'en-US': 'Arrow keys move the cursor. Enter shades a square.', 'es-MX': 'Las flechas mueven el cursor. Enter sombrea un cuadrito.', 'pt-BR': 'As setas movem o cursor. Enter pinta um quadradinho.' },
  areaFacts: {
    role: 'data', 'en-US': 'Grid {columns} by {rows}. Shaded squares: {count}. Cursor: {x}, {y}.',
    'es-MX': 'Cuadrícula de {columns} por {rows}. Cuadritos sombreados: {count}. Cursor: {x}, {y}.',
    'pt-BR': 'Grade de {columns} por {rows}. Quadradinhos pintados: {count}. Cursor: {x}, {y}.',
  },
  areaCaption: { role: 'heading', 'en-US': 'Shaded squares by row', 'es-MX': 'Cuadritos sombreados por fila', 'pt-BR': 'Quadradinhos pintados por linha' },
  colRow: { role: 'data', 'en-US': 'Row', 'es-MX': 'Fila', 'pt-BR': 'Linha' },
  colShaded: { role: 'data', 'en-US': 'Shaded', 'es-MX': 'Sombreados', 'pt-BR': 'Pintados' },
  rowName: { role: 'data', 'en-US': 'Row {n}', 'es-MX': 'Fila {n}', 'pt-BR': 'Linha {n}' },
  metArea: { role: 'body', 'en-US': 'You shaded every square inside.', 'es-MX': 'Sombreaste todos los cuadritos de adentro.', 'pt-BR': 'Você pintou todos os quadradinhos de dentro.' },
  hintArea: { role: 'body', 'en-US': 'Not yet. Shade only the squares inside the outline.', 'es-MX': 'Aún no. Sombrea solo los cuadritos dentro del contorno.', 'pt-BR': 'Ainda não. Pinte só os quadradinhos dentro do contorno.' },

  tfLabel: { role: 'data', 'en-US': 'Coordinate plane', 'es-MX': 'Plano cartesiano', 'pt-BR': 'Plano cartesiano' },
  tfFigure: { role: 'data', 'en-US': 'Figure', 'es-MX': 'Figura', 'pt-BR': 'Figura' },
  tfImage: { role: 'data', 'en-US': 'Image', 'es-MX': 'Imagen', 'pt-BR': 'Imagem' },
  tfMirror: { role: 'data', 'en-US': 'Mirror line', 'es-MX': 'Línea del espejo', 'pt-BR': 'Linha do espelho' },
  tfCenter: { role: 'data', 'en-US': 'Center', 'es-MX': 'Centro', 'pt-BR': 'Centro' },
  tfCorner: { role: 'data', 'en-US': 'Corner {name}', 'es-MX': 'Vértice {name}', 'pt-BR': 'Vértice {name}' },
  tfImageOf: { role: 'data', 'en-US': 'Image of {name}', 'es-MX': 'Imagen de {name}', 'pt-BR': 'Imagem de {name}' },
  ruleTranslate: { role: 'data', 'en-US': 'Rule: slide {dx} across and {dy} up.', 'es-MX': 'Regla: desliza {dx} en horizontal y {dy} en vertical.', 'pt-BR': 'Regra: deslize {dx} na horizontal e {dy} na vertical.' },
  ruleReflect: { role: 'data', 'en-US': 'Rule: reflect across the line {line}.', 'es-MX': 'Regla: refleja sobre la recta {line}.', 'pt-BR': 'Regra: reflita sobre a reta {line}.' },
  ruleRotate: { role: 'data', 'en-US': 'Rule: turn {degrees} degrees counterclockwise about {about}.', 'es-MX': 'Regla: gira {degrees} grados en sentido antihorario alrededor de {about}.', 'pt-BR': 'Regra: gire {degrees} graus no sentido anti-horário em torno de {about}.' },
  ruleDilate: { role: 'data', 'en-US': 'Rule: scale by {factor} from {about}.', 'es-MX': 'Regla: amplía con razón {factor} desde {about}.', 'pt-BR': 'Regra: amplie com razão {factor} a partir de {about}.' },
  tfFacts: { role: 'data', 'en-US': '{rule} Image corners: {list}.', 'es-MX': '{rule} Vértices de la imagen: {list}.', 'pt-BR': '{rule} Vértices da imagem: {list}.' },
  tfCaption: { role: 'heading', 'en-US': 'Figure and image corners', 'es-MX': 'Vértices de la figura y su imagen', 'pt-BR': 'Vértices da figura e da imagem' },
  colCorner: { role: 'data', 'en-US': 'Corner', 'es-MX': 'Vértice', 'pt-BR': 'Vértice' },
  colFigure: { role: 'data', 'en-US': 'Figure', 'es-MX': 'Figura', 'pt-BR': 'Figura' },
  colImage: { role: 'data', 'en-US': 'Image', 'es-MX': 'Imagen', 'pt-BR': 'Imagem' },
  tfCoincide: { role: 'data', 'en-US': 'Two corners are on the same point.', 'es-MX': 'Dos vértices están en el mismo punto.', 'pt-BR': 'Dois vértices estão no mesmo ponto.' },
  metTransform: { role: 'body', 'en-US': 'Every corner is in the right place.', 'es-MX': 'Cada vértice está en su lugar.', 'pt-BR': 'Cada vértice está no lugar certo.' },
  hintTransform: { role: 'body', 'en-US': 'Not yet. Check each corner against the rule.', 'es-MX': 'Aún no. Revisa cada vértice con la regla.', 'pt-BR': 'Ainda não. Confira cada vértice com a regra.' },

  tsLabel: { role: 'data', 'en-US': 'Floor', 'es-MX': 'Piso', 'pt-BR': 'Piso' },
  tsCursor: { role: 'data', 'en-US': 'Tile cursor', 'es-MX': 'Cursor de baldosa', 'pt-BR': 'Cursor do ladrilho' },
  placeTile: { role: 'action', 'en-US': 'Place tile', 'es-MX': 'Poner baldosa', 'pt-BR': 'Colocar ladrilho' },
  removeLast: { role: 'action', 'en-US': 'Remove last', 'es-MX': 'Quitar última', 'pt-BR': 'Remover última' },
  tsHint: { role: 'body', 'en-US': 'Arrow keys move the cursor. Enter places the tile.', 'es-MX': 'Las flechas mueven el cursor. Enter pone la baldosa.', 'pt-BR': 'As setas movem o cursor. Enter coloca o ladrilho.' },
  tsFacts: {
    role: 'data', 'en-US': 'Floor {columns} by {rows}. Tiles placed: {count}. Squares left: {left}. Cursor: {x}, {y}.',
    'es-MX': 'Piso de {columns} por {rows}. Baldosas puestas: {count}. Cuadritos libres: {left}. Cursor: {x}, {y}.',
    'pt-BR': 'Piso de {columns} por {rows}. Ladrilhos colocados: {count}. Quadradinhos livres: {left}. Cursor: {x}, {y}.',
  },
  tsNoFit: { role: 'data', 'en-US': 'The tile does not fit here.', 'es-MX': 'La baldosa no cabe aquí.', 'pt-BR': 'O ladrilho não cabe aqui.' },
  tsCaption: { role: 'heading', 'en-US': 'Placed tiles', 'es-MX': 'Baldosas puestas', 'pt-BR': 'Ladrilhos colocados' },
  colTile: { role: 'data', 'en-US': 'Tile', 'es-MX': 'Baldosa', 'pt-BR': 'Ladrilho' },
  tileName: { role: 'data', 'en-US': 'Tile {n}', 'es-MX': 'Baldosa {n}', 'pt-BR': 'Ladrilho {n}' },
  metTiles: { role: 'body', 'en-US': 'The tiles cover the whole floor.', 'es-MX': 'Las baldosas cubren todo el piso.', 'pt-BR': 'Os ladrilhos cobrem todo o piso.' },
  tsMotion: { role: 'data', 'en-US': 'Move', 'es-MX': 'Movimiento', 'pt-BR': 'Movimento' },
  colMove: { role: 'data', 'en-US': 'Move', 'es-MX': 'Movimiento', 'pt-BR': 'Movimento' },
  moveSlide: { role: 'option', 'en-US': 'Slide', 'es-MX': 'Deslizar', 'pt-BR': 'Deslizar' },
  moveTurn: { role: 'option', 'en-US': 'Half turn', 'es-MX': 'Media vuelta', 'pt-BR': 'Meia volta' },
  moveFlip: { role: 'option', 'en-US': 'Flip', 'es-MX': 'Voltear', 'pt-BR': 'Virar' },
  tsMove: { role: 'data', 'en-US': 'Move: {move}.', 'es-MX': 'Movimiento: {move}.', 'pt-BR': 'Movimento: {move}.' },
  tsHintMoves: { role: 'body', 'en-US': 'Arrows move the cursor. Pick a move, then Enter.', 'es-MX': 'Las flechas mueven el cursor. Elige un movimiento y pulsa Enter.', 'pt-BR': 'As setas movem o cursor. Escolha um movimento e tecle Enter.' },
  hintTiles: { role: 'body', 'en-US': 'Not yet. Fill every gap with no overlaps.', 'es-MX': 'Aún no. Llena cada hueco sin encimar.', 'pt-BR': 'Ainda não. Preencha cada lacuna sem sobrepor.' },
} as const satisfies HorizonteCopy;
