/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/geom2/fixtures.ts. Do not edit: change the source and regenerate. */
import type { HorizonteFixture } from '../types.generated';

export const GEOM2_FIXTURES: readonly HorizonteFixture[] = [];
