/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/geom2/geoboardModel.ts. Do not edit: change the source and regenerate. */
import { FIGURE_SHAPES, area2, distinct, isLatticeList, isSimplePolygon, matchesShape, type FigureShape, type Lattice } from './geometry.generated';

export const GEOBOARD_MIN_SIZE = 3;
export const GEOBOARD_MAX_SIZE = 8;

/** A square geoboard of `size` by `size` pegs, named by whole numbers 0 to size - 1 on both axes. The payload never carries the key. */
export interface GeoboardPayload { size: number }
/** The private key: the band's area in half squares (area2) and, when the task names one, the figure. */
export interface GeoboardRubric { area2: number; shape?: FigureShape }

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const hasKeys = (value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): boolean => {
  const keys = Object.keys(value);
  return required.every((key) => keys.includes(key)) && keys.every((key) => required.includes(key) || optional.includes(key));
};

export const isGeoboardSize = (value: unknown): value is number => Number.isInteger(value) && (value as number) >= GEOBOARD_MIN_SIZE && (value as number) <= GEOBOARD_MAX_SIZE;
export const isGeoboardPayload = (value: unknown): value is GeoboardPayload => isRecord(value) && hasKeys(value, ['size']) && isGeoboardSize(value.size);

/** The largest band a board can hold, in half squares. */
export const maxArea2 = (size: number): number => 2 * (size - 1) * (size - 1);

export function isGeoboardRubric(value: unknown, size: number): value is GeoboardRubric {
  if (!isRecord(value) || !hasKeys(value, ['area2'], ['shape'])) return false;
  if (!Number.isInteger(value.area2) || (value.area2 as number) < 1 || (value.area2 as number) > maxArea2(size)) return false;
  return value.shape === undefined || (typeof value.shape === 'string' && (FIGURE_SHAPES as readonly string[]).includes(value.shape));
}

export const onBoard = (points: readonly Lattice[], size: number): boolean => points.every((point) => point.x >= 0 && point.x < size && point.y >= 0 && point.y < size);

export type BandReading = { kind: 'untouched' } | { kind: 'band'; points: Lattice[] };

/** A response is the rubber band's pegs in order: none (untouched) or a simple closed band of three pegs or more, all on the board. */
export function readBand(response: unknown, size: number): BandReading | null {
  if (!isRecord(response) || !hasKeys(response, ['points'])) return null;
  const points = response.points;
  if (!isLatticeList(points, 0, size * size) || !onBoard(points, size) || !distinct(points)) return null;
  if (points.length === 0) return { kind: 'untouched' };
  return isSimplePolygon(points) ? { kind: 'band', points } : null;
}

export type BandCheck = 'met' | 'area' | 'shape';

export function checkBand(points: readonly Lattice[], rubric: GeoboardRubric): BandCheck {
  if (area2(points) !== rubric.area2) return 'area';
  if (rubric.shape && !matchesShape(points, rubric.shape)) return 'shape';
  return 'met';
}

/** The pegs of a band that meets the rubric, searched among axis-anchored figures; null when the board cannot hold one. */
export function findBand(size: number, rubric: GeoboardRubric): Lattice[] | null {
  const top = size - 1;
  const bands: Lattice[][] = [];
  for (let a = 1; a <= top; a += 1) {
    for (let b = 1; b <= top; b += 1) {
      bands.push([{ x: 0, y: 0 }, { x: a, y: 0 }, { x: a, y: b }, { x: 0, y: b }]);
      bands.push([{ x: 0, y: 0 }, { x: a, y: 0 }, { x: 0, y: b }]);
      for (let skew = 0; a + skew <= top; skew += 1) {
        bands.push([{ x: 0, y: 0 }, { x: a, y: 0 }, { x: a + skew, y: b }, { x: skew, y: b }]);
        bands.push([{ x: 0, y: 0 }, { x: a, y: 0 }, { x: skew, y: b }]);
      }
    }
  }
  return bands.find((band) => isSimplePolygon(band) && checkBand(band, rubric) === 'met') ?? null;
}
