#!/usr/bin/env bash
# Regenerates repo_map.md: directory tree + first 15 lines of every source file.
# Run from anywhere: npm run repo:map
#
# DETERMINISTIC for a committed tree. release-readiness regenerates this map
# and then requires a clean tree (git:diff-check), so any nondeterminism here
# false-fails the release gate:
#   - the stamp is the last COMMIT date (git log -1 --format=%cs), never
#     wall-clock — a run on a later calendar day must not dirty the tree;
#   - enumeration is git-aware (tracked + untracked-not-gitignored via
#     `git ls-files`), never a plain `find` — gitignored run artifacts
#     (e.g. coursegen/runs/, which release-readiness itself creates) must
#     never leak into the map;
#   - sorting is LC_ALL=C so byte order is locale-independent.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="repo_map.md"
# Excluded by NAME at any depth (covers tracked-but-noise dirs like .vscode;
# gitignored dirs such as node_modules/dist are already absent from git ls-files):
EXCLUDE_NAMES=(.git node_modules dist coverage .claude .agents .codex LEGAL .vscode .branches .temp duckdb)
# Excluded by exact PATH from root:
EXCLUDE_PATHS=(.github/skills database/supabase)
INCLUDE_EXT=(ts tsx js jsx json sql md sh yml yaml css html toml)

# Last commit date (YYYY-MM-DD). Strict on purpose: outside a git history the
# map has no deterministic stamp, so fail loudly instead of silently falling
# back to wall-clock and reintroducing the nondeterminism.
STAMP="$(git log -1 --format=%cs)"

NAME_RE=""
for d in "${EXCLUDE_NAMES[@]}"; do NAME_RE+="${NAME_RE:+|}${d//./[.]}"; done
PATH_RE=""
for p in "${EXCLUDE_PATHS[@]}"; do PATH_RE+="${PATH_RE:+|}${p//./[.]}"; done
EXCLUDE_RE="(^|/)(${NAME_RE})(/|\$)|^(${PATH_RE})(/|\$)"

EXT_RE=""
for e in "${INCLUDE_EXT[@]}"; do EXT_RE+="${EXT_RE:+|}${e}"; done

# Tracked files plus untracked-but-not-gitignored ones: work in progress shows
# up before it is committed (the §5 gate runs repo:map before the commit);
# gitignored artifacts never do.
ALL_FILES="$(git ls-files --cached --others --exclude-standard | LC_ALL=C sort -u | grep -Ev "$EXCLUDE_RE")"

{
  echo "# repo_map.md — LittleFounders Repository Map"
  echo
  echo "> AUTO-GENERATED by scripts/update-repo-map.sh on $STAMP (last commit date). Do not edit by hand."
  echo "> Tree + first 15 lines of each source file. Never paste this whole file into a prompt — search it."
  echo
  echo '## Directory tree'
  echo
  echo '```'
  printf '%s\n' "$ALL_FILES" \
    | awk -F/ '{ p=""; for(i=1;i<NF;i++){ p=p $i "/"; print p } }' \
    | LC_ALL=C sort -u \
    | awk -F/ '{ indent=""; for(i=1;i<=NF-2;i++) indent=indent "  "; print indent $(NF-1) "/" }'
  echo '```'
  echo
  echo '## File previews (first 15 lines)'

  printf '%s\n' "$ALL_FILES" | grep -E "[.](${EXT_RE})\$" | while IFS= read -r f; do
    case "$f" in
      repo_map.md|*package-lock.json) continue ;;
    esac
    echo
    echo "### $f"
    echo
    echo '```'
    head -n 15 "$f" 2>/dev/null || true
    echo '```'
  done || true
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
