const labels = [
 ['usable-money','Usable money','Dinero utilizable','Dinheiro utilizável'],
 ['financial-math','Financial arithmetic','Cálculos financieros','Cálculos financeiros'],
 ['goals-tradeoffs','Goals and choices','Metas y decisiones','Metas e escolhas'],
 ['income-work','Income and work','Ingresos y trabajo','Renda e trabalho'],
 ['spending-patterns','Spending patterns','Patrones de gasto','Padrões de gasto'],
 ['cashflow-budget','Budget and timing','Presupuesto y fechas','Orçamento e datas'],
 ['accounts-records','Accounts and records','Cuentas y registros','Contas e registros'],
 ['payments-digital','Payments and security','Pagos y seguridad','Pagamentos e segurança'],
 ['purchase-decisions','Purchase decisions','Decisiones de compra','Decisões de compra'],
 ['saving-resilience','Saving and resilience','Ahorro y preparación','Poupança e preparo'],
 ['time-inflation','Time and inflation','Tiempo e inflación','Tempo e inflação'],
 ['credit-mechanics','How credit works','Cómo funciona el crédito','Como funciona o crédito'],
 ['credit-products','Credit products','Productos de crédito','Produtos de crédito'],
 ['debt-recovery','Managing debt','Manejo de deudas','Gestão de dívidas'],
 ['credit-records','Credit records','Historial crediticio','Histórico de crédito'],
 ['insurance-risk','Risk and protection','Riesgos y protección','Riscos e proteção'],
 ['investing-foundations','Investment foundations','Bases de inversión','Bases de investimento'],
 ['investment-comparison','Comparing investments','Comparar inversiones','Comparar investimentos'],
 ['tax-public-systems','Taxes and public systems','Impuestos y sistemas públicos','Tributos e sistemas públicos'],
 ['retirement-future','Retirement and the future','Retiro y futuro','Aposentadoria e futuro'],
 ['housing-transport','Housing and transport','Vivienda y transporte','Moradia e transporte'],
 ['shared-finances','Shared finances','Finanzas compartidas','Finanças compartilhadas'],
 ['financial-landscape','The financial landscape','El entorno financiero','O ambiente financeiro'],
 ['integrated-decisions','Putting it together','Decisiones integradas','Decisões integradas'],
];
export const unitTitles = Object.fromEntries(labels.map(([id, en, es, pt]) => [id, { 'en-US': en, 'es-MX': es, 'pt-BR': pt }]));
