/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/fin1/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const FIN1_SEGMENTS = [] as const;
export const FIN1_RUBRICS = {} as const;
export const FIN1_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
