import type { HorizonteCopy } from '../boardTypes';

/*
 * fin1 board copy: F1.10 compound interest (`cmp*`, ages 10 and up), F2.11 time value (`tv*`) and F2.12 effective rate, card,
 * NPV and IRR (`ef*`, `cd*`, `np*`, `ir*`; ages 13 and up). Each string is native, not translated word for word. A string that
 * carries figures is `data` (the Copy Budget exempts it); the prose around the figures stays inside the body, option and action
 * limits. `$` is the generic currency sign.
 */
export const FIN1_COPY = {
  /* ── shared ── */
  showTable: { role: 'action', band: '10-12', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', band: '10-12', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  less: { role: 'action', band: '10-12', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  more: { role: 'action', band: '10-12', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  yearOne: { role: 'data', band: '10-12', 'en-US': '{n} year', 'es-MX': '{n} año', 'pt-BR': '{n} ano' },
  yearMany: { role: 'data', band: '10-12', 'en-US': '{n} years', 'es-MX': '{n} años', 'pt-BR': '{n} anos' },

  /* ── F1.10 compound interest ── */
  cmpPredictHeading: { role: 'heading', band: '10-12', 'en-US': 'Your prediction', 'es-MX': 'Tu predicción', 'pt-BR': 'Sua previsão' },
  cmpPredictHelp: { role: 'body', band: '10-12', 'en-US': 'Pick one before you slide.', 'es-MX': 'Elige una antes de mover los controles.', 'pt-BR': 'Escolha uma antes de mexer nos controles.' },
  cmpReveal: { role: 'action', band: '10-12', 'en-US': 'Reveal', 'es-MX': 'Revelar', 'pt-BR': 'Revelar' },
  cmpTryHeading: { role: 'heading', band: '10-12', 'en-US': 'Try the sliders', 'es-MX': 'Prueba los controles', 'pt-BR': 'Teste os controles' },
  cmpRate: { role: 'body', band: '10-12', 'en-US': 'Yearly rate', 'es-MX': 'Tasa anual', 'pt-BR': 'Taxa anual' },
  cmpYears: { role: 'body', band: '10-12', 'en-US': 'Years', 'es-MX': 'Años', 'pt-BR': 'Anos' },
  cmpChartHeading: { role: 'heading', band: '10-12', 'en-US': 'Growth of the deposit', 'es-MX': 'Crecimiento del depósito', 'pt-BR': 'Crescimento do depósito' },
  cmpLegendCompound: { role: 'data', band: '10-12', 'en-US': 'Compound', 'es-MX': 'Compuesto', 'pt-BR': 'Composto' },
  cmpLegendSimple: { role: 'data', band: '10-12', 'en-US': 'Simple', 'es-MX': 'Simple', 'pt-BR': 'Simples' },
  cmpChartLabel: {
    role: 'data', band: '10-12',
    'en-US': 'Growth chart. After {years} at {rate}, compound interest gives {compound} and simple interest gives {simple}.',
    'es-MX': 'Gráfica de crecimiento. Tras {years} al {rate}, el interés compuesto da {compound} y el simple da {simple}.',
    'pt-BR': 'Gráfico de crescimento. Após {years} a {rate}, os juros compostos dão {compound} e os simples dão {simple}.',
  },
  cmpStatus: {
    role: 'data', band: '10-12',
    'en-US': 'After {years} at {rate}: compound {compound}, simple {simple}.',
    'es-MX': 'Tras {years} al {rate}: compuesto {compound}, simple {simple}.',
    'pt-BR': 'Após {years} a {rate}: composto {compound}, simples {simple}.',
  },
  cmpChallenge: {
    role: 'data', band: '10-12',
    'en-US': 'Challenge: reach {amount} in {years} or less.',
    'es-MX': 'Reto: llega a {amount} en {years} o menos.',
    'pt-BR': 'Desafio: chegue a {amount} em {years} ou menos.',
  },
  cmpChallengeMet: { role: 'body', band: '10-12', 'en-US': 'You reached it.', 'es-MX': 'Lo lograste.', 'pt-BR': 'Você conseguiu.' },
  cmpChallengeOpen: { role: 'body', band: '10-12', 'en-US': 'Not reached yet.', 'es-MX': 'Aún no llegas.', 'pt-BR': 'Ainda não chegou.' },
  cmpOutcome: {
    role: 'data', band: '10-12',
    'en-US': 'At {rate} for {years}, {deposit} grows to {amount}.',
    'es-MX': 'Al {rate} por {years}, {deposit} se convierten en {amount}.',
    'pt-BR': 'A {rate} por {years}, {deposit} viram {amount}.',
  },
  cmpDoubling: {
    role: 'data', band: '10-12',
    'en-US': 'At {rate}, money doubles in about {years} years.',
    'es-MX': 'Al {rate}, el dinero se duplica en unos {years} años.',
    'pt-BR': 'A {rate}, o dinheiro dobra em cerca de {years} anos.',
  },
  cmpHintRight: { role: 'body', band: '10-12', 'en-US': 'Right. Your pick was the closest.', 'es-MX': 'Bien. Tu elección fue la más cercana.', 'pt-BR': 'Certo. Sua escolha foi a mais próxima.' },
  cmpHintSimple: {
    role: 'body', band: '10-12', 'en-US': 'Close to simple interest. Compounding adds more.',
    'es-MX': 'Cerca del interés simple. El compuesto suma más.', 'pt-BR': 'Perto dos juros simples. Os compostos somam mais.',
  },
  cmpHintShort: {
    role: 'body', band: '10-12', 'en-US': 'Too low. Interest earns interest too.',
    'es-MX': 'Muy bajo. El interés también gana interés.', 'pt-BR': 'Baixo demais. Os juros também rendem juros.',
  },
  cmpHintOver: {
    role: 'body', band: '10-12', 'en-US': 'Too high. It grows a lot, but not that much.',
    'es-MX': 'Muy alto. Crece mucho, pero no tanto.', 'pt-BR': 'Alto demais. Cresce muito, mas não tanto.',
  },
  cmpExplainLegend: { role: 'body', band: '10-12', 'en-US': 'Why does it grow faster each year?', 'es-MX': '¿Por qué crece más rápido cada año?', 'pt-BR': 'Por que cresce mais rápido a cada ano?' },
  'cmpExplain.interest-on-interest': { role: 'option', band: '10-12', 'en-US': 'Interest earns interest too', 'es-MX': 'El interés también gana interés', 'pt-BR': 'Os juros também rendem juros' },
  'cmpExplain.same-each-year': { role: 'option', band: '10-12', 'en-US': 'It adds the same each year', 'es-MX': 'Suma lo mismo cada año', 'pt-BR': 'Soma o mesmo a cada ano' },
  'cmpExplain.rate-grows': { role: 'option', band: '10-12', 'en-US': 'The rate rises every year', 'es-MX': 'La tasa sube cada año', 'pt-BR': 'A taxa sobe a cada ano' },
  'cmpExplain.deposit-grows': { role: 'option', band: '10-12', 'en-US': 'You deposit more each year', 'es-MX': 'Depositas más cada año', 'pt-BR': 'Você deposita mais a cada ano' },
  cmpTableCaption: { role: 'heading', band: '10-12', 'en-US': 'Value after each year', 'es-MX': 'Valor después de cada año', 'pt-BR': 'Valor após cada ano' },
  cmpColYear: { role: 'data', band: '10-12', 'en-US': 'Year', 'es-MX': 'Año', 'pt-BR': 'Ano' },
  cmpColCompound: { role: 'data', band: '10-12', 'en-US': 'Compound', 'es-MX': 'Compuesto', 'pt-BR': 'Composto' },
  cmpColSimple: { role: 'data', band: '10-12', 'en-US': 'Simple', 'es-MX': 'Simple', 'pt-BR': 'Simples' },
  cmpMet: { role: 'body', band: '10-12', 'en-US': 'You predicted, tested and explained it.', 'es-MX': 'Predijiste, probaste y explicaste.', 'pt-BR': 'Você previu, testou e explicou.' },
  cmpNot: { role: 'body', band: '10-12', 'en-US': 'Not yet. Check each part again.', 'es-MX': 'Aún no. Revisa cada parte.', 'pt-BR': 'Ainda não. Revise cada parte.' },

  /* ── F2.11 time value of money and annuities ── */
  tvYear: { role: 'data', band: '13-17', 'en-US': 'Year {n}', 'es-MX': 'Año {n}', 'pt-BR': 'Ano {n}' },
  tvYearZero: { role: 'data', band: '13-17', 'en-US': 'Today, year 0', 'es-MX': 'Hoy, año 0', 'pt-BR': 'Hoje, ano 0' },
  tvPrize: { role: 'option', band: '13-17', 'en-US': 'Prize {n}', 'es-MX': 'Premio {n}', 'pt-BR': 'Prêmio {n}' },
  tvBill: { role: 'option', band: '13-17', 'en-US': 'Bill {n}', 'es-MX': 'Cuenta {n}', 'pt-BR': 'Conta {n}' },
  tvPayment: { role: 'option', band: '13-17', 'en-US': 'Payment', 'es-MX': 'Pago', 'pt-BR': 'Pagamento' },
  tvTimeline: { role: 'heading', band: '13-17', 'en-US': 'Timeline', 'es-MX': 'Línea de tiempo', 'pt-BR': 'Linha do tempo' },
  tvRate: { role: 'data', band: '13-17', 'en-US': 'Rate: {rate} a year', 'es-MX': 'Tasa: {rate} al año', 'pt-BR': 'Taxa: {rate} ao ano' },
  tvFiguresToday: { role: 'body', band: '13-17', 'en-US': 'Each figure shows worth today.', 'es-MX': 'Cada cifra muestra el valor de hoy.', 'pt-BR': 'Cada valor mostra o valor de hoje.' },
  tvFiguresEnd: { role: 'data', band: '13-17', 'en-US': 'Each figure shows worth at year {n}.', 'es-MX': 'Cada cifra muestra el valor en el año {n}.', 'pt-BR': 'Cada valor mostra o valor no ano {n}.' },
  tvTotalToday: { role: 'data', band: '13-17', 'en-US': 'Total worth today: {amount}', 'es-MX': 'Valor total hoy: {amount}', 'pt-BR': 'Valor total hoje: {amount}' },
  tvTotalEnd: { role: 'data', band: '13-17', 'en-US': 'Total worth at year {n}: {amount}', 'es-MX': 'Valor total en el año {n}: {amount}', 'pt-BR': 'Valor total no ano {n}: {amount}' },
  tvTray: { role: 'heading', band: '13-17', 'en-US': 'Payments', 'es-MX': 'Pagos', 'pt-BR': 'Pagamentos' },
  tvDragOrder: { role: 'body', band: '13-17', 'en-US': 'Drag a payment to another year to swap.', 'es-MX': 'Arrastra un pago a otro año para cambiarlos.', 'pt-BR': 'Arraste um pagamento a outro ano para trocar.' },
  tvDragAnnuity: { role: 'body', band: '13-17', 'en-US': 'Drag each payment onto a year.', 'es-MX': 'Arrastra cada pago a un año.', 'pt-BR': 'Arraste cada pagamento para um ano.' },
  tvPlaced: { role: 'data', band: '13-17', 'en-US': 'Placed: {n} of {total}', 'es-MX': 'Colocados: {n} de {total}', 'pt-BR': 'Posicionados: {n} de {total}' },
  tvTrayName: { role: 'option', band: '13-17', 'en-US': 'Tray', 'es-MX': 'Bandeja', 'pt-BR': 'Bandeja' },
  tvAnswerToday: { role: 'body', band: '13-17', 'en-US': 'Worth today, in dollars', 'es-MX': 'Valor hoy, en dólares', 'pt-BR': 'Valor hoje, em dólares' },
  tvAnswerEnd: { role: 'data', band: '13-17', 'en-US': 'Worth at year {n}, in dollars', 'es-MX': 'Valor en el año {n}, en dólares', 'pt-BR': 'Valor no ano {n}, em dólares' },
  tvTableCaption: { role: 'heading', band: '13-17', 'en-US': 'Payments on the timeline', 'es-MX': 'Pagos en la línea de tiempo', 'pt-BR': 'Pagamentos na linha do tempo' },
  tvColYear: { role: 'data', band: '13-17', 'en-US': 'Year', 'es-MX': 'Año', 'pt-BR': 'Ano' },
  tvColPayment: { role: 'data', band: '13-17', 'en-US': 'Payment', 'es-MX': 'Pago', 'pt-BR': 'Pagamento' },
  tvColAmount: { role: 'data', band: '13-17', 'en-US': 'Amount', 'es-MX': 'Monto', 'pt-BR': 'Valor' },
  tvColWorthToday: { role: 'data', band: '13-17', 'en-US': 'Worth today', 'es-MX': 'Valor hoy', 'pt-BR': 'Valor hoje' },
  tvColWorthEnd: { role: 'data', band: '13-17', 'en-US': 'Worth at the end', 'es-MX': 'Valor al final', 'pt-BR': 'Valor no fim' },
  tvTotal: { role: 'data', band: '13-17', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  tvMetOrder: { role: 'body', band: '13-17', 'en-US': 'You ordered the payments and found the worth.', 'es-MX': 'Ordenaste los pagos y hallaste su valor.', 'pt-BR': 'Você ordenou os pagamentos e achou o valor.' },
  tvHintOrder: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check the order and the total.', 'es-MX': 'Aún no. Revisa el orden y el total.', 'pt-BR': 'Ainda não. Confira a ordem e o total.' },
  tvMetAnnuity: { role: 'body', band: '13-17', 'en-US': 'You timed the payments and found the worth.', 'es-MX': 'Ubicaste los pagos y hallaste su valor.', 'pt-BR': 'Você posicionou os pagamentos e achou o valor.' },
  tvHintAnnuity: { role: 'body', band: '13-17', 'en-US': 'Not yet. Check the years and the total.', 'es-MX': 'Aún no. Revisa los años y el total.', 'pt-BR': 'Ainda não. Confira os anos e o total.' },

  /* ── F2.12 effective rate ── */
  efNominal: {
    role: 'data', band: '13-17', 'en-US': 'Nominal {rate} a year, compounded {n} times',
    'es-MX': 'Nominal {rate} al año, capitalizada {n} veces', 'pt-BR': 'Nominal {rate} ao ano, capitalizada {n} vezes',
  },
  efStart: { role: 'data', band: '13-17', 'en-US': 'You start with {amount}.', 'es-MX': 'Empiezas con {amount}.', 'pt-BR': 'Você começa com {amount}.' },
  efPeriod: { role: 'body', band: '13-17', 'en-US': 'Compounding period', 'es-MX': 'Periodo de capitalización', 'pt-BR': 'Período de capitalização' },
  efPeriodValue: { role: 'data', band: '13-17', 'en-US': 'Period {n} of {m}', 'es-MX': 'Periodo {n} de {m}', 'pt-BR': 'Período {n} de {m}' },
  efBalance: { role: 'data', band: '13-17', 'en-US': 'Balance: {amount}', 'es-MX': 'Saldo: {amount}', 'pt-BR': 'Saldo: {amount}' },
  efGained: { role: 'data', band: '13-17', 'en-US': 'Gained so far: {amount}', 'es-MX': 'Ganado hasta ahora: {amount}', 'pt-BR': 'Ganho até agora: {amount}' },
  efChartLabel: {
    role: 'data', band: '13-17',
    'en-US': 'Chart of a balance that starts at {start}. After period {n} of {m} it is {balance}.',
    'es-MX': 'Gráfica de un saldo que empieza en {start}. Tras el periodo {n} de {m} es {balance}.',
    'pt-BR': 'Gráfico de um saldo que começa em {start}. Após o período {n} de {m} ele é {balance}.',
  },
  efTableCaption: { role: 'heading', band: '13-17', 'en-US': 'Balance after some periods', 'es-MX': 'Saldo tras algunos periodos', 'pt-BR': 'Saldo após alguns períodos' },
  efColPeriod: { role: 'data', band: '13-17', 'en-US': 'Period', 'es-MX': 'Periodo', 'pt-BR': 'Período' },
  efColBalance: { role: 'data', band: '13-17', 'en-US': 'Balance', 'es-MX': 'Saldo', 'pt-BR': 'Saldo' },
  efAnswer: { role: 'body', band: '13-17', 'en-US': 'Rate, in percent', 'es-MX': 'Tasa, en porcentaje', 'pt-BR': 'Taxa, em porcentagem' },
  efMet: { role: 'body', band: '13-17', 'en-US': 'You found the rate you really pay.', 'es-MX': 'Hallaste la tasa que de verdad pagas.', 'pt-BR': 'Você achou a taxa que realmente paga.' },
  efHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Compare the balance with the start.', 'es-MX': 'Aún no. Compara el saldo con el inicio.', 'pt-BR': 'Ainda não. Compare o saldo com o início.' },

  /* ── F2.12 credit card ── */
  cdOwed: { role: 'data', band: '13-17', 'en-US': 'You owe {amount} at {rate} a year.', 'es-MX': 'Debes {amount} al {rate} al año.', 'pt-BR': 'Você deve {amount} a {rate} ao ano.' },
  cdMonth: { role: 'body', band: '13-17', 'en-US': 'Month', 'es-MX': 'Mes', 'pt-BR': 'Mês' },
  cdMonthValue: { role: 'data', band: '13-17', 'en-US': 'Month {n}', 'es-MX': 'Mes {n}', 'pt-BR': 'Mês {n}' },
  cdNow: { role: 'data', band: '13-17', 'en-US': 'Owed now: {amount}', 'es-MX': 'Debes ahora: {amount}', 'pt-BR': 'Deve agora: {amount}' },
  cdInterest: { role: 'data', band: '13-17', 'en-US': 'Interest so far: {amount}', 'es-MX': 'Interés hasta ahora: {amount}', 'pt-BR': 'Juros até agora: {amount}' },
  cdPaid: { role: 'data', band: '13-17', 'en-US': 'Paid so far: {amount}', 'es-MX': 'Pagado hasta ahora: {amount}', 'pt-BR': 'Pago até agora: {amount}' },
  cdZero: { role: 'body', band: '13-17', 'en-US': 'The balance is zero.', 'es-MX': 'El saldo es cero.', 'pt-BR': 'O saldo é zero.' },
  cdChartLabel: {
    role: 'data', band: '13-17',
    'en-US': 'Chart of the balance owed each month. At month {n} you owe {balance} and have paid {interest} in interest.',
    'es-MX': 'Gráfica de lo que debes cada mes. En el mes {n} debes {balance} y has pagado {interest} de interés.',
    'pt-BR': 'Gráfico do que você deve a cada mês. No mês {n} você deve {balance} e já pagou {interest} de juros.',
  },
  cdLegendOwed: { role: 'data', band: '13-17', 'en-US': 'Owed', 'es-MX': 'Deuda', 'pt-BR': 'Dívida' },
  cdLegendInterest: { role: 'data', band: '13-17', 'en-US': 'Interest', 'es-MX': 'Interés', 'pt-BR': 'Juros' },
  cdTableCaption: { role: 'heading', band: '13-17', 'en-US': 'Balance every 12 months', 'es-MX': 'Saldo cada 12 meses', 'pt-BR': 'Saldo a cada 12 meses' },
  cdColMonth: { role: 'data', band: '13-17', 'en-US': 'Month', 'es-MX': 'Mes', 'pt-BR': 'Mês' },
  cdColOwed: { role: 'data', band: '13-17', 'en-US': 'Owed', 'es-MX': 'Deuda', 'pt-BR': 'Dívida' },
  cdColInterest: { role: 'data', band: '13-17', 'en-US': 'Interest so far', 'es-MX': 'Interés acumulado', 'pt-BR': 'Juros acumulados' },
  cdAnswerMonths: { role: 'body', band: '13-17', 'en-US': 'Months, as a whole number', 'es-MX': 'Meses, en número entero', 'pt-BR': 'Meses, em número inteiro' },
  cdAnswerInterest: { role: 'body', band: '13-17', 'en-US': 'Interest, in dollars', 'es-MX': 'Interés, en dólares', 'pt-BR': 'Juros, em dólares' },
  cdMetMonths: { role: 'body', band: '13-17', 'en-US': 'You found when the card is paid off.', 'es-MX': 'Hallaste cuándo se paga la tarjeta.', 'pt-BR': 'Você achou quando o cartão é quitado.' },
  cdHintMonths: { role: 'body', band: '13-17', 'en-US': 'Not yet. Scrub until the balance is zero.', 'es-MX': 'Aún no. Recorre hasta que el saldo sea cero.', 'pt-BR': 'Ainda não. Percorra até o saldo zerar.' },
  cdMetInterest: { role: 'body', band: '13-17', 'en-US': 'You found what the minimum really costs.', 'es-MX': 'Hallaste lo que de verdad cuesta el mínimo.', 'pt-BR': 'Você achou quanto o mínimo realmente custa.' },
  cdHintInterest: { role: 'body', band: '13-17', 'en-US': 'Not yet. Read the interest at the end.', 'es-MX': 'Aún no. Lee el interés al final.', 'pt-BR': 'Ainda não. Leia os juros no fim.' },

  /* ── F2.12 NPV ── */
  npRate: { role: 'body', band: '13-17', 'en-US': 'Discount rate', 'es-MX': 'Tasa de descuento', 'pt-BR': 'Taxa de desconto' },
  npTask: { role: 'data', band: '13-17', 'en-US': 'Rate for your answer: {rate}', 'es-MX': 'Tasa para tu respuesta: {rate}', 'pt-BR': 'Taxa para sua resposta: {rate}' },
  npOutlay: { role: 'data', band: '13-17', 'en-US': 'Paid today: {amount}', 'es-MX': 'Pagas hoy: {amount}', 'pt-BR': 'Você paga hoje: {amount}' },
  npYear: { role: 'data', band: '13-17', 'en-US': 'Year {n}', 'es-MX': 'Año {n}', 'pt-BR': 'Ano {n}' },
  npLegendCash: { role: 'data', band: '13-17', 'en-US': 'Payment', 'es-MX': 'Pago', 'pt-BR': 'Pagamento' },
  npLegendWorth: { role: 'data', band: '13-17', 'en-US': 'Worth today', 'es-MX': 'Valor hoy', 'pt-BR': 'Valor hoje' },
  npChartLabel: {
    role: 'data', band: '13-17',
    'en-US': 'Bars of each yearly payment and its worth today at {rate}: {list}.',
    'es-MX': 'Barras de cada pago anual y su valor hoy al {rate}: {list}.',
    'pt-BR': 'Barras de cada pagamento anual e do valor hoje a {rate}: {list}.',
  },
  npListItem: { role: 'data', band: '13-17', 'en-US': 'year {n}, {cash} is worth {worth}', 'es-MX': 'año {n}, {cash} valen {worth}', 'pt-BR': 'ano {n}, {cash} valem {worth}' },
  npTableCaption: { role: 'heading', band: '13-17', 'en-US': 'Each payment, today', 'es-MX': 'Cada pago, hoy', 'pt-BR': 'Cada pagamento, hoje' },
  npColYear: { role: 'data', band: '13-17', 'en-US': 'Year', 'es-MX': 'Año', 'pt-BR': 'Ano' },
  npColCash: { role: 'data', band: '13-17', 'en-US': 'Payment', 'es-MX': 'Pago', 'pt-BR': 'Pagamento' },
  npColWorth: { role: 'data', band: '13-17', 'en-US': 'Worth today', 'es-MX': 'Valor hoy', 'pt-BR': 'Valor hoje' },
  npAnswer: { role: 'body', band: '13-17', 'en-US': 'Net value today, in dollars', 'es-MX': 'Valor neto hoy, en dólares', 'pt-BR': 'Valor líquido hoje, em dólares' },
  npMet: { role: 'body', band: '13-17', 'en-US': 'You found the net value today.', 'es-MX': 'Hallaste el valor neto de hoy.', 'pt-BR': 'Você achou o valor líquido de hoje.' },
  npHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Add the worths, then subtract the cost.', 'es-MX': 'Aún no. Suma los valores y resta el costo.', 'pt-BR': 'Ainda não. Some os valores e subtraia o custo.' },

  /* ── F2.12 IRR ── */
  irDial: { role: 'body', band: '13-17', 'en-US': 'Trial rate', 'es-MX': 'Tasa de prueba', 'pt-BR': 'Taxa de teste' },
  irHere: { role: 'data', band: '13-17', 'en-US': 'Net value at {rate}: {amount}', 'es-MX': 'Valor neto al {rate}: {amount}', 'pt-BR': 'Valor líquido a {rate}: {amount}' },
  irAbove: { role: 'body', band: '13-17', 'en-US': 'The value is above zero.', 'es-MX': 'El valor está sobre cero.', 'pt-BR': 'O valor está acima de zero.' },
  irBelow: { role: 'body', band: '13-17', 'en-US': 'The value is below zero.', 'es-MX': 'El valor está bajo cero.', 'pt-BR': 'O valor está abaixo de zero.' },
  irAt: { role: 'body', band: '13-17', 'en-US': 'The value is exactly zero.', 'es-MX': 'El valor es justo cero.', 'pt-BR': 'O valor é exatamente zero.' },
  irChartLabel: {
    role: 'data', band: '13-17',
    'en-US': 'Curve of the net value at each rate. At {rate} the net value is {amount}.',
    'es-MX': 'Curva del valor neto con cada tasa. Al {rate} el valor neto es {amount}.',
    'pt-BR': 'Curva do valor líquido em cada taxa. A {rate} o valor líquido é {amount}.',
  },
  irTableCaption: { role: 'heading', band: '13-17', 'en-US': 'Net value at some rates', 'es-MX': 'Valor neto con algunas tasas', 'pt-BR': 'Valor líquido em algumas taxas' },
  irColRate: { role: 'data', band: '13-17', 'en-US': 'Rate', 'es-MX': 'Tasa', 'pt-BR': 'Taxa' },
  irColValue: { role: 'data', band: '13-17', 'en-US': 'Net value', 'es-MX': 'Valor neto', 'pt-BR': 'Valor líquido' },
  irAnswer: { role: 'body', band: '13-17', 'en-US': 'Break-even rate, in percent', 'es-MX': 'Tasa de equilibrio, en porcentaje', 'pt-BR': 'Taxa de equilíbrio, em porcentagem' },
  irMet: { role: 'body', band: '13-17', 'en-US': 'You found the rate where value is zero.', 'es-MX': 'Hallaste la tasa donde el valor es cero.', 'pt-BR': 'Você achou a taxa em que o valor é zero.' },
  irHint: { role: 'body', band: '13-17', 'en-US': 'Not yet. Slide until the value reaches zero.', 'es-MX': 'Aún no. Mueve hasta que el valor llegue a cero.', 'pt-BR': 'Ainda não. Mexa até o valor chegar a zero.' },
} as const satisfies HorizonteCopy;
