import type { HorizonteCopy } from '../boardTypes';

/* Written to the strictest budget (ages 6-9) so one entry serves both bands; slots are {name}. */
export const NUM_B_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  answerHeading: { role: 'heading', 'en-US': 'Your answer', 'es-MX': 'Tu respuesta', 'pt-BR': 'Sua resposta' },
  fractionHeading: { role: 'heading', 'en-US': 'Write the fraction', 'es-MX': 'Escribe la fracción', 'pt-BR': 'Escreva a fração' },
  yes: { role: 'data', 'en-US': 'Yes', 'es-MX': 'Sí', 'pt-BR': 'Sim' },
  no: { role: 'data', 'en-US': 'No', 'es-MX': 'No', 'pt-BR': 'Não' },
  colItem: { role: 'data', 'en-US': 'Item', 'es-MX': 'Elemento', 'pt-BR': 'Item' },
  colValue: { role: 'data', 'en-US': 'Value', 'es-MX': 'Valor', 'pt-BR': 'Valor' },
  colPart: { role: 'data', 'en-US': 'Part', 'es-MX': 'Parte', 'pt-BR': 'Parte' },
  colParts: { role: 'data', 'en-US': 'Parts', 'es-MX': 'Partes', 'pt-BR': 'Partes' },
  colShaded: { role: 'data', 'en-US': 'Shaded', 'es-MX': 'Sombreadas', 'pt-BR': 'Pintadas' },
  total: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },

  arrayLabel: { role: 'data', 'en-US': 'Rows of dots', 'es-MX': 'Filas de puntos', 'pt-BR': 'Fileiras de pontos' },
  arrayRow: { role: 'data', 'en-US': 'Row {n}', 'es-MX': 'Fila {n}', 'pt-BR': 'Fileira {n}' },
  rowDots: { role: 'data', 'en-US': '{n} dots', 'es-MX': '{n} puntos', 'pt-BR': '{n} pontos' },
  arrayFacts: {
    role: 'data', 'en-US': '{rows} rows of {columns} dots. Counted rows: {counted}. Dots so far: {dots}.',
    'es-MX': '{rows} filas de {columns} puntos. Filas contadas: {counted}. Puntos hasta ahora: {dots}.',
    'pt-BR': '{rows} fileiras de {columns} pontos. Fileiras contadas: {counted}. Pontos até agora: {dots}.',
  },
  totalDots: { role: 'body', 'en-US': 'How many dots in all?', 'es-MX': '¿Cuántos puntos hay en total?', 'pt-BR': 'Quantos pontos há no total?' },
  arrayCaption: { role: 'heading', 'en-US': 'Dots in each row', 'es-MX': 'Puntos en cada fila', 'pt-BR': 'Pontos em cada fileira' },
  colRow: { role: 'data', 'en-US': 'Row', 'es-MX': 'Fila', 'pt-BR': 'Fileira' },
  colDots: { role: 'data', 'en-US': 'Dots', 'es-MX': 'Puntos', 'pt-BR': 'Pontos' },
  colCounted: { role: 'data', 'en-US': 'Counted', 'es-MX': 'Contada', 'pt-BR': 'Contada' },
  metArray: { role: 'body', 'en-US': 'You found the total of equal rows.', 'es-MX': 'Hallaste el total de filas iguales.', 'pt-BR': 'Você achou o total de fileiras iguais.' },
  hintArray: { role: 'body', 'en-US': 'Not yet. Count the dots in one row.', 'es-MX': 'Aún no. Cuenta los puntos de una fila.', 'pt-BR': 'Ainda não. Conte os pontos de uma fileira.' },

  boxLabel: { role: 'data', 'en-US': 'Multiplication box', 'es-MX': 'Caja de multiplicar', 'pt-BR': 'Caixa de multiplicar' },
  cutHeading: { role: 'heading', 'en-US': 'Where to cut', 'es-MX': 'Dónde cortar', 'pt-BR': 'Onde cortar' },
  cutChip: { role: 'option', 'en-US': 'Cut the side', 'es-MX': 'Corta el lado', 'pt-BR': 'Corte o lado' },
  cutAt: { role: 'option', 'en-US': 'Cut at {n}', 'es-MX': 'Corta en {n}', 'pt-BR': 'Corte em {n}' },
  cutFirst: { role: 'body', 'en-US': 'Cut the side first.', 'es-MX': 'Primero corta el lado.', 'pt-BR': 'Primeiro corte o lado.' },
  boxFacts: {
    role: 'data', 'en-US': 'Side {across} cut into {a} and {b}. Height {down}.',
    'es-MX': 'Lado {across} cortado en {a} y {b}. Altura {down}.', 'pt-BR': 'Lado {across} cortado em {a} e {b}. Altura {down}.',
  },
  boxFactsUncut: {
    role: 'data', 'en-US': 'Side {across} not cut yet. Height {down}.',
    'es-MX': 'Lado {across} sin cortar. Altura {down}.', 'pt-BR': 'Lado {across} ainda sem corte. Altura {down}.',
  },
  leftBox: { role: 'body', 'en-US': 'Left box: {a} × {b}', 'es-MX': 'Caja izquierda: {a} × {b}', 'pt-BR': 'Caixa esquerda: {a} × {b}' },
  rightBox: { role: 'body', 'en-US': 'Right box: {a} × {b}', 'es-MX': 'Caja derecha: {a} × {b}', 'pt-BR': 'Caixa direita: {a} × {b}' },
  boxTotal: { role: 'body', 'en-US': 'Total of both boxes', 'es-MX': 'Total de las dos cajas', 'pt-BR': 'Total das duas caixas' },
  boxCaption: { role: 'heading', 'en-US': 'Parts of the box', 'es-MX': 'Partes de la caja', 'pt-BR': 'Partes da caixa' },
  colWidth: { role: 'data', 'en-US': 'Width', 'es-MX': 'Ancho', 'pt-BR': 'Largura' },
  colHeight: { role: 'data', 'en-US': 'Height', 'es-MX': 'Alto', 'pt-BR': 'Altura' },
  colArea: { role: 'data', 'en-US': 'Your area', 'es-MX': 'Tu área', 'pt-BR': 'Sua área' },
  leftName: { role: 'data', 'en-US': 'Left box', 'es-MX': 'Caja izquierda', 'pt-BR': 'Caixa esquerda' },
  rightName: { role: 'data', 'en-US': 'Right box', 'es-MX': 'Caja derecha', 'pt-BR': 'Caixa direita' },
  wholeBox: { role: 'data', 'en-US': 'Whole box', 'es-MX': 'Caja entera', 'pt-BR': 'Caixa inteira' },
  metBox: { role: 'body', 'en-US': 'You cut the side and added the boxes.', 'es-MX': 'Cortaste el lado y sumaste las cajas.', 'pt-BR': 'Você cortou o lado e somou as caixas.' },
  hintBox: { role: 'body', 'en-US': 'Not yet. Multiply each box, then add.', 'es-MX': 'Aún no. Multiplica cada caja y suma.', 'pt-BR': 'Ainda não. Multiplique cada caixa e some.' },

  divLabel: { role: 'data', 'en-US': 'Rectangle with a missing side', 'es-MX': 'Rectángulo con un lado que falta', 'pt-BR': 'Retângulo com um lado faltando' },
  divFacts: {
    role: 'data', 'en-US': 'Area {dividend}. Known side {divisor}. Area left: {left}.',
    'es-MX': 'Área {dividend}. Lado conocido {divisor}. Área restante: {left}.', 'pt-BR': 'Área {dividend}. Lado conhecido {divisor}. Área restante: {left}.',
  },
  firstPart: { role: 'body', 'en-US': 'First part of the side', 'es-MX': 'Primera parte del lado', 'pt-BR': 'Primeira parte do lado' },
  secondPart: { role: 'body', 'en-US': 'Second part of the side', 'es-MX': 'Segunda parte del lado', 'pt-BR': 'Segunda parte do lado' },
  wholeSide: { role: 'body', 'en-US': 'The whole side', 'es-MX': 'El lado completo', 'pt-BR': 'O lado completo' },
  divCaption: { role: 'heading', 'en-US': 'Rectangle and its parts', 'es-MX': 'Rectángulo y sus partes', 'pt-BR': 'Retângulo e suas partes' },
  areaItem: { role: 'data', 'en-US': 'Area', 'es-MX': 'Área', 'pt-BR': 'Área' },
  knownSide: { role: 'data', 'en-US': 'Known side', 'es-MX': 'Lado conocido', 'pt-BR': 'Lado conhecido' },
  firstArea: { role: 'data', 'en-US': 'Area of the first part', 'es-MX': 'Área de la primera parte', 'pt-BR': 'Área da primeira parte' },
  areaLeft: { role: 'data', 'en-US': 'Area left', 'es-MX': 'Área restante', 'pt-BR': 'Área restante' },
  metDiv: { role: 'body', 'en-US': 'You cut the area and found the side.', 'es-MX': 'Cortaste el área y hallaste el lado.', 'pt-BR': 'Você cortou a área e achou o lado.' },
  hintDiv: { role: 'body', 'en-US': 'Not yet. Take the area away in parts.', 'es-MX': 'Aún no. Quita el área por partes.', 'pt-BR': 'Ainda não. Tire a área por partes.' },

  lineLabel: { role: 'data', 'en-US': 'Double number line', 'es-MX': 'Recta numérica doble', 'pt-BR': 'Reta numérica dupla' },
  step: { role: 'data', 'en-US': 'Step {n}', 'es-MX': 'Paso {n}', 'pt-BR': 'Passo {n}' },
  markHeading: { role: 'heading', 'en-US': 'Count the steps', 'es-MX': 'Cuenta los pasos', 'pt-BR': 'Conte os passos' },
  markerChip: { role: 'option', 'en-US': 'Move the marker', 'es-MX': 'Mueve el marcador', 'pt-BR': 'Mova o marcador' },
  stepOption: { role: 'option', 'en-US': 'To step {n}', 'es-MX': 'Al paso {n}', 'pt-BR': 'Ao passo {n}' },
  lineFacts: {
    role: 'data', 'en-US': '{a} {unitA} match {b} {unitB}. Given: {given} {givenUnit}.',
    'es-MX': '{a} {unitA} equivalen a {b} {unitB}. Dado: {given} {givenUnit}.', 'pt-BR': '{a} {unitA} equivalem a {b} {unitB}. Dado: {given} {givenUnit}.',
  },
  markerAt: {
    role: 'data', 'en-US': 'Marker at step {n}: {value} {unit}.',
    'es-MX': 'Marcador en el paso {n}: {value} {unit}.', 'pt-BR': 'Marcador no passo {n}: {value} {unit}.',
  },
  markerNone: { role: 'data', 'en-US': 'Marker not placed yet.', 'es-MX': 'Marcador sin colocar.', 'pt-BR': 'Marcador ainda não colocado.' },
  quantityOf: { role: 'body', 'en-US': 'Number of {unit}', 'es-MX': 'Cantidad de {unit}', 'pt-BR': 'Quantidade de {unit}' },
  lineCaption: { role: 'heading', 'en-US': 'Pairs on the two lines', 'es-MX': 'Pares en las dos rectas', 'pt-BR': 'Pares nas duas retas' },
  colStep: { role: 'data', 'en-US': 'Step', 'es-MX': 'Paso', 'pt-BR': 'Passo' },
  metLine: { role: 'body', 'en-US': 'You scaled both lines by the same steps.', 'es-MX': 'Escalaste las dos rectas con los mismos pasos.', 'pt-BR': 'Você escalou as duas retas com os mesmos passos.' },
  hintLine: { role: 'body', 'en-US': 'Not yet. Count the steps on the given line.', 'es-MX': 'Aún no. Cuenta los pasos de la recta dada.', 'pt-BR': 'Ainda não. Conte os passos da reta dada.' },

  tapeLabel: { role: 'data', 'en-US': 'Ratio tape', 'es-MX': 'Cinta de razón', 'pt-BR': 'Fita de razão' },
  partA: { role: 'data', 'en-US': 'Part A', 'es-MX': 'Parte A', 'pt-BR': 'Parte A' },
  partB: { role: 'data', 'en-US': 'Part B', 'es-MX': 'Parte B', 'pt-BR': 'Parte B' },
  wholeName: { role: 'data', 'en-US': 'Whole', 'es-MX': 'Todo', 'pt-BR': 'Todo' },
  tapeFacts: {
    role: 'data', 'en-US': '{whole} {unit} in {boxes} equal boxes. Part A has {a} boxes. Part B has {b} boxes.',
    'es-MX': '{whole} {unit} en {boxes} cajas iguales. La parte A tiene {a} cajas. La parte B tiene {b} cajas.',
    'pt-BR': '{whole} {unit} em {boxes} caixas iguais. A parte A tem {a} caixas. A parte B tem {b} caixas.',
  },
  checkHeading: { role: 'heading', 'en-US': 'Check one box', 'es-MX': 'Revisa una caja', 'pt-BR': 'Confira uma caixa' },
  boxValue: { role: 'body', 'en-US': 'Value of one box', 'es-MX': 'Valor de una caja', 'pt-BR': 'Valor de uma caixa' },
  boxCheck: { role: 'data', 'en-US': '{boxes} × {value} = {product}.', 'es-MX': '{boxes} × {value} = {product}.', 'pt-BR': '{boxes} × {value} = {product}.' },
  boxMatch: { role: 'data', 'en-US': 'Matches the whole.', 'es-MX': 'Coincide con el total.', 'pt-BR': 'Coincide com o total.' },
  boxMiss: { role: 'data', 'en-US': 'Does not match the whole.', 'es-MX': 'No coincide con el total.', 'pt-BR': 'Não coincide com o total.' },
  askA: { role: 'body', 'en-US': 'Value of part A', 'es-MX': 'Valor de la parte A', 'pt-BR': 'Valor da parte A' },
  askB: { role: 'body', 'en-US': 'Value of part B', 'es-MX': 'Valor de la parte B', 'pt-BR': 'Valor da parte B' },
  tapeCaption: { role: 'heading', 'en-US': 'Parts of the tape', 'es-MX': 'Partes de la cinta', 'pt-BR': 'Partes da fita' },
  colBoxes: { role: 'data', 'en-US': 'Boxes', 'es-MX': 'Cajas', 'pt-BR': 'Caixas' },
  metTape: { role: 'body', 'en-US': 'You shared the whole into equal boxes.', 'es-MX': 'Repartiste el total en cajas iguales.', 'pt-BR': 'Você dividiu o total em caixas iguais.' },
  hintTape: { role: 'body', 'en-US': 'Not yet. Find the value of one box.', 'es-MX': 'Aún no. Halla el valor de una caja.', 'pt-BR': 'Ainda não. Ache o valor de uma caixa.' },
  unitCoins: { role: 'data', 'en-US': 'coins', 'es-MX': 'monedas', 'pt-BR': 'moedas' },
  unitPencils: { role: 'data', 'en-US': 'pencils', 'es-MX': 'lápices', 'pt-BR': 'lápis' },
  unitTickets: { role: 'data', 'en-US': 'tickets', 'es-MX': 'boletos', 'pt-BR': 'ingressos' },
  unitCups: { role: 'data', 'en-US': 'cups', 'es-MX': 'tazas', 'pt-BR': 'copos' },
  unitMinutes: { role: 'data', 'en-US': 'minutes', 'es-MX': 'minutos', 'pt-BR': 'minutos' },
  unitPages: { role: 'data', 'en-US': 'pages', 'es-MX': 'páginas', 'pt-BR': 'páginas' },
  unitStickers: { role: 'data', 'en-US': 'stickers', 'es-MX': 'calcomanías', 'pt-BR': 'figurinhas' },
  unitBoxes: { role: 'data', 'en-US': 'boxes', 'es-MX': 'cajas', 'pt-BR': 'caixas' },

  wallLabel: { role: 'data', 'en-US': 'Fraction wall', 'es-MX': 'Muro de fracciones', 'pt-BR': 'Muro de frações' },
  givenRow: { role: 'data', 'en-US': 'Given: {name}', 'es-MX': 'Dada: {name}', 'pt-BR': 'Dada: {name}' },
  targetRow: { role: 'data', 'en-US': 'Wall of {n} parts', 'es-MX': 'Muro de {n} partes', 'pt-BR': 'Muro de {n} partes' },
  shadeHeading: { role: 'heading', 'en-US': 'Shade the wall', 'es-MX': 'Sombrea el muro', 'pt-BR': 'Pinte o muro' },
  shadeChip: { role: 'option', 'en-US': 'Shade to here', 'es-MX': 'Sombrea hasta aquí', 'pt-BR': 'Pinte até aqui' },
  shadeTo: { role: 'option', 'en-US': 'Shade to part {n}', 'es-MX': 'Sombrea hasta la parte {n}', 'pt-BR': 'Pinte até a parte {n}' },
  shadeNone: { role: 'option', 'en-US': 'Clear the shading', 'es-MX': 'Quita el sombreado', 'pt-BR': 'Limpe a pintura' },
  partOf: { role: 'data', 'en-US': 'Part {n} of {d}', 'es-MX': 'Parte {n} de {d}', 'pt-BR': 'Parte {n} de {d}' },
  wallFacts: {
    role: 'data', 'en-US': 'Given {name}. Wall of {d} parts. Shaded: {k} of {d}.',
    'es-MX': 'Dada {name}. Muro de {d} partes. Sombreadas: {k} de {d}.', 'pt-BR': 'Dada {name}. Muro de {d} partes. Pintadas: {k} de {d}.',
  },
  wallCaption: { role: 'heading', 'en-US': 'Rows of the wall', 'es-MX': 'Filas del muro', 'pt-BR': 'Fileiras do muro' },
  rowGiven: { role: 'data', 'en-US': 'Given', 'es-MX': 'Dada', 'pt-BR': 'Dada' },
  rowYours: { role: 'data', 'en-US': 'Yours', 'es-MX': 'Tuya', 'pt-BR': 'Sua' },
  metWall: { role: 'body', 'en-US': 'You found the same amount in more parts.', 'es-MX': 'Hallaste la misma cantidad en más partes.', 'pt-BR': 'Você achou a mesma quantidade em mais partes.' },
  hintWall: { role: 'body', 'en-US': 'Not yet. Match the length of the given row.', 'es-MX': 'Aún no. Iguala el largo de la fila dada.', 'pt-BR': 'Ainda não. Iguale o comprimento da fileira dada.' },

  barsLabel: { role: 'data', 'en-US': 'Two fraction bars', 'es-MX': 'Dos barras de fracciones', 'pt-BR': 'Duas barras de frações' },
  leftBar: { role: 'data', 'en-US': 'First: {name}', 'es-MX': 'Primera: {name}', 'pt-BR': 'Primeira: {name}' },
  rightBar: { role: 'data', 'en-US': 'Second: {name}', 'es-MX': 'Segunda: {name}', 'pt-BR': 'Segunda: {name}' },
  commonOn: { role: 'action', 'en-US': 'Show common parts', 'es-MX': 'Mostrar partes comunes', 'pt-BR': 'Mostrar partes comuns' },
  commonOff: { role: 'action', 'en-US': 'Hide common parts', 'es-MX': 'Ocultar partes comunes', 'pt-BR': 'Ocultar partes comuns' },
  addFacts: { role: 'data', 'en-US': 'Add {left} and {right}.', 'es-MX': 'Suma {left} y {right}.', 'pt-BR': 'Some {left} e {right}.' },
  subtractFacts: { role: 'data', 'en-US': 'Take {right} from {left}.', 'es-MX': 'Quita {right} de {left}.', 'pt-BR': 'Tire {right} de {left}.' },
  commonFacts: { role: 'data', 'en-US': 'Cut in {l} parts: {x} and {y}.', 'es-MX': 'Cortadas en {l} partes: {x} y {y}.', 'pt-BR': 'Cortadas em {l} partes: {x} e {y}.' },
  numerator: { role: 'body', 'en-US': 'Top number', 'es-MX': 'Número de arriba', 'pt-BR': 'Número de cima' },
  denominator: { role: 'body', 'en-US': 'Bottom number', 'es-MX': 'Número de abajo', 'pt-BR': 'Número de baixo' },
  barsCaption: { role: 'heading', 'en-US': 'Bars side by side', 'es-MX': 'Barras lado a lado', 'pt-BR': 'Barras lado a lado' },
  colBar: { role: 'data', 'en-US': 'Bar', 'es-MX': 'Barra', 'pt-BR': 'Barra' },
  rowFirst: { role: 'data', 'en-US': 'First', 'es-MX': 'Primera', 'pt-BR': 'Primeira' },
  rowSecond: { role: 'data', 'en-US': 'Second', 'es-MX': 'Segunda', 'pt-BR': 'Segunda' },
  rowFirstCommon: { role: 'data', 'en-US': 'First, common parts', 'es-MX': 'Primera, partes comunes', 'pt-BR': 'Primeira, partes comuns' },
  rowSecondCommon: { role: 'data', 'en-US': 'Second, common parts', 'es-MX': 'Segunda, partes comunes', 'pt-BR': 'Segunda, partes comuns' },
  metAdd: { role: 'body', 'en-US': 'You added with matching parts.', 'es-MX': 'Sumaste con partes iguales.', 'pt-BR': 'Você somou com partes iguais.' },
  metSubtract: { role: 'body', 'en-US': 'You took away with matching parts.', 'es-MX': 'Quitaste con partes iguales.', 'pt-BR': 'Você tirou com partes iguais.' },
  hintBars: { role: 'body', 'en-US': 'Not yet. Cut both bars into the same parts.', 'es-MX': 'Aún no. Corta las dos barras en partes iguales.', 'pt-BR': 'Ainda não. Corte as duas barras em partes iguais.' },

  gridLabel: { role: 'data', 'en-US': 'Fraction product grid', 'es-MX': 'Cuadrícula del producto', 'pt-BR': 'Grade do produto' },
  gridColumn: { role: 'data', 'en-US': 'Column {n}', 'es-MX': 'Columna {n}', 'pt-BR': 'Coluna {n}' },
  gridRow: { role: 'data', 'en-US': 'Row {n}', 'es-MX': 'Fila {n}', 'pt-BR': 'Linha {n}' },
  gridFacts: {
    role: 'data', 'en-US': 'Grid: {c} columns, {r} rows. Shaded columns: {sc} of {c}. Shaded rows: {sr} of {r}.',
    'es-MX': 'Cuadrícula: {c} columnas, {r} filas. Columnas sombreadas: {sc} de {c}. Filas sombreadas: {sr} de {r}.',
    'pt-BR': 'Grade: {c} colunas, {r} linhas. Colunas pintadas: {sc} de {c}. Linhas pintadas: {sr} de {r}.',
  },
  gridTask: {
    role: 'data', 'en-US': 'Shade {left} of the columns and {right} of the rows.',
    'es-MX': 'Sombrea {left} de las columnas y {right} de las filas.', 'pt-BR': 'Pinte {left} das colunas e {right} das linhas.',
  },
  productCaption: { role: 'heading', 'en-US': 'Parts of the grid', 'es-MX': 'Partes de la cuadrícula', 'pt-BR': 'Partes da grade' },
  columnsItem: { role: 'data', 'en-US': 'Columns', 'es-MX': 'Columnas', 'pt-BR': 'Colunas' },
  shadedColumnsItem: { role: 'data', 'en-US': 'Shaded columns', 'es-MX': 'Columnas sombreadas', 'pt-BR': 'Colunas pintadas' },
  rowsItem: { role: 'data', 'en-US': 'Rows', 'es-MX': 'Filas', 'pt-BR': 'Linhas' },
  shadedRowsItem: { role: 'data', 'en-US': 'Shaded rows', 'es-MX': 'Filas sombreadas', 'pt-BR': 'Linhas pintadas' },
  cellsItem: { role: 'data', 'en-US': 'Cells in all', 'es-MX': 'Celdas en total', 'pt-BR': 'Células no total' },
  metProduct: { role: 'body', 'en-US': 'You found a part of a part.', 'es-MX': 'Hallaste una parte de una parte.', 'pt-BR': 'Você achou uma parte de uma parte.' },
  hintProduct: { role: 'body', 'en-US': 'Not yet. Count the cells shaded twice.', 'es-MX': 'Aún no. Cuenta las celdas sombreadas dos veces.', 'pt-BR': 'Ainda não. Conte as células pintadas duas vezes.' },

  measureLabel: { role: 'data', 'en-US': 'Measuring bar', 'es-MX': 'Barra de medida', 'pt-BR': 'Barra de medida' },
  tilesHeading: { role: 'heading', 'en-US': 'Lay the tiles', 'es-MX': 'Pon las piezas', 'pt-BR': 'Coloque as peças' },
  addTile: { role: 'action', 'en-US': 'Add a tile', 'es-MX': 'Agrega una pieza', 'pt-BR': 'Adicione uma peça' },
  removeTile: { role: 'action', 'en-US': 'Remove a tile', 'es-MX': 'Quita una pieza', 'pt-BR': 'Tire uma peça' },
  lengthRow: { role: 'data', 'en-US': 'Length: {name}', 'es-MX': 'Largo: {name}', 'pt-BR': 'Comprimento: {name}' },
  tileRow: { role: 'data', 'en-US': 'Tile: {name}', 'es-MX': 'Pieza: {name}', 'pt-BR': 'Peça: {name}' },
  measureFacts: {
    role: 'data', 'en-US': 'Measure {left} with tiles of {right}. Tiles laid: {t}.',
    'es-MX': 'Mide {left} con piezas de {right}. Piezas puestas: {t}.', 'pt-BR': 'Meça {left} com peças de {right}. Peças colocadas: {t}.',
  },
  measureCaption: { role: 'heading', 'en-US': 'Measuring with tiles', 'es-MX': 'Medir con piezas', 'pt-BR': 'Medir com peças' },
  lengthItem: { role: 'data', 'en-US': 'Length to measure', 'es-MX': 'Largo por medir', 'pt-BR': 'Comprimento a medir' },
  tileItem: { role: 'data', 'en-US': 'Tile length', 'es-MX': 'Largo de la pieza', 'pt-BR': 'Comprimento da peça' },
  tilesItem: { role: 'data', 'en-US': 'Tiles laid', 'es-MX': 'Piezas puestas', 'pt-BR': 'Peças colocadas' },
  metMeasure: { role: 'body', 'en-US': 'You measured with equal tiles.', 'es-MX': 'Mediste con piezas iguales.', 'pt-BR': 'Você mediu com peças iguais.' },
  hintMeasure: { role: 'body', 'en-US': 'Not yet. Count tiles, then the part left.', 'es-MX': 'Aún no. Cuenta las piezas y la parte que sobra.', 'pt-BR': 'Ainda não. Conte as peças e a parte que sobra.' },

  circlesLabel: { role: 'data', 'en-US': 'Fraction circles', 'es-MX': 'Círculos de fracciones', 'pt-BR': 'Círculos de frações' },
  circleWhole: { role: 'data', 'en-US': 'Whole circle, not cut', 'es-MX': 'Círculo entero, sin cortar', 'pt-BR': 'Círculo inteiro, sem cortes' },
  circleName: {
    role: 'data', 'en-US': 'Circle in {d} parts, {k} shaded', 'es-MX': 'Círculo en {d} partes, {k} sombreadas', 'pt-BR': 'Círculo em {d} partes, {k} pintadas',
  },
  circlePartOf: { role: 'data', 'en-US': '{circle}: part {n} of {d}', 'es-MX': '{circle}: parte {n} de {d}', 'pt-BR': '{circle}: parte {n} de {d}' },
  circleFirst: { role: 'data', 'en-US': 'First circle', 'es-MX': 'Primer círculo', 'pt-BR': 'Primeiro círculo' },
  circleSecond: { role: 'data', 'en-US': 'Second circle', 'es-MX': 'Segundo círculo', 'pt-BR': 'Segundo círculo' },
  circleWork: { role: 'data', 'en-US': 'Work circle', 'es-MX': 'Círculo de trabajo', 'pt-BR': 'Círculo de trabalho' },
  circleYours: { role: 'data', 'en-US': 'Your circle', 'es-MX': 'Tu círculo', 'pt-BR': 'Seu círculo' },
  circleLegend: { role: 'data', 'en-US': '{which}: {name}', 'es-MX': '{which}: {name}', 'pt-BR': '{which}: {name}' },
  circleCutHeading: { role: 'heading', 'en-US': 'Cut the circle', 'es-MX': 'Corta el círculo', 'pt-BR': 'Corte o círculo' },
  circleShadeHeading: { role: 'heading', 'en-US': 'Shade the circle', 'es-MX': 'Sombrea el círculo', 'pt-BR': 'Pinte o círculo' },
  circleMoreHeading: { role: 'heading', 'en-US': 'Which is more?', 'es-MX': '¿Cuál es más?', 'pt-BR': 'Qual é mais?' },
  cutInto: { role: 'action', 'en-US': 'Cut in {n}', 'es-MX': 'Corta en {n}', 'pt-BR': 'Corte em {n}' },
  shadeMore: { role: 'action', 'en-US': 'Shade one more', 'es-MX': 'Sombrea una más', 'pt-BR': 'Pinte mais uma' },
  shadeFewer: { role: 'action', 'en-US': 'Shade one less', 'es-MX': 'Sombrea una menos', 'pt-BR': 'Pinte uma a menos' },
  moreFirst: { role: 'action', 'en-US': 'First is more', 'es-MX': 'El primero es más', 'pt-BR': 'O primeiro é mais' },
  moreSecond: { role: 'action', 'en-US': 'Second is more', 'es-MX': 'El segundo es más', 'pt-BR': 'O segundo é mais' },
  circleShowFresh: {
    role: 'data', 'en-US': 'Show {name}. The circle is not cut yet.', 'es-MX': 'Muestra {name}. El círculo aún no está cortado.', 'pt-BR': 'Mostre {name}. O círculo ainda não foi cortado.',
  },
  circleShowFacts: {
    role: 'data', 'en-US': 'Show {name}. Cut in {d} parts. Shaded: {k} of {d}.',
    'es-MX': 'Muestra {name}. Cortado en {d} partes. Sombreadas: {k} de {d}.', 'pt-BR': 'Mostre {name}. Cortado em {d} partes. Pintadas: {k} de {d}.',
  },
  circleCompareFacts: {
    role: 'data', 'en-US': 'Circles cut in {d} parts. First: {a} shaded. Second: {b} shaded.',
    'es-MX': 'Círculos cortados en {d} partes. Primero: {a} sombreadas. Segundo: {b} sombreadas.',
    'pt-BR': 'Círculos cortados em {d} partes. Primeiro: {a} pintadas. Segundo: {b} pintadas.',
  },
  pickedFirst: { role: 'data', 'en-US': 'More: first circle.', 'es-MX': 'Más: primer círculo.', 'pt-BR': 'Mais: primeiro círculo.' },
  pickedSecond: { role: 'data', 'en-US': 'More: second circle.', 'es-MX': 'Más: segundo círculo.', 'pt-BR': 'Mais: segundo círculo.' },
  circleWorkFacts: {
    role: 'data', 'en-US': 'Work circle: {k} of {d} shaded.', 'es-MX': 'Círculo de trabajo: {k} de {d} sombreadas.', 'pt-BR': 'Círculo de trabalho: {k} de {d} pintadas.',
  },
  circlesCaption: { role: 'heading', 'en-US': 'Circles and their parts', 'es-MX': 'Círculos y sus partes', 'pt-BR': 'Círculos e suas partes' },
  metCircleShow: { role: 'body', 'en-US': 'You cut and shaded the circle.', 'es-MX': 'Cortaste y sombreaste el círculo.', 'pt-BR': 'Você cortou e pintou o círculo.' },
  hintCircleShow: {
    role: 'body', 'en-US': 'Not yet. Match the name: parts, then shaded.', 'es-MX': 'Aún no. Iguala el nombre: partes y sombreadas.', 'pt-BR': 'Ainda não. Iguale o nome: partes e pintadas.',
  },
  metCircleCompare: { role: 'body', 'en-US': 'You compared parts of the same size.', 'es-MX': 'Comparaste partes del mismo tamaño.', 'pt-BR': 'Você comparou partes do mesmo tamanho.' },
  hintCircleCompare: {
    role: 'body', 'en-US': 'Not yet. Look at which circle has more shaded.', 'es-MX': 'Aún no. Mira qué círculo tiene más sombreado.', 'pt-BR': 'Ainda não. Veja qual círculo tem mais pintado.',
  },
  metCircleAdd: { role: 'body', 'en-US': 'You joined parts of the same size.', 'es-MX': 'Juntaste partes del mismo tamaño.', 'pt-BR': 'Você juntou partes do mesmo tamanho.' },
  hintCircleAdd: {
    role: 'body', 'en-US': 'Not yet. Count the shaded parts in the work circle.', 'es-MX': 'Aún no. Cuenta las partes sombreadas del círculo de trabajo.',
    'pt-BR': 'Ainda não. Conte as partes pintadas do círculo de trabalho.',
  },
  metCircleSubtract: { role: 'body', 'en-US': 'You took away parts of the same size.', 'es-MX': 'Quitaste partes del mismo tamaño.', 'pt-BR': 'Você tirou partes do mesmo tamanho.' },
  hintCircleSubtract: {
    role: 'body', 'en-US': 'Not yet. Count the parts left in the work circle.', 'es-MX': 'Aún no. Cuenta las partes que quedan en el círculo de trabajo.',
    'pt-BR': 'Ainda não. Conte as partes que sobram no círculo de trabalho.',
  },
} as const satisfies HorizonteCopy;
