/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/num-b/scorer.ts. Do not edit: change the source and regenerate. */
import type { HorizonteScorer } from '../types.generated';

export const NUM_B_SCORERS: Readonly<Record<string, HorizonteScorer>> = {};
