/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/num-b/scorer.ts. Do not edit: change the source and regenerate. */
import type { V2Grade } from '../../v2VisualScorer.generated';
import type { HorizonteScorer } from '../types.generated';
import {
  arrayAreaAnswer, arrayAreaKind, standArray, standAreaDivision, standAreaModel,
  type AreaDivisionPayload, type AreaModelPayload, type ArrayAreaStanding, type ArrayPayload,
} from './arrayAreaModel.generated';
import { circleKeyProblem, isCirclePayload, standCircle } from './fractionCirclesModel.generated';
import { fractionVisual, isFractionPayload, keyProblem, standFraction } from './fractionWallModel.generated';
import { ratioAnswer, ratioKind, standRatio } from './ratioLineModel.generated';

type Segment = { visual?: { type?: unknown }; payload?: unknown };

const INVALID: V2Grade = { verdict: 'invalid', diagnostic: 'none' };
const VALID: V2Grade = { verdict: 'valid', diagnostic: 'none' };
const MET: V2Grade = { verdict: 'met', diagnostic: 'none' };
const REVIEW: V2Grade = { verdict: 'review', diagnostic: 'value' };

const record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const valueKey = (value: unknown): value is { value: unknown } => record(value) && Object.keys(value).join() === 'value';

/**
 * One rule for the three types. invalid: a malformed segment, response or key (the key is checked before the response is
 * called untouched, so a key nobody can reach is refused at publish). valid: nothing entered yet, and every well-formed
 * response when there is no rubric, as in the browser. review: an answer that is not the key. met: the key.
 */
function verdictOf(standing: Exclude<ArrayAreaStanding, 'invalid'>): V2Grade {
  return standing === 'incomplete' ? VALID : standing === 'right' ? MET : REVIEW;
}

function gradeArrayArea(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  const kind = arrayAreaKind(payload);
  if (kind === null || segment.visual?.type !== kind) return INVALID;
  const standing = kind === 'array' ? standArray(payload as ArrayPayload, response)
    : kind === 'area-model' ? standAreaModel(payload as AreaModelPayload, response) : standAreaDivision(payload as AreaDivisionPayload, response);
  if (standing === 'invalid') return INVALID;
  if (rubric === undefined) return VALID;
  if (!valueKey(rubric) || rubric.value !== arrayAreaAnswer(payload)) return INVALID;
  return verdictOf(standing);
}

function gradeRatioLine(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  const kind = ratioKind(payload);
  if (kind === null || segment.visual?.type !== kind) return INVALID;
  const standing = standRatio(payload, response);
  if (standing === 'invalid') return INVALID;
  if (rubric === undefined) return VALID;
  if (!valueKey(rubric) || rubric.value !== ratioAnswer(payload)) return INVALID;
  return verdictOf(standing);
}

function gradeFractionWall(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!isFractionPayload(payload) || segment.visual?.type !== fractionVisual(payload)) return INVALID;
  const standing = standFraction(payload, response);
  if (standing === 'invalid') return INVALID;
  if (rubric === undefined) return VALID;
  if (keyProblem(payload, rubric) !== null) return INVALID;
  return verdictOf(standing);
}

function gradeFractionCircles(segment: Segment, response: unknown, rubric: unknown): V2Grade {
  const payload = segment?.payload;
  if (!isCirclePayload(payload) || segment.visual?.type !== 'fraction-circles') return INVALID;
  const standing = standCircle(payload, response);
  if (standing === 'invalid') return INVALID;
  if (rubric === undefined) return VALID;
  if (circleKeyProblem(payload, rubric) !== null) return INVALID;
  return verdictOf(standing);
}

export const NUM_B_SCORERS: Readonly<Record<string, HorizonteScorer>> = {
  'math.array-area.v2': {
    grade: gradeArrayArea as HorizonteScorer['grade'],
    sample: ((segment: Segment) => {
      const kind = arrayAreaKind(segment.payload);
      return kind === 'area-model' ? { split: 0, partials: ['', ''], value: '' } : kind === 'area-division' ? { partials: ['', ''], value: '' } : { value: '' };
    }) as HorizonteScorer['sample'],
  },
  'math.ratio-line.v2': {
    grade: gradeRatioLine as HorizonteScorer['grade'],
    sample: (() => ({ value: '' })) as HorizonteScorer['sample'],
  },
  'math.fraction-wall.v2': {
    grade: gradeFractionWall as HorizonteScorer['grade'],
    sample: (() => ({ n: 0, d: 0 })) as HorizonteScorer['sample'],
  },
  'math.fraction-circles.v2': {
    grade: gradeFractionCircles as HorizonteScorer['grade'],
    sample: (() => ({ n: 0, d: 0 })) as HorizonteScorer['sample'],
  },
};
