import {teach,ex,q,workedSteps,projectionChart} from './helpers.mjs';
import {numeric,input,subtract} from '../factory.mjs';
const d='insurance-risk';
const min=(a,b)=>({op:'min',args:[a,b]});
const max=(a,b)=>({op:'max',args:[a,b]});
const pocket=subtract(input(0),min(max(subtract(input(0),input(1)),{constant:0}),input(2)));
export const insuranceRisk=[
teach(d,1,'Loss Severity|Frecuencia e impacto financiero|Frequência e impacto financeiro',
 'A rare event can threaten essentials while a frequent small loss fits your budget; compare both likelihood and impact.|Un evento raro puede amenazar esenciales mientras pérdida pequeña frecuente cabe en presupuesto; compara frecuencia e impacto.|Um evento raro pode ameaçar essenciais enquanto perda pequena frequente cabe no orçamento; compare frequência e impacto.',
 'The most frequent loss is automatically the most financially severe.',[
 ex('example-01','Two questions about each risk|Dos preguntas sobre cada riesgo|Duas perguntas sobre cada risco','Ask how often a loss might occur and whether you could absorb its cost. These answer different questions.|Pregunta con qué frecuencia podría ocurrir una pérdida y si podrías cubrir su costo. Son preguntas distintas.|Pergunte com que frequência uma perda poderia ocorrer e se poderia cobrir seu custo. São perguntas distintas.'),
 q('guided-01','guided',[
 'Which loss threatens essentials?|Small breakages fit savings; a rare major fire would exceed all available resources.|The major fire~The small breakages~Both have equal impact|The fire exceeds available resources despite being less frequent.|Separate likelihood from the household’s ability to absorb loss.',
 '¿Qué pérdida amenaza esenciales?|Roturas pequeñas caben en ahorro; incendio mayor raro superaría todos los recursos disponibles.|Incendio mayor~Roturas pequeñas~Ambos tienen igual impacto|Incendio supera recursos disponibles aunque ocurra menos.|Separa frecuencia de capacidad del hogar para cubrir pérdida.',
 'Que perda ameaça essenciais?|Quebras pequenas cabem na poupança; incêndio grande raro superaria todos os recursos disponíveis.|Incêndio grande~Quebras pequenas~Ambos têm igual impacto|Incêndio supera recursos disponíveis mesmo sendo menos comum.|Separe frequência da capacidade da família de cobrir perda.']),
 q('guided-02','guided',[
 'Does rare mean affordable?|A rare covered disruption could stop income longer than the household’s reserve lasts.|No~Yes~Only frequency matters|A rare disruption can still exceed the household’s financial buffer.|Check the size and duration of the resulting gap.',
 '¿Raro significa costeable?|Contratiempo raro podría detener ingresos más tiempo de lo que dura reserva del hogar.|No~Sí~Solo importa frecuencia|Contratiempo raro puede superar colchón financiero del hogar.|Revisa tamaño y duración del faltante que provoca.',
 'Raro significa que cabe?|Contratempo raro poderia parar renda por mais tempo que dura reserva da família.|Não~Sim~Só importa frequência|Contratempo raro pode superar reserva financeira da família.|Veja tamanho e duração da falta que causa.']),
 q('practice-01','practice',[
 'What is missing from this assessment?|A list ranks risks only by how often they occur.|Financial impact~Only the risk count~Only the most recent event|Frequency alone does not show which losses threaten essentials.|Add the cost and available resources for each risk.',
 '¿Qué falta en esta evaluación?|Lista ordena riesgos solo por frecuencia.|Impacto financiero~Solo cantidad de riesgos~Solo evento más reciente|Frecuencia sola no muestra qué pérdidas amenazan esenciales.|Agrega costo y recursos disponibles para cada riesgo.',
 'O que falta nesta análise?|Lista ordena riscos só por frequência.|Impacto financeiro~Só quantidade de riscos~Só evento mais recente|Frequência só não mostra que perdas ameaçam essenciais.|Some custo e recursos disponíveis para cada risco.']),
 q('practice-02','practice',[
 'Which is manageable as stated?|A recurring repair fits the planned repair fund without reducing essentials.|That recurring repair~Every rare loss~Every loss with insurance advertising|The stated repair fits resources already set aside.|Use the given cost and capacity, not marketing or rarity.',
 '¿Cuál es manejable según datos?|Arreglo recurrente cabe en fondo previsto de reparación sin reducir esenciales.|Ese arreglo recurrente~Toda pérdida rara~Toda pérdida con anuncio de seguro|Arreglo indicado cabe en recursos ya apartados.|Usa costo y capacidad dados, no anuncios ni rareza.',
 'Qual é manejável pelos dados?|Conserto recorrente cabe no fundo previsto de reparo sem reduzir essenciais.|Esse conserto recorrente~Toda perda rara~Toda perda com anúncio de seguro|Conserto dado cabe nos recursos já separados.|Use custo e capacidade dados, não anúncios ou raridade.']),
 q('practice-03','practice',[
 'Can losses affect households differently?|The same repair fits one household’s reserve but exceeds another’s available money.|Yes, capacity differs~No, equal price means equal strain~No, frequency fixes the impact|The same cost can create different financial strain.|Compare the loss with each household’s available resources.',
 '¿Pérdida igual afecta distinto a hogares?|Mismo arreglo cabe en reserva de un hogar, pero supera dinero disponible de otro.|Sí, capacidad difiere~No, precio igual significa presión igual~No, frecuencia fija impacto|Mismo costo puede crear presión financiera distinta.|Compara pérdida con recursos disponibles de cada hogar.',
 'Perda igual afeta famílias de modo distinto?|Mesmo conserto cabe na reserva de uma família, mas supera dinheiro disponível de outra.|Sim, capacidade difere~Não, preço igual significa pressão igual~Não, frequência fixa impacto|Mesmo custo pode criar pressão financeira distinta.|Compare perda com recursos disponíveis de cada família.']),
 q('transfer-01','transfer',[
 'Which risk needs severe-loss planning?|Frequent small delivery delays fit the budget; rare equipment destruction would end essential income.|Equipment destruction~Only the delays~Neither because destruction is rare|Equipment destruction threatens essential income despite its lower frequency.|Assess consequences as well as how often losses occur.',
 '¿Qué riesgo requiere plan de pérdida grave?|Demoras pequeñas frecuentes caben en presupuesto; destrucción rara de equipo acabaría ingreso esencial.|Destrucción del equipo~Solo demoras~Ninguno porque destrucción es rara|Destrucción del equipo amenaza ingreso esencial aunque sea menos frecuente.|Evalúa consecuencias además de frecuencia de pérdidas.',
 'Que risco exige plano de perda grave?|Atrasos pequenos frequentes cabem no orçamento; destruição rara de equipamento acabaria renda essencial.|Destruição do equipamento~Só atrasos~Nenhum pois destruição é rara|Destruição do equipamento ameaça renda essencial mesmo sendo menos comum.|Avalie consequências além da frequência das perdas.']),
]),
teach(d,2,'Risk Tools|Combina formas de manejar riesgo|Combine formas de lidar com risco',
 'Prevention reduces a risk, reserves absorb costs and insurance transfers specified losses under a contract; they can complement each other.|Cuidado reduce riesgo, ahorro cubre costos y seguro paga pérdidas bajo contrato. Puedes usar los tres.|Cuidado reduz risco, poupança cobre custos e seguro paga perdas sob contrato. Você pode usar os três.',
 'Insurance replaces prevention and all reserves, or prevention removes every possible loss.',[
 ex('example-01','Different tools, different tasks|Herramientas distintas, usos distintos|Formas distintas, usos distintos','Reduce avoidable risks, reserve money for manageable costs, and check insurance for severe covered losses. One tool cannot cover everything.|Reduce riesgos evitables, reserva dinero para costos manejables y revisa seguro para pérdidas graves cubiertas. Una herramienta no cubre todo.|Reduza riscos evitáveis, reserve dinheiro para custos manejáveis e veja seguro para perdas graves cobertas. Uma ferramenta não cobre tudo.'),
 q('guided-01','guided',[
 'Which action reduces the chance of loss?|A faulty lock raises theft risk; it can be repaired.|Repair the lock~Only label savings~Only read a premium quote|Repairing the fault addresses a cause of the loss.|Distinguish reducing risk from paying after it occurs.',
 '¿Qué acción reduce probabilidad de pérdida?|Cerradura defectuosa eleva riesgo de robo; puede repararse.|Reparar cerradura~Solo etiquetar ahorro~Solo leer prima cotizada|Reparar falla atiende causa de pérdida.|Distingue reducir riesgo de pagar después de que ocurra.',
 'Que ação reduz chance de perda?|Fechadura com defeito eleva risco de furto; pode ser consertada.|Consertar fechadura~Só nomear poupança~Só ler prêmio cotado|Consertar falha trata causa da perda.|Separe reduzir risco de pagar após ele ocorrer.']),
 q('guided-02','guided',[
 'What absorbs this stated cost?|A small repair fits money already saved for repairs.|The repair reserve~A promise that nothing breaks~Only a premium payment|The earmarked reserve can absorb the manageable repair cost.|Match the tool to the stated financial need.',
 '¿Qué cubre este costo indicado?|Arreglo pequeño cabe en dinero ya ahorrado para reparaciones.|Reserva de reparación~Promesa de que nada falla~Solo pago de prima|Reserva apartada puede cubrir costo manejable del arreglo.|Relaciona herramienta con necesidad financiera indicada.',
 'O que cobre este custo dado?|Conserto pequeno cabe no dinheiro já poupado para reparos.|Reserva de reparo~Promessa de que nada quebra~Só pagamento de prêmio|Reserva separada pode cobrir custo manejável do conserto.|Ligue ferramenta à necessidade financeira dada.']),
 q('practice-01','practice',[
 'What does this contract provide?|Fictional policy pays specified major fire losses, subject to its conditions.|Transfer of stated covered risk~Removal of all fire risk~Payment for every possible expense|Insurance transfers specified financial losses under its terms.|Coverage does not prevent every event or cover every cost.',
 '¿Qué ofrece este contrato?|Póliza ficticia paga pérdidas concretas de incendio mayor bajo sus condiciones.|Transferencia del riesgo cubierto indicado~Eliminar todo riesgo de incendio~Pago de todo gasto posible|Seguro transfiere pérdidas financieras concretas bajo sus términos.|Cobertura no evita todo evento ni cubre todo costo.',
 'O que oferece este contrato?|Apólice fictícia paga perdas específicas de incêndio grande sob suas condições.|Transferência do risco coberto dado~Eliminar todo risco de incêndio~Pagamento de todo gasto possível|Seguro transfere perdas financeiras específicas sob seus termos.|Cobertura não evita todo evento nem cobre todo custo.']),
 q('practice-02','practice',[
 'Does coverage replace maintenance?|The policy requires maintaining the alarm; an alarm fault is known.|No, address the fault~Yes, stop maintaining it~Yes, premiums prevent every loss|The stated maintenance duty remains even with insurance.|Use both risk reduction and the actual policy conditions.',
 '¿Cobertura sustituye cuidado del equipo?|Póliza exige mantener alarma; hay falla conocida.|No, atender falla~Sí, dejar cuidado del equipo~Sí, primas evitan toda pérdida|Deber indicado de cuidado del equipo sigue aunque exista seguro.|Usa reducción del riesgo y condiciones reales de póliza.',
 'Cobertura substitui cuidado do bem?|Apólice exige manter alarme; há falha conhecida.|Não, cuidar da falha~Sim, parar cuidado do bem~Sim, prêmios evitam toda perda|Dever dado de cuidado do bem segue mesmo com seguro.|Use redução do risco e condições reais da apólice.']),
 q('practice-03','practice',[
 'Why keep some accessible savings?|Fictional coverage leaves a stated deductible payable by the household.|To fund the retained cost~To make exclusions disappear~To double the claim automatically|The household still needs money for its retained share.|A covered event can still leave an out-of-pocket cost.',
 '¿Por qué conservar ahorro accesible?|Cobertura ficticia deja deducible indicado a cargo del hogar.|Para cubrir costo propio~Para borrar exclusiones~Para duplicar reclamo automáticamente|Hogar aún necesita dinero para su parte.|Evento cubierto aún puede dejar costo de bolsillo.',
 'Por que manter poupança acessível?|Cobertura fictícia deixa franquia dada a cargo da família.|Para cobrir custo próprio~Para apagar exclusões~Para dobrar pedido automaticamente|Família ainda precisa de dinheiro para sua parte.|Evento coberto ainda pode deixar custo próprio.']),
 q('transfer-01','transfer',[
 'Which combined plan fits?|Preventable leaks need maintenance; small repairs fit savings; severe covered damage exceeds savings.|Maintain, reserve, verify coverage~Only buy a policy~Only hope leaks stop|Different loss sizes and causes call for complementary tools.|Match prevention, reserves and coverage to their distinct roles.',
 '¿Qué plan combinado corresponde?|Fugas evitables requieren cuidado del equipo; arreglos pequeños caben en ahorro; daño grave cubierto supera ahorro.|Mantener, reservar, verificar cobertura~Solo comprar póliza~Solo esperar que fugas paren|Causas y tamaños distintos requieren formas de apoyo.|Relaciona cuidado previo, reservas y cobertura con sus funciones distintas.',
 'Que plano combinado cabe?|Vazamentos evitáveis exigem cuidado do bem; reparos pequenos cabem na poupança; dano grave coberto supera poupança.|Manter, reservar, verificar cobertura~Só comprar apólice~Só esperar vazamentos pararem|Causas e tamanhos distintos exigem formas que se complementam.|Ligue prevenção, reservas e cobertura às suas funções distintas.']),
]),
teach(d,3,'Policy Roles|Lee quién y qué está cubierto|Leia quem e o que está coberto',
 'A policy identifies the contracting person, the covered event and who receives a benefit; these roles need not be identical.|Póliza dice quién contrata, qué cubre y quién recibe pago. Pueden ser personas distintas.|Apólice identifica contratante, evento coberto e quem recebe benefício; esses papéis não precisam coincidir.',
 'The person paying always receives the benefit, and a named person means every event is covered.',[
 ex('example-01','Follow the named roles|Sigue los papeles indicados|Siga os papéis dados','Read who holds the contract, which event triggers coverage, and who receives the benefit. Do not infer roles from names.|Lee quién tiene contrato, qué evento activa cobertura y quién recibe beneficio. No deduzcas papeles por los nombres.|Leia quem tem contrato, que evento aciona cobertura e quem recebe benefício. Não deduza papéis pelos nomes.'),
 q('guided-01','guided',[
 'Who is the policyholder?|Fictional policy: Ana contracts; Rui is insured; Lee receives the stated death benefit.|Ana~Rui~Lee|Ana is explicitly named as the contracting policyholder.|Follow the role assigned by the policy.',
 '¿Quién es contratante?|Póliza ficticia: Ana contrata; Rui es asegurado; Lee recibe beneficio indicado por fallecimiento.|Ana~Rui~Lee|Ana está nombrada como contratante de póliza.|Sigue papel asignado por póliza.',
 'Quem é titular do contrato?|Apólice fictícia: Ana contrata; Rui é segurado; Lee recebe benefício dado por morte.|Ana~Rui~Lee|Ana está nomeada como titular do contrato.|Siga papel atribuído pela apólice.']),
 q('guided-02','guided',[
 'Which event triggers this stated benefit?|Fictional policy covers insured Rui’s death during its term; no other event is listed.|Rui’s death during the term~Rui reaches retirement~Rui’s survival|The stated insured event must match the policy wording.|A named insured does not make all events covered.',
 '¿Qué evento activa beneficio indicado?|Póliza ficticia cubre fallecimiento de Rui asegurado durante vigencia; no lista otro evento.|Fallecimiento de Rui durante vigencia~Rui llega al retiro~Supervivencia de Rui|Evento asegurado debe coincidir con texto de póliza.|Persona asegurada no vuelve cubiertos todos los eventos.',
 'Que evento aciona benefício dado?|Apólice fictícia cobre morte do segurado Rui durante vigência; não lista outro evento.|Morte de Rui durante vigência~Rui chega à aposentadoria~Sobrevivência de Rui|Evento segurado deve coincidir com texto da apólice.|Pessoa segurada não torna todos os eventos cobertos.']),
 q('practice-01','practice',[
 'Who receives the stated benefit?|Fictional policy names Noor as beneficiary; Mika pays premiums.|Noor~Mika automatically~Whoever reports first|The named beneficiary receives the benefit under the stated terms.|Payment of premiums does not alone identify the beneficiary.',
 '¿Quién recibe beneficio indicado?|Póliza ficticia nombra a Noor para recibir el pago; Mika paga primas.|Noor~Mika por sí solo~Quien reporte primero|Beneficiaria nombrada recibe beneficio según términos indicados.|Pagar primas no identifica por sí solo a quien recibe el pago.',
 'Quem recebe benefício dado?|Apólice fictícia nomeia Noor beneficiária; Mika paga prêmios.|Noor~Mika automaticamente~Quem informar primeiro|Beneficiária nomeada recebe benefício conforme termos dados.|Pagar prêmios não identifica por si só a beneficiária.']),
 q('practice-02','practice',[
 'What remains unknown?|A summary names the insured person but omits covered events.|Which events trigger payment~The insured person’s name~Whether events are listed|The missing event terms prevent deciding what triggers coverage.|Do not turn an omitted condition into unlimited coverage.',
 '¿Qué sigue desconocido?|Resumen nombra persona asegurada pero omite eventos cubiertos.|Qué eventos activan pago~Nombre de persona asegurada~Si se enumeran eventos|Faltan términos para decidir qué activa cobertura.|No conviertas condición omitida en cobertura sin límites.',
 'O que segue desconhecido?|Resumo nomeia pessoa segurada mas omite eventos cobertos.|Que eventos acionam pagamento~Nome da pessoa segurada~Se há eventos listados|Faltam termos para decidir o que aciona cobertura.|Não transforme condição omitida em cobertura sem limites.']),
 q('practice-03','practice',[
 'Can these roles coincide here?|Fictional policy explicitly names Jo as both policyholder and insured.|Yes, as stated~No, always different people~Yes, so every loss is covered|The contract can assign multiple roles to the same person.|Read the stated roles without assuming extra coverage.',
 '¿Pueden coincidir estos papeles aquí?|Póliza ficticia nombra de forma clara a Jo contratante y asegurado.|Sí, según texto~No, siempre personas distintas~Sí, entonces cubre toda pérdida|Contrato puede asignar varios papeles a misma persona.|Lee papeles indicados sin suponer cobertura extra.',
 'Esses papéis podem coincidir aqui?|Apólice fictícia nomeia Jo titular e segurado de forma expressa.|Sim, conforme texto~Não, sempre pessoas distintas~Sim, então cobre toda perda|Contrato pode dar vários papéis à mesma pessoa.|Leia papéis dados sem supor cobertura extra.']),
 q('transfer-01','transfer',[
 'Who is entitled under these terms?|Fictional contract: Sam holds policy; Lee is insured; Pat receives benefit after Lee’s covered death.|Pat~Sam because Sam signed~Lee’s employer automatically|Pat is the beneficiary identified in the stated contract.|Distinguish holder, insured person and recipient of the benefit.',
 '¿Quién tiene derecho según términos?|Contrato ficticio: Sam contrata; Lee es asegurado; Pat recibe beneficio tras fallecimiento cubierto de Lee.|Pat~Sam porque firmó~Empleador de Lee por sí solo|Contrato indica que Pat recibe el pago.|Distingue contratante, persona asegurada y quien recibe el pago.',
 'Quem tem direito pelos termos?|Contrato fictício: Sam contrata; Lee é segurado; Pat recebe benefício após morte coberta de Lee.|Pat~Sam porque assinou~Empregador de Lee automaticamente|Pat é beneficiário identificado no contrato dado.|Separe titular, pessoa segurada e quem recebe benefício.']),
]),
teach(d,4,'Insurance Payments|Prima y deducible son distintos|Prêmio e franquia são distintos',
 'Paying for coverage and paying your share of a covered loss are separate costs; use the contract to distinguish them.|Pagar cobertura y pagar tu parte de pérdida cubierta son costos distintos; usa contrato para distinguirlos.|Pagar cobertura e pagar sua parte de perda coberta são custos distintos; use contrato para separá-los.',
 'The premium is refunded if no claim occurs, or paying it removes the deductible.',[
 ex('example-01','Two different payments|Dos pagos distintos|Dois pagamentos distintos','A premium buys coverage under the contract. A deductible is a stated share you retain when the covered loss occurs.|Prima paga cobertura bajo contrato. Deducible es parte indicada a tu cargo cuando ocurre pérdida cubierta.|Prêmio paga cobertura sob contrato. Franquia é parte dada a seu cargo quando ocorre perda coberta.'),
 numeric(q('guided-01','guided',[
 'Which amount buys this coverage?|Fictional terms: annual premium 120; deductible 300 per covered loss.|120~300~420|The premium is the stated price of coverage.|Separate the coverage price from the retained claim cost.',
 '¿Qué monto paga esta cobertura?|Términos ficticios: prima anual 120; deducible 300 por pérdida cubierta.|120~300~420|Prima es precio indicado de cobertura.|Separa precio de cobertura de costo propio del reclamo.',
 'Que valor paga esta cobertura?|Termos fictícios: prêmio anual 120; franquia 300 por perda coberta.|120~300~420|Prêmio é preço dado da cobertura.|Separe preço da cobertura de custo próprio do pedido.']),[120,300],input(0)),
 q('guided-02','guided',[
 'Which cost stays with the household?|Fictional terms: premium pays coverage; deductible remains payable for each covered repair.|The deductible~No cost after premium~Only the advertisement price|The deductible remains separate from the premium under these terms.|Read what remains payable when a covered loss happens.',
 '¿Qué costo queda al hogar?|Términos ficticios: prima paga cobertura; deducible sigue pagadero por cada reparación cubierta.|Deducible~Ningún costo tras prima~Solo precio del anuncio|Deducible sigue separado de prima bajo estos términos.|Lee qué sigue pagadero al ocurrir pérdida cubierta.',
 'Que custo fica com a família?|Termos fictícios: prêmio paga cobertura; franquia segue devida por cada reparo coberto.|Franquia~Nenhum custo após prêmio~Só preço do anúncio|Franquia segue separada do prêmio sob esses termos.|Leia o que segue devido ao ocorrer perda coberta.']),
 q('practice-01','practice',[
 'Is a refund promised here?|Fictional terms charge a nonrefundable premium; no loss occurs.|No~Yes, all unused premiums return~Yes, deductibles become refunds|These terms explicitly make the premium nonrefundable.|Use the stated contract, not an assumed refund rule.',
 '¿Se promete reembolso aquí?|Términos ficticios cobran prima no reembolsable; no ocurre pérdida.|No~Sí, toda prima sin uso vuelve~Sí, deducibles se vuelven reembolsos|Estos términos indican prima no reembolsable.|Usa contrato indicado, no regla supuesta de reembolso.',
 'Há promessa de devolução aqui?|Termos fictícios cobram prêmio sem devolução; não ocorre perda.|Não~Sim, todo prêmio sem uso volta~Sim, franquias viram devoluções|Esses termos indicam prêmio sem devolução.|Use contrato dado, não regra suposta de devolução.']),
 q('practice-02','practice',[
 'Does paying the premium erase this deductible?|Fictional policy separately requires a premium and a deductible for covered repairs.|No~Yes~Only if paid early|Both costs remain distinct obligations under the stated policy.|Early payment does not remove an unchanged contract condition.',
 '¿Pagar prima borra este deducible?|Póliza ficticia exige por separado prima y deducible para reparaciones cubiertas.|No~Sí~Solo pagando antes|Ambos costos siguen siendo deberes distintos bajo póliza indicada.|Pagar antes no quita condición contractual sin cambio.',
 'Pagar prêmio apaga esta franquia?|Apólice fictícia exige em separado prêmio e franquia para reparos cobertos.|Não~Sim~Só pagando antes|Ambos os custos seguem deveres distintos sob apólice dada.|Pagar antes não tira condição contratual sem mudança.']),
 q('practice-03','practice',[
 'Which change needs a cash check?|A quoted policy lowers premiums but raises the deductible above available savings.|Ability to fund the deductible~Only the annual premium~Nothing because premiums fell|A lower premium can leave a larger claim cost to fund.|Compare both regular cost and retained loss capacity.',
 '¿Qué cambio requiere revisar efectivo?|Póliza cotizada baja primas pero sube deducible por encima del ahorro disponible.|Capacidad de cubrir deducible~Solo la prima anual~Nada porque primas bajaron|Prima menor puede dejar costo propio mayor por cubrir.|Compara costo regular y capacidad de absorber pérdida.',
 'Que mudança exige conferir dinheiro?|Apólice cotada baixa prêmios mas sobe franquia acima da poupança disponível.|Capacidade de cobrir franquia~Só o prêmio anual~Nada pois prêmios caíram|Prêmio menor pode deixar custo próprio maior por cobrir.|Compare custo regular e capacidade de absorver perda.']),
 q('transfer-01','transfer',[
 'Which distinction fits?|Fictional travel policy charges before the trip and retains a stated share per covered claim.|Premium before; deductible at claim~Both are refunds~Premium removes every retained cost|The coverage price differs from the share retained per claim.|Identify why each payment is charged.',
 '¿Qué distinción es correcta?|Póliza ficticia de viaje cobra antes de viajar y deja parte propia por reclamo cubierto.|Prima antes; deducible al reclamar~Ambos son reembolsos~Prima elimina todo costo propio|Precio de cobertura difiere de parte propia por reclamo.|Identifica por qué se cobra cada pago.',
 'Que distinção está certa?|Apólice fictícia de viagem cobra antes de viajar e deixa parte própria por pedido coberto.|Prêmio antes; franquia no pedido~Ambos são devoluções~Prêmio elimina todo custo próprio|Preço de cobertura difere de parte própria por pedido.|Identifique por que se cobra cada pagamento.']),
]),
teach(d,5,'Retained Loss|Calcula pérdida a tu cargo|Calcule perda a seu cargo',
 'A covered claim may leave a deductible and amounts above the payout cap; calculate both with fictional local currency.|Reclamo cubierto puede dejar deducible y monto sobre tope de pago; calcula ambos con pesos ficticios.|Pedido coberto pode deixar franquia e valor acima do teto de pagamento; calcule ambos com reais fictícios.',
 'The deductible is the only possible retained cost even when the insurer payout is capped.',[
 ex('example-01','Apply the exact payment rule|Aplica regla exacta de pago|Aplique regra exata de pagamento','Subtract the deductible from loss, floor at zero, then cap insurer payment. Your cost is loss minus that payment.|Resta deducible de pérdida sin bajar de cero; limita pago del seguro al tope. Tu costo es pérdida menos pago.|Subtraia franquia da perda sem ficar abaixo de zero; limite pagamento do seguro ao teto. Seu custo é perda menos pagamento.'),
 workedSteps('guided-01',['900 - 100','min(800, 600)','900 - 600'],[800,600,300],[
 'Fictional covered loss 900 dollars; deductible 100; insurer payout cap 600 after deduction; no other costs. Find household cost.|The cap leaves more than the deductible unpaid.|Deduct, apply the payout cap, then subtract payment from loss.|Loss after deductible|Capped insurer payment|Household cost',
 'Pérdida cubierta ficticia 900 pesos; deducible 100; tope de pago del seguro 600 tras deducir; sin otros costos. Calcula costo propio.|Tope deja sin pagar más que deducible.|Deduce, aplica tope de pago y resta pago de pérdida.|Pérdida tras deducible|Pago limitado del seguro|Costo del hogar',
 'Perda coberta fictícia 900 reais; franquia 100; teto de pagamento do seguro 600 após deduzir; sem outros custos. Ache custo próprio.|Teto deixa sem pagar mais que franquia.|Deduza, aplique teto de pagamento e subtraia pagamento da perda.|Perda após franquia|Pagamento limitado do seguro|Custo da família']),
 q('guided-02','guided',[
 'Can insurer payment become negative?|Fictional rule subtracts deductible from loss but floors payment at zero.|No~Yes, a negative claim is owed~Yes, whenever loss is small|The zero floor prevents a negative insurer payment.|Use the stated floor before applying the payout cap.',
 '¿Puede pago del seguro ser negativo?|Regla ficticia resta deducible de pérdida pero fija mínimo de pago en cero.|No~Sí, se debe reclamo negativo~Sí, siempre con pérdida pequeña|Mínimo cero evita pago negativo del seguro.|Usa mínimo indicado antes de aplicar tope de pago.',
 'Pagamento do seguro pode ser negativo?|Regra fictícia subtrai franquia da perda mas fixa mínimo de pagamento em zero.|Não~Sim, deve pedido negativo~Sim, sempre com perda pequena|Mínimo zero evita pagamento negativo do seguro.|Use mínimo dado antes de aplicar teto de pagamento.']),
 ...[
 ['practice-01','practice',[500,100,1000],100,[400,500]],
 ['practice-02','practice',[80,100,1000],80,[0,100]],
 ['practice-03','practice',[1400,200,900],500,[200,1200]],
 ].map(([key,role,values,answer,distractors])=>numeric(q(key,role,[
 `What cost remains yours?|Fictional covered loss ${values[0]}; deductible ${values[1]}; insurer cap ${values[2]}; payout is loss minus deductible, floored at zero and capped; no other costs.|${[answer,...distractors].join('~')}|Your cost is loss minus the capped insurer payment.|Apply the deduction, zero floor and cap before finding your share.`,
 `¿Qué costo queda a tu cargo?|Pérdida cubierta ficticia ${values[0]}; deducible ${values[1]}; tope del seguro ${values[2]}; pago es pérdida menos deducible, mínimo cero y limitado al tope; sin otros costos.|${[answer,...distractors].join('~')}|Tu costo es pérdida menos pago limitado del seguro.|Aplica deducción, mínimo cero y tope antes de calcular tu parte.`,
 `Que custo fica com você?|Perda coberta fictícia ${values[0]}; franquia ${values[1]}; teto do seguro ${values[2]}; pagamento é perda menos franquia, mínimo zero e limitado ao teto; sem outros custos.|${[answer,...distractors].join('~')}|Seu custo é perda menos pagamento limitado do seguro.|Aplique dedução, mínimo zero e teto antes de calcular sua parte.`]),values,pocket)),
 numeric(q('transfer-01','transfer',[
 'Budget for repairs after insurance?|Fictional covered flood repairs: 750. Insurer pays repairs minus deductible 50, minimum zero, maximum 400; no other costs.|350~50~700|Insurance pays 400; budget the remaining 350 to complete the repairs.|Subtract the capped insurance payment from the full repair cost.',
 '¿Cuánto presupuestas para reparar tras el seguro?|Reparación cubierta por inundación: 750. Póliza ficticia: seguro paga reparación menos deducible 50, mínimo cero, máximo 400; sin otros costos.|350~50~700|El seguro paga 400; presupuesta los 350 restantes para completar la reparación.|Resta el pago limitado del seguro al costo completo de reparación.',
 'Quanto reservar para reparar após o seguro?|Reparo coberto por enchente: 750. Apólice fictícia: seguro paga reparo menos franquia 50, mínimo zero, máximo 400; sem outros custos.|350~50~700|O seguro paga 400; reserve os 350 restantes para completar o reparo.|Subtraia o pagamento limitado do seguro do custo total do reparo.'
 ]),[750,50,400],pocket),
]),
teach(d,6,'Excluded Events|Lee el evento excluido|Leia o evento excluído',
 'Coverage names do not decide every claim; compare the actual cause with the policy’s exclusions and any amendments.|Nombre de cobertura no decide todo reclamo; compara causa real con exclusiones y cambios de póliza.|Nome da cobertura não decide todo pedido; compare causa real com exclusões e mudanças da apólice.',
 'A broad coverage label or paid premium overrides an explicit exclusion.',[
 ex('example-01','Cause and conditions matter|Causa y condiciones importan|Causa e condições importam','Match the actual event to covered causes and exclusions. A broad policy title cannot override a specific excluded cause.|Relaciona evento real con causas cubiertas y exclusiones. Título amplio de póliza no anula causa excluida específica.|Ligue evento real a causas cobertas e exclusões. Título amplo da apólice não anula causa excluída específica.'),
 q('guided-01','guided',[
 'Does this policy cover it?|Fictional policy covers pipe bursts but excludes river floods; river flooding causes damage.|No, excluded river flood~Yes, all water damage~Yes, because premiums were paid|The actual cause matches the explicit exclusion.|Identify the cause rather than relying on the policy title.',
 '¿Esta póliza indicada cubre pérdida?|Póliza ficticia cubre roturas de tubo pero excluye desbordes de río; desborde causa daño.|No, desborde de río excluido~Sí, todo daño por agua~Sí, porque se pagaron primas|Causa real coincide con exclusión expresa.|Identifica causa sin depender del título de póliza.',
 'Esta apólice dada cobre perda?|Apólice fictícia cobre cano rompido mas exclui enchente de rio; enchente causa dano.|Não, enchente de rio excluída~Sim, todo dano por água~Sim, pois prêmios foram pagos|Causa real coincide com exclusão expressa.|Identifique causa sem depender do título da apólice.']),
 q('guided-02','guided',[
 'What evidence is missing?|Policy covers accidental breakage but excludes wear; the cause of damage is unknown.|Cause of damage~The purchase price alone~Proof that every cause qualifies|Without the cause, this coverage decision remains unresolved.|Find the relevant event facts before applying the exclusion.',
 '¿Qué evidencia falta?|Póliza cubre rotura accidental pero excluye desgaste; causa del daño es desconocida.|Causa del daño~Solo el precio de compra~Prueba de que toda causa cumple|Sin causa, decisión de cobertura sigue sin resolver.|Busca hechos relevantes antes de aplicar exclusión.',
 'Que prova falta?|Apólice cobre quebra acidental mas exclui desgaste; causa do dano é desconhecida.|Causa do dano~Só o preço de compra~Prova de que toda causa atende|Sem causa, decisão de cobertura segue sem solução.|Busque fatos relevantes antes de aplicar exclusão.']),
 q('practice-01','practice',[
 'Which document may change this exclusion?|A signed amendment adds river-flood coverage to the fictional policy.|The applicable amendment~An unrelated advertisement~A friend’s different policy|An applicable contract amendment can change the stated coverage.|Check which written terms actually apply to this policy.',
 '¿Qué documento puede cambiar exclusión?|Modificación firmada agrega cobertura de desborde de río a póliza ficticia.|Modificación aplicable~Anuncio ajeno~Póliza distinta de amigo|Modificación aplicable del contrato puede cambiar cobertura indicada.|Revisa qué términos escritos aplican a esta póliza.',
 'Que documento pode mudar exclusão?|Alteração assinada inclui cobertura de enchente de rio na apólice fictícia.|Alteração aplicável~Anúncio alheio~Apólice distinta de amigo|Alteração aplicável do contrato pode mudar cobertura dada.|Veja que termos escritos se aplicam a esta apólice.']),
 q('practice-02','practice',[
 'Does a bigger limit remove the exclusion?|Fictional policy increases its payout limit but keeps wear excluded.|No~Yes~Only after another premium|A higher limit does not change an unchanged excluded cause.|Separate how much is payable from which events qualify.',
 '¿Límite mayor elimina exclusión?|Póliza ficticia aumenta límite de pago pero sigue excluyendo desgaste.|No~Sí~Solo tras otra prima|Límite mayor no cambia causa excluida sin cambio.|Separa cuánto se paga de qué eventos cumplen.',
 'Limite maior elimina exclusão?|Apólice fictícia aumenta limite de pagamento mas segue excluindo desgaste.|Não~Sim~Só após outro prêmio|Limite maior não muda causa excluída sem mudança.|Separe quanto se paga de que eventos atendem.']),
 q('practice-03','practice',[
 'Which loss matches the stated exclusion?|Fictional phone policy excludes unattended theft; the phone was left unattended and stolen.|This unattended theft~Every accidental drop~No loss after paying premium|The scenario matches the stated unattended-theft exclusion.|Match the actual facts to the exact exclusion.',
 '¿Qué pérdida coincide con exclusión?|Póliza ficticia de teléfono excluye robo sin vigilancia; teléfono quedó sin vigilancia y fue robado.|Este robo sin vigilancia~Toda caída accidental~Ninguna tras pagar prima|Escenario coincide con exclusión indicada de robo sin vigilancia.|Relaciona hechos reales con exclusión exacta.',
 'Que perda coincide com exclusão?|Apólice fictícia de celular exclui furto sem vigilância; celular ficou sem vigilância e foi furtado.|Este furto sem vigilância~Toda queda acidental~Nenhuma após pagar prêmio|Cenário coincide com exclusão dada de furto sem vigilância.|Ligue fatos reais à exclusão exata.']),
 q('transfer-01','transfer',[
 'Is this covered?|Fictional travel policy covers carrier cancellation but excludes voluntary changes; traveler chooses a new date.|No, voluntary change excluded~Yes, any changed trip~Yes, carrier coverage means everything|The voluntary change falls under the stated exclusion.|Distinguish the covered trigger from the actual reason.',
 '¿Causa está cubierta según texto?|Póliza ficticia de viaje cubre cancelación del transportista pero excluye cambios voluntarios; viajero elige otra fecha.|No, cambio voluntario excluido~Sí, todo viaje cambiado~Sí, cubrir transportista cubre todo|Cambio voluntario cae en exclusión indicada.|Distingue causa cubierta del motivo real.',
 'Causa está coberta pelo texto?|Apólice fictícia de viagem cobre cancelamento da empresa mas exclui mudanças voluntárias; viajante escolhe outra data.|Não, mudança voluntária excluída~Sim, toda viagem mudada~Sim, cobrir empresa cobre tudo|Mudança voluntária cai na exclusão dada.|Separe causa coberta do motivo real.']),
]),
teach(d,7,'Policy Comparisons|Alinea pólizas antes de comparar precios|Alinhe apólices antes de comparar preços',
 'A cheaper premium can buy different protection; align covered events, deductibles, limits and time before judging the price.|Prima menor puede comprar protección distinta; alinea eventos cubiertos, deducibles, límites y periodo antes de juzgar precio.|Prêmio menor pode comprar proteção distinta; alinhe eventos cobertos, franquias, limites e período antes de julgar preço.',
 'The lowest premium always identifies the best equivalent protection.',[
 ex('example-01','Make the comparison fair|Haz comparación justa|Faça comparação justa','First match covered events, exclusions, deductibles, limits and period. Then compare price and the costs you could retain.|Primero iguala eventos cubiertos, exclusiones, deducibles, límites y periodo. Luego compara precio y costos que quedarían a tu cargo.|Primeiro iguale eventos cobertos, exclusões, franquias, limites e período. Depois compare preço e custos que ficariam com você.'),
 q('guided-01','guided',[
 'Is price alone enough?|A costs less but excludes the flood risk being assessed; B includes that stated risk.|No, coverage differs~Yes, choose the lower premium~Yes, ignore the event|The policies do not cover the same stated risk.|Align the relevant coverage before judging the premium.',
 '¿Precio solo basta aquí?|A cuesta menos pero excluye inundación evaluada; B incluye ese riesgo indicado.|No, cobertura difiere~Sí, elegir prima menor~Sí, ignorar evento|Pólizas no cubren el mismo riesgo indicado.|Alinea cobertura relevante antes de juzgar prima.',
 'Preço só basta aqui?|A custa menos mas exclui enchente avaliada; B inclui esse risco dado.|Não, cobertura difere~Sim, escolher prêmio menor~Sim, ignorar evento|Apólices não cobrem o mesmo risco dado.|Alinhe cobertura relevante antes de julgar prêmio.']),
 projectionChart('guided-02','guided',[120,150],[
 'Fictional dollars; identical events, exclusions, deductible, limit and annual period. Compare annual premiums.|Annual premium|A|B|Which costs less?|A costs less for the explicitly equal protection.|Compare price only after confirming the stated terms match.',
 'Pesos ficticios; eventos, exclusiones, deducible, límite y periodo anual iguales. Compara primas anuales.|Prima anual|A|B|¿Cuál cuesta menos?|A cuesta menos por protección expresamente igual.|Compara precio solo tras confirmar términos iguales.',
 'Reais fictícios; eventos, exclusões, franquia, limite e período anual iguais. Compare prêmios anuais.|Prêmio anual|A|B|Qual custa menos?|A custa menos por proteção expressamente igual.|Compare preço só após confirmar termos iguais.'
 ],'lower', ["Annual premium","Prima anual","Prêmio anual"]),
 q('practice-01','practice',[
 'Which mismatch blocks this comparison?|One quoted premium buys a month; the other buys a year.|Coverage period~Only the payment method~No mismatch|Different coverage periods make the listed prices incomparable as shown.|Align the period before comparing totals.',
 '¿Qué diferencia impide comparación?|Una prima cotizada compra un mes; otra compra un año.|Periodo cubierto~Solo el método de pago~Ninguna diferencia|Periodos distintos impiden comparar precios tal como aparecen.|Alinea periodo antes de comparar totales.',
 'Que diferença impede comparação?|Um prêmio cotado compra um mês; outro compra um ano.|Período coberto~Só a forma de pagamento~Nenhuma diferença|Períodos distintos impedem comparar preços como aparecem.|Alinhe período antes de comparar totais.']),
 q('practice-02','practice',[
 'What retained cost changed?|Lower-premium policy covers the same events but doubles the deductible.|Household share per claim~Only the insured name~Nothing relevant|The household must fund a larger deductible under that option.|Include the retained claim cost when comparing policies.',
 '¿Qué costo propio cambió?|Póliza de prima menor cubre mismos eventos pero duplica deducible.|Parte del hogar por reclamo~Solo nombre asegurado~Nada relevante|Hogar debe cubrir deducible mayor en esa opción.|Incluye costo propio del reclamo al comparar pólizas.',
 'Que custo próprio mudou?|Apólice de prêmio menor cobre mesmos eventos mas dobra franquia.|Parte da família por pedido~Só nome segurado~Nada relevante|Família deve cobrir franquia maior nessa opção.|Inclua custo próprio do pedido ao comparar apólices.']),
 q('practice-03','practice',[
 'What must be checked before calling these equal?|Premiums and deductibles match; one summary omits the payout limit.|The missing limit~Only payment method~Nothing, equal premium proves equality|An unknown limit prevents confirming equivalent protection.|Equal prices do not supply missing contract terms.',
 '¿Qué revisar antes de llamarlas iguales?|Primas y deducibles coinciden; un resumen omite límite de pago.|Límite faltante~Solo forma de pago~Nada, prima igual prueba igualdad|Límite desconocido impide confirmar protección equivalente.|Precios iguales no completan términos faltantes del contrato.',
 'O que conferir antes de chamá-las iguais?|Prêmios e franquias coincidem; um resumo omite limite de pagamento.|Limite faltante~Só forma de pagamento~Nada, prêmio igual prova igualdade|Limite desconhecido impede confirmar proteção equivalente.|Preços iguais não completam termos faltantes do contrato.']),
 q('transfer-01','transfer',[
 'Is the cheaper quote equivalent?|Travel quotes match limits and period; cheaper quote excludes the required activity.|No, activity coverage differs~Yes, matching limits settle it~Yes, price decides all|The excluded required activity makes the protection materially different.|Match the actual risk as well as limits and price.',
 '¿Cotización menor puede juzgarse equivalente?|Cotizaciones de viaje igualan límites y periodo; más barata excluye actividad necesaria.|No, cobertura de actividad difiere~Sí, límites iguales resuelven~Sí, precio decide todo|Actividad necesaria excluida vuelve protección distinta.|Iguala riesgo real además de límites y precio.',
 'Cotação menor pode ser julgada igual?|Cotações de viagem igualam limites e período; mais barata exclui atividade necessária.|Não, cobertura da atividade difere~Sim, limites iguais resolvem~Sim, preço decide tudo|Atividade necessária excluída torna proteção distinta.|Iguale risco real além de limites e preço.']),
]),
teach(d,8,'Coverage Timing|Revisa cuándo inicia cobertura|Veja quando começa cobertura',
 'Purchase and coverage dates may differ; read the waiting rule before relying on protection.|Fecha de compra puede diferir de fecha elegible para evento; lee regla exacta de espera antes de contar con protección.|Data de compra pode diferir da data elegível para evento; leia regra exata de carência antes de contar com proteção.',
 'Paying today means every event today qualifies, or a later claim date fixes an event that occurred during a waiting period.',[
 ex('example-01','Use the event date|Usa fecha del evento|Use data do evento','Compare the event date with the stated coverage start. A later claim date does not change when the event occurred.|Compara fecha del evento con inicio indicado de cobertura. Reclamar después no cambia cuándo ocurrió evento.|Compare data do evento com início dado da cobertura. Pedir depois não muda quando ocorreu evento.'),
 q('guided-01','guided',[
 'Is this event eligible?|Fictional terms cover events from day 11; the event occurs on day 5.|No~Yes, premium was paid~Yes, if reported later|The event occurs before the stated coverage start.|Compare the event day with the first eligible day.',
 '¿Evento cumple estos términos?|Términos ficticios cubren eventos desde día 11; evento ocurre día 5.|No~Sí, se pagó prima~Sí, si se reporta después|Evento ocurre antes del inicio indicado de cobertura.|Compara día del evento con primer día elegible.',
 'Evento atende estes termos?|Termos fictícios cobrem eventos desde dia 11; evento ocorre dia 5.|Não~Sim, prêmio foi pago~Sim, se informado depois|Evento ocorre antes do início dado da cobertura.|Compare dia do evento com primeiro dia elegível.']),
 q('guided-02','guided',[
 'Does this event pass waiting?|Fictional terms cover events from day 11 inclusive; event occurs day 11; other conditions met.|Yes~No, one more day always required~No event can qualify|The stated start includes the event day.|Read whether the boundary date is included.',
 '¿Evento supera regla de espera?|Términos ficticios cubren eventos desde día 11 inclusive; evento ocurre día 11; cumple otras condiciones.|Sí~No, siempre falta otro día~Ningún evento cumple|Inicio indicado incluye día del evento.|Lee si fecha límite está incluida.',
 'Evento passa regra de carência?|Termos fictícios cobrem eventos desde dia 11 inclusive; evento ocorre dia 11; atende outras condições.|Sim~Não, sempre falta outro dia~Nenhum evento atende|Início dado inclui dia do evento.|Leia se data limite está incluída.']),
 q('practice-01','practice',[
 'Does reporting later change eligibility?|Fictional policy excludes events before June 10; event occurs June 8 and is reported June 12.|No~Yes, use report date~Yes, choose either date|The event date remains before the stated eligibility date.|Do not replace the event date with the report date.',
 '¿Reportar después cambia elegibilidad?|Póliza ficticia excluye eventos antes del 10 de junio; evento ocurre 8 y se reporta 12 de junio.|No~Sí, usar fecha de reporte~Sí, elegir cualquier fecha|Fecha del evento sigue antes de fecha elegible indicada.|No sustituyas fecha del evento por fecha de reporte.',
 'Informar depois muda elegibilidade?|Apólice fictícia exclui eventos antes de 10 de junho; evento ocorre dia 8 e é informado dia 12.|Não~Sim, usar data do aviso~Sim, escolher qualquer data|Data do evento segue antes da data elegível dada.|Não troque data do evento pela data do aviso.']),
 q('practice-02','practice',[
 'Does one period apply?|Fictional policy starts accident coverage today but illness coverage later; tomorrow’s event is illness.|No, use illness start~Yes, earliest date covers all~Yes, premium date decides|The illness event follows its own stated waiting rule.|Match the event type to its coverage start.',
 '¿Una espera responde por ambos?|Póliza ficticia inicia cobertura de accidente hoy y enfermedad después; evento de mañana es enfermedad.|No, usar inicio de enfermedad~Sí, primera fecha cubre todo~Sí, decide fecha de prima|Enfermedad sigue su propia regla indicada de espera.|Relaciona tipo de evento con inicio de cobertura.',
 'Uma carência responde por ambos?|Apólice fictícia inicia cobertura de acidente hoje e doença depois; evento de amanhã é doença.|Não, usar início de doença~Sim, primeira data cobre tudo~Sim, decide data do prêmio|Doença segue sua própria regra dada de carência.|Ligue tipo de evento ao início de cobertura.']),
 q('practice-03','practice',[
 'What must be clarified?|A quote says coverage has a waiting period but gives no start date or counting rule.|Exact eligibility start and rule~The premium amount~Assume immediate coverage|The missing timing terms prevent confirming near-term protection.|Request the precise rule before relying on a start date.',
 '¿Qué debe aclararse?|Cotización dice que hay periodo de espera pero no da inicio ni regla de conteo.|Inicio elegible y regla exactos~El monto de prima~Suponer cobertura inmediata|Términos de tiempo faltantes impiden confirmar protección próxima.|Solicita regla precisa antes de contar con fecha de inicio.',
 'O que deve ser esclarecido?|Cotação diz que há carência mas não dá início nem regra de contagem.|Início elegível e regra exatos~O valor do prêmio~Supor cobertura imediata|Termos de prazo faltantes impedem confirmar proteção próxima.|Peça regra precisa antes de contar com data de início.']),
 q('transfer-01','transfer',[
 'Does this qualify?|Fictional benefit covers events from October 20 inclusive; event is October 18; other conditions hold.|No, before the start~Yes, other conditions suffice~Yes, file after October 20|The timing condition fails despite the other conditions being met.|Check every stated condition, including the event date.',
 '¿Evento próximo cumple?|Beneficio ficticio cubre eventos elegibles desde 20 de octubre inclusive; evento es 18 de octubre; cumple demás condiciones.|No, antes del inicio~Sí, demás condiciones bastan~Sí, reclamar tras 20 de octubre|Condición de tiempo falla aunque se cumplan las demás.|Revisa cada condición indicada, incluida fecha del evento.',
 'Evento próximo atende?|Benefício fictício cobre eventos elegíveis desde 20 de outubro inclusive; evento é 18 de outubro; atende demais condições.|Não, antes do início~Sim, demais condições bastam~Sim, pedir após 20 de outubro|Condição de prazo falha mesmo atendendo as demais.|Veja cada condição dada, inclusive data do evento.']),
]),
teach(d,9,'Claim Records|Conserva evidencia del reclamo|Guarde provas do pedido',
 'Claims need relevant facts, records and dates; preserve what you submit and its confirmation.|Reclamo necesita hechos, comprobantes y fechas bajo términos reales; guarda copia rastreable de lo que entregas.|Pedido precisa de fatos, comprovantes e datas sob termos reais; guarde cópia rastreável do que envia.',
 'A verbal report guarantees payment or removes documentary requirements and stated deadlines.',[
 ex('example-01','Facts, records and dates|Hechos, registros y fechas|Fatos, registros e datas','Check the claim instructions; preserve relevant evidence, deadlines, submitted copies and confirmation. Reporting alone does not guarantee coverage or payment.|Revisa instrucciones; conserva evidencia relevante, fechas, copias entregadas y confirmación. Reportar solo no garantiza cobertura ni pago.|Veja instruções; guarde provas relevantes, datas, cópias enviadas e confirmação. Informar só não garante cobertura nem pagamento.'),
 q('guided-01','guided',[
 'Which record set meets these instructions?|Fictional claim asks for event date, damage photos and repair invoice.|All three requested records~Only a premium advertisement~Only an unrelated receipt|The requested records document the actual loss and its cost.|Match each requested item to the relevant evidence.',
 '¿Qué registros cumplen instrucciones?|Reclamo ficticio pide fecha del evento, fotos del daño y factura de reparación.|Los tres registros pedidos~Solo anuncio de prima~Solo recibo ajeno|Registros pedidos documentan pérdida real y su costo.|Relaciona cada elemento pedido con evidencia relevante.',
 'Que registros atendem instruções?|Pedido fictício exige data do evento, fotos do dano e nota do reparo.|Os três registros pedidos~Só anúncio de prêmio~Só recibo alheio|Registros pedidos documentam perda real e seu custo.|Ligue cada item pedido à prova relevante.']),
 q('guided-02','guided',[
 'Which deadline applies to notice?|Fictional instructions: notify by May 8; invoices may follow by May 20.|May 8~May 20 for everything~Whenever repair ends|The notice deadline differs from the later invoice deadline.|Track each required action with its own stated date.',
 '¿Qué fecha aplica al aviso?|Instrucciones ficticias: avisar antes o el 8 de mayo; facturas hasta 20 de mayo.|8 de mayo~20 de mayo para todo~Cuando acabe reparación|Fecha de aviso difiere de fecha posterior de facturas.|Registra cada acción requerida con su propia fecha.',
 'Que data vale para aviso?|Instruções fictícias: avisar até 8 de maio; notas podem seguir até 20 de maio.|8 de maio~20 de maio para tudo~Quando acabar reparo|Data do aviso difere da data posterior das notas.|Registre cada ação exigida com sua própria data.']),
 q('practice-01','practice',[
 'What proves the submission trail?|A claim was submitted through the official portal.|Saved copy and receipt reference~Memory alone~Deleting the confirmation|A saved copy and receipt document what was sent and when.|Preserve evidence of submission as well as evidence of loss.',
 '¿Qué prueba entrega del reclamo?|Reclamo fue entregado por portal oficial.|Copia guardada y folio de recepción~Solo memoria~Borrar confirmación|Copia y recepción documentan qué se envió y cuándo.|Conserva evidencia de entrega además de evidencia de pérdida.',
 'O que prova envio do pedido?|Pedido foi enviado pelo portal oficial.|Cópia salva e protocolo de recebimento~Só memória~Apagar confirmação|Cópia e recebimento documentam o que foi enviado e quando.|Guarde prova de envio além de prova da perda.']),
 q('practice-02','practice',[
 'What should happen with an unclear requirement?|Instructions request a document that is unavailable; the deadline is near.|Ask official claim channel promptly~Invent a document~Assume the deadline vanished|The official channel can clarify acceptable evidence and next steps.|Raise the issue promptly and keep its written response.',
 '¿Qué hacer con requisito poco claro?|Instrucciones piden documento no disponible; fecha límite está cerca.|Consultar pronto canal oficial de reclamos~Inventar documento~Suponer fecha borrada|Canal oficial puede aclarar evidencia aceptable y siguientes pasos.|Consulta pronto y guarda respuesta escrita.',
 'O que fazer com exigência pouco clara?|Instruções pedem documento indisponível; prazo está perto.|Consultar logo canal oficial de pedidos~Inventar documento~Supor prazo apagado|Canal oficial pode esclarecer prova aceita e próximos passos.|Consulte logo e guarde resposta escrita.']),
 q('practice-03','practice',[
 'Does a receipt confirm coverage approval?|The portal confirms only that the claim was received.|No~Yes, receipt means approved~Yes, every report guarantees payment|Receipt confirms submission, not the final coverage decision.|Distinguish acknowledgment from approval and payment.',
 '¿Recepción confirma aprobación de cobertura?|Portal solo confirma que recibió reclamo.|No~Sí, recepción significa aprobado~Sí, todo reporte garantiza pago|Recepción confirma entrega, no decisión final de cobertura.|Distingue recepción de aprobación y pago.',
 'Recebimento confirma aprovação de cobertura?|Portal só confirma que recebeu pedido.|Não~Sim, recebimento significa aprovado~Sim, todo aviso garante pagamento|Recebimento confirma envio, não decisão final da cobertura.|Separe recebimento de aprovação e pagamento.']),
 q('transfer-01','transfer',[
 'Which action preserves claims?|Fictional terms require notice today, then receipts later; receipts are not ready.|Notify today; preserve reference and receipts~Wait until receipts are ready~Send unrelated receipts instead|The first deadline still applies while supporting receipts follow later.|Follow each stated deadline and retain the submission trail.',
 '¿Qué acción preserva este reclamo?|Términos ficticios exigen aviso hoy y recibos después; recibos aún no están listos.|Avisar hoy; guardar folio y recibos~Esperar recibos listos~Enviar recibos ajenos|Primera fecha sigue aplicando aunque recibos lleguen después.|Sigue cada fecha indicada y conserva evidencia de entrega.',
 'Que ação preserva este pedido?|Termos fictícios exigem aviso hoje e recibos depois; recibos ainda não estão prontos.|Avisar hoje; guardar protocolo e recibos~Esperar recibos prontos~Enviar recibos alheios|Primeiro prazo segue valendo mesmo com recibos depois.|Siga cada prazo dado e guarde prova de envio.']),
]),
teach(d,10,'Overlapping Coverage|Examina protección que se solapa|Examine proteção que se sobrepõe',
 'Two policies can cover similar risks while paying differently; inspect coordination, limits and extra benefits before calling the overlap useless.|Dos pólizas pueden cubrir riesgos similares y pagar distinto; revisa coordinación, límites y beneficios extra antes de llamar inútil solapamiento.|Dois seguros podem cobrir o mesmo risco. Veja como pagam e o que cada um soma antes de dizer que um sobra.',
 'Two policies automatically double reimbursement, or every overlap has no possible value.',[
 ex('example-01','Overlap is a question|Solapamiento requiere preguntas|Sobreposição exige perguntas','Compare payments, coordination rules and extra benefits across policies. Similar titles do not settle value.|Compara pagos, reglas de suma y beneficios extra entre pólizas. Títulos similares no deciden valor.|Compare o que cada seguro paga e como soma com o outro. Nomes parecidos não bastam.'),
 q('guided-01','guided',[
 'Do these terms promise double reimbursement?|Fictional policies reimburse the same repair; combined payment cannot exceed repair cost.|No~Yes, two policies double it~Yes, two premiums override terms|The stated combined cap prevents reimbursement beyond the repair cost.|Apply the coordination rule rather than counting policy titles.',
 '¿Términos prometen doble pago?|Pólizas ficticias reembolsan mismo arreglo; pago combinado no puede superar costo del arreglo.|No~Sí, dos pólizas duplican~Sí, dos primas anulan términos|Tope combinado indicado evita pago sobre costo del arreglo.|Aplica regla de coordinación, no cuentes títulos de pólizas.',
 'Termos prometem pagamento duplo?|Apólices fictícias pagam mesmo conserto; pagamento combinado não pode superar custo do conserto.|Não~Sim, duas apólices dobram~Sim, dois prêmios anulam termos|Teto combinado dado evita pagamento acima do custo do conserto.|Aplique regra de soma, não conte títulos de apólices.']),
 q('guided-02','guided',[
 'Does another policy add value?|Fictional A pays covered repairs; B separately pays stated transport costs A excludes.|Yes, transport benefit differs~No, any overlap is useless~Yes, all costs double|The stated transport benefit is distinct from repair reimbursement.|Compare actual benefits before dismissing the second policy.',
 '¿Segunda póliza podría agregar beneficio distinto?|A ficticia paga arreglos cubiertos; B paga aparte transporte indicado que A excluye.|Sí, beneficio de transporte difiere~No, todo solapamiento es inútil~Sí, todo costo se duplica|Beneficio indicado de transporte difiere del pago de arreglo.|Compara beneficios reales antes de descartar segunda póliza.',
 'Segunda apólice pode somar benefício distinto?|A fictícia paga consertos cobertos; B paga à parte transporte dado que A exclui.|Sim, benefício de transporte difere~Não, toda parte em comum é inútil~Sim, todo custo dobra|Benefício dado de transporte difere do pagamento de conserto.|Compare pagamentos reais antes de descartar segunda apólice.']),
 q('practice-01','practice',[
 'What precedes removing one policy?|Two policy titles sound similar; payment conditions have not been compared.|Compare terms and remaining protection~Cancel the older one immediately~Assume both pay identically|Similar titles do not establish duplicate benefits or equivalent protection.|Check what protection would remain before changing coverage.',
 '¿Qué falta antes de quitar una póliza?|Títulos de dos pólizas suenan similares, pero no se compararon condiciones de pago.|Comparar términos y protección restante~Cancelar más antigua de inmediato~Suponer que ambas pagan igual|Títulos similares no prueban beneficios duplicados ni protección equivalente.|Revisa qué protección quedaría antes de cambiar cobertura.',
 'O que falta antes de tirar uma apólice?|Títulos de duas apólices parecem iguais, mas condições de pagamento não foram comparadas.|Comparar termos e proteção restante~Cancelar mais antiga logo~Supor que ambas pagam igual|Títulos parecidos não provam pagamentos duplicados nem proteção igual.|Veja que proteção restaria antes de mudar cobertura.']),
 q('practice-02','practice',[
 'Which wording suggests overlap worth checking?|Both fictional policies cover the same event, expense and period.|Same event, expense and period~Different household names alone~Equal premiums alone|Matching event, expense and period identifies potential overlap.|Next check payment coordination and differences in benefits.',
 '¿Qué texto sugiere solapamiento por revisar?|Ambas pólizas ficticias cubren mismo evento, gasto y periodo.|Mismo evento, gasto y periodo~Solo nombres distintos del hogar~Solo primas iguales|Coincidir evento, gasto y periodo identifica posible solapamiento.|Luego revisa coordinación de pagos y diferencias de beneficios.',
 'Que texto sugere parte em comum por conferir?|Ambas apólices fictícias cobrem mesmo evento, gasto e período.|Mesmo evento, gasto e período~Só nomes distintos da família~Só prêmios iguais|Coincidir evento, gasto e período identifica possível parte em comum.|Depois confira regras de soma e o que cada seguro paga.']),
 q('practice-03','practice',[
 'Can the extra payout be assumed?|Second policy is advertised as supplemental; its payment rule is missing.|No, verify the actual rule~Yes, supplemental means unlimited~Yes, another premium proves payment|The label does not establish how much the second policy pays.|Read its conditions and coordination with existing coverage.',
 '¿Puede suponerse pago extra?|Segunda póliza se anuncia complementaria; falta regla de pago.|No, verificar regla real~Sí, complementaria significa ilimitada~Sí, otra prima prueba pago|Etiqueta no establece cuánto paga segunda póliza.|Lee condiciones y coordinación con cobertura existente.',
 'Pode supor pagamento extra?|Segunda apólice é anunciada como extra; falta regra de pagamento.|Não, verificar regra real~Sim, extra significa ilimitada~Sim, outro prêmio prova pagamento|Nome não define quanto paga segunda apólice.|Leia condições e soma com cobertura existente.']),
 q('transfer-01','transfer',[
 'Compare what?|Employer and personal travel cover may overlap; limits, exclusions and continued eligibility differ.|Net protection and cost under both~That overlap is always waste~That every claim doubles|Different terms can change the protection each arrangement actually provides.|Compare the combined rules before deciding whether coverage is redundant.',
 '¿Qué debe establecer comparación?|Coberturas laboral y personal de viaje pueden solaparse; límites, exclusiones y elegibilidad continua difieren.|Protección neta y costo de ambas~Que solapamiento siempre desperdicia~Que todo reclamo se duplica|Términos distintos pueden cambiar protección real de cada conjunto.|Compara reglas combinadas antes de decidir si cobertura sobra.',
 'O que comparar aqui?|Coberturas de viagem do emprego e pessoal podem se somar; limites, riscos de fora e quem segue coberto diferem.|Proteção conjunta e custo de ambas~Que parte em comum sempre desperdiça~Que todo pedido dobra|Termos distintos podem mudar proteção real de cada conjunto.|Compare regras combinadas antes de decidir se cobertura sobra.']),
]),
teach(d,11,'Changing Needs|Revisa protección cuando cambia vida|Reveja proteção quando vida muda',
 'Changed dependents or obligations can alter protection needs; reassess the gap before changing coverage.|Nuevo dependiente u obligación distinta puede cambiar pérdida que hogar soporta; reevalúa necesidades y recursos antes de cambiar cobertura.|Novo dependente ou obrigação distinta pode mudar perda que família suporta; reavalie necessidades e recursos antes de mudar cobertura.',
 'Protection needs never change, or every life change automatically requires a larger policy.',[
 ex('example-01','Recalculate the need|Vuelve a calcular necesidad|Calcule de novo a necessidade','List who depends on the income, continuing obligations and available resources. Recheck the gap after a meaningful life change.|Lista quién depende del ingreso, obligaciones que siguen y recursos disponibles. Revisa faltante tras cambio importante de vida.|Liste quem depende da renda, obrigações que seguem e recursos disponíveis. Reveja falta após mudança importante na vida.'),
 q('guided-01','guided',[
 'What changed in the protection need?|A new dependent relies on household income; current resources and benefits are unchanged.|Support needs may rise~Nothing can change~All old coverage becomes invalid|A new dependent can increase the support gap if income stops.|Reassess actual needs against existing resources and benefits.',
 '¿Qué cambió en necesidad de protección?|Nuevo dependiente requiere ingreso del hogar; recursos y beneficios actuales no cambiaron.|Necesidad de apoyo puede crecer~Nada puede cambiar~Toda cobertura anterior pierde validez|Nuevo dependiente puede ampliar faltante si ingreso se detiene.|Reevalúa necesidades reales frente a recursos y beneficios existentes.',
 'O que mudou na necessidade de proteção?|Novo dependente precisa da renda familiar; recursos e benefícios atuais não mudaram.|Necessidade de apoio pode crescer~Nada pode mudar~Toda cobertura anterior perde validade|Novo dependente pode ampliar falta se renda parar.|Reavalie necessidades reais frente a recursos e benefícios existentes.']),
 q('guided-02','guided',[
 'Does this change only increase needs?|A major debt is fully repaid; other needs and resources remain unchanged.|No, that obligation falls~Yes, needs always rise~Yes, ignore the repayment|Repaying the debt removes that obligation from the assessment.|Update both increases and decreases in continuing commitments.',
 '¿Este cambio solo aumenta necesidades?|Deuda mayor queda pagada; demás necesidades y recursos siguen iguales.|No, esa obligación baja~Sí, necesidades siempre suben~Sí, ignorar pago|Pagar deuda quita esa obligación de evaluación.|Actualiza aumentos y reducciones de compromisos que siguen.',
 'Esta mudança só aumenta necessidades?|Dívida grande fica quitada; demais necessidades e recursos seguem iguais.|Não, essa obrigação cai~Sim, necessidades sempre sobem~Sim, ignorar quitação|Quitar dívida tira essa obrigação da análise.|Atualize aumentos e reduções dos compromissos que seguem.']),
 q('practice-01','practice',[
 'What should be verified after changing employment?|Previous protection was tied to the former employment contract.|Whether and when it continues~Assume lifelong coverage~Assume every personal policy ends|Employment-linked benefits may depend on terms that have changed.|Verify actual continuation terms and any resulting gap.',
 '¿Qué verificar tras cambiar empleo?|Protección anterior dependía del contrato laboral previo.|Si continúa y hasta cuándo~Suponer cobertura de por vida~Suponer que toda póliza personal termina|Beneficios laborales pueden depender de términos que cambiaron.|Verifica condiciones reales de continuidad y posible faltante.',
 'O que verificar após mudar emprego?|Proteção anterior dependia do antigo contrato de emprego.|Se continua e até quando~Supor cobertura por toda vida~Supor que toda apólice pessoal acaba|Benefícios do emprego podem depender de termos que mudaram.|Verifique condições reais de continuidade e possível falta.']),
 q('practice-02','practice',[
 'Which inputs need updating?|A household starts supporting an older relative regularly.|New support obligation and available resources~Only current income~Only last year’s income|The new recurring support changes the household’s commitments.|Use current obligations and resources rather than outdated assumptions.',
 '¿Qué datos necesitan actualizarse?|Hogar comienza apoyo regular a familiar mayor.|Nueva obligación de apoyo y recursos disponibles~Solo ingreso actual~Solo ingreso del año pasado|Nuevo apoyo recurrente cambia compromisos del hogar.|Usa obligaciones y recursos actuales, no supuestos pasados.',
 'Que dados precisam mudar?|Família começa apoio regular a parente idoso.|Novo dever de apoio e recursos disponíveis~Só renda atual~Só renda do ano passado|Novo apoio recorrente muda compromissos da família.|Use deveres e recursos atuais, não suposições passadas.']),
 q('practice-03','practice',[
 'Does change dictate a product?|Needs changed, but current coverage, resources and terms have not been reviewed.|No, reassess the gap first~Yes, buy the largest policy~Yes, cancel all protection|The change triggers reassessment, not an automatic product decision.|Check the actual gap before choosing how to address it.',
 '¿Cambio dicta producto de inmediato?|Necesidades cambiaron, pero no se revisaron cobertura, recursos ni términos actuales.|No, reevaluar faltante primero~Sí, comprar póliza mayor~Sí, cancelar toda protección|Cambio activa reevaluación, no decisión automática de producto.|Revisa faltante real antes de elegir cómo cubrirlo.',
 'Mudança dita produto de imediato?|Necessidades mudaram, mas cobertura, recursos e termos atuais não foram revistos.|Não, reavaliar falta primeiro~Sim, comprar maior apólice~Sim, cancelar toda proteção|Mudança pede reavaliação, não decisão automática de produto.|Veja falta real antes de escolher como cobri-la.']),
 q('transfer-01','transfer',[
 'Which reassessment fits this household?|A dependent now earns independently while a new care obligation begins.|Update both support changes and resources~Assume needs only fell~Keep every old assumption|The two changes can affect needs in different directions.|Reassess the whole support gap using current facts.',
 '¿Qué reevaluación corresponde al hogar?|Dependiente ya gana por su cuenta mientras inicia nueva obligación de cuidados.|Actualizar ambos cambios de apoyo y recursos~Suponer que necesidades solo bajaron~Conservar todo supuesto anterior|Dos cambios pueden afectar necesidades en sentidos distintos.|Reevalúa faltante completo de apoyo con hechos actuales.',
 'Que reavaliação cabe à família?|Dependente já ganha por conta própria enquanto começa novo dever de cuidado.|Atualizar ambas mudanças de apoio e recursos~Supor que necessidades só caíram~Manter toda suposição antiga|Duas mudanças podem afetar necessidades em sentidos distintos.|Reavalie toda falta de apoio com fatos atuais.']),
]),
teach(d,12,'Protection Projections|Separa protección de cifras futuras|Separe proteção de valores futuros',
 'Combined offers show contractual protection and uncertain future values; read each on its own terms.|Oferta de seguro y ahorro muestra pagos por contrato y cifras futuras inciertas. Lee sus términos por separado.|Oferta de seguro e poupança mostra pagamentos por contrato e valores futuros incertos. Leia seus termos em separado.',
 'An illustrated investment value is the same promise as a contractual insurance benefit.',[
 ex('example-01','Two different kinds of numbers|Dos clases distintas de cifras|Duas classes distintas de valores','Separate the contractual covered benefit from projected investment values. Projections depend on assumptions; check fees, conditions and access separately.|Separa beneficio cubierto por contrato de valores de inversión proyectados. Proyecciones dependen de supuestos; revisa costos, condiciones y acceso aparte.|Separe benefício coberto do contrato de valores de investimento previstos. Projeções dependem de suposições; veja custos, condições e acesso à parte.'),
 q('guided-01','guided',[
 'Which is a projection?|Fictional offer lists a defined covered benefit and a future account estimate dependent on assumed returns.|The future account estimate~The defined covered event~Every contract condition|The account estimate depends on assumptions about future returns.|Distinguish the illustrated value from the contractual benefit.',
 '¿Cuál es proyección?|Oferta ficticia lista beneficio cubierto definido y estimación de cuenta futura dependiente de ganancias supuestas.|Estimación futura de cuenta~Evento cubierto definido~Toda condición por contrato|Estimación de cuenta depende de supuestos de rendimiento futuro.|Distingue valor ilustrado de beneficio por contrato.',
 'Qual é valor previsto?|Oferta fictícia lista benefício coberto definido e valor previsto de conta futura dependente de ganhos supostos.|Estimativa futura da conta~Evento coberto definido~Toda condição do contrato|Estimativa da conta depende de suposições de ganho futuro.|Separe valor ilustrado de benefício do contrato.']),
 q('guided-02','guided',[
 'What must be checked for protection?|A combined offer highlights account growth but omits the insured event and exclusions.|Covered event and exclusions~Only the growth picture~Only projected investment returns|The missing protection terms prevent assessing the insurance benefit.|Investment illustrations do not supply missing coverage conditions.',
 '¿Qué revisar para protección?|Oferta combinada destaca crecimiento de cuenta pero omite evento asegurado y exclusiones.|Evento cubierto y exclusiones~Solo gráfica de crecimiento~Solo rendimientos previstos|Términos faltantes impiden evaluar beneficio del seguro.|Ilustraciones de inversión no completan condiciones faltantes de cobertura.',
 'O que conferir para proteção?|Oferta combinada destaca crescimento da conta mas omite evento segurado e exclusões.|Evento coberto e exclusões~Só gráfico de crescimento~Só retornos projetados|Termos faltantes impedem avaliar benefício do seguro.|Exemplos de investimento não completam condições faltantes da cobertura.']),
 q('practice-01','practice',[
 'Does this promise final value?|Fictional illustration explicitly states that future account values vary with returns and charges.|No~Yes, every printed value is promised~Yes, insurance removes investment uncertainty|The stated account value varies with its underlying assumptions.|Read the illustration’s conditions rather than treating estimates as promises.',
 '¿Ejemplo promete valor final?|Ejemplo ficticia indica que valores futuros de cuenta varían con ganancias y cargos.|No~Sí, toda cifra impresa está prometida~Sí, seguro elimina incertidumbre de inversión|Valor indicado de cuenta varía con sus supuestos.|Lee condiciones de ejemplo sin tratar estimaciones como promesas.',
 'Exemplo promete valor final?|Exemplo fictício indica que valores futuros da conta variam com ganhos e taxas.|Não~Sim, todo valor impresso é promessa~Sim, seguro elimina risco do investimento|Valor dado da conta varia com suas suposições.|Leia condições do exemplo sem tratar valores previstos como promessas.']),
 q('practice-02','practice',[
 'What else matters for access?|Projected account value is shown, but early withdrawal charges and timing are omitted.|Withdrawal conditions~Only the tallest projected bar~Only the insured person’s initials|A projected balance does not establish accessible withdrawal proceeds.|Check charges, timing and contractual access restrictions.',
 '¿Qué más importa para acceso?|Se muestra valor proyectado, pero omite cargos y plazos de retiro anticipado.|Condiciones de retiro~Solo barra proyectada más alta~Solo iniciales de persona asegurada|Saldo proyectado no establece cuánto puedes retirar.|Revisa cargos, plazos y reglas de acceso del contrato.',
 'O que mais importa para acesso?|Mostra valor previsto, mas omite taxas e prazos de saque antes do prazo.|Condições de saque~Só barra projetada mais alta~Só iniciais da pessoa segurada|Saldo previsto não define quanto pode sacar.|Veja taxas, prazos e regras do contrato de acesso.']),
 q('practice-03','practice',[
 'Can a larger projection prove better protection?|Two offers show different account projections, but covered benefits have not been compared.|No~Yes, bigger estimate means broader coverage~Yes, fees cannot matter|A larger account projection does not establish a broader covered benefit.|Compare protection terms separately from investment assumptions.',
 '¿Proyección mayor prueba mejor protección?|Dos ofertas muestran cifras futuras distintas de cuenta, pero no se compararon beneficios cubiertos.|No~Sí, estimación mayor significa cobertura amplia~Sí, cargos no importan|Proyección mayor de cuenta no prueba beneficio cubierto más amplio.|Compara términos de protección aparte de supuestos de inversión.',
 'Projeção maior prova melhor proteção?|Duas ofertas mostram valores futuros distintos de conta, mas benefícios cobertos não foram comparados.|Não~Sim, valor previsto maior significa cobertura ampla~Sim, taxas não importam|Projeção maior da conta não prova benefício coberto mais amplo.|Compare termos da proteção à parte das suposições de investimento.']),
 q('transfer-01','transfer',[
 'Which reading fits?|Fictional brochure defines conditional death cover and separate growth using assumed returns.|Conditional protection plus an uncertain projection~One promise covering every number~Projection alone defines coverage|The covered benefit and growth estimate rest on different terms.|Separate the contractual protection from assumption-based future values.',
 '¿Qué lectura corresponde a oferta?|Folleto ficticio define cobertura por fallecimiento con condiciones y muestra crecimiento con rendimiento supuesto.|Protección condicionada y proyección incierta~Una promesa para toda cifra~Solo proyección define cobertura|Beneficio cubierto y crecimiento estimado tienen términos distintos.|Separa protección por contrato de valores futuros basados en supuestos.',
 'Que leitura cabe à oferta?|Folheto fictício define cobertura por morte com condições e mostra crescimento com ganho suposto.|Proteção condicional e valor previsto incerto~Uma promessa para todo valor~Só valor previsto define cobertura|Benefício coberto e crescimento estimado têm termos distintos.|Separe proteção do contrato de valores futuros baseados em suposições.']),
]),
];
