export const localizedObjectives = {
 'saving-resilience-01':['Separar dinero para una cuenta previsible de dinero para un contratiempo imprevisto.','Separar dinheiro para uma conta previsível de dinheiro para um contratempo imprevisto.'],
 'saving-resilience-02':['Estimar gastos esenciales durante una interrupción indicada del ingreso.','Estimar gastos essenciais durante uma interrupção dada da renda.'],
 'saving-resilience-03':['Establecer meta inicial de reserva usando riesgos reales del escenario y aportes viables.','Definir meta inicial de reserva usando riscos reais do cenário e aportes viáveis.'],
 'saving-resilience-04':['Elegir dónde mantener reserva cercana usando condiciones indicadas de acceso, seguridad y cargos.','Escolher onde manter reserva próxima usando condições dadas de acesso, segurança e taxas.'],
 'saving-resilience-05':['Calcular tiempo para alcanzar meta con aporte fijo viable sin rendimiento supuesto.','Calcular tempo para atingir meta com aporte fixo viável sem rendimento suposto.'],
 'saving-resilience-06':['Ajustar plan tras aporte faltante sin ocultar el faltante.','Ajustar plano após aporte perdido sem ocultar a falta.'],
 'saving-resilience-07':['Elegir cuándo una transferencia automática crearía faltante para pagos.','Identificar quando uma transferência automática criaria falta para pagamentos.'],
 'saving-resilience-08':['Asignar dinero inesperado entre obligaciones urgentes y metas indicadas sin suponer regla universal.','Distribuir dinheiro inesperado entre deveres urgentes e metas dadas sem supor regra universal.'],
 'saving-resilience-09':['Decidir si gasto indicado corresponde al propósito de una reserva de emergencia.','Decidir se gasto dado cabe na finalidade de uma reserva de emergência.'],
 'saving-resilience-10':['Crear plan de reposición tras usar parte de una reserva.','Criar plano de reposição após usar parte de uma reserva.'],
 'purchase-decisions-01':['Comparar precios unitarios tras convertir cantidades a la misma unidad.','Comparar preços unitários após converter quantidades à mesma unidade.'],
 'purchase-decisions-02':['Calcular precio final incluyendo todos los cargos obligatorios indicados.','Calcular preço final incluindo todos os custos obrigatórios dados.'],
 'purchase-decisions-03':['Calcular precio después de un descuento porcentual.','Calcular preço após um desconto percentual.'],
 'purchase-decisions-04':['Calcular descuentos sucesivos sin sumar sus porcentajes.','Calcular descontos sucessivos sem somar seus percentuais.'],
 'purchase-decisions-05':['Revisar si el gasto mínimo de una promoción encarece la compra prevista.','Conferir se o gasto mínimo de uma promoção encarece a compra prevista.'],
 'purchase-decisions-06':['Comparar costos totales de propiedad durante el mismo periodo indicado.','Comparar custos totais de posse durante o mesmo período dado.'],
 'purchase-decisions-07':['Distinguir garantía, política de devolución y plan de protección comprado por separado.','Distinguir garantia, política de devolução e plano de proteção comprado em separado.'],
 'purchase-decisions-08':['Identificar renovación, cancelación y costos de salida de un contrato antes de aceptarlo.','Identificar renovação, cancelamento e custos de saída de um contrato antes de aceitar.'],
 'purchase-decisions-09':['Comparar precios de contado y en cuotas mediante calendarios completos de pago.','Comparar preços à vista e em parcelas por calendários completos de pagamento.'],
 'purchase-decisions-10':['Reconocer comparaciones engañosas que usan cantidades o periodos distintos.','Reconhecer comparações enganosas que usam quantidades ou períodos distintos.'],
 'purchase-decisions-11':['Elegir qué información faltante obtener antes de una comparación de compra defendible.','Escolher que informação ausente obter antes de uma comparação de compra defensável.'],
 'purchase-decisions-12':['Decidir entre reparar, reemplazar y esperar usando costos y necesidades funcionales indicadas.','Decidir entre consertar, trocar e esperar usando custos e necessidades funcionais dadas.'],
 'financial-landscape-01':['Verificar identidad y actividad permitida de un proveedor financiero mediante registro oficial pertinente.','Verificar identidade e atividade permitida de um provedor financeiro pelo registro oficial relevante.'],
 'financial-landscape-02':['Distinguir regulación del proveedor de protección contra toda posible pérdida.','Distinguir regulação do provedor de proteção contra toda possível perda.'],
 'financial-landscape-03':['Revisar alcance y condiciones de elegibilidad de una afirmación local de protección de depósitos.','Conferir alcance e condições para cobertura de uma alegação local de proteção de depósitos.'],
 'financial-landscape-04':['Preparar una queja con solución solicitada clara y pruebas de operación pertinentes.','Preparar uma reclamação com solução pedida clara e provas relevantes da transação.'],
 'financial-landscape-05':['Identificar vía oficial de escalamiento cuando la respuesta del proveedor no resuelve la queja.','Identificar via oficial para recorrer quando a resposta do provedor não resolve a queixa.'],
 'financial-landscape-06':['Calcular cuánto recibe un destinatario tras comisión de remesa y tipo de cambio indicado.','Calcular quanto recebe um destinatário após taxa de remessa e câmbio dado.'],
 'financial-landscape-07':['Comparar remesas usando monto recibido, tiempo y condiciones de cobro.','Comparar remessas usando valor recebido, prazo e condições de saque.'],
 'financial-landscape-08':['Identificar un margen en conversión de moneda cuando se proporciona tipo de referencia.','Identificar uma margem na conversão de moeda quando se fornece câmbio de referência.'],
 'financial-landscape-09':['Distinguir afirmación sostenible específica verificable de etiqueta de producto financiero sin respaldo.','Distinguir alegação sustentável específica verificável de rótulo de produto financeiro sem apoio.'],
 'financial-landscape-10':['Revisar quién recibe datos financieros y cómo retirar consentimiento antes de habilitar un servicio de intercambio.','Conferir quem recebe dados financeiros e como retirar consentimento antes de ativar serviço de compartilhamento.'],
 'shared-finances-01':['Comparar aportes compartidos iguales y proporcionales al ingreso bajo reglas acordadas explícitas.','Comparar aportes conjuntos iguais e proporcionais à renda sob regras combinadas explícitas.'],
 'shared-finances-02':['Separar acceso a cuentas de propiedad jurídica y responsabilidad de deuda que requieren verificación local.','Separar acesso a contas de posse legal e responsabilidade por dívida que exigem verificação local.'],
 'shared-finances-03':['Crear un acuerdo de pagos compartidos que identifique monto, responsable y fecha de revisión.','Criar um acordo de pagamentos conjuntos que identifique valor, responsável e data de revisão.'],
 'shared-finances-04':['Reconocer coerción financiera e identificar apoyo seguro sin exigir confrontación.','Reconhecer coação financeira e identificar apoio seguro sem exigir confronto.'],
 'shared-finances-05':['Revisar un plan para un periodo indicado de cuidados con menos trabajo pagado.','Rever um plano para um período dado de cuidados com menos trabalho pago.'],
 'shared-finances-06':['Distinguir un regalo asequible de un préstamo familiar que requiere expectativas claras de devolución.','Distinguir um presente acessível de um empréstimo familiar que exige expectativas claras de devolução.'],
 'shared-finances-07':['Identificar registros de cuentas, contratos y acceso necesarios cuando un hogar se separa.','Identificar registros de contas, contratos e acesso necessários quando uma família se separa.'],
 'shared-finances-08':['Identificar preguntas de herencia y facultades de decisión que requieren orientación local calificada tras fallecimiento o incapacidad.','Identificar questões de herança e poderes de decisão que exigem orientação local qualificada após morte ou incapacidade.'],
  'housing-transport-01': ['Separar costos iniciales de mudanza de costos mensuales continuos.', 'Separar custos iniciais da mudança de custos mensais contínuos.'],
  'housing-transport-02': ['Comparar costos mensuales de vivienda incluyendo servicios y transporte.', 'Comparar custos mensais da moradia incluindo serviços e transporte.'],
  'housing-transport-03': ['Leer condiciones de depósito, aviso y reparaciones de un contrato de renta ficticio.', 'Ler condições de depósito, aviso e consertos de um contrato fictício de aluguel.'],
  'housing-transport-04': ['Distinguir precio de compra de costos de financiamiento, operación y mantenimiento.', 'Distinguir preço de compra de custos de financiamento, transação e manutenção.'],
  'housing-transport-05': ['Explicar cómo el enganche reduce el préstamo sin asegurar capacidad de pago.', 'Explicar como a entrada reduz o empréstimo sem assegurar capacidade de pagar.'],
  'housing-transport-06': ['Recalcular capacidad de pago de vivienda ante menor ingreso o mayor pago de tasa variable.', 'Recalcular capacidade de pagar moradia com menor renda ou maior prestação de taxa variável.'],
  'housing-transport-07': ['Comparar rentar y comprar durante un horizonte indicado sin suponer aumento del precio de vivienda.', 'Comparar alugar e comprar num prazo dado sem supor aumento do preço da casa.'],
  'housing-transport-08': ['Comparar costos totales de vehículo incluyendo mantenimiento, seguro y pérdida de valor.', 'Comparar custos totais de veículo incluindo manutenção, seguro e perda de valor.'],
  'housing-transport-09': ['Comparar ofertas de financiamiento de vehículo con enganche, cuotas y pago final adicional.', 'Comparar ofertas de financiamento de veículo com entrada, parcelas e pagamento final adicional.'],
  'housing-transport-10': ['Comparar arrendar y comprar considerando kilometraje, devolución y costos totales.', 'Comparar arrendar e comprar considerando quilometragem, devolução e custos totais.'],
  'housing-transport-11': ['Planear mantenimiento y reparaciones por separado del presupuesto de compra.', 'Planejar manutenção e consertos separados do orçamento de compra.'],
  'housing-transport-12': ['Elegir opciones viables de vivienda y transporte que cumplan restricciones de acceso y tiempo.', 'Escolher opções viáveis de moradia e transporte que atendam limites de acesso e tempo.'],
  'retirement-future-01': ['Distinguir la necesidad prevista de gasto durante el retiro de un saldo de cuenta proyectado.', 'Separar a necessidade prevista de gasto na aposentadoria de um saldo de conta projetado.'],
  'retirement-future-02': ['Identificar las funciones distintas de apoyos públicos, planes patronales y ahorro personal.', 'Identificar as funções distintas de benefícios públicos, planos patronais e poupança pessoal.'],
  'retirement-future-03': ['Leer condiciones de aportación y propiedad de un plan patronal ficticio de retiro.', 'Ler condições de aporte e propriedade de um plano patronal fictício de aposentadoria.'],
  'retirement-future-04': ['Comparar empezar aportaciones antes o después bajo los mismos supuestos explícitos de proyección.', 'Comparar começar aportes antes ou depois sob as mesmas hipóteses explícitas de projeção.'],
  'retirement-future-05': ['Identificar cómo afectan las comisiones una proyección de largo plazo sin tratarla como garantizada.', 'Identificar como tarifas afetam uma projeção de longo prazo sem tratá-la como garantida.'],
  'retirement-future-06': ['Reconocer inflación y longevidad como riesgos distintos para un plan de gastos de retiro.', 'Reconhecer inflação e longevidade como riscos distintos para um plano de gastos na aposentadoria.'],
  'retirement-future-07': ['Revisar restricciones de acceso antes de tratar activos de retiro como reserva de emergencia.', 'Conferir restrições de acesso antes de tratar ativos de aposentadoria como reserva de emergência.'],
  'retirement-future-08': ['Identificar cómo pérdidas tempranas afectan retiros de una cartera ficticia de retiro.', 'Identificar como perdas iniciais afetam saques de uma carteira fictícia de aposentadoria.'],
  'retirement-future-09': ['Reevaluar aportaciones al cambiar ingresos mientras se protegen obligaciones indispensables cercanas.', 'Reavaliar aportes quando a renda muda, preservando deveres essenciais próximos.'],
  'retirement-future-10': ['Identificar registros de beneficiarios y cuentas que deben revisarse tras un cambio importante de vida.', 'Identificar registros de beneficiários e contas que precisam ser revistos após grande mudança de vida.'],
  'tax-public-systems-01': ['Distinguir impuesto, cuota y contribución social en ejemplos con etiquetas explícitas.', 'Distinguir imposto, tarifa e contribuição social em exemplos com nomes explícitos.'],
  'tax-public-systems-02': ['Distinguir impuesto retenido durante el año del cálculo final del impuesto.', 'Separar imposto retido durante o ano do cálculo final do imposto.'],
  'tax-public-systems-03': ['Calcular impuesto en un sistema ficticio de tramos progresivos sin aplicar la tasa máxima a todo el ingreso.', 'Calcular imposto num sistema fictício de faixas progressivas sem aplicar a taxa máxima a toda a renda.'],
  'tax-public-systems-04': ['Distinguir una deducción de un crédito mediante un cálculo ficticio simplificado.', 'Distinguir uma dedução de um crédito por meio de um cálculo fictício simplificado.'],
  'tax-public-systems-05': ['Identificar registros que respaldan una declaración ficticia de ingresos o gastos.', 'Identificar registros que sustentam uma declaração fictícia de renda ou despesas.'],
  'tax-public-systems-06': ['Encontrar la fuente oficial local de un plazo u obligación fiscal sin importar reglas de otro país.', 'Encontrar a fonte oficial local de um prazo ou dever fiscal sem importar regras de outro país.'],
  'tax-public-systems-07': ['Reconocer que se deben verificar requisitos y condiciones de retiro de un apoyo antes de incluirlo en el presupuesto.', 'Reconhecer que requisitos e condições de saque de um benefício devem ser verificados antes de incluí-lo no orçamento.'],
  'tax-public-systems-08': ['Distinguir la planeación fiscal permitida de ocultar o falsificar hechos en registros financieros.', 'Separar o planejamento fiscal permitido de esconder ou falsificar fatos em registros financeiros.'],
  'investment-comparison-08': ['Identificar si un ajuste de cartera recupera la distribución indicada o solo sigue una moda reciente.', 'Identificar se um ajuste da carteira retoma a distribuição dada ou só segue uma moda recente.'],
  'investment-comparison-09': ['Identificar supuestos de impuestos, comisiones o retiros que impiden comparar justamente rendimientos netos.', 'Identificar hipóteses de impostos, tarifas ou saques que impedem comparar de forma justa rendimentos líquidos.'],
  'investment-comparison-10': ['Rechazar una promesa no verificable de rendimientos altos garantizados mediante comprobaciones independientes.', 'Rejeitar uma promessa não verificável de rendimentos altos garantidos por meio de checagens independentes.'],
  'investment-comparison-02': ['Comparar rendimientos reportados del mismo periodo con un tratamiento consistente de los pagos recibidos.', 'Comparar rendimentos relatados do mesmo período com tratamento igual dos pagamentos recebidos.'],
  'investment-comparison-03': ['Identificar información de riesgo omitida en una oferta que muestra solo su mejor rendimiento histórico.', 'Identificar dados de risco omitidos numa oferta que mostra só seu melhor rendimento passado.'],
  'investment-comparison-04': ['Comparar objetivos e inversiones de un fondo con la exposición que se pretendía obtener.', 'Comparar metas e ativos de um fundo com o risco que se pretendia assumir.'],
  'investment-comparison-05': ['Distinguir una estrategia de seguimiento de índice de una promesa de superar el mercado.', 'Distinguir uma estratégia que segue um índice de uma promessa de superar o mercado.'],
  'investment-comparison-06': ['Explicar la exposición cambiaria cuando la meta de gasto y la inversión usan monedas distintas.', 'Explicar o risco cambial quando a meta de gasto e o investimento usam moedas distintas.'],
  'investment-comparison-07': ['Identificar conflictos de interés en la forma de remunerar a quien vende una inversión.', 'Identificar conflitos de interesse na forma de remunerar quem vende um investimento.'],
  'investment-comparison-01': [
    'Calcular la ganancia de una inversión después de las comisiones explícitas de operación y mantenimiento.',
    'Calcular o ganho de uma aplicação após as tarifas explícitas de operação e manutenção.',
  ],
  'investing-foundations-01': [
    'Distinguir el dinero para invertir del dinero que debe seguir accesible para una obligación cercana.',
    'Separar o dinheiro para investir do dinheiro que deve ficar acessível para uma obrigação próxima.',
  ],
  'investing-foundations-02': [
    'Relacionar el plazo de una meta con la consecuencia de una pérdida temporal de inversión.',
    'Relacionar o prazo de uma meta com a consequência de uma perda temporária no investimento.',
  ],
  'investing-foundations-03': [
    'Distinguir la disposición a aceptar pérdidas de la capacidad financiera para absorberlas.',
    'Distinguir a disposição para aceitar perdas da capacidade financeira de suportá-las.',
  ],
  'investing-foundations-04': [
    'Distinguir los pagos de ingresos de una inversión de los cambios de su valor de venta.',
    'Separar os pagamentos de rendimento de uma aplicação das mudanças de seu valor de venda.',
  ],
  'investing-foundations-05': [
    'Distinguir poseer una acción de prestar dinero mediante un bono.',
    'Distinguir possuir uma ação de emprestar dinheiro por meio de um título de dívida.',
  ],
  'investing-foundations-06': [
    'Explicar el riesgo de crédito de un bono usando un deudor que no puede realizar un pago prometido.',
    'Explicar o risco de crédito de um título usando um devedor que não consegue fazer um pagamento prometido.',
  ],
  'investing-foundations-07': [
    'Explicar por qué puede cambiar el precio de reventa de un bono de tasa fija antes de vencer.',
    'Explicar por que o preço de revenda de um título de taxa fixa pode mudar antes do vencimento.',
  ],
  'investing-foundations-08': [
    'Identificar concentración de riesgo cuando varias inversiones dependen de la misma fuente de ingresos.',
    'Identificar concentração de risco quando vários investimentos dependem da mesma fonte de renda.',
  ],
  'investing-foundations-09': [
    'Comparar carteras ficticias diversificadas y concentradas ante un mismo problema.',
    'Comparar carteiras fictícias diversificadas e concentradas diante de um mesmo problema.',
  ],
  'investing-foundations-10': [
    'Distinguir un fondo que reúne inversiones de los activos que contiene.',
    'Distinguir um fundo que reúne investimentos dos ativos que ele possui.',
  ],
  'investing-foundations-11': [
    'Identificar restricciones de acceso que contradicen una necesidad de retiro indicada.',
    'Identificar restrições de acesso que conflitam com uma necessidade de saque informada.',
  ],
  'investing-foundations-12': [
    'Distinguir una custodia regulada de una promesa de rendimientos de mercado garantizados.',
    'Separar uma custódia regulada de uma promessa de rendimentos de mercado garantidos.',
  ],
  'investing-foundations-13': [
    'Identificar deuda usada para invertir que puede ampliar la pérdida frente a una inversión sin deuda.',
    'Identificar dívida usada para investir que pode ampliar a perda diante de uma aplicação sem dívida.',
  ],
  'investing-foundations-14': [
    'Reconocer especulación en un activo volátil sin tomar ganancias pasadas como evidencia de seguridad.',
    'Reconhecer especulação num ativo volátil sem tratar ganhos passados como evidência de segurança.',
  ],
  'insurance-risk-01': ["Distinguir una pérdida frecuente manejable de una pérdida menos frecuente y financieramente grave.","Distinguir uma perda frequente manejável de uma perda menos frequente e financeiramente grave."],
  'insurance-risk-02': ["Relacionar un riesgo indicado con prevención, reserva o transferencia sin tratar una herramienta como suficiente para todo.","Relacionar um risco dado com prevenção, reserva ou transferência sem tratar uma ferramenta como suficiente para tudo."],
  'insurance-risk-03': ["Identificar contratante, evento asegurado y beneficiario en una póliza ficticia.","Identificar titular, evento segurado e beneficiário em uma apólice fictícia."],
  'insurance-risk-04': ["Distinguir prima de deducible en términos de seguro indicados.","Distinguir prêmio de franquia em termos de seguro dados."],
  'insurance-risk-05': ["Calcular costo de bolsillo de un reclamo con deducible y límite indicados.","Calcular custo próprio de um pedido com franquia e limite dados."],
  'insurance-risk-06': ["Identificar una exclusión que impide cobertura en un escenario dado.","Identificar uma exclusão que impede cobertura em um cenário dado."],
  'insurance-risk-07': ["Comparar pólizas tras alinear coberturas, límites y deducibles.","Comparar apólices após alinhar coberturas, limites e franquias."],
  'insurance-risk-08': ["Comprobar si un periodo de espera deja sin cobertura un evento próximo indicado.","Verificar se uma carência deixa sem cobertura um evento próximo dado."],
  'insurance-risk-09': ["Identificar documentos y fechas que deben conservarse para un reclamo ficticio.","Identificar documentos e prazos que devem ser guardados para um pedido fictício."],
  'insurance-risk-10': ["Detectar coberturas que se solapan sin suponer que todo solapamiento es inútil.","Detectar coberturas que se sobrepõem sem supor que toda sobreposição é inútil."],
  'insurance-risk-11': ["Reevaluar necesidad de protección tras cambiar dependientes u obligaciones financieras.","Reavaliar necessidade de proteção após mudar dependentes ou obrigações financeiras."],
  'insurance-risk-12': ["Distinguir protección de seguro de proyección de inversión en una oferta combinada.","Distinguir proteção de seguro de projeção de investimento em uma oferta combinada."],
  'credit-products-01': ["Leer saldo, pago mínimo y fecha de vencimiento de un estado ficticio de tarjeta.","Ler saldo, pagamento mínimo e vencimento de um extrato fictício de cartão."],
  'credit-products-02': ["Distinguir fecha de corte de fecha de vencimiento del pago.","Distinguir data de fechamento da data de vencimento do pagamento."],
  'credit-products-03': ["Determinar si se cumplen condiciones indicadas para evitar intereses de una tarjeta ficticia.","Determinar se condições dadas para evitar juros de um cartão fictício foram cumpridas."],
  'credit-products-04': ["Seguir efecto de pagos de solo mínimo sobre saldo bajo calendario dado.","Acompanhar efeito de pagamentos de só mínimo no saldo sob calendário dado."],
  'credit-products-05': ["Identificar costos separados de adelanto de efectivo en contrato ficticio de tarjeta.","Identificar custos separados de saque a crédito em contrato fictício de cartão."],
  'credit-products-06': ["Colocar cuotas de varios planes de compra ahora y pago después en un mismo calendario.","Colocar parcelas de vários planos de compra agora e pagamento depois num mesmo calendário."],
  'credit-products-07': ["Distinguir facilidad de sobregiro de dinero propio en cuenta.","Distinguir limite do cheque especial de dinheiro próprio na conta."],
  'credit-products-08': ["Comparar préstamo con y sin garantía usando costos y consecuencias indicados.","Comparar empréstimo com e sem garantia usando custos e consequências dados."],
  'credit-products-09': ["Identificar obligación del garante en un acuerdo de garantía expresado claramente.","Identificar dever do fiador em um acordo de garantia expresso com clareza."],
  'credit-products-10': ["Reconocer préstamo corto costoso cuya renovación suma costo sin reducir capital.","Reconhecer empréstimo curto caro cuja renovação soma custo sem reduzir principal."],
};
