/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/num-a/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const NUM_A_SEGMENTS = [] as const;
export const NUM_A_RUBRICS = {} as const;
export const NUM_A_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
