/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/num-a/contract.ts. Do not edit: change the source and regenerate. */
import { z } from 'zod';
import { hzBase, hzServer, hzVisual } from '../shared.generated';
import type { HorizonteAgeScope } from '../types.generated';
import { ABACUS_MAX_DIGIT, ABACUS_MAX_RODS, REKENREK_BEADS } from './beads-model.generated';
import { JUMP_SIZES, LINE_MAX, MAX_JUMPS, MAX_SIZES, MIN_SIZES, ZOOM_MAX_DEPTH, ZOOM_MAX_SPAN } from './line-model.generated';
import { BALANCE_MAX_FIXED, BALANCE_MAX_LOOSE, BALANCE_MAX_WEIGHT, CLOCK_MINUTES, CLOCK_STEPS, RULER_MAX, RULER_UNITS } from './measure-model.generated';

const beadCount = z.number().int().min(0).max(REKENREK_BEADS);
const rekenrekCounts = z.tuple([beadCount, beadCount]);
const digit = z.number().int().min(0).max(ABACUS_MAX_DIGIT);
const abacusDigits = z.array(digit).min(1).max(ABACUS_MAX_RODS);
const linePosition = z.number().int().min(0).max(LINE_MAX);
const jumpSize = z.number().int().refine((size) => JUMP_SIZES.includes(size), 'An allowed jump size');
const minutes = z.number().int().min(0).max(CLOCK_MINUTES - 1);
const clockStep = z.number().int().refine((step) => CLOCK_STEPS.includes(step), 'An allowed minute step');
const weight = z.number().int().min(1).max(BALANCE_MAX_WEIGHT);
const rulerUnit = z.string().refine((unit) => RULER_UNITS.includes(unit), 'An allowed unit');

/** A05: two rows of ten beads. The payload carries only the start counts, never the answer. */
export const rekenrekPayload = z.object({ start: rekenrekCounts }).strict();
/** A06: one to four rods, each a five bead and four one beads (a digit 0-9). */
export const abacusPayload = z.object({ start: abacusDigits }).strict();
/** A12: an empty line, a start number, and the jump sizes the learner may draw. */
export const emptyLinePayload = z.object({
  start: linePosition,
  sizes: z.array(jumpSize).min(MIN_SIZES).max(MAX_SIZES).refine((sizes) => new Set(sizes).size === sizes.length, 'Distinct sizes'),
  max: z.number().int().min(1).max(MAX_JUMPS),
}).strict();
/** A13/C14: a window of whole numbers, how many times it can zoom (tenths, hundredths), and the whole number the marker starts on. */
export const zoomLinePayload = z.object({
  low: linePosition, high: linePosition, depth: z.number().int().min(1).max(ZOOM_MAX_DEPTH), start: linePosition,
}).strict().refine((value) => value.high > value.low && value.high - value.low <= ZOOM_MAX_SPAN && value.start >= value.low && value.start <= value.high, 'A window of at most 20 whole numbers that holds the start');
/** A23: the hands' start time in minutes after 12:00 and the step the minute hand moves in. */
export const clockPayload = z.object({ start: minutes, step: clockStep }).strict()
  .refine((value) => (value.start % 60) % value.step === 0, 'The start sits on the minute step');
/** A25: a bar whose near end is fixed at a mark; the learner moves the far end. */
export const rulerPayload = z.object({ unit: rulerUnit, from: z.number().int().min(0).max(RULER_MAX - 1), start: z.number().int().min(0).max(RULER_MAX), max: z.number().int().min(4).max(RULER_MAX) }).strict()
  .refine((value) => value.from < value.max && value.start >= value.from && value.start <= value.max, 'The bar sits on the ruler');
/** A26: fixed weights on each pan and loose weights to place. */
export const panBalancePayload = z.object({
  left: z.array(weight).max(BALANCE_MAX_FIXED), right: z.array(weight).max(BALANCE_MAX_FIXED), weights: z.array(weight).min(1).max(BALANCE_MAX_LOOSE),
}).strict();

export const NUM_A_SEGMENTS = [
  z.object({ ...hzBase, type: z.literal('math.rekenrek.v2'), grading: hzServer, visual: hzVisual('rekenrek'), payload: rekenrekPayload }).strict(),
  z.object({ ...hzBase, type: z.literal('math.abacus.v2'), grading: hzServer, visual: hzVisual('abacus'), payload: abacusPayload }).strict(),
  z.object({ ...hzBase, type: z.literal('math.number-line.empty.v2'), grading: hzServer, visual: hzVisual('empty-number-line'), payload: emptyLinePayload }).strict(),
  z.object({ ...hzBase, type: z.literal('math.number-line.zoom.v2'), grading: hzServer, visual: hzVisual('zoom-number-line'), payload: zoomLinePayload }).strict(),
  z.object({ ...hzBase, type: z.literal('math.clock.v2'), grading: hzServer, visual: hzVisual('analog-clock'), payload: clockPayload }).strict(),
  z.object({ ...hzBase, type: z.literal('math.ruler.v2'), grading: hzServer, visual: hzVisual('ruler'), payload: rulerPayload }).strict(),
  z.object({ ...hzBase, type: z.literal('math.pan-balance.v2'), grading: hzServer, visual: hzVisual('pan-balance'), payload: panBalancePayload }).strict(),
] as const;

export const NUM_A_RUBRICS = {
  'math.rekenrek.v2': z.object({ target: rekenrekCounts }).strict(),
  'math.abacus.v2': z.object({ target: abacusDigits }).strict(),
  'math.number-line.empty.v2': z.object({ target: linePosition }).strict(),
  'math.number-line.zoom.v2': z.object({ target: z.number().int().min(0).max(LINE_MAX * 10 ** ZOOM_MAX_DEPTH) }).strict(),
  'math.clock.v2': z.object({ target: minutes }).strict(),
  'math.ruler.v2': z.object({ target: z.number().int().min(1).max(RULER_MAX) }).strict(),
  'math.pan-balance.v2': z.object({ target: z.number().int().min(-BALANCE_MAX_WEIGHT * 10).max(BALANCE_MAX_WEIGHT * 10) }).strict(),
} as const;

export const NUM_A_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {
  'math.rekenrek.v2': { ages: [6, 9], adult: false },
  'math.abacus.v2': { ages: [6, 12], adult: false },
  'math.number-line.empty.v2': { ages: [6, 12], adult: false },
  'math.number-line.zoom.v2': { ages: [10, 12], adult: false },
  'math.clock.v2': { ages: [6, 12], adult: false },
  'math.ruler.v2': { ages: [6, 12], adult: false },
  'math.pan-balance.v2': { ages: [6, 12], adult: false },
};
