import type { HorizonteCopy } from '../boardTypes';

export const NUM_A_COPY = {
  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  undo: { role: 'action', 'en-US': 'Undo', 'es-MX': 'Deshacer', 'pt-BR': 'Desfazer' },
  total: { role: 'data', 'en-US': 'Total', 'es-MX': 'Total', 'pt-BR': 'Total' },
  more: { role: 'data', 'en-US': 'More', 'es-MX': 'Más', 'pt-BR': 'Mais' },
  less: { role: 'data', 'en-US': 'Less', 'es-MX': 'Menos', 'pt-BR': 'Menos' },
  counted: { role: 'data', 'en-US': 'counted', 'es-MX': 'contada', 'pt-BR': 'contada' },
  notCounted: { role: 'data', 'en-US': 'not counted', 'es-MX': 'sin contar', 'pt-BR': 'não contada' },

  rekenrek: { role: 'data', 'en-US': 'Rekenrek', 'es-MX': 'Marco de cuentas', 'pt-BR': 'Rekenrek' },
  row: { role: 'data', 'en-US': 'Row {n}', 'es-MX': 'Fila {n}', 'pt-BR': 'Fileira {n}' },
  bead: { role: 'data', 'en-US': 'bead {n}', 'es-MX': 'cuenta {n}', 'pt-BR': 'conta {n}' },
  slideOne: { role: 'option', 'en-US': 'Slide one bead', 'es-MX': 'Desliza una cuenta', 'pt-BR': 'Deslize uma conta' },
  slideFive: { role: 'option', 'en-US': 'Slide a block of five', 'es-MX': 'Desliza un bloque de cinco', 'pt-BR': 'Deslize um bloco de cinco' },
  backOne: { role: 'option', 'en-US': 'Slide one back', 'es-MX': 'Regresa una cuenta', 'pt-BR': 'Volte uma conta' },
  backFive: { role: 'option', 'en-US': 'Slide five back', 'es-MX': 'Regresa un bloque de cinco', 'pt-BR': 'Volte um bloco de cinco' },
  rekenrekTray: { role: 'heading', 'en-US': 'Slide beads', 'es-MX': 'Desliza cuentas', 'pt-BR': 'Deslize contas' },
  rekenrekCaption: { role: 'heading', 'en-US': 'Beads in each row', 'es-MX': 'Cuentas en cada fila', 'pt-BR': 'Contas em cada fileira' },
  colRow: { role: 'data', 'en-US': 'Row', 'es-MX': 'Fila', 'pt-BR': 'Fileira' },
  colBeads: { role: 'data', 'en-US': 'Beads', 'es-MX': 'Cuentas', 'pt-BR': 'Contas' },
  colFives: { role: 'data', 'en-US': 'Fives', 'es-MX': 'Cincos', 'pt-BR': 'Cincos' },
  colOnes: { role: 'data', 'en-US': 'Ones', 'es-MX': 'Unos', 'pt-BR': 'Uns' },
  metRekenrek: { role: 'body', 'en-US': 'You slid the beads to match the number.', 'es-MX': 'Deslizaste las cuentas para formar el número.', 'pt-BR': 'Você deslizou as contas para formar o número.' },
  hintRekenrek: { role: 'body', 'en-US': 'Not yet. Count the beads in each row.', 'es-MX': 'Aún no. Cuenta las cuentas de cada fila.', 'pt-BR': 'Ainda não. Conte as contas de cada fileira.' },

  abacus: { role: 'data', 'en-US': 'Abacus', 'es-MX': 'Ábaco', 'pt-BR': 'Ábaco' },
  placeOnes: { role: 'data', 'en-US': 'Ones', 'es-MX': 'Unidades', 'pt-BR': 'Unidades' },
  placeTens: { role: 'data', 'en-US': 'Tens', 'es-MX': 'Decenas', 'pt-BR': 'Dezenas' },
  placeHundreds: { role: 'data', 'en-US': 'Hundreds', 'es-MX': 'Centenas', 'pt-BR': 'Centenas' },
  placeThousands: { role: 'data', 'en-US': 'Thousands', 'es-MX': 'Millares', 'pt-BR': 'Milhares' },
  fiveBead: { role: 'data', 'en-US': 'five bead', 'es-MX': 'cuenta de cinco', 'pt-BR': 'conta de cinco' },
  oneBead: { role: 'data', 'en-US': 'one bead {n}', 'es-MX': 'cuenta de uno {n}', 'pt-BR': 'conta de um {n}' },
  addOne: { role: 'option', 'en-US': 'Add one', 'es-MX': 'Suma uno', 'pt-BR': 'Some um' },
  takeOne: { role: 'option', 'en-US': 'Take one', 'es-MX': 'Quita uno', 'pt-BR': 'Tire um' },
  addFive: { role: 'option', 'en-US': 'Add five', 'es-MX': 'Suma cinco', 'pt-BR': 'Some cinco' },
  takeFive: { role: 'option', 'en-US': 'Take five', 'es-MX': 'Quita cinco', 'pt-BR': 'Tire cinco' },
  abacusTray: { role: 'heading', 'en-US': 'Change a rod', 'es-MX': 'Cambia una varilla', 'pt-BR': 'Mude uma haste' },
  abacusCaption: { role: 'heading', 'en-US': 'Beads on each rod', 'es-MX': 'Cuentas en cada varilla', 'pt-BR': 'Contas em cada haste' },
  colPlace: { role: 'data', 'en-US': 'Place', 'es-MX': 'Lugar', 'pt-BR': 'Posição' },
  colFive: { role: 'data', 'en-US': 'Five bead', 'es-MX': 'Cuenta de cinco', 'pt-BR': 'Conta de cinco' },
  colOneBeads: { role: 'data', 'en-US': 'One beads', 'es-MX': 'Cuentas de uno', 'pt-BR': 'Contas de um' },
  colDigit: { role: 'data', 'en-US': 'Digit', 'es-MX': 'Dígito', 'pt-BR': 'Dígito' },
  number: { role: 'data', 'en-US': 'Number', 'es-MX': 'Número', 'pt-BR': 'Número' },
  metAbacus: { role: 'body', 'en-US': 'You showed the number on the abacus.', 'es-MX': 'Mostraste el número en el ábaco.', 'pt-BR': 'Você mostrou o número no ábaco.' },
  hintAbacus: { role: 'body', 'en-US': 'Not yet. Check the beads on each rod.', 'es-MX': 'Aún no. Revisa las cuentas de cada varilla.', 'pt-BR': 'Ainda não. Confira as contas de cada haste.' },

  emptyLine: { role: 'data', 'en-US': 'Empty number line', 'es-MX': 'Recta numérica vacía', 'pt-BR': 'Reta numérica vazia' },
  forward: { role: 'data', 'en-US': 'Forward', 'es-MX': 'Adelante', 'pt-BR': 'Para frente' },
  backward: { role: 'data', 'en-US': 'Back', 'es-MX': 'Atrás', 'pt-BR': 'Para trás' },
  jumpForward: { role: 'data', 'en-US': 'Jump forward {n}', 'es-MX': 'Salta hacia adelante {n}', 'pt-BR': 'Pule para frente {n}' },
  jumpBack: { role: 'data', 'en-US': 'Jump back {n}', 'es-MX': 'Salta hacia atrás {n}', 'pt-BR': 'Pule para trás {n}' },
  start: { role: 'data', 'en-US': 'Start', 'es-MX': 'Inicio', 'pt-BR': 'Início' },
  nowAt: { role: 'data', 'en-US': 'Now at', 'es-MX': 'Ahora en', 'pt-BR': 'Agora em' },
  jumpsLeft: { role: 'data', 'en-US': 'Jumps left', 'es-MX': 'Saltos restantes', 'pt-BR': 'Saltos restantes' },
  lineCaption: { role: 'heading', 'en-US': 'Jumps on the line', 'es-MX': 'Saltos en la recta', 'pt-BR': 'Saltos na reta' },
  colStep: { role: 'data', 'en-US': 'Step', 'es-MX': 'Paso', 'pt-BR': 'Passo' },
  colJump: { role: 'data', 'en-US': 'Jump', 'es-MX': 'Salto', 'pt-BR': 'Salto' },
  colLands: { role: 'data', 'en-US': 'Lands on', 'es-MX': 'Cae en', 'pt-BR': 'Cai em' },
  metLine: { role: 'body', 'en-US': 'You reached the number with jumps.', 'es-MX': 'Llegaste al número con saltos.', 'pt-BR': 'Você chegou ao número com saltos.' },
  hintLine: { role: 'body', 'en-US': 'Not yet. Where does your last jump land?', 'es-MX': 'Aún no. ¿Dónde cae tu último salto?', 'pt-BR': 'Ainda não. Onde cai o seu último salto?' },

  zoomLine: { role: 'data', 'en-US': 'Zoom number line', 'es-MX': 'Recta numérica con zoom', 'pt-BR': 'Reta numérica com zoom' },
  zoomIn: { role: 'action', 'en-US': 'Zoom in', 'es-MX': 'Acercar', 'pt-BR': 'Aproximar' },
  zoomOut: { role: 'action', 'en-US': 'Zoom out', 'es-MX': 'Alejar', 'pt-BR': 'Afastar' },
  marker: { role: 'body', 'en-US': 'Marker', 'es-MX': 'Marcador', 'pt-BR': 'Marcador' },
  tickLeft: { role: 'data', 'en-US': 'One tick left', 'es-MX': 'Una marca a la izquierda', 'pt-BR': 'Uma marca para a esquerda' },
  tickRight: { role: 'data', 'en-US': 'One tick right', 'es-MX': 'Una marca a la derecha', 'pt-BR': 'Uma marca para a direita' },
  zoomLevel: { role: 'data', 'en-US': 'Zoom {n}', 'es-MX': 'Zoom {n}', 'pt-BR': 'Zoom {n}' },
  markerAt: { role: 'data', 'en-US': 'Marker at', 'es-MX': 'Marcador en', 'pt-BR': 'Marcador em' },
  zoomCaption: { role: 'heading', 'en-US': 'Zoom levels', 'es-MX': 'Niveles de zoom', 'pt-BR': 'Níveis de zoom' },
  colZoom: { role: 'data', 'en-US': 'Zoom', 'es-MX': 'Zoom', 'pt-BR': 'Zoom' },
  colFrom: { role: 'data', 'en-US': 'From', 'es-MX': 'Desde', 'pt-BR': 'De' },
  colTo: { role: 'data', 'en-US': 'To', 'es-MX': 'Hasta', 'pt-BR': 'Até' },
  colTick: { role: 'data', 'en-US': 'Tick', 'es-MX': 'Marca', 'pt-BR': 'Marca' },
  metZoom: { role: 'body', band: '10-12', 'en-US': 'You placed the marker by zooming in.', 'es-MX': 'Colocaste el marcador al acercar.', 'pt-BR': 'Você colocou o marcador ao aproximar.' },
  hintZoom: { role: 'body', band: '10-12', 'en-US': 'Not yet. Zoom in to see the smaller ticks.', 'es-MX': 'Aún no. Acerca para ver las marcas pequeñas.', 'pt-BR': 'Ainda não. Aproxime para ver as marcas menores.' },

  clockFace: { role: 'data', 'en-US': 'Clock showing {n}', 'es-MX': 'Reloj que marca las {n}', 'pt-BR': 'Relógio marcando {n}' },
  hour: { role: 'body', 'en-US': 'Hour', 'es-MX': 'Hora', 'pt-BR': 'Hora' },
  minutes: { role: 'body', 'en-US': 'Minutes', 'es-MX': 'Minutos', 'pt-BR': 'Minutos' },
  time: { role: 'data', 'en-US': 'Time', 'es-MX': 'Hora', 'pt-BR': 'Horário' },
  clockCaption: { role: 'heading', 'en-US': 'The time on the clock', 'es-MX': 'La hora en el reloj', 'pt-BR': 'A hora no relógio' },
  metClock: { role: 'body', 'en-US': 'You set the hands to the right time.', 'es-MX': 'Pusiste las manecillas en la hora correcta.', 'pt-BR': 'Você pôs os ponteiros na hora certa.' },
  hintClock: { role: 'body', 'en-US': 'Not yet. Check the short hand, then the long hand.', 'es-MX': 'Aún no. Revisa la manecilla corta y luego la larga.', 'pt-BR': 'Ainda não. Confira o ponteiro curto e depois o longo.' },

  ruler: { role: 'data', 'en-US': 'Ruler', 'es-MX': 'Regla', 'pt-BR': 'Régua' },
  barEnd: { role: 'body', 'en-US': 'End of the bar', 'es-MX': 'Final de la barra', 'pt-BR': 'Fim da barra' },
  unitCm: { role: 'data', 'en-US': 'centimeters', 'es-MX': 'centímetros', 'pt-BR': 'centímetros' },
  unitIn: { role: 'data', 'en-US': 'inches', 'es-MX': 'pulgadas', 'pt-BR': 'polegadas' },
  fromTo: { role: 'data', 'en-US': 'From {n} to {n}', 'es-MX': 'De {n} a {n}', 'pt-BR': 'De {n} a {n}' },
  length: { role: 'data', 'en-US': 'Length', 'es-MX': 'Largo', 'pt-BR': 'Comprimento' },
  rulerCaption: { role: 'heading', 'en-US': 'The bar on the ruler', 'es-MX': 'La barra en la regla', 'pt-BR': 'A barra na régua' },
  metRuler: { role: 'body', 'en-US': 'You stretched the bar to the right mark.', 'es-MX': 'Estiraste la barra hasta la marca correcta.', 'pt-BR': 'Você esticou a barra até a marca certa.' },
  hintRuler: { role: 'body', 'en-US': 'Not yet. Line up the end with a mark.', 'es-MX': 'Aún no. Alinea el final con una marca.', 'pt-BR': 'Ainda não. Alinhe o fim com uma marca.' },

  panBalance: { role: 'data', 'en-US': 'Pan balance', 'es-MX': 'Balanza de platillos', 'pt-BR': 'Balança de pratos' },
  leftPan: { role: 'data', 'en-US': 'Left pan', 'es-MX': 'Platillo izquierdo', 'pt-BR': 'Prato esquerdo' },
  rightPan: { role: 'data', 'en-US': 'Right pan', 'es-MX': 'Platillo derecho', 'pt-BR': 'Prato direito' },
  trayName: { role: 'data', 'en-US': 'Tray', 'es-MX': 'Bandeja', 'pt-BR': 'Bandeja' },
  trayHeading: { role: 'heading', 'en-US': 'Weights to place', 'es-MX': 'Pesas por colocar', 'pt-BR': 'Pesos para colocar' },
  weight: { role: 'option', 'en-US': 'Weight {n}', 'es-MX': 'Pesa {n}', 'pt-BR': 'Peso {n}' },
  fixedWeight: { role: 'data', 'en-US': 'Fixed weight {n}', 'es-MX': 'Pesa fija {n}', 'pt-BR': 'Peso fixo {n}' },
  balanced: { role: 'data', 'en-US': 'Both pans are equal', 'es-MX': 'Los platillos pesan igual', 'pt-BR': 'Os pratos pesam igual' },
  heavierLeft: { role: 'data', 'en-US': 'Left pan is heavier by {n}', 'es-MX': 'El platillo izquierdo pesa {n} más', 'pt-BR': 'O prato esquerdo pesa {n} a mais' },
  heavierRight: { role: 'data', 'en-US': 'Right pan is heavier by {n}', 'es-MX': 'El platillo derecho pesa {n} más', 'pt-BR': 'O prato direito pesa {n} a mais' },
  panCaption: { role: 'heading', 'en-US': 'Weights on each pan', 'es-MX': 'Pesas en cada platillo', 'pt-BR': 'Pesos em cada prato' },
  colPan: { role: 'data', 'en-US': 'Pan', 'es-MX': 'Platillo', 'pt-BR': 'Prato' },
  colWeights: { role: 'data', 'en-US': 'Weights', 'es-MX': 'Pesas', 'pt-BR': 'Pesos' },
  metPan: { role: 'body', 'en-US': 'You placed the weights to match the goal.', 'es-MX': 'Colocaste las pesas para lograr la meta.', 'pt-BR': 'Você colocou os pesos para chegar à meta.' },
  hintPan: { role: 'body', 'en-US': 'Not yet. Add up the weights on each pan.', 'es-MX': 'Aún no. Suma las pesas de cada platillo.', 'pt-BR': 'Ainda não. Some os pesos de cada prato.' },
} as const satisfies HorizonteCopy;
