// `choice` family — one demo segment per type for /dev/lesson-lab.
// Written per locale; see `../../lab/fixtureCopy.ts`. Structure and answer keys
// are written once and are identical in every locale by construction.

import type { Locale } from '@/i18n'
import type { SegmentBase } from '../../core/types'
import { copyPack, type Copy } from '../../lab/fixtureCopy'

const EN = {
  mcqPrompt: 'What is **saving**?',
  mcqHint: 'Think about your piggy bank: what do you do with the coins you keep?',
  mcqExplain: 'Saving is **keeping part** of your money today so you can use it later.',
  mcqA: 'Keeping part of my money for later',
  mcqB: 'Spending all my money on candy',
  mcqBWhy: 'That is *spending*, not saving. Spend it all today and nothing is left for tomorrow.',
  mcqC: 'Borrowing money',
  mcqCWhy: 'Borrowing is the opposite: using money that is **not** yours yet.',

  tfPrompt: 'Liruf says a sentence. Is it true?',
  tfExplain: 'The money you save is **still yours** — it is just waiting until you need it.',
  tfStatement: 'If I save my money, **I lose it** forever.',
  tfJ1: 'True, because I cannot touch it any more.',
  tfJ2: 'False, because it is still mine and I use it when I need it.',
  tfJ3: 'False, because the piggy bank turns it into more money by itself.',

  picPrompt: 'Where is your money **safest**?',
  picExplain: 'A bank keeps your money **safe** and can even pay you interest.',
  picA: 'At the bank',
  picB: 'Under a rock',
  picBWhy: 'Under a rock anyone could find it… or the rain could ruin it!',
  picC: 'In my backpack',
  picCWhy: 'A backpack goes everywhere with you: easy to lose, easy to drop.',

  oddPrompt: 'One of these things is **not** money. Which one?',
  oddI1: '$10 coin',
  oddI2: '$50 note',
  oddI3: 'A leaf from a tree',
  oddI4: 'Debit card',
  oddR1: 'Because nobody accepts it as payment',
  oddR2: 'Because it is green',
  oddR3: 'Because it is very small',

  bestPrompt: 'What would you do?',
  bestExplain: 'Comparing prices **before** you buy leaves you more money for your goals.',
  bestScenario: 'You want a ball that costs **$80**. In the shop across the street the same ball costs **$60**.',
  bestA: 'Buy it right now for $80 — I want it already!',
  bestAWhy: 'Rushing costs: you paid **$20 extra** for not crossing the street.',
  bestB: 'Cross over and buy it for $60',
  bestBWhy: 'Nice! Comparing prices saved you **$20** you can put away.',
  bestC: 'Never buy anything at all',
  bestCWhy: 'Saving is great, but money is also there to be enjoyed **with a plan**.',

  ynPrompt: "Detective Rho's rule: is it a **need**?",
  ynRule: 'A **need** is something you cannot live well without: food, water, a home, health.',
  ynC1: 'Drinking water',
  ynC2: 'The new video game',
  ynC3: 'Shoes for school',
  ynC4: 'A giant candy',

  tapPrompt: 'Quick! Tap only the **coins**.',
  tapInstruction: 'Tap everything that is **coin money**. You have 20 seconds!',
  tapM1: '$1',
  tapB1: '$20 note',
  tapM2: '$5',
  tapX1: 'Button',
  tapM3: '$10',
  tapX2: 'Sticker',
  tapB2: '$100 note',
  tapM4: '50¢',

  confPrompt: 'If I save $10 every week, how much do I have in **4 weeks**? And tell me how sure you are.',
  confExplain: '$10 × 4 weeks = **$40**. Keeping at it adds up!',
  confA: '$14',
  confAWhy: 'You added 10 + 4 — but every week you add **another** $10.',
  confB: '$40',
  confC: '$1000',
  confCWhy: 'If only! But $10 for 4 weeks is 10+10+10+10.',
} as const

const ES: Copy<typeof EN> = {
  mcqPrompt: '¿Qué es el **ahorro**?',
  mcqHint: 'Piensa en tu alcancía: ¿qué haces con las monedas que guardas?',
  mcqExplain: 'Ahorrar es **guardar una parte** de tu dinero hoy para poder usarlo después.',
  mcqA: 'Guardar una parte de mi dinero para después',
  mcqB: 'Gastar todo mi dinero en dulces',
  mcqBWhy: 'Eso es *gastar*, no ahorrar. Si gastas todo hoy, no te queda nada para mañana.',
  mcqC: 'Pedir dinero prestado',
  mcqCWhy: 'Pedir prestado es lo contrario: usar dinero que **no** es tuyo todavía.',

  tfPrompt: 'Liruf dice una frase. ¿Es cierta?',
  tfExplain: 'El dinero que ahorras **sigue siendo tuyo** — solo espera a que lo necesites.',
  tfStatement: 'Si ahorro mi dinero, **lo pierdo** para siempre.',
  tfJ1: 'Cierto, porque ya no lo puedo tocar.',
  tfJ2: 'Falso, porque sigue siendo mío y lo uso cuando lo necesite.',
  tfJ3: 'Falso, porque la alcancía lo convierte en más dinero sola.',

  picPrompt: '¿Dónde está más **seguro** tu dinero?',
  picExplain: 'Un banco guarda tu dinero con **seguridad** y hasta puede pagarte intereses.',
  picA: 'En el banco',
  picB: 'Bajo una piedra',
  picBWhy: 'Bajo una piedra cualquiera lo puede encontrar… ¡o la lluvia lo arruina!',
  picC: 'En la mochila',
  picCWhy: 'La mochila viaja contigo a todos lados: es fácil perderla o que se caiga.',

  oddPrompt: 'Una de estas cosas **no** es dinero. ¿Cuál?',
  oddI1: 'Moneda de $10',
  oddI2: 'Billete de $50',
  oddI3: 'Una hoja de árbol',
  oddI4: 'Tarjeta de débito',
  oddR1: 'Porque nadie la acepta para pagar',
  oddR2: 'Porque es de color verde',
  oddR3: 'Porque es muy pequeña',

  bestPrompt: '¿Qué harías tú?',
  bestExplain: 'Comparar precios **antes** de comprar te deja más dinero para tus metas.',
  bestScenario:
    'Quieres una pelota que cuesta **$80**. En la tienda de enfrente la misma pelota cuesta **$60**.',
  bestA: 'Comprarla de inmediato por $80, ¡ya la quiero!',
  bestAWhy: 'La prisa cuesta: pagaste **$20 extra** por no cruzar la calle.',
  bestB: 'Cruzar y comprarla por $60',
  bestBWhy: '¡Bien! Comparar precios te ahorró **$20** que puedes guardar.',
  bestC: 'No comprar nada nunca',
  bestCWhy: 'Ahorrar está genial, pero el dinero también sirve para disfrutarse **con plan**.',

  ynPrompt: 'Regla del detective Rho: ¿es una **necesidad**?',
  ynRule: 'Una **necesidad** es algo sin lo que no puedes vivir bien: comida, agua, casa, salud.',
  ynC1: 'Agua para beber',
  ynC2: 'El videojuego nuevo',
  ynC3: 'Zapatos para ir a la escuela',
  ynC4: 'Un dulce gigante',

  tapPrompt: '¡Rápido! Toca solo las **monedas**.',
  tapInstruction: 'Toca todas las cosas que son **dinero en monedas**. ¡Tienes 20 segundos!',
  tapM1: '$1',
  tapB1: 'Billete $20',
  tapM2: '$5',
  tapX1: 'Botón',
  tapM3: '$10',
  tapX2: 'Sticker',
  tapB2: 'Billete $100',
  tapM4: '50¢',

  confPrompt: 'Si guardo $10 cada semana, ¿cuánto tengo en **4 semanas**? Y dime qué tan seguro estás.',
  confExplain: '$10 × 4 semanas = **$40**. ¡La constancia suma!',
  confA: '$14',
  confAWhy: 'Sumaste 10 + 4 — pero cada semana agregas **otros** $10.',
  confB: '$40',
  confC: '$1000',
  confCWhy: '¡Ojalá! Pero $10 por 4 semanas son 10+10+10+10.',
}

const PT: Copy<typeof EN> = {
  mcqPrompt: 'O que é **poupar**?',
  mcqHint: 'Pense no seu cofrinho: o que você faz com as moedas que guarda?',
  mcqExplain: 'Poupar é **guardar uma parte** do seu dinheiro hoje para usar depois.',
  mcqA: 'Guardar uma parte do meu dinheiro para depois',
  mcqB: 'Gastar todo o meu dinheiro em doces',
  mcqBWhy: 'Isso é *gastar*, não poupar. Se gastar tudo hoje, não sobra nada para amanhã.',
  mcqC: 'Pedir dinheiro emprestado',
  mcqCWhy: 'Pedir emprestado é o contrário: usar dinheiro que **não** é seu ainda.',

  tfPrompt: 'Liruf disse uma frase. Ela é verdadeira?',
  tfExplain: 'O dinheiro que você guarda **continua sendo seu** — só está esperando você precisar.',
  tfStatement: 'Se eu guardar meu dinheiro, **eu o perco** para sempre.',
  tfJ1: 'Verdadeiro, porque não posso mais mexer nele.',
  tfJ2: 'Falso, porque continua meu e eu uso quando precisar.',
  tfJ3: 'Falso, porque o cofrinho transforma em mais dinheiro sozinho.',

  picPrompt: 'Onde seu dinheiro fica mais **seguro**?',
  picExplain: 'Um banco guarda seu dinheiro com **segurança** e ainda pode pagar juros.',
  picA: 'No banco',
  picB: 'Embaixo de uma pedra',
  picBWhy: 'Embaixo de uma pedra qualquer um acha… ou a chuva estraga!',
  picC: 'Na mochila',
  picCWhy: 'A mochila vai com você para todo lado: é fácil perder ou deixar cair.',

  oddPrompt: 'Uma destas coisas **não** é dinheiro. Qual?',
  oddI1: 'Moeda de R$10',
  oddI2: 'Nota de R$50',
  oddI3: 'Uma folha de árvore',
  oddI4: 'Cartão de débito',
  oddR1: 'Porque ninguém aceita como pagamento',
  oddR2: 'Porque é verde',
  oddR3: 'Porque é bem pequena',

  bestPrompt: 'O que você faria?',
  bestExplain: 'Comparar preços **antes** de comprar deixa mais dinheiro para as suas metas.',
  bestScenario:
    'Você quer uma bola que custa **R$80**. Na loja da frente a mesma bola custa **R$60**.',
  bestA: 'Comprar na hora por R$80 — já quero!',
  bestAWhy: 'A pressa custa: você pagou **R$20 a mais** por não atravessar a rua.',
  bestB: 'Atravessar e comprar por R$60',
  bestBWhy: 'Boa! Comparar preços economizou **R$20** que você pode guardar.',
  bestC: 'Nunca comprar nada',
  bestCWhy: 'Poupar é ótimo, mas dinheiro também serve para aproveitar **com plano**.',

  ynPrompt: 'Regra do detetive Rho: isto é uma **necessidade**?',
  ynRule: 'Uma **necessidade** é algo sem o que você não vive bem: comida, água, casa, saúde.',
  ynC1: 'Água para beber',
  ynC2: 'O videogame novo',
  ynC3: 'Sapatos para ir à escola',
  ynC4: 'Um doce gigante',

  tapPrompt: 'Rápido! Toque só nas **moedas**.',
  tapInstruction: 'Toque em tudo que é **dinheiro em moeda**. Você tem 20 segundos!',
  tapM1: 'R$1',
  tapB1: 'Nota de R$20',
  tapM2: 'R$5',
  tapX1: 'Botão',
  tapM3: 'R$10',
  tapX2: 'Adesivo',
  tapB2: 'Nota de R$100',
  tapM4: '50 centavos',

  confPrompt:
    'Se eu guardar R$10 por semana, quanto tenho em **4 semanas**? E diga o quanto você está seguro.',
  confExplain: 'R$10 × 4 semanas = **R$40**. Constância soma!',
  confA: 'R$14',
  confAWhy: 'Você somou 10 + 4 — mas cada semana você acrescenta **outros** R$10.',
  confB: 'R$40',
  confC: 'R$1000',
  confCWhy: 'Quem dera! Mas R$10 por 4 semanas é 10+10+10+10.',
}

const COPY = copyPack(EN, ES, PT)

export function choiceFixtures(locale: Locale): SegmentBase[] {
  const c = COPY[locale]
  return [
    {
      id: 'fx-quiz-mcq',
      type: 'quiz_mcq',
      prompt_md: c.mcqPrompt,
      difficulty: 1,
      xp: 10,
      hints: [c.mcqHint],
      explanation_md: c.mcqExplain,
      narrator: { character: 'dina', emotion: 'happy' },
      payload: {
        options: [
          { id: 'a', text_md: c.mcqA },
          { id: 'b', text_md: c.mcqB, rationale_md: c.mcqBWhy },
          { id: 'c', text_md: c.mcqC, rationale_md: c.mcqCWhy },
        ],
      },
      answer: { correct_option_id: 'a' },
    },
    {
      id: 'fx-true-false',
      type: 'true_false',
      prompt_md: c.tfPrompt,
      difficulty: 2,
      xp: 10,
      explanation_md: c.tfExplain,
      narrator: { character: 'liruf', emotion: 'thinking' },
      payload: {
        statement_md: c.tfStatement,
        justifications: [
          { id: 'j1', text_md: c.tfJ1 },
          { id: 'j2', text_md: c.tfJ2 },
          { id: 'j3', text_md: c.tfJ3 },
        ],
      },
      answer: { is_true: false, correct_justification_id: 'j2' },
    },
    {
      id: 'fx-picture-choice',
      type: 'picture_choice',
      prompt_md: c.picPrompt,
      difficulty: 1,
      xp: 10,
      explanation_md: c.picExplain,
      narrator: { character: 'rho', emotion: 'thinking' },
      payload: {
        options: [
          { id: 'a', icon: 'account_balance', label: c.picA },
          { id: 'b', icon: 'grass', label: c.picB, rationale_md: c.picBWhy },
          { id: 'c', icon: 'backpack', label: c.picC, rationale_md: c.picCWhy },
        ],
      },
      answer: { correct_option_id: 'a' },
    },
    {
      id: 'fx-odd-one-out',
      type: 'odd_one_out',
      prompt_md: c.oddPrompt,
      difficulty: 2,
      xp: 15,
      narrator: { character: 'zara', emotion: 'thinking' },
      payload: {
        items: [
          { id: 'i1', text_md: c.oddI1 },
          { id: 'i2', text_md: c.oddI2 },
          { id: 'i3', text_md: c.oddI3 },
          { id: 'i4', text_md: c.oddI4 },
        ],
        reasons: [
          { id: 'r1', text_md: c.oddR1 },
          { id: 'r2', text_md: c.oddR2 },
          { id: 'r3', text_md: c.oddR3 },
        ],
      },
      answer: { odd_item_id: 'i3', correct_reason_id: 'r1' },
    },
    {
      id: 'fx-best-decision',
      type: 'best_decision',
      prompt_md: c.bestPrompt,
      difficulty: 3,
      xp: 15,
      explanation_md: c.bestExplain,
      narrator: { character: 'zara', emotion: 'happy' },
      payload: {
        scenario_md: c.bestScenario,
        options: [
          { id: 'a', text_md: c.bestA, rationale_md: c.bestAWhy },
          { id: 'b', text_md: c.bestB, rationale_md: c.bestBWhy },
          { id: 'c', text_md: c.bestC, rationale_md: c.bestCWhy },
        ],
      },
      answer: { qualities: { a: 20, b: 100, c: 55 } },
    },
    {
      id: 'fx-yes-no-cases',
      type: 'yes_no_cases',
      prompt_md: c.ynPrompt,
      difficulty: 2,
      xp: 15,
      narrator: { character: 'rho', emotion: 'thinking' },
      payload: {
        rule_md: c.ynRule,
        cases: [
          { id: 'c1', text_md: c.ynC1 },
          { id: 'c2', text_md: c.ynC2 },
          { id: 'c3', text_md: c.ynC3 },
          { id: 'c4', text_md: c.ynC4 },
        ],
      },
      answer: { applies_ids: ['c1', 'c3'] },
    },
    {
      id: 'fx-speed-tap',
      type: 'speed_tap',
      prompt_md: c.tapPrompt,
      difficulty: 2,
      xp: 15,
      narrator: { character: 'liruf', emotion: 'excited' },
      payload: {
        instruction_md: c.tapInstruction,
        items: [
          { id: 'm1', text_md: c.tapM1 },
          { id: 'b1', text_md: c.tapB1 },
          { id: 'm2', text_md: c.tapM2 },
          { id: 'x1', text_md: c.tapX1 },
          { id: 'm3', text_md: c.tapM3 },
          { id: 'x2', text_md: c.tapX2 },
          { id: 'b2', text_md: c.tapB2 },
          { id: 'm4', text_md: c.tapM4 },
        ],
        seconds: 20,
      },
      answer: { target_ids: ['m1', 'm2', 'm3', 'm4'] },
    },
    {
      id: 'fx-confidence-quiz',
      type: 'confidence_quiz',
      prompt_md: c.confPrompt,
      difficulty: 3,
      xp: 20,
      explanation_md: c.confExplain,
      narrator: { character: 'dina', emotion: 'thinking' },
      payload: {
        options: [
          { id: 'a', text_md: c.confA, rationale_md: c.confAWhy },
          { id: 'b', text_md: c.confB },
          { id: 'c', text_md: c.confC, rationale_md: c.confCWhy },
        ],
      },
      answer: { correct_option_id: 'b' },
    },
  ]
}
