/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/solids/contract.ts. Do not edit: change the source and regenerate. */
import { z } from 'zod';
import { hzBase, hzServer, hzVisual } from '../shared.generated';
import type { HorizonteAgeScope } from '../types.generated';
import { COUNT_KINDS, SOLID_IDS } from './model.generated';
import { FACE_NAMES, NET_GRID_LIMITS, NET_PIECE } from './net.generated';
import {
  COMPLETE_FIXED_LIMITS, LABEL_FIXED_LIMITS, NET_EDGE_LIMIT, VIEWER_COUNT_LIMIT, VIEWER_MIN_SOLIDS,
  netProblem, readNetPayload, readStackPayload, readViewerPayload, stackProblem, viewerProblem,
} from './rules.generated';
import { STACK_MAX_HEIGHT, STACK_PIECE } from './stack.generated';

const solidId = z.enum(SOLID_IDS);
const countKind = z.enum(COUNT_KINDS);

/** F4.1: a few solids to turn and compare; the learner names the one that has the searched count, then counts something else on it. */
export const viewerPayload = z.object({
  solids: z.array(solidId).min(VIEWER_MIN_SOLIDS).max(SOLID_IDS.length).refine((list) => new Set(list).size === list.length, 'Each solid is listed once'),
  find: z.object({ kind: countKind, count: z.number().int().min(0).max(VIEWER_COUNT_LIMIT) }).strict(),
  report: countKind,
}).strict();

const netCell = z.tuple([z.number().int().min(0).max(7), z.number().int().min(0).max(7)]);
const netEdge = z.number().int().min(1).max(NET_EDGE_LIMIT);

/** F4.2: `label` names the squares of a given cube net; `complete` finishes a partial net so it folds into a cube. */
export const netPayload = z.discriminatedUnion('mode', [
  z.object({
    mode: z.literal('label'),
    cells: z.array(netCell).length(6),
    fixed: z.array(z.object({ cell: z.number().int().min(0).max(5), name: z.enum(FACE_NAMES) }).strict()).min(LABEL_FIXED_LIMITS.min).max(LABEL_FIXED_LIMITS.max),
    edge: netEdge,
  }).strict(),
  z.object({
    mode: z.literal('complete'),
    grid: z.object({ cols: z.number().int().min(NET_GRID_LIMITS.minCols).max(NET_GRID_LIMITS.maxCols), rows: z.number().int().min(NET_GRID_LIMITS.minRows).max(NET_GRID_LIMITS.maxRows) }).strict(),
    fixed: z.array(netCell).min(COMPLETE_FIXED_LIMITS.min).max(COMPLETE_FIXED_LIMITS.max),
    edge: netEdge,
  }).strict(),
]);

const heightList = z.array(z.number().int().min(0).max(STACK_MAX_HEIGHT)).min(2).max(3);

/** F4.3: rebuild a stack of cubes from its views; `fewest` asks for the smallest number of cubes that shows them. */
export const stackPayload = z.object({
  size: z.union([z.literal(2), z.literal(3)]),
  start: z.array(heightList).min(2).max(3),
  goal: z.object({
    front: heightList.optional(),
    side: heightList.optional(),
    plan: z.array(z.array(z.number().int().min(0).max(1)).min(2).max(3)).min(2).max(3).optional(),
  }).strict(),
  fewest: z.boolean(),
}).strict();

const complain = (ctx: z.RefinementCtx, message: string) => ctx.addIssue({ code: 'custom', path: ['payload'], message });

export const SOLIDS_SEGMENTS = [
  z.object({
    ...hzBase, type: z.literal('geometry.solid-viewer.v2'), grading: hzServer, visual: hzVisual('solid-viewer'), payload: viewerPayload,
  }).strict().superRefine((value, ctx) => {
    const payload = readViewerPayload(value.payload);
    const problem = payload ? viewerProblem(payload) : 'The viewer payload is malformed';
    if (problem) complain(ctx, problem);
  }),
  z.object({
    ...hzBase, type: z.literal('geometry.cube-net.v2'), grading: hzServer, visual: hzVisual('cube-net'), payload: netPayload,
  }).strict().superRefine((value, ctx) => {
    const payload = readNetPayload(value.payload);
    const problem = payload ? netProblem(payload) : 'The net payload is malformed';
    if (problem) complain(ctx, problem);
  }),
  z.object({
    ...hzBase, type: z.literal('geometry.cube-stack.v2'), grading: hzServer, visual: hzVisual('cube-stack'), payload: stackPayload,
  }).strict().superRefine((value, ctx) => {
    const payload = readStackPayload(value.payload);
    const problem = payload ? stackProblem(payload) : 'The stack payload is malformed';
    if (problem) complain(ctx, problem);
  }),
] as const;

const netSlots = z.record(z.string().regex(/^(cell[0-5]|g[0-4]x[0-3])$/), z.array(z.enum([...FACE_NAMES, NET_PIECE] as const)).max(1));
const stackSlots = z.record(z.string().regex(/^c[0-2]r[0-2]$/), z.array(z.literal(STACK_PIECE)).max(STACK_MAX_HEIGHT));
const arrangement = <T extends z.ZodType>(slots: T) => z.object({ solutions: z.array(slots).min(1).max(8), ordered: z.boolean().optional() }).strict();

export const SOLIDS_RUBRICS = {
  'geometry.solid-viewer.v2': z.object({ solid: solidId, count: z.string().regex(/^(0|[1-9]\d?)$/) }).strict(),
  'geometry.cube-net.v2': arrangement(netSlots),
  'geometry.cube-stack.v2': arrangement(stackSlots),
} as const;

export const SOLIDS_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {
  'geometry.solid-viewer.v2': { ages: [7, 12], adult: false },
  'geometry.cube-net.v2': { ages: [7, 12], adult: false },
  'geometry.cube-stack.v2': { ages: [6, 12], adult: false },
};
