/* Generated by agent/tools/sync-v2-horizonte.mjs from backend/src/services/horizonte/solids/contract.ts. Do not edit: change the source and regenerate. */
import type { HorizonteAgeScope } from '../types.generated';

export const SOLIDS_SEGMENTS = [] as const;
export const SOLIDS_RUBRICS = {} as const;
export const SOLIDS_AGE_SCOPE: Readonly<Record<string, HorizonteAgeScope>> = {};
