import type { HorizonteCopy } from '../boardTypes';

export const SOLIDS_COPY = {
  solidCube: { role: 'option', 'en-US': 'Cube', 'es-MX': 'Cubo', 'pt-BR': 'Cubo' },
  solidPrism: { role: 'option', 'en-US': 'Triangular prism', 'es-MX': 'Prisma triangular', 'pt-BR': 'Prisma triangular' },
  solidPyramid: { role: 'option', 'en-US': 'Square pyramid', 'es-MX': 'Pirámide cuadrada', 'pt-BR': 'Pirâmide quadrada' },
  solidCylinder: { role: 'option', 'en-US': 'Cylinder', 'es-MX': 'Cilindro', 'pt-BR': 'Cilindro' },

  viewLevel: { role: 'data', 'en-US': 'Level view', 'es-MX': 'Vista a nivel', 'pt-BR': 'Vista no nível' },
  viewCorner: { role: 'data', 'en-US': 'Corner view', 'es-MX': 'Vista de esquina', 'pt-BR': 'Vista de canto' },
  viewTop: { role: 'data', 'en-US': 'Top view', 'es-MX': 'Vista desde arriba', 'pt-BR': 'Vista de cima' },
  viewTurn: { role: 'data', 'en-US': 'Turn {n} of 4', 'es-MX': 'Giro {n} de 4', 'pt-BR': 'Giro {n} de 4' },

  viewerControls: { role: 'heading', 'en-US': 'Change the view', 'es-MX': 'Cambia la vista', 'pt-BR': 'Mude a vista' },
  turnLeft: { role: 'action', 'en-US': 'Turn left', 'es-MX': 'Girar a la izquierda', 'pt-BR': 'Girar à esquerda' },
  turnRight: { role: 'action', 'en-US': 'Turn right', 'es-MX': 'Girar a la derecha', 'pt-BR': 'Girar à direita' },
  viewHigher: { role: 'action', 'en-US': 'Look higher', 'es-MX': 'Vista más alta', 'pt-BR': 'Vista mais alta' },
  viewLower: { role: 'action', 'en-US': 'Look lower', 'es-MX': 'Vista más baja', 'pt-BR': 'Vista mais baixa' },
  viewerKeys: {
    role: 'body',
    'en-US': 'Arrow keys turn the solid. Up and down tilt it.',
    'es-MX': 'Las flechas giran el cuerpo. Arriba y abajo lo inclinan.',
    'pt-BR': 'As setas giram o sólido. Cima e baixo o inclinam.',
  },

  showTable: { role: 'action', 'en-US': 'Show as table', 'es-MX': 'Mostrar como tabla', 'pt-BR': 'Mostrar como tabela' },
  hideTable: { role: 'action', 'en-US': 'Hide table', 'es-MX': 'Ocultar tabla', 'pt-BR': 'Ocultar tabela' },
  factsCaption: { role: 'heading', 'en-US': 'Facts about the solid', 'es-MX': 'Datos del cuerpo', 'pt-BR': 'Dados do sólido' },
  colFact: { role: 'data', 'en-US': 'Fact', 'es-MX': 'Dato', 'pt-BR': 'Dado' },
  colCount: { role: 'data', 'en-US': 'Count', 'es-MX': 'Cantidad', 'pt-BR': 'Quantidade' },
  factFaces: { role: 'data', 'en-US': 'Faces', 'es-MX': 'Caras', 'pt-BR': 'Faces' },
  factFlat: { role: 'data', 'en-US': 'Flat faces', 'es-MX': 'Caras planas', 'pt-BR': 'Faces planas' },
  factCurvedFaces: { role: 'data', 'en-US': 'Curved faces', 'es-MX': 'Caras curvas', 'pt-BR': 'Faces curvas' },
  factEdges: { role: 'data', 'en-US': 'Edges', 'es-MX': 'Aristas', 'pt-BR': 'Arestas' },
  factStraight: { role: 'data', 'en-US': 'Straight edges', 'es-MX': 'Aristas rectas', 'pt-BR': 'Arestas retas' },
  factCurvedEdges: { role: 'data', 'en-US': 'Curved edges', 'es-MX': 'Aristas curvas', 'pt-BR': 'Arestas curvas' },
  factVertices: { role: 'data', 'en-US': 'Vertices', 'es-MX': 'Vértices', 'pt-BR': 'Vértices' },

  solidsHeading: { role: 'heading', 'en-US': 'Pick a solid to look at', 'es-MX': 'Elige un cuerpo para mirar', 'pt-BR': 'Escolha um sólido para olhar' },
  labelsHeading: { role: 'heading', 'en-US': 'Show labels', 'es-MX': 'Mostrar etiquetas', 'pt-BR': 'Mostrar rótulos' },
  optLabelsNone: { role: 'option', 'en-US': 'No labels', 'es-MX': 'Sin etiquetas', 'pt-BR': 'Sem rótulos' },
  optFaces: { role: 'option', 'en-US': 'Faces', 'es-MX': 'Caras', 'pt-BR': 'Faces' },
  optEdges: { role: 'option', 'en-US': 'Edges', 'es-MX': 'Aristas', 'pt-BR': 'Arestas' },
  optVertices: { role: 'option', 'en-US': 'Vertices', 'es-MX': 'Vértices', 'pt-BR': 'Vértices' },
  chooseThis: { role: 'action', 'en-US': 'Choose this solid', 'es-MX': 'Elegir este cuerpo', 'pt-BR': 'Escolher este sólido' },
  chosen: { role: 'data', 'en-US': 'Chosen: {solid}', 'es-MX': 'Elegido: {solid}', 'pt-BR': 'Escolhido: {solid}' },
  chosenNone: { role: 'data', 'en-US': 'Chosen: none', 'es-MX': 'Elegido: ninguno', 'pt-BR': 'Escolhido: nenhum' },
  countFaces: { role: 'body', 'en-US': 'Number of faces', 'es-MX': 'Número de caras', 'pt-BR': 'Número de faces' },
  countEdges: { role: 'body', 'en-US': 'Number of edges', 'es-MX': 'Número de aristas', 'pt-BR': 'Número de arestas' },
  countVertices: { role: 'body', 'en-US': 'Number of vertices', 'es-MX': 'Número de vértices', 'pt-BR': 'Número de vértices' },
  metViewer: { role: 'body', 'en-US': 'You found the solid and counted it.', 'es-MX': 'Encontraste el cuerpo y lo contaste.', 'pt-BR': 'Você encontrou o sólido e o contou.' },
  hintViewer: { role: 'body', 'en-US': 'Not yet. Look at the solid again and count.', 'es-MX': 'Aún no. Mira el cuerpo otra vez y cuenta.', 'pt-BR': 'Ainda não. Olhe o sólido de novo e conte.' },

  gridName: { role: 'data', 'en-US': 'Net grid', 'es-MX': 'Cuadrícula de la plantilla', 'pt-BR': 'Grade da planificação' },
  squareN: { role: 'data', 'en-US': 'Square {n}', 'es-MX': 'Cuadrado {n}', 'pt-BR': 'Quadrado {n}' },
  faceTop: { role: 'option', 'en-US': 'Top', 'es-MX': 'Arriba', 'pt-BR': 'Cima' },
  faceBottom: { role: 'option', 'en-US': 'Bottom', 'es-MX': 'Abajo', 'pt-BR': 'Baixo' },
  faceFront: { role: 'option', 'en-US': 'Front', 'es-MX': 'Frente', 'pt-BR': 'Frente' },
  faceBack: { role: 'option', 'en-US': 'Back', 'es-MX': 'Atrás', 'pt-BR': 'Atrás' },
  faceLeft: { role: 'option', 'en-US': 'Left', 'es-MX': 'Izquierda', 'pt-BR': 'Esquerda' },
  faceRight: { role: 'option', 'en-US': 'Right', 'es-MX': 'Derecha', 'pt-BR': 'Direita' },
  given: { role: 'data', 'en-US': 'given', 'es-MX': 'dado', 'pt-BR': 'dado' },
  unnamed: { role: 'data', 'en-US': 'no name', 'es-MX': 'sin nombre', 'pt-BR': 'sem nome' },
  takeBack: { role: 'data', 'en-US': 'Take back', 'es-MX': 'Quitar', 'pt-BR': 'Remover' },
  facesHeading: { role: 'heading', 'en-US': 'Names to place', 'es-MX': 'Nombres para colocar', 'pt-BR': 'Nomes para colocar' },
  placeHint: { role: 'body', 'en-US': 'Pick a name, then tap a square.', 'es-MX': 'Elige un nombre y toca un cuadrado.', 'pt-BR': 'Escolha um nome e toque em um quadrado.' },
  namedCount: { role: 'data', 'en-US': 'Named: {n} of 6', 'es-MX': 'Nombradas: {n} de 6', 'pt-BR': 'Nomeadas: {n} de 6' },
  areaLabel: { role: 'data', 'en-US': 'Surface area', 'es-MX': 'Área de la superficie', 'pt-BR': 'Área da superfície' },
  areaUnit: { role: 'data', 'en-US': 'square units', 'es-MX': 'unidades cuadradas', 'pt-BR': 'unidades quadradas' },
  netCaption: { role: 'heading', 'en-US': 'Net squares and names', 'es-MX': 'Cuadrados de la plantilla y sus nombres', 'pt-BR': 'Quadrados da planificação e seus nomes' },
  colSquare: { role: 'data', 'en-US': 'Square', 'es-MX': 'Cuadrado', 'pt-BR': 'Quadrado' },
  colColumn: { role: 'data', 'en-US': 'Column', 'es-MX': 'Columna', 'pt-BR': 'Coluna' },
  colRow: { role: 'data', 'en-US': 'Row', 'es-MX': 'Fila', 'pt-BR': 'Linha' },
  colName: { role: 'data', 'en-US': 'Name', 'es-MX': 'Nombre', 'pt-BR': 'Nome' },
  metNetLabel: { role: 'body', 'en-US': 'You named every face of the cube.', 'es-MX': 'Nombraste todas las caras del cubo.', 'pt-BR': 'Você nomeou todas as faces do cubo.' },
  hintNetLabel: {
    role: 'body',
    'en-US': 'Not yet. Picture folding the net into a cube.',
    'es-MX': 'Aún no. Imagina doblar la plantilla para armar un cubo.',
    'pt-BR': 'Ainda não. Imagine dobrar a planificação para formar um cubo.',
  },

  gridCellEmpty: { role: 'data', 'en-US': 'Column {c}, row {r}: empty', 'es-MX': 'Columna {c}, fila {r}: vacía', 'pt-BR': 'Coluna {c}, linha {r}: vazia' },
  gridCellSquare: { role: 'data', 'en-US': 'Column {c}, row {r}: square', 'es-MX': 'Columna {c}, fila {r}: cuadrado', 'pt-BR': 'Coluna {c}, linha {r}: quadrado' },
  gridCellGiven: { role: 'data', 'en-US': 'Column {c}, row {r}: given square', 'es-MX': 'Columna {c}, fila {r}: cuadrado dado', 'pt-BR': 'Coluna {c}, linha {r}: quadrado dado' },
  squaresCount: { role: 'data', 'en-US': 'Squares: {n} of 6', 'es-MX': 'Cuadrados: {n} de 6', 'pt-BR': 'Quadrados: {n} de 6' },
  foldJoin: { role: 'data', 'en-US': 'The squares are not joined edge to edge.', 'es-MX': 'Los cuadrados no se unen por los lados.', 'pt-BR': 'Os quadrados não se juntam pelos lados.' },
  foldOverlap: { role: 'data', 'en-US': 'Two squares would land on the same face.', 'es-MX': 'Dos cuadrados caerían en la misma cara.', 'pt-BR': 'Dois quadrados cairiam na mesma face.' },
  foldMore: { role: 'data', 'en-US': 'Keep adding squares.', 'es-MX': 'Sigue agregando cuadrados.', 'pt-BR': 'Continue adicionando quadrados.' },
  foldOk: { role: 'data', 'en-US': 'The net folds into a cube.', 'es-MX': 'La plantilla se dobla y forma un cubo.', 'pt-BR': 'A planificação dobra e forma um cubo.' },
  foldedHeading: { role: 'heading', 'en-US': 'The folded cube', 'es-MX': 'El cubo doblado', 'pt-BR': 'O cubo dobrado' },
  foldedView: { role: 'data', 'en-US': 'The cube so far, seen from {side}', 'es-MX': 'El cubo hasta ahora, visto {side}', 'pt-BR': 'O cubo até agora, visto {side}' },
  sideFrontRight: { role: 'data', 'en-US': 'the front right', 'es-MX': 'desde el frente a la derecha', 'pt-BR': 'da frente à direita' },
  sideBackLeft: { role: 'data', 'en-US': 'the back left', 'es-MX': 'desde atrás a la izquierda', 'pt-BR': 'de trás à esquerda' },
  pairsNote: { role: 'body', 'en-US': 'Same color means opposite faces.', 'es-MX': 'El mismo color indica caras opuestas.', 'pt-BR': 'A mesma cor indica faces opostas.' },
  squaresHeading: { role: 'heading', 'en-US': 'Squares to add', 'es-MX': 'Cuadrados para agregar', 'pt-BR': 'Quadrados para adicionar' },
  addSquare: { role: 'option', 'en-US': 'Add a square', 'es-MX': 'Agrega un cuadrado', 'pt-BR': 'Adicione um quadrado' },
  placeSquareHint: { role: 'body', 'en-US': 'Pick a square, then tap the grid.', 'es-MX': 'Elige un cuadrado y toca la cuadrícula.', 'pt-BR': 'Escolha um quadrado e toque na grade.' },
  metNetComplete: { role: 'body', 'en-US': 'You built a net that folds into a cube.', 'es-MX': 'Armaste una plantilla que forma un cubo.', 'pt-BR': 'Você montou uma planificação que forma um cubo.' },
  hintNetComplete: { role: 'body', 'en-US': 'Not yet. Check which squares would overlap.', 'es-MX': 'Aún no. Revisa qué cuadrados se encimarían.', 'pt-BR': 'Ainda não. Veja quais quadrados se sobreporiam.' },

  stackHeading: { role: 'heading', 'en-US': 'Your stack', 'es-MX': 'Tu pila', 'pt-BR': 'Sua pilha' },
  stackName: { role: 'data', 'en-US': 'Stack of cubes', 'es-MX': 'Pila de cubos', 'pt-BR': 'Pilha de cubos' },
  stackCell: { role: 'data', 'en-US': 'Column {c}, row {r}: height {n}', 'es-MX': 'Columna {c}, fila {r}: altura {n}', 'pt-BR': 'Coluna {c}, linha {r}: altura {n}' },
  cellName: { role: 'data', 'en-US': 'Column {c}, row {r}', 'es-MX': 'Columna {c}, fila {r}', 'pt-BR': 'Coluna {c}, linha {r}' },
  stackHint: { role: 'body', 'en-US': 'Tap a cell to add a cube. After three, it clears.', 'es-MX': 'Toca una celda para agregar un cubo. Después de tres, se vacía.', 'pt-BR': 'Toque em uma célula para adicionar um cubo. Depois de três, ela esvazia.' },
  gridNote: { role: 'body', 'en-US': 'Row 1 is at the back. Column 1 is on the left.', 'es-MX': 'La fila 1 está atrás. La columna 1 está a la izquierda.', 'pt-BR': 'A linha 1 fica atrás. A coluna 1 fica à esquerda.' },
  addCube: { role: 'option', 'en-US': 'Add a cube', 'es-MX': 'Agrega un cubo', 'pt-BR': 'Adicione um cubo' },
  cubesTotal: { role: 'data', 'en-US': 'Cubes: {n}', 'es-MX': 'Cubos: {n}', 'pt-BR': 'Cubos: {n}' },
  viewsHeading: { role: 'heading', 'en-US': 'Views of your stack', 'es-MX': 'Vistas de tu pila', 'pt-BR': 'Vistas da sua pilha' },
  viewPlan: { role: 'data', 'en-US': 'From above', 'es-MX': 'Desde arriba', 'pt-BR': 'De cima' },
  viewFront: { role: 'data', 'en-US': 'From the front', 'es-MX': 'De frente', 'pt-BR': 'De frente' },
  viewSide: { role: 'data', 'en-US': 'From the right side', 'es-MX': 'Desde el lado derecho', 'pt-BR': 'Do lado direito' },
  viewLine: { role: 'data', 'en-US': '{view}: {state}', 'es-MX': '{view}: {state}', 'pt-BR': '{view}: {state}' },
  viewSame: { role: 'data', 'en-US': 'same as the goal', 'es-MX': 'igual que la meta', 'pt-BR': 'igual à meta' },
  viewDifferent: { role: 'data', 'en-US': 'not the same yet', 'es-MX': 'aún no es igual', 'pt-BR': 'ainda não é igual' },
  stackCaption: { role: 'heading', 'en-US': 'Cubes in each cell', 'es-MX': 'Cubos en cada celda', 'pt-BR': 'Cubos em cada célula' },
  rowN: { role: 'data', 'en-US': 'Row {r}', 'es-MX': 'Fila {r}', 'pt-BR': 'Linha {r}' },
  viewsCaption: { role: 'heading', 'en-US': 'Your views and the goal', 'es-MX': 'Tus vistas y la meta', 'pt-BR': 'Suas vistas e a meta' },
  colView: { role: 'data', 'en-US': 'View', 'es-MX': 'Vista', 'pt-BR': 'Vista' },
  colYours: { role: 'data', 'en-US': 'Yours', 'es-MX': 'Tuya', 'pt-BR': 'Sua' },
  colGoal: { role: 'data', 'en-US': 'Goal', 'es-MX': 'Meta', 'pt-BR': 'Meta' },
  colMatch: { role: 'data', 'en-US': 'Same', 'es-MX': 'Igual', 'pt-BR': 'Igual' },
  yes: { role: 'data', 'en-US': 'Yes', 'es-MX': 'Sí', 'pt-BR': 'Sim' },
  no: { role: 'data', 'en-US': 'No', 'es-MX': 'No', 'pt-BR': 'Não' },
  filled: { role: 'data', 'en-US': 'filled', 'es-MX': 'llena', 'pt-BR': 'cheia' },
  empty: { role: 'data', 'en-US': 'empty', 'es-MX': 'vacía', 'pt-BR': 'vazia' },
  diagramLabel: { role: 'data', 'en-US': '{view}, {who}: {values}', 'es-MX': '{view}, {who}: {values}', 'pt-BR': '{view}, {who}: {values}' },
  metStack: { role: 'body', 'en-US': 'Your stack matches every view.', 'es-MX': 'Tu pila coincide con todas las vistas.', 'pt-BR': 'Sua pilha corresponde a todas as vistas.' },
  metStackFewest: { role: 'body', 'en-US': 'Your stack matches with the fewest cubes.', 'es-MX': 'Tu pila coincide con la menor cantidad de cubos.', 'pt-BR': 'Sua pilha corresponde com o menor número de cubos.' },
  hintStack: { role: 'body', 'en-US': 'Not yet. Compare each view with the goal.', 'es-MX': 'Aún no. Compara cada vista con la meta.', 'pt-BR': 'Ainda não. Compare cada vista com a meta.' },
  hintStackFewest: { role: 'body', 'en-US': 'Not yet. Match every view, using the fewest cubes.', 'es-MX': 'Aún no. Iguala cada vista con la menor cantidad de cubos.', 'pt-BR': 'Ainda não. Iguale cada vista com o menor número de cubos.' },

  solidBox: { role: 'option', 'en-US': 'Box', 'es-MX': 'Caja', 'pt-BR': 'Caixa' },
  faceSlope: { role: 'option', 'en-US': 'Slope', 'es-MX': 'Rampa', 'pt-BR': 'Rampa' },
  netLabel: { role: 'data', 'en-US': 'Net: {solid}', 'es-MX': 'Plantilla: {solid}', 'pt-BR': 'Planificação: {solid}' },
  panelN: { role: 'data', 'en-US': 'Panel {n}', 'es-MX': 'Pieza {n}', 'pt-BR': 'Peça {n}' },
  colPanel: { role: 'data', 'en-US': 'Panel', 'es-MX': 'Pieza', 'pt-BR': 'Peça' },
  colShape: { role: 'data', 'en-US': 'Shape', 'es-MX': 'Forma', 'pt-BR': 'Forma' },
  colLengths: { role: 'data', 'en-US': 'Lengths', 'es-MX': 'Medidas', 'pt-BR': 'Medidas' },
  shapeRect: { role: 'data', 'en-US': 'Rectangle', 'es-MX': 'Rectángulo', 'pt-BR': 'Retângulo' },
  shapeSquare: { role: 'data', 'en-US': 'Square', 'es-MX': 'Cuadrado', 'pt-BR': 'Quadrado' },
  shapeRight: { role: 'data', 'en-US': 'Right triangle', 'es-MX': 'Triángulo rectángulo', 'pt-BR': 'Triângulo retângulo' },
  shapeTriangle: { role: 'data', 'en-US': 'Triangle', 'es-MX': 'Triángulo', 'pt-BR': 'Triângulo' },
  lengthsRect: { role: 'data', 'en-US': '{a} by {b}', 'es-MX': '{a} por {b}', 'pt-BR': '{a} por {b}' },
  lengthsRight: { role: 'data', 'en-US': 'legs {a} and {b}', 'es-MX': 'catetos {a} y {b}', 'pt-BR': 'catetos {a} e {b}' },
  lengthsTriangle: { role: 'data', 'en-US': 'base {a}, height {b}', 'es-MX': 'base {a}, altura {b}', 'pt-BR': 'base {a}, altura {b}' },

  foldHeading: { role: 'heading', 'en-US': 'Fold the net', 'es-MX': 'Dobla la plantilla', 'pt-BR': 'Dobre a planificação' },
  fold: { role: 'action', 'en-US': 'Fold', 'es-MX': 'Doblar', 'pt-BR': 'Dobrar' },
  unfold: { role: 'action', 'en-US': 'Unfold', 'es-MX': 'Desdoblar', 'pt-BR': 'Desdobrar' },
  foldSlider: { role: 'body', 'en-US': 'How far the net is folded', 'es-MX': 'Cuánto se dobló la plantilla', 'pt-BR': 'Quanto a planificação dobrou' },
  foldFlat: { role: 'data', 'en-US': 'Flat', 'es-MX': 'Plana', 'pt-BR': 'Plana' },
  foldClosed: { role: 'data', 'en-US': 'Folded up', 'es-MX': 'Doblada', 'pt-BR': 'Dobrada' },
  foldPart: { role: 'data', 'en-US': 'Folded {n} of {total}', 'es-MX': 'Doblada {n} de {total}', 'pt-BR': 'Dobrada {n} de {total}' },

  namedOf: { role: 'data', 'en-US': 'Named: {n} of {total}', 'es-MX': 'Nombradas: {n} de {total}', 'pt-BR': 'Nomeadas: {n} de {total}' },
  placePanelHint: { role: 'body', 'en-US': 'Pick a name, then tap a panel.', 'es-MX': 'Elige un nombre y toca una pieza.', 'pt-BR': 'Escolha um nome e toque em uma peça.' },
  labelCaption: { role: 'heading', 'en-US': 'Panels and names', 'es-MX': 'Piezas y nombres', 'pt-BR': 'Peças e nomes' },
  metSolidLabel: { role: 'body', 'en-US': 'You named every face of the solid.', 'es-MX': 'Nombraste todas las caras del cuerpo.', 'pt-BR': 'Você nomeou todas as faces do sólido.' },
  hintSolidLabel: {
    role: 'body',
    'en-US': 'Not yet. Match each panel with its lengths.',
    'es-MX': 'Aún no. Relaciona cada pieza con sus medidas.',
    'pt-BR': 'Ainda não. Relacione cada peça com suas medidas.',
  },

  joinHeading: { role: 'heading', 'en-US': 'Faces to join', 'es-MX': 'Caras para unir', 'pt-BR': 'Faces para unir' },
  joinHint: { role: 'body', 'en-US': 'Pick a face, then tap an edge.', 'es-MX': 'Elige una cara y toca un borde.', 'pt-BR': 'Escolha uma face e toque em uma borda.' },
  joinTo: { role: 'data', 'en-US': 'Edge with {parent}', 'es-MX': 'Borde con {parent}', 'pt-BR': 'Borda com {parent}' },
  joinedOf: { role: 'data', 'en-US': 'Faces joined: {n} of {total}', 'es-MX': 'Caras unidas: {n} de {total}', 'pt-BR': 'Faces unidas: {n} de {total}' },
  sheetFits: { role: 'data', 'en-US': 'The net fits the sheet.', 'es-MX': 'La plantilla cabe en la hoja.', 'pt-BR': 'A planificação cabe na folha.' },
  sheetTooBig: { role: 'data', 'en-US': 'The net is too big for the sheet.', 'es-MX': 'La plantilla es muy grande para la hoja.', 'pt-BR': 'A planificação é grande demais para a folha.' },
  sheetSize: { role: 'data', 'en-US': 'Sheet: {w} by {h}', 'es-MX': 'Hoja: {w} por {h}', 'pt-BR': 'Folha: {w} por {h}' },
  netSize: { role: 'data', 'en-US': 'Your net: {w} by {h}', 'es-MX': 'Tu plantilla: {w} por {h}', 'pt-BR': 'Sua planificação: {w} por {h}' },
  joinCaption: { role: 'heading', 'en-US': 'Faces of the net', 'es-MX': 'Caras de la plantilla', 'pt-BR': 'Faces da planificação' },
  colFace: { role: 'data', 'en-US': 'Face', 'es-MX': 'Cara', 'pt-BR': 'Face' },
  colJoined: { role: 'data', 'en-US': 'Joined to', 'es-MX': 'Unida a', 'pt-BR': 'Unida a' },
  firstFace: { role: 'data', 'en-US': 'first face', 'es-MX': 'primera cara', 'pt-BR': 'primeira face' },
  notJoined: { role: 'data', 'en-US': 'not joined', 'es-MX': 'sin unir', 'pt-BR': 'sem unir' },
  metSolidComplete: { role: 'body', 'en-US': 'You built a net that folds up.', 'es-MX': 'Armaste una plantilla que se dobla.', 'pt-BR': 'Você montou uma planificação que dobra.' },
  hintSolidComplete: {
    role: 'body',
    'en-US': 'Not yet. Check that faces touch and fit the sheet.',
    'es-MX': 'Aún no. Revisa que las caras se toquen y quepan en la hoja.',
    'pt-BR': 'Ainda não. Veja se as faces se tocam e cabem na folha.',
  },

  areaCaption: { role: 'heading', 'en-US': 'Panels and lengths', 'es-MX': 'Piezas y medidas', 'pt-BR': 'Peças e medidas' },
  areaAsk: { role: 'body', 'en-US': 'Total area of all the faces', 'es-MX': 'Área total de todas las caras', 'pt-BR': 'Área total de todas as faces' },
  metArea: { role: 'body', 'en-US': 'You added the area of every face.', 'es-MX': 'Sumaste el área de cada cara.', 'pt-BR': 'Você somou a área de cada face.' },
  hintArea: { role: 'body', 'en-US': 'Not yet. Find each area, then add them.', 'es-MX': 'Aún no. Halla cada área y suma.', 'pt-BR': 'Ainda não. Ache cada área e some.' },
} as const satisfies HorizonteCopy;
